### ISSUE TITLE
Firewall always redeploys although present in the terraform state.

### ISSUE THREAD

**Issue by gro1m** [terraform-providers/terraform-provider-azurerm#9054] opened 2020-10-28 14:44 UTC
Although the firewall is stored in the Terraform state, the Azure Firewall is destroyed and recreated in every deployment totalling in around 20 minutes for deploying the firewall infrastructure. Our team looked into it, but we could not detect any issues and we do not have it with any other resources. Can someone confirm? Thank you!

**Comment by tombuildsstuff** [comment] 2020-10-28 14:47
hi @gro1m 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-10-28 14:47 UTC

**Comment by gro1m** [comment] 2020-10-28 21:44
Hi @tombuildsstuff 

I understand your concerns here, but in my opinion this is a bug. The main difficulty here is how to provide a sensible MWE, because that may need a terraform state file, where I might need to remove sensitive data. And as the firewall is a time-consuming and costly resource to just build it for fun. Of course, it is also asking a lot for someone else to do this, but I see that this would probably be an unavoidable step to reproduce/resolve the issue. Furthermore, the question is not that broad in that it concerns very directly the Firewall Azure resource (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall) and asks why redeploying without changing the state leads to destruction and rebuilding of the firewall.

Still, to follow your suggestion: 
1) Do you think that https://discuss.hashicorp.com/c/terraform-providers/31 provides the appropriate forum to discuss this? 
2) What kind of information would you need to reproduce the issue. Would it be sufficient to provide the terraform state and the example provided on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall?

Thank you for your effort!

**Comment by tombuildsstuff** [comment] 2020-10-29 06:38
@gro1m if your modifying the statefile to remove information then Terraform will detect changes to those fields - that's by design and is not a bug.

Sure, the Discuss forums are available for further assistance - however as this appears to be a Terraform usage question I'd suggest filing a Terraform question specifically: https://discuss.hashicorp.com/c/terraform-core/27

Thanks!

**Comment by gro1m** [comment] 2020-10-29 12:21
@tombuildsstuff Thanks for your response. There is a slight misunderstanding: I did not mean that I change the terraform state file, but the state file might contain sensitive information, that I do not want to upload to a public forum. No, the problem is that the state of the firewall is not changed, but there is just a redeployment of infrastructure without changing the terraform code and this still rebuilds the firewall. And we work with Azure, so I do not know if other providers have this problem.
