### ISSUE TITLE
azurerm_key_vault_certificate_data: pkcs12: expected exactly two safe bags in the PFX PDU

### ISSUE THREAD

**Issue by calebak404** [terraform-providers/terraform-provider-azurerm#11298] opened 2021-04-12 21:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0

### Affected Resource(s)

* `azurerm_key_vault_certificate_data`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_certificate_data" "keyvault_certificate_data" {
  key_vault_id = var.key_vault_resource_id
  name = var.certificate_name
}
```

### Debug Output

Error: decoding certificate ("CERTIFICATE-NAME"): pkcs12: expected exactly two safe bags in the PFX PDU

### Expected Behaviour

plan should have completed with no issues

### Actual Behaviour

plan failed with unexpected error

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Certificates used here are generated by a 3rd party module and stored in the Azure keyvault.  The generated certificates include their full trust chain.  I believe this error is occurring because the `Decode` function only supports a single certificate and key and does not properly handle the trust chain being present.

**Comment by patpicos** [comment] 2021-04-20 19:01
Same issue for me. I also have the full trust chain in the cert.
```
Error: decoding certificate ("nginx-cert"): pkcs12: expected exactly two safe bags in the PFX PDU

  on main.tf line 8, in data "azurerm_key_vault_certificate_data" "cert":
   8: data "azurerm_key_vault_certificate_data" "cert" {
```

**Comment by a-sinkavets** [comment] 2021-05-20 07:14
Looks like that's duplicate of #10909

**Comment by favoretti** [comment] 2021-05-26 16:23
Hey, thanks for reporting, it's indeed a dupe of #10909, so I'll close this one and welcome everyone to subscribe to the other issue to keep the discussion concise.

**Closed by favoretti** 2021-05-26 16:23 UTC
Labels: enhancement, service/keyvault
