### ISSUE TITLE
Support for Azure AD Domain Services

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#12346] opened 2021-06-24 10:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now Azure AD Domain Services can only be deployed using the Portal or an ARM template. It can only be configured after deployment through the portal.

### New or Affected Resource(s)

* azurerm_domain_services

### Potential Terraform Configuration

```hcl
resource "azurerm_domain_services" "aadds" {
  domain_name = "foobar.onmicrosoft.com"
  location = "West US"
  filtered_sync = "FullySynced"
  
  sku = "Standard"

  subnet_id = azurerm_subnet.aadds_subnet.id

  notification_settings {
     notify_global_admins = true
     notify_dc_admins = true
     additional_recipients = [ "foo@bar.com" ]
  }

  domain_security_settings {
     tls_v1 = true
     ntlm_v1 = true
     sync_ntlm_passwords = true
     sync_onprem_passwords = true
     kerberos_rc4_encryption = true
     kerberos_armoring = true
  }

}
```

### References

* https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-create-instance

**Comment by tombuildsstuff** [comment] 2021-06-24 11:52
hi @markti 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #8970 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8970 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-06-24 11:52 UTC
Labels: duplicate, new-resource, service/domain-services
