### ISSUE TITLE
Support for hard deletion in Azure LogAnalytics workspace

### ISSUE THREAD

**Issue by aarroyoc** [terraform-providers/terraform-provider-azurerm#7297] opened 2020-06-11 11:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

An Azure LogAnalytics workspace is soft-deleted by default, which may cause problems in development because of name collisions.

Azure has a hard-delete option in the REST API: https://docs.microsoft.com/bs-cyrl-ba/azure/azure-monitor/platform/delete-workspace?view=azurestackps-1.3.0#permanent-workspace-delete.

My proposal is to add a force_delete flag to force delete when destroying the resource.

### New or Affected Resource(s)

* azurerm_log_analytics_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  force_delete = true
}
```

**Comment by tombuildsstuff** [comment] 2020-06-11 12:44
hi @aarroyoc 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7282 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7282 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-11 12:44 UTC
Labels: duplicate, enhancement, service/log-analytics

**Comment by aarroyoc** [comment] 2020-06-11 13:48
Sure!
