### ISSUE TITLE
Feature Request: Support Storage Account Firewall and Network Rules

### ISSUE THREAD

**Issue by HighwayofLife** [terraform-providers/terraform-provider-azurerm#1110] opened 2018-04-10 21:12 UTC
Feature Request: Add support for Storage Account Firewall and Network Rules.

### Affected Resource(s)

- azurerm_storage_account
- azurerm_subnet

Subnets need to be able to create service endpoints. (see below ARM snippet)

### References

* **[Announcement: Virtual Network Integration for Azure Storage and Azure SQL](https://azure.microsoft.com/en-us/blog/announcing-virtual-network-integration-for-azure-storage-and-azure-sql/)**
* **[Configure Storage Network Security](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security)**
* **[Virtual Network Service Endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview)**

### ARM Template snippet - Storage
```json
"kind": "Storage",
"name": "[parameters('storageAccounts_devworkdiag410_name')]",
"apiVersion": "2017-10-01",
"location": "eastus2",
"tags": {},
"scale": null,
"properties": {
    "networkAcls": {
        "bypass": "AzureServices",
        "virtualNetworkRules": [
            {
                "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('virtualNetworks_DevWork_vnet_name'), parameters('subnets_default_name'))]",
                "action": "Allow",
                "state": "Succeeded"
            }
        ],
        "ipRules": [],
        "defaultAction": "Deny"
    },
```

### ARM Template snippet - Subnet
```json
"type": "Microsoft.Network/virtualNetworks/subnets",
"name": "[concat(parameters('virtualNetworks_DevWork_vnet_name'), '/', parameters('subnets_default_name'))]",
"apiVersion": "2018-01-01",
"scale": null,
"properties": {
    "provisioningState": "Succeeded",
    "addressPrefix": "10.0.0.0/24",
    "serviceEndpoints": [
        {
            "provisioningState": "Succeeded",
            "service": "Microsoft.Storage",
            "locations": [
                "eastus2",
                "centralus"
            ]
        }
    ]
}
```

**Comment by tombuildsstuff** [comment] 2018-04-11 08:33
hey @HighwayofLife 

Thanks for opening this issue

Support for this functionality has been previously requested in #1110 - rather than having multiple issues tracking the same thing I'm going to close this issue in favour of that one.

Thanks!

**Closed by tombuildsstuff** 2018-04-11 08:33 UTC
Labels: service/storage

**Comment by hafizullah** [comment] 2018-04-13 09:44
Hi @tombuildsstuff the link you have provided to the previously requested functionality references this issue. Could you please update the link so we can track that issue?

**Comment by tombuildsstuff** [comment] 2018-04-13 10:34
@hafizullah @HighwayofLife apologies for the incorrect issue number - this is duplicate of #416

**Comment by HighwayofLife** [comment] 2018-04-14 16:30
Ok, thanks... although that ticket doesn't contain any useful information. I'll copy it over there.

**Comment by xelor81** [comment] 2018-06-25 10:07
Can someone print a small sippet how to use this this feature in tf file please?
I am completely green in reading go lang code but I have a big need to implement this in my tf plans.
