### ISSUE TITLE
Getting "Access is denied"

### ISSUE THREAD

**Issue by dwtuts** [terraform-providers/terraform-provider-azurerm#4871] opened 2019-11-13 20:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.13
+ provider.azurerm v1.36.1
```

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
# Create an App Service Plan with Windows
resource "azurerm_app_service_plan" "appserviceplan" {
  name                = "${var.rg-name}-plan"
  location            = "westus"
  resource_group_name = var.rg-name

  # Define Windows as Host OS
  kind                = "xenon"
  is_xenon            = true

  # Choose size
  sku {
    tier = "PremiumContainer"
    size = "PC2"
  }
}

# Create an Azure Web App for Containers in that App Service Plan
resource "azurerm_app_service" "dockerapp" {
  name                = "${var.rg-name}-dockerapp"
  location            = "westus"
  resource_group_name = "${var.rg-name}"
  app_service_plan_id = "${azurerm_app_service_plan.appserviceplan.id}"
  

  # Configure Docker Image to load on start
  site_config {
    windows_fx_version = "DOCKER|apps.azurecr.io/engine/engine:latest"
  }
  app_settings = {

    # Settings for private Container Registires  
    DOCKER_REGISTRY_SERVER_URL      = "https://apps.azurecr.io",
    DOCKER_REGISTRY_SERVER_USERNAME = "apps",
    DOCKER_REGISTRY_SERVER_PASSWORD = "super secret password"

  }

}
```

### Debug Output

[Gist](https://gist.github.com/dwtuts/ea6e53e68d50b350aaec193719fd4ce3)

### Expected Behavior

App Service Plan should be deployed along with Container Web App

### Actual Behavior

App Service Plan is getting deployed but the Container Web App fails due to "Access is denied"

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

I was able to get the container web app to deploy if I use a public image from Microsoft instead of a private ACR image. 

### References

* #4635

**Comment by tracypholmes** [comment] 2019-11-14 23:20
Thanks for submitting this issue @dwtuts! I believe this is a duplicate of #4635.  As such I'm going to close this issue for now. But if you feel this is in error, feel free to let us know 😄

**Closed by tracypholmes** 2019-11-14 23:20 UTC
Labels: bug, duplicate, service/app-service
