### ISSUE TITLE
Error: Provider produced inconsistent result after apply azurem

### ISSUE THREAD

**Issue by Thibaultce** [terraform-providers/terraform-provider-azurerm#12078] opened 2021-06-06 16:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_role_assignment`

```
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.62.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "managed_identity_storage_assignment" {
  name               = uuid()
  scope              = var.storage_account_id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id       = var.webapp_identity
}
```

### Panic Output

none

### Expected Behaviour

works

### Actual Behaviour

```
Error: Provider produced inconsistent result after apply
When applying changes to module.storage_account_permissions.azurerm_role_assignment.managed_identity_storage_assignment, provider
"provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

Running plan from local or Azure DevOps workspace.

**Comment by aristosvo** [comment] 2021-06-07 10:44
@Thibaultce Thanks for submitting!

I think this is a duplicate of #12057.

**Closed** 2021-06-08 16:17 UTC
