### ISSUE TITLE
Apply fails because recently created resource group returns 404

### ISSUE THREAD

**Issue by lelandsindttouchnet** [terraform-providers/terraform-provider-azurerm#4682] opened 2019-10-22 14:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.12
+ provider.azurerm v1.35.0
```

### Affected Resource(s)

* `azurerm_resource_group`
* `azurerm_api_management`

### Terraform Configuration Files

```hcl
variable "resource_group" {
  type = string
  description = "Name of the Azure Resource Group"
  default = "issue1"
}

variable "resource_location" {
  type = string
  description = "Location of the Azure Resources"
  default = "eastus"
}

variable "api_name" {
  type = string
  description = "Name of the Azure API Resource"
  default = "issue1"
}

resource "azurerm_resource_group" "main" {
  name     = var.resource_group
  location = var.resource_location
}

resource "azurerm_api_management" "main" {
  name                = var.api_name
  location            = var.resource_location
  resource_group_name = var.resource_group
  publisher_name      = "I have issues"
  publisher_email     = "nobody@azure.com"
  sku_name = "Developer_1"
}
```

### Debug Output

https://gist.github.com/lelandsindttouchnet/af56ab76cb996d666ff9050d79265f57

### Standard Output 

```
$ terraform apply --auto-approve
azurerm_resource_group.main: Creating...
azurerm_api_management.main: Creating...
azurerm_resource_group.main: Creation complete after 2s [id=/subscriptions/SUBSCRIPTION_ID/resourceGroups/issue1]

Error: Error creating/updating API Management Service "issue1" (Resource Group "issue1"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'issue1' could not be found."

  on main.tf line 25, in resource "azurerm_api_management" "main":
  25: resource "azurerm_api_management" "main" {
```

### Expected Behavior

Creation of the API resource retry rather than fail/quit.

### Actual Behavior

404 on the resource group causes the API resource to fail.

### Steps to Reproduce

1. `terraform apply --auto-approve`

### Important Factoids

9 times out of 10 I see a failure.

**Comment by taliesins** [comment] 2019-11-07 06:57
I have flickering integration tests that I think are caused by this same issue.

What is really wierd is that I get log lines like this:
`Creation complete after 3s [id=/subscriptions/c64025d2-f603-4eb1-b4bf-8401deed99a3/resourceGroups/shared-services-azure-monitor-rg-WCcyF7]`

followed by:
`operationalinsights.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'shared-services-log-analytics-rg-KsHWCa' could not be found."`


Here is the code to reproduce the problem. I am running a few integration tests in parallel and they all seem to intermittently fail in a similar way. I just picked cleanest test to demonstrate the problem.

main.tf
```
resource "azurerm_resource_group" "shared_services_log_analytics" {
  provider = "azurerm"
  name     = "${var.shared_services_log_analytics_resource_group_name}"
  location = "${var.shared_services_log_analytics_primary_location}"
}

# Set up log analytics workspace for logging resource diagnostics and activity
resource "azurerm_log_analytics_workspace" "shared_services_log_analytics_workspace" {
  provider            = "azurerm"
  name                = "${var.shared_services_log_analytics_workspace_name}"
  location            = "${var.shared_services_log_analytics_primary_location}"
  resource_group_name = "${azurerm_resource_group.shared_services_log_analytics.name}"
  sku                 = "${var.shared_services_log_analytics_workspace_sku}"
  retention_in_days   = "${var.shared_services_log_analytics_workspace_retention_period}"
}

output "log_analytics_workspace_id" {
  value = "${azurerm_log_analytics_workspace.shared_services_log_analytics_workspace.workspace_id}"
}
```

Snippet from our test code (Terratest) that calls Terraform

```
func TestIT_LogAnalytics(t *testing.T) {
	t.Parallel()

	// Parameters
	uniqueID := random.UniqueId()

	shared_services_log_analytics_resource_group_name := "shared-services-log-analytics-rg-" + uniqueID
	shared_services_log_analytics_workspace_name := "shared-services-log-analytics-workspace-" + uniqueID
	shared_services_log_analytics_primary_location := "uksouth"

	// Configurations
	tfOptions := &terraform.Options{
		TerraformDir: "../examples/log_analytics",
		Vars: map[string]interface{}{
			"shared_services_log_analytics_resource_group_name": shared_services_log_analytics_resource_group_name,
			"shared_services_log_analytics_workspace_name":      shared_services_log_analytics_workspace_name,
			"shared_services_log_analytics_primary_location":    shared_services_log_analytics_primary_location,
		},
	}

	// Init, Apply & finally Destroy
	defer terraform.Destroy(t, tfOptions)
	terraform.InitAndApply(t, tfOptions)

	// Get the created log analytics workspace ID, service principal ID and application registration password
	// from the output after resource creation.
	// These vars are required to form the log analytics API query URL later in the test
	outputOptions := &terraform.Options{
		TerraformDir: "../examples/log_analytics",
	}

```


Test output:

```
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z retry.go:72: terraform [init -upgrade=false]
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z command.go:53: Running command terraform with args [init -upgrade=false]
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z command.go:121: [0m[1mInitializing the backend...[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z command.go:121: [0m[1mInitializing provider plugins...[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:01Z command.go:121: - Checking for available provider plugins...
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: - Downloading plugin for provider "azurerm" (hashicorp/azurerm) 1.36.1...
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: The following providers do not have any version constraints in configuration,
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: so the latest version was installed.
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: To prevent automatic upgrades to new major versions that may contain breaking
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: changes, it is recommended to add version = "..." constraints to the
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: corresponding provider blocks in configuration, with the constraint strings
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: suggested below.
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: * provider.azurerm: version = "~> 1.36"
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:121: [0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z retry.go:72: terraform [get -update]
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:53: Running command terraform with args [get -update]
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z retry.go:72: terraform [apply -input=false -lock=false -auto-approve -var shared_services_log_analytics_primary_location=uksouth -var shared_services_log_analytics_resource_group_name=shared-services-log-analytics-rg-KsHWCa -var shared_services_log_analytics_workspace_name=shared-services-log-analytics-workspace-KsHWCa]
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:03Z command.go:53: Running command terraform with args [apply -input=false -lock=false -auto-approve -var shared_services_log_analytics_primary_location=uksouth -var shared_services_log_analytics_resource_group_name=shared-services-log-analytics-rg-KsHWCa -var shared_services_log_analytics_workspace_name=shared-services-log-analytics-workspace-KsHWCa]
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:10Z command.go:121: [0m[1mdata.azurerm_client_config.current: Refreshing state...[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:21Z command.go:121: [0m[1mazurerm_resource_group.shared_services_log_analytics: Creating...[0m[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:24Z command.go:121: [0m[1mazurerm_resource_group.shared_services_log_analytics: Creation complete after 3s [id=/subscriptions/c64025d2-f603-4eb1-b4bf-8401deed99a3/resourceGroups/shared-services-log-analytics-rg-KsHWCa][0m[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:24Z command.go:121: [0m[1mazurerm_log_analytics_workspace.shared_services_log_analytics_workspace: Creating...[0m[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121: [31m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121: [1m[31mError: [0m[0m[1moperationalinsights.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'shared-services-log-analytics-rg-KsHWCa' could not be found."[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121: 
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121: [0m  on main.tf line 10, in resource "azurerm_log_analytics_workspace" "shared_services_log_analytics_workspace":
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121:   10: resource "azurerm_log_analytics_workspace" "shared_services_log_analytics_workspace" [4m{[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121: [0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z command.go:121: [0m[0m
01:22:04  TestIT_LogAnalytics 2019-11-07T01:18:25Z retry.go:80: Returning due to fatal error: FatalError{Underlying: exit status 1}
```

 I am almost of the opinion that Azure has made a recent change on their side that is cause the problem: perhaps some kind of caching optimization on their side.

I don't think its Terraform AzureRm bug looking at the code as when the group is created its immediately read.

CreateOrUpdate Entity for resource group:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_resource_group.go#L74

Immediately followed by read entity on resource group:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_resource_group.go#L78

I then though it might by the go sdk client doing some dodgy caching. But nothing obvious popped out:

CreateOrUpdate resource group
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2018-05-01/resources/groups.go#L132

Get resource group
https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2018-05-01/resources/groups.go#L391

**Comment by tombuildsstuff** [comment] 2019-11-07 07:59
hi @lelandsindttouchnet 

Thanks for opening this issue.

Taking a look at the configuration posted above it appears there's no dependency between the Resource Group and the API Management - as such Terraform believes it can create them in parallel. To fix this you should be able to chain them using an Implicit Dependency - for example:

```
resource "azurerm_resource_group" "main" {
  name     = var.resource_group
  location = var.resource_location
}

resource "azurerm_api_management" "main" {
  name                = var.api_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  publisher_name      = "I have issues"
  publisher_email     = "nobody@azure.com"
  sku_name = "Developer_1"
}
```

Would you be able to take a look and see if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Closed by tombuildsstuff** 2019-11-07 07:59 UTC

**Comment by lelandsindttouchnet** [comment] 2019-11-07 19:48
@tombuildsstuff 

... you mean like all my other (working without issue) manifests are configured? 

Thank you.

**Comment by sangeethaguhan** [comment] 2020-03-04 01:34
> hi @lelandsindttouchnet
> 
> Thanks for opening this issue.
> 
> Taking a look at the configuration posted above it appears there's no dependency between the Resource Group and the API Management - as such Terraform believes it can create them in parallel. To fix this you should be able to chain them using an Implicit Dependency - for example:
> 
> ```
> resource "azurerm_resource_group" "main" {
>   name     = var.resource_group
>   location = var.resource_location
> }
> 
> resource "azurerm_api_management" "main" {
>   name                = var.api_name
>   location            = azurerm_resource_group.main.location
>   resource_group_name = azurerm_resource_group.main.name
>   publisher_name      = "I have issues"
>   publisher_email     = "nobody@azure.com"
>   sku_name = "Developer_1"
> }
> ```
> 
> Would you be able to take a look and see if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look :)
> 
> Thanks!

This didn't quite really solve the issue.  can you suggest another workaround please?
