### ISSUE TITLE
Support pre-flight validation based on ARM what-if

### ISSUE THREAD

**Issue by fawohlsc** [terraform-providers/terraform-provider-azurerm#10191] opened 2021-01-14 15:57 UTC
### Description

`terraform plan` should include [ARM What-If Operation ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-deploy-what-if?tabs=azure-powershell) in the preflight-check. This way also Azure Policy are considered as well.

### New or Affected Resource(s)

Proposed change to terraform CLI not resources.

### Potential Terraform Configuration

No potential Terraform configuration. 

### References
[ARM template deployment what-if operation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-deploy-what-if?tabs=azure-powershell)

**Comment by ruandersMSFT** [comment] 2021-01-14 18:10
Duplicate to issue #9907.  ARM What-If needs to be incorporated into AzureRM Resource _azurerm_resource_group_template_deployment_.

**Comment by tombuildsstuff** [comment] 2021-01-15 06:51
hi @fawohlsc 

Thanks for opening this issue :)

As @ruandersMSFT has menioned this appears to be a duplicate of #9907 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9907 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-15 06:51 UTC

**Comment by fawohlsc** [comment] 2021-01-15 13:04
@tombuildsstuff & @ruandersMSFT: Thank you . Agree this issue to be a duplicate and will subscribe to #9907.
