### ISSUE TITLE
Default_ttl_seconds is always replaced in azurerm_cosmosdb_mongo_collection

### ISSUE THREAD

**Issue by Petr-Liska** [terraform-providers/terraform-provider-azurerm#8242] opened 2020-08-25 08:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `terraform v0.13.0`
* `azurerm v2.24.0`

### Affected Resource(s)

* `azurerm_cosmosdb_mongo_collection`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "2.24.0"
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "test_rg"
  location = "West Europe"
}

resource "azurerm_cosmosdb_account" "example" {
  name                = "test-cosmos-db-account"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  offer_type          = "Standard"
  kind                = "MongoDB"
  consistency_policy {
    consistency_level       = "Session"
  }
  geo_location {
      failover_priority = 0
      location = azurerm_resource_group.example.location
  }
}

resource "azurerm_cosmosdb_mongo_database" "example" {
  name                = "test-cosmos-mongo-db"
  resource_group_name = azurerm_cosmosdb_account.example.resource_group_name
  account_name        = azurerm_cosmosdb_account.example.name
}

resource "azurerm_cosmosdb_mongo_collection" "example" {
  name                = "test-cosmos-mongo-db"
  resource_group_name = azurerm_cosmosdb_account.example.resource_group_name
  account_name        = azurerm_cosmosdb_account.example.name
  database_name       = azurerm_cosmosdb_mongo_database.example.name

  default_ttl_seconds = "345600"
  shard_key           = "_id"
}
```

### Expected Behavior

Terraform will not replace the default_ttl_seconds value if it was not changed.

### Actual Behavior

Terraform always replaces argument default_ttl_seconds in every run.

```~ default_ttl_seconds = 0 -> 345600```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

The same problem was described in #6611

**Comment by tombuildsstuff** [comment] 2020-08-25 08:35
hi @Petr-Liska 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7825 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7825 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-25 08:35 UTC
Labels: bug, duplicate, service/cosmosdb
