### ISSUE TITLE
Deleting subnets failed (InUseSubnetCannotBeDeleted) used by networkInterfaces

### ISSUE THREAD

**Issue by adhipgupta** [terraform-providers/terraform-provider-azurerm#4784] opened 2019-10-31 22:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

I have 3 modules: Azure RG, Azure Subnet, and VM
```hcl
module "adhipDemo1" {
       source              = "../module/arista/azure/rg"
       rg_name             = "adhipDemo1"
       rg_location         = "westus2"
       vnet_name           = "adhipDemo1Vnet"
       address_space       = "12.0.0.0/16"
}

module "adhipDemo1Subnet" {
       source              = "../module/arista/azure/subnet"
       subnet_prefixes     = ["12.0.0.0/24", "12.0.1.0/24"]
       subnet_names        = ["adhipDemo1Subnet0", "adhipDemo1Subnet1"]
       vnet_name	       = module.adhipDemo1.vnet_name
       vnet_id                  = module.adhipDemo1.vnet_id
       rg_name		       = module.adhipDemo1.rg_name
}
module "azureadhipDemo1veos1" {
       source		= "../module/arista/azure/veos"
       vnet_name    = module.adhipDemo1.vnet_name
       vnet_id      = module.adhipDemo1.vnet_id
       rg_name		= module.adhipDemo1.rg_name
       rg_location	= module.adhipDemo1.rg_location
       intf_names	= ["adhipDemo1veos1Intf0", "adhipDemo1veos1Intf1"]
       subnetids	= {
			"adhipDemo1veos1Intf0" = <subnetid1>
			"adhipDemo1veos1Intf1" = <subnetid2>
		}
}
```

Relevant Resources in Subnet module
```hcl
resource "azurerm_subnet" "subnet" {
  name                 = var.subnet_names[count.index]
  virtual_network_name = var.vnet_name
  resource_group_name  = var.rg_name
  address_prefix       = var.subnet_prefixes[count.index]
  count                = length(var.subnet_names)

  lifecycle {
    ignore_changes = ["route_table_id"]
  }

}
```

Relevant Resources in VM module

```hcl
resource "azurerm_network_interface" "allIntfs" {
  count                         = length(var.intf_names)
  name                          = var.intf_names[count.index]
  location                      = var.rg_location
  resource_group_name           = var.rg_name
ip_configuration {
    name                          = var.intf_names[count.index]
    subnet_id                     = lookup(var.subnetids, var.intf_names[count.index], null)
  }

resource "azurerm_virtual_machine" "veosVm" {
  name                          = var.name
  location                      = var.rg_location
  resource_group_name           = var.rg_name
  primary_network_interface_id  = azurerm_network_interface.allIntfs[0].id
  network_interface_ids         = azurerm_network_interface.allIntfs.*.id
  vm_size                       = "Standard_D4s_v3"

  ...
  ...
}
```

### Debug Output
```
module.azureadhipDemo1veos1.azurerm_network_interface.allIntfs[1]: Destruction complete after 1s
module.azureadhipDemo1veos1.azurerm_network_interface.allIntfs[0]: Destruction complete after 1s
Error: Error deleting Subnet "adhipDemo1Subnet0" (Virtual Network "adhipDemo1Vnet" / Resource Group "adhipDemo1"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet adhipDemo1Subnet0 is in use by /subscriptions/xxxxxxx/resourceGroups/adhipDemo1/providers/Microsoft.Network/networkInterfaces/adhipDemo1veos1Intf0/ipConfigurations/adhipDemo1veos1Intf0 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

Error: Error deleting Subnet "adhipDemo1Subnet1" (Virtual Network "adhipDemo1Vnet" / Resource Group "adhipDemo1"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet adhipDemo1Subnet1 is in use by /subscriptions/xxxxxxx/resourceGroups/adhipDemo1/providers/Microsoft.Network/networkInterfaces/adhipDemo1veos1Intf1/ipConfigurations/adhipDemo1veos1Intf1 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

```

### Expected Behavior

All subnets should have been deleted from the Resource group
### Actual Behavior

Subnets weren't deleted because of the "InUseSubnetCannotBeDeleted" error.
While I was running `terraform apply` I was monitoring the Azure portal and I saw that even though terraform declares the resource to have been deleted, the network interfaces was still present in the resource group. And thats the reason why subnet deletion fails.

I don't see this error, when I do a `terraform destroy` followed by a `terraform apply`
### Steps to Reproduce

1. `terraform apply`
2. Remove modules from .tf file
3. `terraform apply`

### References

After googling, I did find this issue https://github.com/hashicorp/terraform/issues/16361 but wasn't sure if this is the same issue.

* #0000

**Comment by adhipgupta** [comment] 2019-10-31 22:27
Looking more closely at the terraform output, I also observed that when I execute `terraform apply` the subnets start "Destroying" before the interfaces are destroyed. Whereas, in the case of `terraform destroy` the dependency order is maintained and the subnet only starts destroying after the interfaces have been destroyed.

**Comment by nidhi5885** [comment] 2020-01-18 06:17
I started facing the same issue, In my case "terraform destroy" is producing this result. It was working fine till one day back.
I am using terraform v0.12.2 and azurerm v1.39.0

Is it still a bug?

**Comment by liliankasem** [comment] 2020-04-03 16:40
I believe I'm running into a similar issue.

1. Scenario 1 -> no issues
- `terraform apply` 
- `terraform destroy`

2. Scenario 2 -> no issues
- `terraform apply`
-  **no changes** are made to the .tf file
- `terraform apply` 

3. Scenario 3 -> doesn't work
- `terraform apply`
-  **change made:** added another subnet to the vnet I'm deploying
- `terraform apply` 
-  Unable to create/update the vnet: `InUseSubnetCannotBeDeleted` error

```
Error: Error Creating/Updating Virtual Network "vnet-example-01" (Resource Group "rg-likasem-example"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet vm-example-01_subnet is in use by /subscriptions/<my_sub_id>/resourceGroups/rg-likasem-example/providers/Microsoft.Network/networkInterfaces/vm-example-01_nic/ipConfigurations/internal and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

  on main.tf line 16, in resource "azurerm_virtual_network" "vnet":
  16: resource "azurerm_virtual_network" "vnet" {
```

Is this expected behaviour?

**Versions:**
Terraform v0.12.18
+ provider.azurerm v2.0.0

**Comment by tombuildsstuff** [comment] 2020-05-07 17:29
hi @adhipgupta 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this, this appears to be an issue in Terraform Core where dependencies between modules aren't correctly tracked - and so Terraform believes that it's possible to delete all of the items at once since there's no dependencies between them.

Support for Module Dependencies being tracked in several issues in Terraform Core, including [support for `depends_on`](https://github.com/hashicorp/terraform/issues/10462) - as such unfortunately this isn't something we can fix in the AzureRM Provider and would need to be fixed in Terraform Core.

As such I'm going to suggest that we close this issue for the moment, in favour of https://github.com/hashicorp/terraform/issues/10462 which should provide a solution to this longer-term - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-07 17:29 UTC
Labels: question, service/network-interfaces, service/subnets
