### ISSUE TITLE
Allow setting of mode on AKS pools and leverage this to improve default pool settings changes without cluster destroy/recreate

### ISSUE THREAD

**Issue by jstewart612** [terraform-providers/terraform-provider-azurerm#6629] opened 2020-04-26 10:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
With the introduction of AKS System Pools, it should be possible to do two things:
* Allow the default pool to be modified in any area.  For parameters where the API would require a cluster re-create, it should be possible to create a "temporary" system-mode node pool, delete the default, create another system-mode node pool named "default", then delete the "temporary" node pool.  I can understand if people object to doing this, but at least.....
* Add this option to the azurerm_kubernetes_cluster_node_pool resource.

### New or Affected Resource(s)
azurerm_kubernetes_cluster
azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

Simply add a "mode" parameter to azurerm_kubernetes_cluster_node_pool that one can set to "user" or "system", default "user".

### References

* https://docs.microsoft.com/en-us/azure/aks/use-system-pools

**Comment by tombuildsstuff** [comment] 2020-04-27 03:47
hi @jstewart612 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6058 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6058 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-04-27 03:47 UTC
Labels: duplicate, enhancement, service/kubernetes-cluster
