### ISSUE TITLE
azurerm_application_gateway - when updating the list in the request_routing_rules or redirect_configurations, it requires deleting all the items in the list and recreating them

### ISSUE THREAD

**Issue by yehia2221** [terraform-providers/terraform-provider-azurerm#7870] opened 2020-07-23 10:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

**Terraform Version**
0.12.26

**azurerm provider version**
2.19

### Description

When updating the list in the `request_routing_rule` or `redirect_configuration` blocks, `terraform plan` shows that it will delete all the items in the list and recreating them. The expected behavior is to add more rules and redirections to the end of the list without impacting the existing ones, however, it proposes to one by one delete and recreate all the existing rules and redirections. This is not the expected behavior. We do not have the problem on the other blocks: `http_listener`, `ssl_certificate`, `probe`, `url_path_map`, etc.

**Comment by neil-yechenwei** [comment] 2020-07-24 02:09
request_routing_rule and redirect_configuration is TypeSet, which means it's unordered collection. So it cannot know which item is changed when the item of the collection is changed. So I assume it's expected behavior. And the updated collection would be put into http request body while calling rest api, so I assume api would process it as incremental increase. So it should be partial update.

**Comment by tombuildsstuff** [comment] 2020-08-31 13:48
hi @yehia2221 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6896 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6896 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-31 13:48 UTC
Labels: bug, service/application-gateway
