### ISSUE TITLE
AzureLoadBalancer not supported in destination_address_prefix

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#2011] opened 2018-10-03 11:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.13.0

```

### Affected Resource(s)

* azurerm_network_security_group
* azurerm_network_security_rule

### Expected Behavior

The documentation says:

> Tags such as ‘VirtualNetwork’, ‘AzureLoadBalancer’ and ‘Internet’ can also be used.

### Actual Behavior

This will apply, but in the portal, it seems clear that this is not a value that works. Additionally, I've tried using this to permit access to the public load balancer IPs (Azure datacenter IPs) and it does not work. This appears to be a long requested feature for a tag that includes all public IPs for Azure.

I also don't think 'Internet' Is a valid tag.

**Comment by mbrancato** [comment] 2018-10-03 11:49
This looks like an upstream issue with the AzureRM API, does it not?

https://github.com/Azure/azure-rest-api-specs/blob/1e43dbf4e07dcb6f0215b46d715f842a65fa3130/specification/network/resource-manager/Microsoft.Network/stable/2018-02-01/networkSecurityGroup.json#L657-L660

**Comment by neil-yechenwei** [comment] 2020-06-02 04:13
@mbrancato , Thanks for opening this issue. Seems it's an API issue. After tested, seems I can create security rule successfully when set `destination_address_prefix` as `AzureLoadBalancer`, `VirtualNetwork` or `Internet`. Maybe I missed something. If you want, please have a try below tfconfig to check whether the problem still exists. If still exists, could you possibly share the tf config that triggers this problem?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-nsg-test"
  location = "westus"
}

resource "azurerm_network_security_group" "test" {
  name                = "nsgtest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_network_security_rule" "test" {
  name                        = "nsgruletest"
  network_security_group_name = azurerm_network_security_group.test.name
  resource_group_name         = azurerm_resource_group.test.name
  priority                    = 100
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "AzureLoadBalancer"
}

resource "azurerm_network_security_rule" "test2" {
  name                        = "nsgruletest2"
  network_security_group_name = azurerm_network_security_group.test.name
  resource_group_name         = azurerm_resource_group.test.name
  priority                    = 101
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "VirtualNetwork"
}

resource "azurerm_network_security_rule" "test3" {
  name                        = "nsgruletest3"
  network_security_group_name = azurerm_network_security_group.test.name
  resource_group_name         = azurerm_resource_group.test.name
  priority                    = 102
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "Internet"
}
```

**Comment by ArcturusZhang** [comment] 2020-06-05 09:15
Hi @mbrancato 

Since this issue has been open for quite a long time, and we cannot reproduce this on the latest provider any more. I would close this issue hope you would not mind. If the issue persists, please feel free to reopen, comment or open a new issue regarding the new version of provider.

Thank you!

**Closed by ArcturusZhang** 2020-06-05 09:15 UTC
Labels: question, service/load-balancers
