### ISSUE TITLE
azurerm_virtual_machine_extension fails to install AADLoginForLinux extension with error "Failed to get status file"

### ISSUE THREAD

**Issue by raidlman** [terraform-providers/terraform-provider-azurerm#6337] opened 2020-04-02 07:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.8
+ provider.archive v1.3.0
+ provider.azuread v0.7.0
+ provider.azurerm v2.3.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "azrm_vm_extension" {
  name                       = "aadlogin"
  virtual_machine_id         = <vm_id>
  publisher                  = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
  type                       = "AADLoginForLinux"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true
  settings                   = "{}"
  protected_settings         = "{}"
}
```

### Expected Behavior

VM extension gets provisioned on virtual machine.

### Actual Behavior

Terraform provisoning fails with

```
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing
extension 'test'. Error message: \"Failed to get status file [Errno 2] No such fileor directory:
'/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/0.status'\"\r\n\r\n
More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot "
```

Same error when checking the state via the Azure CLI:

```
$ az vm get-instance-view --resource-group azrm_rg --name azrm_vm --query "instanceView.extensions"
[
  {
    "name": "aadlogin",
    "statuses": [
      {
        "code": "ProvisioningState/failed/-1",
        "displayStatus": "Provisioning failed",
        "level": "Error",
        "message": "Failed to get status file [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux-1.0.8370001/status/0.status'",
        "time": null
      }
    ],
    "substatuses": null,
    "type": "Microsoft.Azure.ActiveDirectory.LinuxSSH.AADLoginForLinux",
    "typeHandlerVersion": "1.0.8370001"
  }
]
```

Having a looking at the machine, the **provisioning of the extension succeeded**, but the extension does not write a status file during/after installation. I've also openend up a [Bug report](https://github.com/Azure/azure-linux-extensions/issues/1070) at the extensions repo. The extension does not write a status file even if it's deployed via the Azure CLI. Strange enough it doesn't report any errors when installing vie the CLI. Please refer to the Bug report for the other ouputs.

I'm opening up this issue here, because I'm not sure if writing a status file is mandatory or if the error message thrown by the Azure API should just be ignored by the Terraform provider.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* location: West Europe
* vm size: Standard_D2as_v4

### References

* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad
* https://github.com/Azure/azure-linux-extensions/issues/1070

**Comment by kbetts-wwt** [comment] 2020-08-18 17:02
@raidlman Not sure if you ever figured this out, but I was able to work around this by **completely removing the Settings section** from the config block. I think since no settings/scripts are being passed to the AAD extension, but the settings section still exists, its wanting to write some status. But by removing Settings all together, the status write is bypassed. Worked for me when I did this:

```
  name                 = "AADLoginForLinux"
  virtual_machine_id   = azurerm_linux_virtual_machine.vm.id
  publisher            = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
  type                 = "AADLoginForLinux"
  type_handler_version = "1.0"
  auto_upgrade_minor_version = true
```
 instead of this

```
  name                 = "AADLoginForLinux"
  virtual_machine_id   = azurerm_linux_virtual_machine.vm.id
  publisher            = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
  type                 = "AADLoginForLinux"
  type_handler_version = "1.0"
  auto_upgrade_minor_version = true
  settings             = "{}"
```

**Comment by tombuildsstuff** [comment] 2020-08-18 17:31
👋 

Taking a look through here since this appears to be a question regarding the AADLoginForLinux extension specifically rather than something specific to the Azure Provider. By design within Azure, the behaviour & configuration required for each type of Virtual Machine Extension is different - and as such unfortunately we're unable to offer detailed support with this - however it sounds like in this instance removing the `settings` block is sufficient here.

Since it sounds like this issue is resolved - I'm going to close this issue for the moment - however if you're continuing to have issues I'd suggest opening an issue with Microsoft Support/on the VM Extension repository where they should be able to assist further here.

Thanks!

**Closed by tombuildsstuff** 2020-08-18 17:31 UTC
Labels: question, service/virtual-machine-extensions
