### ISSUE TITLE
mangement of default route table from azurerm_virtual_hub

### ISSUE THREAD

**Issue by rowco** [terraform-providers/terraform-provider-azurerm#11644] opened 2021-05-10 10:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is no way to manage the default route table which is created when adding a virtual hub using azurerm_virtual_hub. To add a route to this route_table we need to import the resource after each new hub is added.

A Data Source for azurerm_virtual_hub_route_table would be one solution.

### New or Affected Resource(s)

* azurerm_virtual_hub
* azurerm_virtual_hub_route_table

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by rowco** [comment] 2021-05-10 10:38
#11169 would also be a good solution (or both)

**Comment by tombuildsstuff** [comment] 2021-05-10 12:42
hi @rowco 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #11169 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11169 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-05-10 12:42 UTC
