### ISSUE TITLE
azurerm_key_vault_access_policy fails when key vault is in a different subscription

### ISSUE THREAD

**Issue by eparisca** [terraform-providers/terraform-provider-azurerm#11977] opened 2021-05-26 22:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.60.0

### Affected Resource(s)

* `azurerm_key_vault_access_policy`

### Terraform Configuration Files

```hcl
# default subscription
provider "azurerm" {
  features {}
  subscription_id = "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"
}

# secondary subscription
provider "azurerm" {
  alias = "xxx_subscription"
  features {}
  subscription_id = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
}

resource "azurerm_resource_group" "yyy" {
  name = "rg-yyy-example"
  location = "East US"
}

data "azurerm_key_vault" "akv" {
  provider = azurerm.xxx_subscription
  resource_group_name = "rg-xxx-example"
  name                = "kv-example"
}

resource "azurerm_user_assigned_identity" "agw_identity" {
  name                = "id-agw-example"
  resource_group_name = "rg-yyy-example"
  location            = "East US"
}

resource "azurerm_key_vault_access_policy" "agw_identity" {
  key_vault_id = data.azure_key_vault.akv.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_user_assigned_identity.agw_identity.principal_id

  secret_permissions = [
    "get",
  ]
}
```

### Expected Behaviour

Upon running `terraform apply` and `terraform import`, `azurerm_key_vault_access_policy` references the full key vault ID, including the subscription ID `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`

```
2021/05/26 17:59:58 [TRACE] vertex "module.application_gateway[\"EUS-PROD\"].azurerm_key_vault_access_policy.agw_identity (import id \"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/rg-xxx-example/providers/Microsoft.KeyVault/vaults/kv-example/objectId/08777991-4a77-4fd9-a08a-80a3f17c2882\")": dynamic subgraph encountered errors
```

### Actual Behaviour

Upon running `terraform apply` and `terraform import`, `azurerm_key_vault_access_policy` appears to replace key_vault_id's subscription ID `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX` with `YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY` in the request URL to management.azure.com

```
2021-05-26T17:59:58.912-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.60.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYY/resourceGroups/rg-xxx-example/providers/Microsoft.KeyVault/vaults/kv-example?api-version=2019-09-01: 
2021-05-26T17:59:58.912-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.60.0_x5: HTTP/2.0 404 Not Found
```

### Steps to Reproduce

1. `terraform apply`

Alternative
1. Create access policy manually from Azure Portal
2. `terraform import` access policy

### References

* #10824 appears to be similar in nature

**Comment by katbyte** [comment] 2021-06-24 04:33
closing as a duplicate of #10824

**Closed by katbyte** 2021-06-24 04:33 UTC
Labels: bug, service/keyvault

**Comment by weberswords** [comment] 2021-06-28 23:17
Why was this considered a duplicate? It was called out that #10824 is similar but not the same.
