### ISSUE TITLE
Cannot update an azurerm_role_definition

### ISSUE THREAD

**Issue by quaintance** [terraform-providers/terraform-provider-azurerm#3510] opened 2019-05-23 15:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `terraform 0.11.14`
* `azurerm_v1.28.0`

### Terraform Configuration Files

original state:
```hcl
resource "azurerm_role_definition" "owner_test_role_ml_for_pim" {
  name        = "owner_test_role_ml_for_pim"
  scope       = "${data.azurerm_subscription.current.id}"
  description = "This is a custom role created via Terraform for ML when using PIM"

  permissions {
    actions     = ["*"]
    not_actions = []
  }

  assignable_scopes = [
    "${module.vmss.resource_group_id}",
  ]
}
```
updated state:
```hcl
resource "azurerm_role_definition" "owner_test_role_ml_for_pim" {
  name        = "owner_test_role_ml_for_pim"
  scope       = "${data.azurerm_subscription.current.id}"
  description = "This is a custom role created via Terraform for ML when using PIM"

  permissions {
    actions     = []
    not_actions = []
  }

  assignable_scopes = [
    "${module.vmss.resource_group_id}",
  ]
}
```

Problem is that terraform cannot update a role, it can now delete the role thanks to [#1887](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1887) but updates fail with same error described in [#1540](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1540)

error when applying the updated state:
```
Acquiring state lock. This may take a few moments...
data.azurerm_subscription.current: Refreshing state...
azurerm_role_definition.owner_test_role_ml_for_pim: Refreshing state... (ID: /subscriptions/a1c3028f-e12c-4266-xxxx-...s/4ec4ea6a-0999-6d3b-d04d-xxxxxxxxxx)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_role_definition.owner_test_role_ml_for_pim
      permissions.0.actions.#: "1" => "0"
      permissions.0.actions.0: "*" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_role_definition.owner_test_role_ml_for_pim: Modifying... (ID: /subscriptions/a1c3028f-e12c-4266-xxxx-...s/4ec4ea6a-0999-6d3b-d04d-xxxxxxx)
  permissions.0.actions.#: "1" => "0"
  permissions.0.actions.0: "*" => ""

Error: Error applying plan:

1 error occurred:
	* azurerm_role_definition.owner_test_role_ml_for_pim: 1 error occurred:
	* azurerm_role_definition.owner_test_role_ml_for_pim: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleDefinitionWithSameNameExists" Message="A role definition cannot be updated with a name that already exists."
```

### Debug Output

[gist output](https://gist.github.com/quaintance/91c0f76c505dfd65a48da6ae64a93631)

### Steps to Reproduce

1. `terraform apply`

### References

* #1540 
* #1887

**Comment by fgnathan** [comment] 2019-06-10 20:23
Still happens with `terraform 0.12.1` and `azurerm_v1.30.1`.

**Comment by fgnathan** [comment] 2019-06-12 23:43
Using a `role_definition_id` as mentioned here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2069#issuecomment-483621471 works.

**Comment by katbyte** [comment] 2019-07-09 06:37
Closing as a duplicate of #2069

**Closed by katbyte** 2019-07-09 06:37 UTC
Labels: bug, good first issue, service/roles
