### ISSUE TITLE
Please re-open 5352, it's not a question, it's a bug!

### ISSUE THREAD

**Issue by schuettecarsten** [terraform-providers/terraform-provider-azurerm#5986] opened 2020-03-04 17:25 UTC
Please reopen issue #5352 

The issue described in #5352 is not a question, it's a serious bug and may affect all Microsoft Partners that are "Cloud Solution Providers" (CSP) and use the delegated administration feature to manage their customers subscriptions.

Background Information: Since AzureRM provider 1.38.0, some user details are requested using Graph API calls. Unfortunately, in CSP subscriptions and delegated administration model, the used user is not a visible member of the customers active directory, but only some kind of shadow object. So, Graph API cannot return any details for these users. That's by design from Microsoft and cannot be changed. Also, it's not possible to grant additional rights to something here.

One workaround might be a flag/feature to disable these additional Graph API calls during login and use some "fake" values?

**Comment by Idanatcox** [comment] 2020-09-11 02:42
I'm surprised to see how the current 2.x azurerm provider is essentially broken due to #5352 with no resolution in sight.
Logging in using minimal permissions to Graph API seems to be the right approach. 
As a new Azure Terraform user this issues renders this guide as broken https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell#log-into-azure-using-an-azure-service-principal 
What's the solution?

**Comment by schuettecarsten** [comment] 2020-09-11 06:43
There is no solution for this. You need to use a user account from the target tenant and cannot use delegated administration with terraform any more. Or you need to use other tools, like Pulumi. Unfortunately, Hashicorp prefers to close the issues instead of fixing this. :-(

**Comment by tombuildsstuff** [comment] 2020-09-11 08:59
hi @schuettecarsten 

As mentioned in #5352 unfortunately we now require that valid credentials are passed in - and at this time we require using the Azure AD legacy API's due to the Graph API's only recently becoming stable (and there being no Go SDK available for that).

At this time we're looking into a Go SDK for the new Graph API's as a part of the Azure AD provider - which we'll ultimately end up using here too; as such this'll ultimately be fixed by that. However since at this time this behaviour is working as intended (since the legacy Azure AD API's are the only ones exposed in the Azure SDK for Go) and as such I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2020-09-11 08:59 UTC
Labels: question
