### ISSUE TITLE
frontdoor - read context deadline exceeded

### ISSUE THREAD

**Issue by timja** [terraform-providers/terraform-provider-azurerm#7925] opened 2020-07-28 08:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

https://github.com/hmcts/azure-platform-terraform/blob/master/modules/azure-landing-zone/frontdoor.tf#L5
https://github.com/hmcts/azure-platform-terraform/blob/master/environments/ithc/ithc.tfvars#L26

### Debug Output

```
error: retrieving Front Door Frontend Endpoint "sscs-cor" (Resource Group "lz-perftest-rg"): frontdoor.FrontendEndpointsClient#Get: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```

### Expected Behavior

It shouldn't timeout

### Actual Behavior

It timed out

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We have quite a few frontend endpoints

Seems to be caused by:
https://github.com/terraform-providers/terraform-provider-azurerm/pull/7485

@WodansSon @tombuildsstuff 

### References

* #0000

**Comment by darrenk13** [comment] 2020-07-29 00:20
I have been using Front Door with custom domains and found that I needed to increase the read timeout of the resource to get it to complete being created successfully.  It looks like Azure or Terraform goes through the frontends serially when they are defined as part of the Front Door resource.  Domain validation was taking 5-10 minutes each for me.

Have you tried using the new resource [`azurerm_frontdoor_custom_https_configuration`](https://www.terraform.io/docs/providers/azurerm/r/frontdoor_custom_https_configuration.html) ?  The Terraform docs say that using that resource type allows the frontends with custom https settinsgs to be created and updated in parallel.

**Comment by timja** [comment] 2020-07-29 06:22
@darrenk13 we wrote that resource and we’re updating to the latest provider version before changing over to using that and hit this.

Will give it a try doing it in one go as that might fix it

But this is definitely a regression as this worked on the old provider versions

**Comment by ignatz42** [comment] 2020-08-28 13:43
To workaround this regression, we have explicitly set the azurerm_frontdoor resouce read timeout to '6h' like the create, update, and delete timeouts.  In our case, the Front Door resource is being updated and the modification takes almost 2 hours to complete. Without the timeout set, the apply operation fails after ~10 minutes.

**Comment by timja** [comment] 2020-08-28 13:44
cc @tombuildsstuff

**Comment by tombuildsstuff** [comment] 2020-08-28 14:19
@timja I believe this has been fixed in 2.24/2.25 - can you take a look?

**Comment by timja** [comment] 2020-08-28 14:35
Read timeout hasn't been changed https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/frontdoor/frontdoor_resource.go#L58

but was there a bug fix around here @tombuildsstuff ?

I can't see a specific fix but there are changes to the resource in 2.24

**Comment by tombuildsstuff** [comment] 2020-08-28 14:37
@timja the read timeout is correct (at 5 minutes) - the issue (IIRC as a part of #8146) was that the read timeout was unintentionally used inside a create/update - so this should be resolved

**Comment by timja** [comment] 2020-08-28 14:42
fyi @naikajah @luigibk if you have time to take a look.

(I'm going on leave now).

Thanks for your response!

**Comment by tombuildsstuff** [comment] 2020-08-28 14:46
@timja enjoy your holiday :)

**Comment by ignatz42** [comment] 2020-08-28 18:15
Thanks for the quick response.   Initially, I was using version 2.23 of the provider.   I upgraded to version 2.25 and my long running update has made it to the 1 hour mark (and still going) with the default timeouts.  This is closed from my perspective.  Thanks again for the help.

**Comment by tombuildsstuff** [comment] 2020-08-31 12:47
Closing since as per @ignatz42's comment this is confirmed resolved.

**Closed by tombuildsstuff** 2020-08-31 12:47 UTC
Labels: question, service/frontdoor
