### ISSUE TITLE
AzureRm V2: Cannot delete keyVault without Subscription Level Permissions

### ISSUE THREAD

**Issue by orangenagy** [terraform-providers/terraform-provider-azurerm#8968] opened 2020-10-21 11:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.32.0

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = "true"
}

resource "azurerm_key_vault" "test" {
  name                       = "test345456345"
  location                   = "uksouth"
  resource_group_name        = "testrg"
  tenant_id                  = "xxx"
  sku_name                   = "standard"
  purge_protection_enabled   = true
  soft_delete_enabled        = true
  soft_delete_retention_days = 7
}
```

### Expected Behavior

The resources should be destroyed and terraform exits without error.

### Actual Behavior

The resources are destroyed on the first run of 'terraform destroy'. However, terraform exits with an error. After the keyvault is destroyed it attempts to view deleted vaults, for which it needs subscription level permissions, and fails. The principal in use  has Contributor over the resource group and so is able to create and delete a keyvault. However, it cannot view deleted vaults. The error is as follows:
```
Error: Error retrieving the Deletion Details for KeyVault "xxx": keyvault.VaultsClient#GetDeleted: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.KeyVault/locations/deletedVaults/read' over scope '/subscriptions/xxx' or the scope is invalid. If access was recently granted, please refresh your credentials."
```
If you then run destroy for a second time, terraform exits without error.

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`
1. `terraform destroy`
-- The resource should be destroyed. However, terraform will exit with an error.
1. `terraform destroy`
-- Terraform will exit without error

### Important Factoids
The principal in use has Contributor access on the resource group, but nothing on the subscription.

### References

* #6059

**Comment by tombuildsstuff** [comment] 2020-10-22 15:40
hi @orangenagy 

Thanks for opening this issue.

As you've mentioned during deletion of the Key Vault, by default Terraform looks up the state of the Key Vault to determine if it can/should be purged.

Whilst this functionality is enabled by default (as users have already confirmed they want this deleted via Terraform's Plan functionality) - it's possible to control the behaviour of this functionality [through the `features` block within the `provider` block](https://www.terraform.io/docs/providers/azurerm/index.html#features-2), for instance to disable this functionality:

```hcl
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}
```

Since it should be possible to work around this by updating the Terraform Configuration being used here I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-10-22 15:40 UTC
Labels: question, service/keyvault

**Comment by orangenagy** [comment] 2020-10-22 20:50
Thanks a lot @tombuildsstuff, this works. Am able to destroy now without error.

Nice to also see a use for the features block. Didn't know what it was there for :)
