### ISSUE TITLE
Terraform on Azure don't support disk attach and reattach feature with VM

### ISSUE THREAD

**Issue by lbsolar** [terraform-providers/terraform-provider-azurerm#1017] opened 2018-03-22 20:34 UTC
Hi there,

Currently, terraform on Azure don't support disk attach and reattach feature with VM. It will causes the issue for processing persistent data volume.

We have already submitted request to Azure terraform team.

**Comment by achandmsft** [comment] 2018-03-22 22:25
Thanks for reporting this issue. Closing this as a duplicate of #1014. Please track status of this with that issue.

**Closed by achandmsft** 2018-03-22 22:25 UTC
