### ISSUE TITLE
azurerm_key_vault_key does not work. 

### ISSUE THREAD

**Issue by virtualbubble** [terraform-providers/terraform-provider-azurerm#1277] opened 2018-05-22 15:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

azurerm_key_vault_key

### Terraform Configuration Files
```
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "my-resource-group"
  location = "West US"
}

resource "random_id" "server" {
  keepers = {
    ami_id = 1
  }

  byte_length = 8
}

resource "azurerm_key_vault" "test" {
  name                = "${format("%s%s", "kv", random_id.server.hex)}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  tenant_id           = "${data.azurerm_client_config.current.tenant_id}"

  sku {
    name = "premium"
  }

  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${var.object_id}"

    key_permissions = [
      "create",
      "get",
    ]

    secret_permissions = [
      "set",
    ]
  }

  tags {
    environment = "Production"
  }
}

resource "azurerm_key_vault_key" "generated" {

  name      = "generated-certificate"
  vault_uri = "${azurerm_key_vault.test.vault_uri}"

  key_type  = "RSA"
  key_size  = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}


```

### Expected Behavior

Deployment without errors. I started writing a module and then had issues and tried the example code pasted above from the Terraform website.

https://www.terraform.io/docs/providers/azurerm/r/key_vault_key.html

### Actual Behavior

Error: Error applying plan:

1 error(s) occurred:

* azurerm_key_vault_key.generated: 1 error(s) occurred:

* azurerm_key_vault_key.generated: Error Creating Key: keyvault.BaseClient#CreateKey: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2018-05-22 16:31
Duplicate of #656 (where Azure CLI auth doesn't support Key Vault sub-objects at this time) - closing in favour of that one.

**Closed by tombuildsstuff** 2018-05-22 16:31 UTC
