### ISSUE TITLE
Support for Event Hub Cluster

### ISSUE THREAD

**Issue by brandonh-msft** [terraform-providers/terraform-provider-azurerm#7370] opened 2020-06-17 16:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Event Hubs Dedicated](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dedicated-overview) - aka Cluster - is not supported in the azurerm provider. This issue is a feature request for it.

### New or Affected Resource(s)

* azurerm_eventhub_cluster

### Potential Terraform Configuration

```hcl
# TBD
```

### References

* #0000

**Comment by mybayern1974** [comment] 2020-06-18 04:36
Hi @brandonh-msft , thank you for opening this issue. 

Taking a look through this appears to be a duplicate of #6808 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; Indeed there is already a merged PR #7306 addressing this request. Feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-06-18 04:36 UTC
Labels: duplicate, service/event-hubs

**Comment by brandonh-msft** [comment] 2020-06-18 16:37
excellent! I did search before posting this but alas that one must not've popped for me. thanks
