### ISSUE TITLE
error when deploying to azure: ttlInSeconds object is not present in the request body.

### ISSUE THREAD

**Issue by scotm-gxg** [terraform-providers/terraform-provider-azurerm#954] opened 2018-03-08 14:41 UTC
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_function_app
- azurerm_app_service

### Terraform Configuration Files
main.tf
```hcl
terraform {
    backend "azurerm" {
        storage_account_name = "XXXXX"
        container_name = "XXXX"
        access_key = XXXX
        key = "terraform_tfstate"
    }
}

data "terraform_remote_state" "core_api_state" {
    backend = "azurerm"
    config {
        storage_account_name = "XXXX"
        container_name = "XXXX"
        access_key = "XXXX"
        key = "terraform_tfstate"
    }
}

variable environment_name {

}
variable instance_name {

}
variable sql_admin {

}
variable sql_admin_pwd {

}

provider "azurerm" {
}

module "core-api-azure" {
    source = "azure-infrastructure"
    aspnetcore_environment = "${var.environment_name}"
    instance_name = "${var.instance_name}"
    sql_admin = "${var.sql_admin}"
    sql_admin_pwd = "${var.sql_admin_pwd}"
}

```
azure-infrastructure\main.tf
```hcl
variable aspnetcore_environment {}
variable instance_name {}
variable sql_admin {}
variable sql_admin_pwd {}

locals {
    instance_name_short = "${replace(var.instance_name, "-", "")}"
}

resource "azurerm_resource_group" "terraform_coreapi" {
    name = "${var.instance_name}_core_api_resourcegroup"
    location = "South Central US"
}

resource "azurerm_storage_account" "coreapi-storage" {
    name = "${substr(local.instance_name_short, 0, length(local.instance_name_short) < 14 ? length(local.instance_name_short) : 14)}coreapistr"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    account_tier = "Standard"
    account_replication_type = "LRS"
    enable_blob_encryption = true
    enable_file_encryption = true
}

resource "azurerm_app_service_plan" "core-api" {
    name = "${var.instance_name}-core-api-asp"
    location = "South Central US"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"

    sku {
        tier = "Basic"
        size = "B1"
    }
}

resource "azurerm_app_service" "core-api-auth" {
    name = "${var.instance_name}-core-api-auth"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    app_service_plan_id = "${azurerm_app_service_plan.core-api.id}"

    site_config {
        dotnet_framework_version = "v4.0",
        use_32_bit_worker_process = true
    }

    app_settings {
        "ASPNETCORE_ENVIRONMENT"= "${var.aspnetcore_environment}"
    }

}

resource "azurerm_app_service" "core-api" {
    name = "${var.instance_name}-core-api"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    app_service_plan_id = "${azurerm_app_service_plan.core-api.id}"

    site_config {
        dotnet_framework_version = "v4.0",
        use_32_bit_worker_process = true
    }

    app_settings {
        "ASPNETCORE_ENVIRONMENT"= "${var.aspnetcore_environment}"
    }
}

resource "azurerm_sql_server" "core-api-sql" {
    name = "${var.instance_name}-core-api-sql"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    version = "12.0"
    administrator_login = "${var.sql_admin}"
    administrator_login_password = "${var.sql_admin_pwd}"
}

resource "azurerm_sql_firewall_rule" "core-api-sql-fw" {
    name = "${var.instance_name}-core-api-sql-fw"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    server_name = "${azurerm_sql_server.core-api-sql.name}"
    start_ip_address = "66.249.100.36"
    end_ip_address = "66.249.100.36"
}

resource "azurerm_sql_database" "core-api-db" {
    name = "COREAPI"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    server_name = "${azurerm_sql_server.core-api-sql.name}"
    edition = "Basic"
}

resource "azurerm_sql_database" "core-auth-db" {
    name = "gxgauth"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    server_name = "${azurerm_sql_server.core-api-sql.name}"
    edition = "Basic"
}

resource "azurerm_function_app" "core-api-auth-seed" {
    name = "${var.instance_name}-core-api-auth-seed"
    location = "${azurerm_resource_group.terraform_coreapi.location}"
    resource_group_name = "${azurerm_resource_group.terraform_coreapi.name}"
    app_service_plan_id = "${azurerm_app_service_plan.core-api.id}"
    storage_connection_string = "${azurerm_storage_account.coreapi-storage.primary_connection_string}"
}
```

### Debug Output
https://gist.github.com/scotm-gxg/bbcde1976cafa504e72737fa10848f44

### Panic Output
no panic output

### Expected Behavior
apply succeeds without errors

### Actual Behavior
error happened

### Steps to Reproduce
1. run `terraform plan` and output plan to file
2. run `terraform apply` and pass in file from step 1
3. repeat steps 1 and 2 without making any changes to terraform file
4. some of the time, i receive the error described in the debug output (https://gist.github.com/scotm-gxg/bbcde1976cafa504e72737fa10848f44)

### Important Factoids
Occurs consistently in our DI environment. Happens occasionally when run locally. Can't determine what triggers getting this error.

**Comment by tombuildsstuff** [comment] 2018-03-08 16:58
hi @scotm-gxg 

Thanks for opening this issue :)

So you're seeing this issue because it's currently not possible to update an App Service due to a bug in the Azure API. Terraform stores knowledge about which resources it's managing in a Statefile (generally `terraform.tfstate`) that we recommend holding onto. In this case, the AzureRM Provider in Terraform knows that it's not possible to update an App Service at this time and thus forces a recreation; however it can only do this for resources which are managed by Terraform - you're seeing the error message above as Terraform's calling the API's `upsert` method and getting an error back since this resource already exists (and as such updates can't be made at this time).

You can import the existing App Service into Terraform using [the `terraform import` command](https://www.terraform.io/docs/commands/import.html) - for instance [here's how to import an existing App Service into Terraform](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#import). Once that's done, Terraform can handle updating resources as needed. It's worth noting that we'd generally recommend the use of a Backend/Remote State, such as storing the Statefile in Azure Blob Storage - so that multiple people can't modify the same resources at the same time; [there's more information about this here](https://www.terraform.io/docs/backends/index.html) and the [Azure Blob Storage backend here](https://www.terraform.io/docs/backends/types/azurerm.html).

Would you mind taking a look and seeing if Importing the resource solves your issue? Just to let you know that since this is a configuration question and not a bug in Terraform - I'm going to close this issue.

---

On a separate note - it's worth mentioning that a couple of the usages in the config you've posted above will be deprecated in the not-too-distant future (e.g. all variables need to be quoted, and you'll want to specify the relative path to the module) e.g.

```
variable "environment_name" {

}
variable "instance_name" {

}
variable "sql_admin" {

}
variable "sql_admin_pwd" {

}

provider "azurerm" {
}

module "core-api-azure" {
    source = "./azure-infrastructure"
    aspnetcore_environment = "${var.environment_name}"
    # ...
}
```

Thanks!

**Closed by tombuildsstuff** 2018-03-08 16:58 UTC
Labels: question, service/app-service

**Comment by scotm-gxg** [comment] 2018-03-08 17:55
First, thanks for the tip for upcoming deprecated functionality and the quick reply :)

I'm a little confused. We are using a remote backend for state - azure blob storage. In fact, the app service in question was created by terraform. Would the import just overwrite what is already there for that resource?

when i ran the import as you suggested, i got this error:
`Can't import module.core-api-azure.azurerm_function_app.core-api-auth-seed, would collide with an existing resource.`

So, just to be clear, I cannot update an existing App Service, _even if that service was created by terraform?_

**Comment by tombuildsstuff** [comment] 2018-03-08 18:34
@scotm-gxg so it's possible to update some (e.g. the AppSettings keys), but not all fields (e.g. Tags) - Terraform will suggest either updating or destroying+recreating the App Service, depending on which fields have changed.

Out of interest, would it be possible to see the output of `terraform plan` so we can see what's requiring an update?

Thanks!

**Comment by scotm-gxg** [comment] 2018-03-08 20:01
it looks as though the state on the build server is different than the state on my local machine. a couple of the resources show up as needing to be added when i run `terraform plan` on the build server, but everything is up to date and no changes are shown when i run `terraform plan` on my local machine. 

My local machine and the build server are targeting the same azure subscription and using the same terraform workspace

below is the output:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  + module.core-api-azure.azurerm_app_service.core-api
      id:                                      <computed>
      app_service_plan_id:                     "/subscriptions/XXXXX/resourceGroups/qa-thor_core_api_resourcegroup/providers/Microsoft.Web/serverfarms/qa-thor-core-api-asp"
      app_settings.%:                          "1"
      app_settings.ASPNETCORE_ENVIRONMENT:     "qa"
      client_affinity_enabled:                 <computed>
      connection_string.#:                     <computed>
      default_site_hostname:                   <computed>
      enabled:                                 "true"
      location:                                "southcentralus"
      name:                                    "qa-thor-core-api"
      outbound_ip_addresses:                   <computed>
      resource_group_name:                     "qa-thor_core_api_resourcegroup"
      site_config.#:                           "1"
      site_config.0.always_on:                 "false"
      site_config.0.dotnet_framework_version:  "v4.0"
      site_config.0.local_mysql_enabled:       <computed>
      site_config.0.remote_debugging_enabled:  "false"
      site_config.0.use_32_bit_worker_process: "true"
      site_config.0.websockets_enabled:        <computed>
      tags.%:                                  <computed>

  + module.core-api-azure.azurerm_app_service.core-api-auth
      id:                                      <computed>
      app_service_plan_id:                     "/subscriptions/XXXXX/resourceGroups/qa-thor_core_api_resourcegroup/providers/Microsoft.Web/serverfarms/qa-thor-core-api-asp"
      app_settings.%:                          "1"
      app_settings.ASPNETCORE_ENVIRONMENT:     "qa"
      client_affinity_enabled:                 <computed>
      connection_string.#:                     <computed>
      default_site_hostname:                   <computed>
      enabled:                                 "true"
      location:                                "southcentralus"
      name:                                    "qa-thor-core-api-auth"
      outbound_ip_addresses:                   <computed>
      resource_group_name:                     "qa-thor_core_api_resourcegroup"
      site_config.#:                           "1"
      site_config.0.always_on:                 "false"
      site_config.0.dotnet_framework_version:  "v4.0"
      site_config.0.local_mysql_enabled:       <computed>
      site_config.0.remote_debugging_enabled:  "false"
      site_config.0.use_32_bit_worker_process: "true"
      site_config.0.websockets_enabled:        <computed>
      tags.%:                                  <computed>

  ~ module.core-api-azure.azurerm_function_app.core-api-auth-seed
      app_settings.%:                          "1" => "0"
      app_settings.testSetting1:               "testSetting" => ""


Plan: 2 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
