### ISSUE TITLE
Set throughput at CosmosDB SQL database level

### ISSUE THREAD

**Issue by RiverPhillips** [terraform-providers/terraform-provider-azurerm#3623] opened 2019-06-10 10:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CosmosDB suports setting throughput at a database level and shared across collections, this is not currently possible when provisioning using terraform. 

This affects the cost and performance so is needed for this resource

### New or Affected Resource(s)

*  azurerm_cosmosdb_sql_database 

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_sql_database" "example" {
  name                          = "tfex-cosmos-mongo-db"
  resource_group_name = "${data.azurerm_cosmosdb_account.example.resource_group_name}"
  account_name             = "${data.azurerm_cosmosdb_account.example.name}"
  throughput                 = 400
}
```

**Comment by jpovey** [comment] 2019-06-10 10:22
The options are set using a map of strings https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_cosmosdb_sql_database.go (see line 75)

**Comment by fmjrey** [comment] 2019-06-11 17:04
I can only encourage this feature: we recently migrated from a MongoDB in Heroku to a CosmosDB in Azure, and now realise that each collection within the terraformed CosmosDB is a separate cost item. Collections in MongoDB are not the same in CosmosDB, the former uses them for storing docs of a same type, while the latter is able to store docs of different types.

**Comment by christonog** [comment] 2019-06-25 01:04
I also just started using the `cosmosdb_mongo_collection` resource and was disappointed I couldn't set the throughput for a mongodb collection.

https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_mongo_collection.html

@jpovey apologies for being dense (first time using terraform in a while), but I tried this, which didn't work:

```
resource "azurerm_cosmosdb_mongo_collection" "collection" {
  name = "my_collection"
  .
  .
  .
  { throughput          = 1000 }
```
Must be something I'm missing?

**Comment by christonog** [comment] 2019-06-25 02:03
Actually, my issue looks to be related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/3586

**Comment by katbyte** [comment] 2019-07-09 04:43
@christonog, looks like this is a duplicate of #3586 so i am going to close this. If you think this is an error please feel free to reopen it!

**Comment by katbyte** [comment] 2019-07-09 04:46
Actually upon a closer look that is mongo, and this is SQL, reopening. apologies!

**Comment by tminhein** [comment] 2019-07-30 16:01
guys, any update on this issue. I'm facing this issue my terraform proj as well.

**Comment by tminhein** [comment] 2019-07-31 08:32
> The options are set using a map of strings https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_cosmosdb_sql_database.go (see line 75)

please explain with a sample.   I've tried {througtput = 400}.  it's not working.

**Comment by sawyerh** [comment] 2019-08-29 13:06
For those getting confused by @jpovey's comment – My impression is: it's being pointed out that this looks possible using the Go SDK (though I'm not sure how you pass in that map of strings), which the Azure Terraform provider depends upon. However, it doesn't appear that this is supported by the provider right now, which this issue is requesting. cc @tminhein

**Comment by ronaldmiranda** [comment] 2019-09-05 11:45
> 
> 
> > The options are set using a map of strings https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_cosmosdb_sql_database.go (see line 75)
> 
> please explain with a sample. I've tried {througtput = 400}. it's not working.

Until this is not implemented, im using via azure template.

**Comment by MartinKosicky** [comment] 2019-09-11 16:32
So is this ever going to be implemented?  The cosmos terraform provider is useless if i cannot specify throughput. I would have to create a separate script to configure this

**Comment by ronaldmiranda** [comment] 2019-09-11 17:09
> 
> 
> So is this ever going to be implemented? The cosmos terraform provider is useless if i cannot specify throughput. I would have to create a separate script to configure this

Is just like i mentioned above, im using the azurerm template provider.

**Comment by markti** [comment] 2019-11-08 21:37
Very sad throughput cannot be controlled when deploying terraform. This is a critical issue as you cannot change the throughput configuration of a SQL Database once it has been deployed. It requires a drop / create.

**Closed** 2019-12-18 09:59 UTC
Labels: enhancement, service/cosmosdb
