### ISSUE TITLE
Variables and conditional with dynamic blocks, not work as expected?

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#3916] opened 2019-07-24 08:55 UTC
Hi Team,
I open this thread from https://discuss.hashicorp.com/t/variables-and-conditional-with-dynamic-blocks-not-work-as-expected-azurerm-provider/2078 following the @apparentlymart suguesstions.

 @apparentlymart said it is a limitation of the current SDK, but it is possible to avoid it in the AzureRM provider. 
In this case, it opens up new possibilities to reduce the number of declared resources and increases the configuration options.

_Copy/paste of the original post:_ 

Hi,
I am trying to use the dynamic blocks introduced in version 0.12. With this vesion it is possible, for example, to declare a unique resource to create virtual machines (windows / linux).

The problem I’m having is how to declare the condition to know what kind of machine to create, I have tried several options but all get the same problem.

I do not understand what is happening, also if I declare the value I need directly with locals there are no problems, but doing this does not make sense.

Any help is well come
Thank you!!

Issue description:
In the example that follows, if I use this condition I get an error because it tries to create the two dynamic blocks, even when the result of “os_win” is “true” (it is being evaluated well):

```hcl
locals {
  os_win = substr(lookup (var.image, "publisher", "value_not_declared"), 0, 9) == "Microsoft" ? true: false
  dynamic_linux = ! local.os_win ? {dummy_create = true}: {}
  dynamic_windows = local.os_win ? {dummy_create = true}: {}
}
```
If I declare it manually (it’s not a variable), it works correctly, but as I said earlier, it does not make sense to do so.

```hcl
locals {
  os_win = true
  dynamic_linux = ! local.os_win ? {dummy_create = true}: {}
  dynamic_windows = local.os_win ? {dummy_create = true}: {}
}
```

All code:

```hcl
terraform -version
Terraform v0.12.5
+ provider.azurerm v1.31.0


# variable "image" {
#   type = map
#   default = {
#     publisher = "Canonical"
#     offer     = "UbuntuServer"
#     sku       = "16.04-LTS"
#     version   = "latest"
#   }
# }

variable "image" {
  type = map
  default = {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }
}

locals {
  os_win = substr(lookup(var.image, "publisher", "value_not_declared"), 0, 9) == "Microsoft" ? true : false
  #os_win          = true
  dynamic_linux   = ! local.os_win ? { dummy_create = true } : {}
  dynamic_windows = local.os_win ? { dummy_create = true } : {}
}

resource "azurerm_resource_group" "main" {
  name     = "testjc-resources"
  location = "West US 2"
}

resource "azurerm_virtual_network" "main" {
  name                = "testjc-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_subnet" "internal" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "main" {
  name                = "testjc-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.internal.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_virtual_machine" "main" {
  name                  = "testjc-vm"
  location              = azurerm_resource_group.main.location
  resource_group_name   = azurerm_resource_group.main.name
  network_interface_ids = [azurerm_network_interface.main.id]
  vm_size               = "Standard_DS1_v2"

  storage_image_reference {
    publisher = lookup(var.image, "publisher")
    offer     = lookup(var.image, "offer")
    sku       = lookup(var.image, "sku")
    version   = lookup(var.image, "version")
  }
  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  os_profile {
    computer_name  = "hostname"
    admin_username = "testadmin"
    admin_password = "Password1234!"
  }

  dynamic "os_profile_linux_config" {
    for_each = local.dynamic_linux

    content {
      disable_password_authentication = false
    }
  }

  dynamic "os_profile_windows_config" {
    for_each = local.dynamic_windows

    content {
      enable_automatic_upgrades = false
      provision_vm_agent        = true
    }
  }
}
```

Results:

```hcl
terraform plan

Error: "os_profile_windows_config": conflicts with os_profile_linux_config

  on main.tf line 81, in resource "azurerm_virtual_machine" "main":
  81: resource "azurerm_virtual_machine" "main" {



Error: "os_profile_linux_config": conflicts with os_profile_windows_config

  on main.tf line 81, in resource "azurerm_virtual_machine" "main":
  81: resource "azurerm_virtual_machine" "main" {
```

**Comment by apparentlymart** [comment] 2019-07-24 14:14
Hello! Just wanted to add some additional context from over in that discussion post, along with some more details, just to capture everything in one place:

The key problem here is that the current 0.11-oriented SDK does not have any special support for `dynamic` blocks. Although in most cases it works anyway just due to the result looking _enough like_ a static block for the SDK to pass, but there are a few naive validation features in the SDK that run into difficulties dealing with the new "unknown" situations that can arise with dyanmic blocks:

* The `MinItems` constraint can fail validation when dealing with dynamic blocks because it's expecting to be able to see the static block count at validation time, but that isn't available yet.
* The `ConflictsWith` constraint can fail validation when dealing with dynamic blocks (as we see in this case) for the same reason: it's expecting to be able to prove statically that the block count is zero for at least one of the two blocks here.

The root cause common to both of these is that, just as with unknown argument values in prior Terraform versions, dynamic blocks tend to not be resolved yet during the validation phase. The _intent_ is that the validation rules will skip over situations where there isn't yet enough information available to decide whether the configuration is valid or not, but the old SDK doesn't understand dynamic blocks and so doesn't know how to detect and skip them.

---

Hopefully the future 0.12-oriented SDK will have direct support for dynamic blocks and will be able to treat them the same as unknown argument values, by deferring the checks until the plan or apply phase when more information is available. But I was thinking about ways that this _particular_ constraint could be expressed in `CustomizeDiff` instead so that the check can have more context available. However, I don't know if these ideas are feasible in the details of how this resource type is implemented. Here are two ideas that _might_ work here:

* The first and simplest idea (which I didn't have yet when I wrote that forum response) is that just doing this validation rule in `CustomizeDiff` might actually be enough here, because by definition any logic in that function is deferred until plan time. Plan-time checks have access to a finalized block count _as long as the `for_each` expression is known_. Just implementing the existing rule directly in `CustomizeDiff` logic would not fix it for the case where `for_each` is unknown until apply time, but for the sake of the specific situation this issue is about that shouldn't matter.
* Building on that, the idea I was less sure about is whether a `CustomizeDiff` implementation here would have enough information to infer automatically whether the selected image is a Windows or Linux image and thus make the rule more precise:

  ```
  if a Windows image:
    require one os_profile_windows_config block
  if a Linux image:
    require one os_profile_linux_config
  if image type isn't known yet:
    accept any combination of blocks and await further information
  else:
    don't allow any blocks (future expansion of a new image type?)
  ```

  If the image type _is_ available there then I think this would also help in the situation described in this issue because it would fall into the "if image type isn't known yet" path during validation, and thus allow this rule to be deferred to the plan phase.

With that said, it's quite possible that making this work in spite of the SDK is complex enough to not be achievable prior to the new SDK being ready anyway, so this could end up just being one of those features where the `dynamic` block isn't available yet until the SDK catches up with this new feature. There's already a handful of these due to similar validation limitations, and while it's not ideal so far I believe it falls into the category of things that were not possible in 0.11 anyway and thus we've not _lost_ any previously-working functionality as a result of these SDK limitations.

**Comment by tombuildsstuff** [comment] 2020-08-28 06:36
hi @jcmaasb 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward - which by being more granular resources are able to offer better validation here.

Thanks!

**Closed by tombuildsstuff** 2020-08-28 06:36 UTC
Labels: question, service/virtual-machine
