### ISSUE TITLE
AppService overriding unspecified settings

### ISSUE THREAD

**Issue by ahmedspiir** [terraform-providers/terraform-provider-azurerm#3148] opened 2019-03-29 12:17 UTC
### Terraform Version

```
v0.11.13
+ provider.azurerm v1.23.0
```

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "myapp" {
  name                = "${var.app_name}"
  location            = "${azurerm_resource_group.myapp.location}"
  resource_group_name = "${azurerm_resource_group.myapp.name}"
  app_service_plan_id = "${azurerm_app_service_plan.myapp.id}"
  https_only          = "true"

  app_settings {
    "APPINSIGHTS_INSTRUMENTATIONKEY" = "${azurerm_application_insights.myapp.instrumentation_key}"
  }

  site_config {
    always_on                 = "true"
    ftps_state                = "Disabled"
    use_32_bit_worker_process = "false"
  }
}
```

### Actual Behavior

Terraform will perform the following actions:

  ~ azurerm_app_service.myapp
      site_config.0.always_on:                 "false" => "true"
      site_config.0.default_documents.#:       "9" => "0"
      site_config.0.default_documents.0:       "Default.htm" => ""
      site_config.0.default_documents.1:       "Default.html" => ""
      site_config.0.default_documents.2:       "Default.asp" => ""
      site_config.0.default_documents.3:       "index.htm" => ""
      site_config.0.default_documents.4:       "index.html" => ""
      site_config.0.default_documents.5:       "iisstart.htm" => ""
      site_config.0.default_documents.6:       "default.aspx" => ""
      site_config.0.default_documents.7:       "index.php" => ""
      site_config.0.default_documents.8:       "hostingstart.html" => ""
      site_config.0.ftps_state:                "AllAllowed" => "Disabled"
      site_config.0.php_version:               "5.6" => ""
      site_config.0.use_32_bit_worker_process: "true" => "false"

Plan: 0 to add, 1 to change, 0 to destroy.

### Expected Behavior
So the expected behaviour is to override the specified site_config settings, and not to set everything else to be empty.
So i expected to get something like this

>  ~ azurerm_app_service.myapp
>       site_config.0.always_on:                 "false" => "true"
>       site_config.0.ftps_state:                "AllAllowed" => "Disabled"
>       site_config.0.use_32_bit_worker_process: "true" => "false"
> 

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by tombuildsstuff** [comment] 2019-03-29 12:47
hi @ahmedspiir 

Thanks for opening this issue :)

Since Terraform's managing the `site_config` block it'll attempt to manage all properties within the block (as you're seeing); since these fields aren't specified Terraform uses the default value for these fields - which is why you're seeing this diff. As such the values of any fields which use non-default values will need to be specified (for example for `ftps_state`) - which will mean Terraform will pass the value you're using here (which means this diff will disappear). Would you be able to take a look and see if this works for you?

Since this behaviour is by design I'm going to close this issue for the moment - but please let us know if specifying these values in the config doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2019-03-29 12:47 UTC

**Comment by ahmedspiir** [comment] 2019-03-29 12:54
Hi @tombuildsstuff
Thanks for the answer, but in my opinion, this is not the best way to handle because if the user wants to change something he should specify it, in this case, wouldn't it be better if the values are not specified take the current ones from Azure?
If i'll have to specify all the values all the time, then i'll be writing boilerplate code
