### ISSUE TITLE
Support for Key Vault Managed Storage Accounts

### ISSUE THREAD

**Issue by rudolphjacksonm** [terraform-providers/terraform-provider-azurerm#6872] opened 2020-05-12 10:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Azure Key Vault can manage and automatically rotate the access keys for an Azure Storage Account. Currently this is only possible via the CLI: https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys#create-a-key-vault-managed-storage-account

It looks like the process for doing this involves creating a Storage Account as normal, and then using the `azure keyvault storage` command to set up the integration.

### New or Affected Resource(s)

* azurerm_keyvault_managed_storage

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "storageacc" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
}

resource "azurerm_key_vault" "azkeyvault" {
  name                = "azkeyvault"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}

resource "azurerm_keyvault_managed_storage" "keyvault_managed" {
  active_key_name     = "key1"
  auto_regenerate_key = true
  regeneration_period = "90d"
  storage_account_id  = azurerm_storage_account.storageacc.id
  vault_name          = "azkeyvault"
}
```

### References

* #0000

**Comment by amasover** [comment] 2020-05-12 19:12
I think this is a dupe of #4659? I'm waiting for this feature as well.

**Comment by mybayern1974** [comment] 2020-05-13 03:57
Thank you @rudolphjacksonm for raising up this feature request and thank you @amasover for figuring out the dup! If you do not mind then I'm closing this issue and please subscribe [issue 4659](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4659).

**Closed by mybayern1974** 2020-05-13 03:57 UTC
