### ISSUE TITLE
postgresql - hyperscale support

### ISSUE THREAD

**Issue by az-cloud** [terraform-providers/terraform-provider-azurerm#7380] opened 2020-06-17 17:41 UTC
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.
Hi All,

Wanted to check if current Terraform version supports hyperscale option since iam not able to find one except for sql.
---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by az-cloud** [comment] 2020-06-22 03:31
hi,  can someone please help me here.

**Comment by tombuildsstuff** [comment] 2020-06-23 09:34
hi @az-cloud 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5040 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5040 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-23 09:34 UTC
Labels: duplicate, enhancement, service/postgresql

**Comment by az-cloud** [comment] 2020-06-23 16:10
thanks Tom, subscribed to #5040
