### ISSUE TITLE
Cosmosdb missing keyVaultKeyUri attribute

### ISSUE THREAD

**Issue by marchesir** [terraform-providers/terraform-provider-azurerm#8116] opened 2020-08-13 17:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I am attempting to create Azure CosmosDB that needs CMK (Customer Managed Keys) which is very simple process via Azure Portal via ARM templates or Az CLI.  But i want to autmate all of these via Terraform.
Normally you would be required to provide an Azure KV Key URL but for some reason this attribute is missing from Terraform azurerm provider even if its avialbale in ARM templates and Az CLI.

https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/databaseaccounts

The missing attribute is "keyVaultKeyUri" of type sting.

Why is it missing or is there any plans to add it?

This means in my project I have to use an ARM template emmedded inside terraform which is messy.

### New or Affected Resource(s)

* azurerm_2.22.0
* terraform 13.X

### Potential Terraform Configuration

N/A as the attribute is not avilable!!

### References

* #0000

**Comment by ArcturusZhang** [comment] 2020-08-17 04:39
Hi @marchesir thanks for this issue, but I am afraid that this should be a duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/7798.

Therefore I will close this issue in favor of that issue, could you please track the CMK progress in that issue?

**Closed by ArcturusZhang** 2020-08-17 04:39 UTC
Labels: service/cosmosdb

**Comment by marchesir** [comment] 2020-09-02 15:40
great thanks iv seen it now much appreciated
