### ISSUE TITLE
Request support for Azure Files Soft Delete

### ISSUE THREAD

**Issue by ryan-peterson3** [terraform-providers/terraform-provider-azurerm#9091] opened 2020-10-29 20:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to configure Soft Delete on Azure File Shares.

### New or Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account
Resource: Storage Account
Setting: File Service - Soft Delete

* azurerm_storage_account

**Comment by NT-D** [comment] 2020-11-02 04:05
Can I do some PR for this ?
I've confirmed I can do this via Azure CLI, so I believe we can do this via Terraform, too.

[Prep: Create resource group and storage account]
- az group create -l japaneast -n MasaCli
- az storage account create -g MasaCli -l japaneast -n masotaclistorage --sku Standard_LRS

[Enable soft delete policy]
az storage account file-service-properties update --enable-delete-retention true --delete-retention-days 100 -n masotaclistorage -g MasaCli


FYI: 
- `delete-retention-days` range should be 1 - 365
- [Official document](https://docs.microsoft.com/en-us/cli/azure/storage/account/file-service-properties?view=azure-cli-latest#az_storage_account_file_service_properties_update)

**Comment by NT-D** [comment] 2020-11-02 05:22
Did some investigation. Because this is my 1st PR, I need good example.

[blob_properties](https://github.com/terraform-providers/terraform-provider-azurerm/blob/7690961a94167fe8112a0ccccf97ce44bf6bb204/azurerm/internal/services/storage/resource_arm_storage_account.go#L247) and its related codes looks useful.
This is properties for blob. I can learn from this to create property for file. I may be able to say `file__properties`.

**Comment by aristosvo** [comment] 2020-11-02 08:14
Hi @NT-D ! Thanks for your investigation! I believe this [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8932) implements this already. Can you confirm?

**Comment by NT-D** [comment] 2020-11-02 08:40
Hi, @aristosvo thank you for let me know that. Yes, #8932 implements this. Let me try to resolve other issue.

**Comment by tombuildsstuff** [comment] 2020-11-19 12:55
👋 

As @NT-D has mentioned above this is a duplicate of #7115 - as such I'm going to close this in favour of that issue - but this should be resolved via #8932.

Thanks!

**Closed by tombuildsstuff** 2020-11-19 12:55 UTC
Labels: duplicate, enhancement, service/storage
