### ISSUE TITLE
Support for Storage account Turn on Soft delete for file share / blobs

### ISSUE THREAD

**Issue by kgopi1** [terraform-providers/terraform-provider-azurerm#10281] opened 2021-01-22 11:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_storage_account

Provide option to Turn on Soft delete for Blobs / File share when creating the Storage account. 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-01-22 11:15
hi @kgopi1 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7115 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7115 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-22 11:15 UTC
Labels: duplicate, service/storage
