### ISSUE TITLE
Terraform tries to destroy resources before the management lock had a chance to sync

### ISSUE THREAD

**Issue by mariojacobo** [terraform-providers/terraform-provider-azurerm#5025] opened 2019-11-29 12:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.4

### Affected Resource(s)

* `azurerm_management_lock`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=1.37.0"
}

resource "azurerm_resource_group" "test" {
  name     = "testResourceGroup1"
  location = "West Europe"
}

resource "azurerm_management_lock" "resource-group-level" {
  name       = "resource-group-level"
  scope      = azurerm_resource_group.test.id
  lock_level = "CanNotDelete"
  notes      = "do not delete !!"
}

resource "azurerm_storage_account" "media_sa" {
  name                     = "testingaccount0002"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "RAGRS"
  enable_https_traffic_only = true
  
  network_rules {
  default_action             = "Deny"  
  }
}

resource "azurerm_storage_account" "media_sa1" {
  name                     = "testingaccount00022"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "RAGRS"
  enable_https_traffic_only = true
  
  network_rules {
  default_action             = "Deny" 
   
  }
}
```

### Expected Behavior

Terraform should wait until Azure reports the management lock as deleted 
### Actual Behavior

Terraform will try to delete the storage accounts (or any other type of resources) before getting the status of deletion of the locks

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

azurerm_storage_account.media_sa1: Destroying... [id=/subscriptions//resourceGroups/testResourceGroup1/providers/Microsoft.Storage/storageAccounts/testingaccount00022]
azurerm_management_lock.resource-group-level: Destroying... [id=/subscriptions//resourceGroups/testResourceGroup1/providers/Microsoft.Authorization/locks/resource-group-level]
azurerm_storage_account.media_sa: Destroying... [id=/subscriptions//resourceGroups/testResourceGroup1/providers/Microsoft.Storage/storageAccounts/testingaccount0002]
azurerm_management_lock.resource-group-level: Destruction complete after 0s

Error: Error issuing delete request for Storage Account "testingaccount0002" (Resource Group "testResourceGroup1"): storage.AccountsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ScopeLocked" Message="The scope '/subscriptions//resourceGroups/testResourceGroup1/providers/Microsoft.Storage/storageAccounts/testingaccount0002' cannot perform delete operation because following scope(s) are locked: '/subscriptions//resourceGroups/testResourceGroup1'. Please remove the lock and try again."

Error: Error issuing delete request for Storage Account "testingaccount00022" (Resource Group "testResourceGroup1"): storage.AccountsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ScopeLocked" Message="The scope '/subscriptions//resourceGroups/testResourceGroup1/providers/Microsoft.Storage/storageAccounts/testingaccount00022' cannot perform delete operation because following scope(s) are locked: '/subscriptions//resourceGroups/testResourceGroup1'. Please remove the lock and try again."

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by mariojacobo** [comment] 2019-11-29 12:55
to workaround this issue, I have a Jenkins pipeline which reruns the "destroy" steps twice. On the first try, the locks are deleted, it errors out, but succeeds on the second run.

**Comment by hacst** [comment] 2019-12-19 12:57
We are also seeing this issue. The locks seem to be prone to race issues in general. It seems like they can also behave inconsistent on creation leading to:
```
Error: locks.ManagementLocksClient#GetByScope: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="LockNotFound" Message="The lock 'XXX' could not be found."
```
But that is not easily reproducible like the deletion one.

**Comment by akorp** [comment] 2020-02-27 11:38
Should Terraform wait with the destruction of the resources dependent on the lock before it receive a confirmation that the lock is removed?

**Comment by mariojacobo** [comment] 2020-02-27 12:42
@akorp - the way I understand this, is that Terraform should know that it cannot destroy resources because of management locks; in the same way it detect dependencies between let's say a resource group and a resource inside said resource group;  what I see is that it discovers the management locks but it proceeds to destroy the locked resources regardless.

**Comment by mbfrahry** [comment] 2020-04-27 20:41
Hey all, I've got an update/potential fix for this issue. The main problem here, is that we're trying to delete the management lock at the same time as the storage accounts; however, it fails because azure put a dependency between the lock and the storage account. Unfortunately, the way the config is written, Terraform doesn't know this dependency exists. The way Terraform builds its dependency tree is through resources referencing other resources. For example, we know we can't build a storage_account until after the resource_group has been created. We know this because of `resource_group_name  = azurerm_resource_group.test.name` being written into config. There is no such linkage between storage accounts and the management lock so Terraform thinks that it can manage them both at the same time. What we want to add is `depends_on = [azurerm_management_lock.resource-group-level]` to each of the storage accounts declarations. At that point, we've set up an explicit dependency so Terraform will manage the lock first before modifying the storage accounts. 

I'll close this issue down but if you continue to experience issues feel free to reopen this.

**Closed by mbfrahry** 2020-04-27 20:41 UTC
Labels: question, service/resources
