### ISSUE TITLE
Storage Resources now require the resource group in the right case

### ISSUE THREAD

**Issue by Farishta** [terraform-providers/terraform-provider-azurerm#1890] opened 2018-09-07 01:40 UTC
**Community Note**

**_Just a heads up_** 

Please avoid updating to the latest AzureRM provider (1.14.0) that had removed blob containers automatically from our Azure Storage when it ran the first time.

**Description**
We have an automatic provider update configured for our dev environment whenever there is a new release. Today around 7-8 hours ago, when the new release v1.14.0 was released, we noticed our blob containers and azure storage resources were deleted during the refresh state phase. Upon initial investigation, we found out that it happened due to the version update from v1.13.0 to v1.14.0.

We are still investigating what caused the new release to destroy our azure storage resources and will keep posting here.

**New or Affected Resource(s)**
azurerm provider 1.14.0

**Potential Terraform Configuration**
azurerm provider 1.14.0

**Comment by tombuildsstuff** [comment] 2018-09-07 17:42
hey @Farishta 

Thanks for opening this issue :)

I've taken a look into this using the following Terraform Configuration:

```
provider "azurerm" {
  version = "=1.13.0" # and then `=1.14.0`
}

resource "azurerm_resource_group" "test" {
  name     = "tom-dev89"
  location = "West Europe"
  tags {
    hello = "World"
  }
}

resource "azurerm_storage_account" "test" {
  name                     = "tomdevsatest"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  location                 = "${azurerm_resource_group.test.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "test" {
  name                  = "vhds"
  resource_group_name   = "${azurerm_resource_group.test.name}"
  storage_account_name  = "${azurerm_storage_account.test.name}"
  container_access_type = "private"
}

resource "azurerm_storage_blob" "testsb" {
  name                   = "image.jpg"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  storage_account_name   = "${azurerm_storage_account.test.name}"
  storage_container_name = "${azurerm_storage_container.test.name}"
  source                 = "image.jpg"
  type                   = "block"
}
```

After running `terraform apply` from v1.13 -> v1.14 of the AzureRM Provider, I'm unable to repro this (see the plan below):

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tom-dev89)
azurerm_storage_account.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-...t.Storage/storageAccounts/tomdevsatest)
azurerm_storage_container.test: Refreshing state... (ID: vhds)
azurerm_storage_blob.testsb: Refreshing state... (ID: image.jpg)

------------------------------------------------------------------------


No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

I've also tried reproducing this using v1.12 of the AzureRM Provider and then upgrading to v1.14 of the Provider - but I've been unsuccessful.

So that we could take a further look into this would you be able to give a reproduceable example of this issue?

Whilst the ID's for these resources have changed in the most recent version of the Provider, there's a state migration which updates the old format ID -> the new format ID, such that there shouldn't be any recreation.

Thanks!

**Comment by Farishta** [comment] 2018-09-10 04:45
G'day @tombuildsstuff 

Thanks for looking into the reported bug and attempting to reproduce.

We investigated further and found the issue due to the case sensitivity for the required (breaking) field values. It looks like the latest provider (v1.14) is forcing the input values into lower case as illustrated in the example below: (you can reproduce the issue by using the resource below)

## Queue - events
resource "azurerm_storage_queue" "tenant_queue_events" {
  name                 = "temp-emails"
  resource_group_name  = "Fake-Shared-Resources"
  storage_account_name = "${var.storage_account_name}"
}

## terraform plan output

-/+ azurerm_storage_queue.tenant_queue_emails (new resource required)
      id:                    "https://fake.queue.core.windows.net/temp-emails" => <computed> (forces new resource)
      name:                  "temp-emails" => "temp-emails"
      resource_group_name:   "**fake-shared-resources**" => "**Fake-Shared-Resources**" (forces new resource)
      storage_account_name:  "fake" => "fake"

We are following the pascal casing for our resource names i.e. specifically for the resource group as above highlighted. The case sensitivity issue has started happening in the latest v1.14 azurerm provider. 

This explains why it is trying to remove the existing resources that were created by following pascal case. Since Azure allows both upper and lower cases, the provider should not force lower casing for the RSG.

Hope it makes sense. Please feel free to discuss with me if you have any further queries/concerns.

Cheers!

**Comment by Farishta** [comment] 2018-09-12 00:17
Thanks @katbyte for the response.

Sorry I think I could have explained the reproduce steps better earlier and I also believe a picture worth more than thousand words as shown below (**Note**: we just executed 'plan' command after creating new resources and it shows destruction of the resource due to the change in the RSG name):

![image](https://user-images.githubusercontent.com/2209778/45394423-d1abed80-b673-11e8-8e2b-b2649d356076.png)

I suspect it is happening due to the resource group was created ages ago using earlier terraform version and pascal case. Somehow the existing created resource group name "peoplestreme-hcm-shared-resources" => "Peoplestreme-Hcm-Shared-Resources" (forces new resource)" is causing the issue. 

(**Important**: when we change the RSG name to lower case then it does not detect any difference)

You may try using a RSG that was created using the earlier version and then use that RSG to create new resource as shown in the snapshot.

Hope it helps to reproduce the issue.

**Comment by tombuildsstuff** [comment] 2018-09-12 10:10
hey @Farishta 

Thanks for posting that update - that helps clarify things.

Versions of the AzureRM Provider prior to v1.14 had a bug in the `azurerm_storage_{name}` resources where the fields in the schema weren't set to the values returned from the API. v1.14 of the Provider included a fix for this such that these fields are now set (which also allows these resources to be Imported) - which is why you're seeing this issue.

Based on what I can see from the above configuration/screenshot - it appears the name of the Resource Group is actually in lower-case - would you be able to confirm if this is the case via the Portal?

There's a separate bug in the AzureRM Provider (due to the Azure API's being different to the API's of other Providers [technically they support Upserting where most API's have separate Create and Update methods]) where existing resources can be re-created without importing them into the state first (which will be solved via #1746) which I believe may be the underlying cause in this instance.

Thanks!

**Comment by Farishta** [comment] 2018-09-13 01:15
Hey @tombuildsstuff 

Good to hear that clarified the issue.

Cool! that make sense to me. Also, I verified on the Azure portal that it is all lowercase.

Wondering does it mean we need to make it lowercase everywhere to avoid destruction of the resources? or there is going to be a fix that should compare state by lowering the casing first?

Given that Terraform allows inputting upper case name for creating the resource, it would always be a problem when it compare with the values returned from the API. Isn't it?

**Comment by katbyte** [comment] 2018-09-19 17:27
@Farishta,

You are correct. You can either change your terraform to be match what exists, or recreate the resource group to match your desired casing.

**Comment by tombuildsstuff** [comment] 2018-10-22 19:46
hey @Farishta 

Thanks for confirming that - given this issue appears to be resolved - I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2018-10-22 19:46 UTC
Labels: question, service/storage, waiting-response
