### ISSUE TITLE
No way to attach managed_disk as Data disk to a existing VM?

### ISSUE THREAD

**Issue by woosley** [terraform-providers/terraform-provider-azurerm#1014] opened 2018-03-21 14:04 UTC
I am trying to accomplish VM creation and data disk attachment in this order

1) create a managed_disk 
2) create a VM, without creating any data disk
3) attach the managed_disk as datadisk to the created VM 

but it seems not possible accroding to the document. The only way to create data disk for a VM is when a vm is created by ` azurerm_virtual_machine ` with `storage_os_disk`

is there any limitation in the backgroud or this feature is just missing? I really want this feature if possible.

**Comment by jeffreyCline** [comment] 2018-03-31 00:11
Thanks for reporting this issue. Closing this as a duplicate of #734. Please track status of this with that issue.

**Comment by tombuildsstuff** [comment] 2018-04-13 09:42
re-closing this since it’s a duplicate

**Closed** 2018-04-13 09:42 UTC
Labels: microsoft/2, question, service/disks, service/virtual-machine

**Comment by woosley** [comment] 2018-04-16 05:41
this is done? can you provide any link to the changes related?

**Comment by tombuildsstuff** [comment] 2018-04-16 06:35
@woosley this is a duplicate of #734 where this work is being tracked. Please ignore the “done” state above, that’s coming from a GitHub project. Thanks!

**Comment by woosley** [comment] 2018-04-16 07:14
I don't think it is duplicated. what I want is something like old azure_data_disk described here 
https://www.terraform.io/docs/providers/azure/r/data_disk.html. The issue described in #734 is just the new data disk can not be attached.
