### ISSUE TITLE
Hardcoded signedVersion for SAS key in azurerm_storage_account_blob_container_sas

### ISSUE THREAD

**Issue by vamsik302** [terraform-providers/terraform-provider-azurerm#12083] opened 2021-06-07 06:55 UTC
Signed version need to be taken as a configurable parameter in data "azurerm_storage_account_blob_container_sas'. Currently it is hardcoded to "2018-11-09".

**Comment by tombuildsstuff** [comment] 2021-06-07 10:32
Duplicate of #6519

**Closed by tombuildsstuff** 2021-06-07 10:32 UTC
