### ISSUE TITLE
r/redis_cache: Add support for Redis 6

### ISSUE THREAD

**Issue by andrei-dascalu** [terraform-providers/terraform-provider-azurerm#9403] opened 2020-11-19 17:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently in Azure there is the possibility of choosing either Redis 4 or Redis 6 (preview). As of now azurerm_redis_cache doesn't seem to have an option to make a choice.

### New or Affected Resource(s)

azurerm_redis_cache
azurerm_redis_linked_server (presumably?)

### Potential Terraform Configuration

Not sure about where this could go, whether this would be a `redis_configuration` item or a simple `version` key

Thanks!

**Comment by anasokan** [comment] 2020-12-10 03:14
Any update on this support.
It would be required as azure started supporting redis 6

**Comment by maxkuzkin** [comment] 2021-02-16 19:07
It might be better to change the title of this issue to "**Add support for Redis 6**", because, practically speaking, it's not possible to use Redis 6 without this feature today. Thus, I'm not even sure what was the idea of people who announced Redis 6 Preview back in November?... Anyone who automates their deployment (which is the target audience of services like Reddis most likely) is currently not able to use it in their scenarios.

**Comment by tombuildsstuff** [comment] 2021-02-17 11:16
👋 

Taking a look through here it appears there's a couple of different things to call out here:

1. Support for `Azure Redis Cache` running v6 of Redis appears to be possible by setting `"redisVersion": "6"` within the `properties` block - however support for this isn't available in the Azure SDK at this point (only as a read-only value). As such this'd need Microsoft to support this within the Azure SDK for us to be able to support this in Terraform - @WodansSon would you mind running that down?
2. Support for `Azure Redis Enterprise Cache` - which _does_ include [support for Redis 6 in the SDK](https://github.com/Azure/azure-sdk-for-go/blob/4b77208ea6e3bb79d5235efeaf699f1c31a16908/services/preview/redisenterprise/mgmt/2020-10-01-preview/redisenterprise/models.go#L353-L366) - however this [looks to be an entirely separate service](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/quickstart-create-redis-enterprise)

Whilst this issue is tracking the former - and so at this point is blocked on the Azure SDK adding support for this - if you're looking for support for Redis Enterprise, please open a separate Feature Request so that we can track that specifically.

Thanks!

**Comment by NillsF** [comment] 2021-02-26 21:17
@tombuildsstuff @WodansSon: I believe the issue is not (only) an SDK issue, but a [raw API issue ](https://docs.microsoft.com/en-us/rest/api/redis/redis/create) for Redis. Based on what I'm seeing in the API documentation, the redisVersion property is not available as a property in the body on the create request and only is available on the returned object.

**Comment by steph-moto** [comment] 2021-04-07 01:30
Has there been any updates on this.  I truly believe it would be beneficial to have this supported from terraform

**Comment by tomatwoodliquidx** [comment] 2021-06-22 03:12
Any status update on this item?

**Comment by Poil** [comment] 2021-08-03 07:27
Hi,

The SDK have been updated to support [API 2020-1201](https://github.com/terraform-providers/terraform-provider-azurerm/pull/12565).
We just need a patch to support the "version" parameter 

Best regards

**Comment by Poil** [comment] 2021-08-04 13:32
https://github.com/terraform-providers/terraform-provider-azurerm/pull/12820

**Comment by tombuildsstuff** [comment] 2021-08-05 10:02
Fixed via #12820

**Closed by tombuildsstuff** 2021-08-05 10:02 UTC
Labels: enhancement, sdk/not-yet-supported, sdk/requires-swagger-changes, service/redis, upstream-microsoft
