### ISSUE TITLE
`azurerm_logic_app_workflow` support for customized parameters

### ISSUE THREAD

**Issue by magodo** [terraform-providers/terraform-provider-azurerm#11505] opened 2021-04-28 09:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Per [the resource document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow#parameters), currently, the `azurerm_logic_app_worflow` only supports to specify parameters that are defined in the designated schema file. Whilst the API actually allows users to define the model of customized parameters (though not defined in Swagger, the `definition` is an plain `object`):

![image](https://user-images.githubusercontent.com/7970698/116378530-cddd3180-a844-11eb-942b-efcf45b4f1a4.png)

### New or Affected Resource(s)

* azurerm_logic_app_workflow

### Potential Terraform Configuration

```hcl
resource "azurerm_logic_app_workflow" "example" {
  name                = "workflow1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  parameter_definitions = <<EOF
{
  "$connections": {
    "defaultValue": {},
    "type": "Object"
  }
}
EOF
}
```

**Comment by tombuildsstuff** [comment] 2021-04-28 09:29
Duplicate of #1691

**Closed by tombuildsstuff** 2021-04-28 09:29 UTC
Labels: enhancement, service/logic

**Comment by magodo** [comment] 2021-04-28 14:00
@tombuildsstuff I saw #1691 and I didn't think this issue is a duplication to that, as this issue is about "linking" an existed connection to a workflow, whilst #1691 is about creating a connection resource.

**Comment by alexinthesky** [comment] 2021-05-10 15:17
same here, this is not a duplicate, as [#1691](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1691) is for creating a separate api Connection object ( =resourceType/Microsoft.Web%2Fconnections ), whereas this is to be able to give these API connections to a logic app workflow ( add them in the azurerm_logic_app_workflow  parameters )
