### ISSUE TITLE
Support for CosmosDB - Enable Synapse Link

### ISSUE THREAD

**Issue by ksista-ahc** [terraform-providers/terraform-provider-azurerm#10419] opened 2021-02-01 22:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there a way to enable Azure Synapse Link when creating azurerm_cosmosdb_account?

### New or Affected Resource(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.resource_group_location
}

resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"
  
  enable_analytical_store = true
  analytical_store_ttl = -1
  enable_automatic_failover = true

  enable_synapse_link = true

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 10
    max_staleness_prefix    = 200
  }

  geo_location {
    location          = var.failover_location
    failover_priority = 1
  }

  geo_location {
    prefix            = "tfex-cosmos-db-${random_integer.ri.result}-customid"
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/cosmos-db/configure-synapse-link

**Comment by T1loc** [comment] 2021-02-05 17:12
Duplicate of : https://github.com/terraform-providers/terraform-provider-azurerm/issues/10419

**Comment by favoretti** [comment] 2021-02-11 00:02
Unfortunately from the looks of it it's not yet supported even by the latest SDK.

**Comment by bm77525-kr** [comment] 2021-04-27 15:52
It looks like this should be available as noted [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10198#issuecomment-822799598)

**Comment by katbyte** [comment] 2021-06-24 03:40
Hey @ksista-ahc - looks like this was added in #11655 so i'm going to close this

**Closed by katbyte** 2021-06-24 03:40 UTC
Labels: enhancement, service/cosmosdb, service/synapse
