### ISSUE TITLE
AuthorizationPermissionMismatch when creating Azure Data Lake Storage gen2 Filesystems

### ISSUE THREAD

**Issue by sdebruyn** [terraform-providers/terraform-provider-azurerm#6934] opened 2020-05-14 22:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.25
+ provider.azuread v0.8.0
+ provider.azurerm v2.9.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_role_assignment`
* `azurerm_storage_data_lake_gen2_filesystem`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 2.9.0"
  features {}
}

data "azurerm_client_config" "current" {

}

resource "azurerm_resource_group" "rg" {
  location = "eastus2"
  name     = "repro"
}

locals {
  amount_accounts               = 6
  amount_containers_per_account = 2
  amount_containers             = local.amount_accounts * local.amount_containers_per_account
}

resource "random_string" "random" {
  length  = 6
  special = false
  upper   = false
}

resource "azurerm_storage_account" "sa" {
  count                    = local.amount_accounts
  resource_group_name      = azurerm_resource_group.rg.name
  account_replication_type = "LRS"
  name                     = "repro${count.index}${random_string.random.result}"
  account_tier             = "Standard"
  location                 = azurerm_resource_group.rg.location
  is_hns_enabled           = true
  access_tier              = "Cool"
}

resource "azurerm_role_assignment" "ra" {
  count                = local.amount_accounts
  scope                = azurerm_storage_account.sa[count.index].id
  role_definition_name = "Storage Blob Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_storage_data_lake_gen2_filesystem" "filesystems" {
  count              = local.amount_containers
  depends_on         = [azurerm_role_assignment.ra]
  name               = "container${count.index}"
  storage_account_id = azurerm_storage_account.sa[floor(count.index / local.amount_containers_per_account)].id
}
```

### Debug Output

https://gist.github.com/sdebruyn/505a7050bd5768b99fc80895a7d85d96
### Expected Behavior

Filesystem is created.

### Actual Behavior

```
Error: Error creating File System "container3" in Storage Account "repro185u69s": datalakestore.Client#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized to perform this operation using this permission."
```

### Steps to Reproduce

1. `terraform apply`

You might have go back and forth between `apply` and `destroy` a couple of times, although I almost always have it on the first try.

### Important Factoids

No sane person will probably do something like in the excerpt above... However, I have this issue with a lot less resources here: https://github.com/datarootsio/terraform-module-azure-datalake/issues/68

The problem seems to be that the role assignment is not really created when the HTTP response comes back and you have to wait for a bit before it is really created.

**Comment by sdebruyn** [comment] 2020-05-15 08:28
Same issue with v2.10.0

**Comment by yupwei68** [comment] 2020-05-18 03:38
Hi @sdebruyn thanks for opening this issue. On fact, when you add or remove role assignments, it can take up to 30 minutes for changes to take effect, according to https://docs.microsoft.com/en-us/azure/role-based-access-control/troubleshooting#role-assignment-changes-are-not-being-detected. I would like to suggest a walk-around solution by adding a dependent resource of waiting 10 minutes to prevent the intermittent error.

```
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 600"
  }
  depends_on         = [azurerm_role_assignment.ra]
}

resource "azurerm_storage_data_lake_gen2_filesystem" "filesystems" {
  depends_on         = [null_resource.delay]
  name               = "container"
  storage_account_id = azurerm_storage_account.sa.id
}
```

**Comment by ArcturusZhang** [comment] 2020-06-05 03:19
Hi @sdebruyn 

Glad to see you have performed the work around! Since this is actually caused by some limitation of Azure itself, and it would be not so appropriate to add this kind of sleep logic in the provider, therefore I would close this issue hope you would not mind. If you feel there are more things to add or discuss, please feel free to reopen. Thank you!

**Closed by ArcturusZhang** 2020-06-05 03:19 UTC
Labels: service/data-lake
