### ISSUE TITLE
Azure APIM Backend creation fails with rpc timeout error

### ISSUE THREAD

**Issue by venkatadorisala** [terraform-providers/terraform-provider-azurerm#10903] opened 2021-03-09 21:58 UTC
I'm trying to add a functionapp backend to Azure API Management resource. But it fails with below error.

`AzureRM: 2.50.0 and below`
`Terraform: 0.14.6`

```
resource "azurerm_api_management_backend" "function" {
  name                = "function-backend"
  description         = "description"
  resource_group_name = data.azurerm_resource_group.apim-rg.name
  api_management_name = data.azurerm_api_management.platform.name
  protocol            = "http"
  resource_id         = data.azurerm_function_app.function.id
  url                 = "https://url.com/api"
}

```
Error log:
```
2021/03/09 21:54:06 [TRACE] EvalWriteState: using RefreshState for azurerm_api_management_backend.function
2021/03/09 21:54:06 [TRACE] EvalWriteState: removing state object for azurerm_api_management_backend.function
2021/03/09 21:54:06 [TRACE] Re-validating config for "azurerm_api_management_backend.function"
2021/03/09 21:54:06 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/03/09 21:54:06 [TRACE] GRPCProvider: PlanResourceChange
2021/03/09 21:54:06 [TRACE] EvalWriteState: writing current state object for azurerm_api_management_backend.function
2021/03/09 21:54:06 [TRACE] EvalWriteDiff: recorded Create change for azurerm_api_management_backend.function
2021/03/09 21:54:06 [TRACE] vertex "azurerm_api_management_backend.function": visit complete
2021/03/09 21:54:06 [TRACE] vertex "azurerm_api_management_backend.function": dynamic subgraph completed successfully
2021/03/09 21:54:06 [TRACE] vertex "azurerm_api_management_backend.function": visit complete
2021/03/09 21:54:06 [TRACE] vertex "azurerm_api_management_backend.function (expand)": dynamic subgraph completed successfully
2021/03/09 21:54:06 [TRACE] vertex "azurerm_api_management_backend.function (expand)": visit complete
2021/03/09 21:54:06 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/03/09 21:54:06 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2021/03/09 21:54:06 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/03/09 21:54:06 [INFO] backend/local: plan operation completed

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7757177 vs. 4194304)
```

**Comment by tombuildsstuff** [comment] 2021-03-10 08:37
hi @venkatadorisala 

Thanks for opening this issue.

Unfortunately there's not enough information above for us to be able to reproduce this, based on these lines:

> 2021/03/09 21:54:06 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
> 2021/03/09 21:54:06 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping

It appears that this issue is with a dependency of the Azure Provider, rather than the provider directly - but without the full debug log it's hard to confirm unfortunately.

Since there's not enough information above to be able to diagnose this, I'm going to close this issue for the moment, but if you're able to [complete the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md) which contains all of the information we need (including a full debug log) then we should be able to take a look and track down where this is happening.

Thanks!

**Closed by tombuildsstuff** 2021-03-10 08:37 UTC
