### ISSUE TITLE
Support for adding a Logic App to an Integration Service Environment

### ISSUE THREAD

**Issue by thomasdewulf** [terraform-providers/terraform-provider-azurerm#8325] opened 2020-09-02 13:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Make it possible inside Terraform to add a Logic App to an Integration Service Environment.

### New or Affected Resource(s)

- azurerem_logic_app_workflow
- azurerm_integration_service_environment

**Comment by tombuildsstuff** [comment] 2020-09-02 14:12
hi @thomasdewulf 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8229 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8229 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-09-02 14:12 UTC
Labels: duplicate, service/logic

**Comment by thomasdewulf** [comment] 2020-09-02 14:25
Hi @tombuildsstuff 

I saw that issue already, but I don't see the relation with an integration account? 

Going from the Azure docs, it seems to be possible to put a Logic App inside an ISE without using an integration account?

It uses the 'location' property to put the Logic App inside the ISE rather than in a region like 'West Europe'.

https://docs.microsoft.com/en-us/azure/logic-apps/connect-virtual-network-vnet-isolated-environment

**Comment by jackofallops** [comment] 2020-09-03 11:13
Hi @thomasdewulf 
I'm in the process of updating the referenced PR to expand the scope accommodate this, but I've not updated the description yet - I'll do so when I've tested and push the associated code changes.
