### ISSUE TITLE
Support for Automated Key Rotation for azurerm_storage_account_customer_managed_key

### ISSUE THREAD

**Issue by jaredledvina** [terraform-providers/terraform-provider-azurerm#6149] opened 2020-03-17 21:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when leveraging the `azurerm_storage_account_customer_managed_key` resource, passing in a specific key version is required. It appears that the result is that "Automated Key Rotation" is disabled. 

When we select CMK's via the Portal UI, it appears that we can't specify a specific version and that "Automated Key Rotation" is enabled. I would ideally be able to configure this via Terraform such that 'Automated Key Rotation' is enabled. 

### New or Affected Resource(s)

* azurerm_storage_account_customer_managed_key

### Potential Terraform Configuration

```hcl
# Unsure here, maybe `version` shouldn't be required?
```

**Comment by ashrayjain** [comment] 2020-03-17 21:55
Based on this issue: https://github.com/MicrosoftDocs/azure-docs/issues/31491#issue-445509822, it looks like the empty string value for version would make Azure use the "current" version.

**Comment by IanMoroney** [comment] 2020-07-20 16:37
@ashrayjain , the issue preventing this right now is that Terraform says:
`Error: expected "key_version" to not be an empty string, got`
Is that correct?

**Comment by IanMoroney** [comment] 2020-07-21 22:09
I've wrote a fix for this in the provider and issued a PR for the changes.
I can confirm that it will enable Automatic Key Rotation so long as a key_version is not specified (I have set the parameter to be optional).

**Closed** 2020-09-17 13:13 UTC
Labels: enhancement, service/storage
