### ISSUE TITLE
Allow App Service Settings to be set independently

### ISSUE THREAD

**Issue by syedhassaanahmed** [terraform-providers/terraform-provider-azurerm#6903] opened 2020-05-13 17:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We're using Terraform to create Key Vault, an App Service and pre-populate App Service Settings using [Key Vault references](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references). As part of App Service creation, we've specified [system-assigned managed identity](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#identity). Currently App Settings can't be specified on its own and must be specified within `azurerm_app_service` in the `app_settings` block. Setting key vault references in `app_settings` fails because the system-assigned managed identity is also created as part of `azurerm_app_service` and doesn't yet exist.

A better solution would be, if we were allowed to create App Settings separately. Then we could do the following in Terraform
* Provision Key Vault
* Provision App Service with system-assigned managed identity
* Assign appropriate role to above identity on the Key Vault
* Provision App Service settings with Key Vault references.

### New or Affected Resource(s)

* azurerm_app_service_settings

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_settings" "example" {
  app_service_id = azurerm_app_service.example.id

  app_settings = {
    "SOME_KEY" = "some-value"
  }
}
```

### References

* #0000

**Comment by StefanSchoof** [comment] 2020-05-13 19:13
You should be able to break the cycle with a sperate [azurerm_key_vault_access_policy](https://www.terraform.io/docs/providers/azurerm/r/key_vault_access_policy.html)

**Comment by syedhassaanahmed** [comment] 2020-05-13 19:27
@StefanSchoof We're already using a separate `azurerm_key_vault_access_policy` but it doesn't break the cycle.

**Comment by StefanSchoof** [comment] 2020-05-13 19:42
I have [here](https://github.com/StefanSchoof/espresso/blob/e45d13b112fa664587999550e80300c0c946fb21/deploy/main.tf#L104) code (with a azure function and not a web app) that is creating a Key Vault Reference and using the system identity. But maybe your requirement is a little bit different.

**Comment by StefanSchoof** [comment] 2020-05-13 20:03
A another thing, in this area you may run into #3129

**Comment by syedhassaanahmed** [comment] 2020-05-13 21:25
@StefanSchoof many thanks for the help. [Here](https://github.com/syedhassaanahmed/tf-kv-appservice/blob/master/main.tf) is my template that doesn't work. After applying the template, if you navigate to the App Service Settings, you'll see the identity access denied error in the Key Vault reference. Re-applying the template doesn't help, however restarting the App Service fixes the reference. I suspect its a lifecycle issue, when the app setting is referencing the key vault, the access policy on managed identity doesn't yet exist, hence its marked as failed. Maybe the lifecycle is different in case of a Functions App.
PS: I haven't run into #3129 probably because I'm using [this trick](https://blog.eldert.net/reference-key-vault-secret-latest-version/) to always get latest version of the secret.

**Comment by tombuildsstuff** [comment] 2020-05-14 06:54
hi @syedhassaanahmed 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1212 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1212 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-14 06:54 UTC
Labels: duplicate, enhancement, service/app-service

**Comment by StefanSchoof** [comment] 2020-05-14 07:32
@syedhassaanahmed Thanks for the "trick". I think I have just a Use Case where this is helping me.
