### ISSUE TITLE
Unable to output public IP of a azure VM attached to availability set+load balancer

### ISSUE THREAD

**Issue by harshagv** [terraform-providers/terraform-provider-azurerm#8445] opened 2020-09-13 04:42 UTC
```
$ terraform output vm_public_ip_address
Output: <empty string>
```

### Terraform (and AzureRM Provider) Version
```
- random v2.3.0
- template v2.1.2
- azurerm v2.26.0
- terraform v0.13.1
```

### Affected Resource(s)
`azurerm_public_ip.vm_name.ip_address`

### Terraform Configuration Files
```hcl
provider "azurerm" {
  version = "~>2.0"
  features {}
}

data "azurerm_resource_group" "azresgroup" {
  name = var.az_res_group
}

data "azurerm_subnet" "azsubnet" {
  name = var.az_subnet
  virtual_network_name = var.az_virtual_nw_name
  resource_group_name  = var.az_res_group
}

data "azurerm_network_security_group" "nsg_name" {
  name = var.az_nsg_name
  resource_group_name = var.az_res_group
}

data "template_file" "vm_init_script" {
  template = file("../scripts/initialize_setup.sh")
}

resource "random_string" "randomId" {
  length = 4
  upper = false
  number = true
  lower = false
  special = false
}

resource "random_string" "vm-name" {
  length = 5
  upper = false
  number = false
  lower = true
  special = false
}

resource "azurerm_public_ip" "simplified_stack_public_ip" {
  name = "${var.az_public_ip_name}${random_string.randomId.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  allocation_method = "Dynamic"

  tags = {
    owner = "gvh",
    buildID = var.jenkins_buildID
  }
}

resource "azurerm_network_interface" "nw_interface_name" {
  name = "${var.az_nw_interface_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  ip_configuration {
    name = "${var.az_ip_configuration}${random_string.vm-name.result}"
    subnet_id = data.azurerm_subnet.azsubnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id = azurerm_public_ip.simplified_stack_public_ip.id
  }

  tags = {
    owner = "gvh",
    buildID = var.jenkins_buildID
  }
}

resource "azurerm_network_interface_security_group_association" "nw_interface_nsg_assoc" {
  network_interface_id = azurerm_network_interface.nw_interface_name.id
  network_security_group_id = data.azurerm_network_security_group.nsg_name.id
}

data "azurerm_lb" "simplified_loadbalancer" {
  name = var.az_loadbalancer_name
  resource_group_name = var.az_res_group
}

data "azurerm_lb_backend_address_pool" "simplified_backend_pool" {
  name = var.az_backendpool_name
  loadbalancer_id = data.azurerm_lb.simplified_loadbalancer.id
}

data "azurerm_availability_set" "simplified_avail_set" {
  name = var.az_availability_set_name
  resource_group_name = var.az_res_group
}

resource "azurerm_network_interface_backend_address_pool_association" "simplified_backend_pool_assoc" {
  network_interface_id = azurerm_network_interface.nw_interface_name.id
  ip_configuration_name = "${var.az_ip_configuration}${random_string.vm-name.result}"
  backend_address_pool_id = data.azurerm_lb_backend_address_pool.simplified_backend_pool.id
}

resource "azurerm_managed_disk" "simplified_stack_mgd_disk" {
  name = "${var.az_managed_disk_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  storage_account_type = var.az_storage_acc_type
  create_option = "Empty"
  disk_size_gb = var.az_managed_disk_size

  tags = {
    environment = "staging-db"
    owner = "gvh"
    buildID = var.jenkins_buildID
  }
}

resource "azurerm_virtual_machine" "simplified-stack-vm" {
  name = "${var.az_vm_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  availability_set_id = data.azurerm_availability_set.simplified_avail_set.id
  network_interface_ids = [ azurerm_network_interface.nw_interface_name.id ]
  vm_size = var.az_vm_size

  storage_image_reference {
    publisher = "Canonical"
    offer = "UbuntuServer"
    sku = "18.04-LTS"
    version = "latest"
  }

  storage_os_disk {
    name = "${var.az_os_disk_name}${random_string.randomId.result}${random_string.randomId.result}"
    create_option = "FromImage"
    caching = "ReadWrite"
    disk_size_gb = var.az_os_disk_size
  }

  os_profile {
    computer_name = "${var.az_vm_name}${random_string.vm-name.result}"
    admin_username = var.az_vm_admin_user_name
    custom_data = base64encode(data.template_file.vm_init_script.rendered)
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path = "/home/${var.az_vm_admin_user_name}/.ssh/authorized_keys"
      key_data = file("../scripts/ssh-key-azure.pub")
    }
  }

  tags = {
    environment = var.env_type,
    owner = "gvh"
    buildID = var.jenkins_buildID
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "attach_managed_disk" {
  managed_disk_id = azurerm_managed_disk.simplified_stack_mgd_disk.id
  virtual_machine_id = azurerm_virtual_machine.simplified-stack-vm.id
  lun = "10"
  caching = "ReadWrite"
}

output "vm_public_ip_address" {
  value = azurerm_public_ip.simplified_stack_public_ip.ip_address
}
```

### Panic Output
<empty string>

### Expected Behavior
User shall be able to fetch/output the public IP of a azure VM attached to availability set+load balancer

### Actual Behavior
Unable to output public IP of a azure VM attached to availability set+load balancer

### Steps to Reproduce
```bash
$ az login
$ az account set -s <id>
$ terraform init
$ terraform plan
$ terraform apply 
```

#### PS: 
Was able to fetch the public IP for the same VM using azure-CLI
```
$ az vm show -d -g $RESOURCE_GROUP -n $VM_NAME --query publicIps -o tsv
```

### References
https://www.terraform.io/docs/providers/azurerm/r/lb.html
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html

* #0000

**Comment by ArcturusZhang** [comment] 2020-09-15 03:32
Hi @harshagv thanks for this issue!

Since our resource `azurerm_virtual_machine` is in feature-frozen mode, a lot of further enhancements are not introduced to it (please check out the disclaimer [here](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#disclaimers)). In the new resource `azurerm_linux_virtual_machine`, we support the output `public_ip_addresses` (please see the documentation [here](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html)). But due to some limitation of Azure, this public ip address may not be allocated immediately, therefore in some cases, you may not be able to get the public ip addresses right after the provisioning is completed.

**Comment by harshagv** [comment] 2020-09-15 11:21
Thanks for your reply @ArcturusZhang!

I changed my script to use the resource `azurerm_linux_virtual_machine` and I still do not see the public IP address of the VM attached but the same can be retrieved by using azure CLI right after `terraform apply`, is it not an issue with the terraform?

```HCL
resource "azurerm_linux_virtual_machine" "simplified-stack-vm" {
  name = "${var.az_vm_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  size  = var.az_vm_size
  network_interface_ids = [ azurerm_network_interface.nw_interface_name.id ]
  availability_set_id = data.azurerm_availability_set.simplified_avail_set.id
  admin_username  = var.az_vm_admin_user_name
  computer_name = "${var.az_vm_name}${random_string.vm-name.result}"
  disable_password_authentication = true
  custom_data = base64encode(data.template_file.vm_init_script.rendered)

  admin_ssh_key {
    username  = var.az_vm_admin_user_name
    public_key = file("../scripts/ssh-key-azure.pub")
  }

  os_disk {
    name = "${var.az_os_disk_name}${random_string.randomId.result}${random_string.randomId.result}"
    caching = "ReadWrite"
    storage_account_type = var.az_storage_acc_type
    disk_size_gb = var.az_os_disk_size
  }

  source_image_reference {
    publisher = "Canonical"
    offer = "UbuntuServer"
    sku = "18.04-LTS"
    version   = "latest"
  }

  tags = {
    environment = var.env_type,
    owner = "gvh"
    buildID = var.jenkins_buildID
  }
}
```

**Comment by ArcturusZhang** [comment] 2020-09-16 06:45
Yeah... as documented in [the disclaimer](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html#disclaimers) of `azurerm_linux_virtual_machine`, it is a known issue that the dynamic public ip address cannot be populated in one single apply. To workaround this, you will have to run another `terraform refresh` and get that public ip address in the vm, like this:
![image](https://user-images.githubusercontent.com/10554446/93301561-36821b80-f82b-11ea-8539-d29d0b8a5a1a.png)

**Comment by tombuildsstuff** [comment] 2020-09-16 09:52
@harshagv the Public IP Address of Dynamic Public IP's (and Dynamic Private IP's, fwiw) cannot be retrieved until the Network Interface they're part of is attached to something in a running state, be that a virtual machine or a load balancer etc which is unfortunately by design within Azure.

As such, this won't have an IP Address until it's attached to something (and when we retrieve the state of the Public IP Address/Network Interface when we create it, it's not attached to anything). Instead you should be able to use the data sources for `azurerm_network_interface` and `azurerm_public_ip` to retrieve this once the virtual machine has been created using a `depends_on`, to force the ordering here.

Whilst the new `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources expose a property within those resources for the private IP address, as @ArcturusZhang has mentioned these currently suffer from the same limitation (but this is a bug we intend to fix in time, which is why this is documented) - however you should be able to work around this by using a data source to retrieve this information once the Public IP Address (and Network Interface) have been attached to the Virtual Machine (by using a depends_on on the virtual machine resource) as outlined above.

Since this should be fixed by updating the Terraform Configuration to include a data source, I'm going to close this issue for the moment however should you need further assistance I'd recommend taking a look at [one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-09-16 09:52 UTC
Labels: question, service/virtual-machine, waiting-response
