### ISSUE TITLE
AKS failing to create in subnet with CIDR overlap error

### ISSUE THREAD

**Issue by FirstInternetUser** [terraform-providers/terraform-provider-azurerm#3778] opened 2019-07-03 08:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform_0.12.3

### Affected Resource(s)

AKS is being affected while deploying to Azure

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "rpmi_log_analytics_workspace" {
  name                = "${var.log_analytics_workspace_name}"
  location            = "${var.log_analytics_workspace_location}"
  resource_group_name = "${var.resource_group_name}"
  sku                 = "${var.log_analytics_workspace_sku}"
}

resource "azurerm_log_analytics_solution" "log_analytics_solution" {
  solution_name         = "ContainerInsights"
  location              = "${azurerm_log_analytics_workspace.rpmi_log_analytics_workspace.location}"
  resource_group_name   = "${var.resource_group_name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.rpmi_log_analytics_workspace.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.rpmi_log_analytics_workspace.name}"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.cluster_name}"
  location            = "${var.k8slocation}"
  resource_group_name = "${var.resource_group_name}"
  dns_prefix          = "${var.dns_prefix}"

  linux_profile {
    admin_username = "ubuntu"

    ssh_key {
      #key_data = "${file("${var.ssh_public_key}")}"
      key_data = "${var.ssh_public_key}"
    }
  }

  agent_pool_profile {
    name            = "agentpool"
    count           = "${var.agent_count}"
    vm_size         = "Standard_DS1_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = "/subscriptions/xxx/resourceGroups/xxx-SIT/providers/Microsoft.Network/virtualNetworks/xxx-SIT/subnets/SERVICES"
  }

  service_principal {
    client_id     = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = "${azurerm_log_analytics_workspace.rpmi_log_analytics_workspace.id}"
    }
  }

  network_profile {
    network_plugin = "azure"
    service_cidr = "10.0.4.0/25"
    dns_service_ip = "10.0.4.10"	
    docker_bridge_cidr = "172.17.0.1/16"
  }

}
```

### Expected Behavior

I'm expecting the AKS cluster to be deployed in the specified subnet.

### Actual Behavior

Getting a cidr overlap error:
```
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SubnetCidrOverlapServiceCidr" Message="AgentPoolProfile.VnetSubnetID 10.0.4.0/22 overlaps Service Cidr 10.0.4.0/25. Please choose a new Service Cidr" Target="networkProfile.serviceCIDR"

  on 30_k8s.tf line 21, in resource "azurerm_kubernetes_cluster" "k8s":
  21: resource "azurerm_kubernetes_cluster" "k8s" {
```
### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2019-11-17 16:39
hi @FirstInternetUser 

Thanks for opening this issue.

Taking a look into the error being returned from the Azure API here:

> "AgentPoolProfile.VnetSubnetID 10.0.4.0/22 overlaps Service Cidr 10.0.4.0/25. Please choose a new Service Cidr"

It appears the issue is the Subnet CIDR that you're attempting to use is in conflict with the default Kubernetes CIDR block - as such this isn't something we'd be able to work around in Terraform - instead you'll need to pick a different CIDR range here.

If you'd like to see this functionality (being able to configure the Service CIDR) added to AKS - I'd suggest [opening an issue on their repository](https://github.com/Azure/AKS/issues) where they should be able to take a look; however since this isn't something we're able to fix within the Azure Provider I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2019-11-17 16:39 UTC
Labels: question, service/kubernetes-cluster
