### ISSUE TITLE
Support for daily cap in azurerm_application_insights a.k.a. 'currentbillingfeatures'

### ISSUE THREAD

**Issue by evertonmc** [terraform-providers/terraform-provider-azurerm#5175] opened 2019-12-16 10:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is currently no way to set the application insights  [daily cap](https://docs.microsoft.com/en-us/azure/azure-monitor/app/pricing#manage-your-maximum-daily-data-volume) with this provider

### New or Affected Resource(s)

* azurerm_application_insights

### References

* [go for it](https://github.com/Azure/azure-sdk-for-go/blob/master/services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go)

* [api specs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentFeaturesAndPricing_API.json#L37)

**Comment by tombuildsstuff** [comment] 2019-12-16 10:53
hi @evertonmc 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #584 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #584 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-12-16 10:53 UTC
Labels: duplicate, new-resource, service/application-insights
