### ISSUE TITLE
Storage custom domain indirect validation does not work

### ISSUE THREAD

**Issue by laurencee** [terraform-providers/terraform-provider-azurerm#2542] opened 2018-12-18 23:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.20.0

### Affected Resource(s)

* azurerm_storage_account - custom_domain

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "testsa" {
  name                     = "storageaccountname"
  resource_group_name      = "${azurerm_resource_group.testrg.name}"
  location                 = "westus"
  account_tier             = "Standard"
  account_replication_type = "GRS"

  custom_domain {
    name = "mycustomdomain.com"
    use_subdomain = true
  }
}
```

### Expected Behavior

Terraform applies the custom domain with domain indirect validation enabled

### Actual Behavior

Terraform fails to apply the custom domain with standard domain validation - the error from azure is:  
`The custom domain name could not be verified. CNAME mapping from mycustomdomain.com to any of test.blob.core.windows.net,test.z5.web.core.windows.net does not exist.`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This works when run manually from the azure portal ticking the "Use indirect CNAME validation" checkbox.
The `terraform apply` does work when setting use_subdomain to false and using the direct CNAME mapping approach.

**Comment by tombuildsstuff** [comment] 2019-01-04 16:36
@bernerha _interesting_ since you've got the context here would you mind [filing a bug about that on the Swagger repository](https://github.com/Azure/azure-rest-api-specs/issues) (which the Azure CLI and SDK's are generated from)? It appears that's a breaking change to the API which (IMO) should be reverted so the CLI and other providers work (and instead make the breaking change in a new API version)

Thanks!

**Comment by bernerha** [comment] 2019-01-09 10:00
Seems fixed. Now we have to wait for the release.
https://github.com/Azure/azure-rest-api-specs/issues/4995

**Comment by pijemcolu** [comment] 2019-10-11 10:10
Using the terraform versions 0.12.7 and up and azurerm provider 1.34.0. This now works for us.

```
terraform {
  required_version = ">= 0.12.7"
}

provider "azurerm" {
  version         = "=1.34.0"
  ...
}
resource "azurerm_storage_account" "sa" {
  ...
  custom_domain {
    name          = "${var.sa_custom_hostname}"
    use_subdomain = true
  }
```

**Comment by tombuildsstuff** [comment] 2019-10-11 12:17
Closing since @pijemcolu / @bernerha have confirmed that this is fixed in Terraform / the API respectively 👍

**Closed by tombuildsstuff** 2019-10-11 12:17 UTC
Labels: bug, service/storage, upstream-microsoft
