### ISSUE TITLE
azurerm_virtual_network accept only one value in subnet address_prefix preventing creation of ipv4 and ipv6 subnet

### ISSUE THREAD

**Issue by tradosh** [terraform-providers/terraform-provider-azurerm#10596] opened 2021-02-15 20:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0,14.5
AzureRM - v2.46.1

### Affected Resource(s)

azurerm_virtual_network

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  resource_group_name = var.resource_group_name
  location            = var.az_region
  address_space       = var.address_space
  dns_servers         = var.dns_servers
  tags                = var.tags

 subnet {
      name           = "name"
      address_prefix = "address_prefix"
      security_group = "nsg"
    }
}
```

### Expected Behaviour

the system should allow you to provide IPv4 and IPv6 values in the same line, similar to azurerm_subnet resource where it's looking for: address_prefixes value.

### Actual Behaviour

```
Error: Error Creating/Updating Virtual Network "network" (Resource Group "rg"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidAddressPrefixFormat" Message="Address prefix 172.16.68.64/26, fd9a:a0f:b1b1:9fe4::/64 of resource /subscriptions/*/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/network/subnets/name is not formatted correctly. It should follow CIDR notation, for example 10.0.0.0/24." Details=[]
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2021-02-16 06:45
hi @tradosh 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3917 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3917 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-16 06:45 UTC
Labels: duplicate, enhancement, service/virtual-networks
