### ISSUE TITLE
Azure cosmos db re-created when geo_locations are added/removed.

### ISSUE THREAD

**Issue by waleedexe** [terraform-providers/terraform-provider-azurerm#3839] opened 2019-07-12 10:58 UTC
### Terraform (and AzureRM Provider) Version

Terraform v0.12.3
+ provider.azurerm v1.31.0

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "cosmos_db" {
  name                      = "sample-test-geo"
  location                  = "uksouth"
  resource_group_name       = "grp-sample-test-geo"
  offer_type                = "Standard"
  enable_automatic_failover = true

  consistency_policy {
    consistency_level = "Session"
  }

  geo_location {
    location          = "uksouth"
    failover_priority = 0
  }
  # geo_location {
  #   location          = "ukwest"
  #   failover_priority = 1
  # }
}
```

### Plan log

```hcl
Terraform will perform the following actions:

  # azurerm_cosmosdb_account.cosmos_db must be replaced
-/+ resource "azurerm_cosmosdb_account" "cosmos_db" {
      ~ connection_strings                = (sensitive value)
        enable_automatic_failover         = true
        enable_multiple_write_locations   = false
      ~ endpoint                          = "https://sample-test-geo.documents.azure.com:443/" -> (known after apply)
      ~ id                                = "/subscriptions/xxx-xxx/resourceGroups/grp-sample-test-geo/providers/Microsoft.DocumentDB/databaseAccounts/sample-test-geo" -> (known after apply)
        is_virtual_network_filter_enabled = false
        kind                              = "GlobalDocumentDB"
        location                          = "uksouth"
        name                              = "sample-test-geo"
        offer_type                        = "Standard"
      ~ primary_master_key                = (sensitive value)
      ~ primary_readonly_master_key       = (sensitive value)
      ~ read_endpoints                    = [
          - "https://sample-test-geo-uksouth.documents.azure.com:443/",
        ] -> (known after apply)
        resource_group_name               = "grp-sample-test-geo"
      ~ secondary_master_key              = (sensitive value)
      ~ secondary_readonly_master_key     = (sensitive value)
      ~ tags                              = {} -> (known after apply)
      ~ write_endpoints                   = [
          - "https://sample-test-geo-uksouth.documents.azure.com:443/",
        ] -> (known after apply)

        consistency_policy {
            consistency_level       = "Session"
            max_interval_in_seconds = 5
            max_staleness_prefix    = 100
        }

      - geo_location { # forces replacement
          - failover_priority = 0 -> null
          - id                = "sample-test-geo-uksouth" -> null
          - location          = "uksouth" -> null
        }
      + geo_location { # forces replacement
          + failover_priority = 0
          + id                = (known after apply)
          + location          = "uksouth"
        }
      + geo_location { # forces replacement
          + failover_priority = 1
          + id                = (known after apply)
          + location          = "ukwest"
        }
    }
```

### Apply log

```hcl
azurerm_cosmosdb_account.cosmos_db: Destroying... [id=/subscriptions/xxx-xxx/resourceGroups/grp-sample-test-geo/providers/Microsoft.DocumentDB/databaseAccounts/sample-test-geo]
azurerm_cosmosdb_account.cosmos_db: Still destroying... [id=/subscriptions/xxx-xxx-...entDB/databaseAccounts/sample-test-geo, 10s elapsed]
azurerm_cosmosdb_account.cosmos_db: Still destroying... [id=/subscriptions/xxx-xxx-...entDB/databaseAccounts/sample-test-geo, 20s elapsed]
...
azurerm_cosmosdb_account.cosmos_db: Destruction complete after 8m2s
azurerm_cosmosdb_account.cosmos_db: Creating...
azurerm_cosmosdb_account.cosmos_db: Still creating... [10s elapsed]
azurerm_cosmosdb_account.cosmos_db: Still creating... [20s elapsed]
...
azurerm_cosmosdb_account.cosmos_db: Creation complete after 8m42s [id=/subscriptions/xxx-xxx/resourceGroups/grp-sample-test-geo/providers/Microsoft.DocumentDB/databaseAccounts/sample-test-geo]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

### Expected Behavior

A second geo_location should be added to the existing resource.

### Actual Behavior

- The whole resource is destroyed/replaced.
- Existing geo_location is replaced with the same geo_location and priority!

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`
1. uncomment the second geo_location.
1. `terraform plan`
1. `terraform apply`

### References

#3230

**Comment by waleedexe** [comment] 2019-07-12 16:33
ok this was already reported by #3532

**Comment by BarnumD** [comment] 2019-08-23 23:31
I think I'm experiencing the same thing, but I don't have to uncomment anything.  As long as I have a second geo_location the account is recreated every time.  Is there a workaround to this?

**Comment by katbyte** [comment] 2019-09-03 20:29
Hi @waleedexe, i'm going to close this as a duplicate of #3532.

**Closed by katbyte** 2019-09-03 20:29 UTC
Labels: bug, duplicate, service/cosmosdb
