### ISSUE TITLE
AzureRm V2: Cannot set up Data Factory code repository without Subscription Level Permissions

### ISSUE THREAD

**Issue by eedwards36** [terraform-providers/terraform-provider-azurerm#6484] opened 2020-04-15 12:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to deploy a Azure Data Factory with the Azure DevOps repository configured using the following terraform: 

    
    provider "azurerm" {
     version = "=2.3.0"
     features {}
    }
    resource "azurerm_data_factory" "example" {
      name                = "adf_name"
      location            = "location"
      resource_group_name = "rg_name"
      vsts_configuration {
        account_name      = "account_name"
       branch_name       = "branch_name"
        project_name      = "project_name"
        repository_name   = "repo_name"
        root_folder       = "root_folder"
     }
    }

When deploying the above code using Azure Cloud Shell with Contributor role on the resource group and not on the subscription level I get the following error:

Error: Error configuring Repository for Data Factory "adf-name" (Resource Group "rg-name"): datafactory.FactoriesClient#ConfigureFactoryRepo: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxx@xxx.com' with object id 'xxxxx' does not have authorization to perform action 'Microsoft.DataFactory/locations/configureFactoryRepo/action' over scope '/subscriptions/xxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials.

To reproduce the error create a new terraform project and copy the above code, then run:
terraform init
terraform apply

Is there a way to use vsts_configuration without having Contributor role access on the subscription?

**Comment by lmicverm** [comment] 2020-05-18 13:30
Just checked the API of Azure and terraform source code. Terraform is using the following rest call to add the git repo:
[Configure factory repo](https://docs.microsoft.com/en-us/rest/api/datafactory/factories/configurefactoryrepo)

This call requires more than reader permissions over the subscription. However, when using the following rest call, only permissions on the resource group are necessary. This is also the call that is used by the portal of data factory:
[Create or update factory](https://docs.microsoft.com/en-us/rest/api/datafactory/factories/createorupdate)

I think the desired behaviour is the last one. It should not be necessary to have contributor permissions on a subscription to add a git config when you have enough permissions on the resource group. 

Please fix

**Comment by elmasimons** [comment] 2020-07-14 09:50
I am facing the same issue, May I know if there is any update on this or a fix for this ?

**Comment by sahilchaudhry08** [comment] 2020-10-14 14:03
Any updates to this issue? I am still facing this issue.

**Comment by mkoptelov** [comment] 2020-11-24 23:10
a potential workaround is to use arm for this inside terraform:
`
resource "azurerm_template_deployment" "vsts-configuration" {
  name = "vsts-configuration-${formatdate("YYYY-MMM-DD-hh-mm-ss-ZZZ", timestamp())}"
  resource_group_name = "RG-NAME"
  deployment_mode = "Incremental"

  lifecycle {
    ignore_changes = [
      name
    ]
  }

  depends_on = [
    azurerm_data_factory.adf
  ]

  parameters = {
    factoryName = azurerm_data_factory.adf.name
    repositoryName = var.vsts_repository_name
    projectName = var.vsts_project_name
  }

  template_body = file("${path.module}/arm/datafactory.json")
}
`

And ARM template:

`
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "factoryName": {
      "type": "string"
    },
    "projectName": {
      "type": "string"
    },
    "repositoryName": {
      "type": "string"
    }
  },
  "resources": [
    {
      "type": "Microsoft.DataFactory/factories",
      "name": "[parameters('factoryName')]",
      "apiVersion": "2018-06-01",
      "location": "[resourceGroup().location]",
      "identity": {
        "type": "SystemAssigned"
      },
      "properties": {
        "repoConfiguration": {
        "type": "FactoryVSTSConfiguration",
        "accountName": "AzureDevOpsAccount",
        "collaborationBranch": "master",
        "projectName": "[parameters('projectName')]",
        "repositoryName": "[parameters('repositoryName')]",
        "rootFolder": "/"
      }
    }
  }
  ]
}
`

**Comment by Raka74** [comment] 2021-04-16 09:30
Any update on this?

We currently have a custom role in place at subscription level with only the ConfigureFactoryRepo permission as a workaround  but we'd prefer not to have this, and only set permissions on the resource group.

**Comment by mlomat** [comment] 2021-07-26 09:04
> a potential workaround is to use arm for this inside terraform:
> 
> ```
> resource "azurerm_template_deployment" "vsts-configuration" {
>   name = "vsts-configuration-${formatdate("YYYY-MMM-DD-hh-mm-ss-ZZZ", timestamp())}"
>   resource_group_name = "RG-NAME"
>   deployment_mode = "Incremental"
> 
>   lifecycle {
>     ignore_changes = [
>       name
>     ]
>   }
> 
>   depends_on = [
>     azurerm_data_factory.adf
>   ]
> 
>   parameters = {
>     factoryName = azurerm_data_factory.adf.name
>     repositoryName = var.vsts_repository_name
>     projectName = var.vsts_project_name
>   }
> 
>   template_body = file("${path.module}/arm/datafactory.json")
> }
> ```
> 
> And ARM template:
> 
> ```
> {
>   "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
>   "contentVersion": "1.0.0.0",
>   "parameters": {
>     "factoryName": {
>       "type": "string"
>     },
>     "projectName": {
>       "type": "string"
>     },
>     "repositoryName": {
>       "type": "string"
>     }
>   },
>   "resources": [
>     {
>       "type": "Microsoft.DataFactory/factories",
>       "name": "[parameters('factoryName')]",
>       "apiVersion": "2018-06-01",
>       "location": "[resourceGroup().location]",
>       "identity": {
>         "type": "SystemAssigned"
>       },
>       "properties": {
>         "repoConfiguration": {
>         "type": "FactoryVSTSConfiguration",
>         "accountName": "AzureDevOpsAccount",
>         "collaborationBranch": "master",
>         "projectName": "[parameters('projectName')]",
>         "repositoryName": "[parameters('repositoryName')]",
>         "rootFolder": "/"
>       }
>     }
>   }
>   ]
> }
> ```

I tried that, it's working fine on 1st deployment of terraform. After that, it's failing on second apply, because it's still trying to execute something on subscription level. Even after I added ignore on vsts_configuration on Data Factory resource. So the only workaround is to add permission at subscription level  :(

**Comment by tombuildsstuff** [comment] 2021-07-26 11:39
👋 

Taking a look through here unfortunately this behaviour is by design within Azure, since the Factory Repos configured on a per-location/region basis, rather than per-Data Factory. FWIW this doesn't require full access to the subscription, but instead to the scope:

> /subscriptions/{subscriptionId}/providers/Microsoft.DataFactory/locations/{locationId}

Unfortunately the design of the Azure API here means that for Terraform to be able to manage this (e.g. read & write) - we require permission to this scope, since that's where the Factory Repo's configured - but adding a Role Assignment using the scope above (for example `/subscriptions/00000000-0000-0000-000000000000/providers/Microsoft.DataFactory/locations/westeurope`) should make this possible.

Since this behaviour is by design (since we need to be able to track changes to the Factory Repo here) - I'm going to close this issue for the moment, but should you have further usage questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2021-07-26 11:39 UTC
Labels: question, service/data-factory
