### ISSUE TITLE
v1.34 Want to recreate AKS cluster. 

### ISSUE THREAD

**Issue by doggvalera** [terraform-providers/terraform-provider-azurerm#4405] opened 2019-09-22 11:36 UTC
Hi. 
I have an issue with 1.34 version 
When I did the terraform plan. Terraform informed that azurerm_kubernetes_cluster resource will be recreated, but I didn't make any changes. With version 1.33, everything is ok. 

1.34 version output:  
_I have removed all sensitive data_
```
azurerm_kubernetes_cluster.kubernetes-cluster must be replaced
-/+ resource "azurerm_kubernetes_cluster" "kubernetes-cluster" {
      - api_server_authorized_ip_ranges = [] -> null
        dns_prefix                      = "name"
      ~ enable_pod_security_policy      = false -> (known after apply)
      ~ fqdn                            = "name" -> (known after apply)
      ~ id                              = "/subscriptions/" -> (known after apply)
      ~ kube_admin_config               = [
          - {
              - client_certificate     = ""
              - client_key             = ""
              - cluster_ca_certificate = ""
              - host                   = ""
              - password               = ""
              - username               = ""
            },
        ] -> (known after apply)
      ~ kube_admin_config_raw           = (sensitive value)
      ~ kube_config                     = [
          - {
              - client_certificate     = ""
              - client_key             = ""
              - cluster_ca_certificate = ""
              - password               = ""
              - username               = "name"
            },
        ] -> (known after apply)
      ~ kube_config_raw                 = (sensitive value)
        kubernetes_version              = "1.14.3"
        location                        = "northeurope"
        name                            = "name"
      ~ node_resource_group             = "name" -> (known after apply)
        resource_group_name             = "name"
      ~ tags                            = {} -> (known after apply)


        addon_profile {
            oms_agent {
                enabled                    = true
                log_analytics_workspace_id = "subscriptions"
            }
        }

      ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 3
          + dns_prefix          = (known after apply)
            enable_auto_scaling = true
          ~ fqdn                = "name" -> (known after apply)
            max_count           = 3
          ~ max_pods            = 30 -> (known after apply)
            min_count           = 3
            name                = "default"
          - node_taints         = [] -> null
            os_disk_size_gb     = 30
            os_type             = "Linux"
            type                = "VirtualMachineScaleSets"
            vm_size             = "Standard_B2ms"
            vnet_subnet_id      = "/subscriptions/"
        }

        linux_profile {
            admin_username = ""

            ssh_key {
                key_data = ""
            }
        }

      ~ network_profile {
          ~ dns_service_ip     = "10.0.0.10" -> (known after apply)
          ~ docker_bridge_cidr = "172.17.0.1/16" -> (known after apply)
            load_balancer_sku  = "standard"
            network_plugin     = "azure"
            network_policy     = "calico"
          + pod_cidr           = (known after apply)
          ~ service_cidr       = "10.0.0.0/16" -> (known after apply)
        }

        role_based_access_control {
            enabled = true

            azure_active_directory {
                client_app_id     = ""
                server_app_id     = ""
                server_app_secret = (sensitive value)
                tenant_id         = ""
            }
        }

      ~ service_principal {
            client_id     = ""
          + client_secret = (sensitive value)
        }
    }


Plan: 1 to add, 1 to change, 1 to destroy.
```
1.33 version output: 
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by tombuildsstuff** [comment] 2019-09-22 19:12
hi @doggvalera 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4356 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4356 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-22 19:12 UTC
