### ISSUE TITLE
Failed updating API Management policy getting "NotSupported" error "Certificate management for the default domain is not allowed"

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#6636] opened 2020-04-27 11:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
+ provider.azuread v0.6.0
+ provider.azurerm v2.7.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  publisher_name      = var.publisher_name
  publisher_email     = var.publisher_email

  sku_name = var.sku_name

  policy {
    xml_content = <<XML
    <policies>
    <inbound>
        ${local.cors_policy_xml}
    </inbound>
    <backend>
      <forward-request />
    </backend>
    <outbound />
    <on-error />
    </policies>
XML
  }

}
```

### Debug Output

it appears to be only doing a change on the policy in the 'xml_content' property.

### Actual Behavior

Error: creating/updating API Management Service "foo-test-apim" (Resource Group "foo-test-global"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NotSupported" Message="Certificate management for the default domain 'iris-test-apim.azure-api.net' is not allowed."

### Steps to Reproduce

1. `terraform apply`
2. go into azure portal tweak the API management cors policy, hit save.
3. 'terraform apply'

### Important Factoids

Azure Public

**Comment by yupwei68** [comment] 2020-04-28 02:49
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/6621

**Comment by tombuildsstuff** [comment] 2020-05-12 14:28
Closing as a duplicate of #6621

**Closed by tombuildsstuff** 2020-05-12 14:28 UTC
Labels: service/api-management
