### ISSUE TITLE
azurerm_kubernetes_cluster requires recreation with provider 1.

### ISSUE THREAD

**Issue by fbuehlmann** [terraform-providers/terraform-provider-azurerm#4407] opened 2019-09-23 08:25 UTC
A kubernets Cluster created with provider 1.33.1 needs to be recreated with provider version 1.34

Resource Condiguration:
resource "azurerm_kubernetes_cluster" "k8sCluster" {
  name                = format("%s-aks", var.resourceNamePrefix)
  location            = var.location
  resource_group_name = var.resourceGroupName
  dns_prefix          = var.dnsPrefix
  kubernetes_version  = var.kubernetesVersion

  tags = var.tags

  //  linux_profile {
  //    admin_username = "ubuntu"
  //
  //    ssh_key {
  //      key_data = "${file("${var.ssh_public_key}")}"
  //    }
  //  }

  role_based_access_control {
    enabled = var.rbacEnabled
  }

  network_profile {
    network_plugin = "azure"
  }

  agent_pool_profile {
    enable_auto_scaling = false
    name                = "default"
    count               = var.clusterNodeCount
    vm_size             = var.clusterVmSize
    os_type             = "Linux"
    os_disk_size_gb     = var.clusterVmDiskSize
    vnet_subnet_id      = azurerm_subnet.k8sSubnetCluster.id
  }

  service_principal {
    client_id     = var.servicePrincipalID
    client_secret = var.servicePrincipalSecret
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.logws.id
    }
  }

  depends_on = [
    "azurerm_role_assignment.k8sServicePrincipalRightsControbutor",
    "azurerm_role_assignment.k8sServicePrincipalRightsNetworkContributor"

  ]
}

terraform plan output:
-/+ resource "azurerm_kubernetes_cluster" "k8sCluster" {
      - api_server_authorized_ip_ranges = [] -> null
        dns_prefix                      = "prod-srp"
      ~ enable_pod_security_policy      = false -> (known after apply)
      ~ fqdn                            = "prod-srp-d3ec1c95.hcp.westeurope.azmk8s.io" -> (known after apply)
      ~ id                              = "/subscriptions/a048eb3f-1118-4d55-bb00-5fb9cd44ac84/resourcegroups/weu-prod-srp-rg/providers/Microsoft.ContainerService/managedClusters/srp-aks" -> (known after apply)
      ~ kube_admin_config               = [] -> (known after apply)
      + kube_admin_config_raw           = (sensitive value)
      ~ kube_config                     = [
          - {
              - client_certificate     = "hidden"
              - client_key             = "hidden"
              - cluster_ca_certificate = "hidden"
              - host                   = "https://prod-srp-d3ec1c95.hcp.westeurope.azmk8s.io:443"
              - password               = "pwd"
              - username               = "clusterUser_srp-aks"
            },
        ] -> (known after apply)
      ~ kube_config_raw                 = (sensitive value)
        kubernetes_version              = "1.14.6"
        location                        = "westeurope"
        name                            = "weu-prod-srp-aks"
      ~ node_resource_group             = "MC_weu-prod-srp-rg_weu-prod-srp-aks_westeurope" -> (known after apply)
        resource_group_name             = "weu-prod-srp-rg"
        tags                            = {
            "BillTo"         = "Bison Schweiz AG"
            "ProjectName"    = "SmartRetail Plattform"
            "ProjectNumber"  = "3074"
            "ProjectOwner"   = "info@bison-group.com"
            "ProjectSponsor" = "Bison Schweiz AG"
            "srpApplication" = "SmartRetail_Plattform"
            "srpCostCenter"  = ""
            "srpCustomer"    = "BICH"
        }

        addon_profile {

            oms_agent {
                enabled                    = true
                log_analytics_workspace_id = "/subscriptions/a048eb3f-1118-4d55-bb00-5fb9cd44ac84/resourcegroups/weu-prod-srp-rg/providers/microsoft.operationalinsights/workspaces/weu-prod-srp-logws"
            }
        }

      ~ agent_pool_profile {
          - availability_zones  = [] -> null
            count               = 3
          + dns_prefix          = (known after apply)
            enable_auto_scaling = false
          ~ fqdn                = "prod-srp-d3ec1c95.hcp.westeurope.azmk8s.io" -> (known after apply)
          - max_count           = 0 -> null
          ~ max_pods            = 30 -> (known after apply)
          - min_count           = 0 -> null
            name                = "default"
          - node_taints         = [] -> null
            os_disk_size_gb     = 30
            os_type             = "Linux"
            type                = "AvailabilitySet"
            vm_size             = "Standard_E2s_v3"
            vnet_subnet_id      = "/subscriptions/a048eb3f-1118-4d55-bb00-5fb9cd44ac84/resourceGroups/weu-prod-srp-rg/providers/Microsoft.Network/virtualNetworks/weu-prod-srp-vnet/subnets/weu-prod-srp-subnet-cluster"
        }

      ~ network_profile {
          ~ dns_service_ip     = "10.0.0.10" -> (known after apply)
          ~ docker_bridge_cidr = "172.17.0.1/16" -> (known after apply)
            load_balancer_sku  = "basic"
            network_plugin     = "azure"
          + network_policy     = (known after apply)
          + pod_cidr           = (known after apply)
          ~ service_cidr       = "10.0.0.0/16" -> (known after apply)
        }

        role_based_access_control {
            enabled = true
        }

      ~ service_principal {
            client_id     = "f254ac1b-b755-4e5f-b950-f0d505301e20"
          + client_secret = (sensitive value)
        }
    }

Is there any hint what I should change on the configuration to be compatible with provider version 1.34?

**Comment by tombuildsstuff** [comment] 2019-09-23 09:06
hi @dan-gibbons 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4383 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4383 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-23 09:06 UTC
