### ISSUE TITLE
Can not create azurerm_storage_account

### ISSUE THREAD

**Issue by martenbohlin** [terraform-providers/terraform-provider-azurerm#4009] opened 2019-08-05 21:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm (unversioned)

Using git commit 1c9759f6 of provider.azurerm

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "West US"
}

resource "azurerm_storage_account" "test" {
  name                     = "testadsfa"
  location                 = "${azurerm_resource_group.test.location}"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

```

### Debug Output

https://gist.github.com/martenbohlin/34b719670059c1e3541eaf502d02968a

### Expected Behavior

Storage account to be created and terraform to exit succesfully.

### Actual Behavior

Storage account was created but terraform returns the following error message:
```
azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/db017fc9-f2f1-484c-826d-bd349bf2a2ac/resourceGroups/test)
azurerm_storage_account.test: Refreshing state... (ID: /subscriptions/db017fc9-f2f1-484c-826d-...soft.Storage/storageAccounts/testadsfa)

Error: Error refreshing state: 1 error(s) occurred:

* azurerm_storage_account.test: 1 error(s) occurred:

* azurerm_storage_account.test: azurerm_storage_account.test: Error reading queue properties for AzureRM Storage Account "testadsfa": queues.Client#SetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:00316529-4003-00b8-6bd4-4bb627000000\nTime:2019-08-05T21:30:08.9188829Z</Message></Error>" error: invalid character 'ï' looking for beginning of value
```

But if I comment out line 1702 to 1083 in azurerm/resource_arm_storage_account.go it works.

### Steps to Reproduce

1. `terraform apply`

### References

* #3859

**Comment by tombuildsstuff** [comment] 2019-08-12 11:17
hi @martenbohlin 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3939 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3939 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-12 11:17 UTC
Labels: bug, duplicate, service/storage
