### ISSUE TITLE
Support for creating App_Configuration KV Pairs

### ISSUE THREAD

**Issue by dlm69** [terraform-providers/terraform-provider-azurerm#9292] opened 2020-11-12 16:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be really helpful to use terraform outputs to create values in Azure App Config.

### New or Affected Resource(s)

* azurerm_app_configuration

### Potential Terraform Configuration

resource "azurerm_app_configuration_key" "example" {
  name                 = "AppInsightsConnectionString"
  app_configuration_id = azurerm_app_configuration.example.id
  key_value            = azurerm_application_insights.example.connection_string
  key_label            = "optional"
}

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-11-12 17:01
hi @dlm69 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5840 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5840 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-11-12 17:01 UTC
Labels: duplicate, new-resource, sdk/not-yet-supported, service/app-configuration
