### ISSUE TITLE
Function App IP Restrictions still missing

### ISSUE THREAD

**Issue by mehowq** [terraform-providers/terraform-provider-azurerm#4882] opened 2019-11-14 16:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There's still no functionality to configure `ip_restriction` blocks in the terraform function app resource. This feature has been originally requested in [this ticket](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3229) and marked as implemented in [v.1.34.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.34.0/CHANGELOG.md). However, the functionality has been only implemented for `azurerm_app_service` resource rather than `azurerm_function_app`.

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "global_app_function" {
    name                      = "hub-deployer-${var.deployment_suffix}"
    location                  = "${azurerm_resource_group.main_rg.location}"
    resource_group_name       = "${azurerm_resource_group.main_rg.name}"
    app_service_plan_id       = "${azurerm_app_service_plan.global_app_serviceplan.id}"
    storage_connection_string = "${azurerm_storage_account.global_function_storage.primary_connection_string}"
    https_only                = "true"

    # NOT AVAILABLE FOR FUNCTION APP TF RESOURCE (ONLY IN APP SERVICE TF RESOURCE)
    site_config {
        ip_restriction  = {
            ip_address = "65.245.25.32"
        }
    }
```

**Comment by tombuildsstuff** [comment] 2019-11-14 16:17
Duplicate of #4878

**Closed by tombuildsstuff** 2019-11-14 16:17 UTC
