### ISSUE TITLE
Role based permission Issue using Terrafrom

### ISSUE THREAD

**Issue by reddyed** [terraform-providers/terraform-provider-azurerm#1555] opened 2018-07-12 15:44 UTC
I am using terraform script for creating role assignment and associating the AD group (principal id) with a resource group. First time when we are applying changes using terraform apply it works fine and when we do terraform plan, it shows all those roles to be recreated(force new resources). Following is the code we are using

```hcl
resource 'azurerm_role_assignment' 'di-dev-shared-rg-Dev-Ops-Owner' {
scope = '${azurerm_resource_group.di-dev-shared-rg.id}'
role_definition_id = '${data.azurerm_builtin_role_definition.Owner.id}'
principal_id = 'xxxx-xxx-xxx-852b-xxxxxx'
}
```
and following is the message that we get when we do terraform plan after applying changes

```
-/+ azurerm_role_assignment.di-dev-shared-rg-Dev-Sec-Ops-Owner (new resource required)
id: '/subscriptions/xxxxx-xxx-41d9-xxxx-xxxx/resourceGroups/di-dev-shared-rg/providers/Microsoft.Authorization/roleAssignments/xxxxxx-xxx-xxx-xxxx-xxxxxxxxxx' => <computed> (forces new resource)
name: 'xxxxx-321e-xxxx-6bd1-xxxxxxx' => <computed>
principal_id: 'xxxxxxxxxx-axa82-xxxx-b69e-xxxxxxxx' => 'xxxx-xxx-4fc1-b69e-xxxx'
role_definition_id: '/subscriptions/ff70
xxxxxxx-xxxx-41d9-xxxx-xxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxx-xxxx-xxx-xxx-xxxxxxxx' => '/providers/Microsoft.Authorization/roleDefinitions/xxxxxx-a8ff-xxx-xxx-xxxxxxx' (forces new resource)
scope: '/subscriptions/xxxxx-xxxx-xxxx-xxxxxxxx/resourceGroups/di-dev-shared-rg' => '/subscriptions/xxxxx-xxxx-xxxx-bf7d-xxxxxxxx/resourceGroups/di-dev-shared-rg'
```

**Comment by tombuildsstuff** [comment] 2018-07-30 13:49
Duplicate of #1454 - closing in favour of that issue.

**Closed by tombuildsstuff** 2018-07-30 13:49 UTC
