### ISSUE TITLE
Error: Error waiting for deletion of HDInsight "Hadoop" Cluster 

### ISSUE THREAD

**Issue by dvp236** [terraform-providers/terraform-provider-azurerm#4499] opened 2019-10-03 14:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.9

### Affected Resource(s)

* `HDInsight`

### Debug Output
When destroying cluster we get below
```
Error: Error waiting for deletion of HDInsight "Hadoop" Cluster "example-hdinsight" (Resource Group "example-hadoop-rg"): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/b40a1a90-908080/providers/Microsoft.HDInsight/locations/East%20US/azureasyncoperations/b0d42452-e8ccadsfasdf-sdf-0-r?api-version=2018-06-01-preview: StatusCode=0 -- Original Error: Manually created ServicePrincipalToken does not contain secret material to retrieve a new access token
```
We also get below issue as well. 
```
Error deleting Resource Group "example-rabbitmq-rg": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/b40a1a90-e321-45bsdfs/operationresults/eyJqb2JJZad09VUkNFR1JPVVBERUxFVElPTkpPQi1EUEFURUw6MkREUEFBUzoyRFJBRUFTVFVTIiwiam9iTG9jYXRpb24iOiJlYXN0dXMifQ?api-version=2018-05-01: StatusCode=0 -- Original Error: Manually created ServicePrincipalToken does not contain secret material to retrieve a new access token
```

### Expected Behavior

It should have destroyed resources without complaint.

### Actual Behavior

It throws an error and fails to delete some resources. In our case the storage account on the cloud. 
### Steps to Reproduce

1. `terraform destroy`

**Comment by tombuildsstuff** [comment] 2019-10-03 14:23
hi @dvp236 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2602  - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2602  for updates?

Thanks!

**Closed by tombuildsstuff** 2019-10-03 14:23 UTC
Labels: authentication, bug, duplicate

**Comment by dvp236** [comment] 2019-10-03 14:42
Sure. Thanks!
