### ISSUE TITLE
Failure to create app service in Shared D1 plan

### ISSUE THREAD

**Issue by johnmart82** [terraform-providers/terraform-provider-azurerm#9844] opened 2020-12-12 20:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.2
hashicorp/azurerm v2.40.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "uksouth"
}

resource "azurerm_app_service_plan" "example" {
  name                = "example-appserviceplan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    tier = "Shared"
    size = "D1"
  }
}

resource "azurerm_app_service" "example" {
  name                = "example-app-service-${random_id.server.hex}"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  site_config {
    dotnet_framework_version = "v4.0"
    scm_type                 = "LocalGit"
  }
}

resource "random_id" "server" {
  keepers = {
    azi_id = 1
  }

  byte_length = 8
}
```

### Expected Behaviour

App service to be created and linked to app service plan.

### Actual Behaviour

App service resource fails to be created and Terraform provides the following error output.

Error: Error creating App Service "example-app-service-f224b8f14e51faa1" (Resource Group "example-resources"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

  on main.tf line 20, in resource "azurerm_app_service" "example":
  20: resource "azurerm_app_service" "example" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This issue seems to be related to the architecture of the app service being created (x64) while the Shared D1 will only support a 32bit (https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#app-service-limits).

If the HCL listed above is used with tire = "Standard" and size = "S1" then it will work fine. If you then try to re-size the app service plan via the portal you will get an error about x64 not being supported and it is not able to perform the re-sizing activity.

If you manually create the same configuration of D1 plan and then deploy and App service to it then it works fine via the portal.

**Comment by tombuildsstuff** [comment] 2020-12-14 08:51
hi @johnmart82 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1560 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1560 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-12-14 08:51 UTC
Labels: bug, duplicate, service/app-service
