### ISSUE TITLE
azurerm_frontdoor attempts to reorder its inner blocks every time it's run

### ISSUE THREAD

**Issue by jamesggraf** [terraform-providers/terraform-provider-azurerm#9300] opened 2020-11-12 21:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.13.3
AzureRM: 2.36.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "example" {
  name                                         = "my-frontdoor-frontend-poc"
  resource_group_name                          = var.resource_group_name
  enforce_backend_pools_certificate_name_check = false

  frontend_endpoint {
    custom_https_provisioning_enabled       = false
    host_name                               = "my-frontdoor-frontend-poc.azurefd.net"
    name                                    = "my-frontdoor-frontend-poc"
  }

  backend_pool {
    health_probe_name   = "abc"
    load_balancing_name = "abc"
    name                = "abc"

    backend {
      address     = "my-abc-backend.azurewebsites.net"
      enabled     = true
      host_header = "my-abc-backend.azurewebsites.net"
      http_port   = 80
      https_port  = 443
      priority    = 1
      weight      = 50
    }
  }
  backend_pool {
    health_probe_name   = "def"
    load_balancing_name = "def"
    name                = "def"

    backend {
      address     = "my-def-backend.azurewebsites.net"
      enabled     = true
      host_header = "my-def-backend.azurewebsites.net"
      http_port   = 80
      https_port  = 443
      priority    = 1
      weight      = 50
    }
  }
  backend_pool {
    health_probe_name   = "ghi"
    load_balancing_name = "ghi"
    name                = "ghi"

    backend {
      address     = "my-ghi-backend.azurewebsites.net"
      enabled     = true
      host_header = "my-ghi-backend.azurewebsites.net"
      http_port   = 80
      https_port  = 443
      priority    = 1
      weight      = 50
    }
  }
  backend_pool {
    health_probe_name   = "jkl"
    load_balancing_name = "jkl"
    name                = "jkl"

    backend {
      address     = "my-jkl-backend.azurewebsites.net"
      enabled     = true
      host_header = "my-jkl-backend.azurewebsites.net"
      http_port   = 80
      https_port  = 443
      priority    = 1
      weight      = 50
    }
  }

  backend_pool_health_probe {
    enabled             = true
    interval_in_seconds = 120
    name                = "abc"
    path                = "/"
    probe_method        = "GET"
    protocol            = "Http"
  }
  backend_pool_health_probe {
    enabled             = true
    interval_in_seconds = 120
    name                = "def"
    path                = "/"
    probe_method        = "GET"
    protocol            = "Http"
  }
  backend_pool_health_probe {
    enabled             = true
    interval_in_seconds = 120
    name                = "ghi"
    path                = "/"
    probe_method        = "GET"
    protocol            = "Http"
  }
  backend_pool_health_probe {
    enabled             = true
    interval_in_seconds = 120
    name                = "jkl"
    path                = "/"
    probe_method        = "GET"
    protocol            = "Http"
  }

  backend_pool_load_balancing {
    additional_latency_milliseconds = 0
    name                            = "abc"
    sample_size                     = 4
    successful_samples_required     = 2
  }
  backend_pool_load_balancing {
    additional_latency_milliseconds = 0
    name                            = "def"
    sample_size                     = 4
    successful_samples_required     = 2
  }
  backend_pool_load_balancing {
    additional_latency_milliseconds = 0
    name                            = "ghi"
    sample_size                     = 4
    successful_samples_required     = 2
  }
  backend_pool_load_balancing {
    additional_latency_milliseconds = 0
    name                            = "jkl"
    sample_size                     = 4
    successful_samples_required     = 2
  }

  routing_rule {
    accepted_protocols = [
      "Https",
    ]
    enabled            = true
    frontend_endpoints = [
      "my-frontdoor-frontend-poc",
    ]
    name               = "abc"
    patterns_to_match  = [
      "/abc/*",
    ]

    forwarding_configuration {
      backend_pool_name                     = "abc"
      cache_enabled                         = false
      cache_query_parameter_strip_directive = "StripAll"
      cache_use_dynamic_compression         = false
      custom_forwarding_path                = "/"
      forwarding_protocol                   = "MatchRequest"
    }
  }

  routing_rule {
    accepted_protocols = [
      "Https",
    ]
    enabled            = true
    frontend_endpoints = [
      "my-frontdoor-frontend-poc",
    ]
    name               = "def"
    patterns_to_match  = [
      "/def/*",
    ]

    forwarding_configuration {
      backend_pool_name                     = "def"
      cache_enabled                         = false
      cache_query_parameter_strip_directive = "StripAll"
      cache_use_dynamic_compression         = false
      custom_forwarding_path                = "/"
      forwarding_protocol                   = "MatchRequest"
    }
  }

  routing_rule {
    accepted_protocols = [
      "Https",
    ]
    enabled            = true
    frontend_endpoints = [
      "my-frontdoor-frontend-poc",
    ]
    name               = "ghi"
    patterns_to_match  = [
      "/ghi/*",
    ]

    forwarding_configuration {
      backend_pool_name                     = "ghi"
      cache_enabled                         = false
      cache_query_parameter_strip_directive = "StripAll"
      cache_use_dynamic_compression         = false
      custom_forwarding_path                = "/"
      forwarding_protocol                   = "MatchRequest"
    }
  }

  routing_rule {
    accepted_protocols = [
      "Https",
    ]
    enabled            = true
    frontend_endpoints = [
      "my-frontdoor-frontend-poc",
    ]
    name               = "jkl"
    patterns_to_match  = [
      "/jkl/*",
    ]

    forwarding_configuration {
      backend_pool_name                     = "jkl"
      cache_enabled                         = false
      cache_query_parameter_strip_directive = "StripAll"
      cache_use_dynamic_compression         = false
      custom_forwarding_path                = "/"
      forwarding_protocol                   = "MatchRequest"
    }
  }
}
```

### Expected Behaviour

azurerm_frontdoor should remain idempotent between runs so long as nothing has changed in its configuration

### Actual Behaviour

azurerm_frontdoor attempts to reorder backend_pools, routing_rules, backend_pool_health_probe, backend_pool_load_balancing, and likely frontend_endpoint though I haven't confirmed this.

### Steps to Reproduce

1. `terraform apply`

**Comment by kingsleyadam** [comment] 2020-11-13 13:11
Same issue as #9153

**Comment by tombuildsstuff** [comment] 2020-11-13 13:23
hi @jamesggraf 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9153 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9153 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-11-13 13:23 UTC
