### ISSUE TITLE
azurerm_container_service Kubernetes example fails during apply

### ISSUE THREAD

**Issue by jeffreyCline** [terraform-providers/terraform-provider-azurerm#515] opened 2017-11-03 22:12 UTC
### Terraform Version
Terraform v0.10.9-dev (46d2b76e5f7d1591f66c45312d7a25be37dba7c8)
provider.azurerm v0.3.2

### Affected Resource(s)
azurerm_container_service

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG1"
  location = "West US"
}

resource "azurerm_container_service" "test" {
  name                   = "acctestcontservice1"
  location               = "${azurerm_resource_group.test.location}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  orchestration_platform = "Kubernetes"

  master_profile {
    count      = 1
    dns_prefix = "acctestmaster1"
  }

  linux_profile {
    admin_username = "acctestuser1"

    ssh_key {
      key_data = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqaZoyiz1qbdOQ8xEf6uEu1cCwYowo5FHtsBhqLoDnnp7KUTEBN+L2NxRIfQ781rxV6Iq5jSav6b2Q8z5KiseOlvKA/RF2wqU0UPYqQviQhLmW6THTpmrv/YkUCuzxDpsH7DUDhZcwySLKVVe0Qm3+5N2Ta6UYH3lsDf9R9wTP2K/+vAnflKebuypNlmocIvakFWoZda18FOmsOoIVXQ8HWFNCuw9ZCunMSN62QGamCe3dL5cXlkgHYv7ekJE15IA9aOJcM7e90oeTqo+7HTcWfdu0qQqPWY5ujyMw/llas8tsXY85LFqRnr3gJ02bAscjc477+X+j/gkpFoN1QEmt terraform@demo.tld"
    }
  }

  agent_pool_profile {
    name       = "default"
    count      = 1
    dns_prefix = "acctestagent1"
    vm_size    = "Standard_A0"
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }

  diagnostics_profile {
    enabled = false
  }

  tags {
    Environment = "Production"
  }
}
```

### Debug Output
https://gist.github.com/jeffreyCline/3599799aefeb8f4191aca795582abe35

### Expected Behavior
1. Successfully roll out the azurerm_container_service

### Actual Behavior
1. Error message stating "...The credentials in ServicePrincipalProfile were invalid..."

### Steps to Reproduce
1. `terraform apply`

**Comment by devigned** [comment] 2017-11-03 23:19
I'm going to guess this is caused by the `client_id` and `client_secret` below needing to be filled in with something other than these filler values. 

Does the resource automatically provision a service principal if not provided one? The Azure CLI follows this pattern.
 
```
 service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
```

**Comment by devigned** [comment] 2017-11-03 23:29
I think you will likely run into https://github.com/terraform-providers/terraform-provider-azurerm/issues/510 after you get past this issue.

**Comment by tombuildsstuff** [comment] 2017-11-04 09:29
Hey @jeffreyCline / @devigned 

Thanks for opening this issue :)

> Does the resource automatically provision a service principal if not provided one? The Azure CLI follows this pattern.

Not at this time (since we don't support creating service principals in Terraform at this time) - we also don't reuse the credentials used by the Provider for security purposes (since they may have considerably higher privileges than is intended) - instead we recommend people create a new Service Principal specifically for this purpose.

I believe newer versions to the ACS/AKS API's autogenerate a Service Principal for a user (at least AKS, I've not seen any documentation for the new ACS endpoints yet) - as such I believe the best we can do is to leave these zero'd out for the moment?

> I think you will likely run into #510 after you get past this issue.

Agreed - similar to #510 and #518, I think the best thing to do here may be to update the documentation to use `East US` rather than `West US`?

Thanks!

**Comment by jeffreyCline** [comment] 2017-11-06 22:30
I did get this working by updating the location to East US and adding my service_principal to the .tf file.

**Comment by tombuildsstuff** [comment] 2017-11-07 11:01
Great to hear - as such I'm going to close this issue for the moment, but please feel free to re-open it if you're still seeing issues

Thanks!

**Closed by tombuildsstuff** 2017-11-07 11:01 UTC
Labels: bugbash, documentation, msft
