### ISSUE TITLE
No `sku` block was returned for App Service Plan ID

### ISSUE THREAD

**Issue by alpeshv** [terraform-providers/terraform-provider-azurerm#3233] opened 2019-04-11 09:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.13
provider.azurerm v1.23.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```
resource "azurerm_function_app" "functionapp" {
  name                      = "${var.prefix}-functionapp"
  location                  = "${azurerm_resource_group.functionapp.location}"
  resource_group_name       = "${azurerm_resource_group.functionapp.name}"
  app_service_plan_id       = "${var.app_service_plan_id}"
  version                   = "~2"  
  storage_connection_string = "${azurerm_storage_account.storage.primary_connection_string}"

  app_settings {
    "APPINSIGHTS_INSTRUMENTATIONKEY" = "${azurerm_application_insights.insights.instrumentation_key}"
  }
}
```

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* azurerm_function_app.functionapp: 1 error(s) occurred:

* azurerm_function_app.functionapp: No `sku` block was returned for App Service Plan ID "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/serverFarms/av-test-app-service-plan"

### Expected Behavior

My service plan do have sku. If I fetch the data using https://management.azure.com/subscriptions/<subscription_id>/resourceGroups/<resouce_group_name>/providers/Microsoft.Web/serverfarms/<app_service_plan_name>?api-version=2018-02-01 I do get the following sku node in the response.

```
"sku": {
    "name": "I1",
    "tier": "Isolated",
    "size": "I1",
    "family": "I",
    "capacity": 1
  }
```

### Actual Behavior

Not able to create function app with existing app service plan. It worked when I have tried with consumption plan.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
My script works when I use
` app_service_plan_id       ="${azurerm_app_service_plan.avtestappsvcplan.id}"`

but not when I use resource id directly for the same app service plan
`  app_service_plan_id       ="/subscriptions/xxx/resourceGroups/AKS_DEV/providers/Microsoft.Web/serverFarms/av-test-service-plan"                                
`

I can confirm that "${azurerm_app_service_plan.avtestappsvcplan.id}" is "/subscriptions/xxx/resourceGroups/AKS_DEV/providers/Microsoft.Web/serverFarms/av-test-service-plan"

### References

* #0000

**Comment by tombuildsstuff** [comment] 2019-04-11 13:08
hi @alpeshv 

Thanks for opening this issue :)

Resource ID's within Terraform are case sensitive due to inconsistencies within Azure - such that the issue you're seeing here is because `serverFarms` is being used rather than `serverfarms` (which the API returned). Due to this we show an example of the Resource ID we're expecting in the import section of each resource (in this case [the `azurerm_app_service_plan` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#import)) which documents the casing required here.

> If I fetch the data using https://management.azure.com/subscriptions/<subscription_id>/resourceGroups/<resouce_group_name>/providers/Microsoft.Web/serverfarms/<app_service_plan_name>?api-version=2018-02-01 I do get the following sku node in the response.

I'm glad to hear that updating the casing being used fixes this for you 👍.

Since this is a question about Terraform Configuration (which has a confirmed solution above) I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2019-04-11 13:08 UTC
