### ISSUE TITLE
Excessive API calls when refreshing key_vault_secret

### ISSUE THREAD

**Issue by a200462790** [terraform-providers/terraform-provider-azurerm#7123] opened 2020-05-28 16:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.23
azurerm 2.11.0

### Affected Resource(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.example.id
}
```

### Expected Behavior

A terraform refresh should only make get requests for the keyvault and secrets that are referenced by the azurerm_key_vault_secret resource

### Actual Behavior

The refresh actually iterates through all of the keyvaults and makes get requests for each until it finds the keyvault referenced by the azurerm_key_vault_secret resource.

So, if we have 50 keyvaults in the subscription, that is *up to* 50 get requests. and if the terraform code has 50 secrets that is ~2500 

### Steps to Reproduce

1. `terraform apply`
2. `terraform refresh`

### Important Factoids

My Azure subscription has many keyvaults.

### References
It appears that [this method call](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/keyvault/key_vault_secret_resource.go#L278) could be the culprit.

I wouldn't mind contributing a change if we could settle on a solution.

**Comment by tombuildsstuff** [comment] 2020-05-28 17:28
hi @a200462790 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6196 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6196 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-28 17:28 UTC
