### ISSUE TITLE
azurerm_postgresql_virtual_network_rule FeatureSwitchNotEnabled

### ISSUE THREAD

**Issue by ShreyasNBS** [terraform-providers/terraform-provider-azurerm#7265] opened 2020-06-09 13:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`
Terraform v0.12.26
provider.azurerm v2.13.0
`

### Affected Resource(s)

* `azurerm_postgresql_virtual_network_rule`

### Terraform Configuration Files

```
resource "azurerm_postgresql_virtual_network_rule" "artifactory_sql_subnet_rule" {
  name                = "${module.names.standard["sql-server"]}-postgres-artifactory-subnet-rule"
  resource_group_name = data.azurerm_resource_group.artifactory_rg.name
  server_name         = azurerm_postgresql_server.artifactory_postgressqlsrv.name
  subnet_id           = data.azurerm_subnet.artifactory_private_subnet.id
}

resource "azurerm_postgresql_server" "artifactory_postgressqlsrv" {
  name                = "${module.names.standard["sql-server"]}-postgres-artifactory"
  location            = data.azurerm_resource_group.artifactory_rg.location
  resource_group_name = data.azurerm_resource_group.artifactory_rg.name

  sku_name = var.postgres_server_sku

  storage_mb                   = 204800
  backup_retention_days        = 7
  geo_redundant_backup_enabled = true
  auto_grow_enabled            = true

  administrator_login               = var.db_login
  administrator_login_password      = var.af_keyvault_db_password_secret_name
  version                           = "10"
  infrastructure_encryption_enabled = false // This was causing Postgres server creation to time out
  public_network_access_enabled     = false
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"

  threat_detection_policy {
    enabled                    = true
    email_account_admins       = true
    retention_days             = 60
    storage_endpoint           = azurerm_storage_account.artifactory_storage_account_sql_threat_detection_audit.primary_blob_endpoint
    storage_account_access_key = azurerm_storage_account.artifactory_storage_account_sql_threat_detection_audit.primary_access_key
  }

  tags = var.global_settings.tags
}

resource "azurerm_postgresql_database" "artifactory_postgressqlsrv_artifactorydb" {
  name                = "${module.names.standard["sql-database"]}-postgres-artifactory"
  resource_group_name = data.azurerm_resource_group.artifactory_rg.name
  server_name         = azurerm_postgresql_server.artifactory_postgressqlsrv.name
  charset             = "UTF8"
  collation           = "English_United States.1252"
}
```
### Actual Behavior
```
2020-06-09T12:32:33.5653982Z [1m[31mError: [0m[0m[1mError submitting PostgreSQL Virtual Network Rule "***" (PostgreSQL Server: "***", Resource Group: "***"): postgresql.VirtualNetworkRulesClient#CreateOrUpdate: Failure sending request: StatusCode=405 -- Original Error: Code="FeatureSwitchNotEnabled" Message="Requested feature is not enabled"
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ShreyasNBS** [comment] 2020-06-09 13:16
Just forgot to mention that the SKU is MO_Gen5_4.

**Comment by tombuildsstuff** [comment] 2020-06-09 13:41
hi @ShreyasNBS 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6959 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6959 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-09 13:41 UTC

**Comment by ShreyasNBS** [comment] 2020-06-09 13:58
@tombuildsstuff I thought #6959 was more around setting `public_network_access_enabled` to false. My setting is already set to false and I am using Memory Optimised sku. And since I have enabled Virtual Network Endpoint for Microsoft.Sql, I do not want to enable public network access. So how do I get around enabling the feature for adding the DB to subnet/vnet via `azurerm_postgresql_virtual_network_rule ` resource?

**Comment by ShreyasNBS** [comment] 2020-06-09 14:37
Ah. By the looks of it, as of August 2018 PostgresSQL cannot be assigned ot subnet. We have Microsoft.Sql endpoint already enabled. Based on Azure documentation, I do not need to add network firewall rule (unlike SQL server).

https://docs.microsoft.com/en-us/azure/postgresql/concepts-data-access-and-security-vnet

I will give it a bash
