### ISSUE TITLE
azurerm role assignment The request was incorrectly formatted 

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#4689] opened 2019-10-23 08:39 UTC
I'm trying to create a service prinicapal that will give AKS pull access to ACR (I assume that how you do it as I couldn't find documentation for this anywhere) however when I go to create the service principal I've given the error 'The request was incorrectly formatted '

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
provider "azurerm" {
  version = ">= 1.35.0"
}
```

### Affected Resource(s)

* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
resource "azuread_application" "ad-application" {
  name                       = "${data.azurerm_subscription.current.display_name}-cluster-app"
  homepage                   = "https://homepage"
  identifier_uris            = ["https://uri"]
  reply_urls                 = ["https://replyurl"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
}


resource "azuread_service_principal" "ad-service-principal" {
  application_id = "${azuread_application.ad-application.application_id}"
}

resource "random_password" "password" {
  length = 32
  special = true
}

data "azurerm_resource_group" "container-registry-resource-group" {
  name     = "docker-${var.jurisdiction}"
}

data "azurerm_container_registry" "container-registry" {
  name                = "${var.organisation}${var.jurisdiction}containerregistry"
  resource_group_name = "${data.azurerm_resource_group.container-registry-resource-group.name}"
}

resource "azuread_service_principal_password" "ad-service-principal-password" {
  service_principal_id = "${azuread_service_principal.ad-service-principal.object_id}"
  value                = "${random_password.password.result}"
  end_date             = "2020-01-01T01:02:03Z"
}

resource "azurerm_role_assignment" "ad-aks-acr-role-assignment" {
  scope              = "${data.azurerm_container_registry.container-registry.id}"
  role_definition_id = "Contributor"
  principal_id       = "${azuread_service_principal.ad-service-principal.object_id}"
}
```

### Panic Output

```
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequestFormat" Message="The request was incorrectly formatted."
```

### Expected Behavior

The Role is assigned to the service principal

### Actual Behavior

An 400 error is returned 

### Steps to Reproduce

1. `terraform apply`

### References

Peiceing together from things seen here:

https://stackoverflow.com/questions/53771773/azure-acr-how-to-assign-service-principle-through-terraform

https://stackoverflow.com/questions/57753666/terraform-azure-how-to-get-aks-service-principle-object-id

**Comment by cdesewell** [comment] 2019-10-29 10:30
Seems another one here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4258

**Comment by tombuildsstuff** [comment] 2019-10-29 10:49
hi @cdesewell 

Thanks for opening this issue :)

As you've mentioned this appears to be a duplicate of #4258 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4258 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-10-29 10:49 UTC
