### ISSUE TITLE
Adding support for Virtual Network Gateways

### ISSUE THREAD

**Issue by abhijeetgaiha** [terraform-providers/terraform-provider-azurerm#9] opened 2017-06-13 04:16 UTC
### Terraform Version
0.9.7-dev

### Expected Behavior
The ability to configure Virtual Network Gateways from terraform

### References
https://docs.microsoft.com/en-us/rest/api/network/virtualnetworkgateways
https://docs.microsoft.com/en-us/azure/vpn-gateway/

**Comment by abhijeetgaiha** [comment] 2017-06-13 04:16
I'm working on this.

**Comment by tombuildsstuff** [comment] 2017-08-15 11:13
Just noticed this is a duplicate of #17 - as such I'm going to close this issue in favour of that one. Please feel free to re-open this if I've mis-understood and this isn't the case :)

**Closed by tombuildsstuff** 2017-08-15 11:13 UTC
