### ISSUE TITLE
Terraform doesn't re-apply the mysql database password when changed from the portal

### ISSUE THREAD

**Issue by olblak** [terraform-providers/terraform-provider-azurerm#1823] opened 2018-08-24 08:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.10.0
+ provider.random v2.0.0

### Affected Resource(s)

* azurerm_mysql_server

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "db" {
  name     = "db"
  location = "eastus"
}

resource "azurerm_mysql_server" "db" {
  name                = "db"
  location            = "${azurerm_resource_group.db.location}"
  resource_group_name = "${azurerm_resource_group.db.name}"

  sku {
    name = "GP_Gen5_2"
    capacity = 2 
    tier = "GeneralPurpose"
    family = "Gen5"
  }

  storage_profile {
    storage_mb = 10240
    backup_retention_days = 7 
    geo_redundant_backup = "Enabled"
  }

  administrator_login = "mysqladmin"
  administrator_login_password = "1234"
  version = "5.7"
  ssl_enforcement = "Enabled"
}

```

### Debug Output

/

### Panic Output

/

### Expected Behavior

If I change the password from the portal.azure.com, I would expect terraform to re-apply the password from the terraform state

### Actual Behavior

Terraform only re-apply the password from the state if another setting changed like database size or retention backup

### Steps to Reproduce

1. `terraform apply`
2. Change database password from portal
3. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2018-08-24 10:57
hi @olblak 

Thanks for opening this issue :)

Terraform's currently unable to track changes to the password field within this resource, since this value isn't returned from the Azure API (for security reasons) and unfortunately I don't believe there's any other way for us to determine this (for instance such as a "last changed" time for the password).

I'd suggest [opening an issue on the Azure SDK for Go repository](https://github.com/Azure/azure-sdk-for-go/issues) about this - since in order for us to be able to detect this change, the API would need to return some indication of when the password was last changed/an etag.

Since Terraform's currently behaving as intended here (since this value isn't returned from the API) - I'm going to close this issue for the moment (but we'll continue responding 😄).

Thanks!

**Closed by tombuildsstuff** 2018-08-24 10:57 UTC

**Comment by olblak** [comment] 2018-08-24 11:13
Hi @tombuildsstuff, 
Thanks a lot for the clarification, I guess it's the same behavior with azure sql and the postgresql service
I'll open another issue there.

**Comment by tombuildsstuff** [comment] 2018-08-24 14:52
@olblak 

> Thanks a lot for the clarification, I guess it's the same behavior with azure sql and the postgresql service

Yep - I can understand why passwords aren't being returned from the API (security reasons) - however as mentioned above, hopefully something like an `etag/last changed date` or similar (e.g. return "primary/secondary key" vs the key being used in a connection string / the last modified time) which should allow us to detect this has changed without returning the password.

Thanks!
