### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by piotsk** [terraform-providers/terraform-provider-azurerm#6928] opened 2020-05-14 14:35 UTC
Error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: /usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif y is 0 or y is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif y is 0 or y is 1:
/usr/lib64/az/lib/python3.6/site-packages/jmespath/visitor.py:260: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if original_result is 0:

  on main.tf line 24, in provider "azurerm":
  24: provider "azurerm" {

cat /etc/redhat-release 
Fedora release 32 (Thirty Two)

terraform_0.12.25_linux_amd64

az --version
azure-cli                          2.5.1

command-modules-nspkg              2.0.3
core                               2.5.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/bin/python3'
Extensions directory '/home/pskora/.azure/cliextensions'

Python (Linux) 3.8.2 (default, Feb 28 2020, 00:00:00) 
[GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by tombuildsstuff** [comment] 2020-05-14 15:14
hi @piotsk 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6069 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6069 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-14 15:14 UTC
