### ISSUE TITLE
Incorrect casing for SKU name values when importing azurerm_key_vault

### ISSUE THREAD

**Issue by rahmnstein** [terraform-providers/terraform-provider-azurerm#8457] opened 2020-09-14 16:13 UTC
Imported a keyvault and issued terraform plan and got:

`Error: expected sku_name to be one of [standard premium], got Standard`

Changed to lowercase standard:

`      ~ sku_name                        = "Standard" -> "standard"`

Should it really trigger a change? I cannot use Standard and standard i triggering a change to the resource. It should import it with lower case or allow me to use upper case. 

According to thread below upper case does not work so it should import with lower case i guess.
https://github.com/terraform-providers/terraform-provider-azurerm/issues/2780

`terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.26.0`

**Comment by njuCZ** [comment] 2020-09-15 03:08
@rahmnstein for azurerm_key_vault  sku_name field, only `standard` or `premium` is accepted. You should only specify one of them in the tf file. For example:
```
resource "azurerm_key_vault" "test" {
  resource_group_name = "xxx"
  location            = "xxx"
  name                = "xxx"
  sku_name            = "standard"
  tenant_id           = data.azurerm_client_config.current.tenant_id
}
```
there is no such error after terraform import
```
terraform import azurerm_key_vault.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/xxx/provide
rs/Microsoft.KeyVault/vaults/xxx
```

**Comment by rahmnstein** [comment] 2020-09-15 07:28
@njuCZ 
I know, it's from when i issued `terraform plan`

"An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_key_vault.kv will be updated in-place
  ~ resource "azurerm_key_vault" "kv" {
	..........
      ~ sku_name                        = "Standard" -> "standard"
        soft_delete_enabled             = true
        soft_delete_retention_days      = 90"

As you can see, `terraform plan` says it will update my kv from upper to lower case standard. It's imported with upper case, but terraform plan forces me to use lower case.

I imported the kv with `terraform import azurerm_key_vault.kv /sub....verylongid`.
issued `terraform show` to get configuration, removed all unnecesarry info.
ran `terraform plan` and it says it's going to change my sku_name from "Standard" -> "standard.

Either it should let me use upper case or it should be imported with lower case, right? It should not force me to update sku_name just after i imported the resource, or am i missing something?

**Comment by njuCZ** [comment] 2020-09-15 08:00
@rahmnstein this issue is because the sku value of key vault resource is "Standard", but terraform only accept "standard". May I ask how to you create this key vault? In general, when users create key vault from portal, the value should also be "standard"

**Comment by rahmnstein** [comment] 2020-09-15 08:27
@njuCZ 

This was created by another team in a dev environment from the portal and my job now is to import everything into terraform so it can be deployed to test and production. So am testing with `terraform plan` against dev to see if I have the code right.

Just created a test keyvault from the portal and the result is the same.

https://i.imgur.com/2RWMhrk.png

`terraform import azurerm_key_vault.kv2 id`

`terraform show`

`# azurerm_key_vault.kv2:
resource "azurerm_key_vault" "kv2" {
    access_policy                   = [
        {
            application_id          = ""
            certificate_permissions = [
                "Get",
                "List",
                "Update",
                "Create",
                "Import",
                "Delete",
                "Recover",
                "Backup",
                "Restore",
                "ManageContacts",
                "ManageIssuers",
                "GetIssuers",
                "ListIssuers",
                "SetIssuers",
                "DeleteIssuers",
            ]
            key_permissions         = [
                "Get",
                "List",
                "Update",
                "Create",
                "Import",
                "Delete",
                "Recover",
                "Backup",
                "Restore",
            ]
            object_id               = "guid"
            secret_permissions      = [
                "Get",
                "List",
                "Set",
                "Delete",
                "Recover",
                "Backup",
                "Restore",
            ]
            storage_permissions     = []
            tenant_id               = "guid"
        },
    ]
    enabled_for_deployment          = false
    enabled_for_disk_encryption     = false
    enabled_for_template_deployment = false
    id                              = "/subscriptions/guid/resourceGroups/rg-name/providers/Microsoft.KeyVault/vaults/omgjusttesting"
    location                        = "westeurope"
    name                            = "omgjusttesting"
    purge_protection_enabled        = false
    resource_group_name             = "rg-name"
    **sku_name                        = "Standard"**
    soft_delete_enabled             = true
    soft_delete_retention_days      = 90
    tags                            = {}
    tenant_id                       = "guid"
    vault_uri                       = "https://omgjusttesting.vault.azure.net/"

    network_acls {
        bypass                     = "AzureServices"
        default_action             = "Allow"
        ip_rules                   = []
        virtual_network_subnet_ids = []
    }

    timeouts {}
}`

**Comment by njuCZ** [comment] 2020-09-15 08:36
@rahmnstein thanks for your clarification. It seems the portal behaviour has changed. I will submit a PR soon. generally new version will be release in thursday. Sorry for any inconvience

**Comment by adamsebetich** [comment] 2020-10-21 18:09
My issue was a duplicate of this issue, but it seems as though after a month, there has been no solution. Any updates on this?

**Comment by scp-mb** [comment] 2020-10-22 10:22
Same problem, this is a blocker for importing key vault resources into the state.

**Closed** 2020-10-23 08:29 UTC
Labels: question, service/keyvault
