### ISSUE TITLE
Error parsing Resource ID - ID contained more segments than required

### ISSUE THREAD

**Issue by sjblom** [terraform-providers/terraform-provider-azurerm#7604] opened 2020-07-07 07:02 UTC
provider "azurerm" {
   version                  = "2.17.0"
   features {       
   }
}
$ terraform import azurerm_resource_group.xxxxxxx /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxx

Error: Error parsing Resource ID "C:/Program Files/Git/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxx": ID contained more segments than required: "C:/Program Files/Git/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxx"

Thank you,

This is a duplicate from #7005, but, the #7005 was because of an incorrect resource ID... The resource ID for a storage account ID was mistakenly taken for a resource group ID

**Comment by tombuildsstuff** [comment] 2020-07-07 08:06
hi @sjblom 

Thanks for opening this issue.

Unfortunately this is a known issue in Terraform Core when using cygwin - where the working directory can be prefixed into arguments as they're passed through. In this case you should be able to quote the ID, or run Terraform from either PowerShell, the Command Prompt (or potentially from within WSL) which should ensure this is interpreted correctly.

Since this is a bug in Terraform Core I'm going to close this issue for the moment - but if one of the suggestions above doesn't work I'd recommend opening an issue on [the Terraform Core repository](https://github.com/hashicorp/terraform) where someone should be able to take a look.

Thanks!

**Closed by tombuildsstuff** 2020-07-07 08:06 UTC
Labels: question, upstream-terraform

**Comment by sjblom** [comment] 2020-07-07 08:09
Much appreciated @tombuildsstuff 

Switched to Powershell, and it worked as expected...

**Comment by tombuildsstuff** [comment] 2020-07-07 08:13
Duplicate of #7604
