### ISSUE TITLE
azurerm_monitor_log_profile is unfunctional

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#2235] opened 2018-11-05 03:39 UTC
Resource 'azurerm_monitor_log_profile' is unfunctional, please have a check.

Thanks,
Chang

1 error(s) occurred:

* azurerm_monitor_log_profile.test: 1 error(s) occurred:

* azurerm_monitor_log_profile.test: Error Creating/Updating Log Profile "default": insights.LogProfilesClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

**Comment by JunyiYi** [comment] 2018-11-05 21:13
This error is caused by the limitation of at most one log-profile in one subscription. The detailed error message is `The limit of 1 log profiles was reached. To create new log profile 'default', delete an existing one.`

**Comment by tombuildsstuff** [comment] 2018-11-05 22:19
@JunyiYi sounds like this could probably do with a blue info box on the documentation page (see below) to explain about this? e.g.

```
-> **NOTE:** It's only possible to configure one Log Profile per Subscription
```

**Comment by JunyiYi** [comment] 2018-11-07 23:06
@tombuildsstuff Yes I agree, let me simply add that.

**Comment by tombuildsstuff** [comment] 2018-11-08 09:40
Closing since this has been documented in #2265

**Closed by tombuildsstuff** 2018-11-08 09:40 UTC
Labels: question, service/monitor
