### ISSUE TITLE
Support for independant object for azurerm_api_management_policy

### ISSUE THREAD

**Issue by pjeannet-dior** [terraform-providers/terraform-provider-azurerm#5228] opened 2019-12-20 14:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have independent policy objects for APIs, operations or products but not a root policy object. This can only be set in the `azure_api_management` object.

### New or Affected Resource(s)

* azurerm_api_management_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management_policy" "example" {
  api_management_name = "${data.azurerm_api_management_api.example.api_management_name}"
  resource_group_name = "${data.azurerm_api_management_api.example.resource_group_name}"

xml_content = <<XML
<policies>
  <inbound>
    <find-and-replace from="xyz" to="abc" />
  </inbound>
</policies>
XML
}
```

### References

* #0000

**Comment by olohmann** [comment] 2020-01-07 22:15
Likely a duplicate of #5015 .

**Comment by tombuildsstuff** [comment] 2020-01-08 11:56
@olohmann thanks for the heads up - agreed this appears to be a duplicate of #5015

**Closed by tombuildsstuff** 2020-01-08 11:56 UTC
Labels: enhancement, service/api-management
