### ISSUE TITLE
data.azurerm_image to pull latest image based on prefix?

### ISSUE THREAD

**Issue by synhershko** [terraform-providers/terraform-provider-azurerm#577] opened 2017-11-19 06:59 UTC
Hi there,

Using latest Terraform (Terraform v0.11.0, provider.azurerm v0.3.3), I'm trying to pull the latest machine image stored in a resource group. Similar to how I'd do this with AWS AMIs, I'm prefixing the image names with my app name and suffix by a time stamp (e.g. `myapp-2017-11-17T013212`), but that doesn't seem to work:

```
data "azurerm_image" "myapp" {
  name                = "myapp-*"
  resource_group_name = "packer-myapp-images"
}
```

Is there a way of doing this? or, can that be supported?

Thanks

**Comment by tombuildsstuff** [comment] 2017-11-21 13:02
Hey @synhershko 

So we don't support this functionality at the moment - that said I think this'd make a great enhancement.

Taking a look at this I think this would make most sense within the `azurerm_managed_disk` data source - given the API used within an `azurerm_image` doesn't appear to return the time that the image was created at (and it's also what Packer generates - whereas an `azurerm_image` is more for collections of disks).

Thanks!

**Comment by synhershko** [comment] 2017-11-21 13:07
wrt to image creation time - there's no need. Just like in AWS I'm naming the images like this `myapp-2017-11-17T013212` , `myapp-2017-11-20T080024` so you just need to query by prefix and sort lexicography. I hope that makes sense

**Comment by tombuildsstuff** [comment] 2017-12-05 17:19
Hey @synhershko 

Just noticed this is a duplicate of #577 - as such I'm going to close this in favour of that issue to track this feature request in a single place.

Thanks!

**Closed by tombuildsstuff** 2017-12-05 17:19 UTC
Labels: enhancement, good first issue
