### ISSUE TITLE
azurem_sql_server administrator_login_password secret displayed in Terraform State 

### ISSUE THREAD

**Issue by nick-otter** [terraform-providers/terraform-provider-azurerm#3033] opened 2019-03-12 12:11 UTC
### Terraform (and AzureRM Provider) Version
```
Terraform v0.11.8
+ provider.azuread v0.1.0
+ provider.azurerm v1.23.0
+ provider.random v2.0.0
```
### Affected Resource

* `azurerm_sql_server`

### main.tf
```hcl
locals {
  common_tags = {
    terraform = "true"
    environment = "${var.environment}"
  }
}

#SQL server names need to be globally unique so we need a random id
resource "random_id" "sql_server_name" {
  byte_length = 6
  keepers {
    sa_account_ref = 1
  }
}

# SQL Server
resource "azurerm_sql_server" "sql_server" {
  count                        = "${(var.sql_server_ha != "true" ? 1 : 0)}"
  name                         = "${var.sql_server_name}-${var.environment}-sql${random_id.sql_server_name.hex}-sqlserver"
  resource_group_name          = "${var.sql_server_resource_group_name == "" ? var.resource_group_name : var.sql_server_resource_group_name}"
  location                     = "${var.location}"
  version                      = "${var.sql_server_version}"
  administrator_login          = "${var.sql_server_administrator_login_username}"
  administrator_login_password = "${var.sql_server_administrator_login_password}"
  tags                         = "${merge(map("Name", "${var.sql_server_name}-${var.environment}-sql${random_id.sql_server_name.hex}-sqlserver", "ResourceType", "SQLServer"), "${local.common_tags}", "${var.resource_tags}")}"
}
```

### Expected Behavior

Parameter `azurem_sql_server.sql_server.administrator_login_password` cannot be seen when running `terraform state show`.

```
PS D:\Azure DevOps\terraform\azure\environments\production> terraform state show module.spektrix_weu_pod1.module.pod_pool_sql_server.azurem_sql_server.sql_server_ha
id                                              = foo
administrator_login                  = foo
fully_qualified_domain_name   = foo
location                                    = foo
name                                        = foo
resource_group_name             = foo
tags.%                                      = foo
tags.Name                               = foo
tags.ResourceType                  = foo
tags.environment                    = foo
tags.terraform                         = foo
version                                    = foo
```

### Actual Behavior
```
PS D:\Azure DevOps\terraform\azure\environments\production> terraform state show module.spektrix_weu_pod1.module.pod_pool_sql_server.azurem_sql_server.sql_server_ha
id                                              = foo
administrator_login                  = foo
administrator_login_password = bar plain text
fully_qualified_domain_name   = foo
location                                    = foo
name                                        = foo
resource_group_name             = foo
tags.%                                      = foo
tags.Name                               = foo
tags.ResourceType                  = foo
tags.environment                    = foo
tags.terraform                         = foo
version                                    = foo
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform state pull`
3. `terraform state show < module name >`

**Comment by Lucretius** [comment] 2019-03-18 08:57
This is not actually a bug with the Azure provider, just a current behavior of Terraform in general.

Terraform stores its state file in plain text.  Resource properties marked as "sensitive" prevent output of `terraform apply`, and other logs from displaying sensitive information in plain text, but when reading directly from the state file via `terraform state show`, that plain text information from the file is simply read out as-is.

**Comment by katbyte** [comment] 2019-04-27 01:53
Hi @nick-otter,

as @Lucretius pointed out this is not a bug. Terraform does not encrypt sensitive values like passwords in the state. For more informations please see the [terraform documentation](https://www.terraform.io/docs/state/sensitive-data.html)

**Closed by katbyte** 2019-04-27 01:53 UTC
Labels: question, service/mssql
