### ISSUE TITLE
azurerm_api_management wipes out / cannot manage CA Certificates

### ISSUE THREAD

**Issue by bradrlaw** [terraform-providers/terraform-provider-azurerm#8598] opened 2020-09-23 16:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Terraform should be able to manage the Certificate Authority  state and preserve it across changes to the API management instance.

### Actual Behavior

Any changes to the API management instance result in the CA certificates / configuration being removed from the API management instance.  There is not method to control / add the CA certificates from terraform for the API management instance.

### Steps to Reproduce

1. Create an API management instance using terraform or manually
2. Add CA certificates through the portal
3. Attempt to get the state of the service via terraform or apply changes
4. The state does not have the CA certificate information and any applied changes will remove them

### References

* #0000

**Comment by yupwei68** [comment] 2020-09-24 03:09
Duplication of https://github.com/terraform-providers/terraform-provider-azurerm/issues/7815

**Comment by tombuildsstuff** [comment] 2020-09-24 06:48
hi @bradrlaw 

Thanks for opening this issue :)

As @yupwei68 has mentioned this appears to be a duplicate of ##7815 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to ##7815 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-09-24 06:48 UTC
