### ISSUE TITLE
Existing azurerm TF code now requires additional provider namespace registrations

### ISSUE THREAD

**Issue by spmsaj** [terraform-providers/terraform-provider-azurerm#3960] opened 2019-07-29 18:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_network  azurerm_virtual_network_peering  azurerm_route azurerm_policy_assignment`

### Terraform Configuration Files

```hcl
ex: 
resource "azurerm_virtual_network" "vnet" {
  name                = "myvnetname}"
  location            = "azurelocation"
  resource_group_name = "rg-name"
  dns_servers         = ["${var.dnsserver1}"]
  address_space	      = ["${var.addressspace}"]
  depends_on          = ["module.routetable"]
}
```

### Expected Behavior

'Existing code - no changes on developer end. Would have added vnets and corresponding peer networking components and routes'
### Actual Behavior

'Errors out stating Azure.Databricks , Azure.Maps, Azure.StreamAnalytics, Azure.Media and Azure.cdn are not registered.
ex: * provider.azurerm.hub: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.Maps with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 '
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment] 2019-07-29 23:56
Hi @spmsaj,

I am going to close this as a duplicate of #3950 where a more detailed response can be found. In short you can disable provider registration by using the [`skip_provider_registration` flag](https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration).

**Closed by katbyte** 2019-07-29 23:56 UTC
