### ISSUE TITLE
azurerm_storage_account primary_connection_string returns wrong value

### ISSUE THREAD

**Issue by suhancz** [terraform-providers/terraform-provider-azurerm#2538] opened 2018-12-18 15:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.10
+ provider.azurerm v1.20.0

### Affected Resource(s)

* azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage_settlementbatch" {
  name = "settlementbatch"
  account_tier = "Standard"
  account_kind = "BlobStorage"
  account_replication_type = "RAGRS"
  enable_blob_encryption = "True"
  enable_file_encryption = "True"
  access_tier = "Hot"
  resource_group_name = "${azurerm_resource_group.data.name}"
  location = "${var.location}"
  tags {
    CreatedBy = "${var.CreatedBy}"
    CreationDate = "${var.CreationDate}"
  }
  depends_on = ["azurerm_resource_group.data"]
}

output "storage_account_primary_connection_string" {
  value = "${azurerm_storage_account.storage_settlementbatch.primary_connection_string}"
}

### start of code referencing to primary connection string

data "azurerm_storage_account_sas" "storage_settlementbatch" {
  connection_string = "azurerm_storage_account.storage_settlementbatch.primary_connection_string"
  https_only        = true

  resource_types {
    service   = true
    container = false
    object    = false
  }

  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }
  
  start  = "2018-12-04"
  expiry = "2099-12-31"

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
    update  = true
    process = true
  }
}

output "sas_url_query_string_settlementbatch" {
  value = "${data.azurerm_storage_account_sas.storage_settlementbatch.sas}"
}
### end of code referencing to primary connection string
```

### Expected Behavior
azurerm_storage_account primary_connection_string should reflect a proper connection string, e.g. ```DefaultEndpointsProtocol=https;AccountName=ourfiles;AccountKey=FxxxxxxxxxxxxxxF==;EndpointSuffix=core.windows.net```

### Actual Behavior
When using anything (in my case azurerm_storage_account_sas) what refers to a storage account's primary_connection_string Terraform reflects the truth that the retrieved connection string is not a valid key=value pair:
```[ERROR] token `azurerm_storage_account.storage_settlementbatch.primary_connection_string` is an invalid key=pair (connection string azurerm_storage_account.storage_settlementbatch.primary_connection_string)```
When checking the value of the connection string I only get "Standard"

### Steps to Reproduce

1. `terraform apply` using resources which refer to the storage account's primary connection string
2. terraform errs out with the above error message
3. `terraform apply` with the resources referring to the connection string commented out terraform doesn't throw an error
4. `terraform output storage_account_primary_connection_string` shows that the connection string doesn't contain a proper connection string, only "Standard"
### References

* #2465 the fix for the referred issue seems to only hide the symptoms, but the issue with not being able to use SAS data sources persists

**Comment by seppi91** [comment] 2019-07-01 11:06
I think this issue is fixed. At least it does not occure on my side with azruerm v1.31.0

**Comment by neil-yechenwei** [comment] 2020-06-03 08:50
@suhancz , thanks for opening this issue. After tested, seems I can get `primary_connection_string` successfully with tfconfig you provided. So could you help to double check whether the problem still exists? If still exists, could you share your latest tfconfig that trigger this problem? Thanks.

**Comment by ArcturusZhang** [comment] 2020-06-05 09:28
Hi @suhancz 

Since we cannot reproduce this issue on the latest version of the provider, I would close this issue for now, but if you find this issue persists on the latest provider, please feel free to reopen, comment or open a new issue regarding the latest version of the provider.

Thank you!

**Closed by ArcturusZhang** 2020-06-05 09:28 UTC
Labels: bug, service/storage
