### ISSUE TITLE
Terraform takes more than 1 hour to update Azure frontdoor

### ISSUE THREAD

**Issue by veteixei** [terraform-providers/terraform-provider-azurerm#9455] opened 2020-11-24 20:24 UTC
Hello,

I'm trying clarify my cx about the subject on this thread: 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/9295

In the documentation it is described the timeouts that can be specified:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor#timeouts
"
The timeouts block allows you to specify timeouts for certain actions:
create - (Defaults to 6 hours) Used when creating the FrontDoor.
update - (Defaults to 6 hours) Used when updating the FrontDoor.
read - (Defaults to 5 minutes) Used when retrieving the FrontDoor.
delete - (Defaults to 6 hours) Used when deleting the FrontDoor.
"

As per my understanding it is to define the timeout and not the duration of the update.

By the other hand, per Microsoft's documentation, "A new Front Door creation or any updates to an existing Front Door takes about 3 to 5 minutes for global deployment. That means in about 3 to 5 minutes, your Front Door configuration will be deployed across all of our POPs globally."

https://docs.microsoft.com/en-gb/azure/frontdoor/front-door-faq#how-long-does-it-take-to-deploy-an-azure-front-door-does-my-front-door-still-work-when-being-updated

How can we explain the the 3 hours that we are having?

Many thanks,
Vera

**Comment by veteixei** [comment] 2020-12-01 09:29
Hello Team,

Does anyone can help on this question?

Thanks,
Vera

**Comment by veteixei** [comment] 2020-12-04 10:00
@manicminer Are you able to help me in this question?

Thanks a lot!

**Comment by cpressland** [comment] 2020-12-11 10:01
Ours is currently taking ~1:45 hours to apply. Not great.

**Comment by manicminer** [comment] 2020-12-12 03:25
Although I haven't looked into this at great length, this is most likely to be due to API / service behavior. Whilst Azure documentation might state those times, what you're seeing is likely to be the actual provisioning time, not artificially extended by the provider.

**Comment by robselway** [comment] 2021-01-05 13:22
We have experienced long create times when using front door to provision a certificate for a custom domain. Navigating to the frontend endpoint in the portal reveals the status of the certificate request, which I believe goes to a third party. We contacted support about this - our understanding is that the process sometimes goes wrong, but support are able to resolve.

**Comment by manicminer** [comment] 2021-01-06 12:44
As mentioned earlier, and in the original issue #9295, Terraform doesn't impose additional wait time when creating/updating resources. Frontdoor can take several hours to apply some changes and this is likely the reason you are seeing this. Unfortunately the cited service documentation is inaccurate for this use case. I'm closing this issue for now as a duplicate of #9295, but if you have additional information please feel to comment again here. Thanks!

**Closed by manicminer** 2021-01-06 12:44 UTC
Labels: duplicate, question, service/frontdoor
