### ISSUE TITLE
Azure Terraform provider should have a way to get a data block with the list of zones for a region

### ISSUE THREAD

**Issue by Tasilv** [terraform-providers/terraform-provider-azurerm#5868] opened 2020-02-24 20:31 UTC
**Azure Global Feedback Owner:** Muazma Zahid 
**ADO Feedback 19444**
**Exit Criteria / Customer Goal State**
Terraform provider requires you to specify a list of zones to use when creating a resource and fails if that region does not have those zones. there should be a way to get the list of supported zones in a region through the Terraform CLI.
**Description / Customer Scenario**
I want to write terraform that deploys a VMSS into zones if zones are available in the region by purely using Terraform capabilities without custom scripting and custom Terraform extensions being built.
**Customer Impact**
No easy way to just use zones if available.
**Mitigation Description**
You have to manually configure each deployment with the list of zones. Easy to get wrong.

**Comment by tombuildsstuff** [comment] 2020-02-26 13:49
hi @Tasilv 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3025 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3025 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-02-26 13:49 UTC
