### ISSUE TITLE
azurerm_sql_server

### ISSUE THREAD

**Issue by x264243** [terraform-providers/terraform-provider-azurerm#9688] opened 2020-12-04 12:25 UTC
It is required to know if the properties **ssl_minimal_tls_version_enforced** and **public_network_access_enabled**
are planned to be included in the module **azurerm_sql_server** in some future version, as found in the azurerm_mysql_server module.

**Comment by tombuildsstuff** [comment] 2020-12-04 12:52
Duplicate of #9687

**Closed by tombuildsstuff** 2020-12-04 12:52 UTC
