### ISSUE TITLE
Support for data.azurerm_key_vault_certificate

### ISSUE THREAD

**Issue by matt40k** [terraform-providers/terraform-provider-azurerm#6311] opened 2020-03-31 16:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for data source of azurerm_key_vault_certificate

### New or Affected Resource(s)

data azurerm_key_vault_certificate

### Potential Terraform Configuration

```hcl
data "azurerm_key_vault_certificate" "example" {
  name         = "imported-cert"
  key_vault_id = data.azurerm_key_vault.existing.id
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-04-01 10:25
hi @matt40k 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2898 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2898 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-04-01 10:25 UTC
Labels: duplicate, new-data-source, service/keyvault
