### ISSUE TITLE
Add Support for Azure Storage VNET Tunneling and Firewall.

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#787] opened 2018-02-02 15:47 UTC
Could we please get support added for Azure Storage VNET Tunneling and Firewall?

https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#grant-access-from-an-internet-ip-range

**Comment by katbyte** [comment] 2018-05-31 19:27
Hi @rohrerb,

Closing as this appears to be a duplicate of #416.

**Closed by katbyte** 2018-05-31 19:27 UTC
Labels: enhancement, microsoft/1, microsoft/3, service/storage
