### ISSUE TITLE
terraform fails reading queue properties for AzureRm Storage Account - Issuer Validation Failed (USGovernment Cloud)

### ISSUE THREAD

**Issue by sladeedmonds** [terraform-providers/terraform-provider-azurerm#4081] opened 2019-08-13 20:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.6
AzureRM Provider 1.32.1

### Affected Resource(s)

Storage Accounts

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage_account_terraform" {
  name                      = "storagename"
  location                  = azurerm_resource_group.resource_group_terraform.location
  resource_group_name       = azurerm_resource_group.resource_group_terraform.name
  account_kind              = "Storage"
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true

  network_rules {
    ip_rules = var.public_ip_region_list
  }

  tags = {
    Department  = "test"
    projectName = "test"
  }
}
```

### Expected Behavior

Running terraform plan should not fail.

### Actual Behavior

Running terraform plan fails with:

Error: Error reading queue properties for AzureRM Storage Account "storageaccount": queues.Client#SetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:8186b357-3003-00a2-7918-52d73f000000\nTime:2019-08-13T20:50:26.7292338Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>" error: invalid character 'ï' looking for beginning of value

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Running in US Government Cloud

### References

* #3997 
Git 3997 is very similar, but not an identical error.  As with 3997, I can downgrade to 1.31.0 to avoid the issue.  If I update to 1.32.0, I get an error about advanced threat protection (due to it not being available in Gov), which is resolved with 1.32.1, but 1.32.1 triggers this issue.

**Comment by tombuildsstuff** [comment] 2019-08-15 08:35
hi @sladeedmonds 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3939 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3939 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-15 08:35 UTC
