### ISSUE TITLE
source_image_reference block description not available in azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by RastogiAbhijeet** [terraform-providers/terraform-provider-azurerm#6892] opened 2020-05-13 10:42 UTC
On the given link in the documentation, 

https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html#source_image_reference

source_image_reference - definition is not available in the documentation. 

I am suspecting someone must have forgotten about it :/

**Comment by tombuildsstuff** [comment] 2020-05-13 10:48
hi @RastogiAbhijeet 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6403 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6403 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-13 10:48 UTC
