### ISSUE TITLE
Default Agent Pool not found for AKS AvailabilitySet cluster

### ISSUE THREAD

**Issue by yaakov-h** [terraform-providers/terraform-provider-azurerm#10674] opened 2021-02-21 03:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.14.7 (linux amd64)

Providers:
- hashicorp/azurerm v2.48.0
- hashicorp/aws v3.29.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "primary" {
  name                = "smash-kubernetes-primary"
  resource_group_name = azurerm_resource_group.services.name
  location            = var.primary_cluster_location
  dns_prefix          = "smash-aks-node"

  default_node_pool {
    name            = "default"
    node_count      = "2"
    vm_size         = "Standard_A2_v2"
    os_disk_size_gb = 30
    type            = "AvailabilitySet"
  }

  linux_profile {
    admin_username = "smash-admin"

    ssh_key {
      key_data = var.cluster_admin_ssh_key
    }
  }

  service_principal {
    client_id     = var.cluster_application
    client_secret = var.cluster_service_principal_password
  }
}
```

### Debug Output

Available on request if you really need it for this, since I'm concerned about secrets/credentials being included in the log.

### Expected Behaviour

I expect that Terraform/AzureRM would have detected the existing node pool that is the default node pool.

### Actual Behaviour

> Error: flattening `default_node_pool`: The Default Agent Pool "" was not found

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I am attempting to migrate a working configuration from Terraform 0.12 and AzureRM 1.33 to the latest versions (as listed above).

As this cluster is an older availability-set-based cluster, I cannot use the `az aks nodepool update` workaround (in links below) to change the NodePool type from "User" to "System".

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/7813
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/8869
* https://discuss.hashicorp.com/t/migration-from-agent-pool-profile-to-default-node-pool/11393

**Comment by tombuildsstuff** [comment] 2021-02-22 06:40
hi @yaakov-h 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5551 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5551 for updates?

That said - as I understand it, support for AKS clusters using the `AvailabilitySet` type is deprecated and will be removed in the future - as such I'd recommend switching to using the `VirtualMachineScaleSet` type if possible.

Thanks!

**Closed by tombuildsstuff** 2021-02-22 06:40 UTC

**Comment by yaakov-h** [comment] 2021-02-22 06:46
I've had a read through that one and it appears to be a different error. Rather than getting an HTTP error from trying to use an API in an unsupported manner, I'm getting an internal error from the AzureRM provider as it tries to figure out what to do with the cluster.

I understand that AvailabilitySet is deprecated and was looking to rebuild the cluster _after_ updating Terraform/AzureRM. I'm not sure that the old version I was on even supports VMSS.
