### ISSUE TITLE
Advanced networking future update in AKS services

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#1527] opened 2018-07-10 12:41 UTC
Since AKS Version update to 2018-03-31, they added a new future that "Advanced networking". Our Terraform should  have a update to cover this future.

![image](https://user-images.githubusercontent.com/20538091/42510398-580c91a6-8481-11e8-9278-069be4709b0a.png)

Name | Type | Description
-- | -- | --
dnsServiceIP | string | An IP address assigned to the Kubernetes DNS service. It must be within the Kubernetes service address range specified in serviceCidr.
dockerBridgeCidr | string | A CIDR notation IP range assigned to the Docker bridge network. It must not overlap with any Subnet IP ranges or the Kubernetes service address range.
networkPlugin | NetworkPlugin | Network plugin used for building Kubernetes network.
networkPolicy | NetworkPolicy | Network policy used for building Kubernetes network.
podCidr | string | A CIDR notation IP range from which to assign pod IPs when kubenet is used.
serviceCidr | string | A CIDR notation IP range from which to assign service cluster IPs. It must not overlap with any Subnet IP ranges.

Reference:
https://docs.microsoft.com/en-us/azure/aks/networking-overview#advanced-networking
https://docs.microsoft.com/zh-cn/rest/api/aks/managedclusters/createorupdate#containerservicenetworkprofile

**Comment by lfshr** [comment] 2018-07-10 12:52
Duplicate of #1434
Merge Request is open #1479

**Comment by tombuildsstuff** [comment] 2018-07-10 12:55
Duplicate - closing in favour of #1434 (thanks for the issue references @lfshr 😄)

**Closed by tombuildsstuff** 2018-07-10 12:55 UTC
