### ISSUE TITLE
azurerm_linux_virtual_machine does not support data disks which is blocking for cloud-init configuration

### ISSUE THREAD

**Issue by boillodmanuel** [terraform-providers/terraform-provider-azurerm#6074] opened 2020-03-11 19:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_linux_virtual_machine `

### Important Factoids

The `azurerm_virtual_machine`resource supports data_disks, but this isn't possible with the new `azurerm_linux_virtual_machine` or `azurerm_windows_virtual_machine`.

[edit]

As soon as the vm is created, the `cloud-init` initialization starts. As we can not attach a data disk in a single operation with `azurerm_linux_virtual_machine`, **we can not mount nor do anything with the data disk** during the `cloud-init` operation. 

However, it's pretty common (a best practice) to 
- use cloud-init for vm initialization
- rely on a data disk for persistent data

👉 **This use case is not possible anymore.** 😢

**Comment by ArcturusZhang** [comment] 2020-03-12 10:36
Hi @boillodmanuel thanks for this issue, but in 2.0 the `azurerm_linux_virtual_machine` (as well as `azurerm_windows_virtual_machine`) must use the new resource `azurerm_virtual_machine_data_disk_attachment` to attach data disk for them.
Here is the doc page for `azurerm_virtual_machine_data_disk_attachment`: https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_data_disk_attachment.html

**Comment by boillodmanuel** [comment] 2020-03-12 10:42
Thanks @ArcturusZhang for your answer.

But having a separate resource for that does not enable my use case, where the custom data script (a cloud-init script) mount the data disk volume and do stuff on it.

**Comment by boillodmanuel** [comment] 2020-03-12 10:43
To fulfil my answer, I'm able to do that with current "azurerm_virtual_machine".

**Comment by boillodmanuel** [comment] 2020-03-24 08:34
Hello @ArcturusZhang , any update about this use case ? The #6117 is a similar issue.

**Comment by jpbuecken** [comment] 2020-05-11 07:30
You may be able to use `azurerm_virtual_machine_extension` to run your customization.
You need to add `depends_on` in `azurerm_virtual_machine_extension` that point to the id of `azurerm_virtual_machine_data_disk_attachment`

That should achieve the same goal.

**Comment by boillodmanuel** [comment] 2020-05-11 09:03
Hello @jpbuecken, I could do that, but this is an ugly workaround, and force me to rewrite everything in a non-standard way.

Indeed, the standard way of initializing a VM is using [cloud-init](https://cloudinit.readthedocs.io/en/latest/). It's now mainstream for at least Azure, AWS, GCP.

If I use `azurerm_virtual_machine_extension`, I cannot rely to cloud-init mechanism anymore. 
It's a **breaking change** from `azurerm_virtual_machine` 😱.

For my company, this prevents us to move to the new `azurerm_linux_virtual_machine` resource, and we  are forced to stay on the deprecated `azurerm_virtual_machine` resource 😟.

**Comment by boillodmanuel** [comment] 2020-05-26 11:52
Hello, any news about this issue? How are you considering it?
Do you need more details?

**Comment by boillodmanuel** [comment] 2020-06-10 10:44
I updated the main issue with comments content to get a clear overview

**Comment by boillodmanuel** [comment] 2020-06-24 09:31
Just discovered a related issue for the windows version: #6004

**Comment by cloves-jr** [comment] 2020-06-24 16:32
I'm facing the same issue, if I use a image with data disk and try to create with azurerm_linux_virtual_machine occurs the 400 error.

**Comment by jontreynes** [comment] 2020-08-28 13:48
Reporting error relating to this issue

```Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile." Target="storageProfile"```

Similar to the error you see for the windows virtual machine resource #6004

**Comment by val3r10** [comment] 2020-12-03 13:51
Hello! This bug is still present and is making us use "azurerm_virtual_machine" for deploy VMs that are custom created by vendor, like:

    publisher = "IBM"
    offer     = "qradar733"
    sku       = "mh733"
    version   = "latest"

**Comment by PPACI** [comment] 2021-01-12 12:18
I'm reporting the same error in the following scenario.

1. Create a linux vm image including os and data disk
2. Create a managed disk in a disk encryption set
3. Create a VM using image created in (1) with an encrypted OS disk
4. Attach the encrypted data disk with `azurerm_virtual_machine_data_disk_attachment`
5. `terraform apply`

This will lead to 
> Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile." Target="storageProfile"

As I understand it, the image is searching for a data disk which is attached in a separate object, thus not available strictly at creation time.

**Comment by ruandersMSFT** [comment] 2021-01-31 20:46
Also encountering when trying to deploy an VM based on an Azure Image that has both an OS Disk and more or more Data Disk(s).  The cause of this is the observed implementation that Data Disk are **only** handled via the association resource.  While association works for data disk associations that can occur after the VM deployment has occurred, many use cases exist where the DataDisks definition must be provided directly (not via a secondary association process). 

The Terraform code causing this issue for many can be noted on [line 391 of linux_virtual_machine_resource.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/349893341e2b1eb934bea07d3b253d9774839b6a/azurerm/internal/services/compute/linux_virtual_machine_resource.go#L391), where only an empty array is allowed on creation and nil on update.

Code fix for this issue needs to enable direct use of DataDisks.

**Comment by tombuildsstuff** [comment] 2021-02-01 06:38
👋 

Just noticed there's 3 issues tracking the same thing: this issue, #6004 (for windows VM's) and #6117 - rather than having 3 issues tracking the same thing I'm going to close this in favour of #6117 - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-01 06:38 UTC
Labels: question, service/virtual-machine

**Comment by ruandersMSFT** [comment] 2021-02-01 06:55
@tombuildsstuff Not really off topic
