### ISSUE TITLE
Add support to "create filesystem in Azure Data Lake Storage Gen2" 

### ISSUE THREAD

**Issue by svangeti** [terraform-providers/terraform-provider-azurerm#4244] opened 2019-09-04 18:55 UTC
There is no terraform resource currently available to "create filesystem in Azure Data lake storage gen2"

### New or Affected Resource(s)

* new resource
### Potential Terraform Configuration

**accountName** | The Azure Storage account name.
**dnsSuffix** | The DNS suffix for the Azure Data Lake Storage endpoint.
**filesystem**|The filesystem identifier. The value must start and end with a letter or number and must contain only letters, numbers, and the dash (-) character. Consecutive dashes are not permitted. All letters must be lowercase. The value must have between 3 and 63 characters.Regex pattern: ^[$a-z0-9](?!.*--)[-a-z0-9]{1,61}[a-z0-9]$
**resource** |The value must be "filesystem" for all filesystem operations.
**timeout** |An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails.

### References

https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/filesystem

**Comment by tombuildsstuff** [comment] 2019-09-05 11:12
upstream issue: https://github.com/tombuildsstuff/giovanni/issues/10

**Comment by tombuildsstuff** [comment] 2019-09-06 11:05
Should be enabled by https://github.com/tombuildsstuff/giovanni/pull/14

**Comment by tombuildsstuff** [comment] 2019-09-11 10:49
hi @svangeti 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3319 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3319 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-11 10:49 UTC
Labels: new-resource, service/storage, upstream

**Comment by svangeti** [comment] 2019-09-11 11:28
Hello Tom,
I have subscribed to the other issue. By any chance, is it possible to let
me know when this feature be merged. I see a PR created with the change
implemented.

Thanks for your help.
