### ISSUE TITLE
Anyone use terragrunt with apply-all for azure projects?

### ISSUE THREAD

**Issue by stonefury** [terraform-providers/terraform-provider-azurerm#1850] opened 2018-08-30 17:57 UTC
I'm trying to use terragrunt apply-all for a large azure project.  I build the network layer as a separate project, for safety reasons.  So all of my modules must create a data source so I can pull information about my network.

data "terraform_remote_state" "network" {
  backend   = "azurerm"
  workspace = "${terraform.workspace}"

  config {
    resource_group_name  = "${local.workspace["remote_state_resource_group_name"]}"
    access_key           = "${var.access_key}"
    storage_account_name = "${local.workspace["tfstate_storage_account_name"]}"
    container_name       = "${local.workspace["container_name"]}"
    key                  = "${local.workspace["remote_state_key"]}"
  }
}

However, when I run apply-all, I get an error that says the remote data source state file is locked. I would assume terraform_remote_state is doing a read-only, but clearly when TF is reading the data, it locks the file.

This makes running parallel apply (doesn't matter if it's terragrunt doing it) commands impossible. Anyone have this problem, and is this a provider issue or a terraform base code issue?

Thanks!

**Comment by tombuildsstuff** [comment] 2018-10-22 19:33
hey @stonefury 

Thanks for opening this issue - apologies for the delayed response here!

As mentioned in https://github.com/hashicorp/terraform/issues/18761 - the root cause for this appears to be hashicorp/terraform#17046 (since the Data Source consumes the backend) - rather than keeping multiple issues open tracking the same thing I'm going to close this issue in favour of that one.

Thanks!

**Closed by tombuildsstuff** 2018-10-22 19:33 UTC
Labels: question
