### ISSUE TITLE
Cannot create VM based on managed disk

### ISSUE THREAD

**Issue by perbergland** [terraform-providers/terraform-provider-azurerm#1364] opened 2018-06-07 20:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.6.0

### Affected Resource(s)

* azurerm_virtual_machine

### Terraform Configuration Files

```hcl

resource "azurerm_managed_disk" "vs2017" {
  name                 = "vs2017-disk"
  location             = "${local.vm_loc}"
  resource_group_name  = "${local.vm_rg}"
  storage_account_type = "Standard_LRS"
  create_option        = "Import"
  source_uri           = "${var.source_vhd_uri}"
  os_type              = "Windows"

  tags = "${var.tags}"
}

resource "azurerm_virtual_machine" "vsts_vm" {
  name                  = "vsts-vm"
  location              = "${local.vm_loc}"
  resource_group_name   = "${local.vm_rg}"
  network_interface_ids = ["${azurerm_network_interface.for_vm.id}"]
  vm_size               = "${var.vm_size}"

  delete_os_disk_on_termination = true

  storage_os_disk {
    name            = "vsts-disk"
    caching         = "ReadWrite"
    managed_disk_id = "${azurerm_managed_disk.vs2017.id}"
    create_option   = "Attach"
    os_type         = "Windows"
  }

  os_profile {
    computer_name  = "${var.vm_computer_name_base}"
    admin_username = "${var.admin_user}"
    admin_password = "${var.admin_password}"
  }

  os_profile_windows_config {
    provision_vm_agent        = true
    enable_automatic_upgrades = true
  }

  tags = "${var.tags}"
}
```

The source_vhd_uri variable is just a uri to a vhd file produced by packer.

### Debug Output

```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine.vsts_vm: 1 error(s) occurred:

* azurerm_virtual_machine.vsts_vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Parameter 'osProfile' is not allowed." Target="osProfile"
```
### Expected Behavior
Should have worked. The same managed disk can be used to create a VM using the portal UI and Azure CLI:
```
az vm create --name $virtualMachineName --resource-group $resourceGroupName --attach-os-disk $managedDiskId --os-type $osType
```
I've tried a bunch of combinations of removing ostype in both the storage options and the managed disk but it didn't help - I just got a different error saying that ostype was missing instead.

### Actual Behavior

I got the error message above. I get the same error message when using the AzureRM cmdlets.
```
Set-AzureRmVMOSDisk -ManagedDiskId <id>
```
so maybe there's something wrong in some shared layer that both the cmdlets and terraform use.

### Steps to Reproduce

1. `terraform apply`

**Comment by perbergland** [comment] 2018-06-07 20:47
Note that none of the examples in the documentation use a managed disk for the OS storage

**Comment by tombuildsstuff** [comment] 2018-06-20 10:58
hi @perbergland 

Thanks for opening this issue.

Looking at the error message being returned from the API here:

> Parameter 'osProfile' is not allowed

The `os_profile` block is optional - as such have you tried removing this block?

Thanks!

**Comment by perbergland** [comment] 2018-06-20 18:13
Well the os_profile block is kinda crucial to be able to create a Windows VM so I'm not sure what removing it would bring. Can you tell where the error message is coming from or let me know how to check if the error is in the provider, the Go SDK or in the Azure API itself?

**Comment by tombuildsstuff** [comment] 2018-06-21 07:50
@perbergland 

> Well the os_profile block is kinda crucial to be able to create a Windows VM so I'm not sure what removing it would bring. Can you tell where the error message is coming from or let me know how to check if the error is in the provider, the Go SDK or in the Azure API itself?


the OS block is only needed if you're provisioning a VM from a Marketplace image (e.g. Windows/Ubuntu/F5 Firewall etc). Where you're creating a managed disk from an existing image (as in the configuration you've posted above), it's not possible to set this field by design in Azure - such that the error message being returned is from the Azure API; as such removing this block should allow this to provision successfully.

Since this is a question regarding configuration and not a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding) 😄 

Thanks!

**Closed by tombuildsstuff** 2018-06-21 07:50 UTC
Labels: question, service/virtual-machine, waiting-response

**Comment by perbergland** [comment] 2018-06-25 19:10
If https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html exposed os_state as a seting then maybe I would be golden :)

**Comment by tombuildsstuff** [comment] 2018-06-26 14:49
@perbergland in this instance since you're using a pre-created image Azure assumes that the credentials already exist inside this machine. I've not touched this area for a while so I'm not 100% sure, however are you running `sysprep` on the VM at the end of the Packer build? I have a feeling that if you do it should be possible to set this option; however if not it uses the credentials which would have been created via Packer.

Hope that helps :)

**Comment by perbergland** [comment] 2018-06-26 19:11
Yeah well the Vhd image is generalized via sysprep (using the ms-provided packer script to build a VS2017 build server for VSTS) so it does need the credentials. Not sure where to go next to find out if it is possible to create vms based on it via managed disks but clearly Microsoft does it for all the provided build servers. I gave up for now and use normal vhd os disks instead.

**Comment by jomeier** [comment] 2019-07-31 10:54
Hi, 

any news on this one? Have the same problem.

Thanks,

Josef
