### ISSUE TITLE
Support for Managed Azure AD in Azure Kubernetes Service

### ISSUE THREAD

**Issue by jlpedrosa** [terraform-providers/terraform-provider-azurerm#7004] opened 2020-05-19 14:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AKS has in public preview the v2 of the integration between aks and aad for RBAC.
[documentation vailable here](https://docs.microsoft.com/en-us/azure/aks/managed-aad)

### New or Affected Resource(s)

* azurerm__kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "test" {
 ...
  role_based_access_control {
    enabled = true
    azure_active_directory {
      tenant_id = var.tenant_id
      managed   = true 
    }
  }
}
```

### References
* https://docs.microsoft.com/en-us/azure/aks/managed-aad
* #6530

**Comment by darrenk13** [comment] 2020-05-19 20:18
This looks it might be the same issue as #6464

**Comment by jlpedrosa** [comment] 2020-05-20 07:58
Hi @danryc 
Yes it seems the same, I just created this, but I created the PR weeks ago, it is just for cross referencing.

**Comment by mybayern1974** [comment] 2020-05-20 09:57
hi  @jlpedrosa 

In this provider, generally rather than having multiple issues open tracking the same thing, we'd recommend subscribe to one source ([#6464](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6464))? So would you mind if we close this one? 

Thanks!

**Comment by tombuildsstuff** [comment] 2020-05-20 10:28
Duplicate of #6464

**Closed by tombuildsstuff** 2020-05-20 10:28 UTC
Labels: duplicate
