### ISSUE TITLE
Azure Key Vault resource creation fails immediately following a destroy

### ISSUE THREAD

**Issue by tareks** [terraform-providers/terraform-provider-azurerm#12285] opened 2021-06-19 02:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
```

### Affected Resource(s)

* `azurerm_key_vault_secret`
* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      recover_soft_deleted_key_vaults = false
      purge_soft_delete_on_destroy    = true
    }
  }
}

resource "azurerm_key_vault_secret" "secret" {
  name         = "test"
  value        = "123"
  key_vault_id = data.azurerm_key_vault.app.id
}

data "azurerm_key_vault" "app" {
  name                = "< keyvault name>"
  resource_group_name = "< keyvault RG name >"
}
```

### Expected Behaviour

Terraform apply should re-create the resources (secrets or certificates).

### Actual Behaviour

Terraform apply immediately following a destroy results in the following error:
```
Error: keyvault.BaseClient#RecoverDeletedSecret: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SecretNotFound" Message="A secret with (name/id) xxxx was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182"
```

If the `features` section of the provider is updated to explictly specify: 
```
      recover_soft_deleted_key_vaults = false
      purge_soft_delete_on_destroy    = true
```

the error then becomes:
```
azurerm_key_vault_secret.secret: Creating...
╷
│ Error: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Secret test is currently being deleted and cannot be re-created; retry later." InnerError={"code":"ObjectIsBeingDeleted"}
│
│   with azurerm_key_vault_secret.secret,
│   on main.tf line 18, in resource "azurerm_key_vault_secret" "secret":
│   18: resource "azurerm_key_vault_secret" "secret" {
```

Perhaps the destroy is not waiting long enough for the correct API response from ARM? Waiting another minute or so seems to resolve this as the resource is eventually marked as deleted/purged from the key vault.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. `terraform apply` << Fails 

### Important Factoids

Reverting to v2.63.0 of azurerm does not seem to resolve this.
This behavior only seemed to start occurring in the past 24 hours (19/06/2021) from what I've observed.

**Comment by adamevans-ns** [comment] 2021-06-21 19:28
The last time it worked for use was on 17th June in a nightly build environment. Right now all it does is seemingly restore back the original secret (timestamped the 5th June) and then fall over with the error detailed above.

**Comment by ShahradGH** [comment] 2021-06-23 08:26
Confirm the above here, as the issue despite now trying different legacy version, seems to only have correclty functioned on a point of time basis rather than build/version basis.

**Comment by premaarya** [comment] 2021-06-30 00:53
Our team is facing this issue, any timeline for fix or alternate solution?

**Comment by tareks** [comment] 2021-06-30 19:53
Looking at this briefly, it appears that this is a result of the of PUT (https://docs.microsoft.com/en-us/rest/api/keyvault/set-secret/set-secret) returning a 409 with the following error:
````
{"error":{"code":"Conflict","message":"Secret test is currently being deleted and cannot be re-created; retry later.","innererror":{"code":"ObjectIsBeingDeleted"}}}
```

This is despite the prior purge (DELETE) call returning a 204 after the secret is deleted.

Logged a call with Microsoft support around this, but we may need the provider to check and handle 409s on the PUT/CREATE operations if this behavior is by design. This seems to only happen on resource re-creation or within a short period of time after a resource is deleted and purged.

**Comment by vermacodes** [comment] 2021-06-30 22:22
This error is happening when secert/key is being recovered. 

```
{"attributes":{},"contentType":"","tags":{},"value":"szechuan"}: timestamp=2021-06-30T15:57:52.122-0400
2021-06-30T15:57:52.580-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Response for https://myKeyVault.vault.azure.net/secrets/secret-sauce?api-version=7.1:
HTTP/2.0 409 Conflict
Content-Length: 176
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Jun 2021 19:57:50 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Keyvault-Network-Info: conn_type=Ipv4;addr=144.160.228.102;act_addr_fam=InterNetwork;
X-Ms-Keyvault-Region: eastus2
X-Ms-Keyvault-Service-Version: 1.9.12.0
X-Ms-Request-Id: b1c6683d-909d-4ee5-8dab-7f21051e24a2
X-Powered-By: ASP.NET

{"error":{"code":"Conflict","message":"Secret secret-sauce is currently being recovered and cannot be re-created; retry later.","innererror":{"code":"ObjectIsBeingRecovered"}}}: timestamp=2021-06-30T15:57:52.580-0400
╷
│ Error: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Secret secret-sauce is currently being recovered and cannot be re-created; retry later." InnerError={"code":"ObjectIsBeingRecovered"}
```

**Comment by tareks** [comment] 2021-07-05 19:13
Microsoft have responded stating that there is a current known issue related to long running operations, such as purging soft-deleted objects, which take longer to complete than expected. No current ETA on a fix, but it is being looked into.

This still seems to happen with 2.66.0. Perhaps a workaround is to extend the PUT request wait time, especially when getting a 409 back? Not sure if one of the core developers has looked at this yet.

**Comment by dvob** [comment] 2021-07-08 07:38
> Looks like Microsoft is rolling out a hotfix for this and expected to be in all regions by 15/07.

@tareks From where do you have this information? Is there somewhere an official communication?

**Comment by tareks** [comment] 2021-07-09 06:09
> > Looks like Microsoft is rolling out a hotfix for this and expected to be in all regions by 15/07.
> 
> @tareks From where do you have this information? Is there somewhere an official communication?

I haven't seen any official communication yet. That was through a direct support call with Azure support.

**Comment by jackofallops** [comment] 2021-07-09 09:52
Hi all - I've been attempting to reproduce this without success, but felt it worth explaining what happens in recovery of KeyVault items.

When a key / secret is deleted, by default it is also purged. Setting the `purge_soft_delete_on_destroy = false` in the features block will skip the purge step in the delete, and leave the item recoverable. By default, `recover_soft_deleted_key_vaults` is `true`, so a create for a key/secret that exists in a soft-deleted state will attempt a recovery. In this case, when we receive the `409 Conflict` we issue a recovery request and then poll the key for availability. We wait 30s before polling, then wait for 10 consecutive successful reads of that item's availability. In the cases described here, and in 12432, this is the 30s + 10 x 10s (resulting in the 2m10s), we then send an update to that item to ensure the item has the settings in the Terraform Config, and not just those the item had before delete. In our test cases, and my recent attempts to reproduce the error here, this works as expected.  

Based on the comment from @tareks this may be purely an underlying service issue where the Key Vault items are possibly erroneously reporting as available before they actually are so, resulting in the issues being seen? 

Is anyone _still_ seeing this as of today? If so, what region are you deploying into and I'll direct my reproduction efforts there.

Thanks.

**Comment by dvob** [comment] 2021-07-09 11:10
@jackofallops I'm also no longer able to reproduce the problem. Maybe in the mean time Microsoft already rolled out their fix? At least yesterday I was able to reproduce the problem as follows:

```
$ terraform version
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
$ terraform apply -auto-approve
$ terraform destroy -auto-approve
$ terraform apply -auto-approve
```
with the following `main.tf`:
```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
      recover_soft_deleted_key_vaults = true
    }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "main" {
  name     = "test-4f2cf1ca-rg"
  location = "West Europe"
}

resource "azurerm_key_vault" "main" {
  name                = "test-4f2cf1ca-kv"
  location            = "West Europe"
  resource_group_name = azurerm_resource_group.main.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name                 = "standard"
  purge_protection_enabled = true
}

resource "azurerm_key_vault_access_policy" "main" {
  key_vault_id       = azurerm_key_vault.main.id
  tenant_id          = data.azurerm_client_config.current.tenant_id
  object_id          = data.azurerm_client_config.current.object_id

  secret_permissions = [
    "get",
    "list",
    "set",
    "recover",
    "delete",
    "purge",
  ]
}

resource "azurerm_key_vault_secret" "api_token" {
  key_vault_id = azurerm_key_vault.main.id
  # we add a dependeny to the creation of the access policy
  depends_on = [azurerm_key_vault_access_policy.main]
  name         = "test"
  value        = "1234"
}

```

**Comment by tareks** [comment] 2021-07-10 01:12
Still reproduceable as of today in Australia East. If some cannot reproduce this, the fix being rolled out appears to resolve the issue, which is great news! We just have to be a little patient, I guess..

@jackofallops Just to clarify, in the case where ` recover_soft_deleted_key_vaults = false` and `purge_soft_delete_on_destroy    = true`,  it appears that the provider will error immediately when a 409 is returned by the create (PUT request?), perhaps under the assumption that the secret does not exist. This probably makes sense because the purge should have been successful at this point, (API returned a 204) but really isn't because of some internal processing delay by the Azure API.

I should've mentioned this before, but this can be reproduced outside of terraform either through direct API calls or even in the azure portal following this sequence:

1. PUT method to add the secret – no issues
2. DELETE method to delete the secret – succeeds with 204
3. DELETE method to purge the (deleted) secret – eventually succeeds with 204 after secret is actually purged (409 returned until it actually is) 
4. PUT method to create the secret << At this point we expect the method to succeed immediately because there shouldn’t be anything anymore if purge has reportedly succeeded? After a number of 409s returned, this eventually succeeds and the secret is created

 Hopefully be all sorted in a few more days for everyone.

**Comment by tareks** [comment] 2021-07-13 19:42
It appears that as of today, things have returned to what is used to be in Australia East. Our old terraform configuration and pipeline code now works again without modification on our part.

**Comment by jackofallops** [comment] 2021-07-14 06:25
Thanks for the updates folks, it's really appreciated!

I'm going to close this based on the feedback that it appears to be a service-side issue that Azure are resolving. If this pop back up, we can revisit it.  Thanks all.

**Closed by jackofallops** 2021-07-14 06:25 UTC
Labels: service/keyvault

**Comment by Sur3n00** [comment] 2021-08-05 08:57
Hi @jackofallops ,

The issue is still reproduceable in WestEurope. I think the issue could be related with the short time between when the secret is marked as deleted (NotFound in the AKV) and when it is recoverable ([get-deleted-secret](https://docs.microsoft.com/en-us/rest/api/keyvault/get-deleted-secret/get-deleted-secret)). If you try to create the secret in this interval this operation always fails with an error: `Status=409 Code="Conflict" Message="Secret test is currently being deleted."` because is trying to recover a secret in BeingDeleted state.

```hcl
provider "azurerm" {
  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = false
    }
  }

data "azurerm_key_vault" "akv" {
  name                = "myakv"
  resource_group_name = "myrsg"
}

resource "azurerm_key_vault_secret" "main" {
  key_vault_id = data.azurerm_key_vault.akv.id
  name         = "test"
  value        = "1234"
}
```

```sh
Provider: hashicorp/azurerm v2.70.0
$ terraform apply -auto-approve
$ terraform destroy -auto-approve
$ terraform apply -auto-approve
    Error: keyvault.BaseClient#RecoverDeletedSecret: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Secret test is currently being deleted." InnerError={"code":"ObjectIsBeingDeleted"}
    │
    │   with azurerm_key_vault_secret.main,
    │   on main.tf line 46, in resource "azurerm_key_vault_secret" "main":
    │   46: resource "azurerm_key_vault_secret" "main" 
```
