### ISSUE TITLE
Azure Automation DSC 

### ISSUE THREAD

**Issue by catz423** [terraform-providers/terraform-provider-azurerm#654] opened 2017-12-30 01:13 UTC
Terraform v0.11.1
+ provider.azurerm v0.2.2

I am having 2 issues with the below DSC VM extension:

1) The extension is installing (showing as installed on each of the VMs, however my node configuration is not registering with my Azure Automation account defined.

2) I have to run my tf file twice on first provisioning the VMs as it states the VM does not yet exists yet, I would think there is an automatic dependency on the VM being created prior to installing any VM extensions?

```
resource "azurerm_virtual_machine_extension" "dsc" {
 count                = 2
 name                 = "${var.vm_hostname}${count.index}"
 location             = "${var.location}"
 resource_group_name  = "${azurerm_resource_group.vm.name}"
 virtual_machine_name = "${var.vm_hostname}${count.index}"
 publisher            = "Microsoft.Powershell"
 type                 = "DSC"
 type_handler_version = "2.73"

 settings = <<SETTINGS
   {
       "configuration": {
           "registrationKey": "XXXX-Removed-XXXX",
           "registrationUrl": "https://scus-agentservice-prod-1.azure-automation.net/accounts/xxxxxx-removed-xxxxx",
           "ConfigurationNames": "FileResource.locahost"
       }
   }
SETTINGS
}
```

anyone successfully bootstrap the Azure Automation DSC extension?

**Comment by divgo** [comment] 2018-01-02 14:42
try adding a depends_on to your resource to stop the "VM does not exist" error;

`depends_on           = ["azurerm_virtual_machine.virtual_machine"]`

**Comment by tombuildsstuff** [comment] 2018-01-03 17:28
hey @catz423 

Thanks for opening this issue :)

To answer both questions in-line:

> The extension is installing (showing as installed on each of the VMs, however my node configuration is not registering with my Azure Automation account defined.

Unfortunately Azure VM Extensions are fairly complex to configure - my bet would be this is an issue with the casing of the JSON.

Checking the history it appears we've previously had an issue opened about DSC here (albeit for the VMSS Extension, they should be similar) - https://github.com/terraform-providers/terraform-provider-azurerm/issues/248#issuecomment-322748489 which may provide some pointers. My suggestion would be that the field `registrationKey` needs to become `RegistrationKey` and the field `registrationUrl` needs to become `RegistrationKey`.

> I have to run my tf file twice on first provisioning the VMs as it states the VM does not yet exists yet, I would think there is an automatic dependency on the VM being created prior to installing any VM extensions?

As @divgo has suggested this is because there's no dependency between the `azurerm_virtual_machine` resource and the `azurerm_virtual_machine_extension` resource, so Terraform believes it can execute them in Parallel / out of order. It's possible to specify either an Explicit Dependency (by referencing the name of the VM via something like `${azurerm_virtual_machine.test.name}`) or an implicit dependency using a `depends_on` as @divgo has suggested.

[There's more information on this here](https://www.terraform.io/docs/configuration/resources.html#explicit-dependencies) and I'd recommend using an Explicit Dependency where possible, by referencing the resource through the [interpolation syntax](https://www.terraform.io/docs/configuration/interpolation.html#attributes-of-other-resources) as shown above.

---

Given the remaining issue doesn't appear to be a bug with Terraform (and is instead a configuration issue with the VM Extension Resource) - I'm going to close this issue for the moment, but please feel free to follow up here and we'll try and work through this :)

Hope that helps?

Thanks!

**Closed by tombuildsstuff** 2018-01-03 17:28 UTC
Labels: question

**Comment by divgo** [comment] 2018-01-03 18:34
I think the problem is we are expecting the DSC Extension to be able to register a VM with Azure Automation, but that is not what the extension actually does. Looking at the list of properties available when installing an extension, none of the properties are for Azure Automation DSC registration. 

![image](https://user-images.githubusercontent.com/9498673/34534027-a5b8c4f0-f08a-11e7-9a73-e3c792837fb3.png)

**Comment by divgo** [comment] 2018-01-03 23:26
I got this to work today and just committed the scripts\terraform files that worked for me;
https://github.com/divgo/terraform/tree/master/bootstrap_azure_automation

**Comment by catz423** [comment] 2018-01-04 17:18
Thanks, I will try this in a few days to confirm.

**Comment by cdeli** [comment] 2018-06-15 19:10
@catz423 did this work for you? I am trying to get this to work myself, I need to set up a VMSS set.
