### ISSUE TITLE
terraform import azure resource in submodule results in `Azure CLI Authorization Profile was not found`

### ISSUE THREAD

**Issue by erniebilling** [terraform-providers/terraform-provider-azurerm#8165] opened 2020-08-19 00:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
provider.azurerm v2.20.0

### Affected Resource(s)

* `azurerm_azure_sql_db`

### Terraform Configuration Files

instance.tf.json
```json
{
  "module": {
    "instance": {
      "azure_client_id": "<redacted>",
      "azure_client_secret": "<redacted>",
      "azure_subscription_id": "<redacted>",
      "azure_tenant_id": "<redacted>",
      "skip_provider_registration": false,
      "source": "./brokertemplate"
    }
  }
}
```
brokertemplate\main.tf
```hcl
resource "azurerm_sql_database" "azure_sql_db" {
}
```
brokertemplate\provider.tf
```hcl
variable azure_subscription_id { type = string }
variable azure_client_id { type = string }
variable azure_client_secret { type = string }
variable azure_tenant_id { type = string }
variable skip_provider_registration { type = bool }

provider "azurerm" {
  version = "~> 2.20.0"
  features {}

  subscription_id = var.azure_subscription_id
  client_id       = var.azure_client_id
  client_secret   = var.azure_client_secret
  tenant_id       = var.azure_tenant_id  

  skip_provider_registration = var.skip_provider_registration
}
```

### Expected Behavior

When `terraform input` is run, it should successfully import the requested resource.

### Actual Behavior

`terraform imort` fails with

```
Error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

  on brokertemplate/provider.tf line 21, in provider "azurerm":
  21: provider "azurerm" {
```

### Steps to Reproduce

With example files above:

`terraform import module.instance.azurerm_sql_database.azure_sql_db /subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/rg-csb-azsql-svr-d33bb79e-0178-4f53-adcf-6cfd53b523cf/providers/Microsoft.Sql/servers/csb-azsql-svr-d33bb79e-0178-4f53-adcf-6cfd53b523cf/databases/test-db`

Last parameter doesn't matter since it fails before trying to query Azure

**Comment by magodo** [comment] 2020-08-24 06:35
@erniebilling Thank youf for submitting this!

Unfortunately, I'm unable to reproduce your issue with the exactly same provider version and terrafrom config. Are you using a remote backend as mentioned in #5313? 

Besides, if possible can you change the code where the error derived a bit to wrap the original error information? To do this, you need to:

- Clone both [terraform-provider-azurerm](https://github.com/terraform-providers/terraform-provider-azurerm) and [go-azure-helper](https://github.com/hashicorp/go-azure-helpers) locally
- Check out the v0.11.2 of go-azure-helpers and modify the code [here](https://github.com/hashicorp/go-azure-helpers/blob/v0.11.2/authentication/auth_method_azure_cli_token.go#L39) to include the `err` also in the `return`ed error.
- Modify the *go.mod* file of terraform-provider-azurerm to [replace](https://github.com/golang/go/wiki/Modules#gomod) the `go-azure-helpers` to using your local one
- Build the provider
- Use the built provider to reproduce your issue

**Comment by magodo** [comment] 2020-11-13 02:41
@erniebilling Since we haven't hear from you for a relative long time, I'm gonna close this issue for now. If you still have the issue, feel free to comment so I can reopen it.

**Closed by magodo** 2020-11-13 02:41 UTC
Labels: authentication, waiting-response
