### ISSUE TITLE
Can not parse "key_vault_id"  after updated  provider "azurerm" { version = "~> 2.0.0" features {} }

### ISSUE THREAD

**Issue by sunilmehta786** [terraform-providers/terraform-provider-azurerm#5882] opened 2020-02-25 09:32 UTC
Error: Can not parse "key_vault_id" as a resource id: The number of path segments is not divisible by 2 in ""

after update azurerm provider = 

provider "azurerm" {
    version = "~> 2.0.0"
   features {}
}

**Comment by tombuildsstuff** [comment] 2020-03-04 00:21
hi @sunilmehta786 

Thanks for opening this issue.

Unfortunately there's not enough information in the Terraform Configuration posted above for us to be able to debug this - but the cause is likely that the value for the `key_vault_id` field is incorrect. Since the Terraform Configuration posted above is incomplete I'm going to close this issue for the moment however if you can provide the full configuration we should be able to take another look; however I believe it should be possible to fix this by checking the value for the `key_vault_id` field.

Thanks!

**Closed by tombuildsstuff** 2020-03-04 00:21 UTC
Labels: question
