### ISSUE TITLE
Log Analytics pricing tier

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#2479] opened 2018-12-10 00:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v0.11.10
+ provider.azurerm v1.19.0

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "la-global-prod" {
  name                = "la-global-prod"
  location            = "${var.ARM_LOCATION}"
  resource_group_name = "${azurerm_resource_group.la-global.name}"
  sku                 = "PerGB2018"
  retention_in_days   =  90
}
```

### Expected Behavior

Creates a Log Analytics workspace with a paid SKU `standalone` showing in the UI.

### Actual Behavior

I'm following https://www.terraform.io/docs/providers/azurerm/r/log_analytics_workspace.html to create a Log Analytics workspace, however, the `sku` property seems "broken".

However, using 

```hcl
resource "azurerm_log_analytics_workspace" "la-global-prod" {
  name                = "la-global-prod"
  location            = "${var.ARM_LOCATION}"
  resource_group_name = "${azurerm_resource_group.la-global.name}"
  sku                 = "standalone"
  retention_in_days   =  90
}
```

fixes the deployment.
Has something changed on the API that doesn't allow `PerGB2018` anymore?

**Comment by tombuildsstuff** [comment] 2018-12-10 09:38
hey @davidobrien1985 

Thanks for opening this issue :)

Log Analytics Workspaces are an interesting resource insofar as the SKU's available are dependent on when you first provisioned a Log Analytics Workspace. If you've provisioned a Log Analytics Workspace prior to `2018-04-03` - then you can opt into the original SKU's (such as Standalone) - however if you've not you're only able to use the new SKU(s) (such as PerGB2018). IIRC it's possible to switch from the old to the new, but this involves switching any existing Log Analytics Workspaces over to the new SKU's/Pricing Tiers (which I believe Azure does for you as part of the upgrade process).

Out of interest did you provision a Log Analytics Workspace before `2018-04-03` (either via Terraform or some other means)? If so this'd explain why `PerGB2018` doesn't work as a SKU.

Whilst this is an odd behaviour in that (almost) every other API will allow you to provision any SKU - in this case unfortunately this varies based on the Subscription being used, as such there's no easy way of catching this ahead of time; instead we've opted to [document this behaviour](https://www.terraform.io/docs/providers/azurerm/r/log_analytics_workspace.html#sku). However since unfortunately this is by design within Azure, I don't believe there's anything we can do to work around this and as such I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2018-12-10 09:38 UTC
Labels: question, service/log-analytics

**Comment by davidobrien1985** [comment] 2018-12-10 21:47
Hi Tom,

Strange, this subscription is supposed to be a brand new one.

I'll dig a bit deeper and maybe spin up a new subscription to test again.

Thanks
David

Sent from my iPhone

On 10 Dec 2018, at 8:38 pm, Tom Harvey <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @davidobrien1985<https://github.com/davidobrien1985>

Thanks for opening this issue :)

Log Analytics Workspaces are an interesting resource insofar as the SKU's available are dependent on when you first provisioned a Log Analytics Workspace. If you've provisioned a Log Analytics Workspace prior to 2018-04-03 - then you can opt into the original SKU's (such as Standalone) - however if you've not you're only able to use the new SKU(s) (such as PerGB2018). IIRC it's possible to switch from the old to the new, but this involves switching any existing Log Analytics Workspaces over to the new SKU's/Pricing Tiers (which I believe Azure does for you as part of the upgrade process).

Out of interest did you provision a Log Analytics Workspace before 2018-04-03 (either via Terraform or some other means)? If so this'd explain why PerGB2018 doesn't work as a SKU.

Whilst this is an odd behaviour in that (almost) every other API will allow you to provision any SKU - in this case unfortunately this varies based on the Subscription being used, as such there's no easy way of catching this ahead of time; instead we've opted to document this behaviour<https://www.terraform.io/docs/providers/azurerm/r/log_analytics_workspace.html#sku>. However since unfortunately this is by design within Azure, I don't believe there's anything we can do to work around this and as such I'm going to close this issue for the moment.

Thanks!
