### ISSUE TITLE
Support for Workspaced Application Insights

### ISSUE THREAD

**Issue by prqgdbc** [terraform-providers/terraform-provider-azurerm#10727] opened 2021-02-24 20:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Application Insights now supports integration between application insights, and log analytics by defining a Log Analytics workspace during the creation of an App Insights resource. Providing a way to configure that in the azurerm_application_insights resource would be helpful.

### New or Affected Resource(s)

* azurerm_application_insights

### References

* https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource

**Comment by rickychew77** [comment] 2021-07-22 10:05
Is there any update on this? 

It would be a really good enhancement for our infra provision that fully runs with Terraform without click-ops to migrate App Insight into workspace based everytime.

**Comment by tombuildsstuff** [comment] 2021-07-22 10:22
Duplicate of #7667 - please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2021-07-22 10:22 UTC
Labels: duplicate, enhancement, service/application-insights
