### ISSUE TITLE
azurerm_kubernetes_cluster documentation about azure tags bug is incorrect

### ISSUE THREAD

**Issue by luckeyca** [terraform-providers/terraform-provider-azurerm#11228] opened 2021-04-07 02:25 UTC
In this documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster,
it says:
```
Note
At this time there's a bug in the AKS API where Tags for a Node Pool are not stored in the correct case - you may wish to use Terraform's ignore_changes functionality to ignore changes to the casing until this is fixed in the AKS API.
```
This statement and a reported bug to Microsoft, https://github.com/Azure/azure-rest-api-specs/issues/8982, assume azure tags are all case sensitive which are not the case. As per Microsoft documentation here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#:~:text=You%20apply%20tags%20to%20your,all%20the%20resources%20in%20production, the azure tag names are case INSENSITIVE, while the value is case sensitive. So the behavior is by design. If terraform wants to handle this in a case sensitive way, code change in terraform would be required, not on the MS side.

**Comment by tombuildsstuff** [comment] 2021-04-07 15:31
hi @luckeyca 

Thanks for opening this issue.

Unfortunately this is still a bug in the Azure API, since the casing on these tags are updated when changes to other tags are included (for example adding a new, or removing an existing tag) - so it's a diffing issue within the Azure API, and notably this regression only affects a subset of the Azure API's, others will make changes to the casing. In addition from Terraform's side, Terraform Core requires the fields returned from the API to match the fields sent from the configuration, casing included - as such unfortunately this isn't something we plan to fix on our side since Terraform, since this API regression is specific to a handful of API's.

As mentioned above, since this is ultimately a bug in the Azure API since the casing on these tags are case sensitive in some API's, and conditionally applied when adding a new/removing an existing tag to the others, whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment since this needs to be fixed within the Azure API.

Thanks!

**Closed by tombuildsstuff** 2021-04-07 15:31 UTC
Labels: question
