### ISSUE TITLE
Error waiting for certificate in KeyVault

### ISSUE THREAD

**Issue by kennethsparre1980** [terraform-providers/terraform-provider-azurerm#12344] opened 2021-06-24 09:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
resource "random_id" "randomid_gen" {
  keepers = {
    # Generate a new ID only when a new resource group is defined
  }

  byte_length = 8
}

# #########################################################
#  Key vault certificate
# #########################################################

resource "azurerm_key_vault_certificate" "key_vault_certificate" {
  name         = lower("${var.key_vault_certificate_prefix}-${var.application_name}-${var.subscription_name}-${var.environment}-${var.ver}-${random_id.randomid_gen.hex}")
  key_vault_id = var.key_vault_id

  #certificate {
  #  contents = filebase64("certificate-to-import.pfx")
  #  password = ""
  #}

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }


    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }


    lifetime_action {
      action {
        action_type = "AutoRenew"
      }


      trigger {
        days_before_expiry = 30
      }
    }


    secret_properties {
      content_type = "application/x-pkcs12"
    }


    x509_certificate_properties {
      # Server Authentication = 1.3.6.1.5.5.7.3.1
      # Client Authentication = 1.3.6.1.5.5.7.3.2
      extended_key_usage = ["1.3.6.1.5.5.7.3.1"]


      key_usage = [
        "cRLSign",
        "dataEncipherment",
        "digitalSignature",
        "keyAgreement",
        "keyCertSign",
        "keyEncipherment",
      ]

      subject_alternative_names {
        dns_names = ["mysite1.com"]
      }

      subject            = "CN=saltedm.com"
      validity_in_months = 24
    }
  }
}

```

### Actual Behaviour

Error: Error waiting for Certificate "kv-agw-cert-agw-subedm-s-89-beb18dc9c8a3df8a" in Vault "https://kv-core-subedm-s-1.vault.azure.net/" to become available: couldn't find resource (21 retries)

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2021-06-24 11:53
Duplicate of #12347

**Closed by tombuildsstuff** 2021-06-24 11:53 UTC
