### ISSUE TITLE
azurerm_network_interface_backend_address_pool_association fails on refreshing due to NIC not found

### ISSUE THREAD

**Issue by revchris** [terraform-providers/terraform-provider-azurerm#8277] opened 2020-08-27 19:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12
AzureRm 1.25.0

### Terraform Configuration Files

```hcl
#Associate Nic with Backend Pool
resource "azurerm_network_interface_backend_address_pool_association" "nic1" {
  network_interface_id    = module.virtual_machines.nic_id[0]
  ip_configuration_name   = "IPC-ENT-VLENTSPLFWD01-P-CUS01"
  backend_address_pool_id = azurerm_lb_backend_address_pool.splunkpool.id
}
resource "azurerm_network_interface_backend_address_pool_association" "nic2" {
  network_interface_id    = module.virtual_machines.nic_id[1]
  ip_configuration_name   = "IPC-ENT-VLENTSPLFWD02-P-CUS01"
  backend_address_pool_id = azurerm_lb_backend_address_pool.splunkpool.id
}
```

### Panic Output
```

module.virtual_machines.azurerm_virtual_machine.linuxVm[1]: Refreshing state... [id=/subscriptions/<SUB>/resourceGroups/RG-ENT-APP2383-P-CUS01/providers/Microsoft.Compute/virtualMachines/VLENTSPLFWD02P]
module.virtual_machines.azurerm_virtual_machine.linuxVm[0]: Refreshing state... [id=/subscriptions/<SUB>/resourceGroups/RG-ENT-APP2383-P-CUS01/providers/Microsoft.Compute/virtualMachines/VLENTSPLFWD01P]
azurerm_network_interface_backend_address_pool_association.nic1: Refreshing state... [id=/subscriptions/<SUB>/resourceGroups/RG-ENT-APP2383-P-CUS01/providers/Microsoft.Network/networkInterfaces/NIC-ENT-VLENTSPLFWD01-P-CUS01/ipConfigurations/IPC-ENT-VLENTSPLFWD01-P-CUS01|/subscriptions/<SUB>/resourceGroups/RG-ENT-APP2383-P-CUS01/providers/Microsoft.Network/loadBalancers/LB-ENT-APP2383-P-CUS01/backendAddressPools/SplunkBackEndAddressPool]
azurerm_network_interface_backend_address_pool_association.nic2: Refreshing state... 
Error: Network Interface "NIC-ENT-VLENTSPLFWD02-P-CUS01" (Resource Group "RG-ENT-APP2383-P-CUS01") was not found!

Error: Network Interface "NIC-ENT-VLENTSPLFWD01-P-CUS01" (Resource Group "RG-ENT-APP2383-P-CUS01") was not found!

##[error]PowerShell exited with code '1'
```

### Expected Behavior
refresh should run successfully and find out that all resources related to the VM and NIC's

### Actual Behavior

Error's out with output from above

### Steps to Reproduce

Run 
1. `terraform plan`

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/7041

* #0000

**Comment by tombuildsstuff** [comment] 2020-08-28 05:21
hi @revchris 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2491 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2491 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-28 05:21 UTC
