### ISSUE TITLE
FeatureRequest: New datasource azure_key_vault_certificate

### ISSUE THREAD

**Issue by naikajah** [terraform-providers/terraform-provider-azurerm#4554] opened 2019-10-07 22:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As per AzureFrontDoor configuration,
https://www.terraform.io/docs/providers/azurerm/r/front_door.html

it requires the following to be retrieved from the key vault:
* azure_key_vault_certificate_secret_name
* azure_key_vault_certificate_secret_version

New data source support **azurerm_key_vault_certificate**

### New or Affected Resource(s)

New datasource 

* azurerm_key_vault_certificate

### Potential Terraform Configuration

```hcl
data "azurerm_key_vault" "certificate_vault" {
  name                             = "example"
  resource_group_name = "exampleRG"
}

data "azurerm_key_vault_certificate" "certificate" {
  name             = "MyCertificate"
  key_vault_id  = data.azurerm_key_vault.certificate_vault.id
}

# Returns the latest version by default
output "version" {
  value = "${data.azurerm_key_vault_certificate.certificate.version}"
}

output "expiration_date" {
  value = "${data.azurerm_key_vault_certificate.certificate.expiration_date}"
}

```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2019-10-30 08:31
Duplicate of #2898 - thanks for pointing that out @brunhill

**Closed by tombuildsstuff** 2019-10-30 08:31 UTC
Labels: good first issue, new-data-source, service/keyvault
