### ISSUE TITLE
Can't deploy an Azure Service Fabric cluster across Availability Zones

### ISSUE THREAD

**Issue by ChunliangGu** [terraform-providers/terraform-provider-azurerm#8990] opened 2020-10-22 14:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.10
provider.azurerm v2.32.0
```

### Affected Resource(s)

* `azurerm_windows_virtual_machine_scale_set`  `azurerm_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl

resource "azurerm_service_fabric_cluster" "example" {
  name                = "${var.prefix}servicefabric"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  reliability_level   = "Silver"
  upgrade_mode        = "Automatic"
  vm_image            = "Windows"
  management_endpoint = "https://${var.prefix}servicefabric.${var.location}.cloudapp.azure.com:19080"

  node_type {
    name                 = "Windows"
    instance_count       = 5
    is_primary           = true
    client_endpoint_port = 19000
    http_endpoint_port   = 19080
  }


  reverse_proxy_certificate {
    thumbprint      = azurerm_key_vault_certificate.example.thumbprint
    x509_store_name = "My"
  }

  certificate {
    thumbprint      = azurerm_key_vault_certificate.example.thumbprint
    x509_store_name = "My"
  }

  client_certificate_thumbprint {
    thumbprint = azurerm_key_vault_certificate.example.thumbprint
    is_admin   = true
  }
}

resource "azurerm_windows_virtual_machine_scale_set" "example" {
  name                 = "${var.prefix}examplesf"
  computer_name_prefix = var.prefix
  resource_group_name  = azurerm_resource_group.example.name
  location             = azurerm_resource_group.example.location
  sku                  = "Standard_D2_v3"
  instances            = azurerm_service_fabric_cluster.example.node_type[0].instance_count
  admin_password       = "P@55w0rd1234!"
  admin_username       = "adminuser"
  overprovision        = false
  upgrade_mode         = "Automatic"

  zones                = ["1","2","3"]

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter-with-Containers"
    version   = "latest"
  }

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }

  network_interface {
    name    = "example"
    primary = true

    ip_configuration {
      name      = "internal"
      primary   = true
      subnet_id = azurerm_subnet.example.id
      load_balancer_backend_address_pool_ids = [
        azurerm_lb_backend_address_pool.example.id
      ]
      load_balancer_inbound_nat_rules_ids = [
        azurerm_lb_nat_pool.example.id
      ]
    }
  }

  secret {
    certificate {
      store = "My"
      url   = azurerm_key_vault_certificate.example.secret_id
    }
    key_vault_id = azurerm_key_vault.example.id
  }

  extension {
    name                       = "${var.prefix}ServiceFabricNode"
    publisher                  = "Microsoft.Azure.ServiceFabric"
    type                       = "ServiceFabricNode"
    type_handler_version       = "1.1"
    auto_upgrade_minor_version = false

    settings = jsonencode({
      "clusterEndpoint"    = azurerm_service_fabric_cluster.example.cluster_endpoint
      "nodeTypeRef"        = azurerm_service_fabric_cluster.example.node_type[0].name
      "durabilityLevel"    = "Silver"
      "nicPrefixOverride"  = azurerm_subnet.example.address_prefixes[0]
      "enableParallelJobs" = true
      "certificate" = {
        "commonNames" = [
          "${var.prefix}servicefabric.${var.location}.cloudapp.azure.com",
        ]
        "x509StoreName" = "My"
      }
    })

    protected_settings = jsonencode({
      "StorageAccountKey1" = azurerm_storage_account.example.primary_access_key
      "StorageAccountKey2" = azurerm_storage_account.example.secondary_access_key
    })
  }

}

```

### Expected Behavior

Service Fabric using Windows VMSS with zones

### Actual Behavior

Error: Error creating Windows Virtual Machine Scale Set "example" (Resource Group "example"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="MultipleAvailabilityZones must be set for the nodeType:example for enabling multiple zones in 1 VMSS". In resource "azurerm_windows_virtual_machine_scale_set" "example": resource "azurerm_windows_virtual_machine_scale_set" "example" 

### Steps to Reproduce

1. Just `terraform apply`
2. If I remove `zones                = ["1","2","3"]`, `terraform apply` will be successful and create Service Fabric using Windows VMSS.
3. If I remove `service fabric extension in azurerm_virtual_machine_scale_set`, `terraform apply` will be successful, create  Windows VMSS with zones and service fabric resource. Of course, service fabirc doesn't connect to Windows VMSS.
4. If I use `azurerm_virtual_machine_scale_set` instead of `azurerm_windows_virtual_machine_scale_set`, the same error will reproduce

### References

https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine_scale_set.html
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html
https://www.terraform.io/docs/providers/azurerm/r/service_fabric_cluster.html
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cross-availability-zones

* #0000

**Comment by hbuckle** [comment] 2020-11-09 17:07
Service Fabric doesn't support a single scale set spread over multiple zones - you need to create one scale set in each zone

**Comment by tombuildsstuff** [comment] 2021-02-04 11:39
Closing this out since based on @hbuckle's comment above this is by design

**Closed by tombuildsstuff** 2021-02-04 11:39 UTC

**Comment by hbuckle** [comment] 2021-02-04 12:09
@tombuildsstuff  As it so happens it is supported in [preview](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cross-availability-zones#preview-enable-multiple-availability-zones-in-single-virtual-machine-scale-set) now, the provider will need an update to support it though
