### ISSUE TITLE
Changing azurerm_dns_zone type resulted in BadRequest

### ISSUE THREAD

**Issue by kevinjqiu** [terraform-providers/terraform-provider-azurerm#3124] opened 2019-03-26 17:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
terraform -v
Terraform v0.11.8
+ provider.azurerm v1.22.0
```

### Affected Resource(s)

* `azurerm_dns_zone`

### Terraform Configuration Files

```hcl
resource "azurerm_dns_zone" "zone" {
  name                             = "private.example.com"
  resource_group_name = "${data.azurerm_resource_group.rg.name}"

  zone_type = "Private"
}
```

I updated `zone_type` from `Private` to `Public`.

### Debug Output

```
  ~ azurerm_dns_zone.private
      zone_type: "Private" => "Public"


Proceed [Y/n]? y
azurerm_dns_zone.private: Modifying... (ID: /subscriptions/3a95e282-1525-4207-b1ad-.../private.example.com)
  zone_type: "Private" => "Public"

Error: Error applying plan:

1 error(s) occurred:

* azurerm_dns_zone.private: 1 error(s) occurred:

* azurerm_dns_zone.private: Error creating/updating DNS Zone "private.example.com" (Resource Group "cloud-eu-network"): dns.ZonesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="A different Type of Zone with same name under same resource group and subscription already exists."
```

### Expected Behavior

No Bad Request error.  This is an in-place update, which shouldn't result in a conflict by the same resource name.

### Actual Behavior

`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running in Azure West Europe region

### References

* #0000

**Comment by neil-yechenwei** [comment] 2020-06-05 08:26
Thanks for opening this issue. Service API has been upgraded from `2018-03-01-preview` to `2018-05-01` so that the schema has been refactored. So I assume this issue has gone.

**Comment by neil-yechenwei** [comment] 2020-06-05 08:37
@kevinjqiu , Thanks for opening this issue. After checked, seems `zone_type` has been deprecated and use the [`azurerm_private_dns_zone`](https://www.terraform.io/docs/providers/azurerm/r/private_dns_zone.html) resource instead. So I suppose your issue has gone. Could you help to double check whether the problem still exists? Thanks.

**Comment by ArcturusZhang** [comment] 2020-06-05 09:34
Hi @kevinjqiu 

Could you please have a try using the latest version of the provider regarding this issue? In the meantime, I would close this issue hope you would not mind since we currently cannot reproduce your issue (the corresponding attribute has been deprecated).

If this issue persists, please feel free to open a new issue regarding the latest version of the azure provider.

Thank you!

**Closed by ArcturusZhang** 2020-06-05 09:34 UTC
Labels: bug, service/dns
