### ISSUE TITLE
Terraform init crashes when using modules that use different provider version (1.44.0 and 2.9.0)

### ISSUE THREAD

**Issue by elbatane** [terraform-providers/terraform-provider-azurerm#6921] opened 2020-05-14 07:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 Terraform version used: Terraform v0.12.24

### Affected Resource(s)

* `azurerm provider version 1.44.0
* `azurerm provider version 2.9.0

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
  backend "local" {
    path = "local.tfstate"
  }
}

provider "azurerm" {

  version = "1.44.0"
  alias   = "version1"
}

provider "azurerm" {

  version = "2.9.0"
  features {}
  alias = "version2"
}

module "workload-nocritical" {
  providers = {
    azurerm = azurerm.version1
  }
  source          = "./workload-nocritical"
 ....
}

module "main" {
  providers = {
    azurerm = azurerm.version2
  }
  source                = "./private-endpoint"

...

}
```

### Debug Output
No provider "azurerm" plugins meet the constraint "1.44.0,2.9.0,=1.44.0,=1.44.0,=2.9.0".

The version constraint is derived from the "version" argument within the
provider "azurerm" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.

### Expected Behavior

It should use one provider version for one module (1.44.0) and another provider version for the private endpoint module (2.9.0) as it does not work with the 1.44.0 provider. 

### Actual Behavior

It seems that it is not possible to use different versions of the provider 1.* and 2.*.

### Steps to Reproduce

1. `terraform init`

* #0000

**Comment by tombuildsstuff** [comment] 2020-05-14 09:22
hi @elbatane 

Thanks for opening this issue.

> It seems that it is not possible to use different versions of the provider 1.* and 2.*.

Whilst Terraform Core supports instantiating multiple instances of a provider - all instances of that Provider need to be the same version by design - as such it's only possible to use a single version of the AzureRM Provider.

Later versions of the 1.x release of the Azure Provider (such as 1.44) mark fields and resources which will be removed in 2.0 as deprecated - as such it should be possible to work through these and then update the module constraint within that module to use `>= 1.44 < 3.0` as the constraint.

Since this behaviour is by design in Terraform Core I'm going to close this issue for the moment - but you should be able to solve this by making the modules support both 1.x and 2.x and then switching to use a single version of the Provider in the root.

Thanks!

**Closed by tombuildsstuff** 2020-05-14 09:22 UTC
Labels: question, upstream-terraform
