### ISSUE TITLE
issue(azurerm_mysql_server): PointInTimeRestore original server's firewall rules

### ISSUE THREAD

**Issue by man0s** [terraform-providers/terraform-provider-azurerm#10672] opened 2021-02-20 16:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions
```
Terraform: v0.13.3
AzureRM Provider: v2.48.0
```

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_server" "database" {
  name                = <database name>
  location            = <datatabse location>
  resource_group_name = <resource group name>

  administrator_login          = <username>
  administrator_login_password = <password>

  sku_name   = "GP_Gen5_8"
  storage_mb = 5120
  version    = "5.7"

  public_network_access_enabled = true
  ssl_enforcement_enabled       = false
  create_mode                   = "PointInTimeRestore"
  creation_source_server_id     = <azure resource database id>
  restore_point_in_time         = <timestamp>
}
```

### Expected Behaviour

The database server to be created with the restored Firewall rules from the original server.

### Actual Behaviour

The firewall rule of the new server(restored) has been created but it's not working as expected.

For instance, the original server has a firewall rule to allow access to Azure services.
I get the following error when I try to access the new(restored) database server.
```java.sql.SQLException: Client from Azure Virtual Networks is not allowed to access the server. Please make sure your Virtual Network is correctly configured.```

When I reapply it manually via the Azure portal, everything works as expected.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2021-02-22 08:13
hi @man0s 

Firewall Rules are managed via a [separate resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_firewall_rule) - so would need to be configured separately for this new MySql Server - simply restoring the backup from another VM won't copy these over by design within Azure, since the firewall rules may be different (consider for example Staging and Production which may have their own policies).

Since this is by design I'm going to close this issue for the moment - but you should be able to apply the same (or different) Firewall Rules by using [the `azurerm_mysql_firewall_rule` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_firewall_rule) against this new MySql Server.

Thanks!

**Closed by tombuildsstuff** 2021-02-22 08:13 UTC
Labels: question
