### ISSUE TITLE
Azure CLI: Error waiting for the Azure CLI: exit status 2

### ISSUE THREAD

**Issue by AntonioDeJesus** [terraform-providers/terraform-provider-azurerm#8779] opened 2020-10-07 13:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When attempting to use AzureCLI Auth recieving error on `terraform plan`
```bash
Error: Error refreshing state: 1 error occurred:
        * provider.azurerm: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 2
```

* I am able to successfully retrieve a token with `az account get-access-token`
* I do not see this issue with provider v 1.37 but do encounter the issue with 1.38+

Steps to reproduce:
1. az login
2. az account set -s "xxxx-xxx-xx-xx-xxxxxxx"
2. terraform init
3. terraform plan

### Envrionment
```bash
$ terraform --version
Terraform v0.11.14
+ provider.azurerm v1.38.0

$ az --version
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jan 12 2018, 17:31:35)
[GCC 4.8.4]
```

### New or Affected Resource(s)

* azurerm_1.38+

### Potential Terraform Configuration

```hcl
provider "azurerm"{
  version = "=1.38.0"
  subscription_id = "xxxx-xxx-xx-xx-xxxxxxx"
} 
```

**Comment by tombuildsstuff** [comment] 2020-10-08 08:00
hi @AntonioDeJesus 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6069 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6069 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-08 08:00 UTC
