### ISSUE TITLE
TestAccAzureRMServiceBusQueue/Topic deletion failed.

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#1836] opened 2018-08-28 03:09 UTC
**Relate TestCases:**
TestAccAzureRMServiceBusQueue_defaultEnablePartitioningPremium
TestAccAzureRMServiceBusTopic_enablePartitioningPremium
TestAccAzureRMServiceBusTopic_importBasic

**Error Message:**
* azurerm_resource_group.test: Error deleting Resource Group "acctestRG-1713274917983578785": pollingTrackerBase#updatePollingState: the response from the async operation has an invalid status code: StatusCode=0 testing.go:573: Error destroying resource! WARNING: Dangling resources may exist. The full state and error is shown below. Error: Error applying: 1 error(s) occurred: * azurerm_resource_group.test (destroy): 1 error(s) occurred: * azurerm_resource_group.test: Error deleting Resource Group "acctestRG-1713274917983578785": pollingTrackerBase#updatePollingState: the response from the async operation has an invalid status code: StatusCode=0 State: azurerm_resource_group.test: ID = /subscriptions/85b3dbca-5974-4067-9669-67a141095a76/resourceGroups/acctestRG-1713274917983578785 provider = provider.azurerm location = westeurope name = acctestRG-1713274917983578785 tags.% = 0

**Comment by tombuildsstuff** [comment] 2018-08-28 14:19
Duplicate of #1833

**Closed by tombuildsstuff** 2018-08-28 14:19 UTC
