### ISSUE TITLE
JSON parse error in RM template causes resource update in azurerm_template_deployment

### ISSUE THREAD

**Issue by iszekely** [terraform-providers/terraform-provider-azurerm#2029] opened 2018-10-05 12:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v0.11.8
* provider.azurerm v1.16.0
* provider.null v1.0.0

### Affected Resource(s)

* azurerm_template_deployment

### Terraform Configuration Files

https://www.dropbox.com/s/5vyj5pp0dw2hqhy/hditest.zip?dl=0

### Expected Behavior

After applying a configuration, a subsequent plan command should not show any update in the plan.

### Actual Behavior

I applied the configuration then ran a plan command. The plan shows a JSON parse error and that the `azurerm_template_deployment` resource is outdated.

```
  ~ azurerm_template_deployment.hdinsight_template
      parameters_body:            "..." => "Error parsing JSON: invalid character '$' looking for beginning of value"


Plan: 0 to add, 1 to change, 0 to destroy.
```

It is caused by a '$' sign in the Terraform state which comes from the Azure RM template.
```json
"$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
```

### Steps to Reproduce

1. Fill in the missing variables in `env.tfvars`
1. `terraform apply` It will take some time since it creates a lot of resources, including an HDInsight cluster.
1. `terraform plan`

### References

* #1025

**Comment by aambert** [comment] 2019-02-19 15:47
info ?

**Comment by sean-nixon** [comment] 2019-10-28 16:09
I'm guessing this one is caused by this issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/2029

**Comment by tombuildsstuff** [comment] 2020-06-04 06:59
Duplicate of #1025

**Closed by tombuildsstuff** 2020-06-04 06:59 UTC
Labels: bug, service/resources
