### ISSUE TITLE
oms_agent in azurerm_kubernetes_cluster does not work

### ISSUE THREAD

**Issue by toorog** [terraform-providers/terraform-provider-azurerm#1963] opened 2018-09-21 07:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.azurerm v1.14.0

### Affected Resource(s)

* azurerm_kubernetes_cluster 

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "loganalyticsws" {
  name                = "${var.name}-law"
  resource_group_name = "${azurerm_resource_group.mainrg.name}"
  location            = "${azurerm_resource_group.mainrg.location}"
  sku                 = "PerNode"
  retention_in_days   = 90
  tags                = "${local.tags}"
}
resource "azurerm_kubernetes_cluster" "cluster" {
  name = "${var.name}-k8s"
  location            = "${azurerm_resource_group.mainrg.location}"
  resource_group_name = "${azurerm_resource_group.mainrg.name}"
  dns_prefix          = "${var.name}"
  kubernetes_version  = "1.11.2"
  tags                = "${local.tags}"

  agent_pool_profile {
    name            = "default"
    count           = 3
    vm_size         = "Standard_DS4_v2_Promo"
    os_type         ="Linux"
    vnet_subnet_id  = "${azurerm_subnet.k8ssubnet.id}"
  }

  service_principal {
    client_id     = "${var.sp_appid}"
    client_secret = "${var.sp_secret}"
  }
  addon_profile {
    oms_agent {
      enabled                     = true
      log_analytics_workspace_id  = "${azurerm_log_analytics_workspace.loganalyticsws.id}"
    }
  }
  network_profile {
    network_plugin = "azure"
    service_cidr = "10.1.0.0/16"
    docker_bridge_cidr = "172.17.0.1/16"
    dns_service_ip = "10.1.0.0"
  }

}

```

### Expected Behavior

- OMS Pods inside cluster should be able to connect to workspace
- In azure portal: Cluster -> properties there should be a valid value for `Workspace resource id`

### Actual Behavior
- OMS Pods are provisioned but cannot connect to WS because property is missing
-In azure portal the property `Workspace resource id` is empty

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lfshr** [comment] 2018-09-25 17:46
Hi @toorog 
There's a little bit of ambiguity in the term "workspace id".
Can you try and change the line in your terraform to the following:
```hcl
addon_profile {
    oms_agent {
      enabled                     = true
      log_analytics_workspace_id  = "${azurerm_log_analytics_workspace.loganalyticsws.workspace_id}"
    }
  }
```

Let me know how you get on.

**Comment by lfshr** [comment] 2018-09-25 17:51
@toorog never mind, that didn't work, the SDK throws an error. What that did prove though is that Terraform is correctly passing this information to the Azure SDK and the Azure SDK is running validation on it, and is happy. Let me continue to do some testing.

**Comment by lfshr** [comment] 2018-09-25 18:37
@marstr can you shine any light on this? The TF provider is passing valid information to the SDK (Validated this). The SDK seems fine with it but does not actually assign the cluster to the OMS Workspace. :confused:

**Comment by marstr** [comment] 2018-09-25 18:51
Sounds like something we'll need to bring up with the AKS folks, and they rock.

Mind filing an issue over in [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/issues) and mentioning me? I'll be able to reach out internally to get this solved.

**Comment by tombuildsstuff** [comment] 2018-09-26 23:17
👋🏻 from what I can see this appears to be a breaking change within the AKS API? There's more details in #1983 which I'm going to close this in favour of

**Closed by tombuildsstuff** 2018-09-26 23:17 UTC
Labels: question, service/kubernetes-cluster

**Comment by lfshr** [comment] 2018-09-27 14:54
@tombuildsstuff #1983 is more about code styling, and not a bug itself. Azure API seems happy to accept the lower-case "omsAgent".

@marstr thanks for replying. I've not yet had a chance to open this issue. I want to play around with the SDK a little more (without Terraform) so as to understand the problem fully before opening the issue.
