### ISSUE TITLE
Support for Log Analytics and Eventhub azure sql audit policy configuration

### ISSUE THREAD

**Issue by lotaezhao** [terraform-providers/terraform-provider-azurerm#7393] opened 2020-06-18 12:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is currently no support to configure azure sql Log Analytics or Eventhub based audit policy settings in Terraform. These features are still in preview but Log Analytics especially is the better way of implementing auditing now so it would be good to have first class support for this at both the Server and Database level of auditing. This is related to previous issue #5929 that implemented storage account auditing support but not Log Analytics or Eventhub.

### New or Affected Resource(s)

azurerm_sql_database
azurerm_sql_server

### Potential Terraform Configuration

```
resource "azurerm_sql_database" "example" {
  name                = "mysqldatabase"
  resource_group_name = azurerm_resource_group.example.name
  location            = "West US"
  server_name         = azurerm_sql_server.example.name

  extended_auditing_policy {
    log_analytics_workspace_id     = example_log_analytics_workspace_id
    eventhub_authorization_rule_id = example_authorization_rule_id
  }

  tags = {
    environment = "production"
  }
}
```

### References

It is possible to enable eventhub or log analytics auditing policy via powershell:
https://docs.microsoft.com/en-us/powershell/module/az.sql/set-azsqldatabaseauditing?view=azps-2.8.0

* #0000

**Comment by splitified** [comment] 2020-06-19 18:43
This may be a duplicate of the #6849

**Comment by tombuildsstuff** [comment] 2020-06-23 10:17
hi @lotaezhao 

Thanks for opening this issue :)

Taking a look through as @splitified has mentioned this appears to be a duplicate of #6849 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6849 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-23 10:17 UTC
Labels: duplicate, new-resource, service/mssql

**Comment by lotaezhao** [comment] 2020-06-24 13:15
> hi @lotaezhao
> 
> Thanks for opening this issue :)
> 
> Taking a look through as @splitified has mentioned this appears to be a duplicate of #6849 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6849 for updates?
> 
> Thanks!

Hi @tombuildsstuff ,

Sure no problem combining this into #6849. However this one was for adding both Log Analytics and Eventhub auditing support,  #6849 only mentions Log Analytics auditing support. Can you ensure #6849 is updated to include Evenhub auditing too?
