### ISSUE TITLE
azurerm_windows_virtual_machine_scale_set fails when using a specialized image

### ISSUE THREAD

**Issue by clippermadness** [terraform-providers/terraform-provider-azurerm#9637] opened 2020-12-03 01:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0

### Affected Resource(s)

* `azurerm_windows_virtual_machine_scale_set`
* `azurerm_shared_image_version`

### Terraform Configuration Files

```hcl
data "azurerm_shared_image" "pipeline_autoscale_image_ocr_dev2" {
  name                = "autoscaling-image-ocr-dev"
  gallery_name        = data.azurerm_shared_image_gallery.autoscaling_images.name
  resource_group_name = data.azurerm_shared_image_gallery.autoscaling_images.resource_group_name
}

data "azurerm_shared_image_version" "pipeline_autoscale_image_ocr_dev2_v1" {
  name                = "1.0.0"
  image_name          = data.azurerm_shared_image.pipeline_autoscale_image_ocr_dev2.name
  gallery_name        = data.azurerm_shared_image_gallery.autoscaling_images.name
  resource_group_name = data.azurerm_shared_image_gallery.autoscaling_images.resource_group_name
}

resource "azurerm_windows_virtual_machine_scale_set" "pipeline_dev2_text_win_autoscale_schedule" {

  name                = "pipetextwindev2schedule"
  location            = data.azurerm_resource_group.dev2.location
  resource_group_name = data.azurerm_resource_group.dev2.name

  sku = "Standard_F4s_v2"
  upgrade_mode = "Manual"
  instances = 0
  overprovision = false
  source_image_id = data.azurerm_shared_image_version.pipeline_autoscale_image_ocr_dev2_v1.id

  os_disk {
    caching = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  # since the underlying image we're using is a specialized image, I would expect these to be ignored
  computer_name_prefix = "textsched"
  admin_username = "somethingadminlike"
  admin_password = "completelyignoredandunused"

  network_interface {
    name    = "pipetextdev2-networkprofile"
    primary = true
    network_security_group_id = azurerm_network_security_group.pipeline_pipelinetier_dev2.id
    ip_configuration {
      name         = "pipetextdev2-ipconfig"
      subnet_id    = "${data.azurerm_virtual_network.dev2_vnet.id}/subnets/${data.azurerm_subnet.dev2_subnet_default.name}"
      primary      = true
      public_ip_address {
        name                    = "pipetextdev2-publicipconfig"
        domain_name_label       = "textwinsched"
        idle_timeout_in_minutes = 15
      }
    }
  }

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [ instances, automatic_os_upgrade_policy ]
  }
}
```

### Expected Behaviour

I expected terraform to create the VMSS

### Actual Behaviour

azurerm_windows_virtual_machine_scale_set.pipeline_dev2_text_win_autoscale_schedule: Creating...

Error: Error creating Windows Virtual Machine Scale Set "pipetextwindev2schedule" (Resource Group "dev2"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Parameter 'osProfile' is not allowed." Target="osProfile"

  on autoscaling_vidprocessor_text.tf line 105, in resource "azurerm_windows_virtual_machine_scale_set" "pipeline_dev2_text_win_autoscale_schedule":
 105: resource "azurerm_windows_virtual_machine_scale_set" "pipeline_dev2_text_win_autoscale_schedule" {

**Comment by AliAllomani** [comment] 2020-12-12 19:33
looks same as #7772

**Comment by tombuildsstuff** [comment] 2021-03-16 07:31
Duplicate of #7772, thanks for the cross-link @AliAllomani

**Closed by tombuildsstuff** 2021-03-16 07:31 UTC
Labels: bug, duplicate, service/virtual-machine
