### ISSUE TITLE
AKS : log_analytics_workspace_id keeps being re-applied each time

### ISSUE THREAD

**Issue by seboss666** [terraform-providers/terraform-provider-azurerm#8391] opened 2020-09-08 15:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform : 0.12.29
azurerm provider : 2.22.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "aks" {
  name                = local.la_name
  location            = azurerm_resource_group.platform.location
  resource_group_name = azurerm_resource_group.platform.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_kubernetes_cluster" "platform" {
(...)
 addon_profile {
    kube_dashboard {
      enabled = true
    }
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.aks.id
    }
  }
```

### Debug Output

No error to debug.

### Panic Output

Don't Panic

### Expected Behavior

When I'm applying the configuration multiple times, log_analytics id should be set once.

### Actual Behavior

Each Time I reapply the configuration, it wand to set the log_analytics_id : 
```
      ~ addon_profile {

            kube_dashboard {
                enabled = true
            }

          ~ oms_agent {
                enabled                    = true
              + log_analytics_workspace_id = "/subscriptions/d3b07abf-6c2d-4d35-a7f8-ee63f9eb9583/resourcegroups/rg-valrhona-ppr-pf/providers/microsoft.operationalinsights/workspaces/la-valrhona-ppr-pf"
                oms_agent_identity         = []
            }
        }
```
The log_analytics_workspace_id is not kept. Apply is done without error from azure side.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by mybayern1974** [comment] 2020-09-09 11:15
hi  @seboss666 

Thanks for opening this issue!

Taking a look through this appears to be a duplicate of #8344 , rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8344  for updates? Or feel free to suggest reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-09-09 11:15 UTC
Labels: duplicate, service/kubernetes-cluster
