### ISSUE TITLE
Error on Terraform refresh with Key Vault

### ISSUE THREAD

**Issue by antanof** [terraform-providers/terraform-provider-azurerm#9874] opened 2020-12-15 15:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0
+ provider registry.terraform.io/hashicorp/http v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0

### Affected Resource(s)

resource azurerm_key_vault
* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# in module.keyvault
#-----------------------
# Vault
#-----------------------
resource "azurerm_key_vault" "principal" {
  name                            = var.vault_name
  location                        = var.location
  resource_group_name             = var.rgname
  tenant_id                       = data.azurerm_client_config.current.tenant_id
  enabled_for_deployment          = var.enabled_for_deployment
  enabled_for_disk_encryption     = var.enabled_for_disk_encryption
  enabled_for_template_deployment = var.enabled_for_template_deployment
  soft_delete_enabled             = var.soft_delete_enabled
  soft_delete_retention_days      = var.soft_delete_retention_days
  purge_protection_enabled        = var.purge_protection_enabled
  enable_rbac_authorization       = var.enable_rbac_authorization
  sku_name                        = var.sku_name
  network_acls {
    default_action = var.default_action
    bypass         = var.bypass
    ip_rules       = [ var.zscaler_ip, "${data.http.myip.body}/32" ]
  #  virtual_network_subnet_ids = var.vnet_id
  }
  access_policy {
    tenant_id               = data.azurerm_client_config.current.tenant_id
    object_id               = data.azurerm_client_config.current.object_id

    key_permissions         = var.kv_key_permissions_full
    secret_permissions      = var.kv_secret_permissions_full
    certificate_permissions = var.kv_certificate_permissions_full
    storage_permissions     = var.kv_storage_permissions_full
  }
 contact {
   email = var.contact_email
 }
}

# with variables.tf
(...)
variable "kv_key_permissions_full" {
  type        = list(string)
  description = "List of full key permissions, must be one or more from the following: backup, create, decrypt, delete, encrypt, get, import, list, purge, recover, restore, sign, unwrapKey, update, verify and wrapKey."
  default     = [ "backup", "create", "decrypt", "delete", "encrypt", "get", "import", "list", "purge", "recover", "restore", "sign", "unwrapKey","update", "verify", "wrapKey" ]
}

variable "kv_secret_permissions_full" {
  type        = list(string)
  description = "List of full secret permissions, must be one or more from the following: backup, delete, get, list, purge, recover, restore and set"
  default     = [ "backup", "delete", "get", "list", "purge", "recover", "restore", "set" ]
}

variable "kv_certificate_permissions_full" {
  type        = list(string)
  description = "List of full certificate permissions, must be one or more from the following: backup, create, delete, deleteissuers, get, getissuers, import, list, listissuers, managecontacts, manageissuers, purge, recover, restore, setissuers and update"
  default     = [ "backup", "create", "delete", "deleteissuers", "get", "getissuers", "import", "list", "listissuers", "managecontacts", "manageissuers", "purge", "recover", "restore", "setissuers", "update" ]
}

variable "kv_storage_permissions_full" {
  type        = list(string)
  description = "List of full storage permissions, must be one or more from the following: backup, delete, deletesas, get, getsas, list, listsas, purge, recover, regeneratekey, restore, set, setsas and update"
  default     = [ "backup", "delete", "deletesas", "get", "getsas", "list", "listsas", "purge", "recover", "regeneratekey", "restore", "set", "setsas", "update" ]
}

```

### Debug Output

module.vault.azurerm_key_vault.principal: Refreshing state... [id=/subscriptions/48076a74-19fc-5674-b761-375d56ff3c90/resourceGroups/rg-hub-dccsix-prod/providers/Microsoft.KeyVault/vaults/kvdccsix1eb969cf]

Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context canceled
### Expected Behaviour
A normal :
terraform refresh
terraform plan

### Actual Behaviour
When I use terraform with my principal service (I'm owner in the subscription) which has all the rights, my code runs well and my infra is built. But when I make a refresh or a plan, terraform gets a drink at the KeyVault resource and tells me the error :
Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context canceled

### Steps to Reproduce

After a plan succeeded
1. `terraform refresh`
2. `terraform plan`

### Important Factoids

Public 

### References

* #0000
Best regards

**Comment by tinablonjazz** [comment] 2021-01-26 15:41
facing the very same issue... any new findings, @antanof ?

**Comment by glga-byte** [comment] 2021-01-26 16:29
I have the same issue when using KeyVault in combination with azurerm_private_endpoint 
1. `terraform apply` - works
2. `terraform refresh` - not
3. `terraform plan` - not
4. `terraform apply` - not
Refresh state got stuck until i remove Private Endpoint.

**Comment by antanof** [comment] 2021-01-26 16:35
Nope, I think once the vault is created terraform needs to connect from the private network.

**Comment by spect9588** [comment] 2021-01-26 17:25
I experienced the same as @glga-byte . The problem for me only appears when KeyVault is configured with a private endpoint.

**Comment by tombuildsstuff** [comment] 2021-02-04 10:50
hi @antanof @spect9588 @tinablonjazz @glga-byte 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9738 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9738 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-04 10:50 UTC

**Comment by mlomat** [comment] 2021-02-04 14:11
Hi @antanof  
I am using Linux subsystem for windows -ubuntu and I had exactly this same issue! 
After debugging, I figure out that something is wrong with network traffic. I setup proxy on my Windows server - fiddler and everything is working normally in this setup. 
After that I checked DNS setup and it looks like it's somehow connected with DNS protocol, which is switching from UDP to TCP due to large query results (https://www.infoblox.com/dns-security-resource-center/dns-security-faq/is-dns-tcp-or-udp-port-53/) 

After I changed my DNS server in /etc/resolve.conf from Windows Host to my router - everything is also working fine. 

@tombuildsstuff Please check it if you can, because I think that will be nice to catch this exception somewhere and throw better message :) If you need help, you can ping me and I will help to reproduce this issue.  

Best
Mateusz

**Comment by matt-FFFFFF** [comment] 2021-02-07 23:31
@mlomat Thanks! This was my issue too

**Comment by glga-byte** [comment] 2021-02-08 14:13
@mlomat thank you so much. That helped!!

How to change DNS in WSL2:
https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6
