### ISSUE TITLE
The resource azurerm_eventhub_namespace does not respect 'kafka_enabled = false'

### ISSUE THREAD

**Issue by PeterUherek** [terraform-providers/terraform-provider-azurerm#4652] opened 2019-10-18 15:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform v0.12.8
* provider.azurerm v1.35.0

### Affected Resource(s)
* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```
resource "azurerm_resource_group" "test" {
  name     = "resourceGroup1"
  location = "West US"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "acceptanceTestEventHubNamespace"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "Standard"
  capacity            = 1
  kafka_enabled       = false

  tags = {
    environment = "Production"
  }
}
```
### Expected Behavior
This configuration should result in: 
```
"kafkaEnabled": false
```
### Actual Behavior
Not in:
```
"kafkaEnabled": true
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2019-10-20 19:21
hi @PeterUherek 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4598 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4598 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-10-20 19:21 UTC
Labels: bug, service/event-hubs
