### ISSUE TITLE
Advanced threat protection break plan execution

### ISSUE THREAD

**Issue by eliecharra** [terraform-providers/terraform-provider-azurerm#3938] opened 2019-07-26 12:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
➜ ./terraform -v
Terraform v0.11.10
+ provider.azurerm v1.32.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "functions_storage" {
  name                     = "xxxxx${terraform.workspace}"
  resource_group_name      = "${azurerm_resource_group.rg.name}"
  location                 = "francecentral"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}
```

### Debug Output

```
* azurerm_storage_account.functions_storage: azurerm_storage_account.functions_storage: Error reading the advanced threat protection settings of AzureRM Storage Account "xxxxxqa": security.AdvancedThreatProtectionClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'francecentral' and API version '2017-08-01-preview' for type 'advancedThreatProtectionSettings'. The supported api-versions are '2017-08-01-preview'. The supported locations are 'australiacentral, australiacentral2, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus2, eastus, japaneast, japanwest, koreacentral, koreasouth, northcentralus, northeurope, southcentralus, southindia, southeastasia, uksouth, ukwest, westcentralus, westeurope, westindia, westus2, westus'."
* azurerm_storage_account.reciepe_image_storage: 1 error(s) occurred:
```

### Expected Behavior

`terraform apply` terminate successfully

### Actual Behavior

`terraform apply` fails

It seems that https://github.com/terraform-providers/terraform-provider-azurerm/pull/3782 introduce regressions as advanced threat protection is not available in all regions.

### Steps to Reproduce

1. `terraform apply`

**Comment by katbyte** [comment] 2019-07-26 18:27
hi @eliecharra,

This is a duplicate of #3920 and as such am going to close it

**Closed by katbyte** 2019-07-26 18:27 UTC

**Comment by eliecharra** [comment] 2019-07-27 07:18
@katbyte Oops my bad sorry for the dupe ...
