### ISSUE TITLE
azurerm_backup_protected_file_share: Status=404 Code="BMSUserErrorDataSourceObjectNotFound"

### ISSUE THREAD

**Issue by bernardmaltais** [terraform-providers/terraform-provider-azurerm#10258] opened 2021-01-20 14:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `terraform: v0.14.4`
* `azurerm: v2.43.0`

### Affected Resource(s)

* `azurerm_backup_protected_file_share`

### Terraform Configuration Files

Sections of code pertinent to the error. The code below will not allow to reproduce the error on it's own as it is part of a much more complext IaC base. It should provide enough details to see if the issue is related to the code or possibly how the resource is implemented in the provider:

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.43.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 1.1.1"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 1.13.3"
    }
  }
  required_version = ">= 0.14"
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

resource "azurerm_backup_container_storage_account" "protection-container-wxt-dev" {
  count = var.environment == "dev" ? 1 : 0

  resource_group_name = local.resource_groups_L1.Backups.name
  recovery_vault_name = local.Project-rsv_L1.name
  storage_account_id  = module.drupal-wxt.id
}

resource "azurerm_backup_policy_file_share" "azurerm_backup_policy_file_share-wxt-dev" {
  count = var.environment == "dev" ? 1 : 0
  
  name                = "ScDcCLD-WxT-rvp"
  resource_group_name = local.resource_groups_L1.Backups.name
  recovery_vault_name = local.Project-rsv_L1.name

  backup {
    frequency = "Daily"
    time      = "04:00" # UTC time
  }

  retention_daily {
    count = 30
  }
}

module "drupal-wxt" {
  source                   = "github.com/canada-ca-terraform-modules/terraform-azurerm-caf-storage_account?ref=v1.0.1"
  env                      = var.env
  userDefinedString        = "drupalwxt${var.project}"
  resource_group           = local.resource_groups_L2.Project
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "GRS"
  tags                     = var.tags
}

resource "azurerm_storage_share" "drupal-backup-dev" {
  count                = var.environment == "dev" ? 1 : 0
  name                 = "drupal-backup-dev"
  storage_account_name = module.drupal-wxt.name
  quota                = 50
  metadata = {
    "azurebackupprotected" = "true"
  }
}

resource "azurerm_storage_share" "drupal-backup-test" {
  count                = var.environment == "dev" ? 1 : 0
  name                 = "drupal-backup-test"
  storage_account_name = module.drupal-wxt.name
  quota                = 50
  metadata = {
    "azurebackupprotected" = "true"
  }
}

resource "azurerm_backup_protected_file_share" "drupal-backup-dev" {
  count                     = var.environment == "dev" ? 1 : 0
  resource_group_name       = local.resource_groups_L1.Backups.name
  recovery_vault_name       = local.Project-rsv_L1.name
  source_storage_account_id = azurerm_backup_container_storage_account.protection-container-wxt-dev[0].storage_account_id
  source_file_share_name    = azurerm_storage_share.drupal-backup-dev[0].name
  backup_policy_id          = azurerm_backup_policy_file_share.azurerm_backup_policy_file_share-wxt-dev[0].id
}

resource "azurerm_backup_protected_file_share" "drupal-backup-test" {
  count                     = var.environment == "dev" ? 1 : 0
  resource_group_name       = local.resource_groups_L1.Backups.name
  recovery_vault_name       = local.Project-rsv_L1.name
  source_storage_account_id = azurerm_backup_container_storage_account.protection-container-wxt-dev[0].storage_account_id
  source_file_share_name    = azurerm_storage_share.drupal-backup-test[0].name
  backup_policy_id          = azurerm_backup_policy_file_share.azurerm_backup_policy_file_share-wxt-dev[0].id
}
```

### Expected Behaviour

Associated backup items for the selected schedule should be created without errors

### Actual Behaviour

Associated backup items for the selected schedule are created in Azure but with the following terraform execution failing and associated error:

```txt
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_backup_protected_file_share.drupal-backup-test[0]: Creating...
azurerm_storage_share.drupal-backup-dev[0]: Modifying... [id=https://scdcdrupxtgfsksd4a7e32f.file.core.windows.net/drupal-backup-dev]
azurerm_storage_share.drupal-backup-dev[0]: Modifications complete after 1s [id=https://scdcdrupalwxtaksd4a7ec1f.file.core.windows.net/drupal-backup-dev]
azurerm_backup_protected_file_share.drupal-backup-dev[0]: Creating...
azurerm_backup_protected_file_share.drupal-backup-test[0]: Still creating... [10s elapsed]
azurerm_backup_protected_file_share.drupal-backup-dev[0]: Still creating... [10s elapsed]
azurerm_backup_protected_file_share.drupal-backup-test[0]: Still creating... [20s elapsed]
azurerm_backup_protected_file_share.drupal-backup-dev[0]: Still creating... [20s elapsed]
azurerm_backup_protected_file_share.drupal-backup-test[0]: Still creating... [30s elapsed]
azurerm_backup_protected_file_share.drupal-backup-dev[0]: Still creating... [30s elapsed]
azurerm_backup_protected_file_share.drupal-backup-test[0]: Still creating... [40s elapsed]
azurerm_backup_protected_file_share.drupal-backup-dev[0]: Still creating... [40s elapsed]
azurerm_backup_protected_file_share.drupal-backup-test[0]: Still creating... [50s elapsed]
azurerm_backup_protected_file_share.drupal-backup-dev[0]: Still creating... [50s elapsed]
Terraform apply return code: 0
Terraform returned errors:

Error: Error creating/udpating Azure File Share backup item "AzureFileShare;drupal-backup-dev" (Vault "ScDcCNR-CIO-AKS-rsv"): backup.ProtectedItemsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="BMSUserErrorDataSourceObjectNotFound" Message="Item not found.\r\nSelected item might have been deleted. Please check if item is registered to the vault."

  on drupal-wxt-dev.tf line 25, in resource "azurerm_backup_protected_file_share" "drupal-backup-dev":
  25: resource "azurerm_backup_protected_file_share" "drupal-backup-dev" {



Error: Error creating/udpating Azure File Share backup item "AzureFileShare;drupal-backup-test" (Vault "ScDcCNR-CIO-AKS-rsv"): backup.ProtectedItemsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="BMSUserErrorDataSourceObjectNotFound" Message="Item not found.\r\nSelected item might have been deleted. Please check if item is registered to the vault."

  on drupal-wxt-test.tf line 25, in resource "azurerm_backup_protected_file_share" "drupal-backup-test":
  25: resource "azurerm_backup_protected_file_share" "drupal-backup-test" {


Error on or near line 540: Error running terraform apply; exiting with status 2001
```

![image](https://user-images.githubusercontent.com/25299479/105187012-4a52cc80-5b00-11eb-83c9-e46e56ad40a9.png)

Those resources in Azure are now orphan as a result since they are not properly managed in the state file...

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by svsunil** [comment] 2021-01-25 16:45
I took encountered same error when using azurerm_backup_protected_file_share, but backup file share is created properly in recovery service vault configured in terraform.
My environment is terraform: v0.13.2 and azurerm: v2.42.0

**Comment by katbyte** [comment] 2021-06-24 05:53
closing as a duplicate of #9452

**Closed by katbyte** 2021-06-24 05:53 UTC
Labels: bug, service/backup
