### ISSUE TITLE
Provider produced inconsistent final plan when IP restrictions to app service module from another app service module output

### ISSUE THREAD

**Issue by joeyfalloneffatg** [terraform-providers/terraform-provider-azurerm#5185] opened 2019-12-16 20:01 UTC
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.10
+ provider.azurerm v1.38.0
# on macOS Catalina 10.15.1, kernel 19.0.0
### Affected Resource(s)

* `azurerm_app_service`
### Terraform Configuration Files

```hcl
module "app-service-module1" {
  source                              = "./modules/app-service-module1"
  name                                = "app-service-issue-demo-module1"
  resource_group                      = azurerm_resource_group.this
  whitelisted_ip_addresses            = concat(local.ip_addrs, [for ip in module.app-service-module2.outgoing_ips : "${ip}/32"])
  app_service_plan_id                 = azurerm_app_service_plan.service_plan.id
}
module "app-service-module2" {
  source                              = "./modules/app-service-module2"
  name                                = "app-service-issue-demo-module2"
  resource_group                      = azurerm_resource_group.this
  whitelisted_ip_addresses            = local.ip_addrs
  app_service_plan_id                 = azurerm_app_service_plan.service_plan.id
}
# both modules defined as:
resource "azurerm_app_service" "this" {
  name                = var.name
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name
  app_service_plan_id = var.app_service_plan_id
  https_only          = true
  site_config {
    dynamic "ip_restriction" {
      for_each = var.whitelisted_ip_addresses
      content {
        ip_address = cidrhost(ip_restriction.value, 0)
      }
    }
  }
}
output "outgoing_ips" {
  value = split(",", azurerm_app_service.this.outbound_ip_addresses)
}
```
### Panic Output
N/A
### Expected Behavior
Terraform should config the app services with the correct IP rules added.
### Actual Behavior
Terraform produces the following error(s) for each ip:
```
Error: Provider produced inconsistent final plan
When expanding the plan for
module.app-service-module1.azurerm_app_service.this to include new values
learned so far during apply, provider "azurerm" produced an invalid new value
for .site_config[0].ip_restriction: new element 1 has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
### Steps to Reproduce
1. `terraform apply` # from a clean slate
### Important Factoids
Workaround: 
Run `terraform apply` again and the expected behaviour occurs.
* #0000

**Comment by ie-zero** [comment] 2020-05-16 18:50
#5159 appear somewhat similar to this one.

**Comment by tombuildsstuff** [comment] 2020-10-26 10:46
Duplicate of #5159

**Closed by tombuildsstuff** 2020-10-26 10:46 UTC
Labels: bug, service/app-service
