### ISSUE TITLE
Support for SQL data disks with the azurerm_mssql_virtual_machine resource

### ISSUE THREAD

**Issue by Marcus-James-Adams** [terraform-providers/terraform-provider-azurerm#7481] opened 2020-06-24 21:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The mssql_virtual_machine resource allows you to configure a SQL VM and connect it up the SQl management in azure in the same way as you would via the gui or in an arm template.  it covers all the items that the gui and arm template does, with one exception of SQL storage

### New or Affected Resource(s)

azurerm_mssql_virtual_machine resource

### Potential Terraform Configuration

the arm that provisions has code that looks lie this, it allocates the drives to the luns listed, sets the drive letter and formats it then it updates the SQL so that it knows what the new data paths are. 
```hcl
	"storageConfigurationSettings": {
		"DiskConfigurationType": "NEW",
		"StorageWorkloadType": "OLTP",
		"sqlDataSettings": {
			"luns": "2,3,4",
			"DefaultFilePath": "S:\\MSsql\\Data"
		},
		"sqlLogSettings": {
			"luns": "15,16,17,18",
			"DefaultFilePath": "L:\\MSsql\\Logs"
		},
		"sqlTempDbSettings": {
			"luns": "25,26",
			"DefaultFilePath": "T:\\MSsql\\TempDB"
		}
	}
```
I see the code as being a series of optional blocks with the current resource so you can choose what data drive types you want.
I also see two additional options to deal with the addition or removal of extra luns.
**sqlStorage_allow_expand** - if there are now more unused luns than previously allocated to a section - then automatically expand the drive if set. (default is true)
**sqlStorage_allow_shrink**  - if there are fewer luns per data section and this is set to true then the drive recreated as if new under the new size configuration (default is false)

```hcl
  sqlStorage_allow_expand   = "true"
  sqlStorage_allow_shrink   = "false"
  sqlDataSettings {
		DefaultFilePath = "S:\\MSsql\\Data"
        luns = [
		for each azurerm_virtual_machine_data_disk_attachment.dbdata:
			azurerm_virtual_machine_data_disk_attachment.dbdata.lun
			]
}

  sqlLogSettings {
		DefaultFilePath = "L:\\MSsql\\Data"
        luns = [
		# this example pickups up all disk attachments by resource name
			azurerm_virtual_machine_data_disk_attachment.log1.lun.
			azurerm_virtual_machine_data_disk_attachment.log13.lun,
			azurerm_virtual_machine_data_disk_attachment.log3.lun
			]
}

  sqlTempDbSettings {
		DefaultFilePath = "T:\\MSsql\\Data"
		# this example pickups up all disk attachments by lun number
        luns = [ "2","3","4","5" ]
}
```

### References

https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/storage-configuration
--->

* #0000

**Comment by yupwei68** [comment] 2020-09-03 02:46
Duplication of https://github.com/terraform-providers/terraform-provider-azurerm/issues/7341

**Comment by tombuildsstuff** [comment] 2020-09-03 06:24
hi @Marcus-James-Adams 

Thanks for opening this issue :)

Taking a look through as @yupwei68 has mentioned this appears to be a duplicate of #7341 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7341 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-09-03 06:24 UTC
