### ISSUE TITLE
Support for azurerm_resource_group dependent resource deletion detection

### ISSUE THREAD

**Issue by phatcher** [terraform-providers/terraform-provider-azurerm#10218] opened 2021-01-17 15:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Given that deleting a resource group currently deletes all the resources within it is there anyway for us to know that fact before the destroy is executed?

If you issue destroy on a resource group it doesn't currently know/show if it contains nothing or the entire application architecture.

Don't know if this is knowable from where we are.

### New or Affected Resource(s)

* azurerm_resource_group

**Comment by tombuildsstuff** [comment] 2021-01-18 06:58
hey @phatcher 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #1608 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1608 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-18 06:58 UTC

**Comment by phatcher** [comment] 2021-01-18 07:32
@tombuildsstuff Thanks, I thought it might be here already, but I couldn't find it :smile:
