### ISSUE TITLE
Importing policy_set_definition (initiative) into Terraform state fails

### ISSUE THREAD

**Issue by schwarzzz** [terraform-providers/terraform-provider-azurerm#8371] opened 2020-09-07 07:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.2
+ provider registry.terraform.io/-/azurerm v2.26.0
+ provider registry.terraform.io/hashicorp/azurerm v2.26.0
```

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Command

`terraform import azurerm_policy_set_definition.foo /providers/Microsoft.Management/managementGroups/<name>/providers/Microsoft.Authorization/policySetDefinitions/<guid>`

### Expected Behavior

The policy set definition (initiative) is imported into the Terraform state.

### Actual Behavior

The command fails with the following output:

```
terraform import azurerm_policy_set_definition.foo /providers/Microsoft.Management/managementGroups/<name>/providers/Microsoft.Authorization/policySetDefinitions/<guid>
module.baseline_initiative.azurerm_policy_set_definition.instance: Importing from ID "/providers/Microsoft.Management/managementGroups/<name>/providers/Microsoft.Authorization/policySetDefinitions/<guid>"...
module.baseline_initiative.azurerm_policy_set_definition.instance: Import prepared!
  Prepared azurerm_policy_set_definition for import
module.baseline_initiative.azurerm_policy_set_definition.instance: Refreshing state... [id=/providers/Microsoft.Management/managementGroups/<name>/providers/Microsoft.Authorization/policySetDefinitions/<guid>]

Error: setting `policy_definition_reference`: policy_definition_reference.0.parameters.listOfAllowedLocations: '' expected type 'string', got unconvertible type '[]interface {}'
```

### Steps to Reproduce

Execute an import command similar to the one stated above:

1. `terraform import <terraform-resource-id> <azure-resource-id>`

### Important Factoids

n/a
### References

* #0000

**Comment by ArcturusZhang** [comment] 2020-09-08 03:26
Hi @schwarzzz thanks for this issue and sorry for the inconvenience.

This issue should have the same root cause of https://github.com/terraform-providers/terraform-provider-azurerm/issues/8159, could you please track the status there?
I have made a PR to fix this issue and it is in review. 

And since this is essentially a duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/8159, I will close this issue, hope you do not mind. Thanks.

**Closed by ArcturusZhang** 2020-09-08 03:26 UTC
Labels: bug, duplicate, service/policy
