### ISSUE TITLE
AKS can't update tags with UserAssigned identity deployment and userDefinedRoute

### ISSUE THREAD

**Issue by Ledermayer** [terraform-providers/terraform-provider-azurerm#10715] opened 2021-02-24 09:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.14.7 and azurerm 2.48.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks_cluster" {
    lifecycle {
      ignore_changes = [
        default_node_pool[0].node_count,
      ]
    }

    tags = {
      BypassNamingPolicy = "True",
      tf = "True",
      Environment = var.EnvironmentType,
      opsSupportDl = var.OpsSupport,
      opsLifecycle = var.OpsLifecycle
    }

    name                        = local.cluster_name
    location                    = var.ResourceGroupObject.location
    resource_group_name         = var.ResourceGroupObject.name
    dns_prefix                  = "${var.ProductCode}-${var.Purpose}${var.InstanceSequence}"
    kubernetes_version          = var.AKSVersion
    node_resource_group         = join("-", [var.ResourceGroupObject.name,"nodes"])
    sku_tier                    = "Paid"

    #Network Profile
    network_profile {
        network_plugin          = "kubenet"
        outbound_type           = "userDefinedRouting"
        pod_cidr                = "172.16.0.0/16"
        service_cidr            = "172.17.0.0/16"
        dns_service_ip          = "172.17.0.10"
        docker_bridge_cidr      = "172.18.0.1/16"
    }

    #Default Node Pool
    default_node_pool {
        name                    = var.DefaultNodePoolName
        orchestrator_version    = var.AKSVersion
        vm_size                 = var.NodeVMSize
        type                    = "VirtualMachineScaleSets"
        availability_zones      = var.Zones
        vnet_subnet_id          = var.SubnetObjectID
        os_disk_size_gb         = var.OSDiskSize
        enable_host_encryption  = var.EnableHostEncryption
        node_labels             = var.Labels
        enable_auto_scaling     = true
        min_count               = var.NodeCountMin
        max_count               = var.NodeCountMax
        tags                    = {
          BypassNamingPolicy = "True",
          tf = "True",
          Environment = var.EnvironmentType,
          opsSupportDl = var.OpsSupport,
          opsLifecycle = var.OpsLifecycle
        }
    }

  dynamic "auto_scaler_profile" {
    for_each = var.AutoscalingEnabled ? [1] : []
    content {
      max_graceful_termination_sec = var.AutoscalingSensitivity == "low" ? 1200 : (var.AutoscalingSensitivity == "high" ? 300 : 600)
      scale_down_delay_after_add = var.AutoscalingSensitivity == "low" ? "20m" : (var.AutoscalingSensitivity == "high" ? "5m" : "10m")
      scale_down_delay_after_delete = var.AutoscalingSensitivity == "low" ? "20s" : (var.AutoscalingSensitivity == "high" ? "5s" : "10s")
      scale_down_delay_after_failure = var.AutoscalingSensitivity == "low" ? "6m" : (var.AutoscalingSensitivity == "high" ? "1m" : "3m")
      scan_interval = var.AutoscalingSensitivity == "low" ? "20s" : (var.AutoscalingSensitivity == "high" ? "5s" : "10s")
      scale_down_unneeded = var.AutoscalingSensitivity == "low" ? "20m" : (var.AutoscalingSensitivity == "high" ? "5m" : "10m")
      scale_down_unready = var.AutoscalingSensitivity == "low" ? "40m" : (var.AutoscalingSensitivity == "high" ? "10m" : "20m")
      scale_down_utilization_threshold = var.AutoscalingSensitivity == "low" ? 0.25 : (var.AutoscalingSensitivity == "high" ? 0.75 : 0.5)
    }
  }

    identity {
      type = "UserAssigned"
      user_assigned_identity_id = var.ManagedIdentityID
    }
    
    #Addon Profile
    addon_profile {
        oms_agent {
            enabled = var.OMSAgentEnabled
            log_analytics_workspace_id = var.LogAnalyticsWorkspaceID
        }
        
        azure_policy {
            enabled = true
        }
    }

    #Access
    role_based_access_control {
        enabled = true
        azure_active_directory {
            managed = true
            admin_group_object_ids = var.AdminGroupObjectIDs
        }
    }

    dynamic "linux_profile" {
      for_each = var.LinuxProfileEnabled ? [1] : []
        content {
          admin_username = var.AdminUserName
            ssh_key {
                key_data = var.PublicKey
            }
        }
    }
    
    depends_on = [
        azurerm_route_table.udr,
        azurerm_subnet_route_table_association.aksudr-association,
        azurerm_role_assignment.aks_udr
    ]
    
}
```

### Expected Behaviour

Terraform changes tags as per the plan:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # module.akstest.azurerm_kubernetes_cluster.aks_cluster will be updated in-place
~ resource "azurerm_kubernetes_cluster" "aks_cluster" {
        id                              = "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/rgrp-tva2-do-akstest/providers/Microsoft.ContainerService/managedClusters/akse-tva2-do-akstest001"
        name                            = "akse-tva2-do-akstest001"
      ~ tags                            = {
          + "Environment"        = "t"
          + "opsLifecycle"       = "short-lived"
          + "opsSupportDl"       = "someone@somewhere.com"
            # (2 unchanged elements hidden)
        }
        # (16 unchanged attributes hidden)



      ~ default_node_pool {
            name                         = "linuxpool"
          ~ tags                         = {
              + "Environment"        = "t"
              + "opsLifecycle"       = "short-lived"
              + "opsSupportDl"       = "someone@somewhere.com"
                # (2 unchanged elements hidden)
            }
            # (17 unchanged attributes hidden)
        }




        # (6 unchanged blocks hidden)
    }
```

### Actual Behaviour

Apply failed with the following error:

```
Acquiring state lock. This may take a few moments...

module.akstest.azurerm_kubernetes_cluster.aks_cluster: Modifying... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/rgrp-tva2-do-akstest/providers/Microsoft.ContainerService/managedClusters/akse-tva2-do-akstest001]

Error: updating Managed Kubernetes Cluster "akse-tva2-do-akstest001" (Resource Group "rgrp-tva2-do-akstest"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidIdentityValues" Message="Invalid value for the identities '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgrp-tva2-do-akstest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umid-pva2-do-akstest001'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."

  on .terraform/modules/akstest/main.tf line 1, in resource "azurerm_kubernetes_cluster" "aks_cluster":
   1: resource "azurerm_kubernetes_cluster" "aks_cluster" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We have escalated the error to microsoft, they have come back with this statement:

•	Managed Identities have undergone some variation with regard to format so there could be some issue related to how its being translated by Terraform:
o	Old format:  `“My-Managed-Identity-Resource-Id”: {}`
o	New Format: ` “My-Managed-Identity-Resource-Id”`
o	How its stored in Azure:
```
“My-Managed-Identity-Resource-Id”: {
                “clientId”: “xxxxxxx”,
                “principalId”: “xxxxxxx”
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-02-24 10:04
Duplicate of #10406

**Closed by tombuildsstuff** 2021-02-24 10:04 UTC
Labels: bug, duplicate, service/kubernetes-cluster
