### ISSUE TITLE
azurerm_dev_test_windows_virtual_machine Code="TooManyPortsRequested"

### ISSUE THREAD

**Issue by enufacas** [terraform-providers/terraform-provider-azurerm#2415] opened 2018-11-29 18:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.11.10
provider.azurerm v1.19.0

### Affected Resource(s)

* azurerm_dev_test_windows_virtual_machine
https://www.terraform.io/docs/providers/azurerm/r/dev_test_windows_virtual_machine.html

### Terraform Configuration Files

```hcl
resource "azurerm_dev_test_windows_virtual_machine" "test" {
  name                       = "example-vm01"
  lab_name                   = "TeamC-Lab"
  resource_group_name        = "TeamC"
  location                   = "East US"
  size                       = "Standard_B1ms"
  username                   = "exampleuser999"
  password                   = "Pa$$w0rd1234!"
  lab_virtual_network_id     = "/subscriptions/guid/resourcegroups/teamc/providers/microsoft.devtestlab/labs/teamc-lab/virtualnetworks/xxxdevtestcorelab"
  lab_subnet_name            = "subnetname"
  storage_type               = "Standard"
  notes                      = "Some notes about this Virtual Machine."
  disallow_public_ip_address = "true"


  gallery_image_reference {
    offer     = "SQL2017-WS2016"
    publisher = "MicrosoftSQLServer"
    sku       = "Standard"
    version   = "latest"
  }

}
```

### Expected Behavior
I am attempting to use an existing virtual network to create a new dev test machine. The network exists in my DevTest lab and I can successfully create a VM using the network\subnet via the Azure portal. This particular network does not allow public ip addresses. 

### Actual Behavior
Error I am receiving:

 azurerm_dev_test_windows_virtual_machine.test: Error waiting for creation/update of DevTest Windows Virtual Machine "example-vm01" (Lab "TeamC-Lab" / Resource Group "TeamC"): Code="TooManyPortsRequested" Message="A virtual machine cannot expose more than 150 ports, but 0 ports were requested."
 
### Steps to Reproduce

1. `terraform apply`

### Important Factoids
I originally attempted to import the network with [Data Source: azurerm_virtual_network](https://www.terraform.io/docs/providers/azurerm/d/virtual_network.html) but realized that it is a different resource type than [azurerm_dev_test_virtual_network](https://www.terraform.io/docs/providers/azurerm/r/dev_test_virtual_network.html) . So I set the lab_virtual_network_id using the syntax. 

lab_virtual_network_id     = "/subscriptions/guid/resourcegroups/teamc/providers/microsoft.devtestlab/labs/teamc-lab/virtualnetworks/xxxdevtestcorelab"

**Comment by metacpp** [comment] 2019-01-24 02:13
Thanks @enufacas to open this issue. I can reproduce `TooManyPortsRequested` as you through below configuration:

```tf
resource "random_id" "test" {
  byte_length = 4
}
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-${random_id.test.dec}"
  location = "East US"
}

resource "azurerm_dev_test_lab" "test" {
  name                = "acctestlab-${random_id.test.dec}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  tags {
    "Sydney" = "Australia"
  }
}

resource "azurerm_dev_test_virtual_network" "test" {
  name                = "accvnet-${random_id.test.dec}"
  lab_name            = "${azurerm_dev_test_lab.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  subnet {
    use_public_ip_address           = "Allow"
    use_in_virtual_machine_creation = "Allow"
  }
}

resource "azurerm_dev_test_windows_virtual_machine" "test" {
  name                       = "lab-${random_id.test.dec}"
  lab_name                   = "${azurerm_dev_test_lab.test.name}"
  resource_group_name        = "${azurerm_resource_group.test.name}"
  location                   = "${azurerm_resource_group.test.location}"
  size                       = "Standard_B1ms"
  username                   = "exampleuser999"
  password                   = "Pa$$w0rd1234!"
  lab_virtual_network_id     = "${azurerm_dev_test_virtual_network.test.id}"
  lab_subnet_name            = "${azurerm_dev_test_virtual_network.test.subnet.0.name}"
  storage_type               = "Standard"
  notes                      = "Some notes about this Virtual Machine."
  disallow_public_ip_address = "true"

  gallery_image_reference {
    offer     = "SQL2017-WS2016"
    publisher = "MicrosoftSQLServer"
    sku       = "Standard"
    version   = "latest"
  }
}
```

```sh
Error: Error applying plan:

1 error(s) occurred:

* azurerm_dev_test_windows_virtual_machine.test: 1 error(s) occurred:

* azurerm_dev_test_windows_virtual_machine.test: Error waiting for creation/update of DevTest Windows Virtual Machine "lab-**********" (Lab "acctestlab-**********" / Resource Group "acctestRG-**********"): Code="TooManyPortsRequested" Message="A virtual machine cannot expose more than 150 ports, but 0 ports were requested."

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This seems to be an issue by `DevTestLab` service API, we need to reach out service team to double confirm it.

**Comment by tombuildsstuff** [comment] 2019-04-18 10:39
hi @enufacas 

Since this is an issue with the Azure API I've requested an update on the issue that @metacpp opened - however rather than leaving this issue open indefinitely I'm going to close this issue for the moment. Once the upstream API issue has been resolved we'll circle back to this issue and try and identify a path forward.

Thanks!

**Closed by tombuildsstuff** 2019-04-18 10:39 UTC
Labels: service/devtestlabs, upstream-microsoft, waiting-response
