### ISSUE TITLE
autoscale support for for cosmosdb collection and database

### ISSUE THREAD

**Issue by davejhahn** [terraform-providers/terraform-provider-azurerm#7598] opened 2020-07-06 19:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
azurerm_cosmosdb_mongo_collection and database doesn't have support for autoscaling.   

### New or Affected Resource(s)
azurerm_cosmosdb_mongo_collection
azurerm_cosmosdb_mongo_database

### Potential Terraform Configuration
azurerm_cosmosdb_mongo_collection
``````
resource "azurerm_cosmosdb_mongo_collection" "MyCollection" {
  name = "MyCollectionName"
  resource_group_name = "MyResourceGroupName"
  account_name =  "MyAccountName"
  database_name = "MyDatabaseName"
  throughput = 400
  throughout_type = "Manual|Autoscale"
  shard_key = "MyShardKey"
}
``````
azurerm_cosmosdb_mongo_database

``````
resource "azurerm_cosmosdb_mongo_database" "MyDatabase" {
  name = "MyDatabase"
  resource_group_name = "MyResourceGroupName"
  account_name = "MyAccountName"
  throughput = 4000
  throughput_type = "Manual|Autoscale"
}
``````

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by StefanSchoof** [comment] 2020-07-08 21:03
Sounds related to #6164

**Comment by tombuildsstuff** [comment] 2020-07-14 10:58
hi @davejhahn 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6164 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6164 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-07-14 10:58 UTC
Labels: enhancement, service/cosmosdb
