### ISSUE TITLE
how to enable "Storage account key access" for Azure blob storage account with Terraform[azurerm_storage_account]

### ISSUE THREAD

**Issue by immarvin** [terraform-providers/terraform-provider-azurerm#11689] opened 2021-05-13 00:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I created a azure blob storage account with following tf:
```
resource "azurerm_storage_account" "main" {
  name                     = "${var.prefix}${var.env}${var.location}brs"
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  #delete_retention_policy = 365

  tags = {
    source   = "terraform"
    env      = var.env
    location = var.location
    owner    = "xxx@yyy.com"
  }
}

```

![](https://user-images.githubusercontent.com/5668922/117945170-a5732e00-b340-11eb-9088-6cdc0bf2b59c.png)

I went through the doc https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account, but cannot find any filed to enable "Storage account key access".

Any way to enable it with terraform? thanks
### New or Affected Resource(s)

azurerm_storage_account

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account

* #0000

**Comment by WodansSon** [comment] 2021-05-13 01:43
@immarvin, thanks for opening this issue. This would appear to be a bug in the portal UI code, as per the ARM REST API [documentation](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/create#request-body) the default (e.g. `null` value) here defaults to the Storage account key access being enabled. 

> Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). The default value is null, which is equivalent to true.

The bug here, I believe, would be that Terraform doesn't actually allow the resource to disable the Storage account access keys to switch over to Azure AD authorization.

**Comment by immarvin** [comment] 2021-05-13 02:40
thanks for your quick response @WodansSon 
so do you have plan to support the control over this behavior?

**Comment by WodansSon** [comment] 2021-05-13 03:16
@immarvin, I have confirmed that this is a portal UI bug. The portal UI is interpreting the `null` value as `false` and displaying `Disabled` instead of following what the ARM API documentation states that `null` is `true`.

![image](https://user-images.githubusercontent.com/20408400/118072478-b9c62380-b35e-11eb-837d-82611a864227.png)


As for fixing this I don't know, it would be a rather trivial fix but I will contact the internal MS team to see if we can get this on the radar. 🙂

**Comment by yupwei68** [comment] 2021-05-13 05:20
Hi @immarvin , thanks for opening this issue. Since it's a portal UI bug, @WodansSon and I will contact MS team to see if we can get this reported and fixed.
But we could not implement this field in Terraform. Because currently we use `Shared Key` to authenticate storage account. Before we try to update `AllowSharedKeyAccess` to `true`, our plugin will return error in reading this storage account for lack of permission.
I used to raised an issue here for tracking this problem https://github.com/terraform-providers/terraform-provider-azurerm/issues/11460

**Comment by immarvin** [comment] 2021-05-13 06:14
ok. thanks a lot for your information. I am ok to close the ticket

**Comment by yupwei68** [comment] 2021-05-13 08:01
I think it's a portal UI display problem. Because in detail display, it shows that `AllowSharedKeyAccess` is enabled. It doesn't influence the usage in Terraform.
![image](https://user-images.githubusercontent.com/56525716/118096863-81792080-b404-11eb-98f6-f449405d436e.png)

**Comment by WodansSon** [comment] 2021-05-13 08:56
> I think it's a portal UI display problem. Because in detail display, it shows that `AllowSharedKeyAccess` is enabled. It doesn't influence the usage in Terraform.

Yes, that is correct, but it is still confusing for our customers which is why I opened the PR to fix this issue. I feel it is the best we can do with what we have and I am opening a dialog with the Portal team to see if they can fix their code to display this correctly. That said, if my PR makes it into the code base, net new Storage accounts will not see this UI issue, and existing Storage accounts will be fixed if they change the Storage account in anyway, even adding a tag. So, for a non-breaking way to fix this I feel at this point in time this is our best option pending the Portal team fixing their UI bug.

**Closed** 2021-05-13 18:04 UTC
Labels: bug, documentation, enhancement, service/storage, upstream-microsoft
