### ISSUE TITLE
Case Sensitive issue with ssl_certificate.0.data parameter in application_gateway

### ISSUE THREAD

**Issue by VaijanathB** [terraform-providers/terraform-provider-azurerm#1426] opened 2018-06-21 18:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Latest 
Terraform v0.11.8-dev (ab6240afb0898b5c5147e2247454f5d4282ffebf+CHANGES)
+ provider.azurerm (unversioned)

### Affected Resource(s)

* azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-1"
  location = "southcentralus"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-vnet1"
  resource_group_name = "${azurerm_resource_group.test.name}"
  address_space       = ["10.254.0.0/16"]
  location            = "${azurerm_resource_group.test.location}"
}

resource "azurerm_subnet" "test" {
  name                 = "subnet-1"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.254.0.0/24"
}

resource "azurerm_public_ip" "test" {
  name                         = "acctest-pubip-1"
  location                     = "${azurerm_resource_group.test.location}"
  resource_group_name          = "${azurerm_resource_group.test.name}"
  public_ip_address_allocation = "dynamic"
}

resource "azurerm_application_gateway" "test" {
  name                = "acctestgw-1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name     = "Standard_Medium"
    tier     = "Standard"
    capacity = 1
  }

  disabled_ssl_protocols = [
    "TLSv1_0",
  ]

  gateway_ip_configuration {
    # id = computed
    name      = "gw-ip-config1"
    subnet_id = "${azurerm_subnet.test.id}"
  }

  frontend_ip_configuration {
    # id = computed
    name                 = "ip-config-public"
    public_ip_address_id = "${azurerm_public_ip.test.id}"
  }

  frontend_ip_configuration {
    # id = computed
    name      = "ip-config-private"
    subnet_id = "${azurerm_subnet.test.id}"

    # private_ip_address = computed
    private_ip_address_allocation = "Dynamic"
  }

  frontend_port {
    # id = computed
    name = "port-8080"
    port = 8080
  }

  backend_address_pool {
    # id = computed
    name = "pool-1"

    fqdn_list = [
      "terraform.io",
    ]
  }

  backend_http_settings {
    # id = computed
    name                  = "backend-http-1"
    port                  = 8010
    protocol              = "Https"
    cookie_based_affinity = "Enabled"
    request_timeout       = 30

    # probe_id = computed
    probe_name = "probe-1"
  }

  http_listener {
    # id = computed
    name = "listener-1"

    # frontend_ip_configuration_id = computed
    frontend_ip_configuration_name = "ip-config-public"

    # frontend_ip_port_id = computed
    frontend_port_name = "port-8080"
    protocol           = "Http"
  }

  http_listener {
    name                           = "listener-2"
    frontend_ip_configuration_name = "ip-config-public"
    frontend_port_name             = "port-8080"
    protocol                       = "Https"

    # ssl_certificate_id = computed
    ssl_certificate_name = "ssl-1"
    host_name            = "terraform.io"
    require_sni          = true
  }

  probe {
    # id = computed
    name                = "probe-1"
    protocol            = "Https"
    path                = "/test"
    host                = "azure.com"
    timeout             = 120
    interval            = 300
    unhealthy_threshold = 8
}

  url_path_map {
    # id = computed
    name                               = "path-map-1"
    default_backend_address_pool_name  = "pool-1"
    default_backend_http_settings_name = "backend-http-1"

    path_rule {
      # id = computed
      name                       = "path-rule-1"
      backend_address_pool_name  = "pool-1"
      backend_http_settings_name = "backend-http-1"

      paths = [
        "/test",
      ]
    }
  }

  request_routing_rule {
    # id = computed
    name      = "rule-basic-1"
    rule_type = "Basic"

    # http_listener_id = computed
    http_listener_name = "listener-1"

    # backend_address_pool_id = computed
    backend_address_pool_name = "pool-1"

    # backend_http_settings_id = computed
    backend_http_settings_name = "backend-http-1"
  }

  request_routing_rule {
    # id = computed
    name              = "rule-path-1"
    rule_type         = "PathBasedRouting"
    url_path_map_name = "path-map-1"

    # http_listener_id = computed
    http_listener_name = "listener-2"
  }

  ssl_certificate {
    # id = computed
    name     = "ssl-1"
    data     = "${file("~testdata/application_gateway_test.pfx")}"
    password = "terraform"
  }

  tags {
    environment = "tf01"
  }
}

```
### Steps to Reproduce 
1) Terraform apply (Apply succeeds)
2) Terraform plan 

### Expected Behavior

0 Changes to Apply. 

### Actual Behavior
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_application_gateway.test
      ssl_certificate.0.data: <sensitive> => <sensitive> (attribute changed)

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by tombuildsstuff** [comment] 2018-07-15 12:04
Duplicate of #583

**Closed by tombuildsstuff** 2018-07-15 12:04 UTC
Labels: bug, service/application-gateway
