### ISSUE TITLE
Unable to update AKS cluster using user assigned identity

### ISSUE THREAD

**Issue by zachomedia** [terraform-providers/terraform-provider-azurerm#10687] opened 2021-02-22 19:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_user_assigned_identity" "aks" {
  name                = "test"
  resource_group_name = "test-rg"
  location            = "Canada Central"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                = "test"
  resource_group_name = "test-rg"
  location            = "Canada Central"
  dns_prefix          = "test"
  kubernetes_version  = "1.19.7"

  identity {
    type                      = "UserAssigned"
    user_assigned_identity_id = azurerm_user_assigned_identity.aks.id
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed = true
    }
  }

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }
}
```

### Debug Output

https://gist.github.com/zachomedia/f691cf5c33ea61d124446bc82b017352

### Expected Behaviour

Cluster update should have happened successfully.

### Actual Behaviour

Cluster update fails with:

```
Error: updating Managed Kubernetes Cluster "test" (Resource Group "test-rg"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidIdentityValues" Message="Invalid value for the identities '/subscriptions/$SUBSCRIPTION/resourceGroups/test-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."
```

### Steps to Reproduce

1. Apply the terraform provided above
2. Change the `node_count` in the `default_node_pool` to `2`
3. `terraform plan -out plan`
4. `terraform apply plan`

### References

I found this similar forum post:

* https://discuss.hashicorp.com/t/user-assigned-identities-property-keys-should-only-be-empty-json-objects-null-or-the-resource-exisiting-property/20962

**Comment by tombuildsstuff** [comment] 2021-02-23 06:49
hi @zachomedia 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #10406 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10406 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-23 06:49 UTC

**Comment by zachomedia** [comment] 2021-02-23 14:50
@tombuildsstuff Thanks, I'll subscribe to that issue! I guess my GitHub issue queue searching failed me yesterday as I kept looking trying to see if an issue already existed before opening one.
