### ISSUE TITLE
How to add cert from Key vault to api manger 

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3635] opened 2019-06-11 10:00 UTC
Hello, question & possible bug.

How do you correctly add a certificate to an api manager hostname block from key vault. I've noticed there isn't certificate data source so I've tried using the secret data source instead as advised here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2898#issuecomment-465098754

This doesn't seem to work as I'm met with a forbidden error (which is not the case, I can see the certificate in Azure). Terraform attempts to the the following url:
`https://product-dev.vault.azure.net/secrets/my-cert/1234?api-version=7.0'`

Manually adding this URL for the cert
`https://product-dev.vault.azure.net/certificates/my-cert/1234`
Given me this error:
>  ApiManagement service only accepts KeyVault Secrets type.

My terraform looks something like this.

```
data "azurerm_key_vault" "my_key_vault" {
  name                = "${var.name}"
  resource_group_name = "${var.resource_group}"
}

data "azurerm_key_vault_secret" "my_key_vault_secret" {
  name      = "my-cert"
  key_vault_id = "${data.azurerm_key_vault.my_key_vault.id}"
} 

.....

hostname_configuration {
    management {
      host_name = "${var.host}"
      key_vault_id = "${data.azurerm_key_vault_secret.my_key_vault_secret.id}"
    }
  }
```

**Comment by cdesewell** [comment] 2019-06-11 10:16
Issue described here too https://github.com/terraform-providers/terraform-provider-azurerm/issues/3058

**Comment by NickMetz** [comment] 2019-06-12 17:12
Hi @cdesewell,
please see my comment in #3058. The issue is that if we use managed identity in api_management this will create a service principal which has no access to keyvault. In case we define hostname_configuration with key_vault_id this will fail due to missing permissions (401 Forbidden). 

This are the steps to get the required permissions:

1. Create api_management with managed identity enabled
2. Add service principal to your keyvault in access policy. ${your_key_vault} > Access policies > Add access policy. You should find it under the same name as your api_management, it required at least certificate "get" permissions.
3. Now it should be possible to use key_vault_id in api_management

The above 3 steps are not a good solution. Because if we delete and recreate api_management, permissions for service principal are gone.

As a temporary workaround we could do something like this:

```
data "azurerm_key_vault" "my_key_vault" {
  name                            =  var.name
  resource_group_name =  var.resource_group
}

data "azurerm_key_vault_secret" "my_key_vault_secret" {
  name            = "my-cert"
  key_vault_id = data.azurerm_key_vault.my_key_vault.id
}
.....
hostname_configuration {
    management {
      host_name = var.host
      certificate   = data.azurerm_key_vault_secret.my_key_vault_secret.value
    }
  }
```
But please keep in mind that this workaround will pull out the certificate in terraform.

**Comment by cdesewell** [comment] 2019-06-13 08:04
Thanks for your response @NickMetz I can't have the cert being displayed in terraform, additionally I can't have the cert password being used in terraform either.

> 
"The above 3 steps are not a good solution. Because if we delete and recreate api_management, permissions for service principal are gone."

You say this, what kind of changes would make terraform destroy and re-create the api manager as opposed to just making changes?

**Comment by cdesewell** [comment] 2019-06-13 08:52
Just giving the key vault access policy a try to find that It#s not possible to get the principal id. I'm met with 

` "object_id" is an invalid UUUID: uuid: UUID string too short`

**Comment by NickMetz** [comment] 2019-06-13 09:37
HI @cdesewell,

> You say this, what kind of changes would make terraform destroy and re-create the api manager as opposed to just making changes?

I would expect if we delete an api managment which use managed identity, relying service principal will also be deleted. 

> Just giving the key vault access policy a try to find that It#s not possible to get the principal id. I'm met with.

You should find the principal id searching for the same name as your api managment name.

**Comment by cdesewell** [comment] 2019-06-13 09:48
Thanks @NickMetz the Principal id attribute being empty is a bug

**Comment by NickMetz** [comment] 2019-06-13 11:40
Hi @cdesewell,

can you please provide a code sample of what you tried? 

The only thing i can imagine you tried something like this:

```
data "azurerm_api_management" "test" {
  name                = "example-apim"
  resource_group_name = "example-resource-group"
}

data "azurerm_key_vault" "my_key_vault" {
  name                = "example-key-vault"
  resource_group_name = "example-resource-group"
}

data "azurerm_key_vault_secret" "my_key_vault_secret" {
  name            = "my-cert"
  key_vault_id    = data.azurerm_key_vault.my_key_vault.id
}

resource "azurerm_api_management" "test" {
  name                = "example-apim"
  location            = "westeurope"
  resource_group_name = "example-resource-group"
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  hostname_configuration {
    management {
      host_name    = "foo.example.com"
      key_vault_id = data.azurerm_key_vault_secret.my_key_vault_secret.id
    }
  }

  identity {
      type = "SystemAssigned"
   }

  sku {
    name     = "Developer"
    capacity = 1
  }
}

resource "azurerm_key_vault_access_policy" "test" {
  vault_name          = "example-vault"
  resource_group_name = "example-resource-group"

  tenant_id = data.azurerm_api_management.test.tenant_id
  object_id = data.azurerm_api_management.test.principal_id

  key_permissions = [
    "get",
  ]

  secret_permissions = [
    "get",
  ]
}
```
But this won't work because api_management creation will fail due to missing permissions to key_vault (required to fetch certificate in hostname_configuration). If creation of api_management fail managed service principal will not be created. That for it would also not be possible to get object_id from service principal any you can't attach right permissions.

Like it wrote in #3058 chicken vs. egg causality dilemma. It would be better if we had the possibility to add a predefined service principal to api_managment with access to keyvault. But this is something that needs to be fixed from Azure side. 

example (is not possible at the moment)
```
  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
```

**Comment by cdesewell** [comment] 2019-06-13 12:26
@NickMetz your example is spot on, it's a chicken and egg dilemma. Could one solution be to have host configuration as a separate terraform resource definition. Similiar to how an App Service Custom Domain:
https://www.terraform.io/docs/providers/azurerm/r/app_service_custom_hostname_binding.html

**Comment by mikhailshilkov** [comment] 2019-09-18 11:51
Bumped into this "chicken and egg" problem today. It seems that the proper solution should be a separate resource for `host_configuration`, as @cdesewell suggested.

**Comment by w0rldart** [comment] 2019-09-30 08:19
Yup, having the same issue. And as Mikhail said, @cdesewell's suggestion seems to make sense most.

**Comment by cdesewell** [comment] 2019-10-08 12:03
Can we get an update on this? Is this something that will get addressed?

**Comment by jeanpaulsmit** [comment] 2019-10-16 10:15
My approach for now is to create APIM without custom domains or KV integration, but use Powershell with New-AzApiManagementCustomHostnameConfiguration and Set-AzApiManagement to setup host configuration. 
There is an issue with Powershell and KV regarding certificates. APIM in the Azure portal requires certificates to be in the certificate store of KV, while the Powershell requires the certificate to be in the secret store. This leads to the infamous "ApiManagement service only accepts KeyVault Secrets type"...
As long as Microsoft doesn't fix this, my fallback is to store the cert with APIM and not in KV. Rather this and then fully automated deployment and setup, then stick to KV and have to do step manually.

**Comment by hochas** [comment] 2020-04-06 11:19
I just wanted to chime in with how I solved it using the suggestion from @jeanpaulsmit. Hope this helps anyone until there is a proper REST endpoint for doing this.

I added this resource in the same terraform script that creates the API service:

```
data "azurerm_key_vault" "storemanager-common" {
  name                = "storemanager-common"
  resource_group_name = data.azurerm_resource_group.resource_group.name
}

resource "azurerm_key_vault_access_policy" "key_vault_access_policy" {
  key_vault_id  = data.azurerm_key_vault.storemanager-common.id
  tenant_id     = data.azurerm_client_config.current.tenant_id
  object_id     = azurerm_api_management.api_management.identity[0].principal_id
  secret_permissions = [
    "get"
  ]

  provisioner "local-exec" {
    command = format("%s/add-domain.ps1 %s %s %s %s",
      path.module,
     "hostname.com",
      "certificateId",
      azurerm_api_management.api_management.resource_group_name,
      azurerm_api_management.api_management.name
    )
  }
}
```

And `add-domain.ps1`. This requires PowerShell to be installed as a snap. If you have installed it some other way, change the hashbang to point to your PowerShell bin.

```
#!/snap/bin/pwsh

$hostname = $args[0]
$certificateId = $args[1]
$resourceGroupName = $args[2]
$apiServiceName = $args[3]

if (!(Get-Module -ListAvailable -Name Az)) {
    Write-Host "Installing Azure module"
    Install-Module -Name Az -AllowClobber
}

Write-Host "Assigning custom hostname $hostname"
$apim = Get-AzApiManagement -ResourceGroupName $resourceGroupName -Name $apiServiceName
$apim.ProxyCustomHostnameConfiguration = @(New-AzApiManagementCustomHostnameConfiguration -Hostname $hostname -HostnameType Proxy -KeyVaultId $certificateId)
Set-AzApiManagement -InputObject $apim
Write-Host "Assigned hostname $hostname"
```

**Comment by bytejunkie** [comment] 2020-04-16 09:18
I've got this very issue too. I can see two workaround above, but I'd love someone from hashicorp to chip in on if they can see why this circular dependancy just doesnt work. @tombuildsstuff  maybe?
it defintely feels like a bug to me. 

I get that I can use a workaround and we actually already have one, in that we deploy an APIM instance without the hostname config, then in the very same template we repeat the APIM resource with another name and add the hostname config in. its a double deployment of APIM, its a bit hacky, but it ususally works. until today when its erroring for some unknown reason. this is some pretty nasty code that at some point im going to have to hand over to the client an explain that the tool i told them would revolutionise their deployments has some pretty hacky workarounds in it.

**Comment by AmudaPalani** [comment] 2020-11-16 19:44
resolved this issue using azurerm_api_management_custom_domain

**Comment by manicminer** [comment] 2020-11-18 11:30
I believe this issue is resolved using the newly added [azurerm_api_management_custom_domain](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8228) resource, so I'm going to close this issue accordingly. Thanks!

**Closed by manicminer** 2020-11-18 11:30 UTC
Labels: service/api-management, service/keyvault
