### ISSUE TITLE
Specifying Subject Alternative Name in Azure KeyVault Certificate resource

### ISSUE THREAD

**Issue by kalyanrajsista** [terraform-providers/terraform-provider-azurerm#1309] opened 2018-05-28 14:58 UTC
Hi,

Is there any way I can specify Specifying Subject Alternative Name in Azure Keyvault resource for certificate generation.

**Comment by tombuildsstuff** [comment] 2018-05-29 11:12
Duplicate of #479 - closing this in favour of that issue.

**Closed by tombuildsstuff** 2018-05-29 11:12 UTC
Labels: enhancement, service/keyvault
