### ISSUE TITLE
Error: Provider produced inconsistent result after apply "azurerm_eventhub_authorization_rule"

### ISSUE THREAD

**Issue by solinov** [terraform-providers/terraform-provider-azurerm#10704] opened 2021-02-23 14:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.17
Azurerm 2.19.0

### Affected Resource(s)
azurerm_eventhub_authorization_rule

### Terraform Configuration Files

variable hub_and_secret_prefixes {
  default = {
    key1 = "value1"
    key2 = "value2"
    key3 = "value3"
    key4 = "value4"
  }
}

resource azurerm_resource_group tenant_resource_group {
  name     = "prefix-tenant-rg"
  location = "east us 2"
}

resource azurerm_eventhub_namespace tenant_eventhub_namespace {
  name                = "${var.tenant_name}-ehns"
  location            = azurerm_resource_group.tenant_resource_group.location
  resource_group_name = azurerm_resource_group.tenant_resource_group.name
  sku                 = "Standard"
  capacity            = 1
}

resource azurerm_eventhub tenant_eventhub {
  for_each            = var.hub_and_secret_prefixes
  name                = "${each.key}001"
  namespace_name      = azurerm_eventhub_namespace.tenant_eventhub_namespace.name
  resource_group_name = azurerm_resource_group.tenant_resource_group.name
  partition_count     = 2
  message_retention   = 7
}

resource azurerm_eventhub_authorization_rule listen {
  for_each            = azurerm_eventhub.tenant_eventhub
  name                = "ListenSendSharedAccessKey"
  namespace_name      = azurerm_eventhub_namespace.tenant_eventhub_namespace.name
  eventhub_name       = each.value.name
  resource_group_name = azurerm_resource_group.tenant_resource_group.name
  listen              = true
  send                = true
  manage              = false
}

### Expected Behaviour
EventHub’s authorization rule to be configured according to the passed configuration

### Actual Behaviour
Error: Provider produced inconsistent result after apply
When applying changes to
module.eventhub.azurerm_eventhub_authorization_rule.send["servicename"],
provider "azurerm" produced an unexpected new value for was present, but now
absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce
terraform apply

**Comment by solinov** [comment] 2021-02-23 14:40
This is a follow up of [terraform-providers/terraform-provider-azurerm#10655](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10655), that was closed due to lack of technical details.
Hopefully, this will clarify the issue we're experiencing.

**Comment by njuCZ** [comment] 2021-05-14 02:54
@solinov sorry I could not reproduce this issue using terraform 0.12.30 and azurerm provider v2.58.0, could you please confirm whether this issue still exists?

**Comment by blame19** [comment] 2021-06-28 07:32
we're experiencing this suddenly with terraform13 and azurerm 2.65:

```
resource "azurerm_resource_group" "test-eventhub-resources" {
  name     = var.rg_name
  location = "eastus2"
}

resource "azurerm_resource_group" "test-eventhub-resources-secondary" {
  name     = "${var.rg_name}-secondary"
  location = "westus2"
}

module "test-no-cluster" {
  source = "../../"
  providers = {
    azurerm.default = azurerm
  }

  environment = "prod"
  resource_group = {
    name     = azurerm_resource_group.test-eventhub-resources.name
    location = azurerm_resource_group.test-eventhub-resources.location
  }

  eh_namespaces = {
    ci-test-mock = {
      sku                         = "Standard"
      capacity                    = 1
      auto_inflate_enabled        = true
      maximum_throughput_units    = 20
      network_rule_default_action = "Allow"
      virtual_network_rules       = []
      ip_rules                    = []
      environment                 = "prod"
      zone_redundant              = false
    }
  }
  eh_namespace_auth_rules = {
    eader = {
      namespace      = "ci-test-mock"
      listen_allowed = true
      send_allowed   = false
      manage_allowed = false
    }
  }

  eventhub_configs = {
    logs = {
      partition_count   = 2
      message_retention = 1
      namespace         = "ci-test-mock"
    }
  }
  eventhub_authorization_rules = {
    log-reader = {
      eventhub_name  = "logs"
      listen_allowed = true
      send_allowed   = false
      manage_allowed = false
      namespace      = "ci-test-mock"
    }
  }
}
```

```
--- FAIL: TestTerraformNoEventhubCluster (264.27s)
    apply.go:15: 
        	Error Trace:	apply.go:15
        	            				infra_test.go:33
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
        	            	
        	            	  on ../../main.tf line 89, in resource "azurerm_eventhub_authorization_rule" "eventhub":
        	            	  89: resource "azurerm_eventhub_authorization_rule" "eventhub" {
        	            	
        	            	}
        	Test:       	TestTerraformNoEventhubCluster
FAIL
```

It used to work without changes in the content of our module. Reverting back to previous versions of azurerm (e.g. 2.0) had no effect.

**Comment by mxplusb** [comment] 2021-06-29 18:39
I have also hit this issue and #12387.

**Comment by SPeacock1978** [comment] 2021-07-01 12:25
I hit this same issue today when I upgraded from version 2.47.0 of the azurerm provider to 2.65.0.  When I reverted to 2.47.0 the issue went away.  I'm using terraform v0.14.8.

**Comment by ronaldmundell01** [comment] 2021-07-15 00:56
I hit the same issue with the latest version of azurerm 2.67.0. I ended up going back to 2.55.0

**Comment by tombuildsstuff** [comment] 2021-07-19 08:29
There's two separate issues being discussed here, I'm closing this out [due to the lack of information in the original issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10704#issuecomment-840971233) - the other "non-retryable error received" error is being tracked in #12387

**Closed by tombuildsstuff** 2021-07-19 08:29 UTC
Labels: bug, service/event-hubs
