### ISSUE TITLE
Bug Report : Support for User Assigned Managed Identity on API Management

### ISSUE THREAD

**Issue by aberva** [terraform-providers/terraform-provider-azurerm#7909] opened 2020-07-27 09:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
Terraform azurerm 2.20.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
  identity {
    type = "UserAssigned"
    identity_ids = [
        azurerm_user_assigned_identity.UAI_hub02.id,
    ]
  }
```

### Panic Output

azurerm_api_management.APIM_apiproxy01: Creating...

Error: creating/updating API Management Service "apimanagement" (Resource Group "resourcegroup01"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidOperation" Message="Managed Service Identity (http://aka.ms/apimmsi) is not enabled on the service, which is required to access KeyVault https://kvault01.vault.azure.net/secrets/toto-certificate-fr/e082feb9be8d4cdca5f769bff89d8164."

### Steps to Reproduce

(prerequisite to have a certificate)

1. `To declare azurerm_resource_group`
2. `To declare azurerm_key_vault`
3. `To declare azurerm_user_assigned_identity`
4. `To declare azurerm_key_vault_access_policy`
5. `To declare azurerm_api_management`
7. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/6782#issue-612944845

**Comment by yupwei68** [comment] 2020-07-28 07:58
Hi @aberva , thanks for opening this issue. `UserAssigned` `identity` is supported in Azurerm 2.20.0. Would you mind providing all your Terraform configuration to help to reproduce this error?

**Comment by aberva** [comment] 2020-07-28 09:07
Hi @yupwei68 , 

```hcl
resource "azurerm_resource_group" "RG_hub01" {
  name      = "rgtsthub0001"
  location  = var.default-azure-region
  tags = {
      OI = var.OI
  }
}

resource "azurerm_key_vault" "KV_hub01" {
  name                        = "kvtsthub0001"
  location                    = var.default-azure-region
  resource_group_name         = azurerm_resource_group.RG_hub01.name
  enabled_for_disk_encryption = false
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_enabled         = true
  purge_protection_enabled    = false
  sku_name = "standard"
  tags = {
    OI = var.OI
  }
}

resource "azurerm_key_vault_access_policy" "KVAP_hub01" {
    key_vault_id = azurerm_key_vault.KV_hub01.id
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    secret_permissions = [
        "Get",
        "Set"
    ]
    certificate_permissions = [
      "Get",
      "List",
      "Update",
      "Create",
      "Import",
      "Delete",
      "Recover",
      "Backup",
      "Restore",
      "ManageContacts",
      "ManageIssuers",
      "GetIssuers",
      "ListIssuers",
      "SetIssuers",
      "DeleteIssuers",
    ] 
}

resource "azurerm_key_vault_access_policy" "KVAP_hub03" {
    key_vault_id = azurerm_key_vault.KV_hub01.id
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = azurerm_user_assigned_identity.UAI_hub02.principal_id
    secret_permissions = [
        "Get",
        "Set"
    ]
  depends_on = [azurerm_key_vault_access_policy.KVAP_hub01]
}

resource "azurerm_key_vault_certificate" "KVC_01" {
  name         = var.KVC01_name
  key_vault_id = azurerm_key_vault.KV_hub01.id

  certificate {
    contents = filebase64(var.KVC_01_certificate)
    password = ""
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
  depends_on = [azurerm_key_vault_access_policy.KVAP_hub01]
}

resource "azurerm_key_vault_certificate" "KVC_02" {
  name         = var.KVC02_name
  key_vault_id = azurerm_key_vault.KV_hub01.id

  certificate {
    contents = filebase64(var.KVC_02_certificate)
    password = ""
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
  depends_on = [azurerm_key_vault_access_policy.KVAP_hub01]
}

resource "azurerm_virtual_network" "VNET_hub01" {
  name                = var.VNET_HUB_name
  resource_group_name = azurerm_resource_group.RG_hub01.name
  address_space       = [var.VNET_HUB_address_space]
  location            = var.default-azure-region
  dns_servers         = [var.dns_ip01, var.dns_ip02]
  tags = {
    OI = var.OI
  }
}

resource "azurerm_subnet" "SUBNET_APIM01" {
name                    = var.SUBNET_apim_name
  resource_group_name   = azurerm_resource_group.RG_hub01.name
  address_prefixes      = [var.SUBNET_apim_address_space]
  virtual_network_name  = azurerm_virtual_network.VNET_hub01.name
  timeouts {
      create = "60m"
      update = "60m"
    }
}

resource "azurerm_user_assigned_identity" "UAI_hub02" {
  resource_group_name = azurerm_resource_group.RG_hub01.name
  location            = var.default-azure-region
name                = "uaitsthub0002"
  tags = {
    OI = var.OI
  }
}

resource "azurerm_api_management" "APIM_apiproxy01" {
  name                      = "AZRAPIM01"
  location                  = var.default-azure-region
  resource_group_name       = azurerm_resource_group.RG_hub01.name
  publisher_name            = var.APIM_apiproxy01_publisher_email
  publisher_email           = var.APIM_apiproxy01_publisher_email
  sku_name                  = var.APIM_apiproxy01_sku_name
  virtual_network_type      = "Internal"
  notification_sender_email = var.APIM_apiproxy01_notification_sender_email
  policy {
          xml_content = <<XML
            <!--
                IMPORTANT:
                Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.
                Only the <forward-request> policy element can appear within the <backend> section element.
                To apply a policy to the incoming request (before it is forwarded to the backend service), place a corresponding policy element within the <inbound> section element.
                To apply a policy to the outgoing response (before it is sent back to the caller), place a corresponding policy element within the <outbound> section element.
                To add a policy position the cursor at the desired insertion point and click on the round button associated with the policy.
                To remove a policy, delete the corresponding policy statement from the policy document.
                Policies are applied in the order of their appearance, from the top down.
            -->
                <policies>
                    <inbound>
                            <cors allow-credentials="true">
                                    <allowed-origins>
                                            <origin>https://portalapi.test.terra.fr</origin>
                                    </allowed-origins>
                                    <allowed-methods preflight-result-max-age="300">
                                            <method>*</method>
                                    </allowed-methods>
                                    <allowed-headers>
                                            <header>*</header>
                                    </allowed-headers>
                                    <expose-headers>
                                            <header>*</header>
                                    </expose-headers>
                            </cors>
                    </inbound>
                    <backend>
                            <forward-request />
                    </backend>
                    <outbound />
                </policies>
                    <policies>
                      <inbound />
                      <backend />
                      <outbound />
                      <on-error />
                    </policies>
          XML
  }

  hostname_configuration {
    developer_portal {
      host_name                    = var.APIM_apiproxy01_hostname_configuration_developer_portal_host_name
      key_vault_id                 = azurerm_key_vault_certificate.KVC_02.secret_id
      negotiate_client_certificate = false
    }

    management {
      host_name                    = var.APIM_apiproxy01_hostname_configuration_management_name
      key_vault_id                 = azurerm_key_vault_certificate.KVC_02.secret_id
      negotiate_client_certificate = false
    }

    proxy {
      default_ssl_binding          = true
      host_name                    = var.APIM_apiproxy01_hostname_configuration_proxy01_name
      key_vault_id                 = azurerm_key_vault_certificate.KVC_01.secret_id
      negotiate_client_certificate = false
    }

  }

  protocols {
    enable_http2 = false
  }

  security {
    enable_backend_ssl30      = false
    enable_backend_tls10      = false
    enable_backend_tls11      = false
    enable_frontend_ssl30     = false
    enable_frontend_tls10     = false
    enable_frontend_tls11     = false
    enable_triple_des_ciphers = false
  }

  sign_in {
      enabled = false
  }

  sign_up {
    enabled = true
    terms_of_service {
      consent_required = false
      enabled          = false
    }
  }

  virtual_network_configuration {
    subnet_id = azurerm_subnet.SUBNET_APIM01.id
  }
  identity {
    type = "UserAssigned"
    identity_ids = [
        azurerm_user_assigned_identity.UAI_hub02.id,
    ]
  }
  timeouts {
      create = "60m"
      update = "60m"
    }   
  tags = {
    OI = var.OI
  }
}
```

I tried to make a delivery of the API management by commenting on the "hostname_configuration" block, the deployment takes place however it falls into error:

```
Error: waiting for creation/update of API Management Service "AZRAPIM01" (Resource Group "rgprdhub0001"): Future#WaitForCompletion: context has been cancelled: StatusCode=202 -- Original Error: context deadline exceeded

  on network_prod.tf line 1636, in resource "azurerm_api_management" "APIM_apiproxy01":
1636: resource "azurerm_api_management" "APIM_apiproxy01" {
```

The message indicated is that this is due to the timeout which has exceeded the one indicated (60 minutes timeout indicated in the configuration).
However, from the Azure portal, the deployment continues and also goes into error:

```
Service activation failed. Please look at the details in Activity Log on the left side. In case you are deploying into VNET please make sure prerequisites are followed as described on https://aka.ms/apimvnet
```
```
Error code
InvalidOperation
Message
API Management service is activating
```

**Comment by yupwei68** [comment] 2020-07-29 05:04
Hi @aberva , I have confirmed with service team, the error message is by design, as retrieving hostname config certificate using user assigned identity is not yet supported.  Only System assigned identity is allowed, which you could refer to our TF test https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/apimanagement/tests/api_management_resource_test.go#L1025. 
Besides, separate steps are necessary in system assigned identity. First, create apim with system assigned identity. Second, assign the identity key vault access permission. Third, update the apim hostname config with key vault.

PS, virtual network needs to open port 3443 for enabling sign in or sign up refer to https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet#-common-network-configuration-issues

**Comment by aberva** [comment] 2020-07-31 10:33
Hi @yupwei68 ,

I notice that even doing it manually from the portal, it seems that by design it is the system assigned which is used to access the KeyVault.

Thanks for your help.

**Comment by honglim-bd** [comment] 2020-08-13 03:16
Hi @yupwei68,

Based on your comment,

> Besides, separate steps are necessary in system assigned identity. First, create apim with system assigned identity. Second, assign the identity key vault access permission. Third, update the apim hostname config with key vault.

How does the separate steps are possible by using Terraform script only? Any clue on how to achieve this?

**Comment by yupwei68** [comment] 2020-08-13 07:19
Sorry @honglim-bd , currently we don't have an automatic control  tool over the Terraform scripts. Normally we try to avoid the self-dependent relationship in Terraform resources, while this is a special case.

**Comment by evertonmc** [comment] 2021-01-14 08:12
> How does the separate steps are possible by using Terraform script only? Any clue on how to achieve this? I mean, how do I control the flow of the Terraform like step 1 do this, step 2 do that, and so on.
@honglim-bd 
azurerm_api_management > azurerm_key_vault_access_policy > azurerm_api_management_custom_domain

**Comment by tombuildsstuff** [comment] 2021-01-14 09:55
Closing since this appears to be resolved (by using the new split-out resource) - thanks @evertonmc

**Closed by tombuildsstuff** 2021-01-14 09:55 UTC
Labels: service/api-management
