### ISSUE TITLE
Support for additional arguements in subnet block of azurerm_virtual_network

### ISSUE THREAD

**Issue by techbunny** [terraform-providers/terraform-provider-azurerm#12169] opened 2021-06-11 00:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Subnets can be created in two ways: 1) in-line in the azurerm_virtual_network resource 2) with the azurerm_subnet resources.

The azurerm_subnet resource supports additional arguments, such as: "enforce_private_link_service_network_polices", "enforce_private_link_endpoint_network_policies", etc.

### New or Affected Resource(s)

* azurerm_virtual_network

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  resource_group_name = var.resource_group_name
  location            = var.location
  address_space       = [var.address_space]
  dns_servers         = var.dns_servers


  subnet {
    name           = var.default_subnet_name
    address_prefix = var.default_subnet_prefix
    security_group = azurerm_network_security_group.default_nsg.id
    enforce_private_link_endpoint_network_policies = true            <--- This doesn't work here.
  }
```

**Comment by tombuildsstuff** [comment] 2021-06-14 07:22
hi @techbunny 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #3917 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3917 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-06-14 07:22 UTC
Labels: duplicate, enhancement, service/virtual-networks
