### ISSUE TITLE
azurerm_healthcare_service complains about optional access_policy_object_ids argument

### ISSUE THREAD

**Issue by sschmeck** [terraform-providers/terraform-provider-azurerm#7292] opened 2020-06-11 07:11 UTC
The [documentation](https://www.terraform.io/docs/providers/azurerm/r/healthcare_service.html) of `azurerm_healthcare_service` describes the argument `access_policy_object_ids` as optional. It seems correct since the ARM template deployment works without the associated `accessPolicies` property.

But the source code in [ `azurerm\internal\services\healthcare\resource_arm_healthcare_service.go` ](https://github.com/terraform-providers/terraform-provider-azurerm/blob/085e1fb5562d6596552ff56560154457c7e3b6e3/azurerm/internal/services/healthcare/healthcare_service_resource.go#L73) declares that parameter as `Required`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.4
+ provider.azurerm v2.13.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_healthcare_service`

### Terraform Configuration Files

```hcl
resource "azurerm_healthcare_service" "hcs" {
  name                = "sample-hcs"
  resource_group_name = "sample-resource-group"
  location            = "westus2"
  kind                = "fhir-R4"
  cosmosdb_throughput = "2000"

  // should be optional
  //access_policy_object_ids = ["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"]
}
```

### Expected Behavior

`terraform apply` should succeed.

### Actual Behavior

`terrafrom apply` complains about the missing argument.

```
Acquiring state lock. This may take a few moments...

Error: Missing required argument

  on ..\..\infrastructure\main.tf line 8, in resource "azurerm_healthcare_service" "hcs":
   8: resource "azurerm_healthcare_service" "hcs" {

The argument "access_policy_object_ids" is required, but no definition was
found.

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-06-11 08:40
hi @sschmeck 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7281 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7281 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-11 08:40 UTC
