### ISSUE TITLE
azurerm_postgresql_server resource timing out when infrastructure_encryption_enabled set to true

### ISSUE THREAD

**Issue by kuhlman-labs** [terraform-providers/terraform-provider-azurerm#7413] opened 2020-06-19 18:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.15.0
### Affected Resource(s)

* 'azurerm_postgresql_server'

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_postgresql_server" "example" {
  name                = "example-psqlserver"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"

  sku_name   = "GP_Gen5_4"
  version    = "10"
  storage_mb = 10240

  infrastructure_encryption_enabled = true
  backup_retention_days             = 7
  geo_redundant_backup_enabled      = true
  auto_grow_enabled                 = true

  public_network_access_enabled    = false
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"

  timeouts {
      create = "60m"
  }
}
```

### Expected Behavior

Apply to complete.

### Actual Behavior

After 20 minutes:
Error: waiting for creation of PostgreSQL Server "example-psqlserver" (Resource Group "example-resources"): Code="OperationTimedOut" Message="The operation timed out and automatically rolled back. Please retry the operation."

  on Main.tf line 10, in resource "azurerm_postgresql_server" "example":
  10: resource "azurerm_postgresql_server" "example" {
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This only occurs with the `infrastructure_encryption_enabled` is set to true, otherwise resource gets created in ~2minutes
### References

* #0000

**Comment by yupwei68** [comment] 2020-06-22 06:48
Duplicated of https://github.com/terraform-providers/terraform-provider-azurerm/issues/7043

**Comment by mybayern1974** [comment] 2020-06-22 08:45
hi  @kuhlman-labs 

Thanks for opening this issue! Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #7043; Would you mind subscribing to #7043 for updates? 

In addition, by going through the context in #7043, it mentioned the cause is at upstream Microsoft while Microsoft contact mentioned the wanted feature is still in development. So I'm sorry to feel what is wanted in terraform here may be not made in short term.

Feel free to reopen if you believe what is expected in this issue is not the same as the above.

Thanks!

**Closed by mybayern1974** 2020-06-22 08:45 UTC
Labels: duplicate, service/postgresql
