### ISSUE TITLE
azurerm_policy_assignment fails to permission managed identity

### ISSUE THREAD

**Issue by scollins87** [terraform-providers/terraform-provider-azurerm#6486] opened 2020-04-15 14:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.0.0
+ provider.template v2.1.2

### Affected Resource(s)

azurerm_policy_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_policy_assignment" "nsg-diags-assignment" {
  name                 = "test-apply-nsg-logs"
  scope                = "/subscriptions/${var.subscription_id}"
  policy_definition_id = azurerm_policy_definition.deploy-nsg-diags.id
  description          = "Applies diagnostic settings to enable NSG logs and send to Log Analytics Workspace"
  display_name         = "Apply NSG Diagnostics"
  location             = "uksouth"
  identity { type = "SystemAssigned" }
  parameters = <<PARAMETERS
        {
            "logAnalytics": {
                "value" : "<workspace_id>"
            }
        }
        PARAMETERS
}
```
The above will create a policy assignment and associated managed identity required to perform the actions specified in the "deployIfNotExists" in the JSON file at: 

https://github.com/scollins87/az-policy-nsg-diagnostics/blob/master/json/policyrule.json

### Debug Output

https://github.com/scollins87/az-policy-nsg-diagnostics/blob/master/terraform.txt

### Expected Behaviour

When the policy assignment is made, a managed identity should be created and granted permission to deploy missing resources in line with the deployIfNotExists condition

### Actual Behaviour

Policy definition is created and assigned, but the managed identity created is not granted any permissions, so remediation task cannot be created without manual intervention.

### Steps to Reproduce

1.  Clone https://github.com/scollins87/az-policy-nsg-diagnostics/
2. Create policy definition and policy assignment
3. Login to Azure portal and go to Policy > Remediation
4. Create a remediation task for the policy - Note message "The managed identity for this assignment does not have the appropriate permissions to remediate these resources. To add these permissions, go to the Edit Assignment page for this Policy and re-save it."
5. Edit policy definition > Remediation > Note the blank field under "The identity currently has the following permissions"

**Comment by matt-FFFFFF** [comment] 2020-06-04 23:13
I have this but fixed it with the below - it's not much extra work.

```terraform
resource "azurerm_role_assignment" "assignment" {
  scope                = azurerm_policy_assignment.policy.scope
  role_definition_name = "Contributor"
  principal_id         = azurerm_policy_assignment.policy.identity[0].principal_id
}
```

**Comment by fluffy-cakes** [comment] 2020-06-25 08:50
so.... any fix on this? i have the same issue. not too sure the fix above will work for me as i want to scope down the blast radius of this tmp created managed identity.

**Comment by tombuildsstuff** [comment] 2020-06-25 09:01
hi @scollins87 

Thanks for opening this issue.

Taking a look into this the Terraform Configuration posted above will only create a Managed Identity for the Policy Assignment (as per the Azure API), it doesn't grant it access to any resources (which as in @matt-FFFFFF's comment, needs to be done via the `azurerm_role_assignment` resource).

Since this appears to be working as intended (since this is the behaviour of the Azure API) I'm going to close this issue for the moment - but as @matt-FFFFFF has mentioned you can grant the newly created Managed Identity access to the roles/resources necessary using the `azurerm_role_assignment` resource.

Thanks!

**Closed by tombuildsstuff** 2020-06-25 09:01 UTC
Labels: question, service/policy

**Comment by fluffy-cakes** [comment] 2020-06-25 09:08
@tombuildsstuff  So that policy assignment is too broad of a brush stroke. Especially since I scope down the roles access;

```
            "roleDefinitionIds": [
                "/providers/Microsoft.Authorization/roleDefinitions/92aaf0da-9dab-42b6-94a3-d43ce8d16293",
                "/providers/Microsoft.Authorization/roleDefinitions/f526a384-b230-433a-b45c-95f59c4a2dec"
            ],
```
You can see the roles here; https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles

Standard m$ roles. What do you suppose I do in this instance?

**Comment by tombuildsstuff** [comment] 2020-06-25 09:14
@fluffy-cakes unfortunately since the permissions required vary depending on your usage/scenario - that's not something we're able to provide specific advice on - however that information should be found in the Microsoft Documentation as you've linked too (or potentially Microsoft Support)

**Comment by fluffy-cakes** [comment] 2020-06-25 09:14
@tombuildsstuff To give you an idea, here's a screen shot of editing that policy after that error.
![myPolicyName](https://user-images.githubusercontent.com/32635002/85691778-b5eccc80-b6cc-11ea-8f6e-45d9b37bd620.png)

**Comment by fluffy-cakes** [comment] 2020-06-25 09:19
Whether this is a Microsoft issue or a Terraform issue, I am not too sure (probably leaning towards m$), but I do feel it's a bit pointless scoping the policy to specific roles and deploying the definition, but not being able to assign it properly without manual intervention, or giving the MSI too much access.

What's the point of coding the assignment if it won't assign properly, and/or, what's the point of scoping down the access if you gotta give it more access?
