### ISSUE TITLE
Error building AzureRM Client: No (unexpired) Authorization Tokens were found (User credentials)

### ISSUE THREAD

**Issue by arcotek-ltd** [terraform-providers/terraform-provider-azurerm#2370] opened 2018-11-21 12:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.19.0
```

### Affected Resource(s)

All

### Terraform Configuration Files

NA

```hcl
NA
```

### Debug Output
[Gist](https://gist.github.com/arcotek-ltd/a2e980d20ddce1eaecabe0350bb3da7a)

### Expected Behavior

Erm, show plan?

### Actual Behavior

```
Error: Error refreshing state: 1 error(s) occurred:

* provider.azurerm: Error building AzureRM Client: No (unexpired) Authorization Tokens were found - please re-authenticate using `az login`.
```

### Steps to Reproduce

1. `terraform plan -var-file="shrg.tfvars"`

### Important Factoids

I am authenticating using my user account as opposed to a service principal. It was working and now it's not. I have deleted .terraform.

What caused my issue was to install the new [AZ PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azurermps-6.13.0), which I presume, interferes with the already-installed AZ CLI. I am waiting for Microsoft to respond [here](https://github.com/Azure/azure-docs-powershell/issues/827). My AZ CLI is now broken and uninstall / reinstall does not fix AZ CLI.

If we assume that the AZ PowerShell cmdlets install is to blame, then I believe there is a difference in the token that is generated, and my suspicion is that Terraform cannot handle this token.  The log suggests that the token has expired, but it has not.

New AZ PS cmdlets that I run to authenticate:
```
Remove-AZAccount #Get rid of any tokens that may exist.

Login-AZAccount #Use web browser, pasting in code generated on cmdline

Set-AZContext -SubscriptionName "MySubscription"

Get-AZContext #Only "MySubscription", authenticated as my user is return
```

I know I'll be told to use the SP, and we do in production, but this is for quickly testing, without dropping AD application credentials that run the risk of ending up in VCS. The point is that AZ CLI works but the new AZ PS cmdlets do not. I am sure it's a small issue with the token format.

In addition, MS are replacing the old AzureRM PS cmdlets with AZ PS and if indeed AZ CLI and AZ PS cannot coexist then this will break TF AZ CLI authentication. 

### References

* #0000

**Comment by tombuildsstuff** [comment] 2018-11-21 13:05
hi @arcotek-ltd 

Thanks for opening this issue :)

Taking a quick look into this it appears would be a duplicate of #502 - essentially Terraform can't refresh the access token since we don't own that file (and thus don't want to break the Azure CLI). Out of interest - does this work if you logout and then log back in using the Azure CLI?

Thanks!

**Comment by arcotek-ltd** [comment] 2018-11-21 13:16
Hi @tombuildsstuff,
Thanks for your reply. I understand what you are saying and it's a good plan (no pun intended), but I am (hopefully) clearing and logging out of Azure, with the `Remove-AzAccount` and then creating a new token, which according to TF has expired, yet is was created within a minute of running `terraform plan...`

As I said, my immediate thought is that there is a slight difference in the token generated, between AZ CLI and AZ PS. I don't know enough to prove that theory, but I can run AZ commands against Azure after logging in, using the method detailed above.

Thanks again

**Comment by tombuildsstuff** [comment] 2018-11-21 14:48
hey @arcotek-ltd

Thanks for getting back to us here. Whilst there may be variations between the Azure CLI and Azure PowerShell - unfortunately the Azure PowerShell isn’t supported (we only support v1/v2 of the Azure CLI at this time) - as such we can’t provide support for this. It’s possible that PowerShell may be storing the timezone differently to the Azure CLI (and as such it may be possible to work around this by setting the relevant environment variable) - however since this isn’t officially supported (and we have no plans to support this) I don’t think there’s much we can do here.

Instead it should be possible to achieve this using the Azure CLI (or as you’ve mentioned a service principal) - which are the main supported authentication methods at this time. As this issue is about functionality we have no plans to support (since it’s possible to achieve this using the Azure CLI) - I’m going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2018-11-21 14:48 UTC
Labels: authentication, question
