### ISSUE TITLE
When re-running deployment, Terraform attempts to recreate the function app plan despite already existing

### ISSUE THREAD

**Issue by jjgriff93** [terraform-providers/terraform-provider-azurerm#5971] opened 2020-03-03 16:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: `v0.12.18`
AzureRM provider version: `1.40.0`

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "trafficdata" {
  name                = "plan-${var.appname}-traffic-${var.environment}"
  resource_group_name =  azurerm_resource_group.trafficdata.name
  location            =  var.location
  kind                =  "linux"
  reserved            =  true

  sku {
    tier = "Basic"
    size = "B1"
  }
}
```

### Debug Output

https://gist.github.com/jjgriff93/5836c4a6ea2c4fea69e7cc223b003771

### Expected Behavior

Terraform should have detected existing App Service Plan and not recreated

### Actual Behavior

Despite the configuration not changing, Terraform detects the existing App Service Plan kind as Linux instead of Function App and thus tears down existing environment to replace with the same

### Steps to Reproduce

1. Create a Function App tf similar to the one above for the App Service Plan component and set the `kind` to `functionapp`
2. `terraform apply`
3. `terraform apply` again

* #0000

**Comment by Bessonov** [comment] 2020-03-11 22:58
@jjgriff93 duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/4396?

**Comment by jjgriff93** [comment] 2020-03-14 20:54
@Bessonov yes looks to be with slightly different environment configuration

**Comment by Duchynko** [comment] 2020-05-15 11:17
#6931 might be related

**Comment by neil-yechenwei** [comment] 2020-07-17 01:42
Thanks for opening this issue. If you want to set kind as non-linux such as functionapp, you have to set reserved property as false. You can refer terraform [doc ](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#kind)and azure [doc](https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/createorupdate#request-body).

**Comment by katbyte** [comment] 2021-06-23 19:33
I'm going to close this as its been nearly a year, please do let us know if this is still an issue for you!

**Closed by katbyte** 2021-06-23 19:33 UTC
Labels: bug, service/app-service, waiting-response
