### ISSUE TITLE
azurerm_virtual_hub

### ISSUE THREAD

**Issue by mybayern1974** [terraform-providers/terraform-provider-azurerm#4158] opened 2019-08-27 09:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support a new Azure resource. 

### New or Affected Resource(s)

* azurerm_virtual_hub

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_hub" "test" {
    # Required
    name                        = "vhub1"
    location                    = "West US 2"
    resource_group_name         = ""
    address_prefix              = ""
    virtual_wan_id              = azurerm_virtual_wan.test.id

    # Optional
    express_route_gateway_id    = azurerm_virtual_network_gateway.test2.id
    p2s_vpn_gateway_id          = azurerm_p2s_vpn_gateway.test.id
    route_table_route           = {             # configuration can contain multiple of these
        address_prefixes            = [""]
        next_hop_ip_address         = ""
    }
    virtual_network_connection  = {             # configuration can contain multiple of these
        name                                        = ""
        allow_hub_to_remote_vnet_transit            = true
        allow_remote_vnet_to_use_hub_vnet_gateways  = false
        enable_internet_security                    = true
        remote_virtual_network_ids                  = [azurerm_virtual_network.test.id]
    }
    vpn_gateway_id              = azurerm_virtual_network_gateway.test.id
    tags = {
        
    }
}
```

**Comment by tombuildsstuff** [comment] 2019-08-27 09:50
hi @mybayern1974 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3279 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3279 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-27 09:50 UTC

**Comment by mybayern1974** [comment] 2019-08-28 06:45
@tombuildsstuff , yes your suggestion makes sense!
