### ISSUE TITLE
azurerm_monitor_metric_alert not supporting multiples scopes (azure gov)

### ISSUE THREAD

**Issue by Danielperga97** [terraform-providers/terraform-provider-azurerm#6615] opened 2020-04-24 15:24 UTC
**Community Note**
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Description**
Hi, i'm trying to create an alert to monitor multiple database resources. Based on the documentation:
![image](https://user-images.githubusercontent.com/21698890/80229000-6e3abd80-8615-11ea-92b5-87b69a697098.png)
The scopes are supposed to be a set of strings with multiple ids, but when I try using more than one id I receive the following error:
![image](https://user-images.githubusercontent.com/21698890/80230068-038a8180-8617-11ea-8265-4d326fb49af6.png)

my configuration looks as follows: 
![image](https://user-images.githubusercontent.com/21698890/80229228-bc4fc100-8615-11ea-83ef-1b69b8cd3231.png)
already tried with and without the toset.

Afected resources:
azurerm_monitor_metric_alert

**Comment by yupwei68** [comment] 2020-04-26 08:27
Hi @Danielperga97, Thanks for opening this issue. We might fix it later by opening this restriction of scope count. But in your case, your `redis cache` is still not supported for multiple resources alerts in metric alterts. Please refer to [the resouce types supported mulitple resources alerts](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-near-real-time#metrics-and-dimensions-supported).

**Comment by yupwei68** [comment] 2020-04-26 08:53
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/3719

**Comment by mybayern1974** [comment] 2020-04-29 09:55
Hi @Danielperga97 , would you mind we close this issue and instead to have the [#3719](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3719) track?

**Closed by mybayern1974** 2020-04-29 09:55 UTC
