### ISSUE TITLE
Terraform failing to pull output from ARM template

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1024] opened 2018-03-23 15:56 UTC
Have a config that uses the azurerm_template_deployment resource to provision an App Service Plan into an App Service Environment v2.  Using the azurerm_template_deployment resource because the azurerm_app_service_plan resource returns the 201 unhandled success code.  As part of the ARM template, I am trying to output the Resource ID of the App Service Plan and store it in the state file.  The output from the ARM template works fine (I tested it using Visual Studio to deploy the template) but Terraform is unable to handle the output for some reason.

### Terraform Version
`Terraform v0.11.3`

### Affected Resource(s)
List of effected resources:
- azurerm_template_deployment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Output section of ARM template:
```hcl
    "outputs": {
      "aspId": {
        "type": "string",
        "value": "[resourceId('Microsoft.Web/serverfarms', parameters('asp1_name'))]"
      }
    }
```
Output declaration in Terraform config:
```hcl
output "aspResourceId" {
  value = "${azurerm_template_deployment.asp1.outputs["aspId"]}"
}
```

### Expected Behavior
Expected behavior is that the deployment would complete successfully and the Resource ID of the App Service Plan would be written to the state file.

### Actual Behavior
When running `terraform plan`, the error below is generated:
```hcl
Error: Error refreshing state: 1 error(s) occurred:

* output.aspResourceId: At column 43, line 1: map "azurerm_template_deployment.asp1.outputs" does not have any elements so cannot determine type. in:

${azurerm_template_deployment.asp1.outputs["aspId"]}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
When running the ARM template from Visual Studio, the out generated is below:
```hcl
Outputs: {[aspId, Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable]}
Outputs:         Value
               ==========
               /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Web/hostingEnvironments/<ase_name>
```

**Comment by tombuildsstuff** [comment] 2018-04-16 11:40
hi @Phydeauxman 

Thanks for opening this issue - apologies for the delayed response here!

This is a duplicate of #578 in that the way to reference outputs in maps changed in Terraform 0.11, which is detailed in [the upgrade guide](https://www.terraform.io/upgrade-guides/0-11.html#error-checking-for-output-values) and can now be accessed like so:

```
output "app_service_plan_id" {
  value = "${lookup(azurerm_template_deployment.asp1.outputs, "aspId")}"
}
```

Thanks!

**Closed by tombuildsstuff** 2018-04-16 11:40 UTC
Labels: service/deployments
