### ISSUE TITLE
Support for associating NSG with subnet when creating VNET/Subnet

### ISSUE THREAD

**Issue by bramvdklinkenberg** [terraform-providers/terraform-provider-azurerm#8288] opened 2020-08-28 19:44 UTC
### Description

It would be nice when creating a vnet (incl subnet) or subnet you can associate a NSG with the subnet directly, instead of having create a separate [resource](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html) for the association of a subnet with a NSG.

This is possible with the [ARM](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks) template for a VNET.

The reason I would like this is because I have (well had now) an Azure Policy that enforces a NSG on a Subnet. The policy denies the creation of a subnet if there is no NSG associated with it.

### New or Affected Resource(s)

* azurerm_virtual_network
* azurerm_subnet

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network" "example" {
  name                = "virtualNetwork1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
    network_security_group = azurerm_network_security_group.example.id
  }
}
```

Or

```hcl
resource "azurerm_subnet" "example" {
  name                 = "testsubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
  network_security_group = azurerm_network_security_group.example.id
}
```

**Comment by yupwei68** [comment] 2020-08-31 02:07
Hi @bramvdklinkenberg , thanks for opening this issue. The reason why we need a separate `azurerm_subnet_network_security_group_association` instead a field in `azurerm_subnet` is that, in disassociation for example (destroy the NSG and update the subnet), Terraform's practice will destroy the resource NSG before updating the subnet. Thus, it'll raised a service error that the NSG cannot be deleted because it's in use. 
Instead, you could use our registered module to implement your expectation. Please try https://github.com/Azure/terraform-azurerm-vnet if you would like.

**Comment by tombuildsstuff** [comment] 2020-08-31 06:05
hi @bramvdklinkenberg 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8261 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8261 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-31 06:05 UTC
Labels: duplicate, service/subnets, service/virtual-networks
