### ISSUE TITLE
Support for [azurerm_batch_account]

### ISSUE THREAD

**Issue by iasha102** [terraform-providers/terraform-provider-azurerm#11271] opened 2021-04-09 07:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to the Azure Documentation Batch Account has different types of identity to by Assigned, 
at the moment terraform provider don't support declaration of the identity.

We have two types of the identities:
`UserAssigned` 
`SystemAssigned`

we can specify one of them either `None`

Default is `None` 
### New or Affected Resource(s)

* azurerm_batch_account

### Potential Terraform Configuration

```hcl
resource "azurerm_batch_pool" "pool" {
  identity {
    type = "SystemAssigned"
  }
}
```
```hcl
resource "azurerm_batch_pool" "pool" {
  identity {
    type = "UserAssigned"
    userAssignedIdentities = ["armid1","armid2"]
  }
}
```
### References

* https://docs.microsoft.com/en-us/rest/api/batchmanagement/batchaccount/create#userassignedidentities

**Comment by magodo** [comment] 2021-07-19 08:13
Is this duplicate to #8532?

**Comment by tombuildsstuff** [comment] 2021-07-19 10:30
Duplicate of #8532, thanks @magodo

**Closed by tombuildsstuff** 2021-07-19 10:30 UTC
Labels: duplicate, enhancement, service/batch
