### ISSUE TITLE
azurerm_cognitive_account fails to create Bing.Search.v7

### ISSUE THREAD

**Issue by jmyers82** [terraform-providers/terraform-provider-azurerm#9635] opened 2020-12-02 23:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
AzureRM v2.38.0

### Affected Resource(s)

azurerm_cognitive_account    - kind = "Bing.Search.v7" 

### Terraform Configuration Files
```hcl
resource "azurerm_cognitive_account" "luis_bing_spellcheck" {
    name                = "bingspellcheck2020"
    location            = "global"
    resource_group_name = "dev-rg-test
    kind                = "Bing.Search.v7"
    sku_name            = "S2"   

    tags = {}
}
```
### Debug Output

Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ApiSetDisabledForCreation" Message="It's not allowed to create new accounts with type 'Bing.Search.v7'."

### Expected Behaviour

Create a cognitive search account. 

### Work Around
Used azurerm_resource_group_deployment to deploy the ARM code. 

```hcl
resource "azurerm_resource_group_template_deployment" "cog_bing" {
    name                = "bing_arm"
    resource_group_name = "dev-rg-test"
    deployment_mode     = "Incremental"
	template_content	= file("cog_bing.json")
	parameters_content	= jsonencode({
		name	= {value = "bing-look-it-works"}
		sku	    = {value = "S2"}
	})
}
```
the JSON file contains the ARM template downloaded while deploying from the portal.

```json
{
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "String"
        },
        "sku": {
            "type": "String"
        }
    },
    "resources": [
        {
            "apiVersion": "2020-06-10",
            "name": "[parameters('name')]",
            "location": "global",
            "type": "Microsoft.Bing/accounts",
            "kind": "Bing.Search.v7",
            "sku": {
                "name": "[parameters('sku')]"
            },
            "properties": {
                "statisticsEnabled": false
            }
        }
    ]
}
```

**Comment by tombuildsstuff** [comment] 2020-12-03 10:47
hi @jmyers82 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9102 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9102 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-12-03 10:47 UTC
Labels: breaking-change, duplicate, service/cognitive-services, upstream-microsoft

**Comment by jmyers82** [comment] 2020-12-04 00:15
@tombuildsstuff thanks for the update and that is fine.  My searches did not turn up that existing issue.  Thanks.
