### ISSUE TITLE
API Manager disable_frontend_ssl30, disable_frontend_tls10, disable_frontend_tls11 sets wrong default

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3663] opened 2019-06-14 12:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

version = "~> 1.23"

### Affected Resource(s)

azurerm_api_management

### Terraform Configuration Files

resource "azurerm_api_management" "coyote_api_management" {
//any config that does not include disable_frontend_ssl30, disable_frontend_tls10, disable_frontend_tls11
}

### Expected Behavior
Security settings: disable_frontend_ssl30, disable_frontend_tls10, disable_frontend_tls11 are set to false by default as specified by the terraform documentation.

### Actual Behavior

These settings were set to true

### Steps to Reproduce

Create an API Manager instance without the given attributes defined/values set.

### References

https://www.terraform.io/docs/providers/azurerm/r/api_management.html#disable_backend_ssl30

* #0000

**Comment by NickMetz** [comment] 2019-06-14 14:51
Hi @cdesewell,
it seems this is a duplicate of #3125, waiting for feedback from @ReenuSaluja there.

**Comment by katbyte** [comment] 2019-07-09 06:33
Hi @cdesewell,

Going to close this is a duplicate of #3125.

**Closed by katbyte** 2019-07-09 06:33 UTC
Labels: bug, duplicate, service/api-management
