### ISSUE TITLE
Unexpected recreate of Application Insights application_type = "Other" -> "other" when importing existing resource to tfstate, or when upgrading to 2.0.0

### ISSUE THREAD

**Issue by hawkism** [terraform-providers/terraform-provider-azurerm#6259] opened 2020-03-25 19:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.12.24
Provider: 2.0.0 or greater

### Affected Resource(s)

azurerm_application_insights

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=2.0.0"
  subscription_id = var.subscriptionId 
  tenant_id       = var.tenantId
}
resource "azurerm_resource_group" "AAInfraSCRG01" {
  name = "AAInfraSCRG01"
  location = var.location
  tags = {
    terraformVersion = "0.12"
 }
}
resource "azurerm_application_insights" "AASCPANAIO1" {
  name                = "AASCPANAIO1"
  location            = azurerm_resource_group.AAInfraSCRG01.location
  resource_group_name = azurerm_resource_group.AAInfraSCRG01.name
  application_type    = "Other"
  sampling_percentage = 0
}
variable "subscriptionId" {
    default = "00000000-0000-0000-0000-000000000000"
}
variable "tenantId" {
    default = "00000000-0000-0000-0000-000000000000"
}
variable "location" {
    default = "South Central US"
}
```

### Expected Behavior
application_type  = "Other" should be accepted since import has this in the tfstate file as well.
and
No redeploy of Application Insights

### Actual Behavior
Error: expected application_type to be one of [web other java MobileCenter phone store ios Node.JS], got Other

  on main.tf line 17, in resource "azurerm_application_insights" "AASCPANAIO1":
  17: resource "azurerm_application_insights" "AASCPANAIO1" {

or, when line 17 of code is changed to "other"

Unexpected replacement of item:
~ application_type                      = "Other" -> "other" # forces replacement

### Steps to Reproduce

Import an  azurerm_application_insights create previously with azurerm 1.x or upgrade from 1.x to 2.0.0 with an azurerm_application_insights item created with application_type = "Other" from 1.x.

Capitalisation was changed of application_type vs. what was deployed previously.

**Comment by StefanSchoof** [comment] 2020-03-26 07:34
This sounds similar to #5902

**Comment by tombuildsstuff** [comment] 2020-03-26 07:43
@StefanSchoof thanks for the heads up - agreed - I'm going to close this as a duplicate of #5902 - would you mind subscribing to that issue for updates @hawkism?

**Closed by tombuildsstuff** 2020-03-26 07:43 UTC
Labels: bug, service/application-insights
