### ISSUE TITLE
2.32 broke azurerm_mssql_server and azurerm_mssql_database -"Invalid parameter 'storageEndpoint'

### ISSUE THREAD

**Issue by dlm69** [terraform-providers/terraform-provider-azurerm#8954] opened 2020-10-20 11:11 UTC
When creating a new resource whether **azurerm_mssql_server** or **azurerm_mssql_database** you get an error about "Invalid parameter 'storageEndpoint'. Value should be a blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net).". 

If you then include the **azurerm_mssql_server_extended_auditing_policy** or **azurerm_mssql_database_extended_auditing_policy** you still get the same error. However you can add the (soon to be deprecated) extended_auditing_policy block on the **azurerm_mssql_server** and **azurerm_mssql_database** and everything works.

**Comment by tombuildsstuff** [comment] 2020-10-20 11:29
hi @dlm69 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8915 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8915 for updates?

Thanks!

**Closed** 2020-10-20 11:30 UTC
Labels: duplicate, service/mssql, upstream-microsoft
