### ISSUE TITLE
State error while creating eventhub_namespace_authorization_rule

### ISSUE THREAD

**Issue by mkjoerg** [terraform-providers/terraform-provider-azurerm#7171] opened 2020-06-02 10:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26

### Affected Resource(s)

* `azurerm: 2.11.0`
* `azurerm: 2.12.0`

### Terraform Configuration Files

resource group exists already, left it out in the example.

```hcl
resource "azurerm_eventhub_namespace" "eh_namespace" {
  name                      = "${local.prefix}-${var.env}-ehns"
  location                  = var.region
  resource_group_name       = azurerm_resource_group.process_rg.name
  sku                       = "Standard"
  capacity                  = 20
  auto_inflate_enabled      = true
  maximum_throughput_units  = 20
  tags = local.default_tags
}
resource "azurerm_eventhub_namespace_authorization_rule" "eh_authorization_rule" {
  name                = "spark-policy"
  namespace_name      = azurerm_eventhub_namespace.eh_namespace.name
  resource_group_name = azurerm_resource_group.process_rg.name
  listen = true
  send   = true
  manage = false
}
```

### Expected Behavior

Authorization rule should have been created

### Actual Behavior

```log
ocess-int-rg/providers/Microsoft.EventHub/namespaces/process-int-ehns]
module.process-euw.azurerm_eventhub_namespace_authorization_rule.eh_authorization_rule: Creating...

Error: Error making Read request on Azure EventHub Authorization Rule : eventhub.NamespacesClient#GetAuthorizationRule: Invalid input: autorest/validation: validation failed: parameter=authorizationRuleName constraint=MinLength value="" details: value length must be greater than or equal to 1

  on modules/process/main.tf line 131, in resource "azurerm_eventhub_namespace_authorization_rule" "eh_authorization_rule":
 131: resource "azurerm_eventhub_namespace_authorization_rule" "eh_authorization_rule" {
```

After the error occured, we could not run apply or destroy successfully, only deleting the state for the consumer groups manually resolved the issue, but creating them was impossible. After going back to version 2.10.0 everything worked smooth again.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Regular Azure Public Cloud

### References

* #0000

**Comment by mybayern1974** [comment] 2020-06-03 05:33
hi  @mkjoerg 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of [#7162](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7162) - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to [#7162](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7162) for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-06-03 05:33 UTC
Labels: duplicate, service/event-hubs

**Comment by neil-yechenwei** [comment] 2020-06-03 05:43
Thanks for opening this issue. Seems this issue has been fixed in terraform-providers/terraform-provider-azurerm#7122. I assume it should be available in next version.
