### ISSUE TITLE
AzureRM TXT record do not support more than 255 characters

### ISSUE THREAD

**Issue by jonathanlavoie-optel** [terraform-providers/terraform-provider-azurerm#2826] opened 2019-02-01 16:18 UTC
AzureRM TXT record do not support more than 255 characters

**My code:**
`resource "azurerm_dns_txt_record" "google" {
  name                = "google._domainkey"
  zone_name           = "${azurerm_dns_zone.module.name}"
  resource_group_name = "${azurerm_resource_group.module.name}"
  ttl                 = "${var.ttl}"

  record {
    value = "v=DKIM1; k=rsa; p=NqqBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIt7Hs45AQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohs6agccc0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo8tOQyohTccButrh+sUilXtlAhwXQnCzlcakyANB1WPSeAvmWKfkmif/0BfcvbxbSf5oycs/7inV5cTtmhEdfYkogmwFh+RasHI8rlXZy5MkjuOB1TgplQ8upL046KM62Cq5GKqZ1R8lpkrzPPZZoAFwIDAQAB"
  }
}`

**Terraform error:**
`Error: Error applying plan:

1 error(s) occurred:

* module.behaviori_com.azurerm_dns_txt_record.google: 1 error(s) occurred:

* azurerm_dns_txt_record.google: dns.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The value 'v=DKIM1; k=rsa; p=NqqBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIt7Hs45AQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohs6agccc0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo8tOQyohTccButrh+sUilXtlAhwXQnCzlcakyANB1WPSeAvmWKfkmif/0BfcvbxbSf5oycs/7inV5cTtmhEdfYkogmwFh+RasHI8rlXZy5MkjuOB1TgplQ8upL046KM62Cq5GKqZ1R8lpkrzPPZZoAFwIDAQAB' for the TXT record is not valid."
`

**Comment by tombuildsstuff** [comment] 2019-02-01 17:04
hi @jonathanlavoie-optel 

Thanks for opening this issue :)

The error message you're seeing here is being returned from the Azure API - which would suggest this configuration isn't valid; taking a quick look into this when configuring this TXT record in the portal it appears this gets split into two records (the first being 255 characters long, the other being 155 characters) - here's the API response from that:

```json
{
    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-manual/providers/Microsoft.Network/dnszones/mydomain.com/TXT/example",
    "name": "example",
    "type": "Microsoft.Network/dnszones/TXT",
    "etag": "8368b190-538c-4241-9169-2b8a61e40670",
    "properties": {
        "fqdn": "example.mydomain.com.",
        "TTL": 7200,
        "TXTRecords": [
            {
                "value": [
                    "v=DKIM1; k=rsa; p=NqqBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIt7Hs45AQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohs6agccc0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo8t",
                    "OQyohTccButrh+sUilXtlAhwXQnCzlcakyANB1WPSeAvmWKfkmif/0BfcvbxbSf5oycs/7inV5cTtmhEdfYkogmwFh+RasHI8rlXZy5MkjuOB1TgplQ8upL046KM62Cq5GKqZ1R8lpkrzPPZZoAFwIDAQAB"
                ]
            }
        ],
        "targetResource": {},
        "provisioningState": "Succeeded"
    }
}
```

As mentioned above it appears that DNS TXT records need to be split into 255 character sets - as such it should be possible to reproduce this in Terraform like so:

```hcl

resource "azurerm_dns_txt_record" "google" {
  name                = "google._domainkey"
  zone_name           = "${azurerm_dns_zone.module.name}"
  resource_group_name = "${azurerm_resource_group.module.name}"
  ttl                 = "${var.ttl}"

  record {
    value = "v=DKIM1; k=rsa; p=NqqBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIt7Hs45AQEAu6eALKOV7VkAS75B9tmQQnobrG6f4sKb7x+DlFsBehUx3txjIQscAiMz7IAfohs6agccc0t6DLndt9humMV7CGhOjm84ZufzPPSJT1MZHPh3IhEeW2ktxhFqI88RSzzACGyWSOKhymBbbbNI68nglYtG1OIQ0ZIO1EA/gu63RmroyG2iwxxbX2fG4QGRPvo8t"
  }

  record {
    value = "OQyohTccButrh+sUilXtlAhwXQnCzlcakyANB1WPSeAvmWKfkmif/0BfcvbxbSf5oycs/7inV5cTtmhEdfYkogmwFh+RasHI8rlXZy5MkjuOB1TgplQ8upL046KM62Cq5GKqZ1R8lpkrzPPZZoAFwIDAQAB"
  }
}
```

Would you be able to take a look and see if that works for you?

Thanks!

**Comment by tombuildsstuff** [comment] 2019-02-04 10:08
@jonathanlavoie-optel 

> On Azure, it create 2 different records. So, the value will not be read as expected by mail servers. I tried to apply it as a list and also as 2 vars (vars+vars). Not working.

The Azure Portal also splits this value into multiple fields (which is where the API response above comes from) - so unfortunately this appears to be a question around the behaviour of the Azure API.

Since that's a specific question regarding the DNS API (and not Terraform) - I'm going to close this issue and suggest instead [opening an issue on the Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/issues) about this - where a member of the DNS Team should be able to answer if splitting this key into multiple fields should work with regards to DKIM.

Thanks!

**Closed by tombuildsstuff** 2019-02-04 10:08 UTC
Labels: question, service/dns
