### ISSUE TITLE
"Resource already exists" on azurerm_template_deployment failure

### ISSUE THREAD

**Issue by KSiig** [terraform-providers/terraform-provider-azurerm#7100] opened 2020-05-27 04:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_template_deployment`

### Terraform Configuration Files

```hcl
resource "azurerm_template_deployment" "func_consent_key" {
  name = "getBannerCacheEventGridKey"
  parameters = {
    "functionApp" = azurerm_function_app.bannercache.name
  }
  resource_group_name = azurerm_resource_group.main.name
  deployment_mode     = "Incremental"

  template_body = <<BODY
  {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": { 
      "functionApp": {"type": "string", "defaultValue": ""}
    },
    "variables": {
      "functionAppId": "[resourceId('Microsoft.Web/sites', parameters('functionApp'))]"
    },
    "resources": [],
    "outputs": {
        "functionkey": {
            "type": "string",
            "value": "[listkeys(concat(variables('functionAppId'), '/host/default'), '2018-11-01').systemKeys.eventgrid_extension]"
          }
     }
  }
  BODY
}
```

### Expected Behavior

Assuming that the deployment fails, I should be able to fix whatever the issue is, and rerun `terraform apply`, and the deployment should be applied.

### Actual Behavior

The deployment fails, and I fix the issue. Now when I run `terraform apply` it complains that the resource already exists. And because this resource doesn't support importing, the name for the deployment is permanently "blacklisted", since there's no way (afaik) to delete a deployment in the Azure Portal.

My theory is that this happens, because the provider doesn't import something into the state, that hasn't been successfully created, which makes sense. But in this case the deployment is created.

### Steps to Reproduce

1. Create any ARM template deployment. Feel free to use the one above.
1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2020-05-27 08:29
hi @KSiig 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6045 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6045 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-27 08:29 UTC
Labels: bug, duplicate, service/resources
