### ISSUE TITLE
AKS windows_profile forces replacement 

### ISSUE THREAD

**Issue by mariojacobo** [terraform-providers/terraform-provider-azurerm#6410] opened 2020-04-08 14:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.4
+ provider.azuread v0.5.0
+ provider.azurerm v1.44.0
+ provider.external v1.2.0
+ provider.helm v0.10.0
+ provider.http v1.2.0
+ provider.kubernetes v1.8.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.tls v2.1.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "${var.aks_name}"
  location            = "${azurerm_resource_group.aks.location}"
  resource_group_name = "${azurerm_resource_group.aks.name}"
  dns_prefix          = "${var.aks_name}"
  kubernetes_version  = "${var.kubernetes_version}"

 default_node_pool {
    name                = "default"
    enable_auto_scaling = true
    max_count           = 20
    min_count           = "${var.aks_nodes}"
    type                = "VirtualMachineScaleSets"
    node_count          = "${var.aks_nodes}"
    vm_size             = "Standard_A4_v2"
    os_disk_size_gb     = 256
    max_pods            = 50 
    vnet_subnet_id      = "${azurerm_subnet.akssubnet.id}"
  }


 network_profile {
        network_plugin = "azure"
  }

  service_principal {
    client_id     = "${azuread_service_principal.akssp.application_id}"
    # object_id = "${azuread_service_principal.akssp.id}"
    client_secret = "${random_string.aks_password.result}"
  }

  role_based_access_control {
    enabled = true
  }

  addon_profile {
        oms_agent {
        enabled                    = true
        log_analytics_workspace_id = "${azurerm_log_analytics_workspace.log_analytics.id}"
      }
  }
```

### Expected Behavior
On the first run of "apply", everything is deployed correctly, which is fine. 

### Actual Behavior
On a second run of the same terraform apply, I get the following error: 

windows_profile {
          admin_username = "azureuser" -># forces replacement
        }

As seen in the error, for some reason terraform adds additional configuration in the form of a "windows_profile", something which is not present in the tf file. 
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-04-08 14:24
Duplicate of #6235 which will ship in v2.5.0

**Closed by tombuildsstuff** 2020-04-08 14:24 UTC
Labels: bug, duplicate, service/kubernetes-cluster
