### ISSUE TITLE
BackupPolicies do not have tags and will cause terraform you indefinetly change this resource

### ISSUE THREAD

**Issue by DenWin** [terraform-providers/terraform-provider-azurerm#8984] opened 2020-10-22 11:38 UTC
Disclaimer as the 1st issue was closed: **This is NOT a question but a bug report!** 

If one sets up azurerm_backup_policy_vm with tags, these will not be accepted by Azure, as Azure does not provide the option for tags for Backup Policies.

Nonetheless, Terraform will retry over and over again to add them. 

Here my code:
```hcl
terraform {
    required_providers {
        azurerm = {
            source = "hashicorp/azurerm"
            version = "~> 2"
        }
        random = {
            source = "hashicorp/random"
            version = "~> 3"
        }
    }
//    backend "azurerm" { }
}

provider "azurerm" {
    features {}
}

resource "azurerm_resource_group" "example" {
  name     = "tfex-recovery_vault"
  location = "West US"
}

resource "azurerm_recovery_services_vault" "example" {
  name                = "tfex-recovery-vault"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
}

resource "azurerm_backup_policy_vm" "example" {
  name                = "tfex-recovery-vault-policy"
  resource_group_name = azurerm_resource_group.example.name
  recovery_vault_name = azurerm_recovery_services_vault.example.name

  timezone = "UTC"

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }

  tags = { some_random_tag = "abc" }
}
```

And here the result:
```bash
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_backup_policy_vm.example will be updated in-place
  ~ resource "azurerm_backup_policy_vm" "example" {
        id                  = "/subscriptions/84c5c22e-f0e6-4b99-99bb-98990facc06f/resourceGroups/tfex-recovery_vault/providers/Microsoft.RecoveryServices/vaults/tfex-recovery-vault/backupPolicies/tfex-recovery-vault-policy"
        name                = "tfex-recovery-vault-policy"
        recovery_vault_name = "tfex-recovery-vault"
        resource_group_name = "tfex-recovery_vault"
      ~ tags                = {
          + "some_random_tag" = "abc"
        }
        timezone            = "UTC"

        backup {
            frequency = "Daily"
            time      = "23:00"
            weekdays  = []
        }

        retention_daily {
            count = 10
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

**Comment by DenWin** [comment] 2020-10-22 11:40
@tombuildsstuff : ReOpen to #8981

**Comment by tombuildsstuff** [comment] 2020-10-22 11:53
hi @DenWin 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5729 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5729 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-22 11:53 UTC
Labels: duplicate, service/recovery-services, upstream-microsoft
