### ISSUE TITLE
Azure API Management soft-delete feature is in preview but its not available with terraform

### ISSUE THREAD

**Issue by krishrocks1904** [terraform-providers/terraform-provider-azurerm#12839] opened 2021-08-04 08:50 UTC
Currently API  management soft delete feature is in preview when I try to delete and recreate APIM with terraform I am getting following error. 

creating/updating API Management Service "dev-apim" (Resource Group "dev-rg"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ServiceAlreadyExistsInSoftDeletedState" Message="Api service dev-apim was soft-deleted. In order to create the new service with the same name, you have to either undelete the service or purge it. See https://aka.ms/apimsoftdelete."

https://docs.microsoft.com/en-us/azure/api-management/soft-delete

we dont have the feature support available in terraform, could you please update?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-08-04 09:36
hi @krishrocks1904 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #11061 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11061 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-08-04 09:36 UTC
