### ISSUE TITLE
New resource - azurerm_subscription

### ISSUE THREAD

**Issue by adarobin** [terraform-providers/terraform-provider-azurerm#3984] opened 2019-07-31 17:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful for my team to be able to create Azure EA subscriptions using Terraform.

### New or Affected Resource(s)

I'm thinking a new resource `azurerm_subscription` to match the data source or maybe `azurerm_ea_subscription`.

### Potential Terraform Configuration

```hcl
resource "azurerm_subscription" "subscription" {
    display_name = "My New Subscription"
    offer_type = "MS-AZR-0017P"
    owners = [ objectId1, objectId2 ]
}
```

### References

https://docs.microsoft.com/en-us/azure/azure-resource-manager/programmatically-create-subscription?tabs=rest

**Comment by a138076** [comment] 2019-08-06 01:47
Potential Duplicate of:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1216

**Comment by tombuildsstuff** [comment] 2019-08-06 09:08
hi @adarobin 

Thanks for opening this issue :)

Taking a look through, as @a138076 has mentioned this appears to be a duplicate of #1216 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1216 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-06 09:08 UTC
