### ISSUE TITLE
Support for adding a new back-end address pool to an existing Azure Application Gateway

### ISSUE THREAD

**Issue by ahmddp** [terraform-providers/terraform-provider-azurerm#9056] opened 2020-10-28 15:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure Terraform provider does not support creating an address pool in an existing Azure Application Gateway.

It is possible via Azure CLI, as the example below:
```
az network application-gateway address-pool create \
    -n MyAddressPool \
    --gateway-name MyAppGateway \
    -g MyResourceGroup \
    --servers mywebsite.azurewebsites.net
```
It is especially required for use cases where Azure Application Gateway is created in one module, some Azure App Services are deployed in another module, and they need to be added to the application gateway's backend pools.

### New or Affected Resource(s)

* Affected:
  - azurerm_application_gateway
* New:
  - azurerm_application_gateway_address_pool
  - azurerm_application_gateway_address_pool_association

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "example" {
  name = "agw-example"
  resource_group_name = azurerm_resource_group.rg.name
  location = var.location
  ...
}

resource "azurerm_application_gateway_address_pool" "example" {
  name = "address-pool-example"
  servers = [ "mywebsite.azurewebsites.net" ]
  ... 
}

resource "azurerm_application_gateway_address_pool_association" "example" {
  application_gateway_id = azurerm_application_gateway.example.id
  address_pool_id = azurerm_application_gateway_address_pool.example.id
  ...
}
```

### References

* https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#az_network_application_gateway_address_pool_create

**Comment by tombuildsstuff** [comment] 2020-10-28 16:09
hi @ahmddp 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5225 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5225 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-28 16:09 UTC
Labels: duplicate, enhancement, service/application-gateway
