### ISSUE TITLE
Support for `key_vault_secret` in `azurerm_api_management_named_value`

### ISSUE THREAD

**Issue by yupwei68** [terraform-providers/terraform-provider-azurerm#12308] opened 2021-06-22 06:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for `key_vault_secret` in `azurerm_api_management_named_value`
![image](https://user-images.githubusercontent.com/56525716/122874032-1a387f80-d365-11eb-9019-f098e1e357f3.png)

### New or Affected Resource(s)

* azurerm_api_management_named_value

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-06-22 06:22
Duplicate of #10416

**Closed by tombuildsstuff** 2021-06-22 06:22 UTC
