### ISSUE TITLE
Feature Request - Azure Policy support under Authorization resources

### ISSUE THREAD

**Issue by kmcquade** [terraform-providers/terraform-provider-azurerm#567] opened 2017-11-16 20:59 UTC
It would be very useful if Terraform could support Azure Policy as part of the Authorization resources. Would be great for automation, secure configuration checks, and continuous compliance verification.

Brief explanation from their docs:
"Azure Policy is a service in Azure that you use to create, assign and, manage policy definitions. Policy definitions enforce different rules and actions over your resources, so those resources stay compliant with your corporate standards and service level agreements. Azure Policy runs an evaluation of your resources, scanning for those not compliant with the policy definitions you have. For example, you can have a policy to allow only certain type of virtual machines... Another requires that all resources have a particular tag. These policies are then evaluated when creating and updating resources."

https://docs.microsoft.com/en-us/azure/azure-policy/azure-policy-introduction

**Comment by kmcquade** [comment] 2017-11-22 21:43
Closing. Just realized this is a duplicate of #46 

But please do address it... would greatly improve the azurerm provider.

**Comment by tombuildsstuff** [comment] 2017-11-27 17:45
Closing as this is a duplicate of #46

**Closed by tombuildsstuff** 2017-11-27 17:45 UTC
Labels: enhancement, new-resource
