### ISSUE TITLE
azurerm_frontdoor idempotency

### ISSUE THREAD

**Issue by bcochofel** [terraform-providers/terraform-provider-azurerm#9531] opened 2020-11-27 14:11 UTC
Hi, I have the following block

variables.tf

```
variable "frontend" {
  type = object({
    name                                    = string
    session_affinity_enabled                = bool
    session_affinity_ttl_seconds            = number
    web_application_firewall_policy_link_id = string
  })
}
```

main.tf

```
resource "azurerm_frontdoor" "fd" {
  name                                         = var.frontdoor.name
  resource_group_name                          = var.resource_group
  enforce_backend_pools_certificate_name_check = var.frontdoor.enforce_backend_pools_certificate_name_check
  tags                                         = local.default_tags
  backend_pools_send_receive_timeout_seconds   = var.frontdoor.backend_pools_send_receive_timeout_seconds

  // FRONTEND
  frontend_endpoint {
    name                                    = var.frontend.name
    host_name                               = "${var.frontend.name}.azurefd.net"
    session_affinity_enabled                = var.frontend.session_affinity_enabled
    session_affinity_ttl_seconds            = var.frontend.session_affinity_ttl_seconds
    web_application_firewall_policy_link_id = var.frontend.web_application_firewall_policy_link_id
    custom_https_provisioning_enabled       = false
  }

  dynamic frontend_endpoint {
    for_each = { for ch in var.custom_hosts : ch.name => ch }

    content {
      name                                    = frontend_endpoint.value.name
      host_name                               = frontend_endpoint.value.host_name
      session_affinity_enabled                = frontend_endpoint.value.session_affinity_enabled
      session_affinity_ttl_seconds            = frontend_endpoint.value.session_affinity_ttl_seconds
      web_application_firewall_policy_link_id = frontend_endpoint.value.web_application_firewall_policy_link_id
      custom_https_provisioning_enabled       = true

      custom_https_configuration {
        certificate_source = "FrontDoor"
      }
    }
  }
...
}
```

Every time I run the terraform plan I get a switch between the 2 frontend_endpoints I have defined on custom_hosts var. Basically is switching between the 2 endpoints that are being defined with the dynamic block.

Does anybody have a solution for this?

Thanks

**Comment by tombuildsstuff** [comment] 2020-11-27 14:17
hi @bcochofel 

Taking a look through here this appears to be the same root cause as #9153 - to ensure we only have one issue tracking the same thing I'm going to close this issue in favour of that one, would you mind subscribing to #9153 for updates?

Thanks

**Closed by tombuildsstuff** 2020-11-27 14:17 UTC
