### ISSUE TITLE
azurerm_recovery_services_protected_vm lists "tags" as an argument but doesn't work

### ISSUE THREAD

**Issue by mystcb** [terraform-providers/terraform-provider-azurerm#2464] opened 2018-12-06 16:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.19.0
```

### Affected Resource(s)

* azurerm_recovery_services_protected_vm

### Terraform Configuration Files

```hcl
locals {
    tags = {
        project = "${var.project}"
        environment = "${var.environment}"
        app = "${var.app}"
    }
}

resource "azurerm_recovery_services_protected_vm" "example" {
  resource_group_name = "${azurerm_resource_group.compute_rg.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.vm-vault.name}"
  source_vm_id        = "${azurerm_virtual_machine.example.id}"
  backup_policy_id    = "${azurerm_recovery_services_protection_policy_vm.asr-policy.id}"

  tags                      = "${local.tags}"
}
```

### Expected Behavior

There isn't an actual resource within Azure, so it doesn't take any tags. An error saying that tags are not an accepted argument should appear.

Documentation: https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protected_vm.html#tags

### Actual Behavior
A plan shows the change and accepts it, an apply attempts to apply the change and succeeds, however a second plan produces the same required changes.

#### Plan example
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_recovery_services_protected_vm.example
      tags.%:               "0" => "3"
      tags.app:             "" => "app"
      tags.environment:     "" => "nonprod"
      tags.project:         "" => "Project Name"


Plan: 0 to add, 1 to change, 0 to destroy.
```

#### Apply Output

```
azurerm_recovery_services_protected_vm.example: Modifying... (ID: <<redacted>>)
  tags.%:               "0" => "3"
  tags.app:             "" => "app"
  tags.environment:     "" => "nonprod"
  tags.project:         "" => "Project Name"
azurerm_recovery_services_protected_vm.example: Still modifying... (ID: <<redacted>>, 10s elapsed)
azurerm_recovery_services_protected_vm.example: Still modifying... (ID: <<redacted>>, 10s elapsed)
azurerm_recovery_services_protected_vm.example: Modifications complete after 12s (ID: <<redacted>>)

```

### Steps to Reproduce

1. `terraform plan` (above output)
2. `terraform apply` (above output)
3. `terraform plan` (plan shows changes to tags still required)

### References
This is my first bug report! I hope it is ok!

**Comment by tombuildsstuff** [comment] 2020-06-04 06:48
hey @mystcb 

Thanks for opening this issue / apologies for the delayed response here!

Taking a look through here the root cause of this appears to be this issue in the Azure API - https://github.com/Azure/azure-rest-api-specs/issues/9251 - as such I'm going to close this issue in favour of that, since once this is fixed in the Azure API this should automatically be fixed in Terraform - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-04 06:48 UTC
Labels: bug, service/recovery-services, upstream-microsoft
