### ISSUE TITLE
data.azurerm_client_config not compatible service principle declared inline on azurerm provider

### ISSUE THREAD

**Issue by buddhamangler-cbre** [terraform-providers/terraform-provider-azurerm#8004] opened 2020-08-04 16:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
provider "http" (hashicorp/http) 1.2.0...
provider "azuread" (hashicorp/azuread) 0.11.0...
provider "azurerm" (hashicorp/azurerm) 2.21.0...

### Affected Resource(s)

* `data.azurerm_client_config`

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}
```

### Debug Output

Error: Error building AzureAD Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

### Expected Behavior

The datasource should be compatible with service principle declared inline on azurerm provider

### Actual Behavior

Datasource throws an error as it does not seem compatible with the service principle declared inline in the provider such as the following...

```hcl
provider "azurerm" {
  version         = "> 2.1"
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
  features {}
}
```

The datasource instead expects environment variables to exist or logged in with az cli...which I have confirmed to work once I put these same values as environment variables.

ARM_CLIENT_ID="..."
ARM_CLIENT_SECRET="..."
ARM_SUBSCRIPTION_ID="..."
ARM_TENANT_ID="..."

The documentation here https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html at the bottom says its valid to specify the credentials in this way and makes no mention that specifying the service principle in this way has this limitation, nor should it have that limitation as terraform should theoretically be able to use those values specified in the provider.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by njuCZ** [comment] 2020-08-05 09:06
@buddhamangler-cbre I am sorry I could not reproduce this error. Could you please paste some debug  log https://www.terraform.io/docs/internals/debugging.html ? So I could inspect this problem more detailed.

**Comment by buddhamangler-cbre** [comment] 2020-08-05 22:00
@njuCZ right, I might have made too much of an assumption here.  Let me try to get this down to the smallest example and get back to you.

**Comment by buddhamangler-cbre** [comment] 2020-08-05 23:30
@njuCZ ok, I was mistaken, it isn't data.azurerm_client_config, it's actually data.azuread_service_principal that's causing the issue.  I boiled it down to the simplest example possible.  You will need to provide a vars.tf file for the various provider attributes.  This configuration has different outcomes based on either specifying or not specifying the corresponding environment variables for the azure provider such as...

ARM_CLIENT_ID="..."
ARM_CLIENT_SECRET="..."
ARM_SUBSCRIPTION_ID="..."
ARM_TENANT_ID="..."

When they are NOT PRESENT, I get (with TRACE ON)...

`
Terraform v0.12.29

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.21.0...
- Downloading plugin for provider "azuread" (hashicorp/azuread) 0.11.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.azuread: version = "~> 0.11"


Warning: Missing backend configuration

-backend-config was used without a "backend" block in the configuration.

If you intended to override the default local backend configuration,
no action is required, but you may add an explicit backend block to your
configuration to clear this warning:

terraform {
  backend "local" {}
}

However, if you intended to override a defined backend, please verify that
the backend configuration is present and valid.


Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error building AzureAD Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

  on <empty> line 0:
  (source code not available)
`

When they ARE PRESENT I get a successful run.

```hcl
terraform {
  required_version = ">=0.12"
}

provider "azurerm" {
  version         = "> 2.1"
  client_id       = var.armcid
  client_secret   = var.armcsec
  tenant_id       = var.armtenid
  subscription_id = var.armsubid
  features {}
}

data "azuread_service_principal" "MicrosoftWebApp" {
  count = 0
  application_id = "abfa0a7c-a6b6-4736-8310-5855508787cd"
}
```

**Comment by tombuildsstuff** [comment] 2020-08-31 14:47
hey @buddhamangler-cbre

Taking a look at the error message being returned here:

> Error: Error building AzureAD Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

This error message is coming from the AzureAD Provider - not the AzureRM provider. Where you're using both Providers, as you're not specifying a provider block for AzureAD, this is using the Azure CLI authentication.

As such this should be fixed by specifying either the Environment Variables (which both use, as you've mentioned) - or by specifying a Provider block for AzureAD as you have for AzureRM.

Since this should be fixed by updating the Terraform Configuration here I'm going to close this issue for the moment, but if you're still having issues with this then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-08-31 14:47 UTC
Labels: authentication, question
