### ISSUE TITLE
Updates to azurerm_kubernetes_cluster fail when cluster uses managed AAD integration

### ISSUE THREAD

**Issue by pindey** [terraform-providers/terraform-provider-azurerm#7325] opened 2020-06-15 08:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.14.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "aks" {
  name     = "aks-service-rg"
  location = "northeurope"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                            = "aks-service"
  location                        = azurerm_resource_group.aks.location
  resource_group_name             = azurerm_resource_group.aks.name
  node_resource_group             = "aks-infra-rg"
  dns_prefix                      = "aks-dev"
  enable_pod_security_policy      = false
  private_cluster_enabled         = false
  api_server_authorized_ip_ranges = null
 
  default_node_pool {
    name            = "default"
    node_count      = 4
    vm_size         = "Standard_B2ms"
    os_disk_size_gb = 30
    vnet_subnet_id  = var.virtual_network.subnets.aks.id
    max_pods        = 60
    type            = "VirtualMachineScaleSets"
  }

  linux_profile {
    admin_username = var.admin_username

    ssh_key {
      key_data = tls_private_key.aks.public_key_openssh
    }
  }
  
  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed                 = true
      admin_group_object_ids  = [for key, value in local.cluster_admins : value.object_id] 
    }
  }

  identity {
    type    = "SystemAssigned"
  }

  addon_profile {

    azure_policy {
      enabled = true
    }
    
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = var.log_analytics_workspace.id
    }

    kube_dashboard {
      enabled = true
    }

    http_application_routing {
      enabled = false
    }

  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "azure"
    load_balancer_sku  = "Basic"
    service_cidr       = var.kubernetes_service_cidr
    docker_bridge_cidr = var.docker_bridge_cidr
    dns_service_ip     = cidrhost(var.kubernetes_service_cidr, 2)
  }

  tags = local.tags

}
```

### Expected Behavior
- Enable feature 'Microsoft.ContainerService/AAD-V2' on subscription
- Apply plan to create cluster with managed Azure Active Directory integration
- Change value of tags - or any other argument that doesn't necessitate a replacement of the resource
- Run terraform plan
- Apply plan
- Tags are updated to reflect changes

### Actual Behavior
- Enable feature 'Microsoft.ContainerService/AAD-V2' on subscription
- Apply plan to create cluster with managed Azure Active Directory integration
- Change value of tags - or any other argument that doesn't necessitate a replacement of the resource
- Run terraform plan
- Apply plan
- Apply fails with error: -

Error: updating Managed Kubernetes Cluster AAD Profile in cluster "aks-service" (Resource Group "aks-service-rg"): containerservice.ManagedClustersClient#ResetAADProfile: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation 'resetAADProfile' is not allowed for managed AAD enabled cluster."

### Steps to Reproduce
1. Register feature 'Microsoft.ContainerService/AAD-V2' on subscription as per https://docs.microsoft.com/en-us/azure/aks/managed-aad
2. `terraform plan`
3. `terraform apply`
4. Make changes to resource
5. `terraform plan`
6. `terraform apply`

### References

* #0000

**Comment by ekarlso** [comment] 2020-06-23 21:14
@tombuildsstuff or anyone can we mayber get this into the next release as a fix? currently it blocks from using the feature as updates to the cluster makes this break.

**Comment by jhawthorn22** [comment] 2020-06-24 07:30
Week late on this buuutt... me and a colleague had same error today. We noticed you could update the rbac details via cli so for anyone that wants a workaround while this is being looked at: we deleted the aks cluster, set the role_based_access_control block to
```
role_based_access_control {
    enabled = true
    azure_active_directory {
      managed = true
    }
}
```
then created a null resource where we update the managed admin ids
```
resource "null_resource" "update_admin_group_ids" {
  depends_on = [
    azurerm_kubernetes_cluster.aks
  ]
  provisioner "local-exec" {
    command = <<EOT
      # --update ids
      az aks update -g <resource_group> -n <name> --aad-tenant-id <tenant_id> --aad-admin-group-object-ids <admin_group_ids>
   EOT
  }
}
```
However, you'll also need a ignore_change on the aks rbac block
```
lifecycle {
    ignore_changes = [
      role_based_access_control
    ]
  }
```

**Comment by EPinci** [comment] 2020-06-24 08:55
I was hoping that workaround applied also to already deployed clusters but, for the records... it doesn't... :(

**Comment by jhawthorn22** [comment] 2020-06-24 09:00
Yeh we've just tested with some other changes and the tag changes still raise the resetAADprofile error :(. Will feedback if we find a workaround.

**Comment by r3mattia** [comment] 2020-06-24 15:33
I've just encountered the same issue now. Going to try @jhawthorn22's approach

**Comment by r3mattia** [comment] 2020-06-24 15:47
Btw @pindey  are you sure it is not because you use:

```
  role_based_access_control {
    enabled = true
    
    azure_active_directory {
      managed = true 
      admin_group_object_ids  = [for key, value in local.cluster_admins : value.object_id] 
    }
  }
```

Rather than:
```
  role_based_access_control {
    enabled = true
    
    azure_active_directory {
      managed = true 
      admin_group_object_ids  = [for key, value in local.cluster_admins : value] 
    }
  }
```

**Comment by pindey** [comment] 2020-06-25 08:28
@r3mattia local.cluster_admins is a map variable, value.object_id is correct. The aadProfile block output by 'az aks show' returns the expected list of adminGroupObjectIds. Happy to give it a whirl with a static list.

**Comment by jhawthorn22** [comment] 2020-06-25 11:22
Really don't like this approach but it's working for us. Created 2 provisioners, one for the AAD admin group ids, one for updating the tags.

Admin groups provisioner:
```
resource "null_resource" "update_admin_group_ids" {
  depends_on = [
    azurerm_kubernetes_cluster.aks
  ]

  triggers = {
    admin_group_changed = var.default_config.aks_admin_group_id
  }

  provisioner "local-exec" {
    command ="${path.module}/scripts/update_admin_group_ids.sh -g ${azurerm_kubernetes_cluster.aks.resource_group_name} -n ${azurerm_kubernetes_cluster.aks.name} -t ${data.azurerm_client_config.current.tenant_id} -a ${var.default_config.aks_admin_group_id}"
    interpreter = ["bash", "-c"]
  }
}
```
AKS tags update provisioner:
```
resource "null_resource" "update_aks_tags" {
  depends_on = [
    azurerm_kubernetes_cluster.aks
  ]

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = "${path.module}/scripts/update_tags.sh -n ${azurerm_kubernetes_cluster.aks.name} -g ${azurerm_kubernetes_cluster.aks.resource_group_name} -t ${jsonencode(var.tags)}"
    interpreter = ["bash", "-c"]
  }
}
```
Provisioner scripts:
```
#!/bin/bash

# options
while getopts g:n:t:a: option
do
    # shellcheck disable=SC2220
    case "${option}"
    in
        g) resource_group=${OPTARG};;
        n) aks_name=${OPTARG};;
        t) tenant_id=${OPTARG};;
        a) admin_group_id=${OPTARG};;
    esac
done

# --get extension
echo "--get aks-preview extension"
az extension add --name aks-preview
az extension list

# --register feature
echo "--register feature"
az feature register --name AAD-V2 --namespace Microsoft.ContainerService
az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/AAD-V2')].{Name:name,State:properties.state}"
az provider register --namespace Microsoft.ContainerService

# --update admin id
az aks update --resource-group "$resource_group" --name "$aks_name" --aad-tenant-id "$tenant_id" --aad-admin-group-object-ids "$admin_group_id"

```
```
#!/bin/bash

## options
while getopts g:n:t: option
do
    # shellcheck disable=SC2220
    case "${option}"
    in
        g) resource_group=${OPTARG};;
        n) aks_name=${OPTARG};;
        t) tags=${OPTARG};;
    esac
done

## reformat tags
# shellcheck disable=SC2207
tags_arr=($(echo "$tags" | jq . | jq -r 'to_entries[] | "\(.key)=\(.value)"' | tr '\n' ' '))

## update tags
for tag in "${tags_arr[@]}";
do
    echo "tag: $tag"
    az resource tag --resource-group "$resource_group" --name "$aks_name" --resource-type "Microsoft.ContainerService/ManagedClusters" -i --tags "$tag"
done
```

**Comment by r3mattia** [comment] 2020-06-25 11:31
@pindey, I used this approach:

```
locals {
  cluster_admins = yamldecode(data.local_file.cluster_admins.content)
}

data "local_file" "cluster_admins" {
  filename = "${path.module}/data/cluster-admins.yml"
}
```

Then the yml file looks like this:
```
---
cluster-admins: value
```

Worked for me.

**Comment by id27182** [comment] 2020-06-30 12:44
I also faced with this issue. I've got this error message when I've tried to update AAD settings manually through [API ](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/resetaadprofile), however I've managed to update settings with azure cli.

**Comment by patpicos** [comment] 2020-07-07 19:24
This error also occurs when modifying other properties of the cluster such as the max node count on a node pool

```
      ~ default_node_pool {
            availability_zones    = []
            enable_auto_scaling   = true
            enable_node_public_ip = false
          ~ max_count             = 3 -> 4
            max_pods              = 30
            min_count             = 3
            name                  = "default"
            node_count            = 3
            node_labels           = {}
            node_taints           = []
            orchestrator_version  = "1.17.7"
            os_disk_size_gb       = 30
            tags                  = {}
            type                  = "VirtualMachineScaleSets"
            vm_size               = "Standard_DS3_v2"
            vnet_subnet_id        = "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/rg-pegaplatform-network-sbox-canadacentral-persistent/providers/Microsoft.Network/virtualNetworks/vnet-pegaplatform-network-sbox-canadacentral/subnets/Private"
        }
```

error:
```
Error: updating Managed Kubernetes Cluster AAD Profile in cluster "aks-pegaplatform-sbox-canadacentral" (Resource Group "rg-pegaplatform-sbox-canadacentral-persistent"): containerservice.ManagedClustersClient#ResetAADProfile: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation 'resetAADProfile' is not allowed for managed AAD enabled cluster."

  on main.tf line 141, in resource "azurerm_kubernetes_cluster" "aks_cluster":
 141: resource "azurerm_kubernetes_cluster" "aks_cluster" {
```

**Comment by patpicos** [comment] 2020-07-07 19:40
Looking at the TF code, I am not sure why the role_based_access_control is seen as a change when I update the # of max nodes on a node pool. Looking at the resource schema, I wonder if this setting has a bearing on forcing an update:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/277f16cdb3cd9916fe1b1b56e58f9dc4bb55af37/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L431


https://github.com/terraform-providers/terraform-provider-azurerm/blob/277f16cdb3cd9916fe1b1b56e58f9dc4bb55af37/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L874 to https://github.com/terraform-providers/terraform-provider-azurerm/blob/277f16cdb3cd9916fe1b1b56e58f9dc4bb55af37/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L892

![image](https://user-images.githubusercontent.com/25851869/86833264-4c26d800-c067-11ea-96c5-5f32b979fb15.png)

**Comment by julianwyngaard** [comment] 2020-07-09 03:21
The error message also appears when trying to update Kubernetes version. There are too many issues to even consider a reliable work around, so feature is unusable. Just had to revert to using service principle unfortunately.

**Comment by hieumoscow** [comment] 2020-07-16 10:46
Updating kubernetes version also caused this issue:
'resetAADProfile' is not allowed for managed AAD enabled cluster.

**Comment by ch-bohlen** [comment] 2020-07-22 07:36
I could reproduce the same error while updating the autoscaler configuration (e.g. update max_count 3 -> 4).
Executing the same configuration update via the Azure CLI works without issues.

Versions:
Terraform 0.12.28
terraform-provider-azurerm 2.18.0

**Comment by patpicos** [comment] 2020-07-22 13:43
Short of it, AAD v2 is a preview feature and it was enabled in the provider. the resetAADProfile is not supported with AAD v2 clusters (from MS side). Therefore the call to reset it should be omitted if managed = true until microsoft starts supporting the call.

**Comment by PSanetra** [comment] 2020-07-22 13:57
resetAADProfile with API version 2020-06-01 seems to support `enableAzureRBAC`:
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/resetaadprofile#request-body

So I guess this could be fixed by using the new API version.

**Comment by sam96688adm** [comment] 2020-07-22 14:42
Yeah I am seeing this when amending pool size, doing Kubernetes upgrades or changing auto scale, so unusable currently.

@patpicos I don't believe it is preview any more, all the preview markers have been removed from the docs and the old version is now referred to as legacy - [https://docs.microsoft.com/en-us/azure/aks/managed-aad](https://docs.microsoft.com/en-us/azure/aks/managed-aad)

**Comment by sam-cogan** [comment] 2020-07-22 14:43
Yeah I am seeing this when amending pool size, doing Kubernetes upgrades or changing auto scale, so unusable currently.

@patpicos I don't believe it is preview any more, all the preview markers have been removed from the docs and the old version is now referred to as legacy - https://docs.microsoft.com/en-us/azure/aks/managed-aad

**Comment by patpicos** [comment] 2020-07-22 14:59
> Yeah I am seeing this when amending pool size, doing Kubernetes upgrades or changing auto scale, so unusable currently.
> 
> @patpicos I don't believe it is preview any more, all the preview markers have been removed from the docs and the old version is now referred to as legacy - https://docs.microsoft.com/en-us/azure/aks/managed-aad

@sam-cogan that is very interesting news. This commit for the documentation confirms what you are saying. https://github.com/MicrosoftDocs/azure-docs/commit/96ab8c1c3669600ac8cbf91ad3bd3a80a82e445a#diff-90a9850acdb4834ff96cc6562e19144e

I didnt see a notice in AKS release notes. Perhaps one is imminent. @PSanetra might be on the right path w/ updating the API version and see if it makes these errors go away

**Comment by patpicos** [comment] 2020-07-22 16:41
Got confirmation from PM on being GA
https://azure.microsoft.com/en-us/updates/aksmanaged-azure-active-directory-support-is-now-generally-available/?s=09

**Comment by aristosvo** [comment] 2020-07-23 07:06
We are creating a new cluster today with AAD v2 support, will let you know how it goes! Will look into it if it is not working

**Comment by sam-cogan** [comment] 2020-07-23 07:31
I created a new cluster yesterday and can confirm the issue is present. You do not see it at cluster creation (at least I didn't) but when you try and modify the cluster to change the amount of nodes, update version etc. you will see the issue.

**Comment by armandorvila** [comment] 2020-07-23 12:32
Same here, getting the error too.

**Comment by aristosvo** [comment] 2020-07-23 16:15
The feature is not GA anymore, due to a delayed rollout: https://github.com/Azure/AKS/issues/1489#issuecomment-663065702.

Also, when I deploy it with a custom build `azurerm` provider API version 2020-06-01, it still doesn't work and still complains if the preview feature is not enabled:

```bash
az feature register --name AAD-V2 --namespace Microsoft.ContainerService
az provider register -n Microsoft.ContainerService
```

I'm working on a PR at the moment, seems to work but Acceptance testing takes a little while.

**Comment by aristosvo** [comment] 2020-07-27 14:00
I've implemented a fix and added Acceptance tests to cover the scenarios in this issue. 

If nothing goes wrong it will make next release! 🎉

**Closed** 2020-07-28 17:37 UTC
Labels: bug, service/kubernetes-cluster

**Comment by c4m4** [comment] 2020-08-06 09:38
Upgrading provider to 2.21.0 version works :)

**Comment by tkinz27** [comment] 2020-08-06 14:32
With the managed AAD how do we attach an ACR instance to the AKS cluster? Before with a manually setup service provider you would just propogate the ACR role to that principal, but as far as I can see there is no way to get access to the underlying service principal that gets setup automatically.

**Comment by sam-cogan** [comment] 2020-08-06 14:35
@tkinz27 your talking about two different things here. The managed AAD integration this issue refers to is related to being able to login to the cluster for admin work as an AAD user, has nothing to do with the clusters access to other resources.

Using managed identity for the cluster identity creates a user assigned managed identity which you can retrieve the name of using the "user_assigned_identity_id" of the "kubelet_identity" block. you would then grant this managed identity access to ACR.

**Comment by tkinz27** [comment] 2020-08-06 14:37
Ohhh... Sorry new to Azure (coming from AWS) and all the auth has definitely been confusing. Thank you for so quickly clearing that up for me.

**Comment by sutinse1** [comment] 2020-08-13 14:47
I get still error about ResetAADProfile althoug I used v2.22.0 azurerm provider.

Error: updating Managed Kubernetes Cluster AAD Profile in cluster "sutinenseaks-aks" (Resource Group "sutinenseaks-rg"): containerservice.ManagedClustersClient#ResetAADProfile: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation 'resetAADProfile' is not allowed for managed AAD enabled cluster."

  on main.tf line 45, in resource "azurerm_kubernetes_cluster" "demo":
  45: resource "azurerm_kubernetes_cluster" "demo" {

I uppgraded azurerm provider to 2.21.0
terraform init -upgrade 

terraform version
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.21.0
+ provider registry.terraform.io/hashicorp/github v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.11.1
+ provider registry.terraform.io/hashicorp/tls v2.1.0

**Comment by aristosvo** [comment] 2020-08-13 15:23
@sutinse1  Can you provide the configuration you are using?

**Comment by sutinse1** [comment] 2020-08-13 15:30
as attached

**Comment by sutinse1** [comment] 2020-08-13 15:31
Missed provider.tf



From: Sutinen, Seppo (TietoTapiola JV)
Sent: torstai 13. elokuuta 2020 18.30
To: 'terraform-providers/terraform-provider-azurerm' <reply@reply.github.com>; terraform-providers/terraform-provider-azurerm <terraform-provider-azurerm@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [terraform-providers/terraform-provider-azurerm] Updates to azurerm_kubernetes_cluster fail when cluster uses managed AAD integration (#7325)

as attached

**Comment by aristosvo** [comment] 2020-08-13 15:39
@sutinse1 Thanks for your quick response, but could you please post it directly on GitHub? The attachment is not showing 😃

**Comment by sutinse1** [comment] 2020-08-14 05:52
[terraform.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5072798/terraform.zip)

Configuration files as attached

**Comment by aristosvo** [comment] 2020-08-14 06:20
What I see is a cluster setup with AAD-v1 integration. Apparently either the backward compatibility here is a problem or you're  mixing things up in your setup. I think the first is the issue, I'll run a few tests when I've time at hand.

I'd recommend for now to restructure/simplify your terraform file for the AAD integration:

```hcl
role_based_access_control {
    enabled = true

    azure_active_directory {
      managed                 = true
      // optional:
      // admin_group_object_ids  = [<AAD group object ids which you want to make cluster admin via AAD login>] 
    }
  }
```

**Comment by aristosvo** [comment] 2020-08-16 16:12
@sutinse1 Can you explain in short what you did before you ended up with the mentioned error? 

What I think you did was as follows:
- Create the `azurerm_kubernetes_cluster` with the setup from the course:
```hcl
resource "azurerm_kubernetes_cluster" "demo" {
...
  role_based_access_control {
    enabled = true

    azure_active_directory {
      client_app_id     = var.aad_client_app_id
      server_app_id     = var.aad_server_app_id
      server_app_secret = var.aad_server_app_secret
      tenant_id         = var.aad_tenant_id
    }
  }
...
}
```
- You probably upgraded it to `AAD-v2` via commandline `az aks update -g myResourceGroup -n myManagedCluster --enable-aad` or similar.
- You reapplied the old configuration with Terraform.

If not, I'm very curious how your configuration ended up in the state with the error 😄

**Comment by sutinse1** [comment] 2020-08-17 06:10
@aristosvo I did just like you wrote, I upgraded to AAD-v2 with registering feature.

// I registered AAD-V2 feature
az feature register --name AAD-V2 --namespace Microsoft.ContainerService
// created AD group for AKS
az ad group create --display-name myAKSAdmin --mail-nickname myAKSAdmin
// added myself to group
az ad group member add --group myAKSAdmin --member-id $id

// Updated cluster
groupid=$(az ad group show --groupmyAKSAdmin --query objectId --output tsv)
tenantid=$(az account show --query tenantId --output tsv)
az aks update -g myaks-rg -n myaks-aks --aad-tenant-id $tenantid --aad-admin-group-object-ids $groupid

I somehow think that terraform can query if AAD is used :) My mistake.

My configuration now (I have to uncomment SP's)

  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed                 = true
      // optional:
      admin_group_object_ids  = ["myAKSAdmin_groupID_not_text"]  
      #client_app_id     = var.aad_client_app_id
      #server_app_id     = var.aad_server_app_id
      #server_app_secret = var.aad_server_app_secret
      tenant_id         = var.aad_tenant_id
    }
  }
