### ISSUE TITLE
azurerm_key_vault_secret.id exports full URI instead of just the ID

### ISSUE THREAD

**Issue by KajdeMunter** [terraform-providers/terraform-provider-azurerm#9216] opened 2020-11-09 14:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Setting a key vault reference was slightly confusing because azurerm_key_vault_secret.id exports the full secret URI instead of the expected ID.

This is what I first tried:
```
@Microsoft.KeyVault(SecretUri=https://${azurerm_key_vault.vault-test.name}.vault.azure.net/secrets/${azurerm_key_vault_secret.secret-test.name}/${azurerm_key_vault_secret.secret-test.id})
```

When in reality this is all I needed:
```
@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.secret-test.id})
```

I can imagine not being the only one confused by this (my coworker was as well). An easy solution to avoid confusion would be just adding an example value. But in my opinion it should export the URI and ID, either seperately or just the ID.

### New or Affected Resource(s)

* azurerm_key_vault_secret

**Comment by tombuildsstuff** [comment] 2020-12-16 11:43
hi @KajdeMunter 

Thanks for opening this issue.

Terraform uses the term `ID` to refer to Terraform's Resource ID (which differs from the Azure Resource ID) - as an example for the Key Vault Secret resource this references the URI used to access this in the Key Vault. Unfortunately the term "Resource ID" is overloaded within both Azure and Terraform - but in this instance the `id` field for the resource is shown in the `import` section of the documentation, and isn't always directly usable by users (for example some are a Terraform specific `{resource1}"|{resource2}`).

Some of the Storage resources which are in a similar position also export additional fields, for example the `azurerm_storage_container` resource uses the Data Plane ID for the `id` field and `resource_manager_id` to reference the ARM ID.

Since we use a convention within the documentation that the `id` field refers to the Terraform Resource ID, I'm going to close this issue for the moment since this is working as intended. That said, I believe it could make sense to expose a `uri` field which would make this clearer to users - if you think that'd be useful would you mind [opening a new Feature Request](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D)?

Thanks!

**Closed by tombuildsstuff** 2020-12-16 11:43 UTC
Labels: question, service/keyvault
