### ISSUE TITLE
VMSS ignore capacity

### ISSUE THREAD

**Issue by colemickens** [terraform-providers/terraform-provider-azurerm#1341] opened 2018-06-03 05:14 UTC
What does terraform do on re-apply if my VMSS has been scaled outside of Terraform?

Is it possible to tell Terraform to ignore the VMSS Capacity whenever doing an "update" rather than an initial create?

I noticed AWS's scaling groups have a min/max. Is that because the AWS API offers that, or is that Terraform's way of dealing with by just enforcing that the real-world count is between min and max?

**Comment by bpoland** [comment] 2018-06-04 13:50
Did you try setting lifecycle ignore_changes on the capacity?

https://www.terraform.io/docs/configuration/resources.html#ignore_changes

**Comment by gregjhogan** [comment] 2018-08-02 00:04
I can't get `ignore_changes` to only ignore `capacity`.

For example, this does not work (it will still detect the capacity as changed):
```
resource "azurerm_virtual_machine_scale_set" "segment-pipeline_vmss" {
  lifecycle {
    ignore_changes = ["sku.capacity"]
  }
  sku {
    name = "Standard_D2s_v3"
    tier = "Standard"
    capacity = 4
  }
  ...
}
```

Using `sku` (instead of `sku.capacity`) is supported, but then it ignores the `name`, which I think is undesirable.  Now that there is support for auto-scaling w/ #1140 I think this is important.

**Comment by katbyte** [comment] 2018-08-02 19:29
Hi @gregjhogan,

The `sku` block is actually represented as a list with 1 element. So i think the following will work:

```
  lifecycle {
    ignore_changes = ["sku.0.capacity"]
  }
```

**Comment by katbyte** [comment] 2018-08-02 19:31
@colemickens, 

As this appears to be a duplicate of #930 i am going to close it in favour of the older issue.

**Closed by katbyte** 2018-08-02 19:31 UTC
Labels: question, service/vmss
