### ISSUE TITLE
azurerm_bastion_host lowercase letters, highercase letters numbers only are allowed in "name"

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#4762] opened 2019-10-30 11:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_bastion_host `

### Actual Behavior

Hello I just did use the new resource "azurerm_bastion_host" and do thank you for the release but I faced this error, seems that some characters like "-" are prohibited, hardcoded in the resource itself. I can attest because I used to create the bastion host with arm template and creating those resource with this character is supported by Microsoft.

```
Error: lowercase letters, highercase letters numbers only are allowed in "name": "product
```

Reference : https://github.com/terraform-providers/terraform-provider-azurerm/pull/4096

**Comment by tombuildsstuff** [comment] 2019-10-30 11:32
hi @JamesDLD 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4759 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4759 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-10-30 11:32 UTC
