### ISSUE TITLE
Support for populating App Configuration with keys and feature flags

### ISSUE THREAD

**Issue by ps-tb** [terraform-providers/terraform-provider-azurerm#7936] opened 2020-07-28 21:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to populate Azure App Configuration with keys and feature flags following resource creation.

### New or Affected Resource(s)

App Configuration
* azurerm_app_configuration

### Potential Terraform Configuration

```hcl
resource "azurerm_app_configuration_key" "example" {
  name                             = "secret-sauce"
  value                             = "szechuan"
  app_configuration_id    = azurerm_app_configuration.example.id
  label                               = "myLabel"
  tags = {
    environment = "Production"
  }
}

resource "azurerm_app_configuration_feature" "example" {
  name                           = "secret-sauce"
  enabled                       = true
  app_configuration_id  = azurerm_app_configuration.example.id
  label                            = "myLabel"
  description                  = "My description"
  tags = {
    environment = "Production"
  }
}
```

**Comment by neil-yechenwei** [comment] 2020-07-30 04:47
Thanks for opening this issue. I assume this issue is requesting two features "app config key" and "app config feature flag". After checked, seems "app config key" has been implemented by [rest api](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/appconfiguration/data-plane/Microsoft.AppConfiguration/stable/1.0/appconfiguration.json) but "app config feature flag" hasn't implemented yet by rest api since I didn't find it anywhere.

**Comment by ps-tb** [comment] 2020-07-30 14:21
@neil-yechenwei I think you're correct. I have a script that uses the Azure CLI to populate keys and could do the same for feature flags because they're available in the CLI as well, which leads me to believe that they're somehow accessible as well.

**Comment by ps-tb** [comment] 2020-09-28 12:59
@neil-yechenwei Would the key/value module creation be too large of a task for a first time contributor? I'm willing to take it on with some guidance if so.

**Comment by tombuildsstuff** [comment] 2020-09-28 14:32
hi @ps-tb 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5840 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5840 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-09-28 14:32 UTC
Labels: duplicate, enhancement, service/app-configuration, upstream-microsoft
