### ISSUE TITLE
Support for Azure AKS Pod Identities

### ISSUE THREAD

**Issue by jkroepke** [terraform-providers/terraform-provider-azurerm#12853] opened 2021-08-05 09:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support Azure AKS Pod Identities, see https://docs.microsoft.com/de-de/azure/aks/use-azure-ad-pod-identity

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"

  pod_identity {
    enabled = true
    kubenet = true
  }

}
```

### References

https://docs.microsoft.com/de-de/azure/aks/use-azure-ad-pod-identity

**Comment by tombuildsstuff** [comment] 2021-08-05 09:46
hi @jkroepke 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9885 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9885 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-08-05 09:46 UTC
Labels: duplicate, enhancement, service/kubernetes-cluster
