### ISSUE TITLE
azurerm_app_service_plan resource creation is excessively long when an ASE is specified

### ISSUE THREAD

**Issue by DanielBMann9000** [terraform-providers/terraform-provider-azurerm#2616] opened 2019-01-08 00:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.11.11  ac4fff416318bf0915a0ab80e062a99ef3724334

### Affected Resource(s)

* azurerm_app_service_plan

### Terraform Configuration Files

```hcl

resource "azurerm_app_service_plan" "asp" {
  name                = "test-asp"
  resource_group_name = "${azurerm_resource_group.applicationResourceGroup.name}"
  location            = "${azurerm_resource_group.applicationResourceGroup.location}"
  app_service_environment_id = "${local.ase_id}" # Assume that this is a valid ID to a pre-existing app service environment
  
  kind = "app"
  sku = {
    tier = "Isolated"
    size = "I1"
    capacity = "1"
  }  
  reserved = false
  per_site_scaling = false
}
```
### Expected Behavior

If a similar operation is done with an ARM template deployment, the app service plan is created in a few seconds and the deployment proceeds. The app service plan remains in a "Provisioning" state, but functions correctly in the interim.

Example ARM template:
```
{
      "type": "Microsoft.Web/serverfarms",
      "sku": {
        "name": "I1",
        "tier": "Isolated",
        "size": "I1",
        "family": "I",
        "capacity": 1
      },
      "kind": "app",
      "name": "[parameters('appServicePlanName')]",
      "apiVersion": "2016-09-01",
      "location": "[parameters('location')]",
      "scale": null,
      "properties": {
        "name": "[parameters('appServicePlanName')]",
        "workerTierName": null,
        "adminSiteName": null,
        "hostingEnvironmentProfile": {
          "id": "[variables('aseResourceid')]"
        },
        "perSiteScaling": false,
        "reserved": false,
        "targetWorkerCount": 1,
        "targetWorkerSizeId": 0
      }
    }
```

### Actual Behavior

The creation of the app service plan takes upwards of an hour to complete. During this span of time, the app service environment shows a "Scaling Operation is in Progress" message in the portal. The app service plan remains in a "Provisioning" state, *but it has been successfully created and is operational* 

There are two problems here, and one is critical:
1. For this scenario, Terraform is significantly slower than using native ARM templates,
2. **you cannot specify an override timeout** for the app service plan Terraform resource, so you roll the dice on every creation. If it finishes in under an hour, everything is fine. If it takes over an hour, Terraform fails.

**Comment by tombuildsstuff** [comment] 2019-01-16 14:35
hi @DanielBMann9000 

Thanks for opening this issue :)

We've been looking to fully support App Service Environments for a while now - however have encountered an issue in the Azure API where the provisioning time is a multitude longer than documented (and in our experience never finishes provisioning). After some time investigating this it appears the Azure Portal submits an ARM Template and creating App Service Environments doesn't appear to be supported through any other means - as such we've had to hold off implementing support for this feature for the moment.

Given this is showing the same symptoms, I'm wondering if the same underlying issue in the Azure API is the root cause of this (but I'm unable to confirm) - at this time there's an issue open on the Rest API Specs Repository (which is where API bugs are tracked) tracking this: https://github.com/Azure/azure-rest-api-specs/issues/4915. We're currently waiting to hear back from the API team on this. Given this is blocked on an upstream issue (and thus unfortunately there's not a whole bunch we can do here in the interim - I'm going to suggest we close this issue in favour of [the upstream API issue](https://github.com/Azure/azure-rest-api-specs/issues/4915) for the moment.

Thanks!

**Closed by tombuildsstuff** 2019-01-16 14:35 UTC
Labels: bug, service/app-service, upstream-microsoft

**Comment by DanielBMann9000** [comment] 2019-01-16 15:19
@tombuildsstuff This issue is **not** about creating app service environments. It's about creating app service plans that are connected to app service environments.

**Comment by tombuildsstuff** [comment] 2019-01-16 16:25
@DanielBMann9000 sorry, to clarify: whilst I understand that this issue is to do with the App Service Plan resource rather than the App Service Environment resource - based on the time spent investigating ASE's previously (and thus the ASP's within them) - I believe this is the same root cause (the Azure API not handling App Service Environment's [and thus any downstream dependencies] correctly).

Once the Azure API is fixed this use-case should also work (since an App Service Environment can't really be tested in it's own right without an App Service Plan) - as such I believe the best path forward for this is to wait for https://github.com/Azure/azure-rest-api-specs/issues/4915 to be resolved.

Thanks!
