### ISSUE TITLE
Regression: skip_credentials_validation in 1.38.0

### ISSUE THREAD

**Issue by stazz** [terraform-providers/terraform-provider-azurerm#5122] opened 2019-12-10 10:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version `0.12.7`, AzureRM version `1.38.0`.

### Affected Resource(s)

All resources.

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm  = "~1.38.0"
  }
}

provider "azurerm" {
  client_id                   = "00000000-0000-0000-0000-000000000000"
  subscription_id             = "00000000-0000-0000-0000-000000000000"
  tenant_id                   = "00000000-0000-0000-0000-000000000000"
  client_secret               = "not-used"
  skip_credentials_validation = true
}
```

### Debug Output

I can provide the full debug output if it is really needed. Current debug output is a bit complicated due to so many resources used.
The relevant part I think is here:
```
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: [DEBUG] GoAzureHelpers Response for https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/token?api-version=1.0: 
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: HTTP/1.1 400 Bad Request
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Content-Length: 494
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Cache-Control: no-cache, no-store
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Content-Type: application/json; charset=utf-8
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Date: Tue, 10 Dec 2019 08:48:39 GMT
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Expires: -1
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: P3p: CP="DSP CUR OTPi IND OTRi ONL FIN"
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Pragma: no-cache
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Set-Cookie: fpc=AhED198zdQJFmxnHia7YtOQ; expires=Thu, 09-Jan-2020 08:48:40 GMT; path=/; secure; HttpOnly; SameSite=None
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Set-Cookie: x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Set-Cookie: stsservicecookie=ests; path=/; SameSite=None; secure; HttpOnly
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: Strict-Transport-Security: max-age=31536000; includeSubDomains
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: X-Content-Type-Options: nosniff
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: X-Ms-Ests-Server: 2.1.9707.16 - AMS1 ProdSlices
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: X-Ms-Request-Id: <id>
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: 
2019-12-10T08:48:39.965Z [DEBUG] plugin.terraform-provider-azurerm_v1.38.0_x4: {"error":"invalid_request","error_description":"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\r\nTrace ID: <id>\r\nCorrelation ID: <id>\r\nTimestamp: 2019-12-10 08:48:40Z","error_codes":[900021],"timestamp":"2019-12-10 08:48:40Z","trace_id":"<id>","correlation_id":"<id>"}
2019/12/10 08:48:39 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\\r\\nTrace ID: <id>\\r\\nCorrelation ID: <id>\\r\\nTimestamp: 2019-12-10 08:48:40Z\",\"error_codes\":[900021],\"timestamp\":\"2019-12-10 08:48:40Z\",\"trace_id\":\"<id>\",\"correlation_id\":\"<id>\"}", resp:(*http.Response)(0xc0006ef290)}, PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:400, Message:"Failed to refresh the Token for request to https://graph.windows.net/00000000-0000-0000-0000-000000000000/servicePrincipals?%24filter=appId+eq+%2700000000-0000-0000-0000-000000000000%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc0006ef290)}
2019/12/10 08:48:39 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\\r\\nTrace ID: <id>\\r\\nCorrelation ID: <id>\\r\\nTimestamp: 2019-12-10 08:48:40Z\",\"error_codes\":[900021],\"timestamp\":\"2019-12-10 08:48:40Z\",\"trace_id\":\"<id>\",\"correlation_id\":\"<id>\"}", resp:(*http.Response)(0xc0006ef290)}, PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:400, Message:"Failed to refresh the Token for request to https://graph.windows.net/00000000-0000-0000-0000-000000000000/servicePrincipals?%24filter=appId+eq+%2700000000-0000-0000-0000-000000000000%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc0006ef290)}
2019/12/10 08:48:39 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\\r\\nTrace ID: <id>\\r\\nCorrelation ID: <id>\\r\\nTimestamp: 2019-12-10 08:48:40Z\",\"error_codes\":[900021],\"timestamp\":\"2019-12-10 08:48:40Z\",\"trace_id\":\"<id>\",\"correlation_id\":\"<id>\"}", resp:(*http.Response)(0xc0006ef290)}, PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:400, Message:"Failed to refresh the Token for request to https://graph.windows.net/00000000-0000-0000-0000-000000000000/servicePrincipals?%24filter=appId+eq+%2700000000-0000-0000-0000-000000000000%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc0006ef290)}
2019/12/10 08:48:39 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\\r\\nTrace ID: <id>\\r\\nCorrelation ID: <id>\\r\\nTimestamp: 2019-12-10 08:48:40Z\",\"error_codes\":[900021],\"timestamp\":\"2019-12-10 08:48:40Z\",\"trace_id\":\"<id>\",\"correlation_id\":\"<id>\"}", resp:(*http.Response)(0xc0006ef290)}, PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:400, Message:"Failed to refresh the Token for request to https://graph.windows.net/00000000-0000-0000-0000-000000000000/servicePrincipals?%24filter=appId+eq+%2700000000-0000-0000-0000-000000000000%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc0006ef290)}
2019/12/10 08:48:39 [TRACE] [walkPlan] Exiting eval tree: provider.azurerm
```

### Panic Output

No panic output.

### Expected Behavior
The `plan` command completes successfully.
I've verified that success occurs under AzureRM provider version `1.37.0`.

### Actual Behavior
The `plan` command fails with the error:
```
Error: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\\r\\nTrace ID: <id>\\r\\nCorrelation ID: <id>\\r\\nTimestamp: 2019-12-10 08:27:55Z\",\"error_codes\":[900021],\"timestamp\":\"2019-12-10 08:27:55Z\",\"trace_id\":\"<id>\",\"correlation_id\":\"<id>\"}", resp:(*http.Response)(0xc0006c8900)}, PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:400, Message:"Failed to refresh the Token for request to https://graph.windows.net/00000000-0000-0000-0000-000000000000/servicePrincipals?%24filter=appId+eq+%2700000000-0000-0000-0000-000000000000%27&api-version=1.6", Service Error:[]uint8(nil), Response:(*http.Response)(0xc0006c8900)}

  on x.tf line x, in provider "azurerm":
   x: provider "azurerm" {
```

So it looks like the provider is actually trying to log in, even though the `skip_credentials_validation` has been specified and set to `true`.

I have a bunch of tests on a pipeline which involves bundling some TF code, so I use this kind of setup in my tests to verify that the TF code does not have some very obvious mistakes, like typos or other stuff like that.
That's how I stumbled on this problem.

### Steps to Reproduce

Try to run `terraform plan` on any Azure resource with the configuration given above (the `terraform` and `provider` blocks).

### Important Factoids

I use Docker image ( https://hub.docker.com/r/hashicorp/terraform ) to run Terraform.

### References

These are from AWS provider so most likely not relevant, but I provide them here anyway:
* https://github.com/terraform-providers/terraform-provider-aws/issues/5584
* https://github.com/hashicorp/terraform/issues/18696

**Comment by stazz** [comment] 2019-12-16 13:33
Can confirm it still happens on `1.39.0`.

Any plans for this, @tombuildsstuff ? It wouldn't be nice to simply disable all the dry-run tests I have, as they have already catched a lot of typo- and other kind of bugs from my code.

Alternatively, does anyone know any workaround for this, maybe some special TF switch or something like that? I don't know any workarounds, except actually creating and using dedicated Azure account + SP.

**Comment by tombuildsstuff** [comment] 2019-12-16 14:05
hi @stazz 

Thanks for opening this issue.

Whilst I agree this is is a regression, due to the way some of the internals are changing in the future we'll require valid credentials in the future - so it might be worth us deprecating/removing this functionality in 2.0.

Out of interest what's the use-case for using fake credentials, verses say using a Service Principal with read-only access, for example?

Thanks!

**Comment by stazz** [comment] 2019-12-16 14:16
Hi @tombuildsstuff , thanks for replying quickly! :)

I agree that if you really plan to remove this feature in 2.0 release, it doesn't make much sense in fixing it now (unless it still will take a loooong time until 2.0!). I guess maybe some sort of "official" notice would be nice in that case, making it indeed look like a planned feature deprecation.

About the use-case: I am working on a TF codebase which can be run by different clients for their infra deployments. It is basically thin layer around AzureRM provider, with some organization-specific constraints added (how to specify secrets, certain enforced models on how to deploy certain resources, unifying the module and resource names, etc). It is already in use in multiple places, so it is important that new releases don't introduce typo-kind of bugs or any other regressions. So my build pipeline simply runs the code it built in `plan` phase, giving it a few different usecases, and just sees that the code does not crash. Such tests have been really easy to set up with `skip_credentials_validation`, as it required no manual steps to create some 'dummy' Azure subscription and service principal.

**Comment by stazz** [comment] 2019-12-18 13:42
Btw I know a little of Go, so maybe if you can point me to few locations in the code, I could make a PR which would fix this at least for now (until 2.0 I guess).

**Comment by andreasasujacgi** [comment] 2020-03-24 13:08
Hi, any progress on this? We've tested this with azurerm provired versions 1.44.0 and 2.2.0 and both produce the same error when trying to login with service principal. So, we're stuck to version 1.37 as it is the last functioning version.

**Comment by tombuildsstuff** [comment] 2020-08-28 06:05
hi @stazz @andreasasujacgi 

Taking another look through here - unfortunately as mentioned above we're requiring valid credentials (and have done for a while) and so this appears to be working as designed.

This flag was originally intended to workaround a scenario where someone was pre-validating credentials and wanted to avoid that extra hop. Since in this instance we're now using those credentials as we would for any other API call, this functionality still works as intended and unfortunately this alternate use-case of using invalid credentials (whilst useful to your scenario) was never officially supported.

Rather than relying on this undocumented behaviour - you should instead be able to use a real Service Principal (or other account) with readonly permissions to achieve the same thing; optionally you may wish to use a separate/new Terraform Workspace if you'd like to do end-to-end testing too.

As time goes on we're adding more and more validation which requires valid credentials with the intention of moving as much of this logic into regular validation methods as possible, meaning this should be caught by `terraform plan`. The first of these is the new "Enhanced Validation for Locations" where we're now catching invalid Azure Region/Location names - but we'll be adding to these as time goes on.

Since the original behaviour here (bypassing the credentials validation) is working as intended here, and working with invalid credentials was never officially supported - whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment. As mentioned above however I believe you should be able to achieve the same thing using a Service Principal with read-only permissions.

Thanks!

**Closed by tombuildsstuff** 2020-08-28 06:05 UTC
Labels: thinking
