### ISSUE TITLE
azurerm_kubernetes_service_versions can not find a version.

### ISSUE THREAD

**Issue by skydjol** [terraform-providers/terraform-provider-azurerm#4030] opened 2019-08-07 09:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_service_versions`

### Terraform Configuration Files

```hcl
data "azurerm_kubernetes_service_versions" "current" {
  location       = var.location
  version_prefix = "1.11"
}
```

### Debug Output

https://gist.github.com/skydjol/03753033fc17ab5cc82f1290f0b24e0f

### Expected Behavior

According to the documentation, the latest recommended Kubernetes Version should be selected.

### Actual Behavior

```
Error: Error: No Kubernetes Service versions found for location "francecentral"
```
Works with  version < 1.32.0

### Steps to Reproduce

1. `terraform apply`

**Comment by helenabutowatep** [comment] 2019-08-13 20:11
I get the same error for the westus2 location when using a Service Principal scoped to a Resource Group.

**Comment by helenabutowatep** [comment] 2019-12-04 19:17
It looks like this may be resolved with newer versions of the provider (I've gotten terraform-provider-azurerm_v1.37.0_x4 to work at least).

**Comment by neil-yechenwei** [comment] 2020-05-08 04:59
Thanks for opening this issue. Seems the issue has been resolves.
```
provider "azurerm" {
  features {}
}

data "azurerm_kubernetes_service_versions" "test" {
  location       = "westus2"
  version_prefix = "1.16.7"
}
```

**Comment by ArcturusZhang** [comment] 2020-06-05 08:50
Hi @skydjol 

Since this issue is opened for quite a long time, and we are not able to reproduce your issue on the latest version of provider, therefore I would close this issue hope you would not mind.
If you find this issue persist, please feel free to reopen, comment or open a new issue regarding the new version of provider.
Thank you!

**Closed by ArcturusZhang** 2020-06-05 08:50 UTC
Labels: bug, service/kubernetes-cluster
