### ISSUE TITLE
azurerm_role_definition: azure didn't like modifying in place.

### ISSUE THREAD

**Issue by lrosenman** [terraform-providers/terraform-provider-azurerm#3803] opened 2019-07-07 12:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

[I] ➜ terraform -v
Terraform v0.11.14
+ provider.azurerm v1.31.0
+ provider.null v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.3. You can update by downloading from www.terraform.io/downloads.html

wf-corporate-terraform/azure on  lrosenman/az-osrm [!]
[I] ➜
### Affected Resource(s)

* `azurerm_role_definition`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
`resource "azurerm_role_definition" "read-validator" {
  name        = "read-validator"
  scope       = "${data.azurerm_subscription.primary.id}"
  description = "This is a custom role created via Terraform"

  permissions {
    data_actions     = [
                        "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read"
                       ]
    actions          = [
                        "Microsoft.Storage/storageAccounts/blobServices/containers/read",
                        "Microsoft.Storage/storageAccounts/read"
                       ]
    not_actions = []
  }

  assignable_scopes = [
   "${azurerm_storage_account.w2-validator.id}"
  ]
}`
### Expected Behavior

role modified in place
### Actual Behavior

`	* azurerm_role_definition.read-validator: 1 error occurred:
	* azurerm_role_definition.read-validator: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleDefinitionWithSameNameExists" Message="A role definition cannot be updated with a name that already exists."`
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I had added the actions block when the resource already existed with out it. 
### References

* #0000

**Comment by lrosenman** [comment] 2019-07-08 22:12
Similar issue with vmss:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_virtual_machine_scale_set.osrm
      identity.0.identity_ids.0:                     "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourceGroups/EUS2-WHEREFOR-VPC/providers/Microsoft.ManagedIdentity/userAssignedIdentities/w2-validator" => "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourcegroups/EUS2-WHEREFOR-VPC/providers/Microsoft.ManagedIdentity/userAssignedIdentities/w2-validator]"
      identity.0.type:                               "SystemAssigned, UserAssigned" => "SystemAssigned"
      storage_profile_data_disk.0.managed_disk_type: "Standard_LRS" => "Premium_LRS"
      storage_profile_data_disk.1.caching:           "ReadWrite" => "ReadOnly"
      storage_profile_data_disk.1.managed_disk_type: "Standard_LRS" => "Premium_LRS"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_virtual_machine_scale_set.osrm: Modifying... (ID: /subscriptions/30e95a3d-74e7-489c-a2ba-...t.Compute/virtualMachineScaleSets/osrm)
  identity.0.identity_ids.0:                     "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourceGroups/EUS2-WHEREFOR-VPC/providers/Microsoft.ManagedIdentity/userAssignedIdentities/w2-validator" => "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourcegroups/EUS2-WHEREFOR-VPC/providers/Microsoft.ManagedIdentity/userAssignedIdentities/w2-validator]"
  identity.0.type:                               "SystemAssigned, UserAssigned" => "SystemAssigned"
  storage_profile_data_disk.0.managed_disk_type: "Standard_LRS" => "Premium_LRS"
  storage_profile_data_disk.1.caching:           "ReadWrite" => "ReadOnly"
  storage_profile_data_disk.1.managed_disk_type: "Standard_LRS" => "Premium_LRS"

Error: Error applying plan:

1 error occurred:
    * azurerm_virtual_machine_scale_set.osrm: 1 error occurred:
    * azurerm_virtual_machine_scale_set.osrm: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'dataDisk.managedDisk.storageAccountType' is not allowed." Target="dataDisk.managedDisk.storageAccountType"
```

**Comment by katbyte** [comment] 2019-07-09 06:38
Closing as a duplicate of #2069

**Closed by katbyte** 2019-07-09 06:38 UTC
Labels: bug, good first issue, service/roles
