### ISSUE TITLE
"azurerm_kubernetes_cluster_node_pool.system must be replaced" directly after apply

### ISSUE THREAD

**Issue by janegilring** [terraform-providers/terraform-provider-azurerm#6992] opened 2020-05-19 02:56 UTC
I just deployed a new AKS cluster using the above configuration, and immediately ran terraform plan afterwards. Then it states multiple changes is required.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.25
+ provider.azuread v0.8.0 
+ provider.azurerm v2.10.0

### Affected Resource(s)

* `azurerm_v2.10.0`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "cluster" {
    name                = var.aks_cluster_name
    location            = var.location
    resource_group_name = var.resource_group_name
    depends_on          = [azurerm_resource_group.rg]
    dns_prefix          = var.instance-id
    // Define the default pool
    default_node_pool {
        name       = "linux"
        node_count = 6
        vm_size    = "Standard_D4s_v3"
        max_pods   = 200
        // Subnet ID must be defined with CNI
        vnet_subnet_id = azurerm_subnet.aks.id
    }
    // Setting up the cluster to use CNI
    network_profile {
        network_plugin = "azure"
    }

    service_principal {
        client_id     = azuread_service_principal.k8s.application_id
        client_secret = random_password.password.result
    }

    tags = var.tags
}
// Add the secondary pool, for system
resource "azurerm_kubernetes_cluster_node_pool" "system" {
    name                  = "sys"
    kubernetes_cluster_id = azurerm_kubernetes_cluster.cluster.id
    vm_size               = "Standard_D2s_v3"
    node_count            = 2
    os_type = "Linux"
    tags = var.tags
}

// Add the third pool, for Windows nodes
resource "azurerm_kubernetes_cluster_node_pool" "windows" {
    name                  = "win"
    kubernetes_cluster_id = azurerm_kubernetes_cluster.cluster.id
    vm_size               = "Standard_D4s_v3"
    node_count            = 8
    os_type = "Windows"
    tags = var.tags
}
```
### Expected Behavior

terraform plan should state that the infrastructure is up-to-date.

### Actual Behavior

```
  # azurerm_kubernetes_cluster_node_pool.system must be replaced
-/+ resource "azurerm_kubernetes_cluster_node_pool" "system" {
      - availability_zones    = [] -> null
      - enable_auto_scaling   = false -> null
      - enable_node_public_ip = false -> null
      ~ id                    = "/subscriptions/../resourcegroups/...-devtest-rg/providers/Microsoft.ContainerService/managedClusters/elements-01-devtest-k8s/agentPools/sys" -> (known after apply)
        kubernetes_cluster_id = "/subscriptions/../resourcegroups/...-devtest-rg/providers/Microsoft.ContainerService/managedClusters/elements-01-devtest-k8s"
      - max_count             = 0 -> null
      ~ max_pods              = 30 -> (known after apply)
      - min_count             = 0 -> null
        name                  = "sys"
        node_count            = 2
      - node_labels           = {} -> null
      - node_taints           = [] -> null
      ~ os_disk_size_gb       = 100 -> (known after apply)
        os_type               = "Linux"
      ~ tags                  = {
          + "Environment" = "Test"
          + "Source"      = "terraform"
          - "environment" = "Test" -> null
          - "source"      = "terraform" -> null
        }
        vm_size               = "Standard_D2s_v3"
      - vnet_subnet_id        = "/subscriptions/.../resourceGroups/...devtest-rg/providers/Microsoft.Network/virtualNetworks/devtest-vnet/subnets/AksSubnet" -> null # forces replacement
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by tombuildsstuff** [comment] 2020-05-19 09:54
hi @janegilring 

Thanks for opening this issue.

Due to a limitation in the AKS Service at this point in time all Node Pools within the Cluster must be part of the same Virtual Network. As this applies primarily to the Node Pools, we've opted to document this in the [documentation for the Node Pool resource](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#vnet_subnet_id) - however this field is exposed due to upcoming changes in AKS where it's possible to provision Node Pools having some public and some private.

As such you should be able to work around this by placing all Node Pools on the same network (or having them all public) - but unfortunately at this time this is a limitation in the AKS Service itself. Once this change happens in AKS - Terraform should be automatically able to handle having separate Node Pools on multiple networks (or public & private). Since this appears to be working as intended I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-05-19 09:54 UTC
Labels: question, service/kubernetes-cluster

**Comment by janegilring** [comment] 2020-05-20 00:42
Thanks @tombuildsstuff - that was it. I actually had't defined a vnet_subnet_id for the two pools which got re-created every time. After doing so, the issue is gone.
I still had the issue regarding tags being updated, but noticed the comment about that and added a lifecycle block with ignore_changes for tags - no everything looks clean.
