### ISSUE TITLE
Inconsistant ContainerInsights location 

### ISSUE THREAD

**Issue by Djiit** [terraform-providers/terraform-provider-azurerm#3689] opened 2019-06-18 09:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.2
+ provider.azurerm v1.30.1
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0
+ provider.local v1.2.2
```

### Affected Resource(s)

* `azurerm_log_analytics_solution`

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_solution" "my-analytics_solution" {
  solution_name         = "ContainerInsights"
  location              = "chinaeast2"
  resource_group_name   = azurerm_resource_group.my-resource_group.name
  workspace_resource_id = azurerm_log_analytics_workspace.my-analytics_workspace.id
  workspace_name        = azurerm_log_analytics_workspace.my-analytics_workspace.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}
```

### Debug Output

```
  # azurerm_log_analytics_solution.my-analytics_solution must be replaced
-/+ resource "azurerm_log_analytics_solution" "my-analytics_solution" {
      ~ id                    = "<old_id>" -> (known after apply)
      ~ location              = "cne2" -> "chinaeast2" # forces replacement
        resource_group_name   = "MY-RG"
        solution_name         = "ContainerInsights"
        workspace_name        = "myAnalyticsWorkspace"
      ~ workspace_resource_id = "<old_id>" -> "<new_id>"

      ~ plan {
          ~ name      = "ContainerInsights(myAnalyticsWorkspace)" -> (known after apply)
            product   = "OMSGallery/ContainerInsights"
            publisher = "Microsoft"
        }
    }
```

### Expected Behavior

Apply should tell me there are no changes.

### Actual Behavior

Terraform tells me the location has changed (in fact, it seems "cne2" and "chinaeast2" are the same location, but with a different name.

### Steps to Reproduce

1. `terraform apply`

**Comment by mhennecke** [comment] 2020-04-13 23:20
Had special handling in place for this case. For me at least it seems this issue has been resolved. Don't know when and where. I just updated to azurerm provider 2.5.0 from 1.44 and my azurerm_log_analytics_solution resources show a location of chinaeast2 instead of the former cne2.

**Comment by tombuildsstuff** [comment] 2020-04-14 09:11
hey @Djiit 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through here unfortunately this is a bug in the Log Analytics API which has since been resolved on Azure's side (as confirmed by @mhennecke, and I recall another issue tracking this too) - as such I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2020-04-14 09:11 UTC
Labels: bug, service/log-analytics
