### ISSUE TITLE
Azure Maps sku_name is lowercase, but Azure reports as uppercase

### ISSUE THREAD

**Issue by xtellurian** [terraform-providers/terraform-provider-azurerm#4700] opened 2019-10-24 01:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Unknown (I'm using Pulumi)

### Affected Resource(s)

* `azurerm_resource_arm_maps_account`

### Terraform Configuration Files

none

### Debug Output

[Azure Resource Explorer ](https://resources.azure.com/) reports sku name with a capital 'S'

```js
{
"sku": {
        "name": "S0",
        "tier": "Standard"
      }
}
```

### Expected Behavior

Case of sku name from Azure RM should match case when validating `sku_name`

### Actual Behavior

Terraform validation function requires lower-case 's0' and 's1' but ARM reports sku name as upper-case 'S0' and 'S1'

### Steps to Reproduce

1. Create an Azure Maps account
2. Go to https://resources.azure.com/ and look at the Azure Maps resource definition
3. Try to change the `sku_name` property to match the uppercase 'S0' or 'S1' as reported by ARM
4. Terraform validation function does not allow uppercase 'S0' or 'S1'

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_maps_account.go#L51

**Comment by xtellurian** [comment] 2019-10-24 01:19
https://github.com/pulumi/pulumi-azure/issues/396

**Comment by xtellurian** [comment] 2019-10-24 01:25
We could change the validation function like so, to avoid breaking existing code. 
```go
"sku_name": {
    Type:     schema.TypeString,
    Required: true,
    ForceNew: true,
    ValidateFunc: validation.StringInSlice([]string{
        "s0",
        "S0",
        "s1",
        "S1"
    }, false),
},
```

**Comment by mikhailshilkov** [comment] 2019-10-24 12:24
This is a duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/4706 which has more Terraform details

**Comment by tombuildsstuff** [comment] 2019-10-24 12:39
closing in favour of #4706

**Closed by tombuildsstuff** 2019-10-24 12:39 UTC
