### ISSUE TITLE
Unable to update App Service Plan since 2.0

### ISSUE THREAD

**Issue by Djiit** [terraform-providers/terraform-provider-azurerm#5908] opened 2020-02-26 09:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

```sh
terraform -v
Terraform v0.12.20
+ provider.azurerm v2.0.0
```
### Terraform Configuration Files

(names eluded)

```hcl
resource "azurerm_app_service_plan" "cx-app_service_plan" {
  name                = "MY-ASP"
  location            = "West Europe"
  resource_group_name = "MY-RG"'
  reserved            = true
  kind                = "Linux"

  sku {
    tier = var.asp_sku_tier
    size = var.asp_sku_size
  }
}
```

### Description / Feedback

It should have updated my ASP correctly.
Even if I revert to provider 1.44.0, I can't apply anything now :/ This is quite blocking 😅 .

Here is the error I get : 
```
Error: Error creating/updating App Service Plan "MY-ASP" (Resource Group "MY-RG"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
```

Thanks for your help

**Comment by Djiit** [comment] 2020-02-26 09:44
Is a duplicate of: #5884, #5899,
Might be a duplicate of :  #5866, #5867

**Comment by georgegil** [comment] 2020-02-26 14:31
yep, ran into the same issue after using v2 of the azurerm provider:

this in the PUT to the API:

`{
    "kind": "Windows",
    "location": "uksouth",
    "properties": {
        "hostingEnvironmentProfile": {
            "id": ""
        },
        "perSiteScaling": false,
        "maximumElasticWorkerCount": 1,
        "reserved": false,
        "isXenon": false
    },
    "sku": {
        "name": "P2v2",
        "tier": "PremiumV2",
        "size": "P2v2",
        "capacity": 2
    },
    "tags": {
        "Tag_1": "Value_1",
        "Tag_2": "Value_2",
        "Tag_3": "Value_3"
    }
}`
and then an error:

`{"error":{"code":"LinkedInvalidPropertyId","message":"Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."}}`

**Comment by jackofallops** [comment] 2020-02-26 18:40
closing as duplicate of #5884

**Closed by jackofallops** 2020-02-26 18:40 UTC
