### ISSUE TITLE
Support for Policy Assignment nonComplianceMessages property

### ISSUE THREAD

**Issue by jtracey93** [terraform-providers/terraform-provider-azurerm#10697] opened 2021-02-23 10:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Policy Assignments have recently added a new property ```nonComplianceMessages``` that allows for a Custom Policy error/non-compliance message which is useful for end users, instead of having to read through the raw JSON response saying that a resource is non-compliant and finding which policy is causing this.

More info on the nonComplianceMessages property can be found here:
- https://docs.microsoft.com/en-gb/azure/governance/policy/concepts/assignment-structure#non-compliance-messages
- https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/policyAssignments.json

### New or Affected Resource(s)

* azurerm_policy_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_policy_assignment" "example" {
  name                    = "example-policy-assignment"
  scope                   = azurerm_resource_group.example.id
  policy_definition_id    = azurerm_policy_definition.example.id
  description             = "Policy Assignment created via an Acceptance Test"
  display_name            = "My Example Policy Assignment"
  non_compliance_messages = "Non-Compliant Resource Custom Message Example"

  metadata = <<METADATA
    {
    "category": "General"
    }
METADATA

  parameters = <<PARAMETERS
{
  "allowedLocations": {
    "value": [ "West Europe" ]
  }
}
PARAMETERS

}
```

### References

N/A

**Comment by tombuildsstuff** [comment] 2021-06-24 12:15
hi @jtracey93 

Taking a look through this appears to be a duplicate of #10401 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10401 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-06-24 12:15 UTC
Labels: enhancement, sdk/requires-newer-api-version, service/policy
