### ISSUE TITLE
TF apply/plan have different constraints for "Consumption" tier for API Management

### ISSUE THREAD

**Issue by alecor191** [terraform-providers/terraform-provider-azurerm#6730] opened 2020-05-01 06:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.8.0

### Affected Resource(s)

* `azurerm_api_management`

### Issue description
Since 2.8.0 the "Consumption" tier for API Management should be supported. However, I'm unable to set this tier:

#### Use `sku_name = "Consumption"`
`terraform plan` fails with `Error: sku_name(Consumption) is not formatted properly.`

#### Use `sku_name = "Consumption_0"`
`terraform plan` fails with `Error: expected sku_name capacity value to be greater that 1, got 0`

#### Use `sku_name = "Consumption_1"`
`terraform plan` passes, however, `terraform apply` fails with `Error: creating/updating API Management Service "<redacted>" (Resource Group "<redacted>"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameters" Message="Invalid parameter: For Consumption SKU Type capacity must be specified as 0."`

So it seems that `terraform plan` requires "Consumption_1" (or greater), but `terraform apply `requires "Consumption_0"

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Here the output when setting `sku_name = "Consumption_0"` and running `terraform apply`:

```
2020-05-01T06:47:23.0441766Z 2020/05/01 06:47:22 [ERROR] module.apim: eval: *terraform.EvalDiff, err: expected sku_name capacity value to be greater that 1, got 0
2020-05-01T06:47:23.0442653Z 2020/05/01 06:47:22 [ERROR] module.apim: eval: *terraform.EvalSequence, err: expected sku_name capacity value to be greater that 1, got 0
2020-05-01T06:47:23.0443329Z 2020/05/01 06:47:22 [TRACE] [walkRefresh] Exiting eval tree: module.apim.azurerm_api_management.customer_api
2020-05-01T06:47:23.0443789Z 2020/05/01 06:47:22 [TRACE] vertex "module.apim.azurerm_api_management.customer_api": visit complete
2020-05-01T06:47:23.0444288Z 2020/05/01 06:47:22 [TRACE] vertex "module.apim.azurerm_api_management.customer_api": dynamic subgraph encountered errors
2020-05-01T06:47:23.0444782Z 2020/05/01 06:47:22 [TRACE] vertex "module.apim.azurerm_api_management.customer_api": visit complete
```

### Expected Behavior

`terraform apply` and `terraform plan` should have the same capacity constraints for APIM `Consumption` tier.

### Actual Behavior

`terraform plan` requires capacity set to `0`, whereas `terraform apply` requires capacity to be set `>0`.

**Comment by omgapuppy** [comment] 2020-05-05 09:09
Looks like there's a bit more to this than just the capacity tier of zero.

Logic to omit some default attributes that the TF provider passes to the Azure API is needed:

```
Error: creating/updating API Management Service "REDACTED" (Resource Group "REDACTED"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NotSupported" Message="'Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30' customProperties are not supported in SkuType Consumption."
```

**Comment by yupwei68** [comment] 2020-05-06 06:35
Hi @alecor191 , Thanks for opening this issue. This is a bug, and we'll fix it later.

**Comment by evertonmc** [comment] 2020-05-11 10:15
Hi @yupwei68, do you already have an ETA oder milestone for this? There is no possible way to use this feature a.t.m.

**Comment by cloud-devlpr** [comment] 2020-06-04 02:16
Is there an update and ETA on this please, my client wants to move to consumption plan and there is no way to deploy this currently.

**Comment by alecor191** [comment] 2020-07-20 06:59
@omgapuppy / @yupwei68 from what I can tell, you looked into this (thanks for that!). Do you know if there is any work planned/ongoing to address this?

**Comment by omgapuppy** [comment] 2020-07-21 14:47
> @omgapuppy / @yupwei68 from what I can tell, you looked into this (thanks for that!). Do you know if there is any work planned/ongoing to address this?

Sorry, I've since stopped looking into it as I didn't have an immediate need or capacity. @yupwei68 looks to have done a significant amount of work around the issue :+1:

**Comment by cvvarunraj** [comment] 2020-07-27 16:52
@yupwei68 Is the fix released in any version of terraform ? was trying to do some consumption tier deployment of api management, but running into the issues mentioned in this thread.

**Comment by nojaf** [comment] 2020-07-27 17:23
@cvvarunraj while waiting for this fix, I've deployed my API management via ARM.
Code is in F# but you'll get the gist:
```fsharp
    let stackName = Pulumi.Deployment.Instance.StackName
    // Create an Azure Resource Group
    let resourceGroupName = sprintf "rg-nojaf-apim-%s" stackName
    let resourceGroupArgs = ResourceGroupArgs(Name = input resourceGroupName)
    let resourceGroup = ResourceGroup(resourceGroupName, args = resourceGroupArgs)

    let arm = """
    {
        "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
        "contentVersion": "1.0.0.0",
        "resources": [{
            "apiVersion": "2019-12-01",
            "name": "nojaf-apim",
            "type": "Microsoft.ApiManagement/service",
            "location": "westeurope",
            "tags": {},
            "sku": {
                "name": "Consumption",
                "capacity": "0"
            },
            "properties": {
                "publisherEmail": "apim@nojaf.com",
                "publisherName": "nojaf"
            }
        }]
    }
    """

    let deployment = TemplateDeployment("nojaf-apim", TemplateDeploymentArgs(ResourceGroupName = io resourceGroup.Name,
                                                                                      TemplateBody = input arm,
                                                                                      DeploymentMode = input "Incremental"))
```

**Comment by thomasf1234** [comment] 2020-08-26 16:39
@here: Is there any update this?  We're having to mix Terraform with manual changes to keep track of them.

**Comment by Justin-DynamicD** [comment] 2020-10-16 21:31
I see agressive off-topic marking, but not a lot of update info.  Has this behavior been confirmed? Is it on the backlogged? do we need more information?

**Comment by c0dingarchit3ct** [comment] 2020-11-03 04:50
I am also blocked on the same issue running v0.13.5

**Comment by denied173** [comment] 2020-11-25 11:09
Hey guys, 

is there any news about the given issue? I'm facing this, too on terraform v0.13.5 :( 

greetings, Dennis

**Comment by a8ree** [comment] 2020-12-04 09:00
I'm having the same issue also. Is this likely to be resolved soon?

**Comment by mdgrotheer** [comment] 2020-12-08 19:22
Bump on 0.13.4

**Closed** 2020-12-21 06:24 UTC
Labels: bug, service/api-management

**Comment by jomafe** [comment] 2021-01-08 18:37
I just tried deploying APIM with sku_name = "Consumption_0" and it works, so thank you!

It seem though that it doesn't accept the following configuration to negotiate client certificates, while this is available through the portal:

  hostname_configuration {
    proxy {
      host_name                     = ...
      negotiate_client_certificate  = true
    }
  }

Is there another way to manage this option? The documentation for 2.42.0 says this should work 

Thanks.
