### ISSUE TITLE
Error: purging Key...Failure responding to request: StatusCode=403, issue after terraform-provider update

### ISSUE THREAD

**Issue by U-bit-solo** [terraform-providers/terraform-provider-azurerm#10271] opened 2021-01-21 15:29 UTC
Error: purging Key "keystxxxxx" (Key Vault "https://akvteu2nubep40.vault.azure.net/"): keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403  Code="Forbidden" Message="The user, group or application 'appid=5xxxxxxx;oid=xxxxxxx-aa5cxxxx;numgroups=1;iss=https://sts.windows.net/xxxxxb7e-28xxxxb/' does not have keys purge permission on key vault 'akvteu2xxxxx;location=eastus2'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"ForbiddenByPolicy"}

The template worked fine until updated New version for terraform-provider-azurerm: 2.43.0

**Comment by tombuildsstuff** [comment] 2021-01-21 15:50
Duplicate of #9984

**Closed by tombuildsstuff** 2021-01-21 15:50 UTC
Labels: duplicate, service/keyvault
