### ISSUE TITLE
Unexpected new value in "azurerm_key_vault_secret" resource

### ISSUE THREAD

**Issue by sorenhansendk** [terraform-providers/terraform-provider-azurerm#6888] opened 2020-05-13 07:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform CLI **v. 0.12.21**
- Azure Provider **v. 1.44.0**

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

<pre>
resource "azurerm_key_vault_secret" "blob_accountkey" {
  name        = "Blob--AccountKey"
  value        = "XXX"
  key_vault_id = azurerm_key_vault.keyvault.id
}
</pre>

### Expected Behavior

The secret should be created in the Keyvault.

### Actual Behavior

The provider throws this error sporadic:

<pre>
Error: Provider produced inconsistent result after apply

When applying changes to azurerm_key_vault_secret.blob_accountkey, provider
"registry.terraform.io/-/azurerm" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
</pre>

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We are not able to reproduce this issue. It happens out of the blue and sporadic.

And it only happens on a Keyvault there is created, right before the secret.

**Comment by neil-yechenwei** [comment] 2020-05-14 02:16
@sorenhansendk , thanks for opening this issue. After tested, seems I cannot repro this issue with below tf config. Maybe I missed something. If you need, you can try below tf config to check whether the issue still exists. Thanks.
```
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-kvs-test"
  location = "westus"
}

resource "azurerm_key_vault" "test" {
  name                = "acctestkv-test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "premium"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
      "delete",
      "set",
    ]
  }
}

resource "azurerm_key_vault_secret" "test" {
  name         = "secret-test"
  value        = "abc123cde345"
  key_vault_id = azurerm_key_vault.test.id
}
```

Result:
```
azurerm_key_vault.test: Creation complete after 2m20s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-kvs-test/providers/Microsoft.KeyVault/vaults/xxxx]
azurerm_key_vault_secret.test: Creation complete after 9s [id=https://xxxx.vault.azure.net/secrets/secret-test/xxxx]

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
```

**Comment by ArcturusZhang** [comment] 2020-06-05 03:39
Hi @sorenhansendk 

It seems both us and you cannot reproduce this issue :(
I would close this issue for now, but if in the future this issue reappeared, please feel free to open a new issue about this and if with logs it would be best. This kind of issue cannot be easily reproduced by its nature, but with logs we can identify the root cause more easily.
Thank you!

**Closed by ArcturusZhang** 2020-06-05 03:39 UTC
Labels: service/keyvault
