### ISSUE TITLE
Issue with azurerm_synapse_workspace module

### ISSUE THREAD

**Issue by raunakjhawar** [terraform-providers/terraform-provider-azurerm#8820] opened 2020-10-09 16:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_synapse_workspace`

There is no support in the module to grant access to the newly created workspace. Azure AD admin has no access to the workspace.

**Comment by njuCZ** [comment] 2020-10-12 06:23
@raunakjhawar could you please given more details ? Do you mean you could successfully created the synapse workspace resource but you could not open the synapse studio? Have you tried adding synapse workspace firewall rules which should inlude your local IP?

**Comment by tombuildsstuff** [comment] 2020-10-12 08:41
hi @raunakjhawar 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-10-12 08:41 UTC

**Comment by raunakjhawar** [comment] 2020-10-12 14:08
@njuCZ - I can create the workspace, but in order to access the studio, I have to manually add a firewall exception or run azurerm_synapse_firewall_rule module. I think this is a gap in the docs.

**Comment by annetle** [comment] 2020-10-29 02:20
@tombuildsstuff I'm not sure but this seems like a bug. And we're running into the same issue. We are deploying successfully but when we go to access the workspace we have a permissions denied. When we create the same resource in the Portal we are automatically added to the Synapse Workspace Admin group (inside of the Synapse Studio). It appears that when we create it using a service principal that does not happen and I'm not sure who would be set as admin in this case. Is this expected behavior? And per @njuCZ Firewall configured correctly which would also be an issue but our IP addresses are added just fine and it's working when we create it manually. Any thoughts on whether this is intended behavior?

**Comment by njuCZ** [comment] 2020-10-29 02:33
@annetle this is the behaviour of Synapse Rest Api. creating synapse workspace will automatically be added to the Synapse Workspace Admin group. You have to add your local IP to firewall rule munally. In the portal, it just wraps these two operations.

**Comment by annetle** [comment] 2020-10-29 02:40
@njuCZ awesome! Thanks so much for your quick response! Ok so I guess the question is then, if I'm creating the workspace using a service principal (not my individual credentials) and that gets added to the Synapse Workspace Admin Group, how can I add others to the group? Is there a rest API I can use? Because it's like we're locked out, I can't use my Portal credentials or anything.

**Comment by njuCZ** [comment] 2020-10-29 02:44
@annetle you could do that by specifying this block: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace#aad_admin

**Comment by annetle** [comment] 2020-10-29 02:53
@njuCZ Yes! We tried that and hoped that would work. Because as you said in the Portal, the creator gets added as the AD Admin AND the Synapse Workspace Admin group. But it appears that it does not add the ad admin to the group!

**Comment by njuCZ** [comment] 2020-10-29 03:28
@annetle I have tried in my local, settings `aad_admin` could update success, and I have verified it in the portal
![tempsnip](https://user-images.githubusercontent.com/2786738/97521698-0d7fa980-19d9-11eb-866a-0569e2c34478.png)

As for synapse studio acess control part, you could fire a microsoft support ticket why the workspace admin does not change. As for assign new access control role, you could try this resource https://github.com/terraform-providers/terraform-provider-azurerm/pull/8863, which will be released today or tomorrow.

**Comment by annetle** [comment] 2020-11-02 03:12
The new release worked! Thank you so much @njuCZ!! Using that resource here did it for us! https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_role_assignment
