### ISSUE TITLE
redirectconfiguration property is missing in ApplicationGateway 

### ISSUE THREAD

**Issue by VaijanathB** [terraform-providers/terraform-provider-azurerm#1368] opened 2018-06-07 22:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If you want to do http to https redirection or redirection to some other end point you can easily do it using RedirectionConfiguration. This is present in Rest API Spec here https://github.com/Azure/azure-rest-api-specs/blob/e02b7682d09d6600aca3a52744413af1c5e15787/specification/network/resource-manager/Microsoft.Network/stable/2017-09-01/applicationGateway.json#L1414

Need to expose this property to make it easier to specify redirection logic. 

### New or Affected Resource(s)

* azurerm_application_gateway

### References
https://docs.microsoft.com/en-us/rest/api/application-gateway/applicationgateways/createorupdate

**Comment by VaijanathB** [comment] 2018-06-07 22:48
Assigning to myself to fix this.

**Comment by tombuildsstuff** [comment] 2018-06-19 11:30
Duplicate of #552 - closing in favour of that

@VaijanathB FYI we're holding off on any Application Gateway enhancements until [this API bug is fixed](https://github.com/Azure/azure-rest-api-specs/issues/2187) - so it may be worth holding off until this is fixed (since the tests can't delete the Network due to the App Gateway still existing; I'm concerned about adding more App Gateway tests since this'll just hit our network quota faster)

**Closed by tombuildsstuff** 2018-06-19 11:30 UTC
Labels: enhancement, microsoft/1, service/application-gateway
