### ISSUE TITLE
Terraform removes Azure subnet route_table_id on subsequent apply

### ISSUE THREAD

**Issue by adhipgupta** [terraform-providers/terraform-provider-azurerm#4730] opened 2019-10-25 21:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = var.rg_name
  location = var.rg_location
}

resource "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  address_space       = [var.address_space]
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  tags                = var.tags
}

resource "azurerm_subnet" "subnet" {
  name                 = var.subnet_names
  virtual_network_name = var.vnet_name
  resource_group_name  = var.rg_name
  address_prefix       = var.subnet_prefixes
}

resource "azurerm_route_table" "privateRoutetable" {
  name                          = "${var.routetable_name}_private"
  location                      = var.rg_location
  resource_group_name  = var.rg_name
  disable_bgp_route_propagation = false

  route {
    address_prefix = "0.0.0.0/0"
    name = var.route_name
    next_hop_type = "VirtualAppliance"
    next_hop_in_ip_address = "<ip_address>"
  }

}

resource "azurerm_subnet_route_table_association" "privateRtSubnetMap" {
  subnet_id      = azurerm_subnet.subnet.id
  route_table_id = azurerm_route_table.privateRoutetable.id
}

```

### Expected Behavior

The route to subnet association mapping shouldn't have been removed. The route_table_id for the subnet should have remained intact

### Actual Behavior
With "terraform apply" I am successfully able create the subnet, route table and subnet_route_table_association through terraform apply. However, when I run "terraform apply" again, the subnet to route_table_id is removed from the subnet. And thus the association as well. The output of "terraform plan" is given below:

```# module.demoAzureAdhip1Subnet.azurerm_subnet.subnet[1] will be updated in-place
  ~ resource "azurerm_subnet" "subnet" {
        address_prefix       = "11.32.1.0/24"
        id                   = "/subscriptions/xxxxxx/resourceGroups/xxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxVnet/subnets/xxxxSubnet1"
        ip_configurations    = [
            "/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/networkInterfaces/xxxxxx/ipConfigurations/xxxx_Intf1",
        ]
        name                 = "Subnet1"
        resource_group_name  = "azureRg1"
      - route_table_id       = "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Network/routeTables/rt_table_private" -> null
        service_endpoints    = []
        virtual_network_name = "demoAzureAdhip1Vnet"
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

* #0000

**Comment by draggeta** [comment] 2019-10-26 21:16
I tried this with the SDK and it seems to be an Azure issue. Found this issue in the SDK repo:
https://github.com/Azure/azure-sdk-for-go/issues/2794

**Comment by tombuildsstuff** [comment] 2019-10-28 05:29
hi @adhipgupta 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3749 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3749 for updates?

Thanks!

**Comment by tombuildsstuff** [comment] 2019-10-28 05:30
@draggeta this isn't an SDK issue, it's where Azure is automatically adding a route table behind the scenes, which is missing from the configuration (which is why this diff is showing in the plan, since that Route Table ID isn't defined in the code)

**Comment by tombuildsstuff** [comment] 2019-10-28 05:39
hey @adhipgupta 

Thanks for opening this issue.

In 1.x versions of the Azure Provider the association between a Subnet and a Route Table need to be specified both [using the `route_table_id` field within the `azurerm_subnet` resource](https://www.terraform.io/docs/providers/azurerm/r/subnet.html) and [using the `azurerm_subnet_route_table_association ` resource](https://www.terraform.io/docs/providers/azurerm/r/subnet_route_table_association.html).

This'll change in the upcoming 2.0 of the Azure Provider (being tracked in #2807) where the `route_table_id` field within the `azurerm_subnet` resource will be removed meaning the `azurerm_subnet_route_table_association` resource becomes the sole way of configuring this association.

Would you be able to take a look and see if specifying this in both places works for you? Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by adhipgupta** [comment] 2019-10-28 05:40
Thanks!

**Closed by tombuildsstuff** 2019-10-28 05:39 UTC

**Comment by draggeta** [comment] 2019-10-28 18:02
Wow, feel a bit like a tool. Turns out I was testing against a subnet that had the route table removed by TF. Missed that one. Sorry for the noise
