### ISSUE TITLE
Can't create azurerm_linux_virtual_machine from custom image which has data disk

### ISSUE THREAD

**Issue by xuhaiwei** [terraform-providers/terraform-provider-azurerm#7460] opened 2020-06-24 02:49 UTC
Version:
Terraform v0.12.26
+ provider.azurerm v2.15.0

I created a custom image which has one OS disk and one Data disk:

`resource "azurerm_image" "saplinux" {
     name                = "TEST"
     location            = "eastus"
     resource_group_name = "rg-eus-prod-001"

    os_disk {
      os_type  = "Linux"
      os_state = "Generalized"
      caching  = "ReadWrite"
      blob_uri = "https://xxx/vhds/A0DFOF44RHE076-1.vhd"
      size_gb  = 27
    }

    data_disk {
      blob_uri = "https://xxx/vhds/A0DFOF44RHE076-2.vhd"
      caching  = "ReadWrite"
      size_gb  = 23
      lun = 0
    }
}`

And use this image to create linux virtual machine:

`resource "azurerm_linux_virtual_machine" "linuxvm" {
      for_each                 = {for line in local.data: line["${var.ConfigItem.VmName}"] => line
                                if upper(line["${var.ConfigItem.VmType}"]) == var.LinuxVm }

    name                     = each.value["${var.ConfigItem.VmName}"]
    location                 = each.value["${var.ConfigItem.Location}"]
    resource_group_name      = each.value["${var.ConfigItem.ResourceGroup}"]
    network_interface_ids    = [element([for nic in azurerm_network_interface.nic:
                                        nic.id if nic.name == each.value["${var.ConfigItem.NICName}"]],
                                        1)]
    size                     = each.value["${var.ConfigItem.VmSize}"]

    os_disk {
        name                 = each.value["${var.ConfigItem.VmName}"]
        caching              = each.value["${var.ConfigItem.OsDiskCaching}"]
        storage_account_type = each.value["${var.ConfigItem.OsStorageAccountType}"]
    }
      source_image_id = azurerm_image.saplinux.id
   
    computer_name  = each.value["${var.ConfigItem.ComputerName}"]
    admin_username = var.VmCredentials.AdminUserName
    admin_password = var.VmCredentials.AdminPassword

`
when ran `terraform apply` I got this error

`Error: Error creating Linux Virtual Machine "vma0dfeustest001" (Resource Group "rg-a0df-eus-prod-001"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile." Target="storageProfile"`

I also tested using other custom image which only has OS disk, the deployment is succeeded. Seems there is problem with Data disk.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-06-24 06:57
hi @xuhaiwei 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6004 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6004 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-24 06:57 UTC
Labels: bug, duplicate, service/virtual-machine

**Comment by xuhaiwei** [comment] 2020-06-24 07:27
Thank you @tombuildsstuff , I will refer to #6004
