### ISSUE TITLE
Attribute mismatch when plan and apply role definition

### ISSUE THREAD

**Issue by ranokarno** [terraform-providers/terraform-provider-azurerm#3926] opened 2019-07-25 11:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform v0.11.10`

### Affected Resource(s)

* `azurerm_role_definition`

### Terraform Configuration Files

```hcl
resource "azurerm_role_definition" "sp_permissions" {
    count       = "${length(var.subscription)}"
    name        = "additional-permission-${count.index}"
    scope       = "/subscriptions/${var.subsription[count.index]}"
    permissions {
        actions     =
        [
            "Microsoft.Authorization/roleDefinitions/write",
            "Microsoft.Authorization/roleAssignments/delete",
            "Microsoft.Authorization/roleDefinitions/delete",
            "Microsoft.Authorization/roleAssignments/write",
            "Microsoft.Authorization/locks/write",
            "Microsoft.Authorization/locks/delete"
        ]
        not_actions = []
    }

    assignable_scopes = [
        "/subscriptions/${var.subsription[count.index]}",
    ]
```

### Debug Output

* terraform plan -out=$tfplan

```
  ~ module.create_sp_permission.azurerm_role_definition.sp_permission[0]
      permissions.#:                    "1" => "1"
      permissions.0.actions.#:          "4" => "6"
      permissions.0.actions.0:          "Microsoft.Authorization/roleDefinitions/write" => "Microsoft.Authorization/roleDefinitions/write"
      permissions.0.actions.1:          "Microsoft.Authorization/roleAssignments/delete" => "Microsoft.Authorization/roleAssignments/delete"
      permissions.0.actions.2:          "Microsoft.Authorization/roleDefinitions/delete" => "Microsoft.Authorization/roleDefinitions/delete"
      permissions.0.actions.3:          "Microsoft.Authorization/roleAssignments/write" => "Microsoft.Authorization/roleAssignments/write"
      permissions.0.actions.4:          "" => "Microsoft.Authorization/locks/write"
      permissions.0.actions.5:          "" => "Microsoft.Authorization/locks/delete"
```

* terraform apply $tfplan

```
* module.create_sp_permission.azurerm_role_definition.sp_permission[0]: azurerm_role_definition.sp_permission.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.10
    Resource ID: azurerm_role_definition.sp_permission.0
    Mismatch reason: attribute mismatch: permissions.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"permissions.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.1":*terraform.ResourceAttrDiff{Old:"Microsoft.Authorization/roleAssignments/delete", New:"Microsoft.Authorization/roleAssignments/delete", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.4":*terraform.ResourceAttrDiff{Old:"", New:"Microsoft.Authorization/locks/write", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.0":*terraform.ResourceAttrDiff{Old:"Microsoft.Authorization/roleDefinitions/write", New:"Microsoft.Authorization/roleDefinitions/write", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.3":*terraform.ResourceAttrDiff{Old:"Microsoft.Authorization/roleAssignments/write", New:"Microsoft.Authorization/roleAssignments/write", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.5":*terraform.ResourceAttrDiff{Old:"", New:"Microsoft.Authorization/locks/delete", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.#":*terraform.ResourceAttrDiff{Old:"4", New:"6", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.2":*terraform.ResourceAttrDiff{Old:"Microsoft.Authorization/roleDefinitions/delete", New:"Microsoft.Authorization/roleDefinitions/delete", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"permissions.0.actions.4":*terraform.ResourceAttrDiff{Old:"", New:"Microsoft.Authorization/locks/write", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.5":*terraform.ResourceAttrDiff{Old:"", New:"Microsoft.Authorization/locks/delete", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "permissions.0.actions.#":*terraform.ResourceAttrDiff{Old:"4", New:"6", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

```

### Expected Behavior

role definition should be modified with additonal scope

### Actual Behavior

terraform plan, and terraform apply cause attribute mismatch

### Steps to Reproduce

1. Teraform plan -out=$tfplan
2. terraform apply $tfplan

**Comment by tombuildsstuff** [comment] 2020-12-14 12:57
hi @ranokarno 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #440 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #440 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-12-14 12:57 UTC
Labels: bug, duplicate, service/roles
