### ISSUE TITLE
API Management APIs failing to create reliably

### ISSUE THREAD

**Issue by prabhakarreddy1234** [terraform-providers/terraform-provider-azurerm#8579] opened 2020-09-22 15:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
  Terraform  : 0.12.28
  AzureRM  :  2.28.0 (can reproduce in all versions)

### Affected Resource(s)

* `azurerm_api_management_api`
* `azurerm_api_management`

### Terraform Configuration Files

```
resource "azurerm_api_management_api" "openapi-download-api" {
  name                = "openapi-download-${var.environment_name}"
  resource_group_name = "${var.resource_prefix}-${local.environment_common}-${var.environment_geography}-network-persistent"
  api_management_name = data.azurerm_api_management.platform.name
  revision            = "1" # update this value when changing the api definition or else it will not refresh the spec!
  display_name        = "Download Open Api - ${local.environment_long_name}"
  description         = "Allows to download the open api definitions. Use the apiDefinitionName matching the product, e.g. apiDefinitionName=industry, apiDefinitionName=marine etc."
  path                = "${var.environment_name}/abc-api/definition"
  protocols           = [var.protocol]
  service_url         = var.api_backend_url

  import {
    content_format = "swagger-json"
    content_value  = file(abspath("../api-management/apis/download-public-api.json"))
  }
}

resource "azurerm_api_management_api" "abc-public-search-api" {
  name                = "abc-public-search-api-${var.environment_name}"
  resource_group_name = "${var.resource_prefix}-${local.environment_common}-${var.environment_geography}-network-persistent"
  api_management_name = data.azurerm_api_management.platform.name
  revision            = replace(var.release_name, ".", "")
  display_name        = "Search abc Api - ${local.environment_long_name}"
  description         = "Contains all of the endpoints to make aggregated data queries on base."
  path                = "${var.environment_name}/api/abc/v1/search"
  protocols           = [var.protocol]
  service_url         = "${var.api_backend_url}/api/abc/v1/search"

  subscription_key_parameter_names {
    header = "Subscription-Key"
    query  = "Subscription-Key"
  }

  import {
    content_format = "openapi-link"
    content_value  = var.abc_public_search_api_link
  }
}
```

API Management resource 
```

resource "azurerm_api_management" "platform" {
  name                = local.gateway_name
  resource_group_name = azurerm_resource_group.gateway-persistent.name
  location            = var.gateway_region
  publisher_name      = var.gateway_publisher_name
  publisher_email     = var.gateway_publisher_email

  sku_name = var.gateway_sku_name

  hostname_configuration {
    proxy {
      host_name            = var.gateway_proxy_host_name
      certificate          = filebase64("${var.tls_certificate_portal_wildcard_file_path}")
      certificate_password = var.tls_certificate_portal_wildcard_password
    }
  }

  protocols {
    enable_http2 = true
  }

  tags = local.common_tags

  lifecycle {
    ignore_changes = [
      hostname_configuration.0.proxy,
      tags
    ]
  }
}

```
### Debug Output
```

Error: waiting on creating/updating API Management API "abc-public-search-api-prd" (Resource Group "<RG Name>"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"API with specified name 'Abc Services Api - Search' already exists","target":"name"}]
  on apis.tf line 84, in resource "azurerm_api_management_api" "abc-public-search-api":
  84: resource "azurerm_api_management_api" "abc-public-search-api" {
```

### Expected Behavior

We expect all APIs to get deployed on the first attempt of `terraform apply` without any side effects.

### Actual Behavior

Terraform fails with the above error. But works on retry (sometimes 2 retry attempts). On first attempt 2 or 3 APIs randomly succeed and rest fails. On 2nd attempt another 2 or 3 APIs succeed. On 3rd retry attempt the remaining 1 or 2 APIs succeed. So we have to run the terraform apply step 3 times on every deployment. 

### Steps to Reproduce
Sample API script is given above. Create a few APIs and run terraform apply on API Management resource. It should be reproducible since we have been facing this issue every day since few months.

### Additional Context
It worked well for a while on `AzureRM : 2.15.0` version. But later it kept failing forever.

* #7195

**Comment by yupwei68** [comment] 2020-09-23 05:35
Hi @prabhakarreddy1234 , thanks for opening this issue. Since the error message indicates that you have created the `azurerm_api_management_api` with the same name, could you please check that you have created them with the same name?

**Comment by prabhakarreddy1234** [comment] 2020-09-23 08:00
Hello @yupwei68 , I'm sure there is no other API with same name. We have only 7 APIs and all with different name. The same script works well after running `terraform apply` just after the error.  I think there is some conflict occurring internally while creating/updating an API in APIM and it's causing this to fail.

**Comment by yupwei68** [comment] 2020-09-23 08:03
Hi @prabhakarreddy1234 Could you provide your configuration of `azurerm_api_management`? Cause the `virtual_network` or other configuration could impact the results.

**Comment by prabhakarreddy1234** [comment] 2020-09-23 08:08
@yupwei68  Updated the post with `azurerm_api_management` configuration.  We are not using `virtual_network`. We use mTLS.

If you observe the API configuration above, we are forcing the API to redeploy every time by giving a random value to `revision`. I think on every `apply` API is getting deleted and recreated. So probably that's where the timing is missing and API is attempted to get created even before it deleted completely.

**Comment by yupwei68** [comment] 2020-09-24 02:50
@prabhakarreddy1234 Thanks for your information. I could reproduce this problem. I have opened an ICM ticket for the service team.

**Comment by yupwei68** [comment] 2020-09-27 01:45
@prabhakarreddy1234 Do some apis share the same "swagger-json file? Does the "swagger-json" file contains tags in api/operation descriptions? The service team has replied that it was caused by design the concurrency issue. As @vfedonkin replied:

> 
> Two api was created at the same time, openapi-download-yup;rev=1 and abc-public-search-api-yup;rev=2
> 
> I believe both APIs contains the same tag, which were saved into database at the same time.
> 
> Second try was successful because the tag was already in the DB so "create tag" query was not sent to database.

**Comment by yupwei68** [comment] 2020-09-29 02:58
@prabhakarreddy1234 For apis that have concurrency issues (they share the same "swagger-json" file or the "swagger-json" files contain the same tags in api/operation description), we could use a dependency to solve this problem. Then they'll be created one by one.  For example, b depends on a, c depends on b, code example would be:
```

resource "azurerm_api_management_api" "openapi-download-api" {
  name                = "openapi-download-${var.environment_name}"
  resource_group_name = "${var.resource_prefix}-${local.environment_common}-${var.environment_geography}-network-persistent"
  api_management_name = data.azurerm_api_management.platform.name
  revision            = "1" # update this value when changing the api definition or else it will not refresh the spec!
  display_name        = "Download Open Api - ${local.environment_long_name}"
  description         = "Allows to download the open api definitions. Use the apiDefinitionName matching the product, e.g. apiDefinitionName=industry, apiDefinitionName=marine etc."
  path                = "${var.environment_name}/abc-api/definition"
  protocols           = [var.protocol]
  service_url         = var.api_backend_url

  import {
    content_format = "swagger-json"
    content_value  = file(abspath("../api-management/apis/download-public-api.json"))
  }
}

resource "azurerm_api_management_api" "abc-public-search-api" {
  name                = "abc-public-search-api-${var.environment_name}"
  resource_group_name = "${var.resource_prefix}-${local.environment_common}-${var.environment_geography}-network-persistent"
  api_management_name = data.azurerm_api_management.platform.name
  revision            = replace(var.release_name, ".", "")
  display_name        = "Search abc Api - ${local.environment_long_name}"
  description         = "Contains all of the endpoints to make aggregated data queries on base."
  path                = "${var.environment_name}/api/abc/v1/search"
  protocols           = [var.protocol]
  service_url         = "${var.api_backend_url}/api/abc/v1/search"

  subscription_key_parameter_names {
    header = "Subscription-Key"
    query  = "Subscription-Key"
  }

  import {
    content_format = "openapi-link"
    content_value  = var.abc_public_search_api_link
  }

  depends_on = [azurerm_api_management_api.openapi-download-api]
}
```

**Comment by prabhakarreddy1234** [comment] 2020-09-29 10:17
@yupwei68  thanks. I added `depends_on` to all 7 APIs. So each API depends on it's previous API. But still all 7 APIs aren't deployed on the first attempt.  5 deployed on 1st attempt and 2 on 2nd attempt. I'm still getting `"API with specified name 'Abc Services Api - Search' already exists","target":"name"` error on first attempt.

If there is a way to see the exact inner exception then that helps.

**Comment by yupwei68** [comment] 2020-09-30 01:28
@prabhakarreddy1234 Would you mind contacting MS support to open an ICM ticket for you to see the exact inner exception? I think Api Management service team could definitely help you.

**Comment by ccapellan** [comment] 2020-10-19 16:40
Was any resolution ever reached?  I'm experiencing the same exact behavior.

**Comment by prabhakarreddy1234** [comment] 2020-10-19 16:44
Nope. MS support team is working on it since couple of weeks.

**Comment by tombuildsstuff** [comment] 2020-10-26 11:55
👋 

Since this appears to be an issue in the Azure API, rather than something specific to Terraform - I'm going to close this issue for the moment (since once this is fixed in the Azure API, this should be fixed in Terraform). Unfortunately I don't think there's a means of working around this from within Terraform at this time (e.g. using Locks to create these sequentially) - since the root-cause for this is the data within the Azure API itself.

Whilst there's a Microsoft Support ticket open, I'd suggest [opening an issue on the Azure Rest API Specs repository too](https://github.com/Azure/azure-rest-api-specs) so that the Service Team can be directly notified here too, which may speed this fix up.

Thanks!

**Closed by tombuildsstuff** 2020-10-26 11:55 UTC
Labels: service/api-management, upstream-microsoft
