### ISSUE TITLE
Error: purging Secret "xyz" (Key Vault "https://abc.vault.azure.net/"): keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NotSupported" Message="Operation \"purge\" is not enabled for this vault."

### ISSUE THREAD

**Issue by TamasSzerb** [terraform-providers/terraform-provider-azurerm#10132] opened 2021-01-11 14:32 UTC
Using:  https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.42.0"
    }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
      recover_soft_deleted_key_vaults = true
    }
  }
}

resource "azurerm_key_vault" "abc" {
...
soft_delete_enabled = false # should be ignored due to new azurerm release
}

resource "azurerm_key_vault_access_policy" "xyz-pol" {
...
  secret_permissions = [
    "backup",
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set"
  ]
}

will result at destroy time:

Error: purging Secret "xyz" (Key Vault "https://abc.vault.azure.net/"): keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NotSupported" Message="Operation \"purge\" is not enabled for this vault."

I know that the keyvault will enforce soft-delete, so these settings are a bit confusing.

On portal.azure.com the keyvault shows:

Soft-delete: Disabled
Purge protection: Disabled

So no idea what is happening here. Any help would be appreciated!

**Comment by tombuildsstuff** [comment] 2021-01-11 17:22
hi @TamasSzerb 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9984 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9984 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-11 17:22 UTC
Labels: duplicate, service/keyvault

**Comment by TamasSzerb** [comment] 2021-01-12 08:31
Hello @tombuildsstuff , I'm fine with it as it is going to be sorted out soon. :)
