### ISSUE TITLE
azurerm_role_assignment Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by isaacdan** [terraform-providers/terraform-provider-azurerm#12108] opened 2021-06-08 09:14 UTC
Team,
My transformer pipeline is failing while creating role assignment to a managed identity which was working fine till azurerm provider 2.61

After upgrading to azurerm provider 2.62 I'm facing this issue. 
Let me know if any additional info needed (screenshot attached
<img width="573" alt="terraformbug" src="https://user-images.githubusercontent.com/52770541/121158482-06baee00-c868-11eb-85c1-b32374a0a18a.PNG">
)

resource "azurerm_role_assignment" "appgw_role" {
depends_on = [azurerm_user_assigned_identity.appgw_identity]
scope = azurerm_user_assigned_identity.appgw_identity[0].id
role_definition_name = "Managed Identity Operator"
principal_id = data.azuread_service_principal.aks_obj_identity.object_id
}

Error message

Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ module.apcfg_kv_db.azurerm_role_assignment.appgw_role[0], provider
│ "module.apcfg_kv_db.provider["registry.terraform.io/hashicorp/azurerm"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by aristosvo** [comment] 2021-06-08 09:29
Hi @isaacdan!

I believe this is a duplicate of #12057, at least six issues covering this issue are opened the last few days. The PR fixing this problem is under review.

Most information how to solve it can be found under #12060

**Comment by magodo** [comment] 2021-06-09 06:17
I'm gonna close this issue as it is fixed by #12076, which is delivered in v2.62.1. Please feel free to reopen if the issue remains.

**Closed by magodo** 2021-06-09 06:17 UTC
Labels: bug, service/authorization
