### ISSUE TITLE
azurerm_api_management TLS settings are counter-intuitive

### ISSUE THREAD

**Issue by easkay** [terraform-providers/terraform-provider-azurerm#4187] opened 2019-08-29 16:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.6
+ provider.azurerm v1.32.1
```

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl

resource azurerm_api_management apim {
  name                = "castlight-${var.environment_short_name}-${var.region_short_name}"
  location            = azurerm_resource_group.apim.location
  resource_group_name = azurerm_resource_group.apim.name
  publisher_name      = "<redacted>"
  publisher_email     = "<redacted>"

  sku {
    name     = "Developer"
    capacity = "1"
  }

security {
    disable_backend_ssl30      = false
    disable_backend_tls10      = false
    disable_backend_tls11      = false
    disable_frontend_ssl30     = false
    disable_frontend_tls10     = false
    disable_frontend_tls11     = false
    disable_triple_des_ciphers = false
  }
}

```

### Debug Output

Will supply if necessary.

### Panic Output

N/A

### Expected Behavior

If the `disable_*` flags are set to `true`, I expect the feature to be disabled/off as reflected in the following portal screenshot.

![Screenshot_2019-08-29_17-23-00](https://user-images.githubusercontent.com/592657/63958152-b81cd500-ca81-11e9-9cd0-9e9dfa7f11a1.png)

### Actual Behavior

 If the `disable_*` flags are set to `true`, the feature is not disabled and is instead _enabled_.

### Steps to Reproduce

1. `terraform apply`

### Notes

Is this intended behaviour? Are the arguments going to be renamed at some point?

**Comment by tombuildsstuff** [comment] 2019-08-29 16:25
hi @easkay 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3125 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3125 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-29 16:25 UTC
Labels: bug, duplicate, service/api-management

**Comment by easkay** [comment] 2019-08-30 08:10
Hi @tombuildsstuff, my bad I couldn't see any existing issues but apparently my search-fu needs improving. Thanks for the response :)
