### ISSUE TITLE
Support for azurerm_application_gateway configuration blocks as separate resources

### ISSUE THREAD

**Issue by crawfs** [terraform-providers/terraform-provider-azurerm#6703] opened 2020-04-30 00:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if the  configuraiton blocks in [azurerm_application_gateway](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html) could have their own resource types, e.g. a resource type for azurerm_application_gateway_http_listener or backend pools etc.

This would be particularly useful for environments where teams would want to minimize costs by having only a single application gateway but still be able to manage the configuration of the application gateway independently in separate infrastructure deployments for different web applications. 

### New or Affected Resource(s)

Affected:
* azurerm_application_gateway

New: 
* azurerm_application_gateway_backend_address_pool
* azurerm_application_gateway_backend_http_settings
* azurerm_application_gateway_http_listener
* azurerm_application_gateway_request_routing_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway_backend_address_pool" "example" {
  name = "testbackend"
  resource_group_name  = "application-gateway-resource-group"
  application_gateway_name = "test-application-gateway"
  ip_addresses = ["10.0.1.5", "10.0.1.6", "10.0.1.7"]
}

resource "azurerm_application_gateway_backend_http_settings" "example" {
  name = "testbackendhttpsettings"
  resource_group_name  = "application-gateway-resource-group"
  application_gateway_name = "test-application-gateway"
  cookie_based_affinity = "Disabled"
  path = "/path1/"
  port = 80
  protocol = "Http"
  request_timeout = 1
}

resource "azurerm_application_gateway_http_listener" "example" {
  name = "testhttplistener"
  resource_group_name  = "application-gateway-resource-group"
  application_gateway_name = "test-application-gateway"
  frontend_ip_configuration_name = "application-gateway-frontendip"
  frontend_port_name = "application-gateway-frontend-port"
  protocol = "Http"
}

resource "azurerm_application_gateway_request_routing_rule" "example" {
  name = "testrequestroutingrule"
  resource_group_name  = "application-gateway-resource-group"
  application_gateway_name = "test-application-gateway"
  rule_type = "Basic"
  http_listener_name = azurerm_application_gateway_http_listener.example.name
  backend_address_pool_name = azurerm_application_gateway_backend_address_pool.example.name
  backend_http_settings_name = azurerm_application_gateway_backend_http_settings.example.name
}
```
Something along those lines, does that make sense?

**Comment by johnnyhuy** [comment] 2020-04-30 00:25
Hey @crawfs small typo `azurerm_applicaiton_gateway_backend_address_pool` = `application`

**Comment by neil-yechenwei** [comment] 2020-04-30 11:08
@crawfs , thanks for opening this issue. May I know what use case you are using would impel you to separate them from `azurerm_application_gateway`?

**Comment by neil-yechenwei** [comment] 2020-04-30 12:14
Seems application gateway requires at least one backend pool and routing rule which must include http listener and http settings at creation.
![image](https://user-images.githubusercontent.com/19754191/80708155-c560f680-8b1d-11ea-86c4-05914b4fe80b.png)
![image](https://user-images.githubusercontent.com/19754191/80708521-664fb180-8b1e-11ea-8574-db8e8550511f.png)

**Comment by alex-3sr** [comment] 2020-05-01 07:35
Hi, it would be a big improvement this one, clearly. And when updating 1 attribute, the plan output will display the localized change instead a big block when you have more than 50 backend !

**Comment by crawfs** [comment] 2020-05-01 08:33
@neil-yechenwei yeah it's entirely possible that this could require changes to the azure resource to accomplish, but based on the actual ARM reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-11-01/applicationgateways it doesn't look like the Azure REST API requires the appligation gateway to be configured with backends and HTTP rules before being deployed.

**Comment by neil-yechenwei** [comment] 2020-05-01 12:40
After tested, seems the provisioned application gateway is also configured with backend pool and HTTP rules using the below ARM template. So seems backend pool and HTTP rules is required to application gateway at creation.
![image](https://user-images.githubusercontent.com/19754191/80805638-31f5f700-8beb-11ea-8183-03c66ebcb962.png)
![image](https://user-images.githubusercontent.com/19754191/80805691-4afea800-8beb-11ea-9f3a-0d3f09bec63d.png)
![image](https://user-images.githubusercontent.com/19754191/80805698-5356e300-8beb-11ea-9d3d-3b1b4a6a46f3.png)
![image](https://user-images.githubusercontent.com/19754191/80805713-5b168780-8beb-11ea-9d04-2a00797e7fd1.png)
![image](https://user-images.githubusercontent.com/19754191/80805732-65388600-8beb-11ea-9d2c-017c775c7638.png)

**Comment by neil-yechenwei** [comment] 2020-05-01 23:10
After double confirmed with service owner of application gateway, they said backend pool and routing rule (http listener and http settings) are required to application gateway at creation. And I also tried arm template in the above link you provided, seems the provisioned application gateway is also configured with backend pool and http rule.

**Comment by crawfs** [comment] 2020-05-04 00:18
Hey @neil-yechenwei excuse my ignorance but isn't the same true for the azurerm_virtual_network and azurerm_subnet resources? The azure portal doesn't allow you to create a virtual network without specifying at least one subnet but the terraform provider can still split virtual networks and subnets into separately managed resources.

**Comment by neil-yechenwei** [comment] 2020-05-06 02:36
According by the reply from service owner of application gateway, I think they are not the same thing.

**Comment by ArcturusZhang** [comment] 2020-06-05 08:03
Hi @crawfs 

I have done some experiments regarding the application gateway api by changing all the `Required` in code to `Optional` and then see what happens. 
It turns out that the service will throw errors when you are not assigning FrontendIpConfiguration, FrontendPort, BackendAddressPool, BackendHttpSettings, HttpListener, RequestRoutingRule during the creation. And also these are reasons why those attributes or blocks are required in terraform.

The big difference between the application gateway and the virtual network is that virtual network is allowed to be created without a subnet.

This means by the service design, you cannot create application gateway without those configurated during its creation, which makes it impossible to decouple. You may know that terraform cannot properly handle both of the inline components and decoupled components. For instance, if you are using the virtual_network with inline subnet definition and the decoupled subnet resource, you will get troubles.

Error messages are like:
```
Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayMustHaveAtleastOneResourceOfType" Message="At least one FrontendIpConfiguration resource must be specified for the Application Gateway /subscriptions/{subsID}/resourceGroups/dapzhang-resources/providers/Microsoft.Network/applicationGateways/example-appgateway."
```
or 
```
Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayMustHaveAtleastOneResourceOfType" Message="At least one FrontendPort resource must be specified for the Application Gateway /subscriptions/{subsID}/resourceGroups/dapzhang-resources/providers/Microsoft.Network/applicationGateways/example-appgateway." Details=[]
```
or 
```
Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayMustHaveAtleastOneResourceOfType" Message="At least one BackendAddressPool resource must be specified for the Application Gateway /subscriptions/{subsID}/resourceGroups/dapzhang-resources/providers/Microsoft.Network/applicationGateways/example-appgateway." Details=[]
```
or 
```
Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayMustHaveAtleastOneResourceOfType" Message="At least one BackendHttpSettings resource must be specified for the Application Gateway /subscriptions/{subsID}/resourceGroups/dapzhang-resources/providers/Microsoft.Network/applicationGateways/example-appgateway." Details=[]
```
or 
```
Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayMustHaveAtleastOneResourceOfType" Message="At least one HttpListener resource must be specified for the Application Gateway /subscriptions/{subsID}/resourceGroups/dapzhang-resources/providers/Microsoft.Network/applicationGateways/example-appgateway." Details=[]
```
or
```
Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayMustHaveAtleastOneResourceOfType" Message="At least one RequestRoutingRule resource must be specified for the Application Gateway /subscriptions/{subsID}/resourceGroups/dapzhang-resources/providers/Microsoft.Network/applicationGateways/example-appgateway." Details=[]
```

Since it is not applicable to decouple on this resource for now, I will close this issue hope you do not mind.

**Closed by ArcturusZhang** 2020-06-05 08:03 UTC
Labels: enhancement, service/application-gateway
