### ISSUE TITLE
error when creating eventhub authorization rule

### ISSUE THREAD

**Issue by ksadineni13** [terraform-providers/terraform-provider-azurerm#12660] opened 2021-07-20 06:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform ~> 0.14.11
- AzureRM ~> 2.68

### Affected Resource(s)

* resource "azurerm_eventhub_authorization_rule" "example"

### Terraform Configuration Files

```hcl
data "azurerm_eventhub_namespace" "namespace" {
  name                = var.eventhub_namespace_name
  resource_group_name = var.resource_group_name
}

data "azurerm_eventhub" "eventhub" {
  name                = var.eventhub_name
  namespace_name      = var.eventhub_namespace_name
  resource_group_name = var.resource_group_name
}

resource "azurerm_eventhub_authorization_rule" "fluentd_eventhub" {
  name                = "testing"
  namespace_name      = data.azurerm_eventhub_namespace.namespace.name
  eventhub_name       = data.azurerm_eventhub.eventhub.name
  resource_group_name = var.resource_group_name
  listen              = false
  send                = true
  manage              = false
}
```

### Debug Output

Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.

  on main.tf line 44, in resource "azurerm_eventhub_authorization_rule" "fluentd_eventhub":
  44: resource "azurerm_eventhub_authorization_rule" "fluentd_eventhub" {

### Panic Output

Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.

  on main.tf line 44, in resource "azurerm_eventhub_authorization_rule" "fluentd_eventhub":
  44: resource "azurerm_eventhub_authorization_rule" "fluentd_eventhub" {

### Expected Behaviour

It should add the mentioned authorization rule in eventhub.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-07-20 07:10
Duplicate of #12387 which has been fixed by #12642 and will go out in this weeks release

**Closed by tombuildsstuff** 2021-07-20 07:10 UTC
Labels: bug, duplicate, regression, service/event-hubs
