### ISSUE TITLE
azurerm_api_management: Support for Management REST API activation

### ISSUE THREAD

**Issue by patst** [terraform-providers/terraform-provider-azurerm#10472] opened 2021-02-04 10:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_api_management` resources created with terraform have the management REST API disabled. 
![image](https://user-images.githubusercontent.com/9567895/106877281-e112b200-66d8-11eb-9844-879cbea6eca7.png)

We would like to enable the API and get the primary and secondary key as output.

The REST API has an endpoint for this called [Tenant  Access](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/tenantaccess)'

### New or Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management" "apim" {
...
  tenant_access {
    enabled = true
  }
...
}
```

### References

Activate Tenant Access: https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/tenantaccess/update
List Secrets : https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/tenantaccess/listsecrets

**Comment by tombuildsstuff** [comment] 2021-02-04 10:55
hi @patst 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8578 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8578 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-04 10:55 UTC
Labels: duplicate, enhancement, service/api-management

**Comment by patst** [comment] 2021-02-04 11:11
sorry I was blind!

I will try to provide a pull request for above issue
