### ISSUE TITLE
Terraform Error reading the advanced threat protection settings of AzureRM Storage Account

### ISSUE THREAD

**Issue by dox1042** [terraform-providers/terraform-provider-azurerm#8700] opened 2020-09-30 19:01 UTC
Currently dealing with an error when I attempt to do a TF plan and reach the error below. 
Error reading the advanced threat protection settings of AzureRM Storage Account.  
I can confirmed that there is no Firewall setup for that storage account. 
I did see that issue #3968 speaks about it but the solution was never explained.

**Comment by tombuildsstuff** [comment] 2020-10-01 07:32
Duplicate of #8686

**Closed by tombuildsstuff** 2020-10-01 07:32 UTC
