### ISSUE TITLE
Failed VM extensions should stay in state in tainted status

### ISSUE THREAD

**Issue by sean-nixon** [terraform-providers/terraform-provider-azurerm#6980] opened 2020-05-18 13:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If a virtual machine extension fails to install (i.e. goes to status "Provisioning failed" in the Portal), currently the provider fails the operation and does not record anything in state, even though the extension resource exists in Azure still. As a result, Terraform tries to create the extension on the next run and fails because the resource already exists.

Instead, if the extension fails to provision, Terraform should keep the resource in state in a "tainted" state so that the extension will be deleted and created again by Terraform during the next run.

Currently, my workaround is to delete the extension manually in the Portal, but it would be extremely nice to let Terraform handle that.

### New or Affected Resource(s)

* azurerm_virtual_machine_extension

**Comment by ArcturusZhang** [comment] 2020-05-19 11:25
Hi @sean-nixon thanks for this issue!

Terraform does have a `taint` command to mark a resource as `tainted` and in the next apply terraform will destroy it and recreate. But this may not be applicable for your case, since the resource is not managed by terraform yet.

I wonder would it be applicable to destroy the resource when a creation fails? In fact I assume that Azure should have done this to keep idempotence.

**Comment by tombuildsstuff** [comment] 2020-05-19 13:37
hey @sean-nixon 

Thanks for opening this issue.

Unfortunately Azure uses the state "Failed" to mean several things other than "this resource is unusable" - which means that we can't rely on "Failed" meaning "this should be tainted". To give a couple of examples:

* Using the (now older approach) for encrypting disks in VM's, where they're encrypted in the background with Bitlocker (Windows) or the Linux equivalent - if encryption takes over (I think) 3 hours, the VM Extension and VM are marked as "Failed", but the encryption keeps going
* Booting a Virtual Machine which takes longer than (I think) ~120m to boot, is marked as "Failed" even if it eventually comes up (again related to Encryption)

Whilst both of these scenarios could be considered edge-cases, there's a sufficient number of hard-coded timeouts within the Azure API's where "Failed" can mean numerous things (across different Resources/API's). There's also an additional issue specific to with VM extensions, where these are /supposed/ to be idempotent - but (at least with the majority I've seen) aren't - as such "uninstalling" the extension isn't necessarily doing all of the necessary cleanup, and at times (such as during development) it can be preferable to taint the Virtual Machine instead.

Whilst we could look to mark these resources as tainted automatically - since the configuration varies per environment, how this should be "recovered" varies depending on the resources involved. As such we need to delegate to users on the best path forward for your specific applications here - in some circumstances that may be automatically tainting, but in others that could be automatically deleting/recreating - it's not really something that we can generalize in the Azure Provider specifically.

There's an argument that this could be a useful thing to expose in Terraform Core - for example if the provisioning fails, then I'd like to try deleting & re-creating/waiting ~5m then trying again (or something else altogether) - however unfortunately that's a change which would need to be made in Terraform Core, rather than something specific to a Provider.

However since this behaviour is currently by design (and unfortunately isn't something we have plans to change) - I'm going to close this issue for the moment. In the interim it should be possible to delete this extension using the Azure CLI/Portal as you've mentioned - or by tainting the parent Virtual Machine. Alternatively as mentioned above it could make sense to open a feature request in Terraform Core since this preference could vary per user environment/resource (and would need to be there so that Providers could handle that).

Thanks!

**Closed by tombuildsstuff** 2020-05-19 13:37 UTC
Labels: question, service/virtual-machine-extensions
