### ISSUE TITLE
The Resource 'xxx' under resource group 'compaas-01-dev' was not found

### ISSUE THREAD

**Issue by SerenaLi279** [terraform-providers/terraform-provider-azurerm#5255] opened 2019-12-25 08:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.17
terraform-provider-azurerm_v1.37.0_x4
(PS: it works well when use terraform-provider-azurerm_v1.31.0_x4)

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_network_interface" "net-02" {
  name = "${var.tag_name}-net-02"
  location = var.location
  resource_group_name = var.resource_group_name

  ip_configuration {
    name = "${var.tag_name}-net-02"
    subnet_id = data.azurerm_subnet.net-02.id
    private_ip_address_allocation = "Dynamic"

  }

  tags = {
    Name = var.tag_name
  }
  lifecycle {
    ignore_changes = [
        tags,
    ]
  }
}


resource "azurerm_virtual_machine" "vm" {
  name = var.tag_name
  location = var.location
  resource_group_name = var.resource_group_name
  network_interface_ids = [
azurerm_network_interface.net-01.id,
azurerm_network_interface.net-02.id]

  primary_network_interface_id = azurerm_network_interface.net-01.id
  vm_size = var.vm_size
...
}
```

### Debug Output
From terraform log
1. 2019-12-24 08:56:03: jade-centos-cswe-01-net-01 Creation complete then create jade-centos-cswe-01.azurerm_virtual_machine.vm
```hcl
2019-12-24 08:56:03,178 DEBUG: module.jade-centos-cswe-01.azurerm_network_interface.net-01: Creation complete after 4s [id=/subscriptions/66e8f030-dbe5-4677-bd29-06b963faa0ac/resourceGroups/compaas-01-dev/providers/Microsoft.Network/networkInterfaces/jade-centos-cswe-01-net-01]
2019-12-24 08:56:03,217 DEBUG: module.jade-centos-cswe-01.azurerm_virtual_machine.vm: Creating...
```
2. 2019-12-24 09:03:15: but fail for centos-cswe-01-net-01' under resource group 'compaas-01-dev' was not found
```hcl
2019-12-24 09:03:15,241 DEBUG: 
2019-12-24 09:03:15,241 DEBUG: Error: Error determining IP Address for Virtual Machine "jade-centos-cswe-01" (Resource Group "compaas-01-dev"): Error obtaining NIC "jade-centos-cswe-01-net-01" (Resource Group "compaas-01-dev"): network.InterfacesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/networkInterfaces/jade-centos-cswe-01-net-01' under resource group 'compaas-01-dev' was not found."
2019-12-24 09:03:15,242 DEBUG: 
2019-12-24 09:03:15,242 DEBUG:   on modules/instance/jade-centos/group_02/main.tf line 113, in resource "azurerm_virtual_machine" "vm":
2019-12-24 09:03:15,242 DEBUG:  113: resource "azurerm_virtual_machine" "vm" {
2019-12-24 09:03:15,242 DEBUG: 
2019-12-24 09:03:15,242 DEBUG: 
2019-12-24 09:03:19,472  INFO: 
Terraform create failed.
```
3. check this interface jade-centos-cswe-01-net-01 from azure portal, it exists ----that means it has beed created complete by terraform indeed

### Expected Behavior
Could create jade-centos-cswe-01.azurerm_virtual_machine.vm successfully with jade-centos-cswe-01-net-01(because it's Creation complete in 08:56:03)

### Actual Behavior
1. 2019-12-24 09:03:15: but fail for centos-cswe-01-net-01' under resource group 'compaas-01-dev' was not found
2. This interface jade-centos-cswe-01-net-01 will not be deleted when run terraform destroy, should delete it manually

### Steps to Reproduce
This issue does not always happen( I try 3 times and 1 time fail) 

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2020-01-09 12:04
hi @SerenaLi279 

Thanks for opening this issue.

So that we can take a look into this would you mind providing a full Terraform Configuration which reproduces this issue?

Thanks!

**Comment by SerenaLi279** [comment] 2020-01-14 06:19
@tombuildsstuff 
Here is the full Terraform Configuration:
```hcl

variable "location" {default = "East US"}
variable "ssh_username" {default = "cloud-user"}
variable "image_name" {}
variable "image_rg" {}
variable "vm_size" {}
variable "user_data_file" {}
variable "tag_name" {}
variable "zone" {default = 0}
variable "role" {}
variable "admin_username" {  default = "cloud-user"}
variable "ssh_key" {default = "/root/CSF-CLCM/terraform/azure/resources/generated_pub_key.jade-centos"}
variable "resource_group_name" {}


resource "azurerm_public_ip" "pub-ip" {
  name                = "${var.tag_name}-PublicIp"
  location            = var.location
  resource_group_name = var.resource_group_name
  allocation_method   = "Static"
  sku = "Standard"
  tags = {
    Name = var.tag_name
  }
  lifecycle {
    ignore_changes = [
        tags,
    ]
  }


}

data "azurerm_subnet" "net-01" {
  name = "ncm-dualstack-01"
  virtual_network_name = "ncm-dualstack"
  resource_group_name = var.resource_group_name
}

data "azurerm_network_security_group" "nsg-net-01" {
  name                = "ncm-deployment-sg"
  resource_group_name = var.resource_group_name
}

resource "azurerm_network_interface" "net-01" {
  name = "${var.tag_name}-net-01"
  location = var.location
  resource_group_name = var.resource_group_name

  ip_configuration {
    name = "${var.tag_name}-net-01"
    subnet_id = data.azurerm_subnet.net-01.id
    private_ip_address_allocation = "Dynamic"

        public_ip_address_id = azurerm_public_ip.pub-ip.id
  }

  tags = {
    Name = var.tag_name
  }
  lifecycle {
    ignore_changes = [
        tags,
    ]
  }
}


data "azurerm_subnet" "net-02" {
  name = "ncm-dualstack-02"
  virtual_network_name = "ncm-dualstack"
  resource_group_name = var.resource_group_name
}

data "azurerm_network_security_group" "nsg-net-02" {
  name                = "ncm-deployment-sg"
  resource_group_name = var.resource_group_name
}

resource "azurerm_network_interface" "net-02" {
  name = "${var.tag_name}-net-02"
  location = var.location
  resource_group_name = var.resource_group_name

  ip_configuration {
    name = "${var.tag_name}-net-02"
    subnet_id = data.azurerm_subnet.net-02.id
    private_ip_address_allocation = "Dynamic"

  }

  tags = {
    Name = var.tag_name
  }
  lifecycle {
    ignore_changes = [
        tags,
    ]
  }
}


data "azurerm_storage_account" "asa" {
  name                = "compaas01devdiag949"
  resource_group_name = var.resource_group_name
}

data "azurerm_image" "image" {
  name                = var.image_name
  resource_group_name = var.image_rg
}

resource "azurerm_virtual_machine" "vm" {
  name = var.tag_name
  location = var.location
  resource_group_name = var.resource_group_name
  network_interface_ids = [
azurerm_network_interface.net-01.id,
azurerm_network_interface.net-02.id]

  primary_network_interface_id = azurerm_network_interface.net-01.id
  vm_size = var.vm_size

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = true

  # Uncomment this line to delete the data disks automatically when deleting the VM
  delete_data_disks_on_termination = true

  storage_image_reference {
    id = data.azurerm_image.image.id
  }

  storage_os_disk {
    name = "${var.tag_name}-osdisk"
    caching = "ReadWrite"
    create_option = "FromImage"
    managed_disk_type = "Standard_LRS"
    os_type = "Linux"
  }

  os_profile {
    computer_name  = var.tag_name
    admin_username = var.admin_username
    custom_data = file(var.user_data_file)
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path     = "/home/${var.admin_username}/.ssh/authorized_keys"
      key_data = file(var.ssh_key)
    }

  }

  boot_diagnostics {
    enabled = "true"
    storage_uri = data.azurerm_storage_account.asa.primary_blob_endpoint
    }

  lifecycle {
    ignore_changes = [
        tags,
    ]
  }

  tags = {
    Name = var.tag_name
    sshUser = var.ssh_username
    role = var.role
  }

}

resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 30"
  }
  depends_on = [azurerm_virtual_machine.vm]
}

resource "azurerm_managed_disk" "disk-01" {
  name                 = "${var.tag_name}-disk-sdc"
  location             = var.location
  resource_group_name  = var.resource_group_name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "40"
  tags = {
    Name = "${var.tag_name}-disk-01"
  }


  lifecycle {
    ignore_changes = [
        tags,
    ]
  }


}

resource "azurerm_virtual_machine_data_disk_attachment" "attach-disk-01" {
  managed_disk_id    = azurerm_managed_disk.disk-01.id
  virtual_machine_id = azurerm_virtual_machine.vm.id
  lun                = "1"
  caching            = "ReadWrite"
  depends_on = [null_resource.delay]
}

resource "azurerm_managed_disk" "disk-02" {
  name                 = "${var.tag_name}-disk-sdd"
  location             = var.location
  resource_group_name  = var.resource_group_name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "10"
  tags = {
    Name = "${var.tag_name}-disk-02"
  }


  lifecycle {
    ignore_changes = [
        tags,
    ]
  }


}

resource "azurerm_virtual_machine_data_disk_attachment" "attach-disk-02" {
  managed_disk_id    = azurerm_managed_disk.disk-02.id
  virtual_machine_id = azurerm_virtual_machine.vm.id
  lun                = "2"
  caching            = "ReadWrite"

  depends_on = [azurerm_virtual_machine_data_disk_attachment.attach-disk-01]
}

resource "azurerm_managed_disk" "disk-03" {
  name                 = "${var.tag_name}-disk-sde"
  location             = var.location
  resource_group_name  = var.resource_group_name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "20"
  tags = {
    Name = "${var.tag_name}-disk-03"
  }


  lifecycle {
    ignore_changes = [
        tags,
    ]
  }


}

resource "azurerm_virtual_machine_data_disk_attachment" "attach-disk-03" {
  managed_disk_id    = azurerm_managed_disk.disk-03.id
  virtual_machine_id = azurerm_virtual_machine.vm.id
  lun                = "3"
  caching            = "ReadWrite"

  depends_on = [azurerm_virtual_machine_data_disk_attachment.attach-disk-02]
}

resource "azurerm_managed_disk" "disk-04" {
  name                 = "${var.tag_name}-disk-sdf"
  location             = var.location
  resource_group_name  = var.resource_group_name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "10"
  tags = {
    Name = "${var.tag_name}-disk-04"
  }


  lifecycle {
    ignore_changes = [
        tags,
    ]
  }


}

resource "azurerm_virtual_machine_data_disk_attachment" "attach-disk-04" {
  managed_disk_id    = azurerm_managed_disk.disk-04.id
  virtual_machine_id = azurerm_virtual_machine.vm.id
  lun                = "4"
  caching            = "ReadWrite"

  depends_on = [azurerm_virtual_machine_data_disk_attachment.attach-disk-03]
}
```

**Comment by tombuildsstuff** [comment] 2021-02-04 11:28
👋 

Apologies for the delayed reply here.

At this point in time the older `azurerm_virtual_machine` resource has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Since the older `azurerm_virtual_machine` resource has fallen out of sync from the behaviour of the Azure API, to avoid unintentionally breaking users relying on this behaviour the older resources are feature-frozen.

As this resource is feature-frozen to maintain compatibility, I'm going to close this issue for the moment - but I'd recommend instead checking out the `azurerm_linux_virtual_machine` resource, which better represents how the Azure API behaves for this resource.

Thanks!

**Closed by tombuildsstuff** 2021-02-04 11:28 UTC
Labels: question, service/virtual-machine
