### ISSUE TITLE
Support for 'UltraSSD_LRS' as the managed_disk_type option in the 'storage_data_disk' while creating a VMblock 

### ISSUE THREAD

**Issue by normseq** [terraform-providers/terraform-provider-azurerm#3795] opened 2019-07-05 09:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, an UltraSSD disk can be created separately using azure_rm_managed_disk. 
However the 'storage_data_disk' block in the azurerm_virtual_machine doesn't support creation of an UltraSSD managed disk. 
UltraSSD_LRS needs to be added as an option to the managed_disk_type property in the 'storage_data_disk' block
### New or Affected Resource(s)

* azurerm_virtual_machine
*azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
"managed_disk_type": {
							Type:     schema.TypeString,
							Optional: true,
							Computed: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(compute.StorageAccountTypesPremiumLRS),
								string(compute.StorageAccountTypesStandardLRS),
								string(compute.StorageAccountTypesStandardSSDLRS),
								string(compute.StorageAccountTypesUltraSSDLRS),
							}, true),
						},


```

### References
https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html 
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html 

* #0000

**Comment by tombuildsstuff** [comment] 2019-07-07 17:44
hi @normseq 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3765 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3765 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-07-07 17:44 UTC
