### ISSUE TITLE
storage_data_disk: wrong size of managed disk detected if vm is stopped

### ISSUE THREAD

**Issue by jodok** [terraform-providers/terraform-provider-azurerm#539] opened 2017-11-08 21:35 UTC
### Terraform Version
v1.8.0

### Affected Resource(s)
- storage_data_disk

### Terraform Configuration Files
```hcl
resource "azurerm_virtual_machine" "machine" {
  ...
  storage_data_disk {
    name          = "mydisk"
    caching       = "ReadWrite"
    create_option = "Empty"
    disk_size_gb  = 64
    lun           = 0
  }
```

### Debug Output
```
* azurerm_virtual_machine.machine: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ResizeDiskError" Message="Managed disk resize via Virtual Machine 'machine' is not allowed. Please resize disk resource at /subscriptions/.../resourceGroups/.../providers/Microsoft.Compute/disks/mydisk."
* azurerm_virtual_machine.machine[2]: 1 error(s) occurred:
```

### Expected Behavior
terraform should do nothing

### Actual Behavior
terraform tries to upsize the disk from 0 to 64GB

### Steps to Reproduce
create virtual machine with managed disk, stop vm, run apply again

**Comment by JunyiYi** [comment] 2018-04-02 21:35
Root Cause: A stopped virtual machine will return empty OS disks and data disks. (You can also observe this behavior in "Azure portal -> virtual machine -> Disks" page).

**Comment by metacpp** [comment] 2018-04-03 21:46
@jodok This issue is the same one as #555 , we will close this one as duplicate and use that one to track the fix effort.

**Closed** 2018-04-03 21:55 UTC
Labels: M1, M1-priority, bug, duplicate, microsoft/1, microsoft/3, service/disks, upstream-microsoft

**Comment by metacpp** [comment] 2018-04-04 17:30
@jodok this is being tracked by issue #555, that's why we closed it as duplicate.
