### ISSUE TITLE
Can not  get data.azurerm_policy_definition  id by using simplified Chinese  Policy name 

### ISSUE THREAD

**Issue by aaaaasam** [terraform-providers/terraform-provider-azurerm#5883] opened 2020-02-25 10:10 UTC
### Run normally
```hcl
provider "azurerm" {
    environment = "china"
}

data "azurerm_policy_definition" "example" {
    display_name = "Inherit a tag from the subscription if missing"
}
```
## Run Error
```hcl
provider "azurerm" {
    environment = "china"
}

data "azurerm_policy_definition" "example" {
    display_name = "应加密未附加的磁盘"
}
```

### Debug Output

> Use English name

```text
sam@azurepolicy $ ../terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_policy_definition.policy: Refreshing state... [id=/subscriptions/<subid>/providers/Microsoft.Authorization/policyDefinitions/testpolicyformterraform]
data.azurerm_policy_definition.example: Refreshing state...

------------------------------------------------------------------------
```

> Use simplified Chinese name

```text
sam@azurepolicy $ ../terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.azurerm_policy_definition.example: Refreshing state...
azurerm_policy_definition.policy: Refreshing state... [id=/subscriptions/e211ac72-7bf3-4cad-a344-bea6c83b75e5/providers/Microsoft.Authorization/policyDefinitions/testpolicyformterraform]

Error: Error loading Policy Definition List: could not find policy '应加密未附加的磁盘'

  on customrole.tf line 5, in data "azurerm_policy_definition" "example":
   5: data "azurerm_policy_definition" "example" {
```

### Important Factoids

```text
The Policy name '应加密未附加的磁盘'  exists in azure China
```

**Comment by yupwei68** [comment] 2020-06-01 07:06
Hi @aaaaasam , thanks for opening this issue. I have tried your code in azurerm 2.12.0, sorry that I can't reproduce this error. 
Would you like to try the latest provider azurerm version? If this error still runs out in the latest version, would you like to provide the policy definition tf configuration?
```
$ terraform state show data.azurerm_policy_definition.example
# data.azurerm_policy_definition.example:
data "azurerm_policy_definition" "example" {
    display_name = "应加密未附加的磁盘"
    id           = "/subscriptions/XX/providers/Microsoft.Authorization/policyDefinitions/XX"
    metadata     = jsonencode(
        {
            createdBy = "XX"
            createdOn = "2020-06-01T06:57:22.5813345Z"
            updatedBy = null
            updatedOn = null
        }
    )
    name         = "XX"
    parameters   = jsonencode(
        {
            allowedLocations = {
                metadata = {
                    description = "The list of allowed locations for resources."
                    displayName = "Allowed locations"
                    strongType  = "location"
                }
                type     = "Array"
            }
        }
    )
    policy_rule  = jsonencode(
        {
            if   = {
                not = {
                    field = "location"
                    in    = "[parameters('allowedLocations')]"
                }
            }
            then = {
                effect = "audit"
            }
        }
    )
    policy_type  = "Custom"
    type         = "Microsoft.Authorization/policyDefinitions"
}
```

**Comment by ArcturusZhang** [comment] 2020-06-05 09:09
Hi @aaaaasam 

Could you please have a try on the latest provider? Since we could not reproduce this, I would close this issue hope you would not mind. If the issue persist, please feel free to reopen or/and comment.

And as a valid work around, the latest version provider provides the function of getting data source of policy definition by its `name`, which only allows letters and numbers, and I believe this issue would never happen if you switch to getting policy definition data sources by their names.

Thank you!

**Closed by ArcturusZhang** 2020-06-05 09:09 UTC
Labels: bug, service/policy
