### ISSUE TITLE
azurerm_signalr_service fails with 'ID was missing the `signalR` element'

### ISSUE THREAD

**Issue by arkiaconsulting** [terraform-providers/terraform-provider-azurerm#5714] opened 2020-02-12 19:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.44.0

### Affected Resource(s)

azurerm_signalr_service

### Configuration files
```
resource "azurerm_signalr_service" "main" {
  name                = local.naming.signalr
  location            = var.location
  resource_group_name = azurerm_resource_group.main.name

  sku {
    name     = "Standard_S1"
    capacity = 1
  }

  features {
    flag  = "ServiceMode"
    value = "ServerLess"
  }

  features {
    flag  = "EnableConnectivityLogs"
    value = "True"
  }
}
```

### Expected Behavior

The SignalR resource is created

### Actual Behavior

The SignalR resource is not created, and the terrafom exits with the following
Error: ID was missing the `signalR` element

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The same configuration with the provider 1.43.0 ends successfuly.

**Comment by tombuildsstuff** [comment] 2020-02-13 07:56
hi @arkiaconsulting 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #5715 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5715 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-02-13 07:56 UTC
