### ISSUE TITLE
Issue with local-exec -  Run Connect-AzureRmAccount to login.

### ISSUE THREAD

**Issue by gidmaster** [terraform-providers/terraform-provider-azurerm#4686] opened 2019-10-22 19:41 UTC
Hi guys,

I have issue with terrafrom local-exec and Azure DevOps Powershell task.

I have a PowerShell script (1) which run a several `terraform apply` commands to deploy some infrastructure in Azure. One of the terraform modules contains local-exec provisioner that runs PowerShell script (2) which uses  AzureRM module. 
So I use `Connect-AzureRmAccount -ServicePrincipal -Credential $credential -Tenant $tenant` in script (1) to provide credentials.
When I run the script (1) on local machine it works perfectly. But when I run it through PowerShell Task in Azure DevOps script (2) fails with error:
```
 (local-exec): Get-AzureRmResource : Run Connect-AzureRmAccount to login.
```
I thought that context don't saved during the task.
I've tried add `Enable-AzureRmContextAutosave -scope CurrentUser` after login command but it didn't help

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.11.14
AzureRM provider version: 1.35.0

### Affected Resource(s)

* `null_resource`

### Expected Behavior

Complete `terraform apply` command without errors. That means Azure Context provided to local-exec script.

### Actual Behavior

local-exec provisioner failed with error:
```
 (local-exec): Get-AzureRmResource : Run Connect-AzureRmAccount to login.
```

### References

* #2864

**Comment by booyaa** [comment] 2019-11-06 09:27
@gidmaster could you provide a code sample so we can try and reproduce the problem?

**Comment by jdharmon** [comment] 2020-01-24 20:38
I'm having the same issue. If I run `Deploy-WebAppPackage.ps1` in Windows PowerShell, it works fine. Terraform (in the same PowerShell session) fails with the following output:

```
Get-AzureRmWebAppPublishingProfile : No account found in the context. Please login using Connect-AzureRmAccount.
```

Code samples:
```Terraform
provider "azurerm" {
  version = "~> 1.39"
}

resource "null_resource" "deploy_package" {
  provisioner "local-exec" {
    command     = ".\\Deploy-WebAppPackage.ps1 -Source '${local.package_url}' -WebAppname '${azurerm_app_service.irserver.name}' -ResourceGroupName '${var.resource_group_name}'"
    working_dir = path.module
    interpreter = ["PowerShell"]
  }
}
```

**Deploy-WebAppPackage.ps1** 
```powershell
<#
.SYNOPSIS
Deploy Azure Web Application

.PARAMETER Source
Path to package source
.PARAMETER WebAppName
Name of Azure Web App
.PARAMETER ResourceGroupName
Name of web app's resource group
#>

param (
    [Parameter(Mandatory = $true)]
    [Uri]$Source,

    [Parameter(Mandatory = $true)]
    [string]$WebAppName,

    [Parameter(Mandatory = $true)]
    [string]$ResourceGroupName
)

try {
    $outPath = $env:TEMP
    if (-not (Test-Path $outPath)) {
        mkdir $outPath | Out-Null
    }
    $archiveFilename = $Source.Segments[$Source.Segments.Length-1]
    $archivePath = Join-Path $outPath $archiveFilename

    # Download package
    Invoke-WebRequest -Uri $Source -OutFile $archivePath

    # Get credentials
    [xml]$profiles = Get-AzureRmWebAppPublishingProfile -Name $WebAppName -ResourceGroupName $ResourceGroupName
    $profile = $profiles.publishData.publishProfile | Where-Object { $_.publishMethod -eq 'MSDeploy' }

    # Build request
    $credentials = "$($profile.userName):$($profile.userPWD)"
    $authToken = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes($credentials))
    $headers = @{
        Authorization = "Basic $authToken"
    }
    $url = "https://$($profile.publishUrl)/api/zipdeploy?isAsync=true"
    Invoke-WebRequest -Uri $url -Method Post -Headers $headers -InFile $archivePath -ContentType 'application/zip'
}
catch {
    Write-Error $_
    exit 1
}
```

**Comment by petr-x** [comment] 2020-09-29 15:15
Terraform open new session of Powershell in local-exec, it doesn't use your session/profile. You need to pass credentials to your script to be able to authenticate.

**Comment by tombuildsstuff** [comment] 2020-09-29 15:29
hi @gidmaster 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-09-29 15:29 UTC
Labels: question
