### ISSUE TITLE
New Resource: azurerm_route_filter

### ISSUE THREAD

**Issue by Midacts** [terraform-providers/terraform-provider-azurerm#2574] opened 2018-12-26 20:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_route_filter

### Potential Terraform Configuration

```hcl
resource "azurerm_route_filter" "test" {
  name            = "test-rf"
  resource_group  = "testrg"
  location        = "West US"
  rules           = {
    Access        = "Allow"
    Communities   = [
      "comm1",
      "comm2",
    ]
  }
  peerings        = [
    "subscription/xxxx/..."
  ]
  tags            = {
    tag1 = "tag1"
    tag2 = "tag2"
  }
}
```

### References

* https://docs.microsoft.com/en-us/powershell/module/azurerm.network/new-azurermroutefilter?view=azurermps-6.13.0

**Comment by uberrich** [comment] 2019-04-25 21:26
Duplicate of #1083

**Comment by tombuildsstuff** [comment] 2019-05-04 18:51
@uberrich thanks for the heads up - I'd agree this is a duplicate of #1083. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1083

Thanks!

**Closed by tombuildsstuff** 2019-05-04 18:51 UTC
Labels: new-resource
