### ISSUE TITLE
Disks are not encrypted using azurerm_disk_encryption_set on azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by janlunddk** [terraform-providers/terraform-provider-azurerm#5922] opened 2020-02-26 22:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v2.0.0
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_disk_encryption_set`
* `azurerm_windows_virtual_machine`
* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_key" "vmtest-key_disk_enc_key" {
  name                 = "DISKENCRYPTION-KEY"
  key_vault_id         = module.vmtest_keyvault.id
  key_type             = "RSA"
  key_size             = 2048
  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_disk_encryption_set" "vmtest-enc-set" {
  name                = "vmtest-enc-set"
  resource_group_name = data.azurerm_resource_group.product-rg.name
  location            = data.azurerm_resource_group.product-rg.location
  key_vault_key_id    = azurerm_key_vault_key.vmtest-key_disk_enc_key.id
  
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_key_vault_access_policy" "vmtest-disk-encryption" {
  key_vault_id = module.vmtest_keyvault.id
  tenant_id = azurerm_disk_encryption_set.vmtest-enc-set.identity.0.tenant_id
  object_id = azurerm_disk_encryption_set.vmtest-enc-set.identity.0.principal_id
  key_permissions = [
      "create",
      "get",
      "delete",
      "list",
      "wrapkey",
      "unwrapkey"
        ]
  secret_permissions = [
      "get",
      "delete",
      "set",
    ]
}

resource "azurerm_role_assignment" "disk-encryption-read-keyvault" {
  scope                = module.vmtest_keyvault.id
  role_definition_name = "Reader"
  principal_id         = azurerm_disk_encryption_set.vmtest-enc-set.identity.0.principal_id
}

resource "azurerm_windows_virtual_machine" "vmtest-vm" {
  name                = "vmtest-vm"
  location            = data.azurerm_resource_group.product-rg.location
  resource_group_name = data.azurerm_resource_group.product-rg.name
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password = random_string.vmtest-vm-password.result

  network_interface_ids = [
    azurerm_network_interface.vmtest-vm-nic.id,
  ]
  
  os_disk {
    caching                = "ReadWrite"
    disk_encryption_set_id = azurerm_disk_encryption_set.vmtest-enc-set.id
    storage_account_type   = "Standard_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }

}


resource "azurerm_public_ip" "vmtest-pip" {
  name                = "vmtest-pip"
  location            = data.azurerm_resource_group.product-rg.location
  resource_group_name = data.azurerm_resource_group.product-rg.name
  allocation_method   = "Static"
  domain_name_label   = "vmtest"
  tags = local.common_tags
}

resource "azurerm_network_interface" "vmtest-vm-nic" {
  name                = "${var.product-prefix}-vmtest-vm-nic"
  location            = data.azurerm_resource_group.product-rg.location
  resource_group_name = data.azurerm_resource_group.product-rg.name
  enable_accelerated_networking = true
  
  ip_configuration {
    name                          = "vmtestconf"
    subnet_id                     = azurerm_subnet.vmtest-vmtest-subnet.id
    public_ip_address_id          = azurerm_public_ip.vmpip.id
    private_ip_address_allocation = "Dynamic"
  }

  tags = local.common_tags
}

resource "random_string" "vmtest-vm-password" {
  length           = 20
  upper            = true
  lower            = true
  number           = true
  special          = true
  min_upper        = 2
  min_lower        = 2
  min_numeric      = 2
  min_special      = 1
  override_special = "#$%&()-_=+<>:"
}

resource "azurerm_managed_disk" "vmdatadisk" {
  count                = 1
  name                 = "vmdatadisk0${count.index}"
  location             = data.azurerm_resource_group.product-rg.location
  resource_group_name  = data.azurerm_resource_group.product-rg.name
  storage_account_type = "Standard_LRS"

  create_option        = "Empty"
  disk_size_gb         = "256"
  
  disk_encryption_set_id = azurerm_disk_encryption_set.vmtest-enc-set.id
  tags = local.common_tags

}

resource "azurerm_virtual_machine_data_disk_attachment" "datadiskattachment" {
  count = 1
  managed_disk_id    = azurerm_managed_disk.vmdatadisk[count.index].id
  virtual_machine_id = azurerm_windows_virtual_machine.vmtest-vm.id
  lun                =  count.index
  caching            = "ReadWrite"
}

```

### Expected Behavior

OS Disk and Data Disk should have been encrypted.

### Actual Behavior

Disks are not encrypted. In Azure portal you can see that the two disks are associated with the disk encryption set, but when looking at the disks on the VM resource, encryption is "Not Enabled" on both disks.

`Get-AzVmDiskEncryptionStatus  -ResourceGroupName MyResourceGroup -VMName MyVMName`

reports

```
OsVolumeEncrypted          : NotEncrypted
DataVolumesEncrypted       : NotEncrypted
OsVolumeEncryptionSettings :
ProgressMessage            : No Encryption extension or metadata found on the VM
```

Adding the Excryption Extension is not documented in the `azurerm_disk_encryption_set`.
However, when adding the encryption extension i get an error :

```
=<nil> Code="OperationNotAllowed" Message="Disk encryption set resource is not allowed for the disks with disk encryption settings. Please clear encryption settings and Azure Disk Encryption extension in the VM model."

  on webtier.vm.tf line 248, in resource "azurerm_virtual_machine_extension" "vmtest_disk_encryption_windows":
 248: resource "azurerm_virtual_machine_extension" "vmtest_disk_encryption_windows" {
```

The terraform code for the extension:

```
resource "azurerm_virtual_machine_extension" "vmtest_disk_encryption_windows" {
  name                          = "VMestDiskEncryption"
  virtual_machine_id   = azurerm_windows_virtual_machine.vmtest-vm.id
  publisher            = "Microsoft.Azure.Security"
  type                 = "AzureDiskEncryption"
  type_handler_version = "2.2"
  auto_upgrade_minor_version    = true

  settings = <<SETTINGS
  {
    "EncryptionOperation": "EnableEncryption",
    "KeyVaultURL": "https://${module.vmtest_keyvault.name}.vault.azure.net",
    "KeyVaultResourceId": "${module.vmtest_keyvault.id}",
    "KeyEncryptionKeyURL": "${azurerm_key_vault_key.vmtest-key_disk_enc_key.id}",
    "KekVaultResourceId": "${module.vmtest_keyvault.id}",
    "KeyEncryptionAlgorithm": "RSA-OAEP",
    "VolumeType": "All"
  }
  SETTINGS
 
  tags = local.common_tags
}
```
### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

All resources are created in North Europe
Soft Delete and Purge Protection is set using `azurerm_key_vault` (works fine)

**Comment by ArcturusZhang** [comment] 2020-03-24 00:56
Hi @janlunddk thanks for this issue!
The command you are using `Get-AzVmDiskEncryptionStatus -ResourceGroupName MyResourceGroup -VMName MyVMName` is for querying the [legacy encryption](https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html#encryption_settings).

The right command for querying encryption in `disk_encryption_set` should be this (in azure cli):
```
az disk show -g resourceGroupName -n diskName--query [encryption.type] -o tsv
```

Currently this is undocumented yet, and I will make a PR to terraform when the official docs are updated

**Comment by janlunddk** [comment] 2020-03-24 10:45
Hi @ArcturusZhang,
Thank you very much. The `az disk show` displays the correct information.

Do you know if the PowerShell Az module has a corresponding command (or if the existing will be updated)?

Please also notify the Azure Portal people, as the encryption information in the portal is also incorrect.

best regards
Jan

**Comment by ArcturusZhang** [comment] 2020-03-25 09:36
> Hi @ArcturusZhang,
> Thank you very much. The `az disk show` displays the correct information.
> 
> Do you know if the PowerShell Az module has a corresponding command (or if the existing will be updated)?
> 
> Please also notify the Azure Portal people, as the encryption information in the portal is also incorrect.
> 
> best regards
> Jan

`Get-AzDisk` should be the corresponding PS command, maybe this would help:
```
$disk=Get-AzDisk -ResourceGroupName 'ResourceGroup01' -DiskName 'Disk01'
echo $disk.Encryption.Type
```
I am not very familiar with azure PS...

**Comment by tombuildsstuff** [comment] 2020-03-25 10:56
👋 

As @ArcturusZhang has alluded to there's several different kinds of encryption available for Disks in Azure. The PowerShell command:

```powershell
$ Get-AzVmDiskEncryptionStatus -ResourceGroupName MyResourceGroup -VMName MyVMName
```

.. checks the encryption status for the older Azure Encryption Method against the VM - which used an Encryption Settings block on each Disk and a VM Extension to encrypt the disks (using KeyVault on Windows, and other tooling on Linux).

Instead the Azure CLI command:

```bash
$ az disk show -g resourceGroupName -n diskName --query [encryption.type] -o tsv
```

.. queries the state of the Disk Encryption Set on the Disk, which is the latest method of Encrypting Disks in Azure; which is done using a Customer Managed Key (from Key Vault) rather than the Platform Managed Key to encrypt this disk. More details [can be found in the Azure documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption).

However the Disk Encryption Set no longer requires using the Virtual Machine Extension to encrypt the data of these disks, since this is handled by Azure itself and this extension is only applicable to the older encryption method.

The Disk Encryption Set functionality has just come out of Preview - so it appears this hasn't been fully updated/documented in the Azure CLI and Portal yet - but since the Disks themselves are encrypted I believe this is working as intended. @ArcturusZhang would you be able to reach out to the Azure Portal team to raise that bug?

Since this appears to be working as intended I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-03-25 10:56 UTC
Labels: question, service/keyvault, service/virtual-machine

**Comment by janlunddk** [comment] 2020-03-25 11:11
@tombuildsstuff and @ArcturusZhang, thanks a lot for the elaboration. 

Yes, I can confirm that it works as intended. Apparently the only problem was the reporting of the encryption state.

As mentioned, I checked the `az disk show` on the existing test deployment I have, and it works, so this issue can indeed be closed.

I will give it another spin without the extension.

**Comment by ArcturusZhang** [comment] 2020-03-26 10:40
> 👋
> 
> As @ArcturusZhang has alluded to there's several different kinds of encryption available for Disks in Azure. The PowerShell command:
> 
> ```powershell
> $ Get-AzVmDiskEncryptionStatus -ResourceGroupName MyResourceGroup -VMName MyVMName
> ```
> 
> .. checks the encryption status for the older Azure Encryption Method against the VM - which used an Encryption Settings block on each Disk and a VM Extension to encrypt the disks (using KeyVault on Windows, and other tooling on Linux).
> 
> Instead the Azure CLI command:
> 
> ```shell
> $ az disk show -g resourceGroupName -n diskName --query [encryption.type] -o tsv
> ```
> 
> .. queries the state of the Disk Encryption Set on the Disk, which is the latest method of Encrypting Disks in Azure; which is done using a Customer Managed Key (from Key Vault) rather than the Platform Managed Key to encrypt this disk. More details [can be found in the Azure documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption).
> 
> However the Disk Encryption Set no longer requires using the Virtual Machine Extension to encrypt the data of these disks, since this is handled by Azure itself and this extension is only applicable to the older encryption method.
> 
> The Disk Encryption Set functionality has just come out of Preview - so it appears this hasn't been fully updated/documented in the Azure CLI and Portal yet - but since the Disks themselves are encrypted I believe this is working as intended. @ArcturusZhang would you be able to reach out to the Azure Portal team to raise that bug?
> 
> Since this appears to be working as intended I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.
> 
> Thanks!

Actually my information is gotten from the PM of disk encryption set, and he said he will update the doc of this soon.
