### ISSUE TITLE
ip_address output dont work for azurerm_public_ip  on 1.1.0 (works on 1.0.1)

### ISSUE THREAD

**Issue by KresoDenis** [terraform-providers/terraform-provider-azurerm#771] opened 2018-01-29 17:11 UTC
### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
- azurerm_public_ip

### Terraform Configuration Files
```
resource "azurerm_public_ip" "frontend" {
  name                         = "frontend"
  location                     = "${var.arm_location}"
  resource_group_name          = "${var.resource_group}"
  public_ip_address_allocation = "static"
}
output "voyager.default_ingress.ip" {
    value = "${azurerm_public_ip.frontend.ip_address}"
}
```

### Panic Output
output.voyager.default_ingress.ip: Resource 'azurerm_public_ip.frontend' does not have attribute 'ip_address' for variable 'azurerm_public_ip.frontend.ip_address'

### Expected Behavior
Output the ip_address

### Actual Behavior
Cant find ip_address for that resource

### Steps to Reproduce
1. terraform apply

### Important Factoids
It works on 1.0.1 azurerm provider, but dont on 1.1.0.
Same Terraform version
looks like terraform show for azurerm_public_ip includes everything but ip_address.

**Comment by bwerthmann** [comment] 2018-01-29 17:45
We are seeing the same issue.

**Comment by genevievelesperance** [comment] 2018-01-29 19:00
This seems to be the change that might have broken the assignment for `ip_address`: https://github.com/terraform-providers/terraform-provider-azurerm/commit/b5c71c109d7ed3625f009a0928e40298e6fddd6b#r27187845

It is dependent on the `props.DNSSettings` instead of just on `props.IPAddress`.

**Comment by nik-shornikov** [comment] 2018-01-29 19:15
👍 -- the data accessor workaround described here stopgaps this issue for me https://github.com/terraform-providers/terraform-provider-azurerm/issues/310

**Comment by genevievelesperance** [comment] 2018-01-29 19:30
The data accessor works because the code that has not changed. It gets the ip from the iaas and can provide properties on it.

The resource for the public ip has changed and it does not set the property for the output to read from.

**Comment by TheLinuxNinja** [comment] 2018-01-31 17:30
I also tested this. It broke all of our resources that reference the ip_address in order to create DNS entries and network security group rules in all of our existing configurations. I've locked the provider version to 1.0.1 until this is fixed.

Version 1.1.0 completely omits the ip_address in the state file, even after doing a refresh. Whoever is doing testing should add this to the regression testing for future versions of this resource.

**Comment by tombuildsstuff** [comment] 2018-02-03 15:42
👋 hey folks!

Firstly, sorry that this bug made it into this release (and for the delayed response here!)

@genevieve thanks for opening #772 with the fix for this issue, I've taken a look and it looks good to me (so I've merged it).

> Whoever is doing testing should add this to the regression testing for future versions of this resource.

@TheLinuxNinja definitely - I've opened #789 which adds this acceptance test (I don't have permissions to push to @genevieve's fork - or I'd have added it to to #772 before merging).

Since #772 has been merged, we'll do a release early next week with this bug fix - for the moment it should be possible to workaround this by either using [the Public IP Data Source](https://www.terraform.io/docs/providers/azurerm/d/public_ip.html) or by pinning to the previous version of the AzureRM Provider via:

```
provider "azurerm" {
  version = "1.0.1"
}
```

As #772 has been merged (and will be released early next week) and there's workarounds for this issue, I'm going to close this issue for the moment - but please feel free to reopen it. Apologies again that this bug slipped through - the acceptance tests added in #789 will ensure this doesn't happen again.

Thanks!

**Closed by tombuildsstuff** 2018-02-03 15:42 UTC
Labels: bug

**Comment by genevieve** [comment] 2018-02-03 19:10
Thanks @tombuildsstuff!

**Comment by martinbjorgan** [comment] 2018-02-03 19:13
Thanks @genevieve  and @tombuildsstuff for this! 
Been scratching my head a lot the last couple of days, so really nice we'll get a new release soon! :)

**Comment by tombuildsstuff** [comment] 2018-02-06 23:31
@KresoDenis @bwerthmann @genevieve @nik-shornikov @TheLinuxNinja just to let you know that the fix for this has been released in v1.1.1 :)

**Comment by genevieve** [comment] 2018-02-06 23:32
Yay, thank you.

**Comment by KresoDenis** [comment] 2018-02-07 10:23
Thanks. It was really nice to see this fixed so fast. It makes big difference to us.
