### ISSUE TITLE
log_analytics_workspace: creation fails when daily_quota_gb property is set to -1

### ISSUE THREAD

**Issue by boillodmanuel** [terraform-providers/terraform-provider-azurerm#9732] opened 2020-12-07 16:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM Provider: `v2.39.0`

### Affected Resource(s)

* `log_analytics_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg-terraform"
  location = "francecentral"
}

resource "azurerm_log_analytics_workspace" "log-aw" {
  name                = "log-tf-01"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  daily_quota_gb = -1
}
```

### Actual Behaviour

Since AzureRM Provider:`v2.36.0`, `log_analytics_workspace`.`daily_quota_gb` could not be set to -1 explicitly.

Doing this will cause the following error:
```
Error: expected daily_quota_gb to be at least (0.000000), got -1.000000
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2020-12-07 16:26
hi @boillodmanuel 

Thanks for opening this issue

Taking a look through here unfortunately this appears to be working as intended from Terraform's side, since it's not valid for this field to be explicitly set to -1 (which is why the validation requires this is >= 0) - users can instead set this to `null` to omit this field.

Whilst Pulumi does vendor Terraform Providers they alter the functionality somewhat (e.g. changing validation functions) that unfortunately we're unable to offer support with the Pulumi vendored providers. As such whilst I'd like to thank you for opening this issue I'm going to close this in favour of https://github.com/pulumi/pulumi-azure/issues/784 - where this is being tracked on Pulumi's side.

Thanks!

**Closed by tombuildsstuff** 2020-12-07 16:26 UTC
