### ISSUE TITLE
 Unexpected new value in "azurerm_key_vault_certificate" resource

### ISSUE THREAD

**Issue by shubhisethi** [terraform-providers/terraform-provider-azurerm#10384] opened 2021-01-29 15:06 UTC
#6888 [https://github.com/terraform-providers/terraform-provider-azurerm/issues/6888](url)

**Terraform (and AzureRM Provider) Version**
Terraform CLI v. 0.13.3
Azure Provider v. 2.45.1

**Affected Resource(s)**
azurerm_key_vault_certificate

**Terraform Configuration Files**
resource "azurerm_resource_group" "kv-rg" {
  name     = "example-key-vault-resources"
  location = "centralus"
}

data "azurerm_client_config" "current" {}

resource "azurerm_user_assigned_identity" "example_uai" {
  name                = "example-user-assigned-identity"
  location            = azurerm_resource_group.kv-rg.location
  resource_group_name = azurerm_resource_group.kv-rg.name
}

resource "azurerm_key_vault" "example_key_vault" {
  name                = "example-KeyVault"
  location            = azurerm_resource_group.kv-rg.location
  resource_group_name = azurerm_resource_group.kv-rg.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "premium"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    certificate_permissions = [
      "get", "list", "import", "delete", "create", "update", "recover", "purge"
    ]

  }

  **# This access policies is to allow the identity to be granted get and list access to the secret.**
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = azurerm_user_assigned_identity.example_uai.principal_id
    secret_permissions = [
      "get", "list"
    ]
  }
}

**# Generating a new certificate**
resource "azurerm_key_vault_certificate" "kv_cert" {
  name         = "example-generated-cert"
  key_vault_id = azurerm_key_vault.example_key_vault.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    lifetime_action {
      action {
        action_type = "AutoRenew"
      }

      trigger {
        days_before_expiry = 30
      }
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }

    x509_certificate_properties {
      # Server Authentication = 1.3.6.1.5.5.7.3.1
      # Client Authentication = 1.3.6.1.5.5.7.3.2
      extended_key_usage = ["1.3.6.1.5.5.7.3.1"]

      key_usage = [
        "cRLSign",
        "dataEncipherment",
        "digitalSignature",
        "keyAgreement",
        "keyCertSign",
        "keyEncipherment",
      ]

      subject            = "CN=example.iac"
      validity_in_months = 12
    }

  }
}

**Expected Behavior**
The certificate should be created in the Keyvault.

**Actual Behavior**
The provider throws this error sporadic:

**Error: Provider produced inconsistent result after apply**

When applying changes to azurerm_key_vault_secret.blob_accountkey, provider
"registry.terraform.io/-/azurerm" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Steps to Reproduce**
terraform apply

**Comment by aglees** [comment] 2021-01-29 15:53
I think this is another instance of [10371](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10371)

**Comment by BenWyattMilliman** [comment] 2021-02-01 17:43
FYI, I work with @shubhisethi, and we found that this issue was resolved by using v2.44 of the Azure RM provider, which is consistent with what the author of #10371 experienced.

**Comment by tombuildsstuff** [comment] 2021-02-03 10:42
Duplicate of #10371 - thanks for the cross-link @aglees @BenWyattMilliman - would you mind subscribing to #10371 for updates @shubhisethi? Thanks!

**Closed by tombuildsstuff** 2021-02-03 10:42 UTC
Labels: bug, duplicate, regression, service/keyvault
