### ISSUE TITLE
azurerm_eventhub_authorization_rule Error: empty non-retryable error received

### ISSUE THREAD

**Issue by bobhlo** [terraform-providers/terraform-provider-azurerm#12461] opened 2021-07-02 18:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_eventhub_authorization_rule`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
```
terraform {
  required_providers {
    azurerm = {
      # version = ">= 2.38"
      version = ">= 2.40"
    }
  }
}

resource "azurerm_eventhub_authorization_rule" "access_policy" {
  name                = var.name
  namespace_name      = var.namespace.name
  eventhub_name       = var.eventhub.name
  resource_group_name = var.resource_group.name
  listen              = var.listen
  send                = var.send
  manage              = false
}
```

### Debug Output

```
Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.

  on ../modules/services/event-hubs/access_policy/main.tf line 10, in resource "azurerm_eventhub_authorization_rule" "access_policy":
  10: resource "azurerm_eventhub_authorization_rule" "access_policy" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jackofallops** [comment] 2021-07-05 05:53
This appears to be a duplicate of #12387. Closing in favour of earlier opened issue, please subscribe to that for updates.

**Closed by jackofallops** 2021-07-05 05:53 UTC
