### ISSUE TITLE
Bug/Feature to improve deployment reliability with issue resulting in "Error occurred reading http.Response#Body - Error = 'context deadline exceeded'"

### ISSUE THREAD

**Issue by amonnphillipatquest** [terraform-providers/terraform-provider-azurerm#7412] opened 2020-06-19 17:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
The issue has been observed on version 2.14

### Affected Resource(s)
All resources should be affected with this issue, but it can easily be reproduced with a simply Linux VM deployment

### Terraform Configuration Files

 resource "azurerm_resource_group" "example" {
  location = "westus2"
  name     = "testing_only"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "cac" {

  name                  = "cac-vm"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  size                  = "Standard_DS2_v2"
  admin_username        = "admin234"
  admin_password        = "StRoNgPaSsWoRd11#"
  computer_name         = "vm-cac"
  disable_password_authentication = false
  network_interface_ids = [azurerm_network_interface.example.id]

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"
  }

  os_disk {
    name                  = "ac-vm-osdisk"
    caching               = "ReadWrite"
    storage_account_type  = "Standard_LRS"
    disk_size_gb          = 50
  }
}

### Debug Output
https://gist.github.com/amonnphillipatquest/b5abe97af44957e42730bf18b6b1bdd4

results in the following in the console:
Error: Error retrieving Linux Virtual Machine "cac-vm" (Resource Group "testing_only"): compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred reading http.Response#Body - Error = 'context deadline exceeded'

### Panic Output

None.

### Expected Behavior

We have all seen numerous errors where a resource seems to take a long time to deploy. When you take a look at the resource group in the UI you can see the resource, and it looks like it is in a usable state. In the case of a VM I can SSH to the machine etc, so the resource in question has indeed been deployed. Terraform however shows the message 'still creating' in the log. More often than not the deployment eventually times out.

You can even turn on logging (TF_LOG=TRACE) and observe the successful response from the Azure REST API, further pointing to something being wrong in the Terraform AzureRM plugin.

I hacked together some additional logging within the plugin to see where within that function the code stalled. Within the function resourceLinuxVirtualMachineCreate several calls are made to the Azure REST API, one of the calls of course is to create the resource. This almost always succeeds. The next call to the Azure REST API however sometimes does not.

The expected behavior is for the VM to have been deployed successfully, and the plugin should detect that this is so. Within the function resourceLinuxVirtualMachineCreate the call client.CreateOrUpdate, returns successfully. The call to wait for the response via a future future.WaitForCompletionRef handles the response properly. The next call to get the resource JSON from the Azure REST API should detect cases where the API is taking too long, and retry the request.

### Actual Behavior

The VM has been deployed successfully via the call in the plugin function called resourceLinuxVirtualMachineCreate. The call to wait for the response is ok (via the line
if err := future.WaitForCompletionRef(ctx, client.Client); err != nil { ...

The very next line of code however to get the resource JSON object via the call:
read, err := client.Get(ctx, resourceGroup, name, "")
This call sometimes does not return in a timely manner and so the deployment eventually times out (wasting hours of development time for us per day BTW). There is nothing we can do here to make the Azure REST APIs more robust (thanks MS!), but we can have a short timeout for the second call mentioned, as the resource is already created, and there is not much reason why the call in question should respond within a few seconds. We should also make this call retry several times after each time out period. This should make deployments a little more robust.

Ideally this change should be implemented in a way that all resources have this retry mechanism.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None that I am aware of

### References

* #0000

**Comment by amonnphillipatquest** [comment] 2020-06-20 18:24
An update for this. I went ahead and hacked in some code in the linux_virtual_machine_resource.go file, in the function resourceLinuxVirtualMachineCreate to timeout and retry the attempt at getting the virtual machine resource id after the call to create the resource returns 'success' status, and it does work around the issue. Azure deployments for linux VMs are more reliable now.

It seems the Azure resource manager REST API has an issue with the creation of some resources where you cannot immediately get the resource status after resource creation. Currently the code in place simply makes a single call to get the resource id, which has a very long time out and you end up waiting for minute/hours for a resource that has successfully been created but the Azure REST API never returns a response to the call so the deployment fails. To work around this the code needs to either wait some arbitrary amount of time (probably not the best workaround for this issue), or time out the request and retry.

Hopefully this all makes sense to you all.

**Comment by ArcturusZhang** [comment] 2020-06-22 02:34
Hi @amonnphillipatquest thanks for this issue!

While I understand the cause of this issue (not root cause though, root cause should be in Azure API), I had a try on my subscription but it works fine. Actually this does not look like those issues that happen all the time, just in occasion, right?

And for the call of `GET` in the `resourceLinuxVirtualMachineCreate` callback, indeed it is intended to just get the ID from Azure after the resource was created to serve the consecutive `resourceLinuxVirtualMachineRead` callback to fill in the tfstate. And I suppose we could do better in this part by replacing the `Get` call with a `future.Result` (implementation [here](https://github.com/Azure/azure-sdk-for-go/blob/6095b427503b02f76316e8c6c2c5316854cbef52/services/compute/mgmt/2019-07-01/compute/models.go#L13563)). This `Result` function works as a `GET` request but it has `Retry` logic within it.

**Comment by amonnphillipatquest** [comment] 2020-06-22 16:17
Hello, thanks for looking at this so quickly.

Yes the issues does not happen every try, it looks and smells like a race condition dependent on when the resource status can be read successfully via the Azure REST API. I often perform deployments where several VMs need to be created and I see this issue every day, sometimes several times a day. And yes you analysis is the same as mine, the eventual time out is due to behaviour of the REST API, something that will not change any time soon.

Regarding the call to get the resource ID. The call logic should time out after a short-ish period because the behavior of the Azure REST API is to not respond at all to the call, and this is the source of issue. If we time out after a short-ish period of time (like 30 seconds) after 1 to 3 tries the Azure REST API eventually responds and the deployment continues. My hacky workaround currently has a time out of 30 seconds, and retries up to 10 times.

Again thanks for looking at this.

On a similar note, how do I go about proposing and implementing a feature or bug fix for the plugin? Should I just fork the repo, implement my feature, and submit it for review? Please let me know.


Thanks.

Amonn.

**Comment by ArcturusZhang** [comment] 2020-06-28 03:36
Hi @amonnphillipatquest it would be great if you could contribute to this provider!
Indeed the process you mentioned is the typical procedure to contribute and thanks for your contribution in advance.

**Comment by amonnphillip** [comment] 2020-07-22 19:16
Sorry for the delay. Will start to work on this issue using my own fork.

Thanks!

**Comment by amonnphillip** [comment] 2020-07-29 02:47
@tombuildsstuff @ArcturusZhang  I have an approach for review. It involves using a small wrapper around the Get method that provides timeout and retry functionality. I am not a golang expert so please take a look and comment on any changes that are needed.

https://github.com/amonnphillip/terraform-provider-azurerm

**Comment by ArcturusZhang** [comment] 2020-07-29 08:18
Hi @amonnphillip could you please just open a pull request from your forked master? And thanks for your contribution!

**Comment by tombuildsstuff** [comment] 2020-08-06 11:15
hey @amonnphillipatquest 

As mentioned in #7949 - whilst one option would be to fix this behaviour within the Azure Provider, since the Azure SDK (or rather, Azure/go-autorest, the framework it uses to interact with Azure) automatically retries failed requests - in practice I think this'd be better to fix this there instead (since that won't require changes to every resource).

As such whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment - however I'd suggest [opening an issue on Azure/go-autorest](https://github.com/Azure/go-autorest) as a next step here. Once that's available we can vendor those changes in and this should be available within all resources 👍🏻

Thanks!

**Closed by tombuildsstuff** 2020-08-06 11:15 UTC
Labels: question, service/virtual-machine
