### ISSUE TITLE
Cannot register provider Microsoft.DBforMariaDB with Azure Resource Manager

### ISSUE THREAD

**Issue by polasekr** [terraform-providers/terraform-provider-azurerm#6529] opened 2020-04-17 19:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.5.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.tls v2.1.1
```

### Affected Resource(s)

It is prior to any resource creation. It is happening when terraform plan or terraform apply are executed.

### Terraform Configuration Files

provider.tf
```
provider "azurerm" {
  version = "2.6.0"
  features {}
}
```

### Debug Output

```
$ terragrunt plan 
[terragrunt] 2020/04/17 15:14:50 Reading Terragrunt config file at /home/robert/src/stjude/terragrunt-code/core/container-registry/terragrunt.hcl
[terragrunt] [/home/robert/src/stjude/terragrunt-code/core/container-registry] 2020/04/17 15:14:50 Running command: terraform --version
[terragrunt] 2020/04/17 15:14:50 Terraform files in /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry are up to date. Will not download again.
[terragrunt] 2020/04/17 15:14:50 Copying files from /home/robert/src/stjude/terragrunt-code/core/container-registry into /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry
[terragrunt] 2020/04/17 15:14:50 Setting working directory to /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry
[terragrunt] 2020/04/17 15:14:50 The file path /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry/provider.tf already exists, but was a previously generated file by terragrunt. Since if_exists for code generation is set to "overwrite_terragrunt", regenerating file.
[terragrunt] 2020/04/17 15:14:50 Generated file /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry/provider.tf.
[terragrunt] 2020/04/17 15:14:50 The file path /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry/backend.tf already exists, but was a previously generated file by terragrunt. Since if_exists for code generation is set to "overwrite_terragrunt", regenerating file.
[terragrunt] 2020/04/17 15:14:50 Generated file /home/robert/src/stjude/terragrunt-code/core/container-registry/.terragrunt-cache/Oqa1MpMm9QUtDpA62BgfeLNUXLA/KJTjUJoDdZqe2YxS9i6E59n6Gw4/container-registry/backend.tf.
[terragrunt] 2020/04/17 15:14:50 Running command: terraform plan
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error ensuring Resource Providers are registered.

Terraform automatically attempts to register the Resource Providers it supports to
ensure it's able to provision resources.

If you don't have permission to register Resource Providers you may wish to use the
"skip_provider_registration" flag in the Provider block to disable this functionality.

Please note that if you opt out of Resource Provider Registration and Terraform tries
to provision a resource from a Resource Provider which is unregistered, then the errors
may appear misleading - for example:

> API version 2019-XX-XX was not found for Microsoft.Foo

Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
but this could also indicate that this Azure Region doesn't support this API version.

More information on the "skip_provider_registration" flag can be found here:
https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration

Original Error: Cannot register provider Microsoft.DBforMariaDB with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'rpolasek@stjude.org' with object id 'aae1bdab-f8ff-42d6-a6b5-4b9b5b64f33d' does not have authorization to perform action 'Microsoft.DBforMariaDB/register/action' over scope '/subscriptions/0dd230ae-d7aa-4c3f-a257-15b75fed908c' or the scope is invalid. If access was recently granted, please refresh your credentials.".

  on provider.tf line 2, in provider "azurerm":
   2: provider "azurerm" {


[terragrunt] 2020/04/17 15:14:59 Hit multiple errors:
exit status 1
```

### Expected Behavior

When same code is executed with azurerm provider version 2.5.0, no error message is thrown and code is successfully executed. This is a new behavior that came with version 2.6.0.

### Actual Behavior

No resource provisioning is executed and the error posted above is printed out.

### Steps to Reproduce

1) specify version 2.6.0 as required for azurerm provider while skip_provider_registration is set to false.
```
provider "azurerm" {
  version = "2.6.0"
  features {}
}
```
2) execute any previously working terraform code

### Important Factoids

I don't have any mariadb resource defined in my code.  As soon as I set `skip_provider_registration = true` the code works as intended. It is changed behavior from version 2.5.0. I am not sure whether it is intentional, or bug, but there is no remark in release notes.

**Comment by tombuildsstuff** [comment] 2020-04-18 08:43
hi @polasekr 

Thanks for opening this issue :)

Azure's concept of a Resource Provider requires that the Resource Provider is registered before any API's within that Resource Provider can be called. As such, rather than failing during an API call / to improve the user experience Terraform automatically attempts to register any Resource Providers that it supports by default - to ensure that the API's are available when they're needed; and since this list is stored within Terraform, we extend this list from time to time as Terraform is updated to support new functionality (provided in new Resource Providers).

If you'd prefer to manage Resource Provider Registration outside of Terraform (for example you're running in a restricted environment) - as you've mentioned it's possible to opt-out of this behaviour by setting this field [in the Provider block](https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration).

Since this is working as intended I'm going to close this issue for the moment - but please let us know if disabling this functionality doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-04-18 08:43 UTC
