### ISSUE TITLE
resource "azurerm_subscription" tags is not a supported field; please add it 

### ISSUE THREAD

**Issue by crkg** [terraform-providers/terraform-provider-azurerm#11274] opened 2021-04-09 11:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

resource "azurerm_subscription" tags is not a supported field; please add it , there is a feature tags under subscription but its not supported via terraform to add tags automated way.

Error "tags": this field cannot be set 

Add field tags to support an automated, tagging mechanism in resource "azurerm_subscription"

### New or Affected Resource(s)

* azurerm_subscription

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
resource "azurerm_subscription" "subscriptions" {
  # this also produces a map: subscription-name
  for_each = var.subscriptions
  subscription_name     = "subscription_name_example"
  //location = each.value.location
  tags     =  "{ key = value , key2=value2}"
}

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-04-09 14:48
hi @crkg 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #11103 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11103 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-04-09 14:48 UTC
