### ISSUE TITLE
Add Import Key support into azurerm_key_vault_key

### ISSUE THREAD

**Issue by abilous-ti** [terraform-providers/terraform-provider-azurerm#10301] opened 2021-01-25 12:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft document describes possibility to import an externally created key, store it, and return key parameters and attributes to the client.
The import key operation may be used to import any key type into an Azure Key Vault.
If the named key already exists, Azure Key Vault creates a new version of the key. This operation requires the keys/import permission.
https://docs.microsoft.com/en-us/rest/api/keyvault/importkey

Could Key Import feature be implemented for resource azurerm_key_vault_key?
### New or Affected Resource(s)

* azurerm_key_vault_key

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-02-04 10:32
hi @abilous-ti 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4283 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4283 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-04 10:32 UTC
Labels: duplicate, enhancement, service/keyvault
