### ISSUE TITLE
azurerm_firewall_policy_rule_collection_group destination_ports argument does not support "*"

### ISSUE THREAD

**Issue by schlickspringer** [terraform-providers/terraform-provider-azurerm#10918] opened 2021-03-10 16:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.13.5
azurerm 2.49.0

### Affected Resource(s)

* `azurerm_firewall_policy_rule_collection_group`

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy_rule_collection_group" "defaultgrouprules" {
  name               = "DefaultNetworkRuleCollectionGroup"
  firewall_policy_id = azurerm_firewall_policy.pol01.id
  priority           = 200
 network_rule_collection {
    name     = "CollectionforTesting"
    priority = 1000
    action   = "Allow"
    rule {
      name                  = "AllowAll"
      protocols             = ["Any","ICMP","TCP","UDP"]
      source_addresses      = ["*"]
      destination_addresses = ["*"]
      destination_ports     = ["*"]
    }
  }
}
```

### Expected Behaviour

Apply the configuration. 

### Actual Behaviour

An error results when using "*" as a destination_ports argument. An asterisk is a valid destination_port argument when using the Azure Portal.

Error: invalid format of "network_rule_collection.0.rule.0.destination_ports.0"

### Steps to Reproduce

1. `terraform apply`

### References

* #9304

**Comment by adamday2** [comment] 2021-03-10 17:12
I believe this is a dupe of https://github.com/terraform-providers/terraform-provider-azurerm/issues/10524 and https://github.com/terraform-providers/terraform-provider-azurerm/issues/10187 where the recommendation was to set the value to `1-65535`.

**Comment by pauldotyu** [comment] 2021-04-05 22:03
Any updates on this? I too have confirmed that using a port range of 1-65535 does not work for Azure Firewall Policy Manager rule collections.

**Comment by henryxuteck** [comment] 2021-04-08 04:35
ping and traceroute are reply on ICMP, and ICMP is a protocol on network layer which doesnt have the concept of port
https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol

To me, port should be ignored (by using "*") for ICMP traffic.

**Comment by jkroepke** [comment] 2021-04-14 15:41
@adamday2 
> where the recommendation was to set the value to 1-65535.

`1-65535` != `*`

https://docs.microsoft.com/de-de/azure/firewall/rule-processing#network-rule-protocol

> If a destination port is explicitly configured, then the rule is translated to a TCP+UDP rule.

That means, If a rule has port like `1-65535` defined, ICMP not longer works.

**Closed** 2021-04-14 16:34 UTC
Labels: bug, service/firewall
