### ISSUE TITLE
Get existing virtual network object details by providing the resource id in argument

### ISSUE THREAD

**Issue by LaurentLesle** [terraform-providers/terraform-provider-azurerm#10219] opened 2021-01-18 01:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Current implementation of azurerm_virtual_network data source require the name and the resource group.
This is issue proposes an implementation to get the object by providing the resource_id of the virtual network

```hcl
# Current
data "azurerm_virtual_network" "example" {
  name                = "production"
  resource_group_name = "networking"
}

# Proposed
data "azurerm_virtual_network" "example" {
  id = "/subscriptions/[subscription_id]/resourceGroups/[rg_name]/providers/Microsoft.Network/virtualNetworks/[vnet name]"
}
```

The attributes returned should also return the **name** and **resource group** name of the vnet
Current list of attributes Reference

- id - The ID of the virtual network.
- location - Location of the virtual network.
- address_space - The list of address spaces used by the virtual network.
- dns_servers - The list of DNS servers used by the virtual network.
- guid - The GUID of the virtual network.
- subnets - The list of name of the subnets that are attached to this virtual network.
- vnet_peerings - A mapping of name - virtual network id of the virtual network peerings.

This is currently supported by the az cli
```bash
az resource show --ids [resource_id_of _the_existing_vnet]
```

### New or Affected Resource(s)

data "azurerm_virtual_network"

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-01-18 07:06
hi @LaurentLesle 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5691 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5691 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-18 07:06 UTC

**Comment by LaurentLesle** [comment] 2021-01-18 10:24
I can do that. Just wanted to make sure #5691 is also targeting data azurerm_resources, not just networking.
