### ISSUE TITLE
Support for Vnet integration in Databricks

### ISSUE THREAD

**Issue by sunnynazar** [terraform-providers/terraform-provider-azurerm#4905] opened 2019-11-18 10:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Terraform doesn't support vnet integration with azure databricks.**
We need **vnet integration** option in terraform for databricks.

### New or Affected Resource(s)

**Azure Databricks**

### Potential Terraform Configuration
```hcl
 resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West US"
}

resource "azurerm_databricks_workspace" "test" {
  name                = "databricks-test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  sku                 = "standard"
  vnet_id             = "${var.vnet_id}"
  private_subnet_cidr = "${var.private_subnet_cidr}"
  private_subnet_name = "${var.private_subnet_name}"
  public_subnet_cidr  = "${var.public_subnet_cidr}"
  public_subnet_name  = "${var.public_subnet_name}"
  tags = {
    Environment = "Production"
  }
}
```
### References

- [ ] **ARM TEMPLATE** :  https://github.com/Azure/azure-quickstart-templates/blob/master/101-databricks-all-in-one-template-for-vnet-injection

- [ ]  **Microsoft Documentation** : https://docs.microsoft.com/en-us/azure/databricks/administration-guide/cloud-configurations/azure/vnet-inject

**Comment by tombuildsstuff** [comment] 2019-11-18 10:57
hi @sunnynazar 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3001 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3001 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-11-18 10:57 UTC

**Comment by sunnynazar** [comment] 2019-11-18 11:08
thanks @tombuildsstuff  , sorry did n't see #3001 , i have subscribed to this issue now.
