### ISSUE TITLE
azurerm_monitor_diagnostic_setting attribute name issue

### ISSUE THREAD

**Issue by terryjrjoyce** [terraform-providers/terraform-provider-azurerm#9921] opened 2020-12-17 17:30 UTC
### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Description
When I try to connect an eventhub to the diagnostic logs I get a Terraform error.

**Terraform 0.14.2**
### New or Affected Resource(s)
azurerm_monitor_diagnostic_setting

The terraform segment looks like this.

```resource "azurerm_monitor_diagnostic_setting" "main" {
  name                           = var.name
  target_resource_id             = var.resource-id
  eventhub_name                  = var.eventhub-name
  eventhub_authorization_rule_id = var.eventhub-auth-rule-id
```
When I take it out it looks like this.
```resource "azurerm_monitor_diagnostic_setting" "main" {
  name                           = var.name
  target_resource_id             = var.resource-id
  eventhub_name                  = var.eventhub-name
```
When I run the Terraform with the line in I get an error that says:
```Unsupported attribute; This object does not have an attribute named "eventhub_authorization_rule_id".```
When I run the Terraform with the line missing I get an error that says:
```Either a `eventhub_authorization_rule_id`, `log_analytics_workspace_id` or `storage_account_id` must be set```

Can someone tell me why it is doing this?

**Comment by tombuildsstuff** [comment] 2020-12-17 17:38
hi @terryjrjoyce 

Thanks for opening this issue.

Taking a look through here this appears to be a Terraform Configuration question, I can confirm the resource `eventhub_authorization_rule_id` has an attribute `eventhub_authorization_rule_id` - so it's possible the configuration is specified incorrectly here, such as this attribute being specified within a different resource (which would explain the "unsupported attribute") - but unfortunately the snippet above isn't enough to confirm specifically where the issue is. That said, the full error being returned from Terraform Core should show this including resource names and line numbers - so hopefully that should help isolate where this issue is.

Since this is a question regarding Terraform Configuration and we use this forum for feature enhancements and bugs in the Azure Provider - I'm going to close this issue for the moment, but should you have further issues I'd suggest opening a post [on the Community Forum](https://discuss.hashicorp.com) with a complete example and someone should be able to take a look :)

Thanks!

**Closed by tombuildsstuff** 2020-12-17 17:38 UTC
Labels: question, service/monitor
