### ISSUE TITLE
Failure in issuing create/update request for SQL Database - Invalid parameter 'storageEndpoint'

### ISSUE THREAD

**Issue by Edblakejitsuin** [terraform-providers/terraform-provider-azurerm#8925] opened 2020-10-16 14:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azuread v0.10.0
+ provider registry.terraform.io/hashicorp/azurerm v2.29.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

### Affected Resource(s)

* `azurerm_sql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_sql_server" "cluster" {
  provider                     = azurerm.cluster
  name                         = var.cluster_name
  resource_group_name          = data.azurerm_resource_group.cluster_resource_group.name
  location                     = var.sql_server_location
  version                      = var.sql_version
  administrator_login          = random_password.sql_server_username.result
  administrator_login_password = random_password.sql_server_password.result
}


resource "azurerm_sql_database" "example" {
  provider                         = azurerm.example
  name                             = var.example
  resource_group_name              = data.azurerm_kubernetes_cluster.cluster.resource_group_name
  location                         = var.location
  server_name                      = var.sql_server_name
  collation                        = "SQL_Latin1_General_CP1_CI_AS"
  edition                          = var.sql_edition
  requested_service_objective_name = var.sql_dtu
  max_size_bytes                   = var.sql_max_size_bytes
  tags = {
    example1 = var.example
    example2    = var.example
  }
}
```

### Expected Behavior

Should create the sql database without errors, without the need for an extended_auditing_policy block 

### Actual Behavior

Errors occurred:

Error: failure in issuing create/update request for SQL Database "example" Blob Auditing Policies(SQL Server "example"/ Resource Group "example"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="DataSecurityInvalidUserSuppliedParameter" Message="Invalid parameter 'storageEndpoint'. Value should be a blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net)."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This was working fine 2 days ago.
Subsequent 'terraform apply' commands continue to fail every time.

### References

* #0000

**Comment by SDubrulle-e61** [comment] 2020-10-16 16:06
I'm experiencing the same behaviour with a slightly different resource: azurerm_mssql_server. Configuration and error are similar.

**Comment by TPPWC** [comment] 2020-10-17 09:16
Same problem here:

https://github.com/terraform-providers/terraform-provider-azurerm/issues/8915

**Comment by mariiabeschekova** [comment] 2020-10-18 16:57
I'm facing the same issue with azurerm_sql_server.

**Comment by tombuildsstuff** [comment] 2020-10-19 05:17
hi @Edblakejitsuin 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8915 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8915 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-19 05:17 UTC

**Comment by vi7us** [comment] 2020-11-11 09:03
It looks like issue is back. I'm having same error in westeurope, should this be reopened @tombuildsstuff?
