### ISSUE TITLE
Cannnot register providers: Microsoft.AVS if own role is just "Reader" (v2.50.0)

### ISSUE THREAD

**Issue by wiebeck** [terraform-providers/terraform-provider-azurerm#10853] opened 2021-03-05 10:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.50.0
```

### Affected Resource(s)

* any

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.50.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "rg" {
  name = "existing_rg"
}
```

### Expected Behaviour

No error message when executing `terraform plan` or `apply`.

### Actual Behaviour

The following error message appears:

```
Error: Error ensuring Resource Providers are registered.

Terraform automatically attempts to register the Resource Providers it supports to
ensure it's able to provision resources.

If you don't have permission to register Resource Providers you may wish to use the
"skip_provider_registration" flag in the Provider block to disable this functionality.

Please note that if you opt out of Resource Provider Registration and Terraform tries
to provision a resource from a Resource Provider which is unregistered, then the errors
may appear misleading - for example:

> API version 2019-XX-XX was not found for Microsoft.Foo

Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
but this could also indicate that this Azure Region doesn't support this API version.

More information on the "skip_provider_registration" flag can be found here:
https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration

Original Error: Cannnot register providers: Microsoft.AVS. Errors were: Cannot register
provider Microsoft.AVS with Azure Resource Manager: resources.ProvidersClient#Register:
Failure responding to request: StatusCode=403 -- Original Error: autorest/azure:
Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client
'XXX@YYY.ZZZ with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not have
authorization to perform action 'Microsoft.AVS/register/action' over scope
'/subscriptions/xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx' or the scope is invalid.
If access was recently granted, please refresh your credentials.".

  on main.tf line 9, in provider "azurerm":
   9: provider "azurerm" {
```

### Steps to Reproduce

Just try to `terraform plan` the above example script while being logged in on a subscription where you only have the `Reader` role.

### Important Factoids

The above works without issues in provider version 2.49.0 (and below) or when operating with `Contributor` role.

### References

* Issue #9284 added support for a new resource which added `Microsoft.AVS` to the list of "required resource providers" which seems to have issues if you're not at least a `Contributor`.

**Comment by tombuildsstuff** [comment] 2021-03-15 08:48
hi @wiebeck 

Thanks for opening this issue :)

Azure's concept of a Resource Provider requires that the Resource Provider is registered before any API's within that Resource Provider can be called. As such, rather than failing during an API call / to improve the user experience Terraform automatically attempts to register any Resource Providers that it supports by default - to ensure that the API's are available when they're needed; and since this list is stored within Terraform, we extend this list from time to time as Terraform is updated to support new functionality (provided in new Resource Providers).

If you'd prefer to manage Resource Provider Registration outside of Terraform (for example you're running in a restricted environment) - it's possible to opt-out of this behaviour by setting this field [in the Provider block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration).

Since this is working as intended I'm going to close this issue for the moment - but please let us know if disabling this functionality doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2021-03-15 08:48 UTC
Labels: provider, question
