### ISSUE TITLE
Azurerm v2.62.0 now requires me to set skip_provider_registration to true when v2.61.0 did not

### ISSUE THREAD

**Issue by eranjbarSuncor** [terraform-providers/terraform-provider-azurerm#12058] opened 2021-06-04 06:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.62.0
```

### Affected Resource(s)

provider "azurerm"

### Expected Behaviour

terraform running normally

### Actual Behaviour
since utilizing azurerm v2.62.0:
```
 Error: Error ensuring Resource Providers are registered.
...
with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 6, in provider "azurerm":
│    6: provider "azurerm" {
```

### Steps to Reproduce

1. `terraform plan`

### Additional information

With azurerm v2.61.0, I did not need to set my skip_provider_registration set to true. But since the upgrade to v2.62.0, I need to have this value set. I can verify my terraform still works as is with v2.61.0 by running this:

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.61.0"
    }
  }
}
```

**Comment by sebastianhutter** [comment] 2021-06-04 09:55
We face the same issue. 

We face the same issue here.

It seems this is due to the newly added resource type `azurerm_data_protection_backup_vault`.
When running `terraform plan` the service principal doesn't have the required permissions to register 

```
Original Error: Cannnot register providers: Microsoft.DataProtection. Errors were: Cannot register provider Microsoft.DataProtection with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '000000-0000-0000-0000-0000000000' with object id '00000000-0000-0000-0000-00000000' does not have authorization to perform action 'Microsoft.DataProtection/register/action' over scope '/subscriptions/00000000-0000-0000-0000-00000000' or the scope is invalid. If access was recently granted, please refresh your credentials.".
```

Giving the service prinicipal `Contributor` rights on the subscripton fixes the error but we don't want to give the terraform service principal full permissions over all resources in the subscription.

**Comment by nnellans-acts** [comment] 2021-06-04 13:55
> 
> 
> We face the same issue here.
> 
> It seems this is due to the newly added resource type `azurerm_data_protection_backup_vault`.
> When running `terraform plan` the service principal doesn't have the required permissions to register
> 
> ```
> Original Error: Cannnot register providers: Microsoft.DataProtection. Errors were: Cannot register provider Microsoft.DataProtection with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '000000-0000-0000-0000-0000000000' with object id '00000000-0000-0000-0000-00000000' does not have authorization to perform action 'Microsoft.DataProtection/register/action' over scope '/subscriptions/00000000-0000-0000-0000-00000000' or the scope is invalid. If access was recently granted, please refresh your credentials.".
> ```
> 
> Giving the service prinicipal `Contributor` rights on the subscripton fixes the error but we don't want to give the terraform service principal full permissions over all resources in the subscription.
> 
> We implemented a custom role as a workaround for the registration. Adding the custom role to the subscription and assigning it to the terraform service principal allows the call to `Microsoft.DataProtection/register/action`.
> 
> ```json
> {
>     "properties": {
>         "roleName": "Allow register/action",
>         "description": "Allow register/action on any resouyrce type.",
>         "assignableScopes": [
>             "/subscriptions/0000000-0000-0000-0000-0000000"
>         ],
>         "permissions": [
>             {
>                 "actions": [
>                     "*/register/action"
>                 ],
>                 "notActions": [],
>                 "dataActions": [],
>                 "notDataActions": []
>             }
>         ]
>     }
> }
> ```
> 
> The `*` is required as there doesnt seem to be an action `Microsoft.DataProtection/register/action`.
> Trying to create a custom role with the action `Microsoft.DataProtection/register/action` instead of `*/register/action` leads to this error.
> 
> `Invalid JSON content - Validation error: Invalid action is present in "actions": Microsoft.DataProtection/register/action`
> 
> UPDATE: I removed the custom policy from the subscription and the plan remains working. no clue what azure does here ;-)

Provider registration is a one-time thing.  Once it's registered the first time you are good.

**Comment by eranjbarSuncor** [comment] 2021-06-04 14:20
I don't have the option of making my service principal or my credentials have access to the subscription for this... Am I just forced to set skip_provider_registration to false in my terraform for the foreseeable future?

**Comment by sebastianhutter** [comment] 2021-06-04 14:31
> I don't have the option of making my service principal or my credentials have access to the subscription for this... Am I just forced to set skip_provider_registration to false in my terraform for the foreseeable future?

It seems so. The default behaviour is to register any new resource providers. And it doesnt seem like the registration can be configured to exclude certain providers. It's all or nothing:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration

**Comment by nnellans-acts** [comment] 2021-06-04 14:36
> 
> 
> I don't have the option of making my service principal or my credentials have access to the subscription for this... Am I just forced to set skip_provider_registration to false in my terraform for the foreseeable future?

Someone with the proper rights to the Subscription could manually do the registration in the Portal.  Again, it's just a one time thing that needs to happen.

**Comment by tehho** [comment] 2021-06-08 08:15
Had a problem with cross subscription data reference in a module but was able to specify skip_provider_registration = true on the provider in the module and now the teams can continue upgrading. 
Not sure how one might solve this without a major over hull of the entire registration process.

**Comment by tombuildsstuff** [comment] 2021-06-08 08:34
hi @eranjbarSuncor 

Thanks for opening this issue.

Azure's concept of a Resource Provider requires that the Resource Provider is registered before any API's within that Resource Provider can be called. As such, rather than failing during an API call / to improve the user experience Terraform automatically attempts to register any Resource Providers that it supports by default - to ensure that the API's are available when they're needed; and since this list is stored within Terraform, we extend this list from time to time as Terraform is updated to support new functionality (provided in new Resource Providers).

If you'd prefer to manage Resource Provider Registration outside of Terraform (for example when you're running in a restricted environment or using an account without permissions to do so) - you can opt-out of this behaviour by setting this field [in the Provider block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration) (as you've mentioned above).

Since this is working as intended I'm going to close this issue for the moment - but should you have any other questions I'd point you towards [the community discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2021-06-08 08:34 UTC
Labels: question
