### ISSUE TITLE
Support Azure Machine Learning (ML) Service and underlying resources

### ISSUE THREAD

**Issue by samart** [terraform-providers/terraform-provider-azurerm#4323] opened 2019-09-13 14:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A resource to create and manage azure ML Service.  Including being able to create Azure ML vm clusters associated with customer vnet.  Ability to create notebook vms.  and IAM for ML Service.

### New or Affected Resource(s)

AzureML

* azurerm_ml

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2019-09-13 14:47
hi @samart 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3729 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3729 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-13 14:47 UTC
Labels: duplicate, new-resource, service/machine-learning
