### ISSUE TITLE
Unable to deploy .NET Core Azure Web Apps

### ISSUE THREAD

**Issue by Imed-Eden** [terraform-providers/terraform-provider-azurerm#5641] opened 2020-02-07 13:59 UTC
**Community Note**
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Description**
Azure Web Apps have a stack settings that allow to choose what environements is chosen for example python, java, .net and .NET CORE! 
Terraform does not allo to deploy a web app .NET CORE

![image](https://user-images.githubusercontent.com/15699913/74034681-0fbc5680-49b9-11ea-8167-c1284e799dd0.png)

This feature request is to add a possibility to configure app services that run .NET Core Pleaaaaaase

Thank you so much

Imed

**Comment by tombuildsstuff** [comment] 2020-02-07 14:04
hi @Imed-Eden 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5350 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5350 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-02-07 14:04 UTC

**Comment by Imed-Eden** [comment] 2020-02-07 14:08
Sure Thank you Tom! I'll be waiting for new updates hopefully.
