### ISSUE TITLE
Import azurerm_key_vault, sku_name Cap sensitive -> creates change

### ISSUE THREAD

**Issue by adamsebetich** [terraform-providers/terraform-provider-azurerm#8958] opened 2020-10-20 23:02 UTC
I am working through importing existing resources to be managed by Terraform running the "terraform import XXXXXX" command and when working through the Key Vault, I noticed that It is stating that I am making a change to the "sku_name" even if I am keeping the sku the same. 

I am required to add it as a field and I am typing "standard" as the option and I have to type it that specific way (case sensitive) otherwise it errors. However, even though I am not changing the sku_name (importing like for like), the Terraform Plan shows that a "change" is occurring in the keyvault. Stating "~ sku_name = "Standard" -> "standard" "

Any thoughts on how to get around this? I think if i run terraform apply, it shouldnt do anything, but I want to make sure this is a known issue.

**Comment by njuCZ** [comment] 2020-10-21 07:54
duplicate as #8457

**Comment by tombuildsstuff** [comment] 2020-10-21 07:55
hi @adamsebetich 

Thanks for opening this issue :)

Taking a look through here, as @njuCZ has mentioned this appears to be a duplicate of #8457 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8457 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-21 07:55 UTC
