### ISSUE TITLE
azurerm_dns_cname_record: FQDN output returns trailing period

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#6758] opened 2020-05-04 18:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.8.0

### Affected Resource(s)

* `azurerm_dns_cname_record`

### Terraform Configuration Files

```hcl
resource "azurerm_dns_cname_record" "fd_domain_record" {
  for_each            = toset(var.subdomain_name)
  name                = each.value
  zone_name           = var.zone_name
  resource_group_name = var.zone_resource_group
  ttl                 = 10
  record              = "${local.cleaned_name}.azurefd.net"
}
```

and then in Front Door...
```hcl
  dynamic "frontend_endpoint" {
    for_each = azurerm_dns_cname_record.fd_domain_record
    content {
      name                                    = "domain-name"
      host_name                               = frontend_endpoint.value.fqdn
      custom_https_provisioning_enabled       = true
      web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.fd_waf.id
      custom_https_configuration {
        certificate_source = "FrontDoor"
      }
    }
  }
```

### Expected Behavior

The FQDN should be a valid domain name without a trailing period.

### Actual Behavior

The FQDN output contains a trailing period which causes an invalid domain name error when trying to create Front Door.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by WodansSon** [comment] 2020-05-14 01:22
@bcline760, thank you for opening this issue. If I understand your issue correctly, the reason you are seeing the trailing period is because you are looping over a DNS CName record and the trailing period would be by design.

> CNAME records (anything where the “target” is a hostname) must end with a “.” to indicate that it is a FQDN. 
> 
> Per [RFC 1034](https://www.ietf.org/rfc/rfc1034.txt)
> 
> Since a complete domain name ends with the root label, this leads to a printed form which
> ends in a dot.  We use this property to distinguish between:
> 
>    * a character string which represents a complete domain name
>      (often called "absolute").  For example, "poneria.ISI.EDU."
> 
>    * a character string that represents the starting labels of a
>      domain name which is incomplete, and should be completed by
>      local software using knowledge of the local domain (often
>      called "relative").  For example, "poneria" used in the
>      ISI.EDU domain.

**Comment by bcline760** [comment] 2020-05-14 17:36
I'm not looping over the CNAME record parts if that is what you mean. I should have given a simpler example. It's actually a bit of a Terraform hack to have optional blocks in a resource. Anyway, so what you're telling me is that you're returning the absolute FQDN which means it has the root level (trailing period)?

**Comment by WodansSon** [comment] 2020-05-14 18:57
@bcline760,  Yes that is what is being returned from the Azure RP and I am just expose it in the resource.

Please let me know if you have anymore questions, if not I will go ahead and close this issue. Thanks again! 🚀

**Closed** 2020-05-15 01:04 UTC
Labels: service/dns, service/frontdoor, waiting-response
