### ISSUE TITLE
azurerm_application_gateway does not handle empty probe.match value correctly

### ISSUE THREAD

**Issue by schuettecarsten** [terraform-providers/terraform-provider-azurerm#3610] opened 2019-06-06 20:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version 
`1.29.0`

### Affected Resource(s)

* `azurerm_application_gateway`
* `azurerm_application_gateway.probe.match`-blocks

### Terraform Configuration Files

An application gateway configuration that uses this `probe` and `match` blocks:
```hcl
  probe {
    name                = "http_probe${var.prod_domain_suffix}"
    host                = "probe${var.prod_domain_suffix}"
    path                = "/"
    protocol            = "Http"
    interval            = 60
    timeout             = 15
    unhealthy_threshold = 2
    minimum_servers     = 2
    match {
      status_code = ["100-999"]
      body        = ""
    }
  }
```

### Expected Behavior

The "http response body match" field on Azure should be empty when the body property is set to empty.

### Actual Behavior

The "http response body match" field on Azure is set to `*` when the body property is explicitly set to empty. Unfortunately, Azure only looks for the presence of the field value in the response and does not evaluate expressions. So, `*` means that an asterisk must be in the response body and does _not_ mean 'everything'.

I also suggest to change the default value of `body` from `*` to empty.

### References

https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-probe-overview

**Comment by ByteCommander** [comment] 2019-06-13 09:55
Duplicate of #1920 ? I was just searching for this too.

**Comment by schuettecarsten** [comment] 2019-06-13 14:28
Not exactly. Biggest problem now is that even when you set match value explicitly to "", you also get "*" on Azure. So, it's a bug (not a feature request/change) that you cannot set empty probe value.

**Comment by tombuildsstuff** [comment] 2019-08-30 15:02
hi @schuettecarsten 

Thanks for opening this issue :)

Taking a look through as @ByteCommander has mentioned this appears to be a duplicate of #1920 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1920 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-30 15:02 UTC
Labels: bug, service/application-gateway
