### ISSUE TITLE
Importing an App Service Plan tied to an ASE immediately forces the ASP to be destroyed and recreated

### ISSUE THREAD

**Issue by DanielBMann9000** [terraform-providers/terraform-provider-azurerm#2630] opened 2019-01-09 15:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

C:\terraform>terraform -v
Terraform v0.11.11
+ provider.azurerm v1.20.0

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "asp" {
  name                       = "${var.appName}-asp"
  resource_group_name        = "${azurerm_resource_group.applicationResourceGroup.name}"
  location                   = "${azurerm_resource_group.applicationResourceGroup.location}"
  app_service_environment_id = "${local.ase_id}"

  kind = "app"

  sku = {
    tier     = "Isolated"
    size     = "I1"
    capacity = "${local.initialCapacity}"
  }

  reserved         = false
  per_site_scaling = false
  tags             = "${var.tags}"
}
```
If this fails after the hour-long timeout occurs (which has a roughly 50% chance of occurring, see #2616), I would expect I can use `import` after the resource finishes provisioning.

Running import on the resource generates state that looks like this:
```
"azurerm_app_service_plan.asp": {
                    "type": "azurerm_app_service_plan",
                    "depends_on": [],
                    "primary": {
                        "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/serverFarms/xxx-asp",
                        "attributes": {
                            "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/serverFarms/xxx-asp",
                            "kind": "",
                            "name": "",
                            "resource_group_name": "xxx",
                            "sku.#": "0",
                            "tags.%": "0"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.azurerm"
                }
```

### Expected Behavior

Running `terraform plan` should identify the ASP as correctly provisioned.

### Actual Behavior

`terraform plan` identifies the ASP as having to be destroyed and recreated.

```
-/+ azurerm_app_service_plan.asp (new resource required)
      id:                                                           "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/serverFarms/xxx-asp" => <computed> (forces new resource)
      app_service_environment_id:                                   "" => "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Web/hostingEnvironments/zzz" (forces new resource)
      kind:                                                         "" => "app" (forces new resource)
      location:                                                     "" => "eastus" (forces new resource)
      maximum_number_of_workers:                                    "" => <computed>
      name:                                                         "" => "xxx-asp" (forces new resource)
      per_site_scaling:                                             "" => "false"
      properties.#:                                                 "" => <computed>
      reserved:                                                     "" => "false"
      resource_group_name:                                          "xxx" => "xxx"
      sku.#:                                                        "0" => "1"
      sku.0.capacity:                                               "" => "2"
      sku.0.size:                                                   "" => "I1"
      sku.0.tier:                                                   "" => "Isolated"
      tags.%:                                                       "0" => "2"
      tags.a:                                                       "" => "b"
      tags.c:                                                       "" => "d"
```

`import` appears to be missing several fields when importing the ASP into the state file.

**Comment by tombuildsstuff** [comment] 2019-01-15 12:31
hey @DanielBMann9000 

Thanks for opening this issue :)

The Azure API returns the representation of a resource (such as in this case an App Service Plan) at the time that it was last modified - as such the resource returned from the API may not necessarily match the API definition (which is being used in the SDK) if it's an older resource (for example, certain fields can be omited from the API Response if a resource was created during a Preview when they weren't required, or had a different location in the response). Out of interest how long ago was the App Service Plan provisioned?

It should be possible to force this representation to be updated to the latest by making any change to the resource - such as adding or removing a Tag - which means that the representation will be updated in the API such that these fields are returned. Once that's done it should be possible to run `terraform refresh` and have Terraform show no changes are required - would you be able to take a look and see if that works for you?

Thanks!

**Comment by jnancel** [comment] 2019-02-27 20:23
This is not limited to ASE app service plan. I have the same behaviour when importing a Linux app service plan. Exactly the same output as @divgo.

I tried to manually update the state to add all the missing fields and then state push the file :
```
$ terraform state show azurerm_app_service_plan.plan
id                  = /subscriptions/xxxxxxxxxxx/resourceGroups/yyyyyyyyyyyy/providers/Microsoft.Web/serverFarms/zzzzzzzzzzzz
kind                = Linux   <= parameter added
location                                = northeurope    <= parameter added
maximum_number_of_workers               = 2    <= parameter added
name                                    = zzzzzzzzzzzzzz    <= parameter added
per_site_scaling                        = false
properties.#                            = 1 <= parameter added
properties.0.app_service_environment_id = <= parameter added
properties.0.per_site_scaling           = false <= parameter added
properties.0.reserved                   = true <= parameter added
reserved                                = true <= parameter added
resource_group_name                     = yyyyyyyyyyyyyyyyyyyyyy
sku.#                                   = 1 <= parameter added
sku.0.capacity                          = 2 <= parameter added
sku.0.size                              = S1 <= parameter added
sku.0.tier                              = Standard <= parameter added
tags.%                                  = 0

```

But when applying `plan`, it told me again that it needs to be recreated :
```
azurerm_app_service_plan.plan (new resource required)
      id:                                              "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/yyyyyyyyyyyyy/providers/Microsoft.Web/serverFarms/zzzzzzzzzzzzz" => <computed> (forces new resource)
      app_service_environment_id:                      "" => <computed>
      kind:                                            "" => "Linux" (forces new resource)
      location:                                        "northeurope" => "northeurope"
      maximum_number_of_workers:                       "2" => <computed>
      name:                                            "" => "zzzzzzzzzzzzzzz" (forces new resource)
      per_site_scaling:                                "false" => <computed>
      properties.#:                                    "1" => <computed>
      reserved:                                        "true" => "true"
      resource_group_name:                             "yyyyyyyyyyyyy" => "yyyyyyyyyyyyyyy"
      sku.#:                                           "0" => "1"
      sku.0.capacity:                                  "" => "2"
      sku.0.size:                                      "" => "S1"
      sku.0.tier:                                      "" => "Standard"
      tags.%:                                          "0" => "5"
      tags.tag1:                            "" => "enabled"
      tags.tag2:                              "" => "enabled"
      tags.tag3:                             "" => "enabled"
      tags.env:                                        "" => "env"
      tags.stack:                                      "" => "stack"
```

The weird thing is that it took what I added in the state on the `location` parameter into account since it's not listed any more as a parameter that forces a new resource but other parameters were not taken into account.

**Comment by jnancel** [comment] 2019-02-27 20:32
After browsing the issue history, I think it's definitely tied to #1507

**Comment by tombuildsstuff** [comment] 2019-02-28 09:58
@jnancel thanks for the heads-up - I'd agree this is a duplicate of #1507

For users running into this issue - Resource ID's are case-sensitive in Terraform - as such please ensure the casing on the `serverfarms` segment of the ID is in the correct casing, which will resolve this issue - for example from [the App Service Plan Documentation](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#import):

```
$ terraform import azurerm_app_service_plan.instance1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Web/serverfarms/instance1
```

Thanks!

**Closed by tombuildsstuff** 2019-02-28 09:58 UTC
Labels: question, service/app-service
