### ISSUE TITLE
azurerm_api_management_certificate is missing Keyvault certificate input

### ISSUE THREAD

**Issue by AmudaPalani** [terraform-providers/terraform-provider-azurerm#10139] opened 2021-01-11 21:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management_certificate`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behaviour

 The azurerm_api_management_certificate is missing a way to input Keyvault certificate, whereas this is feasible through Azure API : https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/certificate/createorupdate#apimanagementcreatecertificatewithkeyvault.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-01-12 10:57
Duplicate of #10138

**Closed by tombuildsstuff** 2021-01-12 10:57 UTC
