### ISSUE TITLE
Functionapp keys

### ISSUE THREAD

**Issue by prabhakarreddy1234** [terraform-providers/terraform-provider-azurerm#7656] opened 2020-07-09 11:20 UTC
Issue #1493 is closed. So just want to track this feature here.

is data source `azurerm_function_app_key_management` available now? I don't see it in the documentation and the upstream blocker for this feature was resolved couple of years ago.

**Comment by tombuildsstuff** [comment] 2020-07-10 11:25
hi @prabhakarreddy1234 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #699 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #699 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-07-10 11:25 UTC
Labels: duplicate, new-data-source, service/functions
