### ISSUE TITLE
Missing azurerm_api_management_policy resource

### ISSUE THREAD

**Issue by evertonmc** [terraform-providers/terraform-provider-azurerm#5001] opened 2019-11-27 09:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `azurerm 1.36.0`

### Affected Resource(s)

* `azurerm_api_management`

### Debug Output

``` 
[error]Terraform command 'apply' failed with exit code '1'.:  Error setting Policies for API Management Service "***" (Resource Group "*******"): apimanagement.PolicyClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Error in element 'PropertyName' on line 62, column 7: Cannot find a property 'PropertyName'","target":"PropertyName"},{"code":"ValidationError","message":"Error in element 'set-variable' on line 76, column 4: Cannot find a property 'PorpertyName'","target":"set-variable"}]
```
### Expected
It is necessary to have the global policy deployed *after* properties (aka NamedValues) since the global policy can (and probably will) reference a property value.

### Current behaviour
* It sometimes deploys successfully, it sometimes fails to deploy in this order.
* there is a *_policy resource for operation, product, and api, but not for global policy

### Suggested solution
Create extra resource for *`azurerm_api_management_policy`* so it can be made dependent on `azurerm_api_management` similar to the current behavior of `azurerm_api_management_authorization_server`

**Comment by tombuildsstuff** [comment] 2019-11-27 10:36
hi @evertonmc 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4758 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4758 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-11-27 10:36 UTC
Labels: duplicate, new-resource, service/api-management

**Comment by evertonmc** [comment] 2019-11-27 12:01
@tombuildsstuff thanks, works for me. No milestone for it yet?

**Comment by tombuildsstuff** [comment] 2019-11-27 14:10
@evertonmc correct - there's an issue tracking it but there's no timeline for it at the moment
