### ISSUE TITLE
Support for storage_data_disk in azurerm_linux_virtual_machine and azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by xortim** [terraform-providers/terraform-provider-azurerm#8213] opened 2020-08-23 14:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`storage_data_disk` blocks in `azurerm_virtual_machine` allowed attaching disks to the virtual machine at the time of provisioning. This allowed first-boot only configurations to perform necessary actions on the disks such as partitioning and formatting and mounting.

### New or Affected Resource(s)

* azurerm_linux_virtual_machine
* azurerm_windows_virtual_machine

### Potential Terraform Configuration

Same as azurerm_virtual_machine.

**Comment by tombuildsstuff** [comment] 2020-08-24 04:29
hi @xortim 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6117 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6117 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-24 04:29 UTC
Labels: duplicate, enhancement, service/virtual-machine
