### ISSUE TITLE
TERRAFORM CRASH when using 2.0.0 and 1.44.0 version in azurerm provider

### ISSUE THREAD

**Issue by vermaaakansha** [terraform-providers/terraform-provider-azurerm#5965] opened 2020-03-03 09:08 UTC
Hi, 
I'm trying to deploy Azure Virtual Machine with Vnet, Subnet, Loadbalancer, DNS, storage account using their modules. 
But terraform crashes while executing the code. 
Whereas when i try to execute individual modules (using provider azurerm version 2.0.0), the resources gets deploys successfully. 
**Can you please help in debugging the crash.log (PFA file)**
[crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/4280234/crash.log)
![crashlog](https://user-images.githubusercontent.com/50359777/75759908-530da900-5d5c-11ea-9a3b-5cb50b83a9bc.jpg)

**Comment by tombuildsstuff** [comment] 2020-03-04 00:24
hi @vermaaakansha 

Thanks for opening this issue :)

Taking a look through the crash log here this the root cause of this appears to be the same as #5897 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5897 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-03-04 00:24 UTC
Labels: bug, crash, duplicate
