### ISSUE TITLE
unable to list provider registration status using Azure CLI

### ISSUE THREAD

**Issue by jasonrakers** [terraform-providers/terraform-provider-azurerm#10461] opened 2021-02-04 02:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
AzureRM - 2.44.0, 2.45.0, 2.45.1
Terraform v0.14.4

### Affected Resource(s)

* azurerm provider

### Terraform Configuration Files

provider "azurerm" {
  features {}
}
resource "azurerm_virtual_network" "vnet-test" {
    name = "vnet-test"
    address_space = ["10.1.22.0/24"]
    dns_servers = ["10.1.36.31", "10.1.36.50"]
    location = "East US"
    resource_group_name = "RG-new"
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Generate terraform plan output (output from v.2.43.0 below)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_virtual_network.vnet-test will be created
  + resource "azurerm_virtual_network" "vnet-test" {
      + address_space         = [
          + "10.1.22.0/24",
        ]
      + dns_servers           = [
          + "10.1.36.31",
          + "10.1.36.50",
        ]
      + guid                  = (known after apply)
      + id                    = (known after apply)
      + location              = "eastus"
      + name                  = "vnet-test"
      + resource_group_name   = "RG-new"
      + subnet                = (known after apply)
      + vm_protection_enabled = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

### Actual Behaviour

Generates error:
Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c61b06f4-16b9-4f39-b832-e1012463b0cb/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"bad_request_102","message":"Required metadata header not specified"}} Endpoint http://localhost:50342/oauth2/token?api-version=2017-09-01&resource=https%3A%2F%2Fmanagement.azure.com%2F

  on main.tf line 1, in provider "azurerm":
   1: provider "azurerm" {

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Tested azurerm version 2.43.0 without issues   
Using Azure CLI to do terraform plan

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-02-04 06:42
hi @jasonrakers 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #10292 where there's a bug in the upstream library the Azure SDK uses, which is tracked in this issue: https://github.com/Azure/go-autorest/issues/612. From our side rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #10292, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-04 06:42 UTC
