### ISSUE TITLE
replacing storage account with object replication rule creates orphan rules

### ISSUE THREAD

**Issue by blindzero** [terraform-providers/terraform-provider-azurerm#8649] opened 2020-09-27 12:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.27.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
variable "subscription_id" {
  type = string
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.27.0"
    }
  }
}

provider "azurerm" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=2.27.0"
  subscription_id             = var.subscription_id
  skip_provider_registration  = true

  features {}
}

resource "azurerm_resource_group" "rg-test" {
  name      = "rg-test"
  location  = "West Europe"
}

resource "azurerm_storage_account" "stac-test-source" {
  name                     = "stactestsrc"
  resource_group_name      = azurerm_resource_group.rg-test.name
  location                 = azurerm_resource_group.rg-test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  access_tier              = "Hot"
  allow_blob_public_access = true
  min_tls_version          = "TLS1_2"
  enable_https_traffic_only = true
  network_rules {
    bypass = ["AzureServices"]
    default_action = "Allow"
  }
}
resource "azurerm_storage_container" "blob-inbox" {
  name                  = "blob-inbox"
  storage_account_name  = azurerm_storage_account.stac-test-src.name
  container_access_type = "private"
}
resource "azurerm_storage_account" "stac-test-dst" {
  name                     = "stactestdst"
  resource_group_name      = azurerm_resource_group.rg-test.name
  location                 = azurerm_resource_group.rg-test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  access_tier              = "Cool"
  allow_blob_public_access = true
  min_tls_version          = "TLS1_2"
  enable_https_traffic_only = true
  network_rules {
    bypass = ["AzureServices"]
    default_action = "Allow"
  }
}
resource "azurerm_storage_container" "blob-vault" {
  name                  = "blob-vault"
  storage_account_name  = azurerm_storage_account.stac-test-dst.name
  container_access_type = "private"
}

```

### Expected Behavior

Destroying a storaceaccount which has an object replication rule (actually created by az portal, as storage or is not supported by terraform yet) related should not leave the or rule orphaned.

### Actual Behavior

Any action that destroys / replaces a storage account that has an or rule / policy created will leave the policy in az.
That brings conflicts and new rules can not be set up for the old target / source which is still existing.

### Steps to Reproduce

1. Create two storage accounts with terraform
  `terraform apply`
2. Log into Azure Portal and create object replication rule from source storage account, source container "blob-inbox" to destination storage account, destination containr "blob-vault"
3. Change name of source account which leads to replacement
   `terraform apply`
4. Log into Azure Portal and try to create object replication rule from new (renamed) source storage account, source container "blob-inbox" to destination storage account, destination containr "blob-vault". --> leads into error

### Important Factoids

Terraform does not support object replication yet (feature request #8647), thats why the setting must be done manually.

### References

* #8647

**Comment by mybayern1974** [comment] 2020-09-29 02:37
hi  @blindzero 

Thanks for opening this issue. May I assume this is a dup issue with #8647 ? If so, would you mind subscribing to #8647 and we close this one to avoid having multiple issues track the same thing?

Thanks!

**Comment by blindzero** [comment] 2020-09-29 16:38
Servus @mybayern1974 
Honestly I created #8647 as a feature request. 
I then raised this request as a bug as it should be mitigated even if #8647 is not fully realized yet.

**Comment by mybayern1974** [comment] 2020-10-03 03:33
Thank you for mentioning this. Removed the dup tabel.

**Comment by neil-yechenwei** [comment] 2020-10-09 00:25
After checked, seems the root cause is that replication rule of `stac-test-dst` isn't deleted after `stac-test-source` is recreated successfully. So you have to manually remove the replication rule of `stac-test-dst` on Azure portal since terraform hasn't supported it for now. Once it's supported, I assume it would be deleted by terraform. So I assume it's a duplicate issue with 8647. I think we just need to keep one issue to track. So suggest to close this issue.

**Comment by mybayern1974** [comment] 2020-10-10 04:25
hi @blindzero, per neil's latest comment, would you agree if we close this issue and you could subscribe #8647?

**Closed** 2020-10-10 08:39 UTC
Labels: bug, service/storage, waiting-response
