### ISSUE TITLE
KeyVault Cannot be deployed if public network access is disabled (on versions >2.33.0)

### ISSUE THREAD

**Issue by ericfode** [terraform-providers/terraform-provider-azurerm#11245] opened 2021-04-07 21:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Any version `>2.33.0` will show this behavior. When logic was introduced to handle adding contacts to the keyvault at provisioning time this regression was introduced. 

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

In a keyvault deployed like this

```hcl
provider "azurerm" {
  version = "~>2.34.0"
  features {}
}

provider "azurerm" {
  version         = "~>2.34.0"
  alias           = "vnet"
  subscription_id = var.vnet.subscription_id
  features {}
}


resource "azurerm_resource_group" "keyvault_rg" {
  name     = var.keyvault.resource_group_name
  location = var.keyvault.location
}

resource "azurerm_key_vault" "keyvault" {
  tenant_id                       = var.keyvault.tenant_id
  name                            = var.keyvault.name
  location                        = azurerm_resource_group.keyvault_rg.location
  resource_group_name             = azurerm_resource_group.keyvault_rg.name
  enabled_for_deployment          = var.keyvault.enabled_for_deployment
  enabled_for_disk_encryption     = var.keyvault.enabled_for_disk_encryption
  enabled_for_template_deployment = var.keyvault.enabled_for_template_deployment
  sku_name                        = "standard"
  soft_delete_enabled             = var.keyvault.soft_delete_enabled
  purge_protection_enabled        = var.keyvault.purge_protection


  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }
}

resource "azurerm_private_endpoint" "keyvault-privlink" {
  provider            = azurerm.vnet
  name                = var.keyvault.private_endpoint_name
  location            = data.azurerm_resource_group.vnet-rg.location
  subnet_id           = data.azurerm_subnet.endpoint-snet.id
  resource_group_name = data.azurerm_resource_group.vnet-rg.name
  private_service_connection {
    name                           = var.keyvault.private_endpoint_conn_name
    private_connection_resource_id = azurerm_key_vault.keyvault.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }
}

```

### Debug Output

Due to corporate constraints we cannot provide actual debug output. But! I have the exact line of code that is affected here. This is not about "why does this fail", it's about "a change was made and created a regression"  

Times out trying to reach the keyvault url. Right here https://github.com/terraform-providers/terraform-provider-azurerm/pull/11240/files#diff-6776a72ab2fb17566f25c97844fc10fd0d54b2617426df2b1b27dea90d19fea6L387

### Expected Behaviour

Terraform does not attempt to reach out to the provisioned Key Vault's data plane. and provisioning is able to succeed even if it is behind a private endpoint and not accessible publicly. 

### Actual Behaviour

Terraform times out trying to reach the keyvault, because the private endpoint depends on the id of the keyvault to be created and the keyvault has public internet access disable. This works in version 2.33 or earlier.   

```
>2.34 broken because it tries to establish a connection to the provisioned keyvault to set contacts regardless of what is configured. 
==2.34 works and has the new rbac resources we need
<2.33 works but does not have rbac
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We have to provision everything without public internet access.

### References

* #11240 Is a PR that would add a janky work around just to illustrate exactly what is wrong.

**Comment by manicminer** [comment] 2021-04-29 22:08
Hi @ericfode, thanks for reporting this. I've tested the resource without [your patch](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11240/files) whilst enabling a restrictive network ACL that doesn't include the Terraform host, and it works without error.

As it happens, when the key vault is created, the check that hits the vault URL doesn't time out but receives a 403 Forbidden reply, and since it intentionally doesn't perform any checks on the status code of the reply, this check passes. Similarly in the Read function, when retrieving contacts, there is an explicit check for a 403 reply which doesn't cause the function to error out but rather to assume that no contacts are set.

We do have an acceptance test that validates this scenario, to help prevent such a regression. Of course, Terraform is unable to offer any data plane only features without being given access to the keyvault, but this is a judgement left to the user and as best I can tell, we don't depend on the data plane for key vault creation.

I'm going to close this for now, but if I have misunderstood your configuration or if you are not observing the same behavior, please post your logs (or raise a new issue if this one gets locked) and we'll be happy to take another look. Thanks!

**Closed by manicminer** 2021-04-29 22:08 UTC
Labels: regression, service/keyvault
