### ISSUE TITLE
Azure Database for Postgres provider bug

### ISSUE THREAD

**Issue by leroysong** [terraform-providers/terraform-provider-azurerm#5060] opened 2019-12-04 02:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_postgresql_server`

### Description
When createing the postgres server resource, the name of server must be lower case. It would throw error as below when the name of var.postgres_server_name is upper case. I tried to create this resource on Azure portal directly and upper case is allowed. So I believe this issue can be improved

### Terraform Configuration Files

```hcl

resource "azurerm_postgresql_server" "rsconnect-postgres-server" {
  name                = "${var.postgres_server_name}"
  location            = "australiaeast"
  resource_group_name = "${var.rsconnect_rg_name}"

  sku {
    name     = "GP_Gen5_2"
    capacity = 2
    tier     = "GeneralPurpose"
    family   = "Gen5"
  }

  storage_profile {
    storage_mb            = 8192
    backup_retention_days = 7
    geo_redundant_backup  = "Disabled"
  }

  administrator_login          = "${var.postgres_username}"
  administrator_login_password = "${var.postgres_admin_password}"
  version                      = "9.6"
  ssl_enforcement              = "Enabled"
}

resource "azurerm_postgresql_virtual_network_rule" "rsconnect-postgres-server-vnet-rule" {
  name                                 = "${var.postgres_vnet_rule_name}"
  resource_group_name                  = "${var.rsconnect_rg_name}"
  server_name                          = "${azurerm_postgresql_server.rsconnect-postgres-server.name}"
  subnet_id                            = "${var.deploy_subnet_id}"
  ignore_missing_vnet_service_endpoint = true
}
```
### Debug Output

```
Error: Provider produced inconsistent final plan

When expanding the plan for
azurerm_***ql_virtual_network_rule.rsconnect-***-server-vnet-rule to
include new values learned so far during apply, provider "azurerm" produced an
invalid new value for .server_name: was cty.StringVal("PG-DEV-AUE"), but
now cty.StringVal("pg-dev-aue").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

* #0000

**Comment by katbyte** [comment] 2019-12-08 02:14
Hi @leroysong,

The reason you are seeing this problem is the API will accept uppercase letters but will lowercase them upon creation. Please see this issue on the SDK: https://github.com/Azure/azure-sdk-for-go/issues/6305.

We will be adding validation in the future to prevent uppercase names as they are not valid.

**Comment by ausfestivus** [comment] 2019-12-17 03:03
@katbyte this (#5060) is a dupe of https://github.com/terraform-providers/terraform-provider-azurerm/issues/4813

**Comment by katbyte** [comment] 2020-01-17 20:19
Thanks @ausfestivus, closing as a duplicate of #4813

**Closed by katbyte** 2020-01-17 20:19 UTC
Labels: bug, service/postgresql
