### ISSUE TITLE
Allow shared key access disable parameter in azurerm missing

### ISSUE THREAD

**Issue by iiXamOii** [terraform-providers/terraform-provider-azurerm#10622] opened 2021-02-17 15:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey i am currently using Terraform v0.12.28 and provider azurerm v2.22.0 i wanted to Disable (Allow Shared Access Key, Allow Blob public access, and use TLS1_2) in Azure Storage Configuration to make it secure, i found "allow_blob_public_access = false" and "min_tls_version = "TLS1_2" but unable to find parameter to disable Allow Shared Access Key.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
  resource "azurerm_storage_account" "main" {
  name                     = var.storage_account_name
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = var.account_tier
  account_replication_type = var.account_replication_type
  allow_blob_public_access = false
  min_tls_version = "TLS1_2"
  
} 
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Satyricon** [comment] 2021-04-09 14:09
Any news if support for managing `Allow shared key access` is planned for implementation?

**Comment by OliverRC** [comment] 2021-06-15 10:10
I'd check out issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/11460 which has a work around.

**Comment by tombuildsstuff** [comment] 2021-06-15 10:42
Duplicate of #11460

**Closed by tombuildsstuff** 2021-06-15 10:42 UTC
