### ISSUE TITLE
Zero size nodepools are available now on AKS. min_count should allow 0 as a valid value now

### ISSUE THREAD

**Issue by zeroX-tj** [terraform-providers/terraform-provider-azurerm#8245] opened 2020-08-25 14:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.0
+ provider registry.terraform.io/-/azurerm v2.24.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "cpupool" {
  kubernetes_cluster_id = var.cluster_id
  name = "cpupool"
  vm_size = "Standard_F16"
  node_labels = {
    agentpool = "cpupool"
  }
  spot_max_price = -1
  eviction_policy = "Deallocate"
  enable_auto_scaling = true
  min_count = 0
  max_count = 25
  count = 0
}
```

### Expected Behavior

Create a nodepool with 0 nodes

### Actual Behavior

Error: expected min_count to be in the range (1 - 100), got 0

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/Azure/AKS/issues/1565
https://github.com/Azure/AKS/releases/tag/2020-08-10
* #0000

**Comment by tombuildsstuff** [comment] 2020-08-25 14:53
hi @zeroX-tj 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8219 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8219 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-25 14:53 UTC

**Comment by zeroX-tj** [comment] 2020-08-25 14:55
Sure, np, didn't see that one when i was looking for existing ones, my bad!
