### ISSUE TITLE
azurerm_resource_group_template_deployment - Specifying  'parameters_content'

### ISSUE THREAD

**Issue by AndrewJWaite** [terraform-providers/terraform-provider-azurerm#8756] opened 2020-10-06 10:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.4
+ provider registry.terraform.io/-/azurerm v2.30.0        
+ provider registry.terraform.io/hashicorp/azurerm v2.30.0

### Affected Resource(s)

* `azurerm_resource_group_template_deployment`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group_template_deployment" "default" {
  name                = "deploy"
  resource_group_name = azurerm_resource_group.default.name
  deployment_mode     = "Incremental"
  template_content = templatefile("../data/ARM/logic-app-connections.json",
    {}
  )
  parameters_content = templatefile("../data/ARM/logic-app-connections.parameters.json",
    {
      sendgrid_connection_name = "sendgrid"
      sendgrid_api_key         = "xxx"
    }
  )
}
```

**Template file**
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "sendgridConnectionName": {
      "type": "string"
    },
    "sendgridApiKey": {
      "type": "string"
    }
  },
  "variables": {
    "location": "[resourceGroup().location]",
    "subscriptionId": "[subscription().subscriptionId]",
    "sendgridApiId": "[concat('/subscriptions/', variables('subscriptionId'), '/providers/Microsoft.Web/locations/', variables('location'),'/managedApis/sendgrid')]"
  },
  "resources": [
    {
      "type": "Microsoft.Web/connections",
      "apiVersion": "2016-06-01",
      "name": "[parameters('sendgridConnectionName')]",
      "location": "[variables('location')]",
      "properties": {
        "displayName": "[parameters('sendgridConnectionName')]",
        "customParameterValues": {},
        "api": {
          "id": "[variables('sendgridApiId')]"
        },
        "parameterValues": {
          "apiKey": "[parameters('sendgridApiKey')]"
        }
      }
    }
  ],
  "outputs": {}
}
```

**Template parameter file**
I have also tested without using template variables and hard-coding the values. The ARM template and parameter file (with hard-coded values) were tested successfully with `New-AzResourceGroupDeployment`

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "sendgridConnectionName": {
      "value": "${sendgrid_connection_name}"
    },
    "sendgridApiKey": {
      "value": "${sendgrid_api_key}"
    }
  }
}
```

### Expected Behavior
The ARM template is successfully deployed

### Actual Behavior

```
Error: validating Template Deployment "deploy" (Resource Group "xxx"): requesting validating: resources.DeploymentsClient#Validate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Error converting value \"https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#\" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 991.'."
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-10-06 12:33
hey @AndrewJWaite 

Thanks for opening this issue.

Taking a look through here, the parameters needed when provisioning using PowerShell and when using the API are slightly different - whilst you can specify a parameters file with PowerShell, the API here is expecting the parameter content directly, [there's an example of how to do this in this test case](https://github.com/terraform-providers/terraform-provider-azurerm/blob/f6568c9b65cb9524762ce2a0e9ba07bb4e5c4de0/azurerm/internal/services/resource/tests/template_deployment_resource_group_resource_test.go#L315-L345) - can you take a look and see if that works for you?

Thanks!

**Comment by AndrewJWaite** [comment] 2020-10-06 12:48
Thanks @tombuildsstuff 

I've tested using the example and this works.

Appreciate the quick reply.

**Comment by AndrewJWaite** [comment] 2020-10-06 13:12
Actually, sorry, it works first time but not subsequent times.

```
Error: validating Template Deployment "deploy" (Resource Group "xxx"): requesting validating: resources.DeploymentsClient#Validate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The value for the template parameter 'sendgridApiKey' at line '1' and column '191' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'." AdditionalInfo=[{"info":{"lineNumber":1,"linePosition":191,"path":"properties.template.parameters.sendgridApiKey"},"type":"TemplateViolation"}]
```

When testing with PowerShell the deployment can be run multiple times.

**Comment by tombuildsstuff** [comment] 2020-10-26 13:06
hey @AndrewJWaite 

Thanks for the extra info here, since #8840 is a duplicate of this issue but includes a link to the code which'll fix this I hope you don't mind, but I'm going to close this in favour of that issue - would you mind subscribing to #8840 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-26 13:06 UTC
Labels: bug, service/template
