### ISSUE TITLE
Provider 1.26.0, 1.27.1 breaks when using service principal with access to resource group

### ISSUE THREAD

**Issue by flmarins** [terraform-providers/terraform-provider-azurerm#3483] opened 2019-05-21 14:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14
provider azurerm 1.27.1
### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

**Fails**
```hcl
provider "azurerm" {
   subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
  version = "=1.27.1"
}

resource "azurerm_application_insights" "appinsights" {
  name                = "testflm"
  location            = "West Europe"
  resource_group_name = "rgname"
  application_type    = "Web"
}
```
**Works**
```hcl
provider "azurerm" {
   subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
  version = "=1.25.0"
}

resource "azurerm_application_insights" "appinsights" {
  name                = "testflm"
  location            = "West Europe"
  resource_group_name = "rgname"
  application_type    = "Web"
}
```
### Debug Output

**Guids replaced by 00000000-0000-0000-0000-000000000000**
Error: Error running plan: 1 error occurred:
        * provider.azurerm: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.Cdn with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '00000000-0000-0000-0000-000000000000' with object id '00000000-0000-0000-0000-000000000000' does not have authorization to perform action 'Microsoft.Cdn/register/action' over scope '/subscriptions/00000000-0000-0000-0000-000000000000'.".
### Steps to Reproduce
Using a service principal with only access as owner in the resource group that will be deployed
https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2019-05-21 15:19
hi @flmarins 

Thanks for opening this issue :)

Azure's concept of a Resource Provider requires that the Resource Provider is registered before any API's within that Resource Provider can be called. As such, rather than failing during an API call / to improve the user experience Terraform automatically attempts to register any Resource Providers that it supports by default - to ensure that the API's are available when they're needed; and since this list is stored within Terraform, we extend this list from time to time as Terraform is updated to support new functionality (provided in new Resource Providers).

If you'd prefer to manage Resource Provider Registration outside of Terraform (for example you're running in a restricted environment) - it's possible to opt-out of this behaviour by setting this field [in the Provider block](https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration).

Since this is working as intended I'm going to close this issue for the moment - but please let us know if disabling this functionality doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2019-05-21 15:19 UTC
Labels: question

**Comment by flmarins** [comment] 2019-05-21 15:25
Thanks @tombuildsstuff  for the quick answer on that :)
