### ISSUE TITLE
Support for MS SQL VM

### ISSUE THREAD

**Issue by yupwei68** [terraform-providers/terraform-provider-azurerm#5264] opened 2019-12-27 01:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Ms Sql VM is desired to be added.

SQL Server on Azure virtual machines enables you to use full versions of SQL Server in the Cloud without having to manage any on-premises hardware. SQL Server VMs also simplify licensing costs when you pay as you go.

![image](https://user-images.githubusercontent.com/56525716/71497084-9269d600-2891-11ea-9300-0ea26ac96437.png)

### New or Affected Resource(s)

* azurerm_mssql_virtual_machine
`

### References

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-server-iaas-overview

* #0000

**Comment by tombuildsstuff** [comment] 2019-12-27 11:56
duplicate of #3891

**Closed by tombuildsstuff** 2019-12-27 11:56 UTC
