### ISSUE TITLE
Case change in reported Resource Group & Recovery Service Group names causes azurerm_recovery_services_protected_vm recreaction

### ISSUE THREAD

**Issue by WascawyWabbit** [terraform-providers/terraform-provider-azurerm#4790] opened 2019-11-01 10:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform in Azure Cloud Shell:
Terraform v0.12.12
+ provider.azurerm v1.36.1

### Affected Resource(s)

azurerm_recovery_services_protected_vm, specifically the following attributes:
   backup_policy_id
   recovery_vault_name
   resource_group_name

### Terraform Configuration Files

```hcl
resource "azurerm_recovery_services_vault" "Vault1" {
    name                = var.Backups-Infra-vault-name
    location            = azurerm_resource_group.Backups.location
    resource_group_name = azurerm_resource_group.Backups.name
    sku                 = var.Backups-sku
}

resource "azurerm_recovery_services_protection_policy_vm" "Policy1" {
    name                = "Daily-30d"
    resource_group_name = azurerm_resource_group.Backups.name
    recovery_vault_name = azurerm_recovery_services_vault.Vault1.name

    timezone            = "GMT Standard Time"

    backup {
        frequency       = "Daily"
        time            = "23:00"
    }

    retention_daily {
        count           = 30
    }
}

resource "azurerm_recovery_services_protected_vm" "Server1" {
    resource_group_name = lower( azurerm_resource_group.Backups.name )
    recovery_vault_name = lower( azurerm_recovery_services_vault.Vault1.name )
    source_vm_id        = azurerm_virtual_machine.Server1.id
    backup_policy_id    = azurerm_recovery_services_protection_policy_vm.Policy1.id
}
```

### Expected Behavior

The vault, rg and backup had been in place for some time.
No changes were made to the HCL for these items.
Running terraform after a few days with the same config should have resulted in no changes.

### Actual Behavior

The resource group and policy names were previously returned from Azure as lowercase.
Now they match the (mixed) case of the actual names of the Azure objects.
Terraform sees the case change in the specific attributes above and  attempts to delete and recreate the  azurerm_recovery_services_protected_vm item, which fails because Azure soft deletes backups for 30 days.

### Steps to Reproduce

1. Undelete the backup in the Azure portal / etc
2. `terraform apply`

### Important Factoids

No special accounts or environments.

Encasing the rg name and policy names in lower in the code prevents the attempt to delete and recreate the backup, however it does not prevent terraform from attempting to update the backup_id, which causes terraform to eventually bomb out each time the config is run.  Azure sees the backups as fine (after the lower() code change).

**Comment by tombuildsstuff** [comment] 2019-11-01 10:54
hi @WascawyWabbit 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4774 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4774 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-11-01 10:54 UTC
Labels: duplicate, service/recovery-services, upstream-microsoft
