### ISSUE TITLE
Unable to import existing cosmosdb-mongo collection into terraform state

### ISSUE THREAD

**Issue by avdhut1990** [terraform-providers/terraform-provider-azurerm#8190] opened 2020-08-20 18:07 UTC
### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Terraform (and AzureRM Provider) Version
```
terraform version
Terraform v0.12.29
+ provider.azurerm v2.20.0
```
### Affected Resource(s)

- azurerm_cosmosdb_mongo_collection

### Terraform Configuration Files
```
resource "azurerm_cosmosdb_mongo_collection" "mongodb_collection" {
  name                = "subscription"
  resource_group_name = "rgrp-dwa1-es-codb"
  account_name        = "codb-dwa1-es-prodsmdb001"
  database_name       = "codb-dwa1-es-prodsmdb001_alert"

  default_ttl_seconds = "0"
  shard_key           = "alert_def_code"
  throughput          = 400
}
```
### Expected Behavior
Terraform import should import the resource into the terraform state.

### Actual Behavior
Raises an error and prevents import of resource into terraform state.

```
# azurerm_cosmosdb_mongo_collection.mongodb_collection will be created
  + resource "azurerm_cosmosdb_mongo_collection" "mongodb_collection" {
      + account_name        = "codb-dwa1-es-prodsmdb001"
      + database_name       = "codb-dwa1-es-prodsmdb001_alert"
      + default_ttl_seconds = 0
      + id                  = (known after apply)
      + name                = "subscription"
      + resource_group_name = "rgrp-dwa1-es-codb"
      + shard_key           = "alert_def_code"
      + system_indexes      = (known after apply)
      + throughput          = 400
    }

Error: Error reading Cosmos Mongo Collection "subscription" (Account: "codb-dwa1-es-prodsmdb001", Database: "codb-dwa1-es-prodsmdb001_alert"): documentdb.MongoDBResourcesClient#GetMongoDBCollection: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Invalid index key specified.\r\nActivityId: ff4561db-09e3-43ba-93c9-dfb6c0fe9a48, Microsoft.Azure.Documents.Common/2.11.0"
```

### Steps to Reproduce

1. terraform plan
2. terraform import

### Important Factoids
The resource was created using another terraform plan and was working as expected.

**Comment by tombuildsstuff** [comment] 2020-08-21 05:38
hi @avdhut1990

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8144 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8144 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-21 05:38 UTC
Labels: bug, duplicate, service/cosmosdb, upstream-microsoft
