### ISSUE TITLE
Terraform drop AKS nodepool cluster when changing min_count

### ISSUE THREAD

**Issue by wired-R** [terraform-providers/terraform-provider-azurerm#8662] opened 2020-09-28 17:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

➜   ✗ terraform -v                                                                                                                  
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_kubernetes_cluster" "cluster" {
  name                = "${var.aks_dns_prefix}-aks"
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  dns_prefix          = var.aks_dns_prefix

  
  default_node_pool {
    name            = "clusternode"
    enable_auto_scaling = true 
    max_count           = 5
    min_count           = 1
    node_count      = 1
    vm_size         = var.aks_vm_size
    os_disk_size_gb = 30
    vnet_subnet_id  = module.network.vnet_subnets[0]
  }

  service_principal {
    client_id     = var.appId
    client_secret = var.password
  }

  role_based_access_control {
    enabled = true
  }
  depends_on = [module.network]
  tags = {
    environment = var.environment
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "cluster" {
  name                  = "rookceph"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.cluster.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 3
  node_taints           = ["storage-node=true:NoSchedule"]
  os_disk_size_gb       = 30

  tags = {
    environment = var.environment
  }
}

```

### Actual Behavior

nodepool `rookceph` has been removed
### Steps to Reproduce
change `default_node_pool` `min_count` and `node_count` `1` to `2` and `teraform apply`

1. `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment] 2020-09-29 07:57
Thanks for opening this issue. I assume you cannot change min_count when enable_auto_scaling is true because terraform would return error message "Error: expanding `default_node_pool`: `node_count`(1) must be equal to or greater than `min_count`(2) when `enable_auto_scaling` is set to `true`".

**Comment by wired-R** [comment] 2020-09-29 08:03
but nodepool  rookceph will be destroyed. And if I remove the parameter in `default_node_pool` `enable_auto_scaling` and change the parameter `node_coun`t, the nodepool `rookceph` will also be destroyed.

**Comment by neil-yechenwei** [comment] 2020-09-29 09:43
After do more testing, I can repro it now. After investigated, I found the root cause is that azurerm_kubernetes_cluster_node_pool.vnet_subnet_id would also be set with default_node_pool.vnet_subnet_id in state file after set azurerm_kubernetes_cluster.default_node_pool.vnet_subnet_id. So I submitted a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8677).

**Comment by tombuildsstuff** [comment] 2020-09-30 11:34
hi @wired-R 

Thanks for opening this issue.

The AKS API behind the scenes deploys an ARM Template to deploy the components necessary for your Kubernetes Cluster. Whilst this API exposes a field for configuring the Subnet (which we expose as `vnet_subnet_id`) against each Node Pool - at this time when provisioning/updating clusters AKS requires that all Node Pools are located on the same subnet (or are all public).

This behaviour ultimately is controlled by the Default Node Pool configuration - where if this Node Pool is deployed on a subnet, then other Node Pools will also be force-deployed to this subnet (and if it's not on a subnet, these will all be public) - even if you're passing another value for this.

From Terraform's perspective this field is ForceNew, since this has to be set at Cluster/Node Pool creation time - and where this value is coming back from the AKS API (where the Node Pool is forced onto this subnet) - this is ultimately causing the ForceNew here.

For the moment we've opted to [document this behaviour underneath the `vnet_subnet_id` field](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#vnet_subnet_id) - however this isn't ideal since folks may miss it. Our understanding is that this feature (having different node pools on different subnets) has been "coming soon" for a while - and as such should start working whenever the AKS API supports it, which is why this is still enabled.

Whilst one solution to this would be to make the field Computed - as has been proposed in #8677 - ultimately that'd lead to a breaking change when this is implemented behind the scenes on Azure's side (and as such I've closed this PR for the moment). As such unfortunately we're stuck in this position of having shipped this - however the behaviour of this field could change at any time since this is controlled behind the scenes by AKS.

To work around this for the moment, you should be able to use the same value for `vnet_subnet_id` for all of the Node Pools (both Default and separate) - which should clear this diff here, and as such I'm going to close this issue for the moment - however I'd suggest [opening an issue on the AKS Repository](http://github.com/Azure/AKS/issues) should you have further questions around the configuration of AKS.

Thanks!

**Closed by tombuildsstuff** 2020-09-30 11:34 UTC
Labels: question, service/kubernetes-cluster
