### ISSUE TITLE
Resizing the Managed AKS cluster node size or type destroys and recreates the cluster 

### ISSUE THREAD

**Issue by vakkur** [terraform-providers/terraform-provider-azurerm#7801] opened 2020-07-17 20:43 UTC
This is a continuation of Resizing the Managed AKS cluster node size or type destroys and recreates the cluster #5311

I can resize the default node pool from Azure Portal, but when I resize it from terraform it actually destroys the entire cluster and recreating it.

I am not able to add the OMS_Agent and Kube Dashboard after the cluster creation, this is also triggering a destroy and recreate.

**Comment by Bessonov** [comment] 2020-09-30 14:59
It seem like a duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/7093

**Comment by tombuildsstuff** [comment] 2020-10-01 07:47
Thanks for the heads up @Bessonov - agreed, this appears to be a duplicate - would you mind subscribing to #7093 for updates?

**Closed by tombuildsstuff** 2020-10-01 07:47 UTC
Labels: service/kubernetes-cluster
