### ISSUE TITLE
oms_agent attempts to access workspace before it has been created

### ISSUE THREAD

**Issue by River991** [terraform-providers/terraform-provider-azurerm#2063] opened 2018-10-11 16:04 UTC
```
resource "azurerm_log_analytics_workspace" "aks_logging" {
  name                = "${var.log_workspace_name}"
  location            = "westeurope"
  resource_group_name = "${var.resource_group_name}"
  sku                 = "Standard"
  retention_in_days   = 30

  tags {
    Platform = "${var.platform_tag}"
    Stage    = "${var.stage_tag}"
  }
}

resource "azurerm_kubernetes_cluster" "AKS" {
  name                = "${var.cluster_name}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  dns_prefix          = "${var.dns_prefix}"

  depends_on = ["azurerm_log_analytics_workspace.aks_logging"]

  agent_pool_profile {
    name            = "default"
    count           = "${var.node_count}"
    vm_size         = "Standard_D1_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = "${var.aks_client_id}"
    client_secret = "${var.aks_client_secret}"
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = "/subscriptions/${var.subscription_id}/${azurerm_log_analytics_workspace.aks_logging.workspace_id}"
    }
  }

  tags {
    Platform = "${var.platform_tag}"
    Stage    = "${var.stage_tag}"
  }
}
```

I'm trying to create an AKS with a log analytic workspace, however the oms_agent id returns a 400 error as the workspace has not been created despite the depends on tag

**Comment by lfshr** [comment] 2018-10-30 09:43
I don't feel like this is a kubernetes-cluster issue. The oms resource should block until it's finished.

**Comment by tombuildsstuff** [comment] 2018-10-30 09:55
@lfshr good spot / agreed - thanks!

**Comment by metacpp** [comment] 2018-11-30 07:40
@River991 

You need to change the value setting for `log_analytics_workspace_id` to be:

```hcl
log_analytics_workspace_id = "${azurerm_log_analytics_workspace.aks_logging.id}"
```

More detailed usage for OMS with AKS, please refer to:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/kubernetes/monitoring/main.tf

**Comment by metacpp** [comment] 2018-12-01 03:30
@River991 since this issue is not reproducible, I am going to close it. If you still have question, feel free to re-open it or open a new one.

Thanks!

**Closed by metacpp** 2018-12-01 03:30 UTC
Labels: bug, service/oms
