### ISSUE TITLE
Support for Front Door backends/routing rules as separate resources

### ISSUE THREAD

**Issue by hendstephen** [terraform-providers/terraform-provider-azurerm#10514] opened 2021-02-09 16:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Request to add Azure Front Door endpoints, backends, and routing rules as their own resources outside of `azurerm_frontdoor`. I want to expose different applications through a single front end endpoint (e.g. / and /api to different backends), and I'd like to deploy those from separate terraform configurations. Right now I have to declare all of my backends and routing rules through a single `azurerm_frontdoor` block.

### New or Affected Resource(s)

Affected:
* azurerm_frontdoor

New (proposed):
* azurerm_frontdoor_backend
* azurerm_frontdoor_routingrule

### Potential Terraform Configuration

```hcl
resource "azurerm_frontdoor" "frontdoor" {
  name                                         = "fd-${var.app_name}"
  resource_group_name                          = data.azurerm_resource_group.hub.name
  enforce_backend_pools_certificate_name_check = false

  backend_pool_health_probe {
    name = "backendhealthprobe"
  }

  backend_pool_load_balancing {
    name = "backendloadbalancing"
  }
}

resource "azurerm_frontdoor_endpoint" "fd_endpoint" {
  name                                    = "myfrontend"
  frontdoor_id                            = azurerm_frontdoor.frontdoor.id
  host_name                               = "fd-${var.app_name}.azurefd.net"
  custom_https_provisioning_enabled       = false
  web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.waf.id
}

resource "azurerm_frontdoor_backend" "fd_backend" {
  name         = "mybackend"
  frontdoor_id = azurerm_frontdoor.frontdoor.id
  address     = "${local.web_app_name}.azurewebsites.net"
  host_header = "${local.web_app_name}.azurewebsites.net"
  http_port   = 80
  https_port  = 443
  health_probe_name   = "backendhealthprobe"
  load_balancing_name = "backendloadbalancing"
}

resource "azurerm_frontdoor_routingrule" "fd_routing" {
  name               = "myrule"
  frontdoor_id       = azurerm_frontdoor.frontdoor.id
  accepted_protocols = ["Https", "Http"]
  patterns_to_match  = ["/*"]
  frontend_endpoints = [azurerm_frontdoor_endpoint.fd_endpoint.name]

  forwarding_configuration {
    backend_pool_name   = azurerm_frontdoor_backend.fd_backend.name
    forwarding_protocol = "HttpsOnly"
  }
}
```

**Comment by tombuildsstuff** [comment] 2021-02-09 16:53
hey @hendstephen 

Thanks for opening this issue.

As I understand it at this time the Azure API requires sending at least one Backend Pool and one Routing Rule during the creation of the Front Door - as such it's not strictly possible to split this out at this time, since these'd need to be present on the initial resource and the separate resources (which'd conflict). That said, I think this'd make sense as a feature - but since the API doesn't allow for creating these separately unfortunately this isn't something we can add until the API allows provisioning these without any by default.

@WodansSon would you mind reaching out to the Service Team here to see if that's something that's planned?

Thanks!

**Comment by hendstephen** [comment] 2021-02-09 17:05
@tombuildsstuff Make sense, I figured there might be a limitation with Azure's API. No worries, thanks for the update! I'll keep an eye out for this in the future.

**Comment by timja** [comment] 2021-02-09 17:18
FYI looks the same as https://github.com/terraform-providers/terraform-provider-azurerm/issues/8848

**Comment by tombuildsstuff** [comment] 2021-02-09 17:25
Thanks for the heads up @timja :)

@hendstephen based on that I'm going to close this as a duplicate of #8848, would you mind subscribing to that issue for updates?

**Closed by tombuildsstuff** 2021-02-09 17:25 UTC
Labels: new-resource, service/frontdoor, upstream-microsoft
