### ISSUE TITLE
azurerm_kubernetes_cluster SystemAssigned identity is broken

### ISSUE THREAD

**Issue by robgil-dds** [terraform-providers/terraform-provider-azurerm#5389] opened 2020-01-13 16:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- `azurerm_kubernetes_cluster`
- `azurerm_kubernetes_node_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "k8s" {
  name     = "${var.name}-${var.environment}-k8s-test"
  location = var.region
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.name}-${var.environment}-k8s-test"
  location            = azurerm_resource_group.k8s.location
  resource_group_name = azurerm_resource_group.k8s.name
  dns_prefix          = var.k8s_dns_prefix

  service_principal {
    client_id     =  ***
    client_secret = ***
  }

  default_node_pool {
    name                  = "default"
    vm_size               = "Standard_D1_v2"
    os_disk_size_gb       = 30
    vnet_subnet_id        = module.vpc.subnets
    enable_node_public_ip = true 
    enable_auto_scaling   = true
    max_count             = 2
    min_count             = 1
  }

  identity {
    type = "SystemAssigned"
  }
  lifecycle {
    ignore_changes = [
      default_node_pool.0.node_count
    ]
  }

  tags = {
    environment = var.environment
    owner       = var.owner
  }
}
```

### Expected Behavior

The resource should have configured a SystemAssigned identity, but in the console it is not enabled. See below

When running via the CLI, it still lists UserAssigned.

### Actual Behavior

Identity is still set as UserAssigned.

`az vmss list` - find your vmss group

It will show the following, when it should show SystemAssigned.
```
      "type": "UserAssigned",
```

This has to be manually changed to SystemAssigned in the console for things to work like keyvault flexvol mounts and the principal_id in the keyvault policy needs to be updated with the principal of the vmss. See #5388

### Steps to Reproduce

1. `terraform apply`

### References

* #5388

**Comment by tombuildsstuff** [comment] 2020-03-31 12:28
hi @robgil-dds 

Thanks for opening this issue - apologies for the delayed response here!

The `SystemAssigned` value for the `identity` block of the `azurerm_kubernetes_cluster` resource refers to where the identity comes from for the AKS Service, not for the resources it provisions. In this instance where the AKS Service itself creates the Managed Identity and then assigns it to the Virtual Machine (and other resources which may require it).

As such I believe this is working as intended and so I'm going to close this issue for the moment - however since this is the behaviour of the AKS service, I'd suggest [opening an issue on the AKS repository](XXX) should you wish to dig into this further.

Thanks!

**Closed by tombuildsstuff** 2020-03-31 12:28 UTC
Labels: question, service/kubernetes-cluster
