### ISSUE TITLE
azurerm_machine_learning_workspace only creates basic sku

### ISSUE THREAD

**Issue by PowerSchill** [terraform-providers/terraform-provider-azurerm#6339] opened 2020-04-02 16:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azuread v0.7.0
+ provider.azurerm v2.3.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_machine_learning_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_machine_learning_workspace" "main" {
  name                    = "${var.name-prefix}-MAIN-ML"
  resource_group_name     = azurerm_resource_group.ml.name
  location                = var.location
  application_insights_id = azurerm_application_insights.ml.id
  key_vault_id            = module.ml-keyvault.keyvault_id
  storage_account_id      = azurerm_storage_account.ml.id

  sku_name = "Enterprise"

  identity {
    type = "SystemAssigned"
  }
}
```

### Expected Behavior

The machine learning workspace should be created with an Enterprise edition.

### Actual Behavior

The machine learning workspace is created with the Basic Edition

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When running `terraform apply` a second time it recognizes that it needs to change the edition to Enterprise but does not make the change. Upgrading the workspace manually satisfies the resource. 

### References

* #0000

**Comment by akonrath** [comment] 2020-04-07 03:07
I was able to reproduce this from my end. It looks like the Sku Tier (identical to the Name) should be passed alongside the Name. I was successfully able to get the workspace created as Enterprise after doing so, and was able to update a Basic workspace to Enterprise. I will do a bit more testing and submit a PR.

**Comment by ArcturusZhang** [comment] 2020-04-07 06:34
Hi @PowerSchill I will work on this issue and possibly provide a fix for this.

**Closed** 2020-04-09 19:17 UTC
Labels: enhancement, service/machine-learning
