### ISSUE TITLE
provider.azurerm: no suitable version installed

### ISSUE THREAD

**Issue by jokerbea** [terraform-providers/terraform-provider-azurerm#7042] opened 2020-05-21 13:26 UTC
I have a provider file that looks like this:

#Providers are listed here
terraform {
  required_version = "0.12.24"
}

# Configure the Azure Provider
provider "azurerm" {
  version = "2.9.0"
  features {}
}

provider "random" {
  version = "2.2.1"
}

# Configure the Microsoft Azure Active Directory Provider
provider "azuread" {
  version = "=0.8.0"
}

When I run terraform -v I get the following:
 
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.9.0
+ provider.random v2.2.1

But when I run a terraform plan after a terraform init I get the following: 

cquiring state lock. This may take a few moments...

Error: Could not satisfy plugin requirements

Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

Error: provider.azurerm: no suitable version installed
  version requirements: "2.9.0"
  versions installed: none

Error: provider.random: no suitable version installed
  version requirements: "2.2.1"
  versions installed: none

Error: provider.azuread: no suitable version installed
  version requirements: "=0.8.0"
  versions installed: none

**Comment by lrxtom2** [comment] 2020-05-22 08:17
@jokerbea, Thanks for opening the issue! 
You can please run command `terraform init` firstly in your config folder. Then Terraform will download suitable providers automatically. After that you could run `terraform plan` to see the resource changes. Thanks in advance!

**Comment by tombuildsstuff** [comment] 2020-05-25 16:00
hi @jokerbea 

Thanks for opening this issue.

Based on what I can see in the description above it appears that you're using Terraform Cloud as the backend for Terraform (with a Workspace configured for "Remote" runs) - in which case the `terraform init` being done locally will only be for the backend configuration - rather than for the Providers.

Within Terraform Cloud when a plan/apply is run Terraform then first invokes `terraform init`, which is where I believe this error is being caused - since it appears that a workspace with a "Remote" runner is being used in Terraform Cloud (which is the default)?

If that's correct, I believe the root cause of this is the Terraform Configuration, where the version constraints for the Provider need to be `=value` rather than `value` - for example:

```
terraform {
  required_version = "0.12.24"
}

provider "azurerm" {
  version = "=2.9.0"
  features {}
}

provider "random" {
  version = "=2.2.1"
}

provider "azuread" {
  version = "=0.8.0"
}
```

Would you be able to take a look and see if that works for you? Since it appears that this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-05-25 16:00 UTC
Labels: question, terraform-cloud

**Comment by jokerbea** [comment] 2020-05-25 17:34
Hi
I found the issue
if you look at the screenshot you'll see a plugins_path folder routing to a
windows provider. Which is used on a machine to which internet is not
connected.
It was interfering with terraform commands.

When terraform init was run it installed the provider on the local machine,
but terraform plan followed the plugin path shown on the picture and
returned a message as provider not found.
So I renamed that folder to temporary and the issue was resolved

Le lun. 25 mai 2020 à 12:00, Tom Harvey <notifications@github.com> a écrit :

> hi @jokerbea
> <https://mailtrack.io/trace/link/48606203e3f6fd1c5041480a22d1c78e6d4f20a1?url=https%3A%2F%2Fgithub.com%2Fjokerbea&userId=2464481&signature=02f51ab2621758e3>
>
> Thanks for opening this issue.
>
> Based on what I can see in the description above it appears that you're
> using Terraform Cloud as the backend for Terraform (with a Workspace
> configured for "Remote" runs) - in which case the terraform init being
> done locally will only be for the backend configuration - rather than for
> the Providers.
>
> Within Terraform Cloud when a plan/apply is run Terraform then first
> invokes terraform init, which is where I believe this error is being
> caused - since it appears that a workspace with a "Remote" runner is being
> used in Terraform Cloud (which is the default)?
>
> If that's correct, I believe the root cause of this is the Terraform
> Configuration, where the version constraints for the Provider need to be
> =value rather than value - for example:
>
> terraform {
>   required_version = "0.12.24"
> }
>
> provider "azurerm" {
>   version = "=2.9.0"
>   features {}
> }
>
> provider "random" {
>   version = "=2.2.1"
> }
>
> provider "azuread" {
>   version = "=0.8.0"
> }
>
> Would you be able to take a look and see if that works for you? Since it
> appears that this should be fixed by updating the Terraform Configuration
> I'm going to close this issue for the moment - but please let us know if
> that doesn't work for you and we'll take another look.
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/c7372f73e22884e7d8879e084420ea3f4f5dc471?url=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-azurerm%2Fissues%2F7042%23issuecomment-633634402&userId=2464481&signature=ca8179ace9e2549a>,
> or unsubscribe
> <https://mailtrack.io/trace/link/418b87e5f7f32609ce98ccd62f50d52503161df5?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC6E7W2SUPVWEMFNHYFF26DRTKI2XANCNFSM4NG2ZUJQ&userId=2464481&signature=a446e4281770386b>
> .
>


-- 

*Beatriz Kanzki*
Bsc Bioinformatics
MscA Software Engineering
Specialized in Big Data analytics and cloud technologies
ᐧ
