### ISSUE TITLE
Front Door Created in Disabled State

### ISSUE THREAD

**Issue by Jared-Wolff23** [terraform-providers/terraform-provider-azurerm#11038] opened 2021-03-19 13:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0

### Affected Resource(s)

azurerm_frontdoor

* `azurerm_2.51.0`

### Terraform Configuration Files

```hcl

locals {
  k8s_fd_name                = join("", [var.environment, var.application, var.counter, "fd"])
  k8s_fd_frontend            = join("", [local.k8s_fd_name, "-frontend"])
  k8s_fd_frontend_hostname   = join("", [local.k8s_fd_name, ".azurefd.net"])
  k8s_fd_backend_name        = join("", [local.k8s_fd_name, "-backendpool"])
  k8s_fd_health_probe_name   = join("", [local.k8s_fd_name, "-healthprobe"])
  k8s_fd_routing_rule_name   = join("", [local.k8s_fd_name, "-routingrule"])
  k8s_fd_load_balancing_name = join("", [local.k8s_fd_name, "-loadbalancer"])
}

resource "azurerm_frontdoor_firewall_policy" "k8s_waf_policy" {
  name                = join("", [var.environment, var.application, "wafp"])
  resource_group_name = azurerm_resource_group.k8s_rg_east.name

  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = "1.1"
  }
}

resource "azurerm_frontdoor" "k8s_frontdoor" {
  name                                         = local.k8s_fd_name
  resource_group_name                          = azurerm_resource_group.k8s_rg_east.name
  enforce_backend_pools_certificate_name_check = true
  load_balancer_enabled                        = false
  tags                                         = var.tags

  backend_pool {
    name = local.k8s_fd_backend_name
    backend {
      address     = var.fd_backend_hostname
      host_header = var.fd_backend_hostname
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = local.k8s_fd_load_balancing_name
    health_probe_name   = local.k8s_fd_health_probe_name
  }

  frontend_endpoint {
    name                                    = local.k8s_fd_frontend
    host_name                               = local.k8s_fd_frontend_hostname
    session_affinity_enabled                = false
    web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.k8s_waf_policy.id
  }

  backend_pool_health_probe {
    name = local.k8s_fd_health_probe_name
    protocol            = "Https"
    probe_method        = "HEAD"
    interval_in_seconds = 30
  }

  backend_pool_load_balancing {
    name = local.k8s_fd_load_balancing_name
  }

  routing_rule {
    name               = local.k8s_fd_routing_rule_name
    frontend_endpoints = [local.k8s_fd_frontend]
    accepted_protocols = ["Https"]
    patterns_to_match  = ["/*"]
    forwarding_configuration {
      backend_pool_name   = local.k8s_fd_backend_name
      forwarding_protocol = "HttpsOnly"
    }
  }
}
```

### Expected Behaviour

When Terraform creates an instance of Front Door it should be enabled.

### Actual Behaviour

When Terraform creates an instance of Front Door it's disabled.

### Steps to Reproduce

Create an instance of Front Door.

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-03-19 14:04
@Jared-Wolff23 just to clarify, what exactly do you mean by "Disabled" here, the health checks are failing?

**Comment by Jared-Wolff23** [comment] 2021-03-19 14:38
If you go to the overview tab, the status field is disabled.

**Comment by Jared-Wolff23** [comment] 2021-03-19 14:47
I just figured out that load_balancer_enabled needs to be set to true.  Apparently it controls if the entire Front Door instance is enabled and not just the load balancer portion of the instance.

So, this isn't actually a bug.

**Comment by WodansSon** [comment] 2021-05-06 03:18
Closing due to root cause was a configuration error.

**Closed by WodansSon** 2021-05-06 03:18 UTC
Labels: question, service/frontdoor
