### ISSUE TITLE
Ephemeral disk : os_disk_type for kubernetes_cluster default_node_pool

### ISSUE THREAD

**Issue by samairi10** [terraform-providers/terraform-provider-azurerm#10064] opened 2021-01-06 16:52 UTC
Hi,

**os_disk_type** option was recently added to kubernetes node pool on terraform (december release) but you have probably forgot it for “**default**” node pool.

**nodepool** : 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#os_disk_type

**Default nodepool**:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#default_node_pool 

It’s basically the same template, all options are the same, except disk type.

Also, don't forget to change default value to match with Azure :
**terraform** : Defaults to Managed
**azure** : Defaults to Ephemeral 
 source : _[Ephemeral OS is now Generally Available (GA). From now on ephemeral OS will be the default OS disk type for all SKUs](https://github.com/Azure/AKS/releases/tag/2020-11-16)_

**Comment by tombuildsstuff** [comment] 2021-01-06 16:54
hi @samairi10 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9872 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9872 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-06 16:54 UTC
Labels: duplicate, service/kubernetes-cluster

**Comment by samairi10** [comment] 2021-01-06 16:59
Yes, it’s duplicated because I posted it in the wrong place.
Could you move the #9872<https://clicktime.symantec.com/3BTpQGgraffV64pNgPff5SQ7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-azurerm%2Fissues%2F9872> to azurerm repo ?

Thanks.

De : Tom Harvey <notifications@github.com>
Envoyé : mercredi 6 janvier 2021 17:55
À : terraform-providers/terraform-provider-azurerm <terraform-provider-azurerm@noreply.github.com>
Cc : Amairi, Samir <samairi@dxc.com>; Mention <mention@noreply.github.com>
Objet : Re: [terraform-providers/terraform-provider-azurerm] Ephemeral disk : os_disk_type for kubernetes_cluster default_node_pool (#10064)


hi @samairi10<https://clicktime.symantec.com/3GH79bgoB6UfdBzzthFfNDz7Vc?u=https%3A%2F%2Fgithub.com%2Fsamairi10>

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #9872<https://clicktime.symantec.com/3BTpQGgraffV64pNgPff5SQ7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-azurerm%2Fissues%2F9872> - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9872<https://clicktime.symantec.com/3BTpQGgraffV64pNgPff5SQ7Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-azurerm%2Fissues%2F9872> for updates?

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3X3jWQJE9Q7kYHbgybKC1u37Vc?u=https%3A%2F%2Fgithub.com%2Fterraform-providers%2Fterraform-provider-azurerm%2Fissues%2F10064%23issuecomment-755424347>, or unsubscribe<https://clicktime.symantec.com/3Ce6XPokzw1C3CGELq12VHG7Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASL3LNEUEQHYDCFVZZHRVMLSYSIW5ANCNFSM4VXZHXBQ>.


DXC Technology Company -- This message is transmitted to you by or on behalf of DXC Technology Company or one of its affiliates. It is intended exclusively for the addressee. The substance of this message, along with any attachments, may contain proprietary, confidential or privileged information or information that is otherwise legally exempt from disclosure. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient of this message, you are not authorized to read, print, retain, copy or disseminate any part of this message. If you have received this message in error, please destroy and delete all copies and notify the sender by return e-mail. Regardless of content, this e-mail shall not operate to bind DXC Technology Company or any of its affiliates to any order or other contract unless pursuant to explicit written agreement or government initiative expressly permitting the use of e-mail for such purpose.
