### ISSUE TITLE
[VSTS][Hosted Linux][Azure CLI step]: No valid (unexpired) Azure CLI Auth Tokens found

### ISSUE THREAD

**Issue by KbLev** [terraform-providers/terraform-provider-azurerm#1863] opened 2018-09-04 14:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Debug Output

https://gist.github.com/KbLev/3102b10f3fdb5633bb330a0f07b8fe0c

### Expected Behavior

The Azure CLI logs me into Azure and I expect terraform to have a valid session under the service principal defined in the VSTS UI. (So I don't have to create a separate SPN for terraform and pass it through variables)

### Actual Behavior

The Azure CLI logs into Azure so I'm able to do **az account list**, **az group list**.
Terraform init works.
But when I reach terraform plan I'm thrown out because the session is not logged in. If I run one more **az group list** that works fine.

### Steps to Reproduce

0. Have any sample TF code in your repo. I used [terraform-azurerm-vnet](https://github.com/Azure/terraform-azurerm-vnet)
1. Create a new Build Pipeline in VSTS
2. Select Hosted Linux Preview as the Build Agent Pool
3. Add an Azure CLI step
4. Authorize the Subscription from the dropdown (or select existing SPN)
5. Add the inline script:
```
terraform -v
az account list --format=table
terraform init
az account list --format=table
terraform plan
az account list --format=table
```
- Build & Queue

### References

* #0000

**Comment by tombuildsstuff** [comment] 2018-09-04 15:57
Duplicate of #502 - closing in favour of that issue.

**Closed by tombuildsstuff** 2018-09-04 15:57 UTC

**Comment by KbLev** [comment] 2018-09-04 16:28
Just as an FYI, I did see #502 but opened another issue because here I'm not able to use **terraform plan** at all, not just after 30 minutes.

**Comment by tombuildsstuff** [comment] 2018-09-05 07:34
@KbLev thanks. Given that, presumably the Azure CLI is logged in as a Service Principal which isn't supported by Terraform (we have a separate Service Principal authentication which is supported instead. In general we suggest using a Service Principal in a Shared/CI environment - and the Azure CLI locally. Hope that helps :)

**Comment by tombuildsstuff** [comment] 2018-09-05 10:05
@KbLev 

> Any plans to add support for Azure CLI Service Principal authentication?

Not at this time unfortunately, since we recommend using the Environment Variables instead when using a Service Principal.

> Edit: To rephrase my question, is there a way to authenticate Terraform to Azure, inside a VSTS Pipeline without manually touching an SPN password - perhaps by using a VSTS Service Connection?

There's no VSTS support specifically within Terraform - but it can be configured in much the same way as any other CI system. Specifically within VSTS I believe the Client ID and Client Secret for the Service Principal are exposed as Build Variables which are used to login to the Azure CLI via `az login ...` - so it should be possible to re-expose these as the Environment Variables that Terraform's looking for e.g. via Bash: (`export FOO=$BAR`) or PowerShell depending on the platform being used.

Hope that helps.

**Comment by andreacassioli** [comment] 2018-10-28 12:41
Same problem here. I am using VSTS Azure CLI task that nicely logs in me using SP. As far as I can see the credential of the SP are not exported as env variables by the task and therefore I cannot see any way to inject those values in TF.

What would be an alternative? Could TF use the existing authenticated session?
