### ISSUE TITLE
azurerm_linux_virtual_machine  Error: Network Interface was not found!

### ISSUE THREAD

**Issue by assareh** [terraform-providers/terraform-provider-azurerm#8265] opened 2020-08-26 18:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
AzureRM 2.24.0
Terraform 0.13.0 but seen it in 0.12.x as well

### Affected Resource(s)
* `azurerm_linux_virtual_machine` i believe

### Terraform Configuration Files
https://github.com/assareh/azurerm-issue

### Debug Output
```
Terraform v0.13.0
Configuring remote state backend...
Initializing Terraform configuration...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

tls_private_key.hashidemos: Refreshing state... [id=cf597837a622af1a6f3e06f486df7ad43ebe1418]
azurerm_resource_group.hashidemos: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue]
azurerm_public_ip.publicip: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/publicIPAddresses/azurerm-issue]
azurerm_virtual_network.hashidemos: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/virtualNetworks/azurerm-issue]
azurerm_network_security_group.hashidemos: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/networkSecurityGroups/azurerm-issue]
azurerm_subnet.internal: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/virtualNetworks/azurerm-issue/subnets/azurerm-issue]
azurerm_subnet_network_security_group_association.internal-hashidemos: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/virtualNetworks/azurerm-issue/subnets/azurerm-issue]
azurerm_network_interface.hashidemos: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/networkInterfaces/azurerm-issue]
azurerm_network_interface_security_group_association.example: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/networkInterfaces/azurerm-issue|/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Network/networkSecurityGroups/azurerm-issue]
azurerm_linux_virtual_machine.hashidemos: Refreshing state... [id=/subscriptions/14692f20-9428-451b-8298-102ed4e39c2a/resourceGroups/azurerm-issue/providers/Microsoft.Compute/virtualMachines/azurerm-issue]

Error: Network Interface "azurerm-issue" (Resource Group "azurerm-issue") was not found!
```

### Expected Behavior
I expect Terraform to be declarative and idempotent. If a resource that is in the state file is deleted outside of Terraform, Terraform should recreate it on the next apply.

### Actual Behavior
The plan errors. The only way I've found to correct the issue is remove those objects from the state manually.

### Steps to Reproduce
1. `terraform apply`
2. Delete the resource group in Azure, outside of Terraform
3. `terraform apply` 

### References

**Comment by tombuildsstuff** [comment] 2020-08-27 05:28
hi @assareh 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2491 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2491 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-27 05:28 UTC
