### ISSUE TITLE
vm_size is not treated as case insensitive and also forces a disk size change

### ISSUE THREAD

**Issue by amcguign** [terraform-providers/terraform-provider-azurerm#1257] opened 2018-05-18 12:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.azurerm v1.5.0
```

### Affected Resource(s)

* azurerm_virtual_machine

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Nothing. The vm_size should be case-insensitive. 

### Actual Behavior

```
Terraform will perform the following actions:

  ~ module.ltoo.azurerm_virtual_machine.vm
      vm_size: "Standard_D4_v2" => "Standard_D4_V2"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.ltoo.azurerm_virtual_machine.vm: Modifying... (ID: /subscriptions/e3bdb0c4-6ac6-4bc7-bb96-...Compute/virtualMachines/pca1cc1ltoo001)
  vm_size: "Standard_D4_v2" => "Standard_D4_V2"

Error: Error applying plan:

1 error(s) occurred:

* module.ltoo.azurerm_virtual_machine.vm: 1 error(s) occurred:

* azurerm_virtual_machine.vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="Conflict" Message="Disk resizing is allowed only when creating a VM or when the VM is deallocated." Target="disk.diskSizeGB"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Cloud: Azure Commercial
Region: Canada Central

### References

* #1073

**Comment by tombuildsstuff** [comment] 2018-05-22 17:03
hi @amcguign 

Thanks for opening this issue :)

Looking into the code here - this field is now case sensitive since #1131 has been merged; out of interest are you threading the AzureRM Provider through to the module being used? If not - it's possible an older version of the AzureRM Provider is being used within that module.

Thanks!

**Comment by JunyiYi** [comment] 2018-07-25 21:33
hi @tombuildsstuff , one of our customers also reported this and I'm going to investigate. Here is the information I've got:

- The VMs are created by their customized modules
- The terraform script could not be shared to us due to policy
- Tried to reproduce it with some simple standalone terraform scripts but failed
- I made a dedicated provider, which logs `IgnoreCaseDiffSuppressFunc: ("vm_size", "Standard_DS2_V2", "Standard_DS2_v2")` returns `true`.

**Comment by tombuildsstuff** [comment] 2018-07-30 14:06
@JunyiYi since support for this shipped in v1.4 of the Provider (and you're unable to reproduce this) - an older version of the Provider must be being used. You should be able to see this by running `terraform version` on Terraform 0.11+.

Since this issue has been resolved in v1.4 (and we've not heard back about the original issue) - I'm going to close this issue for the moment.

Thanks!

**Comment by rohrerb** [comment] 2018-07-31 12:08
Hi @tombuildsstuff - Can you please open this back up?  @JunyiYi built a custom provider for us to test with which has added debug info.  We tested and sent results back over which they evaluating.

**Results:**

> Image of the plan showing size change: https://imgur.com/a/TfR0riJ

Custom Provider Debug Output:

```
2018/07/25 14:50:45 [TRACE] vertex 'root.lzoo.module.lzoo.azurerm_virtual_machine.vm[1]': evaluating
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] ignoreCaseDiffSuppressFunc: ("vm_size", "Standard_DS2_V2", "Standard_DS2_v2")
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] IgnoreCaseDiffSuppressFunc: ("vm_size", "Standard_DS2_V2", "Standard_DS2_v2")
2018/07/25 14:50:45 [TRACE] [walkPlan] Entering eval tree: module.lzoo.azurerm_virtual_machine.vm[1]
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] k = 76 6d 5f 73 69 7a 65
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] old = 53 74 61 6e 64 61 72 64 5f 44 53 32 5f 56 32
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] new = 53 74 61 6e 64 61 72 64 5f 44 53 32 5f 76 32
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] strings.ToLower("Standard_DS2_V2" [old]) = "standard_ds2_v2"
2018/07/25 14:50:45 [TRACE] root.lzoo: eval: *terraform.EvalSequence
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] strings.ToLower("Standard_DS2_v2" [new]) = "standard_ds2_v2"
2018/07/25 14:50:45 [TRACE] root.lzoo: eval: *terraform.EvalInterpolate
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] strings.ToLower(old) == strings.ToLower(new)? true
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] ignoreCaseDiffSuppressFunc: ("license_type", "", "")
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] IgnoreCaseDiffSuppressFunc: ("license_type", "", "")
2018/07/25 14:50:45 [TRACE] root.lzoo: eval: *terraform.EvalGetProvider
2018/07/25 14:50:45 [TRACE] root.lzoo: eval: *terraform.EvalValidateResource
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] k = 6c 69 63 65 6e 73 65 5f 74 79 70 65
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] old =
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] new =
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] strings.ToLower("" [old]) = ""
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] strings.ToLower("" [new]) = "
```"
2018-07-25T14:50:45.047-0400 [DEBUG] plugin.terraform-provider-azurerm: 2018/07/25 14:50:45 [INFO] strings.ToLower(old) == strings.ToLower(new)? true

**Comment by paultyng** [comment] 2018-08-03 00:51
The custom provider output also showed the same plan with just the `vm_size` changing? I have tried a number of ways to reproduce this locally and the only way I have been successful is using an older version of the provider.

**Comment by tombuildsstuff** [comment] 2018-08-03 03:48
@rohrerb sure, sorry this got lost in my GH notifications.

**Comment by tombuildsstuff** [comment] 2018-10-22 20:06
@rohrerb since this issue appears to be resolved I'm going to close this issue for the moment.

If you're still seeing this issue - would you be able to output the result of `terraform version` showing which Providers are being used (and provide a Terraform Configuration where you're seeing this with)? Azure returns the state of a Virtual Machine at the last time it's modified, so it's possible this just needs a Tag adding/removing on Azure's side to force this to be updated (in addition to being updated in code). 

Also of note: in the next major version of the AzureRM Provider (2.0) - we're planning on making fields case sensitive where they're currently not (there'll be more details on this in the near future) to better match the behaviour of the other Providers - such that the Terraform Configuration will need to be updated to reflect the casing used on the resource in Azure in either case.

Thanks!

**Closed by tombuildsstuff** 2018-10-22 20:06 UTC
Labels: microsoft/3, question, service/virtual-machine, size/L, waiting-response
