### ISSUE TITLE
azurerm_eventhub_authorization_rule Error: empty non-retryable error received.

### ISSUE THREAD

**Issue by DiceUA** [terraform-providers/terraform-provider-azurerm#12474] opened 2021-07-05 09:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
```
### Affected Resource(s)

* `azurerm_eventhub_authorization_rule`

### Terraform Configuration Files

```hcl

locals {
  hubs = [
      {
        name = "hub01"
        partition_count = 2
        message_retention = 1
      },
      {
        name = "hub02"
        partition_count = 2
        message_retention = 1
      }
    ]
}

data "azurerm_resource_group" "eventhub" {
  name = "myPurrrfecRG"
}

resource "azurerm_eventhub_namespace" "eventhub" {
  name                = "my-eventhub"
  location            = data.azurerm_resource_group.eventhub.location
  resource_group_name = data.azurerm_resource_group.eventhub.name
  sku                 = "Standard"
  capacity            = 1

}

resource "azurerm_eventhub" "eventhub" {
  count = length(local.hubs)
  name                = lower(local.hubs[count.index].name)
  namespace_name      = azurerm_eventhub_namespace.eventhub.name
  resource_group_name = data.azurerm_resource_group.eventhub.name
  partition_count     = lower(local.hubs[count.index].partition_count)
  message_retention   = lower(local.hubs[count.index].message_retention)
}

resource "azurerm_eventhub_consumer_group" "eventhub" {
  count = length(local.hubs)
  name                = "consumer-int"
  namespace_name      = azurerm_eventhub_namespace.eventhub.name
  eventhub_name       = azurerm_eventhub.eventhub[count.index].name
  resource_group_name = data.azurerm_resource_group.eventhub.name
  # user_metadata       = "some-meta-data"
}

resource "azurerm_eventhub_authorization_rule" "eventhubfull" {
  count = length(local.hubs)
  name                = "full_access"
  namespace_name      = azurerm_eventhub_namespace.eventhub.name
  eventhub_name       = azurerm_eventhub.eventhub[count.index].name
  resource_group_name = data.azurerm_resource_group.eventhub.name
  listen              = true
  send                = true
  manage              = true
}
```

### Expected Behaviour

Shared Access Policy Created without error

### Actual Behaviour

Terraform crashes with error:
```
Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
│
│   with module.eventhub.azurerm_eventhub_authorization_rule.eventhubfull[0],
│   on ..\modules\eventhub\main.tf line 39, in resource "azurerm_eventhub_authorization_rule" "eventhubfull":
│   39: resource "azurerm_eventhub_authorization_rule" "eventhubfull" {
│
╵
╷
│ Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
│
│   with module.eventhub.azurerm_eventhub_authorization_rule.eventhubfull[1],
│   on ..\modules\eventhub\main.tf line 39, in resource "azurerm_eventhub_authorization_rule" "eventhubfull":
│   39: resource "azurerm_eventhub_authorization_rule" "eventhubfull" {
│
```
but Shared Access Policy created

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ramondeklein** [comment] 2021-07-05 12:39
It worked fine with v2.64, but it breaks from v2.65 and later.

**Comment by nairraghunathgopinath** [comment] 2021-07-06 10:59
Facing the issue its a highest priority issue. 
PFA.
![image](https://user-images.githubusercontent.com/84505580/124589190-5399e080-de77-11eb-9016-fbc92786556a.png)

**Comment by nairraghunathgopinath** [comment] 2021-07-06 16:35
Downgrading is not at all feasible.

**Comment by mayaz009** [comment] 2021-07-07 10:02
facing the same.
![image](https://user-images.githubusercontent.com/84382218/124740500-4bec4180-df34-11eb-9853-d91d91bb40bc.png)

**Comment by bmovva1991** [comment] 2021-07-12 20:35
any workaround or fix for this issue ? im using azure rm 2.67 and terraform 1.0.2

**Comment by sebader** [comment] 2021-07-13 10:03
duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/12387

**Comment by tombuildsstuff** [comment] 2021-07-19 08:30
Duplicate of #12387, thanks @sebader

**Closed by tombuildsstuff** 2021-07-19 08:30 UTC
Labels: bug, service/event-hubs
