### ISSUE TITLE
Support for event-hub dedicated cluster doesn't return resource ID

### ISSUE THREAD

**Issue by no3am** [terraform-providers/terraform-provider-azurerm#8785] opened 2020-10-07 21:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We've used the `azurerm_eventhub_cluster` resource to provision a dedicated event hub cluster on Azure.
We noticed the issue when we tried to add a namespace to that cluster, to start with, we'd want to retrieve the cluster ID using `data "azurerm_eventhub_cluster" "my_eh"` which doesn't seem to exist i.e. the type `data` for `azurerm_eventhub_cluster` doesn't seem to have been implemented.

### New or Affected Resource(s)

* azurerm_eventhub_namespace

**Comment by tombuildsstuff** [comment] 2020-10-08 08:04
hi @no3am 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8742 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8742 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-08 08:04 UTC
Labels: duplicate, new-data-source, service/event-hubs

**Comment by no3am** [comment] 2020-10-08 10:48
thanks and sorry I didn't notice the open one.
