### ISSUE TITLE
no way to conditionally attached storage disks

### ISSUE THREAD

**Issue by pdeva** [terraform-providers/terraform-provider-azurerm#985] opened 2018-03-16 00:24 UTC
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.2.0

### Affected Resource(s)
virtual_machine

The `storage_data_disk` will go ahead and try to add a disk to the vm even with empty name and 0 size.
this means there is no way to conditionally enable/disable adding a data disk to a vm.

**Comment by tombuildsstuff** [comment] 2018-03-16 01:45
hey @pdeva

Thanks for opening this issue :)

> The storage_data_disk will go ahead and try to add a disk to the vm even with empty name and 0 size.

Terraform will try and create resources and disks for anything present in the configuration; in this instance we're passing the values through to Azure which is what's returning any errors here (or at least, I believe that's what's happening here 😄).

Out of interest are you looking to create a generic module for a VM?

There's [a separate feature request open to add a separate resource to allow attaching disks outside of the VM resource](https://github.com/terraform-providers/terraform-provider-azurerm/issues/795) which may solve this problem, but that needs some research to see if it's feasible given how disks are attached in Azure. Given this appears to be a duplicate of that feature request - I'm going to close this issue in favour of that one for the moment.

Thanks!

**Closed by tombuildsstuff** 2018-03-16 01:45 UTC
Labels: question, service/virtual-machine

**Comment by pdeva** [comment] 2018-03-16 01:48
not looking to create a completely generic module, but some of our vms require attaching data disks and some do not.
due to the number of configuration blocks required, instead of duplicating the vm config (which means duplicating a *lot* of other related config inside it), easier to just conditionally allow adding a data disk.

i do think the feature request you pointed to could be useful in this case
