### ISSUE TITLE
azurerm subnet created in Portal automatically added to state after apply - inconsistent behaviour

### ISSUE THREAD

**Issue by k3rst1n** [terraform-providers/terraform-provider-azurerm#10483] opened 2021-02-05 10:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.5
provider registry.terraform.io/hashicorp/azurerm v2.45.1
```

### Affected Resource(s)

* `azurerm_virtual_network`
* `azurerm_subnet`

### Terraform Configuration Files

main.tf:
```hcl
#create resource group
resource "azurerm_resource_group" "rg" {
    name     = "kr-rg-bust1-test-001"
    location = "westeurope"
}

#Create VNET + Subnet
module "network" {
    source              = "./modules/network"
    rgname              = azurerm_resource_group.rg.name
    vnetname            = "kr-vnet-test-we-001"
    address_space       = ["10.0.0.0/16"]
    subnet_prefixes     = ["10.0.1.0/24"]
    subnet_names        = ["kr-snet-test-we-001"]
}
```
network module:
```hcl
resource "azurerm_virtual_network" "vnet" {
    name                = var.vnetname
    address_space       = var.address_space
    location            = var.location
    resource_group_name = var.rgname

    tags = {
      Owner = lookup(var.tags, "Owner")
    }
}

resource "azurerm_subnet" "subnet" {
    count                = length(var.subnet_names)
    name                 = var.subnet_names[count.index]
    address_prefixes     = [var.subnet_prefixes[count.index]]
    resource_group_name  = var.rgname
    virtual_network_name = azurerm_virtual_network.vnet.name
    service_endpoints    = lookup(var.subnet_service_endpoints, var.subnet_names[count.index], null)
}
```

### Debug Output: generated state file

https://gist.github.com/k3rst1n/502445871dda2da1dd753d9e884a681e

### Expected Behaviour

Not entirely sure what the expected behaviour is but the actual behaviour just feels inconsistent.  I'd have assumed that either 
1) Terraform recognises the subnet that was created in the portal and suggests to destroy it during the next `terraform apply` (if it is considered to be part of the `azurerm_virtual_network` resource), or
2) Terraform ignores it completely and claims the infrastructure is up-to-date but also doesn't add it to the state (if it is considered as independent resource that is not being managed by Terraform).

### Actual Behaviour

After adding a new subnet via the Portal and running `terraform plan` and `terraform apply` Terraform claims the infrastructure is up-to-date and 

1) adds the subnet to the state, and
2) the way it is added to the state seems a bit odd:

The new subnet _kr-snet-test-we-002_ cannot be find as dedicated `azurerm_subnet` resource in the updated state file, however it is added to the in-line subnets of resource `azurerm_virtual_network`.

### Steps to Reproduce

1. `terraform apply` (initial deployment)
2. Add new subnet to deployed VNET via Portal (_kr-snet-test-we-002_)
3. `terraform plan` > Output Infrastructure up-to-date
4. `terraform apply` > Subnet still exists and is now added to state

**Comment by tombuildsstuff** [comment] 2021-02-05 10:45
hi @k3rst1n 

There's two ways of managing Subnets within Terraform, within the `azurerm_virtual_network` resource, or using the separate `azurerm_subnet` resource (as shown above) - the reason for this is there's two different use-cases for this:

* When defining subnets within the `azurerm_virtual_network` resource, this means "only these subnets should exist" - since these are defined centrally
* When defining subnets using the separate `azurerm_subnet` resource - this essentially appends to the existing subnets, but won't remove anything unmanaged, which allows (for example) different modules, teams or processes to be used to manage subnets within these networks

We [document this behaviour](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet) on both the Subnets and Virtual Network pages - as such whilst it's possible to use either/or, it's not possible to use both simultaneously - so which you should pick depends on the setup that you're trying to deploy.

If you'd like Terraform to remove unmanaged/undefined Subnets then you'd need to use the first of those (that is, convert this to using the `azurerm_virtual_network` resource with `subnet` blocks) - else, as you're seeing, Terraform won't manage these resources.

Since this behaviour is working as intended (as both use-cases are valid depending on the configuration/architecture being used - I'm going to close this issue for the moment, but should you have further usage questions I'd point you towards [the community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2021-02-05 10:45 UTC
