### ISSUE TITLE
action_set not available in provider

### ISSUE THREAD

**Issue by piyush94** [terraform-providers/terraform-provider-azurerm#9135] opened 2020-11-03 06:37 UTC
While importing an application gateway the provider skips over action_set for a rewrite_rule. But at the time of plan throws an error that action_set is not defined. After defining it manually as well, it is not working.
**Azure output:**
```
"name": "test-rewrites",
    "provisioningState": "Succeeded",
    "resourceGroup": "rg1",
    "rewriteRules": [
      {
        "actionSet": {
          "requestHeaderConfigurations": [],
          "responseHeaderConfigurations": [],
          "urlConfiguration": {
            "modifiedPath": "/new/path/{var_uri_path_1}",
            "modifiedQueryString": null,
            "reroute": false
          }
        },
        "conditions": [
          {
            "ignoreCase": true,
            "negate": false,
            "pattern": ".*oldpath/(.*)",
            "variable": "var_uri_path"
          }
        ],
        "name": "set_path_variable",
        "ruleSequence": 100
      }
```

**terraform block:**
```
    rewrite_rule_set {
        name = "test-rewrites"

        rewrite_rule {
            name          = "set_path_variable"
            rule_sequence = 100

            condition {
                ignore_case = true
                negate      = false
                pattern     = ".*oldpath/(.*)"
                variable    = "var_uri_path"
            }

            action_set {
                url_configuration {
                    modified_path = "/new/path/{var_uri_path_1}"
                    modified_query_string = null
                    reroute = false
                }
            }
        }
    }
```

**Error:**
```
Error: Unsupported block type

  on test.tf line 211, in resource "azurerm_application_gateway" "appgw-1":
 211:             action_set {

Blocks of type "action_set" are not expected here.
```

Provider version: 2.33.0
Terraform version: 0.13.5

**Comment by dhensby** [comment] 2021-02-16 14:36
duplicate of #7565 ?

**Comment by piyush94** [comment] 2021-02-17 06:51
@dhensby yes, looks like it. But the below code would be a better representation of the terraform script, as I found the schema from the terraform validation source code. Maybe it is already being worked on, at least the schema definition. Also, this is more inline with how the Azure output looks like for Rewrite Rule Sets.
```
rewrite_rule_set {
        name = "test-rewrites"

        rewrite_rule {
            name          = "set_path_variable"
            rule_sequence = 100

            condition {
                ignore_case = true
                negate      = false
                pattern     = ".*oldpath/(.*)"
                variable    = "var_uri_path"
            }

            action_set {
                url_configuration {
                    modified_path = "/new/path/{var_uri_path_1}"
                    modified_query_string = null
                    reroute = false
                }
            }
        }
    }
```

**Comment by tombuildsstuff** [comment] 2021-02-17 08:57
Duplicate of #7565

**Closed by tombuildsstuff** 2021-02-17 08:57 UTC
