### ISSUE TITLE
Feature request - Managed Disk Encryption for Virtual Machine

### ISSUE THREAD

**Issue by imcdnzl** [terraform-providers/terraform-provider-azurerm#486] opened 2017-11-02 17:11 UTC
There seem to be other issues around encrypted disk but are not for managed disks that I can find (please close if you consider otherwise or have missed one!!)

A reference for this is how the az cli does it https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest#az_vm_encryption_enable

To implement this I think the machine with disk would have to be created first and then this applied shortly afterwards as it seems to be something you have to apply after the disk has been created (haven't verified personally yet) :-(

**Comment by shahbhavya85** [comment] 2017-12-11 18:35
Looking for this similar feature.

**Comment by Bastien-Brd** [comment] 2018-05-18 11:17
+1
Quite interested in seeing this feature available in Terraform (Linux VMs and disks in my case)

**Comment by verityit** [comment] 2018-06-01 14:28
+1
Would also like to see ability to encrypt a packer image and use in a scaleset

**Comment by moh-abk** [comment] 2018-06-16 21:19
+1

**Comment by LaurentLesle** [comment] 2018-06-19 21:39
+1

**Comment by tombuildsstuff** [comment] 2018-08-16 13:32
Upstream issue: https://github.com/Azure/azure-sdk-for-go/issues/2322

**Comment by marioanton** [comment] 2018-12-13 10:10
When checking this PR for the azurerm provider 1.20.0 looks to be already available to be used.
- https://github.com/terraform-providers/terraform-provider-azurerm/commit/2cdce25925bc38c1e35a2ba869b3c1f4afc144b2#diff-3182672b1fa6f7dd175449c7e721cb4e 

Wondering whether this is still an issue and what is the intended functionality/behaviour. Encrypt on the fly?

**Comment by whytoe** [comment] 2019-02-21 20:44
@OffColour Did this work for Data and OS Disks because we are experiencing an issue where only the OS disk encrypts using the above extension example.

**Comment by OffColour** [comment] 2019-02-22 09:18
@whytoe Yes, it's working for both, however I have seen that occasionally the portal incorrectly reports that the data disk isn't encrypted. This is also true of using Get-AzureRmVMDiskEncryptionStatus. MS have confirmed this is a bug.

However if you got on to the VM and run manage-bde -status _driveletter:_ it reports that it's encrypted.

**Comment by mathieu-benoit** [comment] 2019-06-25 17:34
@tombuildsstuff, just curious, is it now supported (i.e. managed disk encryption for VM)? If yes, it could great to update that example leveraging an ARM Template?
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/virtual-machines/encrypt-running-linux-vm/main.tf#L71
Thanks!

**Comment by ithahn** [comment] 2019-07-08 09:51
Would be great to have another update as this is important to have while using terraform for machine deployment in Azure.

**Comment by clarkcode** [comment] 2019-08-22 15:48
Why is there encryption support [documented within the managed_disk resource](https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html#enabled) if its not currently possible?

Maybe I'm missing something here but when configuring the encryption settings terraform returns the following error for managed data disks on apply:
```
Error: Error waiting for Virtual Machine "<vm>" (Resource Group "<rsg>") to finish updating Disk "<disk>": 
Code="NotSupported" Message="Disk '<disk-id>' contains encryption settings and cannot be used as a data disk. 
In order to use it as a data disk, remove the encryption settings and ensure that the virtual machine OS disk has the applicable encryption settings defined."
```

**Comment by sunnynazar** [comment] 2019-09-26 11:48
I totally agree with @clarkcode .

Encryption of  managed data disk using "azurerm_managed_disk" encryption settings does n't work, it should be either disabled or if its an issue with Azure SDK  should be explained.

@tombuildsstuff  - do you have anymore insights on this please?

**Comment by justcallmetrell** [comment] 2019-10-01 15:49
Have been attempting to deploy a VM w/ Manged OS and Data disk following the Terraform Documentation, however, persistent issues as others in the thread are mentioning. For me, I receive 

`Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Parameter 'osProfile' is not allowed." Target="osProfile"`

I remove the osProfile block and can have successful deployment, however, its not accessible because the VM doesn't have a computer_name, username, and password. 

Is this issue being worked on and/or documentation being updated actively? Any insight or update would be greatly appreciated.

**Comment by ymash13** [comment] 2019-10-15 20:20
I am seeing the same issue where the OS disk gets encrypted but not the Data disk. After initializing the data disk in windows, the disk automatically got encrypted.

**Comment by stefan-rapp** [comment] 2019-12-07 05:14
I have encrypted my **OS** and **data disk** using the following:

```hcl
resource "azurerm_virtual_machine_extension" "vm_encry_win" {
  count                         = "${var.vm_encry_os_type == "Windows" ? 1 : 0}"
  name                          = "${var.vm_encry_name}"
  location                      = "${var.vm_encry_location}"
  resource_group_name           = "${var.vm_encry_rg_name}"
  virtual_machine_name          = "${var.vm_encry_vm_name}"
  publisher                     = "${var.vm_encry_publisher}"
  type                          = "${var.vm_encry_type}"
  type_handler_version          = "${var.vm_encry_type_handler_version == "" ? "2.2" : var.vm_encry_type_handler_version}"
  auto_upgrade_minor_version    = "${var.vm_encry_auto_upgrade_minor_version}"
  tags                          = "${var.vm_encry_tags}"

  settings = <<SETTINGS
                {
                    "EncryptionOperation":      "${var.vm_encry_operation}",
                    "KeyVaultURL":              "${var.vm_encry_kv_vault_uri}",
                    "KeyVaultResourceId":       "${var.vm_encry_kv_vault_id}",
                    "KeyEncryptionKeyURL":      "${var.vm_encry_kv_key_url}",
                    "KekVaultResourceId":       "${var.vm_encry_kv_vault_id}",
                    "KeyEncryptionAlgorithm":   "${var.vm_encry_key_algorithm}",
                    "VolumeType":               "${var.vm_encry_volume_type}"
                }
             SETTINGS
}
```

And it worked so far. Both disks are encrypted now. Unfortunately, I have the problem, when I re-run `terraform plan` or `terraform apply`, because the `azurerm_managed_disk `wants to **replace** my data disk now as the follwoing screenshot illustrates.

```hcl
resource "azurerm_managed_disk" "md" {
    count                   = "${var.md_count}"
    name                    = "${var.md_name}-disk${count.index}"
    location                = "${var.md_location}"
    resource_group_name     = "${var.md_rg_name}"
    storage_account_type    = "${var.md_storage_account_type}"
    create_option           = "${var.md_create_option}"
    source_uri              = "${var.md_create_option == "Import" ? var.md_source_uri : null}"
    source_resource_id      = "${var.md_create_option == "Copy" || var.md_create_option == "Restore" ? var.md_source_resource_id : null}"
    image_reference_id      = "${var.md_create_option == "FromImage" ? var.md_image_reference_id : null}"
    os_type                 = "${var.md_create_option == "Copy" || var.md_create_option == "Import" ? var.md_os_type : null}"
    disk_size_gb            = "${var.md_disk_size_gb != "" ? var.md_disk_size_gb : null}"
    tags                    = "${merge(local.default_tags, var.md_tags)}"
}
```

![2019-12-06 19_48_58-Window](https://user-images.githubusercontent.com/45358082/70369368-5f4aad00-18b8-11ea-8088-1341387254d7.png)


Seems like the `encryption_settings `on `azurerm_managed_disk `is not working correctly.
Does anyone can help me with this issue? Is there a work around?

**Comment by jeff1985** [comment] 2019-12-07 15:32
Hi @stefan-rapp ,

if disk creation works fine, you probably could just tell terraform to ignore the encryption_settings:
```
  lifecycle {
    ignore_changes = [ encryption_settings ]
  }
```

Do you want to give it a try?

**Comment by stefan-rapp** [comment] 2019-12-10 17:47
Hi @jeff1985 ,
I tried that already:

```hcl
lifecycle {
        ignore_changes = [  encryption_settings[0].enabled,
                            encryption_settings[0].key_encryption_key[0].key_url,
                            encryption_settings[0].key_encryption_key[0].source_vault_id,
                            encryption_settings[0].disk_encryption_key[0].secret_url,
                            encryption_settings[0].disk_encryption_key[0].source_vault_id]
    } 
```

But the thing is, that for initial creation of managed disks, I always need encryption settings now.
 
Normally, we need a fix, that if `Microsoft.Azure.Security` with `AzureDiskEncryption `is used as VM Extension to encrypt disks, the parameters of `encryption_settings` should NOT do a replacement of `azurerm_managed_disk`.

**Comment by stefan-rapp** [comment] 2019-12-11 06:26
@jeff1985 , 
sorry for the inconvinience, I tried out your option and it worked.

```hcl
lifecycle {
        ignore_changes = [encryption_settings]
    }
```

Thx for your quick help. Appreciate it!

**Comment by tombuildsstuff** [comment] 2020-01-30 16:58
👋 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We recently opened #5550 which adds support for the new Virtual Machine resources - and I'm able to confirm that encrypting the OS Disk is supported in the new Virtual Machine resources - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine` resource.

In the new resources you can encrypt the OS Disk using a Disk Encryption Set like so:

```hcl
resource "azurerm_resource_group" "example" {}
resource "azurerm_network_interface" "example" {}
resource "azurerm_key_vault" "example" {}
resource "azurerm_key_vault_key" "example" {}

resource "azurerm_disk_encryption_set" "example" {
  name                = "example-set"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  key_vault_key_id    = azurerm_key_vault_key.example.id
  
  identity {
    type = "SystemAssigned"
  }
}
resource "azurerm_key_vault_access_policy" "disk-encryption" {
  key_vault_id = azurerm_key_vault.example.id
  tenant_id = azurerm_disk_encryption_set.example.identity.0.tenant_id
  object_id = azurerm_disk_encryption_set.example.identity.0.principal_id
  key_permissions = [
    "get",
    "wrapkey",
    "unwrapkey",
  ]
}

resource "azurerm_role_assignment" "disk-encryption-read-keyvault" {
  scope                = azurerm_key_vault.test.id
  role_definition_name = "Reader"
  principal_id         = azurerm_disk_encryption_set.example.identity.0.principal_id
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-vm"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]
  
  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }
  os_disk {
    caching                = "ReadWrite"
    disk_encryption_set_id = azurerm_disk_encryption_set.example.id
    storage_account_type   = "Standard_LRS"
  }
  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
  depends_on = [
    "azurerm_role_assignment.disk-encryption-read-keyvault",
    "azurerm_key_vault_access_policy.disk-encryption",
  ]
}
```

Note: Soft Delete is not natively supported on the `azurerm_key_vault` resource prior to 2.0 - as such this needs to be configured out-of-band - however this will be supported in version 2.0 of the Azure Provider.

In order to get feedback on these new resources we'll be launching support for these new resources as an opt-in Beta in an upcoming 1.x release of the Azure Provider and ultimately release these as "GA" in the upcoming 2.0 release. We'll post an update in #2807 when both the opt-in Beta (1.x) & GA (2.0) are available - as such I'd recommend subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!

**Closed** 2020-02-03 17:37 UTC
Labels: enhancement, hashibot/ignore, microsoft/3, service/virtual-machine, upstream-microsoft

**Comment by Dmitry1987** [comment] 2020-03-23 06:23
I just tried the above snippet using my resource group (used the 'data' to import the vault/subnet/key required), it works but the disk shows as 'not encrypted' in Azure UI. How do I know if it actually worked? 😅 
It's Ubuntu, and I tried the `cryptsetup status xxxxx` but no results, the disks don't seem encrypted at the linux level (I know they are by default encrypted at rest, in Azure under the hood).
Terraform run was successful, and the "disk encryption set" exists, and it also has that OS disk. But the VM tab says encryption not enabled, is there a way to check what's the real status of encryption?

**Comment by dsedivec** [comment] 2020-06-12 06:48
For the benefit of anyone who stumbles upon this in the future, I'd like to note that this issue's title refers to "managed disk encryption", which I *think* refers to Azure Server-Side Encryption<sup>1</sup> (SSE).  tombuildsstuff's example [a couple comments up from this one](https://github.com/terraform-providers/terraform-provider-azurerm/issues/486#issuecomment-580351484) is indeed, as far as I know, setting up SSE.

However, a [couple](https://github.com/terraform-providers/terraform-provider-azurerm/issues/486#issuecomment-454797960) of the [comments](https://github.com/terraform-providers/terraform-provider-azurerm/issues/486#issuecomment-562815515) in this issue are setting up Azure Disk Encryption (ADE), which uses a VM extension and sets up BitLocker (Windows) or dm-crypt (Linux) via the OS.

SSE and ADE are not the same thing at all.

The [upstream issue](https://github.com/Azure/azure-sdk-for-go/issues/2322) [tombuildsstuff referred to](https://github.com/terraform-providers/terraform-provider-azurerm/issues/486#issuecomment-413546500) early on also seems to be about ADE, not SSE.

As of this writing, [the `encrypt-running-linux-vm` example](https://github.com/terraform-providers/terraform-provider-azurerm/tree/437e0e006da24a65fd85d1f5e9e4ad7cf926d513/examples/virtual-machines/virtual_machine/encrypt-running-linux-vm) also seems to be referring to ADE.

I propose we blame Microsoft for this confusion.

Finally, I *suspect* pre-2.0 versions of the azurerm provider were able to configure ADE, but not SSE.  I've only just started using Terraform, so I'm starting with the 2.x provider, but from what I've read in this issue and elsewhere, I gather 2.0 added management of SSE.  Something like that.

<sup>1</sup> In Microsoft docs, SSE sometimes has different expansions.  I think I've seen "Server-Side Encryption" (with and without hyphen), "Server-side Storage Encryption", and "Storage Service Encryption".

**Comment by AlphaWong** [comment] 2020-06-16 11:24
> ```terraform
> resource "azurerm_disk_encryption_set" "example" {
>   name                = "example-set"
>   resource_group_name = azurerm_resource_group.example.name
>   location            = azurerm_resource_group.example.location
>   key_vault_key_id    = azurerm_key_vault_key.example.id
>   
>   identity {
>     type = "SystemAssigned"
>   }
> }
> ```

good to see `os_disk` is supported now. But how about the `managed_disk`?
