### ISSUE TITLE
azurerm_virtual_machine_extension does not follow the lifecycle of the VM it is associated with.

### ISSUE THREAD

**Issue by KimShepherdVibrato** [terraform-providers/terraform-provider-azurerm#4268] opened 2019-09-05 22:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.12.8
azurerm 1.33.1

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "test" {
  name                  = local.vm_name
  location              = azurerm_resource_group.test.location
  resource_group_name   = azurerm_resource_group.test.name
  network_interface_ids = [azurerm_network_interface.test.id]
[...]
}

resource "azurerm_virtual_machine_extension" "test" {
  name                             = "TestConfigScript"
  location                         = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  virtual_machine_name = azurerm_virtual_machine.test.name
  publisher                       = "Microsoft.Azure.Extensions"
  type                                = "CustomScript"
  type_handler_version    = "2.0"

  settings = jsonencode(
    {
      commandToExecute = "touch ~/foo"
    }
  )
}



```
### Expected Behavior

When the VM needs to be replaced I would expect the provider to:

1. Destroy the vm extension
2. Destroy the vm
3. Create the VM
4. Create the VM extension

### Actual Behavior

Only the VM is explicitly destroyed.  Since the VM extension is attached to the vm, it is never recreated and will not run on the VM.  The vm extension has to be manually tainted whenever a VM needs to be replaced.

### Steps to Reproduce

```
terraform init
terraform apply -auto-approve
terraform taint azurerm_virtual_machine.test
terraform apply -auto-approve
```

### Workaround

This behaviour seems to occur because the only link in the DAG is to the `name` property of the virtual machine.  Since this is usually static and not computed, terraform doesn't 'know' that the resource needs to be replaced on the same lifecycle as the virtual machine.  Forcing this connection by manually parsing the vm name from its id gives me the behaviour I would expect.

```
virtual_machine_name = split("virtualMachines/", azurerm_virtual_machine.test.id)[1]
```

I would suggest the `virtual_machine_name` property be deprecated and replaced with virtual_machine_id and have the provider parse the vm name to pass to api.

I would be happy to provide a pull request if this is an appropriate solution.

### References

https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html

**Comment by KimShepherdVibrato** [comment] 2019-09-06 00:23
Here is a first pass at the changes I have in mind:

https://github.com/KimShepherdVibrato/terraform-provider-azurerm/compare/master...KimShepherdVibrato:4268_vm_extension_lifecycle?expand=1

I based it heavily off what was done with azurerm_key_vault_access_policy.  I am not sure if deprecation of the current properties is too heavy handed, or if there is a simpler solution that I am not seeing.

**Comment by tombuildsstuff** [comment] 2019-09-06 06:11
hey @KimShepherdVibrato 

Thanks for opening this issue.

The root cause of this is a bug in Terraform Core which is being tracked [in this issue](https://github.com/hashicorp/terraform/issues/8099) - however as you've noted we should be able to work around this by switching the Virtual Machine Extension resource to use the Virtual Machine's ID rather than the Name, which is something we've been planning to do as a part of the changes [coming in 2.0](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807) - so this is great timing :)

Taking a look at the commit you've linked to this looks like the right approach to me - there's a few minor tweaks to make (for example, if we're deprecating the `name` in favour of the `id` then we should pick that value first, [add these fields to the upgrade guide](https://github.com/terraform-providers/terraform-provider-azurerm) and look up the Virtual Machine ID rather than building it manually) but it's otherwise looking great 👍

Thanks!

**Comment by tombuildsstuff** [comment] 2019-09-16 08:15
👋 

Taking a look through since this is duplicate of #2456 I'm going to close this issue in favour of that one - would you mind subscribing to #2456 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-16 08:15 UTC
Labels: bug, service/virtual-machine-extensions
