### ISSUE TITLE
changes to azurerm_subnet are reflected to azurerm_virtual_network attributes only on the second "apply"

### ISSUE THREAD

**Issue by delampri** [terraform-providers/terraform-provider-azurerm#8486] opened 2020-09-16 10:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
 C:\TerraForm\terraform.exe -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.27.0
```

### Affected Resource(s)

* azurerm_subnet
* azurerm_virtual_network

### Terraform Configuration Files

```
provider "azurerm" {
	features {}

}

variable "resourcegroup_name" {
	default = "test_rg"
}

variable "region" {
	default ="eastus"
}

variable "environment_name" {
	default = "vnetsimulation"
}

variable "vnet_cidr" {
	default = "192.168.0.0/16"
}


resource "azurerm_resource_group" "network_rg" {
  name     = var.resourcegroup_name
  location = var.region
}

resource "azurerm_virtual_network" "mgmt_vnet" {
  name                = format("%s_vnet",var.environment_name)
  location            = azurerm_resource_group.network_rg.location
  resource_group_name = azurerm_resource_group.network_rg.name
  address_space       = [ var.vnet_cidr ]
}

resource "azurerm_subnet" "firewall" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.network_rg.name
  virtual_network_name = azurerm_virtual_network.mgmt_vnet.name
  address_prefixes     = [ cidrsubnet(var.vnet_cidr,8, 0) ]
}

output "subnets" {
	value = {
		# convert list to hash, based on subnet name
		for subnet in azurerm_virtual_network.mgmt_vnet.subnet :
			subnet.name => subnet
	}
}
```

### Expected Behavior

at the end of the initial run, after creating the vnet and subnet, the output should be as follows:

```
Changes to Outputs:
  ~ subnets = {
      + AzureFirewallSubnet = {
          + address_prefix = "192.168.0.0/24"
          + id             = "/subscriptions/aaaaaaaaaa-833d-4bb3-92e3-d8cdf7a98171/resourceGroups/test_rg/providers/Microsoft.Network/virtualNetworks/vnetsimulation_vnet/subnets/AzureFirewallSubnet"
          + name           = "AzureFirewallSubnet"
          + security_group = ""
        }
    }
```

### Actual Behavior

```
Outputs:

subnets = {}
```

### Steps to Reproduce

1. `terraform apply`
2. see the output is empty
3. run terraform apply again without any change
4. the correct output is displayed

### Important Factoids

nop.

### References

* #0000

**Comment by magodo** [comment] 2020-09-17 05:57
@delampri Thank you for submitting this issue with a comprehensive reproduciable steps :+1:

The reason why you can't get the subnet info in the first apply is that at the time `azurerm_virtual_network` is provisioned, the `azurerm_subnet` has not started to provision yet. So the state recorded for `azurerm_virtual_network` is the one without any subnet defined. Later when constructing output `subnets`, Terraform will inquire the state of `azurerm_virtual_network` and see no subnet, hence output empty map.

In the second apply, Terraform will refresh the state beforehead, at which point it will see that `azurerm_virtual_network` has subnet defined in the remote (because the `azurerm_subnet` is provisioned in last apply). So the output will reflect that fact.

A imperfect workaround is to "guide" Terraform to do a "read" after provisioning `azurerm_subnet` in the first apply. So we can introduce a data source `azurerm_virtual_network` depending on `azurerm_subnet` accordingly:

```hcl
data "azurerm_virtual_network" "mgmt_vnet" {
  name                = azurerm_virtual_network.mgmt_vnet.name
  resource_group_name = azurerm_virtual_network.mgmt_vnet.resource_group_name
  depends_on = [azurerm_subnet.firewall]
}

output "subnets" {
  value = [for subnet in data.azurerm_virtual_network.mgmt_vnet.subnets: subnet ]
}
```

As currently the property [`subnets`](https://www.terraform.io/docs/providers/azurerm/d/virtual_network.html#subnets) of data source `azurerm_virtual_network` is a list of subnet name, rather than a list of subnet block, we need to modify the output a bit to turn it into a list, rather than a map.

This might is not what you expected, I guess we need to extend the data source to export a subnet block list, but that would be a breaking change.

Another workaround is just run apply twice.

**Comment by delampri** [comment] 2020-09-17 08:21
Thank you for your reply.
This is the simplest example I found, in reality I have multiple subnets
and I have the same issue even if the vnet is already exists and I add a
few subnets to the module.
The output purpose was to conduct a map in which the subnet name is the key
and rest of the data (mainly the ip cidr and subnet id) are values.
 Is there any way to achieve it without running twice? Is there a way to
force the resource to refresh within the same run before running the output?

**Comment by magodo** [comment] 2020-09-18 01:40
From what I know, there is no such way to achieve this for now. The only way I can come up with is to extend the `azurerm_virtual_network` data source. Maybe @tombuildsstuff can provide some insights on this?

**Comment by tombuildsstuff** [comment] 2020-10-26 11:07
@delampri you should be able to workaround this by using [the `azurerm_subnet` Data Source](https://www.terraform.io/docs/providers/azurerm/index.html) to obtain this information for each subnet - with a `depends_on` to ensure this is looked up after the (extended) subnets are created.

Since this is a question regarding Terraform Configuration rather than a feature enhancement/bug in the Azure Provider - I'm going to close this issue for the moment - however if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-10-26 11:07 UTC
Labels: question, service/virtual-networks
