### ISSUE TITLE
Including site_config { } in App Service results in HTTP/1.1 429 Too Many Requests

### ISSUE THREAD

**Issue by ystrte** [terraform-providers/terraform-provider-azurerm#1144] opened 2018-04-20 07:38 UTC
Hi,

Trying to deploy azurerm_app_service, but it results in: 

2018-04-20T09:20:46.105+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.3.3_x4.exe: HTTP/1.1 429 Too Many Requests.

As a result the service is not deployed.

### Terraform Version
0.11.7  41e50bd32a8825a84535e353c3674af8ce799161

### Affected Resource(s)
- azurerm_app_service

### Terraform Configuration Files
```hcl

webapp1.tf

resource "azurerm_resource_group" "webapp_resource_group" {
  name     = "${var.app_service_rg_name}"
  location = "${var.location}"
}

resource "azurerm_app_service" "webapp" {
  name                = "${var.app_service_name}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.webapp_resource_group.name}"
  app_service_plan_id = "${data.terraform_remote_state.service_plan_state.app_service_plan_id}"

  site_config {
    dotnet_framework_version = "v4.0"
    default_documents        = ["index.html"]
  }
}

variables.tf

variable "location" {
  default = "westeurope"
}
variable "app_service_rg_name" {
  description = "Name of the Resource Group for the App Service"
  default     = "customer-project-stg-testApp1-rg"
}

variable app_service_name {
  description = "Name of the App Service"
  default     = "customer-project-stg-testApp1-wapp87"
}

state.tf

terraform {
  backend "azurerm" {
    storage_account_name = "xyz"
    container_name       = "abc"
    key                  = "a/b/apps/test.terraform.tfstate"
  }
}

data "terraform_remote_state" "service_plan_state" {
  backend = "azurerm"

  config {
    storage_account_name = "ystrtetf"
    container_name       = "terraform"
    key                  = "a/b/serviceplan/test.terraform.tfstate"
  }
}

azureprovider.tf

provider "azurerm" {}
```

### Debug Output
https://gist.github.com/ystrte/22a5c048d463d9f3ea562266d6ce930e
[](https://gist.github.com/ystrte/22a5c048d463d9f3ea562266d6ce930e)

### Expected Behavior
The App Service should be created

### Actual Behavior
```hcl
plugin.terraform-provider-azurerm_v1.3.3_x4.exe: HTTP/1.1 429 Too Many Requests
```
and
```hcl
Error: Error applying plan:

1 error(s) occurred:

* azurerm_app_service.webapp: 1 error(s) occurred:

* azurerm_app_service.webapp: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: failed request: autorest/azure: Service returned an error. Status=<nil> <nil>
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids
No issues before yesterday. 

### References
No known issues.

**Comment by ystrte** [comment] 2018-04-23 10:43
Update: 
Timeout only happens when **site_config { }** is included, regardless of parameters and values.

**Comment by ben-lings-tessella** [comment] 2018-10-12 10:50
Possibly related to #1560?

**Comment by tombuildsstuff** [comment] 2018-11-07 12:12
@ben-lings-tessella thanks for identifying that - I'd agree this is a duplicate of #1560. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1560 - please subscribe to that issue for updates.

Thanks!

**Closed by tombuildsstuff** 2018-11-07 12:12 UTC
Labels: bug, service/app-service
