### ISSUE TITLE
Azure KeyVault infrastructure fails.

### ISSUE THREAD

**Issue by wb529kq** [terraform-providers/terraform-provider-azurerm#10450] opened 2021-02-03 15:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# #########################################################
#  Managed Service Identity for the key-vault
# #########################################################
resource "azurerm_user_assigned_identity" "agw_user_assigned_identity" {
  
  resource_group_name = local.resource_group_name  
  // location            = data.azurerm_resource_group.resource_group.location
  location = var.location

  name                = lower("${local.agw_user_prefix}-${var.application_name}-${var.subscription_name}-${var.environment}-${var.ver}")

  tags                  = var.standard_tags
}

	resource "azurerm_key_vault_access_policy" "agw_access_policy" {
	  key_vault_id = data.azurerm_key_vault.keyvault.id
	  tenant_id    = data.azurerm_client_config.current.tenant_id
	  object_id    = azurerm_user_assigned_identity.agw_user_assigned_identity.principal_id
	
	  secret_permissions = [
	    "get"
	  ]
	}



resource "random_id" "randomid_gen" {
    keepers = {
        # Generate a new ID only when a new resource group is defined
    }

    byte_length = 8
}

```

### Panic Output

When applying changes to
module.edm_application_gateway.azurerm_key_vault_certificate.key_vault_certificate,
provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-02-03 16:56
hi @wb529kq 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #10371 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10371 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-03 16:56 UTC
Labels: bug, duplicate, regression, service/keyvault
