### ISSUE TITLE
Api Management apis failing to create reliably

### ISSUE THREAD

**Issue by prabhakarreddy1234** [terraform-providers/terraform-provider-azurerm#8473] opened 2020-09-15 13:58 UTC
We are facing the same issue as posted in https://github.com/terraform-providers/terraform-provider-azurerm/issues/7195 .  It was working with `azurerm :  2.15.0` for sometime but doesn't seem to work in versions released afterwards. 

As a work around we have to run the `terraform apply`  more than 3 times continuously to get all the apis and operations added/updated in API Management.

**Comment by yupwei68** [comment] 2020-09-16 06:26
Hi @prabhakarreddy1234 Thanks for opening this issue. We've not changed the code afterwards. Does you mean that you have `terraform apply` with success, but the api was not created, right? Please provide your terraform configuration and your azurerm version to help to reproduce this issue.

**Comment by tombuildsstuff** [comment] 2020-09-16 10:04
Closing since there's not enough information for us to be able to determine a root cause here, would you mind [opening a new issue completing all of the information in the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Bug_Report.md) which contains all of the information we need to look into this?

Thanks!

**Closed by tombuildsstuff** 2020-09-16 10:04 UTC
