### ISSUE TITLE
skip_provider_registration / ARM_SKIP_PROVIDER_REGISTRATION - has no effect

### ISSUE THREAD

**Issue by jbinko** [terraform-providers/terraform-provider-azurerm#7134] opened 2020-05-29 17:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.12.24
provider.azurerm v2.12.0

### Affected Resource(s)

* `provider "azurerm"`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

provider "azurerm" {
  skip_provider_registration = true
}

```

### Debug Output

2020-05-29T19:13:11.391+0200 [DEBUG] plugin: waiting for RPC address: path=C:\Terraform\Test\.terraform\plugins\windows_amd64\terraform-provider-azurerm_v2.12.0_x5.exe
2020-05-29T19:13:11.494+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "Advisor"..
2020-05-29T19:13:11.494+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Resources for "Advisor"..
2020-05-29T19:13:11.494+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "Analysis Services"..
2020-05-29T19:13:11.494+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Resources for "Analysis Services"..
2020-05-29T19:13:11.494+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "API Management"..
2020-05-29T19:13:11.495+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Resources for "API Management"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "App Configuration"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Resources for "App Configuration"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "App Platform"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Resources for "App Platform"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "Application Insights"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Resources for "Application Insights"..
2020-05-29T19:13:11.504+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.12.0_x5.exe: [DEBUG] Registering Data Sources for "Authorization"..

### Expected Behavior

I Expect TF will not register providers when 
skip_provider_registration = true
Customer is running this with people not having enough permissions on subscription level and it is always failing.

### Actual Behavior

No matter what is set in 
skip_provider_registration
the TF is always trying to register providers

### Steps to Reproduce

1. az login - this is used for TF authentication - no service principle
2. `terraform apply` with just nearly empty main.tf file with 

provider "azurerm" {
  skip_provider_registration = true
}

### References

* #0000

**Comment by njuCZ** [comment] 2020-06-02 05:32
@jbinko the log here may be a little confusing. It means azurerm provider could support those kinds of Resource Providers. And if you set `skip_provider_registration=true`,  TF will not try to resgiter those providers in your subscription. So there is no problems with the logs you pasted. In your case,  if it's always failing, could you please paste the detail error message directly so we could find the root cause quickly?

**Comment by tombuildsstuff** [comment] 2020-08-14 16:47
@jbinko these are internal log messages used when registering the Resources and Data Sources internally within the Provider - whilst I appreciate the terminology used here is reused, this is not registering the resource providers - so this working as intended and as such I'm going to close this issue for the moment. If you're seeing an issue where disabling the resource provider registration doesn't work (and results in an error) then please let us know and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-08-14 16:47 UTC
Labels: provider, waiting-response
