### ISSUE TITLE
terraform execution in westeurope is slow

### ISSUE THREAD

**Issue by ahelal** [terraform-providers/terraform-provider-azurerm#5067] opened 2019-12-04 17:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform 0.12.12
* Azure provider 1.36.1 also with 1.34.0 

### Affected Resource(s)

All 
### Terraform Configuration Files

https://gist.github.com/ahelal/e0fdaa02cb9ad7da9bfcde97e03acdd1

### Expected Behavior

I run the code on two regions `westus2` and `westeurope` from VM on azure  I expect execution time to be smiler.

### Actual Behavior

`westeurope`  is way slower with a factor of 2 - 3 

|   |   | 1 | 2 | 3 | 4 | 5|
|---|---|---|---|---|---|---|
|Creation| westus2 | 06:09 | 06:18 |05:55 |06:15 |05:53 |
|Destruction| westus2 | 04:12 | 04:35 | 04:45 | 05:01 |04:30 |
|Creation | westeurope | 19:04 | 20:31 | 18:47 | 19:31 | 17:39 |
|Destruction | westeurope | 22:02 | 22:21 | 22:02 |21:22 |21:11 |

I have a jobs running in a CI in both location  `westeurope` is always slower. I also run it from my laptop with smiler results.
 
### Steps to Reproduce

* `time terraform apply --var location=westeurope`  and `time terraform apply --var location=westus2`
* or run the test script `./run-test.sh`

### References

* #1

**Comment by hund030** [comment] 2019-12-09 09:21
Hi, @ahelal. I reproduced the issue and I found terraform get slower to deploy for the region where terraform is called at. I run your code on both regions `westus2` and `westeurope` from VM at `westus2` on azure and get an opposite result:

  |   | 1 | 2 | 3
-- | -- | -- | -- | --
Creation | westus2 | 18:32 | 18:04 | 17:27
Destruction | westus2 | 21:54 | 21:05 | 22:25
Creation | westeurope | 5:50 | 6:07 | 6:01
Destruction | westeurope | 3:56 | 3:56 | 4:25

I also try it from my local machine(East China), there isn't any significant performance difference between these two regions.


Besides, I did some tracing works and found when TF deploys to the same region(`westus2` to `westus2` in my case), for most resource it waits about 10 seconds for the service to complete the async creation\destruction. Below pics show processes to create a network security rules on `westus2` and `westeurope`. Because of the mysterious 10 seconds, deploy to `westus2` takes more time even with a lower network latency.

![image](https://user-images.githubusercontent.com/26134943/70421597-0be98200-1aa5-11ea-8d8f-679baa8303b9.png)
![image](https://user-images.githubusercontent.com/26134943/70421845-a0ec7b00-1aa5-11ea-8916-fc1ef7ef3e90.png)

TF forces the security rules be created one by one and the same issue also happens to other resources, so totally the script takes much more time then in other region.

**Comment by katbyte** [comment] 2019-12-09 17:28
Hi @ahelal,

I'm sorry that you are having these issues with azure provisioning times. However from a provider perspective we are calling the same API endpoints with only the `location` property changed so any differences in location provisioning times are on the Azure side, possibly due to differences in demand or useage in that location. As there is not much we can do in the provider i am going to close this and suggest you reach out to Azure Support as they potentially will have more insight into what is going on here.

**Closed by katbyte** 2019-12-09 17:28 UTC
