### ISSUE TITLE
azurerm_app_service_environment_v3 provisioning issue 

### ISSUE THREAD

**Issue by artiomjakubovic** [terraform-providers/terraform-provider-azurerm#12625] opened 2021-07-16 12:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_app_service_environment_v3`

### Terraform Configuration Files

```hcl

terraform {
  required_providers {
    azurerm = {
      version = ">=2.67.0"
    }
    random = {
      version = "3.1.0"
    }
  }

}



provider "azurerm" {
  features {}
}




resource "azurerm_resource_group" "rg1" {
  name     = "web-app-resource-g"
  location = "West Europe"
}

resource "azurerm_virtual_network" "vnet1" {
  name                = "test-vnet1"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg1.location
  resource_group_name = azurerm_resource_group.rg1.name
}
  resource "azurerm_subnet" "ase" {
    name                 = "asesubnet"
    resource_group_name  = azurerm_resource_group.rg1.name
    virtual_network_name = azurerm_virtual_network.vnet1.name
    address_prefixes     = ["10.0.3.0/24"]

    delegation {
      name = "ASE-Delegation"

      service_delegation {
        name    = "Microsoft.Web/hostingEnvironments"
        actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
      }
    }
    service_endpoints = ["Microsoft.Sql", "Microsoft.Web"]
  }

  resource "azurerm_app_service_environment_v3" "ase" {
    name                = "asev3"
    resource_group_name = azurerm_resource_group.rg1.name
    subnet_id           = azurerm_subnet.ase.id

    cluster_setting {
      name  = "DisableTls1.0"
      value = "1"
    }

    cluster_setting {
      name  = "InternalEncryption"
      value = "true"
    }

    cluster_setting {
      name  = "FrontEndSSLCipherSuiteOrder"
      value = "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256"
    }

  }


```

### Debug Output

https://gist.github.com/artiomjakubovic/1a76beeda53590b57f984a0455908594
### Expected Behaviour

azurerm_app_service_environment_v3 resource successful creation
### Actual Behaviour
Resource creation fails with below error in CLI:

│ Error: creating App Service Environment: (Hosting Environment Name "itsolid-asev3" / Resource Group "itsolid-BIS-app"): web.AppServiceEnvironmentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]
│
│   with azurerm_app_service_environment_v3.ase,
│   on ase.tf line 2, in resource "azurerm_app_service_environment_v3" "ase":
│    2: resource "azurerm_app_service_environment_v3" "ase" {
│
│ creating App Service Environment: (Hosting Environment Name "itsolid-asev3" / Resource Group "itsolid-BIS-app"): web.AppServiceEnvironmentsClient#CreateOrUpdate: Failure 
│ sending request: StatusCode=0 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by doug-fish** [comment] 2021-07-19 19:29
I see what I believe is the same issue with the v2 ASE as well.

provider "azurerm" {
 features {}
}


resource "azurerm_resource_group" "rg" {
  name     = "drf-fail-demo-rg"
  location = "North Central US"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "drf-fail-demo-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "ase" {
  name                 = "drf-asesubnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.3.0/24"]
}

resource "azurerm_app_service_environment" "ase" {
  name                         = "drf-fail-demoase"
  resource_group_name          = azurerm_resource_group.rg.name
  subnet_id = azurerm_subnet.ase.id
  pricing_tier                 = "I1"
  front_end_scale_factor       = 10
  internal_load_balancing_mode = "Web, Publishing"

  cluster_setting {
    name  = "DisableTls1.0"
    value = "1"
  }
}


╷
│ Error: creating App Service Environment "drf-fail-demoase" (Resource Group "drf-fail-demo-rg"): web.AppServiceEnvironmentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]
│ 
│   with azurerm_app_service_environment.ase,
│   on module_test.tf line 25, in resource "azurerm_app_service_environment" "ase":
│   25: resource "azurerm_app_service_environment" "ase" {
│ 
╵

I'm upvoting this issue assume this is the same. If this appears to be separate I'd be happy to open a separate issue.

**Comment by doug-fish** [comment] 2021-07-19 19:42
I have successfully created a cluster by omitting the DisableTls block
cluster_setting {
name = "DisableTls1.0"
value = "1"
}

Perhaps this workaround will work for v3 as well?

**Comment by artiomjakubovic** [comment] 2021-07-20 06:34
@doug-fish thanks for the hint. It looks like a workaround. I have omitted all cluster_setting blocks and it seems it is working now. At least it is running for 50 min already. Previous runs were failing at around 8 min of runtime.

**Comment by miwebst** [comment] 2021-07-22 15:57
@artiomjakubovic, this was a regression that has since been fixed. Also I see the cipher suites you have supplied may not include the recommended ciphers (they should be required for ASEv3), so you may want to add them as well. You can find them here: https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-custom-settings#change-tls-cipher-suite-order

**Comment by jackofallops** [comment] 2021-07-27 07:51
> @artiomjakubovic, this was a regression that has since been fixed. Also I see the cipher suites you have supplied may not include the recommended ciphers (they should be required for ASEv3), so you may want to add them as well. You can find them here: [docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-custom-settings#change-tls-cipher-suite-order](https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-custom-settings#change-tls-cipher-suite-order)

Based on this information, I'm going to close this issue for now.

**Closed by jackofallops** 2021-07-27 07:51 UTC
Labels: bug, service/app-service
