### ISSUE TITLE
Support for AKS OS configuration

### ISSUE THREAD

**Issue by wrdls** [terraform-providers/terraform-provider-azurerm#7358] opened 2020-06-17 10:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's possible now to configure the node OS used by AKS: https://docs.microsoft.com/en-us/azure/aks/cluster-configuration
I.e., it allows to use Ubuntu 18.04 instead of 16.04.

The cli command uses `aks-custom-headers` so adding support for custom headers might work as well?

### New or Affected Resource(s)

* azurerm_kubernetes_cluster
* azurerm_kubernetes_cluster_node_pool

**Comment by jmcshane** [comment] 2020-07-16 11:52
Related #6793

**Comment by tombuildsstuff** [comment] 2020-07-16 13:27
hi @wrdls 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6793 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-07-16 13:27 UTC
Labels: service/kubernetes-cluster
