### ISSUE TITLE
Can't connect Azure Activity Logs to a Log Analytics Workspace Using Terraform

### ISSUE THREAD

**Issue by TripleMalahat** [terraform-providers/terraform-provider-azurerm#4446] opened 2019-09-26 16:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There currently seems to be no resource that allows the linking of Azure Activity Logs for a subscription to a Log Analytics Workspace in the style of the New-AzureRmOperationalInsightsAzureActivityLogDataSource PowerShell command. 

### New or Affected Resource(s)

New resource: azurerm_OperationalInsightsAzureActivityLogDataSource

### Potential Terraform Configuration

Something like the following would be ideal:

```hcl
resource "azurerm_OperationalInsightsAzureActivityLogDataSource" "main" {
  name                  = ""
  subscription_id   = ""
  workspace_id      = ""
  backfillstarttime  = ""
}
```

### References

https://docs.microsoft.com/en-us/powershell/module/azurerm.operationalinsights/new-azurermoperationalinsightsazureactivitylogdatasource?view=azurermps-6.13.0

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log-collect

* #0000

**Comment by tombuildsstuff** [comment] 2019-09-30 05:54
hi @TripleMalahat 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3182 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3182 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-30 05:54 UTC
Labels: duplicate, enhancement, service/oms
