### ISSUE TITLE
Resizing the Managed AKS cluster node size or type destroys and recreates the cluster

### ISSUE THREAD

**Issue by vishnu-anil** [terraform-providers/terraform-provider-azurerm#5311] opened 2020-01-05 11:06 UTC
I am trying to resize the AKS cluster Nodes with Terraform, but everytime i does this the terraform destroys and recreates the cluster. I am able to resize the Cluster without disturbing the environment from Portal.

Is this expected? Please advise
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by jcorioland** [comment] 2020-01-06 08:57
This is the expected behavior. AKS does not support changing the size of the VMs once the pool has been created.
The recommended way to do this is to add a new pool with the new desired SKU and cordon/drain the old one (see https://github.com/Azure/AKS/issues/529)

**Comment by vishnu-anil** [comment] 2020-01-07 02:59
Thanks @jcorioland . So does that mean that i have to redeploy my apps into the newly added pool, test it and the prune the old node pool?

**Comment by jcorioland** [comment] 2020-01-07 08:29
@vishnu-anil if you need HA, this is the best thing to do yes. Create a new node pool, deploy your application test, switch and prune the old node pool. In the mean time, you can [codorn](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cordon) the nodes of the old pool to make sure nothing is scheduled on it.

**Comment by tombuildsstuff** [comment] 2020-01-08 15:53
hey @vishnu-anil 

Thanks for opening this issue.

As @jcorioland has mentioned unfortunately the underlying Azure Kubernetes Service itself doesn't support this functionality today - as such this isn't something we can support at this time. If you're looking for AKS to support this functionality I'd recommend opening a [Feature Request on their repository](https://github.com/Azure/aks/issues) where they should be able to take a look; and once it's available we should be able to implement this functionality.

However since this functionality isn't available in AKS today - rather than leaving this open until that feature request is implemented I'm going to close this issue for the moment; once it's available we'll circle around and take another look :)

Thanks!

**Closed by tombuildsstuff** 2020-01-08 15:53 UTC
Labels: question, service/kubernetes-cluster
