### ISSUE TITLE
azurerm_automation_schedule fails with `automation_account_name` must be set

### ISSUE THREAD

**Issue by ewank-hub** [terraform-providers/terraform-provider-azurerm#4808] opened 2019-11-05 10:57 UTC
azurerm_automation_schedule fails on when automation_account_name or account_name is computed, and the azurerm_automation_account does not yet exist.

If the azurerm_automation_account is then deployed on its own, the azurerm_automation_schedule resource deploys correctly.
(This is achieved by commenting out the azurerm_automation_scheduleresource on the first run)

Error displayed;
https://github.com/terraform-providers/terraform-provider-azurerm/blob/94cf18b287d634ee16aa5e37d3a73d3e8a356fa4/azurerm/resource_arm_automation_schedule.go#L205

Code being executed;
```
resource "azurerm_automation_schedule" "test" {
  automation_account_name = azurerm_automation_account.aa.name
  name                    = "daily-pause-1830hrs"
  resource_group_name     = var.resource-group-name
  frequency               = "Day"
  interval                = 1
  start_time              = format("%sT18:30:00Z", split("T", timestamp())[0])
  timezone                = "Europe/London"
  description             = "7 days a week schedule for 1830hrs GMT"
  lifecycle {
    ignore_changes = [start_time]
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.13
+ provider.azurerm v1.36.1

### Affected Resource(s)

azurerm_automation_schedule

### Terraform Configuration Files

as above

### Debug Output

-

### Expected Behavior

resource should be created

### Actual Behavior

resource not created, with the error;

`automation_account_name` must be set

### Steps to Reproduce

1. `terraform plan`

**Comment by WheresAlice** [comment] 2019-11-05 11:09
I think this is because of the `diff.GetOK` - which will return false because the automation_account_name is computed when the `azurerm_automation_account` is being created at the same time.

I'm not too familiar with this codebase, but I would make `automation_account_name` to be required and drop the `diff.getOK` checks.  This would break the compatibility with the old deprecated `account_name` though.

This seems related to but not caused by #4776 to me.

**Comment by njuCZ** [comment] 2020-05-08 09:45
@ewank-hub I believe this problem has been fixed in newer version of azurerm, could you please upgrade the azurerm version and have a try ?

**Comment by mybayern1974** [comment] 2020-05-20 12:11
Hi @ewank-hub 

May we close this issue by assuming njuCZ’s reply has answered your question in terms of using the newer version of this provider? Feel free to reopen this if you do not think so. Thank you.

**Closed by mybayern1974** 2020-05-20 12:11 UTC
Labels: bug, service/automation
