### ISSUE TITLE
Support for "deny public network access" in Azure Database for Microsoft SQL Server

### ISSUE THREAD

**Issue by bogdbo** [terraform-providers/terraform-provider-azurerm#6771] opened 2020-05-05 10:15 UTC
### Description

When the Private Link is used, the Microsoft SQL Server can be accessed using a private address. Therefore we should be able to deny public network access. This option should exists in azurerm_sql_server
New or Affected Resource(s)

    azurerm_sql_server

### Potential Terraform Configuration

    resource "azurerm_sql_server" "example" {

        ...

       public_network_access_enabled = false
    }

### References

* [Deny public network access](https://docs.microsoft.com/en-gb/azure/mysql/concepts-data-access-security-private-link#deny-public-access-for-azure-database-for-mysql)
* [Support for "deny public network access" in Azure Database for MySQL](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6482)

**Comment by yupwei68** [comment] 2020-05-07 02:59
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/6374

**Comment by mybayern1974** [comment] 2020-05-15 13:05
hi @bogdbo 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of [#6374](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6374)- rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to [#6374](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6374) for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-05-15 13:05 UTC
Labels: question, service/mssql
