### ISSUE TITLE
Multiple network profiles for VMSS

### ISSUE THREAD

**Issue by jcwrights** [terraform-providers/terraform-provider-azurerm#1557] opened 2018-07-12 16:07 UTC
I am attempting to create an Azure Virtual Machine Scale Set using multiple network profiles (network interfaces and two IP addresses on different subnets), however it does not allow me to create more than one primary.  Is this a limitation?

**Comment by tombuildsstuff** [comment] 2018-07-13 12:50
hi @jcwrights 

Thanks for opening this issue

> I am attempting to create an Azure Virtual Machine Scale Set using multiple network profiles (network interfaces and two IP addresses on different subnets), however it does not allow me to create more than one primary. Is this a limitation?

Within a Virtual Machine Scale Set in Azure only one of the NIC profiles can be defines as Primary - other NIC's must then designated as secondary (since this Profile is copied onto each instance within the Scale Set; which is by design in Azure. Given this is a question regarding Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2018-07-13 12:50 UTC
