### ISSUE TITLE
Sample code for azurerm_notification_hub are not working

### ISSUE THREAD

**Issue by metacpp** [terraform-providers/terraform-provider-azurerm#1685] opened 2018-07-31 00:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.7

### Affected Resource(s)

* azurerm_notification_hub
* azurerm_notification_hub_namespace
* azurerm_notification_hub_authorization_rule

### Affected Data Source(s)
* azurerm_notification_hub
* azurerm_notification_hub_namespace

### Terraform Configuration Files

* Sample Code
https://www.terraform.io/docs/providers/azurerm/r/notification_hub_authorization_rule.html

### Expected Behavior
1. Successfully create notification hub related resources.
2. https://www.terraform.io/docs/providers/azurerm/d/notification_hub.html should be accessible.
3. Sample code for data sources should also be working.

### Actual Behavior
* Notification Hub related resources:
```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_notification_hub_namespace.test: 1 error(s) occurred:

* azurerm_notification_hub_namespace.test: Error creating/updating Notification Hub Namesapce "myappnamespace" (Resource Group "notificationhub-resources"): notificationhubs.NamespacesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The specified name is not available."

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1. Copy and paste [sample code.](https://www.terraform.io/docs/providers/azurerm/r/notification_hub_authorization_rule.html)
2. `terraform init`

**Comment by metacpp** [comment] 2018-07-31 00:36
Broken link for data source:
https://www.terraform.io/docs/providers/azurerm/d/notification_hub.html

**Comment by tombuildsstuff** [comment] 2018-07-31 05:41
Hi @metacpp 

The code samples within the "Example Usage" block are intended to be references of how to use the Resource/Data Source in question - rather than fully working/copy-pasteable examples. For example in many cases the resource names need to be globally unique within Azure - and as such will require editing in at least some form, or Data Sources will require that these resources exist. For this reason I'm going to close this issue for the moment as this is working as intended.

Thanks!

**Closed by tombuildsstuff** 2018-07-31 05:41 UTC
Labels: documentation, service/notifications
