### ISSUE TITLE
Terraform should track azure resource after initial create not async completion?

### ISSUE THREAD

**Issue by paulgmiller** [terraform-providers/terraform-provider-azurerm#12719] opened 2021-07-23 16:47 UTC
Provider should start tracking resource in state file  after the call to CreateOrUpdate succeeds regardless of if wait for completion fails
https://github.com/terraform-providers/terraform-provider-azurerm/blob/b30da0d2ba5b5035f1e0f9a4961643b91b3fbe94/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L977
```
future, err := client.CreateOrUpdate(ctx, resGroup, name, parameters)
if err != nil {
return fmt.Errorf("creating Managed Kubernetes Cluster %q (Resource Group %q): %+v", name, resGroup, err)
}
if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
return fmt.Errorf("waiting for creation of Managed Kubernetes Cluster %q (Resource Group %q): %+v", name, resGroup, err)
}
```

After the first call the arm resource exists. Even if the second call fails/times out it may eventually be  restored to a good state by a retry. Custoemrs complain that terraform gets confused when this happens becaus the resource is not in the "state" file. Once success is retured by Create or Update terraform either needs to treat this resource as existing (even if its not healthy/provisionstate!=succees) or delete it. 

I'm comign from the AKS team and my terraform knowledge is limited but this is how most azure resource manager calls work. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

All?

### Affected Resource(s)

* `azurerm_kubernetesclusterresource`
* Maybe all other azure arm resources

### Terraform Configuration Files

None - second hand from custoemrs
Possibly otehrs

### References

Internally AKS has issue  243145056 to track this.

**Comment by tombuildsstuff** [comment] 2021-07-26 07:17
hi @paulgmiller 

Thanks for opening this issue.

Terraform intentionally only tracks resources once the platform (this applies to all providers AWS, Azure etc) has both Successfully deployed the resource and it's also ready for use (for example the DNS Name is replicated etc). Within the Azure Platform that means a `ProvisioningState` of `Succeeded` - since a `ProvisioningState` of `Failed` can mean multiple things - including both "this resource will never recover" and "this resource may become available later".

Due to the fact that the Azure API can be ambiguous in the meaning of "Failed" that varies on a per-Resource Provider basis, unfortunately Terraform has no means of knowing whether a particular resource will become available at a given point in time - as such it's unfortunate but we require the user to determine if this resource will recover or not (since redeploying this resource, or deleting + reprovisioning could cause a further outage for example).

Whilst certain Azure API's return a sub-state in addition to ProvisioningState, unfortunately the AKS API doesn't - this leads to the situation as called out above where we're unable to confirm if the cluster will eventually become usable or not. The upstream AKS issue is being tracked in https://github.com/Azure/AKS/issues/1972 (and I've had multiple discussions with the service team who've confirmed they'll look into adding a sub-state to track this) - as such since this is an AKS issue, whilst I'd like to thank you for opening this issue I'm going to close this in favour of the upstream issue.

Thanks!

**Closed by tombuildsstuff** 2021-07-26 07:17 UTC
Labels: question, upstream-microsoft

**Comment by paulgmiller** [comment] 2021-07-31 16:29
Thanks @tombuildsstuff  I'm with the azure service team dev side and trying to help here. Contnuing discussion over on the linked aks issue but also happy to talk on teams/slack/irc whatever.
