### ISSUE TITLE
data.azurerm_client_config doesn't provide the user ObjectID when logged in via Az CLI login method

### ISSUE THREAD

**Issue by JustinGrote** [terraform-providers/terraform-provider-azurerm#3502] opened 2019-05-22 19:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using data.azurerm_client_config when doing az cli login method does not provide the objectID of the "logged in user". This is necessary, for instance, when setting up Azure Key Vault and Secrets. By default Key Vault doesn't provide rights to update secrets even the creator, so you have to add an access policy for the user running terraform or else you get access denied when trying to add the secrets.

### New or Affected Resource(s)

* data.azurerm_client_config

### Example

```hcl
data "azurerm_client_config" "this" {}

output "testcontext" {
  value = "${data.azurerm_client_config.client_id}"
}

```
Should match:
az ad signed-in-user show --output yaml | where {$PSItem -match 'objectid'}

But it doesn't.

### Potential Terraform Configuration

Populate the user object id to service_principal_object_id. This would allow for a non-breaking change.

### Workaround

```hcl
data "external" "this_az_account" {
  program = [
    "az",
    "ad",
    "signed-in-user",
    "show",
    "--query",
    "{displayName: displayName,objectId: objectId,objectType: objectType,odata_metadata: \"odata.metadata\"}"
  ]
}

resource "azurerm_key_vault_access_policy" "terraform" {
  object_id = "${data.external.this_az_account.result.objectId}"
}
```

**Comment by tombuildsstuff** [comment] 2019-05-23 06:09
hi @JustinGrote 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3234 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3234 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-05-23 06:09 UTC
Labels: duplicate, question

**Comment by JustinGrote** [comment] 2019-05-23 06:18
Yep, ironically I posted my workaround there 12 days ago, must have forgot
about it. You can close this as a dupe.
