### ISSUE TITLE
Support for specifying node pool type (system vs user) for azurerm_kubernetes_cluster_node_pool

### ISSUE THREAD

**Issue by uipo78** [terraform-providers/terraform-provider-azurerm#6853] opened 2020-05-11 15:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Azure now has as concept to distinguish critical system node pools from node pools running user applications](https://docs.microsoft.com/en-us/azure/aks/use-system-pools)

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool
* (possibly) azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  is_system_node_pool = true

  tags = {
    Environment = "Production"
  }
}
```

or

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  node_pool_type = "system"

  tags = {
    Environment = "Production"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/use-system-pools

**Comment by tombuildsstuff** [comment] 2020-05-12 07:07
hi @uipo78 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6058 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6058 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-05-12 07:07 UTC
Labels: duplicate, enhancement, service/kubernetes-cluster

**Comment by uipo78** [comment] 2020-05-12 15:07
whoops didn't see that one. sorry!
