### ISSUE TITLE
Destroy kubernetes_node_pool: Error waiting for the deletion. Operation was overriden and canceled by later operation

### ISSUE THREAD

**Issue by arodriguezdlc** [terraform-providers/terraform-provider-azurerm#5638] opened 2020-02-07 09:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.12.16
Provider version: 1.41.0

### Description

Hello, 

We are having an issue when trying to destroy a infrastructure with an AKS cluster and some nodepools. When deleting node pools, we are having this error:

```
Error: Error waiting for the deletion of Node Pool "kafka" (Managed Kubernetes Cluster "albero-azure-a" / Resource Group "baikal-albero-azure-a-rg"): Code="Canceled" Message="The operation was overriden and canceled by a later operation 00000000-0000-0000-0000-000000000000."
```

This is an intermitent error, but we don't know what is happening and why we are having this weird operation-id. 

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Steps to Reproduce

1. Create an AKS cluster and various node pools. 
2. Destroy them

**Comment by tombuildsstuff** [comment] 2020-02-07 12:18
hi @arodriguezdlc 

Thanks for opening this issue.

So that we can take a look into this issue would you be able to provide the Terraform Configuration being used?

Thanks!

**Comment by arodriguezdlc** [comment] 2020-02-07 12:21
Hi @tombuildsstuff thank you for your respone. Here you are the Terraform Configuration 😄 

```
resource "azurerm_kubernetes_cluster" "aks" {
  name                = var.cluster
  location            = azurerm_resource_group.rg.location
  kubernetes_version  = "1.15.7"
  resource_group_name = azurerm_resource_group.rg.name
  node_resource_group = var.resource_group_aks_nodes
  dns_prefix          = var.deployment_prefix

  default_node_pool {
    name       = "common"
    enable_auto_scaling = true
    min_count = 1
    max_count = 100
    vm_size    = var.common_nodes.type
    max_pods   = 80
    os_disk_size_gb = var.common_nodes.disk_size_gb
  }

  service_principal {
    client_id     = azuread_service_principal.auth.application_id
    client_secret = azuread_service_principal_password.auth.value
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "calico"
    load_balancer_sku = "standard"
  }

  linux_profile {
    admin_username = "azureuser"
    ssh_key {
      key_data = trimspace(tls_private_key.nodes.public_key_openssh)
    }
  }

  addon_profile {
    kube_dashboard {
      enabled = true
    }

    http_application_routing {
      enabled = false
    }
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "kafka" {
  name                  = "kafka"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  vm_size               = var.kafka_nodes.type
  enable_auto_scaling   = true
  min_count = 1
  max_count = 100
  max_pods              = 80
  node_taints           = [ "platform.com/kafka=true:NoSchedule" ]
  os_disk_size_gb       = var.kafka_nodes.disk_size_gb
}

resource "azurerm_kubernetes_cluster_node_pool" "processing" {
  for_each = var.processing_nodes

  name                  = each.key
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  vm_size               = each.value.type
  enable_auto_scaling   = true
  min_count = 1
  max_count = 100
  max_pods              = 80
  node_taints           = [ "platform.com/processing=true:NoSchedule" ]
  os_disk_size_gb       = each.value.disk_size_gb
}

```

**Comment by maxkochubey** [comment] 2020-02-12 15:04
Hello! We encountered the same issue.
Terraform version: v0.12.19
AzureRM provider version: 1.43.0

Restarting of the destroying process runs without errors.

**Comment by neil-yechenwei** [comment] 2020-04-28 09:07
Thanks for opening this issue. After tested twice, seems all resources can be destroyed successfuly with below tfconfig. Seems I cannot repro the issue. Maybe I missed something. If you need, you can try below config and check whether the problem still exists. Thanks.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-aks-neil2"
  location = "westus2"
}

resource "tls_private_key" "test" {
  algorithm = "RSA"
  rsa_bits  = "2048"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "aks-neil"
  location            = azurerm_resource_group.test.location
  kubernetes_version  = "1.15.7"
  resource_group_name = azurerm_resource_group.test.name
  node_resource_group = "acctestRGAKS-neil"
  dns_prefix          = "acctestaksprefix"

  default_node_pool {
    name       = "common"
    enable_auto_scaling = true
    min_count = 1
    max_count = 100
    vm_size    = "Standard_DS2_v2"
    max_pods   = 80
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = "<insert your client id>"
    client_secret = "<insert your client secret>"
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "calico"
    load_balancer_sku = "standard"
  }

  linux_profile {
    admin_username = "azureuser"
    ssh_key {
      key_data = trimspace(tls_private_key.test.public_key_openssh)
    }
  }

  addon_profile {
    kube_dashboard {
      enabled = true
    }

    http_application_routing {
      enabled = false
    }
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "npneil1"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count = 1
  max_count = 100
  max_pods              = 80
  node_taints           = [ "platform.com/kafka=true:NoSchedule" ]
  os_disk_size_gb       = 30
}

resource "azurerm_kubernetes_cluster_node_pool" "test2" {
  name                  = "npneil2"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count = 1
  max_count = 100
  max_pods              = 80
  node_taints           = [ "platform.com/test2=true:NoSchedule" ]
  os_disk_size_gb       = 30
}
```

The result of `tf destroy`:
```
azurerm_kubernetes_cluster_node_pool.test2: Destruction complete after 6m13s
azurerm_kubernetes_cluster_node_pool.test: Destruction complete after 6m13s
azurerm_kubernetes_cluster.test: Destruction complete after 11m21s
Destroy complete! Resources: 5 destroyed.
```

**Comment by mybayern1974** [comment] 2020-05-15 13:20
Hi @arodriguezdlc 

Per neil-yechenwei’s investigation, may we close this issue for it cannot repro? Feel free to reopen it if things still repro at your side, and if so please provide more contexts if there are to help repro. Thank you.

Btw, would you wanna try the latest version of provider.azurerm.v2+ to solve the problem?

**Closed by mybayern1974** 2020-05-15 13:20 UTC
Labels: bug, service/kubernetes-cluster

**Comment by Bessonov** [comment] 2020-05-16 06:56
We was able to reproduce this issue very often. To do that we just run terraform for different environments (and use different state file) in parallel. For example if CI run terraform for build environment and a developer run same script for stage environment, then there is a big chance to get this error on CI, but not on local host.

Side note: we don't use terraform environments, but generate backend config (https://github.com/hashicorp/terraform/issues/13022).

We didn't tried it with azurerm v2 yet, because of this issue we avoid to work in parallel. I think we can do than in 2-3 weeks.

**Comment by arodriguezdlc** [comment] 2020-05-18 06:35
Hello @mybayern1974, we are still reproducing this issue. We are deploying multiple environments on the same azure account all the time, so maybe it's relating to the issue @Bessonov is describing.

**Comment by neil-yechenwei** [comment] 2020-05-18 07:36
@arodriguezdlc , could you have a try azurerm v2.X with above tf config I provided to check whether the issue still exists?

**Comment by arodriguezdlc** [comment] 2020-05-22 06:20
Hello @neil-yechenwei , I couldn't reproduce the issue with either v2.X or v1.X. I think it was a problem on the Azure side and for any reason, it's not happening now. If I see the issue again I will write here again. Thank you for your time :)
