### ISSUE TITLE
slot config in azurerm_function_app_slot

### ISSUE THREAD

**Issue by shivanigoyaluk** [terraform-providers/terraform-provider-azurerm#7251] opened 2020-06-08 14:10 UTC
I'm using Terraform to create a slot on an azure function app but I need some of the app settings to be sticky. This is normally done using the "slotConfigNames" in ARM but doesn't seem to be possible in Terraform.

Is this possible to add this feature?

https://www.terraform.io/docs/providers/azurerm/r/function_app_slot.html

_Originally posted by @hashibot in https://github.com/terraform-providers/terraform-provider-azurerm/pull/6435#issuecomment-639543223_

**Comment by tombuildsstuff** [comment] 2020-06-08 14:17
hi @shivanigoyaluk 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1440 - which is tracking supporting Sticky App Settings. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1440 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-08 14:17 UTC
Labels: duplicate, enhancement, service/functions
