### ISSUE TITLE
azurerm_windows_virtual_machine does not support creation from image with managed data disks

### ISSUE THREAD

**Issue by rbarna1** [terraform-providers/terraform-provider-azurerm#6004] opened 2020-03-05 19:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Reviewing the docs on the new azurerm_windows_virtual_machine resource, I dont see any reason why this **shouldnt** work.
We use terraform to create Windows Server images that have managed data disks.
In v0.11 with the Azure provider, when we subsequently make VMs from those images no mention of the managed disk snapshots is required....they simply come w/ the image.  In v0.12 we get the following error:

> Error: Error creating Windows Virtual Machine "BBVM1-vm" (Resource Group "BBVM1"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile." Target="storageProfile"
>on modules\vm-base\main.tf line 47, in resource "azurerm_windows_virtual_machine" "config":
  47: resource "azurerm_windows_virtual_machine" "config" {

Our old v0.11 version

``` terraform
resource "azurerm_virtual_machine" "config" {
  count                            = "${contains(var.servers_needed, var.computer_name) ? 1 : 0}"
  name                             = "${local.name}-vm"
  location                         = "${azurerm_resource_group.config.location}"
  license_type                     = "Windows_Server"
  resource_group_name              = "${azurerm_resource_group.config.name}"
  network_interface_ids            = ["${azurerm_network_interface.config.id}"]
  vm_size                          = "${var.virtual_machine_size}"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    id = "${data.azurerm_image.search.id}"
  }

  storage_os_disk {
    name              = "${local.name}-os-disk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "StandardSSD_LRS"
  }

  os_profile {
    computer_name  = "${local.name}"
    admin_username = "${var.admin_username}"
    admin_password = "${var.admin_password}"
  }

  os_profile_windows_config {
    provision_vm_agent        = true
    enable_automatic_upgrades = false

    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "AutoLogon"
      content      = "<AutoLogon><Password><Value>${var.admin_password}</Value></Password><Enabled>true</Enabled><LogonCount>1</LogonCount><Username>${var.admin_username}</Username></AutoLogon>"
    }

    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "FirstLogonCommands"
      content      = "${file("${path.root}/FirstLogonCommands.xml")}"
    }
  }
}
```

Our new v0.12 with the current beta azurerm_windows_virtual_machine
``` terraform
resource "azurerm_windows_virtual_machine" "config" {
  count                 = contains(var.servers_needed, var.computer_name) ? 1 : 0
  name                  = "${local.name}-vm"
  location              = azurerm_resource_group.config[0].location
  resource_group_name   = azurerm_resource_group.config[0].name
  network_interface_ids = [azurerm_network_interface.config[0].id]
  size                  = var.virtual_machine_size
  source_image_id       = data.azurerm_image.search.id
  computer_name         = local.name
  admin_username        = var.admin_username
  admin_password        = var.admin_password

  os_disk {
    name                 = "${local.name}-os-disk"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  additional_unattend_content {
    setting = "AutoLogon"
    content = "<AutoLogon><Password><Value>${var.admin_password}</Value></Password><Enabled>true</Enabled><LogonCount>1</LogonCount><Username>${var.admin_username}</Username></AutoLogon>"
  }

  additional_unattend_content {
    setting = "FirstLogonCommands"
    content = file("${path.root}/FirstLogonCommands.xml")
  }
}
```

**Comment by xuhaiwei** [comment] 2020-06-24 09:18
Hi, want to know if there is any update on this issue?

**Comment by jozephp** [comment] 2020-10-06 13:57
Hello, I also have encountered similar error with Terraform 0.12.29 and its blocking the use of Managed disk(with packer imaged) to be deployed. Appreciate if we could prioritize this

Terraform v0.12.29
+ provider.azurerm v2.10.0

**Comment by grillba** [comment] 2020-10-16 04:42
Hi all, are there any known work arounds to this issue?

Thanks

**Comment by CGCampbell07** [comment] 2020-10-16 14:13
This still seems to be an issue with terraform 0.12.26 and azure 2.30

**Comment by MDavies-AA** [comment] 2020-11-12 10:03
Hi, Also experiencing this issue. 

Is this still being worked on?

**Comment by Sur3n00** [comment] 2020-11-25 08:58
Hi all,

Any update on this bug. We are experiencing the same bug with azurerm_linux_virtual_machine.
Terraform: 0.13.5
Azurerm: v2.37.0

Thanks.

**Comment by LaurentLesle** [comment] 2021-01-19 09:26
@tombuildsstuff @katbyte We are also facing this issue when deploying a linux vm with a reference image that has an OS disk and a data disk. That was working fine with the previous azurerm_virtual_machine. Looks like azurerm_linux_virtual_machine and azurerm_windows_virtual_machine cannot deploy a marketplace image that has os and data.

```hcl
Error: creating Linux Virtual Machine "cyclecloud" (Resource Group "example-resources"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile." Target="storageProfile"
```

Happy to share a code to reproduce if needed.

**Comment by xpillons** [comment] 2021-01-28 09:37
@tombuildsstuff as you closed #7460 considering the Linux and Windows are the same in that case, I want to highlight that I'm getting the same issue on Linux trying to deploy the marketplace image below. This was working fine with the azurerm_virtual_machine and is not with the azurerm_linux_virtual_machine

Here is what was used with the azurerm_virtual_machine provided
```
  storage_image_reference {
    publisher = "azurecyclecloud"
    offer     = "azure-cyclecloud"
    sku       = "cyclecloud-81"
    version   = "8.1.0"
  }

  plan {
    name      = "cyclecloud-81"
    publisher = "azurecyclecloud"
    product   = "azure-cyclecloud"
  }

  storage_data_disk {
    lun               = 0
    name              = "ccportal-datadisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
    disk_size_gb      = 128
  }
```

**Comment by ruandersMSFT** [comment] 2021-01-31 20:47
Also encountering when trying to deploy an VM based on an Azure Image that has both an OS Disk and more or more Data Disk(s).  The cause of this is the observed implementation that Data Disk are **only** handled via the association resource.  While association works for data disk associations that can occur after the VM deployment has occurred, many use cases exist where the DataDisks definition must be provided directly (not via a secondary association process). 

The Terraform code causing this issue for many can be noted on [line 391 of windows_virtual_machine_resource.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/349893341e2b1eb934bea07d3b253d9774839b6a/azurerm/internal/services/compute/windows_virtual_machine_resource.go#L433), where only an empty array is allowed on creation and nil on update.

Code fix for this issue needs to enable direct use of DataDisks.

**Comment by tombuildsstuff** [comment] 2021-02-01 06:38
👋 

Just noticed there's 3 issues tracking the same thing: this issue, #6074 (for linux VM's) and #6117 - rather than having 3 issues tracking the same thing I'm going to close this in favour of #6117 - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-01 06:38 UTC
Labels: bug, service/virtual-machine

**Comment by jpbuecken** [comment] 2021-02-01 08:47
@tombuildsstuff  

> Just noticed there's 3 issues tracking the same thing: this issue, #6074 (for linux VM's) and #6117

I disagree that #6117 is the same issue as this one:
#6144 is about data disk attachment during creation time
This issue is about using volumes as image.

The value to boot from disk is 52 *thumb up* emoji, and #6144 to attach data disks has only 38 *thump up* emoji.

Even the HCL will look different:

```
resource "azurerm_linux_virtual_machine" "example" {
  [...]

  os_disk {
    name                 = "example-os"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  data_disk {
    name                 = "example-data"
    caching              = "ReadWrite"
    disk_size_gb         = 4096
    lun                  = 0
    storage_account_type = "StandardSSD_LRS"
  }

  [...]
}
```

The HCL for this issue may look like the old azurerm_virtual_machine or as in the original post:
```
resource "azurerm_windows_virtual_machine" "config" {
[...]
  os_disk {
    name                 = "${local.name}-os-disk"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }
[...]
}
```

From a code perspective, you may need to solve similar problems, but I think you still need to do evaluate different considerations as well to solve both.

Anyway, this is the first issue (lowest issue number). If any you should close #6144. But then you may see that #6144 needs more work that this issue only.
