### ISSUE TITLE
azurerm_monitor_metric_alert error Detect invalid value: microsoft.insights/components

### ISSUE THREAD

**Issue by abilous-ti** [terraform-providers/terraform-provider-azurerm#6424] opened 2020-04-09 09:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20

provider.azurerm v2.5.0

### Affected Resource(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "this" {
  name     = var.name
  resource_group_name  = var.resource_group_name
  scopes              = [azurerm_application_insights.this.id]
  frequency = "PT5M"
  severity = 2
  window_size = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "availabilityResults/count"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 6
  }
  action {
    action_group_id = var.action_group_id
  }
}
```

### Expected Behavior

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior

Error creating or updating metric alert "maetricalertname" (resource group "resourcegroupname"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\"code\":\"BadRequest\",\"message\":\"Detect invalid value: microsoft.insights/components for query parameter: 'metricnamespace', the value must be: microsoft.insights/webtests if the query parameter is provided, you can also skip this optional query parameter.\"}"
on ../../main.tf line 1, in resource "azurerm_monitor_metric_alert" "this":
   1: resource "azurerm_monitor_metric_alert" "this" 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
There is no supported parameter: 'metricnamespace' value in Microsoft documentation
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported

If metricnamespace' value is set to microsoft.insights/webtests we are getting an error:

Error: Error creating or updating metric alert "maetricalertname" (resource group "resourcegroupname"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\"code\":\"BadRequest\",\"message\":\"microsoft.insights/webtests is not a supported platform metric namespace, supported ones are Microsoft.AnalysisServices/servers,Microsoft.Web/serverFarms,Microsoft.Web/sites,Microsoft.Web/sites/slots,Microsoft.Web/hostingEnvironments/multiRolePools,Microsoft.Web/hostingEnvironments/workerPools,test.shoebox/testresources,test.shoebox/testresources2,Microsoft.ServiceBus/namespaces,Microsoft.EnterpriseKnowledgeGraph/services,Microsoft.Network/virtualNetworks,Microsoft.Network/natGateways,Microsoft.Network/publicIPAddresses,Microsoft.Network/networkInterfaces,Microsoft.Network/privateEndpoints,Microsoft.Network/loadBalancers,Microsoft.Network/networkWatchers/connectionMonitors,Microsoft.Network/virtualNetworkGateways,Microsoft.Network/connections,Microsoft.Network/applicationGateways,Microsoft.Network/dnszones,Microsoft.Network/privateDnsZones,Microsoft.Network/trafficmanagerprofiles,Microsoft.Network/expressRouteCircuits,Microsoft.Network/vpnGateways,Microsoft.Network/p2sVpnGateways,Microsoft.Network/expressRouteGateways,Microsoft.Network/expressRoutePorts,Microsoft.Network/azureFirewalls,Microsoft.Network/privateLinkServices,Microsoft.Network/frontdoors,Microsoft.Network/virtualRouters,Microsoft.HealthcareApis/services,Microsoft.DBforMySQL/servers,Microsoft.Sql/servers,Microsoft.Sql/servers/databases,Microsoft.Sql/servers/elasticpools,Microsoft.Sql/managedInstances,microsoft.insights/components,microsoft.insights/autoscalesettings,Microsoft.KeyVault/vaults,Microsoft.Cache/Redis,Microsoft.ContainerRegistry/registries,Microsoft.DocumentDB/databaseAccounts,Microsoft.VMwareCloudSimple/virtualMachines,Microsoft.ContainerInstance/containerGroups,Microsoft.Devices/IotHubs,Microsoft.Devices/ElasticPools,Microsoft.Devices/ElasticPools/IotHubTenants,Microsoft.Devices/ProvisioningServices,Microsoft.Compute/virtualMachines,Microsoft.Compute/virtualMachineScaleSets,Microsoft.Compute/virtualMachineScaleSets/virtualMachines,Microsoft.Synapse/workspaces,Microsoft.Synapse/workspaces/bigDataPools,Microsoft.Synapse/workspaces/sqlPools,Microsoft.ClassicCompute/domainNames/slots/roles,Microsoft.ClassicCompute/virtualMachines,Microsoft.SignalRService/SignalR,Microsoft.DataBoxEdge/DataBoxEdgeDevices,Microsoft.StorageCache/caches,Microsoft.Search/searchServices,Microsoft.Logic/workflows,Microsoft.Logic/integrationServiceEnvironments,Microsoft.HDInsight/clusters,Microsoft.MachineLearningServices/workspaces,Microsoft.Relay/namespaces,Microsoft.EventHub/namespaces,Microsoft.EventHub/clusters,Microsoft.Kusto/clusters,Microsoft.OperationalInsights/workspaces,Microsoft.Maps/accounts,Microsoft.DBforMariaDB/servers,Microsoft.TimeSeriesInsights/environments,Microsoft.TimeSeriesInsights/environments/eventsources,Microsoft.AppPlatform/Spring,Microsoft.DBforPostgreSQL/servers,Microsoft.DBforPostgreSQL/serversv2,Microsoft.DBforPostgreSQL/singleServers,Microsoft.StreamAnalytics/streamingjobs,Microsoft.Cdn/CdnWebApplicationFirewallPolicies,Microsoft.NotificationHubs/namespaces/notificationHubs,Microsoft.ApiManagement/service,Microsoft.Storage/storageAccounts,Microsoft.Storage/storageAccounts/blobServices,Microsoft.Storage/storageAccounts/tableServices,Microsoft.Storage/storageAccounts/queueServices,Microsoft.Storage/storageAccounts/fileServices,Microsoft.Media/mediaservices,Microsoft.Media/mediaservices/streamingEndpoints,Microsoft.ServiceFabricMesh/applications,Microsoft.DataLakeAnalytics/accounts,Microsoft.DataCatalog/datacatalogs,Microsoft.PowerBIDedicated/capacities,Microsoft.IoTSpaces/Graph,Microsoft.ClassicStorage/storageAccounts,Microsoft.ClassicStorage/storageAccounts/blobServices,Microsoft.ClassicStorage/storageAccounts/tableServices,Microsoft.ClassicStorage/storageAccounts/fileServices,Microsoft.ClassicStorage/storageAccounts/queueServices,Microsoft.AppConfiguration/configurationStores,Microsoft.Automation/automationAccounts,Microsoft.DataLakeStore/accounts,Microsoft.DataFactory/dataFactories,Microsoft.DataFactory/factories,Microsoft.NetApp/netAppAccounts/capacityPools,Microsoft.NetApp/netAppAccounts/capacityPools/volumes,Microsoft.BatchAI/workspaces,Microsoft.DataShare/accounts,Microsoft.Peering/peerings,Microsoft.Peering/peeringServices,Microsoft.StorageSync/storageSyncServices,Microsoft.StorageSync/storageSyncServices/syncGroups,Microsoft.StorageSync/storageSyncServices/syncGroups/serverEndpoints,Microsoft.StorageSync/storageSyncServices/registeredServers,Microsoft.MixedReality/spatialAnchorsAccounts,Microsoft.MixedReality/remoteRenderingAccounts,Microsoft.ContainerService/managedClusters,Microsoft.Blockchain/blockchainMembers,Microsoft.Batch/batchAccounts,Microsoft.EventGrid/eventSubscriptions,Microsoft.EventGrid/topics,Microsoft.EventGrid/domains,Microsoft.EventGrid/extensionTopics,Microsoft.EventGrid/systemTopics,Microsoft.CognitiveServices/accounts\"}"

 on ../../main.tf line 1, in resource "azurerm_monitor_metric_alert" "this":
   1: resource "azurerm_monitor_metric_alert" "this"

**Comment by yupwei68** [comment] 2020-05-11 07:33
Hi @abilous-ti , thanks for opening this issue. The metric namespace, metric name and aggregation in the code above is supported. Sorry that I can't reproduce this error with the code in azurerm 2.5.0. It shows that:
`Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`

**Comment by abilous-ti** [comment] 2020-05-21 14:22
I see that metric_namespace, metric_name, aggregation, operator and threshold are supported as these are mandatory fields for Azure Metric Alert

If you check current Microsoft official document for supported metric attributes 
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported
you won't find value microsoft.insights/webtests
The error above shows that 
"code":"BadRequest","message":"microsoft.insights/webtests is not a supported platform metric namespace

Officially supported metric_namespace value microsoft.insights/components does wort work either  
code":"BadRequest","message":"Detect invalid value: microsoft.insights/components for query parameter: 'metricnamespace', the value must be: microsoft.insights/webtests

May you please share you working code example?

**Comment by yupwei68** [comment] 2020-05-26 02:25
Hi @abilous-ti ,It's wield. you're right that `Microsoft.Insights/Components` ` availabilityResults/count` is supported from the document. And in my test, it's supported by the service team.
![image](https://user-images.githubusercontent.com/56525716/82853901-87e36380-9f39-11ea-844f-0c684e06f8c2.png)

And I could provide my code that works:
```
provider "azurerm" {
version = "2.5.0"
  features {}
}

resource "azurerm_monitor_metric_alert" "this" {
  name     = "monitor"
  resource_group_name  = "yupinsight"
  scopes              = ["/subscriptions/XXX/resourceGroups/yupinsight/providers/microsoft.insights/components/yupinsight"]
  frequency = "PT5M"
  severity = 2
  window_size = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "availabilityResults/count"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 6
  }
 
}
```

**Comment by abilous-ti** [comment] 2020-06-11 11:07
@yupwei68 I tried your code but I got an error:
The argument "action_group_id" is required, but no definition was found.

So I had to add Required Option action_group_id into resource "azurerm_monitor_metric_alert"
I tried to run the code again and azurerm_monitor_metric_alert resources was created in Azure. However there are few issues:
- Alerts are disabled in WebTest
![image](https://user-images.githubusercontent.com/22077679/84377748-cf314b80-abeb-11ea-8e3b-7d495aa10bdd.png)
- Metric Alert points to Application Insight and has wrong Condition
![image](https://user-images.githubusercontent.com/22077679/84377990-21726c80-abec-11ea-80ef-8a246eab89fd.png)


Here is the correct configuration that was created manually
- Alerts are enabled in WebTest
![image](https://user-images.githubusercontent.com/22077679/84378465-e3297d00-abec-11ea-8210-8bfafb0fd882.png)

- Metric Alert points to WebTest and has Condition "Whenever the average failed locations is greater than or equal to 6 count"
![image](https://user-images.githubusercontent.com/22077679/84378224-79a96e80-abec-11ea-888f-9bd7dc3760cb.png)

**Comment by yupwei68** [comment] 2020-06-12 03:03
Hi @abilous-ti Thanks for your comments. The PR to support `Webtest Location Availability Metric Alerts` [link](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7159) is in reviewing. Please subscribe the PR to get notified once it's merged.

**Comment by magodo** [comment] 2020-08-04 02:42
Hey @abilous-ti
 
As #7159 has been merged now, would you verify that your requirement has been met or not?

**Comment by tombuildsstuff** [comment] 2020-08-14 16:51
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if #7159 hasn't fixed this and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-08-14 16:51 UTC
Labels: enhancement, service/monitor, waiting-response
