### ISSUE TITLE
VM Managed Disk change when shutdown

### ISSUE THREAD

**Issue by mb290** [terraform-providers/terraform-provider-azurerm#921] opened 2018-03-01 23:31 UTC
Hi Everyone.

I have a VM with a managed disk which i've shutdown through the portal (debugging load balancer routing). I re-ran my TF file with an NSG change, nothing being updated in my VM and it tried to change the following:

>   ~ module.production-core.module.ProdLZEastUS2-01.azurerm_virtual_machine.VM-FW2
>       storage_os_disk.0.managed_disk_type:     "" => "Standard_LRS"

Of course this failed and here is the error code:

> * module.production-core.module.ProdLZEastUS2-01.azurerm_virtual_machine.VM-FW2: 1 error(s) occurred:
> 
> * azurerm_virtual_machine.VM-FW2: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: failed request: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Managed disk storage account type change through Virtual Machine 'ProdLZEastUS2-01-VM-FW2' is not allowed. Please update disk resource at /subscriptions/xxxxxxxxx/resourceGroups/ProdLZEastUS2-01/providers/Microsoft.Compute/disks/ProdLZEastUS2-01-VM-FW2-os_disk."

The configuration in the VM is:

```
  storage_os_disk {
    name = "${var.podName}-VM-FW1-os_disk"
    managed_disk_type = "Standard_LRS"
    caching           = "ReadWrite"
    create_option     = "FromImage"
  }
```

Let me know if you need any more details.

Thanks!

**Comment by glcx** [comment] 2018-03-15 10:33
Hi,

It looks like the issue is caused by the "STORAGE ACCOUNT TYPE" attribute not appearing when the VM is down, It tries to replace it using the VM resource but this is not permitted as the disk is already created.

**Steps to Reproduce**
Create virtual machine, stop VM, run apply again

Regards

**Comment by tombuildsstuff** [comment] 2018-04-16 12:43
hey @mb290 @glcx 

Thanks for opening this issue - apologies for the delayed response here!

This is a duplicate of #555 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one.

Thanks!

**Closed by tombuildsstuff** 2018-04-16 12:43 UTC
Labels: M1, bug, service/disks, service/virtual-machine
