### ISSUE TITLE
Adding key vault certificate causes error on a fresh deployment

### ISSUE THREAD

**Issue by atrauzzi** [terraform-providers/terraform-provider-azurerm#6956] opened 2020-05-15 16:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 - `v0.12.24`
 - `2.9.0`

### Affected Resource(s)

`azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_certificate" "environment" {
  name = "${var.project}-${var.environment}"
  key_vault_id = azurerm_key_vault.environment.id

  lifecycle {
    ignore_changes = all
  }

  certificate {
    contents = filebase64("dummy.pfx")
    password = ""
  }

  certificate_policy {

    issuer_parameters {
      name = "Unknown"
    }

    key_properties {
      exportable = true
      key_size = 2048
      key_type = "RSA"
      reuse_key = true
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }

  }

  tags = {
    orchestrator = "terraform"
    project = var.project
    environment = var.environment
    version = var.deploymentVersion
  }
}

```

### Expected Behavior

I don't get a weird error about a resource already existing from the very same deployment that created it.

### Actual Behavior

I receive the following error:

```
Error: A resource with the ID "https://MYORG-MYPROJ.vault.azure.net/certificates/MYORG-MYPROJ/bf1537dc5e254d34bd2645e8584986f5" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_certificate" for more information.

  on terraform/02-global.tf line 195, in resource "azurerm_key_vault_certificate" "environment":
 195: resource "azurerm_key_vault_certificate" "environment" {

```

### Steps to Reproduce
Try to add a certificate to a key store.

### Important Factoids
This error doesn't make sense to me as the certificate is being created by the very same deployment that I'm running.  So how can it create it and then think that the certificate it created now needs to be imported into state??

It's a long and large deployment?  I don't know if that could/would/should affect things?

**Comment by njuCZ** [comment] 2020-05-18 02:23
@atrauzzi I am sorry I did not catch you. What do you mean by "deployment"? 

This error message means there is already a certificate with the same name in the same key vault. So when you want to create it again, terraform will tell that you should import this resource

**Comment by tombuildsstuff** [comment] 2020-05-18 08:54
hi @atrauzzi 

Thanks for opening this issue

In version 2.0 of the Azure Provider we fixed a bug where resources that already existed in Azure could be "adopted" by Terraform, since Azure has Upsert API's for a lot of API's (more details can be found in #2807). This is important because whilst some Azure API's have Upsert API's - certain fields can only be changed on existing resources by deleting/re-creating these resources.

As such when attempting to "create" a resource in version 2.0 or later of the Azure Provider, we first check for the presence of an existing resource with the same Name and Resource Group in Azure - and if this exists we ask that users import this via the error you're seeing.

Since Terraform is Stateful (and tracks the State of resources in it's Statefile) - these resources which Terraform may think it can "create" (but already exist) need to be imported into the Statefile via Terraform's Import functionality.

In this instance it appears that this resource could be being created multiple times within the same configuration (eg where the name is the same) - which is why this error is being raised. As such unfortunately you’d need to check the Terraform Configuration for a duplicate resource here - which is likely the root cause of this.

Alternatively if the Statefile’s aren’t being kept around you'll need to import these existing resources into the State so that Terraform can detect changes to them - and then keep the Statefile around (for example using a Backend) - details of how to import each resource can be found in the documentation for each resource ([for example, here's how to import an App Service](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#import)) - [more details on Terraform Import can be found here](https://www.terraform.io/docs/import/index.html) - however since this is an intentional behaviour I'm going to close this issue for the moment.

Thanks!

**Closed** 2020-05-18 08:54 UTC
Labels: service/keyvault

**Comment by atrauzzi** [comment] 2020-05-18 22:54
All already indicated in my original problem description that this is happening with resources that don't already exist and are part of the deployment itself.
