### ISSUE TITLE
Destroy storage account doesn't destroy

### ISSUE THREAD

**Issue by jamie3** [terraform-providers/terraform-provider-azurerm#3217] opened 2019-04-09 15:45 UTC
I have a module which defines a storage account. This storage account is bound to a vnet. The problem is that when I execute the destroy it never finishes. Instead it times out and the storage account is never deleted. I can delete the storage account very quickly through the Azure Portal UI.

1) Create mock network first following by `terraform init`, `terraform plan` and `terraform apply`
2) Create the Test storage account from module within the Test code.
3) Destroy the Test storage account `terraform destroy`

***Test***

```
terraform {
  required_version = ">= 0.11.8"
}

provider "azurerm" {
  version = "1.24.0"
}

resource "azurerm_resource_group" "rg" {
  name     = "create-storage-account-example"
  location = "westus2"

  tags {
    application       = "ApplicationTag"
    environment       = "EnvironmentTag"
    owner             = "OwnerTag"
    implementor       = "ImplementorTag"
    decommission_date = "DecommissionDateTag"
    business_unit     = "BusinessUnitTag"
  }
}

module "storage_account" {
  source = "module/storage-account"

  storage_account_name = "testcreatestorageaccount"
  tier                 = "1"

  resource_group_name     = "${azurerm_resource_group.rg.name}"
  resource_group_location = "${azurerm_resource_group.rg.location}"

  vnet_resource_group_name = "mock-network"
  vnet_name                = "sandbox-vnet"
}
```

**Terraform Storage account module**

```
terraform {
  required_version = ">=0.11.11"
}

provider "azurerm" {
  version = "=1.24.0"
}

# Get subnet info
data "azurerm_subnet" "appl1" {
  name                 = "appl1"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "appl2" {
  name                 = "appl2"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "appl3" {
  name                 = "appl3"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "transit" {
  name                 = "transit"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "mgmtsubnet" {
  name                 = "mgmtsubnet"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "private" {
  name                 = "private"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "servicesendpoint" {
  name                 = "servicesendpoint"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "gatewaysubnet" {
  name                 = "gatewaysubnet"
  virtual_network_name = "${var.vnet_name}"
  resource_group_name  = "${var.vnet_resource_group_name}"
}

locals {
  "replication_type_map" {
    "1" = "RAGRS"
    "2" = "ZRS"
    "3" = "ZRS"
    "4" = "ZRS"
  }

  "replication_type" = "${lookup(local.replication_type_map,var.tier)}"
}

data "azurerm_resource_group" "resource_group" {
  name = "${var.resource_group_name}"
}

resource "azurerm_storage_account" "storage_account" {
  name                      = "${var.storage_account_name}"
  resource_group_name       = "${var.resource_group_name}"
  location                  = "${var.resource_group_location}"
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  access_tier               = "${var.access_tier}"
  account_replication_type  = "${local.replication_type}"
  enable_blob_encryption    = true
  enable_file_encryption    = true
  enable_https_traffic_only = true

  tags {
    application       = "${data.azurerm_resource_group.resource_group.tags["application"]}"
    environment       = "${data.azurerm_resource_group.resource_group.tags["environment"]}"
    owner             = "${data.azurerm_resource_group.resource_group.tags["owner"]}"
    implementor       = "${data.azurerm_resource_group.resource_group.tags["implementor"]}"
    decommission_date = "${data.azurerm_resource_group.resource_group.tags["decommission_date"]}"
    business_unit     = "${data.azurerm_resource_group.resource_group.tags["business_unit"]}"
    tier              = "${var.tier}"
  }

  network_rules {
    ip_rules                   = ["198.84.14.0/24", "198.84.15.0/24"]
    virtual_network_subnet_ids = ["${data.azurerm_subnet.appl1.id}", "${data.azurerm_subnet.appl2.id}", "${data.azurerm_subnet.appl3.id}", "${data.azurerm_subnet.transit.id}", "${data.azurerm_subnet.mgmtsubnet.id}", "${data.azurerm_subnet.private.id}", "${data.azurerm_subnet.servicesendpoint.id}", "${data.azurerm_subnet.gatewaysubnet.id}"]
  }
}
```

**Mock network**

```
# Mock network to ensure the storage account works
locals {
  resource_group_name              = "mock-network"
  location                         = "westus2"
  vnet_name                        = "sandbox-vnet"
  dns_servers                      = []
  vnet_address                     = ["10.158.32.0/19"]
  gateway_subnet_address_prefix    = "10.158.57.64/26"
  appl1_address_prefix             = "10.158.32.0/21"
  appl2_address_prefix             = "10.158.40.0/21"
  appl3_address_prefix             = "10.158.48.0/21"
  transit_address_prefix           = "10.158.57.128/26"
  mgmt_subnet_address_prefix       = "10.158.57.0/26"
  private_address_prefix           = "10.158.58.0/24"
  services_endpoint_address_prefix = "10.158.56.0/24"

  service_endpoints = ["Microsoft.Storage", "Microsoft.EventHub", "Microsoft.KeyVault"]
}

resource "azurerm_resource_group" "rg" {
  name     = "${local.resource_group_name}"
  location = "${local.location}"

  tags {
    application       = "ApplicationTag"
    environment       = "EnvironmentTag"
    owner             = "OwnerTag"
    implementor       = "ImplementorTag"
    decommission_date = "DecommissionDateTag"
    business_unit     = "BusinessUnitTag"
  }
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${local.vnet_name}"
  address_space       = "${local.vnet_address}"
  dns_servers         = "${local.dns_servers}"
  location            = "${local.location}"
  resource_group_name = "${local.resource_group_name}"

  depends_on = ["azurerm_resource_group.rg"]
}

resource "azurerm_subnet" "gatewaysubnet" {
  name                 = "gatewaysubnet"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.gateway_subnet_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "appl1" {
  name                 = "appl1"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.appl1_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "appl2" {
  name                 = "appl2"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.appl2_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "appl3" {
  name                 = "appl3"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.appl3_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "transit" {
  name                 = "transit"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.transit_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "mgmtsubnet" {
  name                 = "mgmtsubnet"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.mgmt_subnet_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "private" {
  name                 = "private"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.private_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

resource "azurerm_subnet" "servicesendpoint" {
  name                 = "servicesendpoint"
  resource_group_name  = "${local.resource_group_name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  address_prefix       = "${local.services_endpoint_address_prefix}"
  service_endpoints    = "${local.service_endpoints}"

  depends_on = ["azurerm_virtual_network.vnet"]
}

```

**Comment by Lucretius** [comment] 2019-04-09 16:18
This looks pretty similar to https://github.com/terraform-providers/terraform-provider-azurerm/issues/3156. I wonder if the networking rules are causing deletion issues.

**Comment by tombuildsstuff** [comment] 2019-04-23 09:43
hey @jamie3 

Thanks for opening this issue :)

As @Lucretius has mentioned this appears to be a duplicate of #3156 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to that one for updates?

Thanks!

**Closed by tombuildsstuff** 2019-04-23 09:43 UTC

**Comment by jamie3** [comment] 2019-04-24 16:19
Thanks tom
