### ISSUE TITLE
Support for azurerm_integration_service_environment

### ISSUE THREAD

**Issue by jbinko** [terraform-providers/terraform-provider-azurerm#7492] opened 2020-06-25 14:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support in Terraform for: Integration Service Environment (ISE) / Azure Logic Apps
<https://docs.microsoft.com/en-us/azure/logic-apps/ise-manage-integration-service-environment>
<https://docs.microsoft.com/en-us/azure/templates/microsoft.logic/integrationserviceenvironments#IntegrationServiceEnvironmentAccessEndpoint>

Will also initiate implementation based on the specification discussed and described here. Please provide feedback! Implementation self assigned to me @jbinko .

### New or Affected Resource(s)

* azurerm_integration_service_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "exampleRG1"
  location = "westeurope"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/22"]
}

resource "azurerm_subnet" "isesubnet1" {
  name                 = "isesubnet1"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.0/26"
}

resource "azurerm_subnet" "isesubnet2" {
  name                 = "isesubnet2"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.64/26"
}

resource "azurerm_subnet" "isesubnet3" {
  name                 = "isesubnet3"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.128/26"
}

resource "azurerm_subnet" "isesubnet4" {
  name                 = "isesubnet4"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.192/26"
}

resource "azurerm_integration_service_environment" "example" {
  name     = "example-ise"
  location = azurerm_resource_group.example.location
  sku_name = "Developer"
  capacity = 0

  access_endpoint_type = "Internal"
  virtual_network_subnet_ids = [
    azurerm_subnet.isesubnet1.id,
    azurerm_subnet.isesubnet2.id,
    azurerm_subnet.isesubnet3.id,
    azurerm_subnet.isesubnet4.id
  ]

  endpoint_workflow {
    outgoing_ip_addresses        = "52.23.25.3,52.143.43.12"
    access_endpoint_ip_addresses = "52.143.43.12,52.143.43.17"
  }

  endpoint_connector {
    outgoing_ip_addresses        = "52.23.25.3,52.143.43.12"
    access_endpoint_ip_addresses = "52.143.43.12,52.143.43.17"
  }

  tags = {
    environment = "development"
  }
}
```

### References

* Linking with similar request - #7394

**Comment by tombuildsstuff** [comment] 2020-06-25 14:09
hi @jbinko 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7394 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7394 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-25 14:09 UTC
