### ISSUE TITLE
azurerm_windows_virtual_machine: Change of license_type should not force new resource

### ISSUE THREAD

**Issue by NilsBusche** [terraform-providers/terraform-provider-azurerm#7409] opened 2020-06-19 08:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
terraform-provider-azurerm_v2.12.0

### Affected Resource(s)

* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine" "instance" {

[...]

  license_type = "None"

[...]

}
```

### Expected Behavior

Changing attribute `license_type` should be an in-place update and should work online. 
Azure CLI and Azure Portal allow changing this without replacement of VM.

### Actual Behavior

Changing attribute `license_type` forces new resource to be created:
`~ license_type               = "None" -> "Windows_Client" # forces replacement`

### Steps to Reproduce

1. Create `azurerm_windows_virtual_machine` with `license_type = "None"`
2. `terraform apply`
3. Change `license_type` to `Windows_Client`
4. `terraform plan` / `terraform apply`

### Important Factoids

Changing without recreation is possible using Azure built-in features.

**Comment by ArcturusZhang** [comment] 2020-06-22 02:17
Hi @NilsBusche thanks for this issue!

Taking a look through this appears to be a duplicate of #7192 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7192 for updates?

Thanks!

**Closed by ArcturusZhang** 2020-06-22 02:17 UTC
Labels: service/virtual-machine
