### ISSUE TITLE
Support for using attached SO disk in new azurerm_linux_virtual_machine resource

### ISSUE THREAD

**Issue by jmvictoria** [terraform-providers/terraform-provider-azurerm#9806] opened 2020-12-10 14:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi guys. 

I've seen in latest version documentation that azurerm_virtual_machine was frozen in favour of the novel resources azurerm_linux_virtual_machine and azurerm_windows_virtual_machine.

Are you planning to remove completely this old resource at any term?

I'm currently using (and planning to use massively) terraform to save Azure linux virtual machine instance disks with azure snapshot using a developed terraform module to create (recover) a server instance attaching managed disk copies of those snapshots. This is the only way I know to re-create a trusted server instance state without having to generalize it and create an Azure instance image, thus avoiding the generalization changes to the system (using Azure services and avoiding the use of external tools).

This is a full server backup process for retired virtual machines enabling the possibility of restoring to operation with minimal effort and reduced costs, maintaining only the disk snapshots in Azure (deleting server resources).

In case you are planning the final elimination of the old azurerm_virtual_machine resource, it's there any way to maintain storage_os_disk object features (managed_disk_id) in the novel resources?

### New or Affected Resource(s)

* azurerm_linux_virtual_machine

### References

* azurerm_virtual_machine: [ref1](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine) 

* azurerm_linux_virtual_machine: [ref2](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine)

**Comment by tombuildsstuff** [comment] 2020-12-10 15:16
hi @jmvictoria 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8195 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8195 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-12-10 15:16 UTC
Labels: duplicate, enhancement, service/virtual-machine
