### ISSUE TITLE
azurerm_recovery_services_protected_vm times out since 1.36.0

### ISSUE THREAD

**Issue by sasan-hashemi** [terraform-providers/terraform-provider-azurerm#4770] opened 2019-10-31 04:44 UTC
Since the azurerm provider upgrade to 1.36.0, I get the following change plan:
```
  ~ resource "azurerm_recovery_services_protected_vm" "protect_vm" {
      ~ backup_policy_id    = "/subscriptions/***/resourcegroups/us-v1-rg/providers/microsoft.recoveryservices/vaults/eastus-da-v1-recovery-vault/backupPolicies/eastus-da-v1-policy-vm" -> "/subscriptions/***/resourceGroups/us-v1-rg/providers/Microsoft.RecoveryServices/vaults/eastus-da-v1-recovery-vault/backupPolicies/eastus-da-v1-policy-vm"
        id                  = "/subscriptions/***/resourceGroups/us-v1-rg/providers/Microsoft.RecoveryServices/vaults/eastus-da-v1-recovery-vault/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;us-v1-rg;eastus-da-v1-vm/protectedItems/VM;iaasvmcontainerv2;us-v1-rg;eastus-da-v1-vm"
        recovery_vault_name = "eastus-da-v1-recovery-vault"
        resource_group_name = "us-v1-rg"
        source_vm_id        = "/subscriptions/***/resourceGroups/us-v1-rgproviders/Microsoft.Compute/virtualMachines/eastus-da-v1-vm"
        tags                = {}
    }
```

However, It times out after 30 minutes and it fails. 
```
    Error: Error waiting for the Recovery Service Protected VM "VM;iaasvmcontainerv2;us-v1-rg;eastus-da-v1-vm" to be true (Resource Group "us-v1-rg") to provision: timeout while waiting for state to become 'Found' (last state: 'NotFound', timeout: 30m0s)
```
It seems like there is a typo of microsoft.recoveryservices to Microsoft.RecoveryServices

**Comment by tombuildsstuff** [comment] 2019-10-31 11:32
hi @sasan-hashemi 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4774 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4774 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-10-31 11:32 UTC
Labels: duplicate, service/recovery-services, upstream-microsoft
