### ISSUE TITLE
Support for User Managed Identities into azurerm_app_configuration resource 

### ISSUE THREAD

**Issue by Cedric-Bravo** [terraform-providers/terraform-provider-azurerm#10025] opened 2020-12-31 14:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

For High availability purpose we need User Managed Identities support (Same way as Application Gateway).

To deploy a higly available App Configuration Service, you have to deploy a secondary instance into a paired region.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-disaster-recovery?tabs=core2x

Failover between the configuration store is managed by connexion string into the code.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-disaster-recovery?tabs=core2x#failover-between-configuration-stores

Using the same Managed Identities for the replicated App configuration instance will ease management and keep it simple to handle complete automation.

### New or Affected Resource(s)

resource "azurerm_app_configuration" 

identity block must accept "UserAssigned" type and user managed identity id "identity_ids"

### Potential Terraform Configuration

```
resource "azurerm_user_assigned_identity" "UMI1" {
    name                = "UMI-NAME"
    resource_group_name = var.resource_group
    location            = "westeurope"

}

resource "azurerm_app_configuration" "appconf" {
  name                = "AppConfigurationName"
  resource_group_name = var.resource_group
  location            = "westeurope"
  
   identity{
     type           = "UserAssigned"
     identity_ids   = [azurerm_user_assigned_identity.UMI1.id]
   } 
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-01-04 09:04
hi @Cedric-Bravo 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8177 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8177 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-01-04 09:04 UTC
Labels: duplicate, enhancement, service/app-configuration

**Comment by Cedric-Bravo** [comment] 2021-01-04 09:16
Absolutely.
Thanks !
