### ISSUE TITLE
Enable the AGIC add-on in existing AKS cluster with existing Application Gateway

### ISSUE THREAD

**Issue by retheshnair** [terraform-providers/terraform-provider-azurerm#8864] opened 2020-10-13 04:41 UTC
### Description

Enable the AGIC add-on in existing AKS cluster with existing Application Gateway

### New or Affected Resource(s)

AKS Cluster and Application Gateway

### Potential Terraform Configuration

addon_profile {
    ingress_controller_addon_applicationgateway {
      id_appgateway = the id of the application gateway
	  new or exisiting
}

**Comment by neilfromit** [comment] 2020-10-13 22:52
Duplicate of [7384?](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7384)

Thumbs up on the syntax though.

**Comment by tombuildsstuff** [comment] 2020-10-26 11:36
hi @retheshnair 

Thanks for opening this issue :)

Taking a look through as @neilfromit has mentioned this appears to be a duplicate of #7384 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7384 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-26 11:36 UTC
