### ISSUE TITLE
enforce_private_link_service_network_policies should be disable_private_link_service_network_policies

### ISSUE THREAD

**Issue by bentterp** [terraform-providers/terraform-provider-azurerm#6334] opened 2020-04-02 06:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.3.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

I create a subnet as normal, and according to the documentatation `enforce_private_link_endpoint_network_policies` has a default value of false and I should set it to `true` if I want to use private link - which I don't in this case.
But the Azure service I wish to try doesn't deploy and complains, so I look in the docs and reread that I should 
"disable network policies for Private Link Service on your virtual network and subnets." so I do that using the CLI and then do "terraform plan" and now TF wants to roll back my change.

It looks as if things are simply the wrong way around.

### Expected Behavior

Nothing

### Actual Behavior
```
  # module.nwk.azurerm_subnet.subnets["OCPworker"] will be updated in-place
  ~ resource "azurerm_subnet" "subnets" {
        address_prefix                                 = "10.141.20.64/27"
        enforce_private_link_endpoint_network_policies = false
      ~ enforce_private_link_service_network_policies  = true -> false
```

### Steps to Reproduce

1 Create a subnet with Terraform
2 Disable network policies for Private Link Service  using Azure CLI: `az network vnet subnet update 
  -g $RESOURCEGROUP --vnet-name $VNET -n $SUBNET --disable-private-link-service-network-policies true`
3 Check the plan

### References

* #0000

**Comment by elsesiy** [comment] 2020-04-03 16:53
I second this issue, if you set it to `true` the plan output wants to change it to `false` and the other way around. It's never unchanged. I'm also a bit confused when this value should be actually set to `true`. Simply when I use any type of `ServiceEndpoint`?

**Comment by MarkPerry24** [comment] 2020-05-13 19:50
> I second this issue, if you set it to `true` the plan output wants to change it to `false` and the other way around. It's never unchanged. I'm also a bit confused when this value should be actually set to `true`. Simply when I use any type of `ServiceEndpoint`?

This is for private service links not service endpoints.  
This is a pretty good succinct explanation:  https://sameeraman.wordpress.com/2019/10/30/azure-private-link-vs-azure-service-endpoints/

A service endpoint allows you access the resource on the azure network without going onto the internet but the resource itself is still public (so many people think it isn't when it is though you can limit access) and your network is still subject to NSG ip rules.  A private service link not only makes the resource accessible over a private ip address but ensures it can only be reached via that private ip address.  It works as a pair.  The private service link can be to a number of resources provided by Microsoft (you don't need to create the private service link as it already exists implicitly which is slightly confusing I guess) but can also be your own service hosted on a VM for instance for which you would create a private service link connection for.  The network you want to reach from requires a "private endpoint" which is basically a virtual network card acting as a point-2-point connection.  Your resources connect to the address space provided by this network interface and it's as though that is a physical network card plugged directly into the resource itself and sitting on your network.  NSG is not compatible with this networking as it's out of the normal flow.

**Comment by WodansSon** [comment] 2020-05-15 01:33
@bentterp. hello and thank you for opening this issue. The reason you are seeing terraform wanting to revert your change is because you used a tool to update the configuration of your subnet outside of terraform and the configuration file still has the `enforce_private_link_service_network_policies` set to `false`, which is the expected behavior for terraform and would be by design.

@elsesiy, the `enforce_private_link_service_network_policies` should only ever be set when you are attempting to connect to a `azurerm_private_link_service`. You can see an example of how to correctly author the HCL file in the examples section for the [private link service](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/private-endpoint/private-link-service)

> **NOTE:** If you are attempting to attach a `azurerm_private_endpoint` to an existing resources **Azure PaaS Services** (for example a Azure Storage account or a SQL Database) you do not need to set the `enforce_private_link_service_network_policies` attribute. You can see an example of that configuration in the examples section for [postgreSQL](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/private-endpoint/postgresql)

Below is the typical configuration for the network portion of deploying a `azurerm_private_endpoint` that connects to a `azurerm_private_link_service`, notice that the service and the endpoint both need their own **separate** subnets but can share a single virtual network:

```
resource "azurerm_virtual_network" "example" {
  name                = "${var.prefix}-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "service" {
  name                 = "service"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.0/24"

  enforce_private_link_service_network_policies = true
}

resource "azurerm_subnet" "endpoint" {
  name                 = "endpoint"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.2.0/24"

  enforce_private_link_endpoint_network_policies = true
}
```
Unless you have any further questions I am going to go ahead and close this issue, if I did not answer your questions fully feel free to reopen this issue and thanks again for reaching out. 🚀

**Closed by WodansSon** 2020-05-15 01:33 UTC
Labels: question, service/private-link
