### ISSUE TITLE
Error checking if CosmosDB Account 'XX' already exists

### ISSUE THREAD

**Issue by ryanpray** [terraform-providers/terraform-provider-azurerm#7199] opened 2020-06-03 20:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform v0.12.16`
* `provider.azurerm v2.12.0`

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "cosmosdbaccount" {
  name                = "cosmosdb-ryantest-${var.env}"
  location            = var.location
  resource_group_name = var.rg_name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = true

  consistency_policy {
    consistency_level       = "Session"
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }
}
```

### Expected Behavior

The Azure Cosmos DB Account should have been created.

### Actual Behavior

Terraform returned the error: Error checking if CosmosDB Account 'XX' already exists.  This seems similar to the error that is linked before.

1. `terraform apply`

### References

* #3739

**Comment by tombuildsstuff** [comment] 2020-06-04 05:50
Duplicate of #7173 - the cause of this is a bug in the Azure API for which a fix has been merged and will be released in v2.13

**Closed by tombuildsstuff** 2020-06-04 05:50 UTC
Labels: duplicate, service/cosmosdb, upstream-microsoft
