### ISSUE TITLE
Issue with Enhanced Validation for Locations

### ISSUE THREAD

**Issue by TheHodge1234** [terraform-providers/terraform-provider-azurerm#8160] opened 2020-08-18 15:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

 0.13, 2.20+

### Affected Resource(s)

* azurerm_resource_group (all are affected)

### Terraform Configuration Files

```hcl
provider "azurerm" {
    version = "=2.23.0"
    features {}
}

terraform {
    backend "azurerm" {}
}

# Create resource group
resource "azurerm_resource_group" "example" {
    lifecycle {
        prevent_destroy = true
    }
    name     = examplerg
    location = southindia
}
```

### Expected Behavior

southindia ought to be supported as this is the correct name as per the dns names in azure i.e. exampleIP.southindia.cloudapp.azure.com

### Actual Behavior

Error: "southindia" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,indiasouth,indiawest,indiacentral,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast"

### Steps to Reproduce

Attempt to create any resource with 'southindia' or 'centralindia'. 

### References

There are some work arounds for this - 

1) Set the environment variable ARM_PROVIDER_ENHANCED_VALIDATION to false - but i dont think the entry is incorrect so dont see why this should be required
2) Delete and recreate the existing resources using indiasouth rather than southindia - troublesome as any delete task is.  

* #0000

**Comment by tombuildsstuff** [comment] 2020-08-18 16:06
hi @TheHodge1234 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7906 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7906 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-18 16:06 UTC
