### ISSUE TITLE
Error retrieving the AuthSettings for App Service

### ISSUE THREAD

**Issue by mathcantin** [terraform-providers/terraform-provider-azurerm#5829] opened 2020-02-20 15:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v0.12.20
* AzureRM Provider version: 1.44.0

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "appservice" {
  for_each = toset(local.apps)

  name                = each.value
  location            = local.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = azurerm_app_service_plan.appserviceplan.id

  site_config {
    dotnet_framework_version = "v4.0"
    scm_type                 = "LocalGit"
  }
}
```

### Description / Feedback

Since today we have this error on any plan or apply:

`Error: Error retrieving the AuthSettings for App Service "xxx-api-prod-as" (Resource Group "xxxx"): web.AppsClient#GetAuthSettings: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxx' with object id 'xxxxx' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Web/sites/xxxx-api-prod-as/config/authsettings' or the scope is invalid. If access was recently granted, please refresh your credentials."`

Yesterday, we have no problem with the exact same thing. I grant the owner permission to terraform on these resources and we still have the issue. It's more like the api call changed.

**Comment by lrxtom2** [comment] 2020-09-24 12:33
Hi @mathcantin , Thanks for opening the issue! After the new version Provider was released, I couldn't reproduce your issue at this time. Could you please try that to use the latest version to confirm the issue is still reproduced? Thanks.

**Comment by tombuildsstuff** [comment] 2020-09-24 15:30
👋 

Since this is a permissions issue I'm going to close this issue for the moment - but should you still be having issues you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-09-24 15:30 UTC
Labels: bug, service/app-service
