### ISSUE TITLE
Terraform apply errors with 404 when creating multiple auth rules for event hubs

### ISSUE THREAD

**Issue by danieldekock-wintech** [terraform-providers/terraform-provider-azurerm#4893] opened 2019-11-15 11:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.15
provider.azurerm v1.36.0

### Affected Resource(s)

* `azurerm_eventhub_authorization_rule`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=1.36.0"
}

resource "azurerm_resource_group" "rg-debug" {
  name = "rg-debug"
  location = "North Europe"
}

resource "azurerm_eventhub_namespace" "ehns-debug" {
  name = "ehns-debug"
  location = "North Europe"
  resource_group_name = azurerm_resource_group.rg-debug.name
  sku = "Standard"
  capacity = 1
}

resource "azurerm_eventhub" "eh-debug" {
  name = "eh-debug"
  namespace_name = azurerm_eventhub_namespace.ehns-debug.name
  resource_group_name = azurerm_resource_group.rg-debug.name
  partition_count = 2
  message_retention = 1
}

variable "auth-rules" {
  type    = list(string)
  default = ["rule1", "rule2", "rule3", "rule4", "rule5"]
}

resource "azurerm_eventhub_authorization_rule" "eh-rule" {
  for_each = toset(var.auth-rules)
  name = each.key
  namespace_name = azurerm_eventhub_namespace.ehns-debug.name
  eventhub_name = azurerm_eventhub.eh-debug.name
  resource_group_name = azurerm_resource_group.rg-debug.name
  listen = false
  send = true
  manage = false
}
```

### Debug Output

https://gist.github.com/danieldekock-wintech/32e94d5f90def9372951bfef963aa1d5

### Panic Output

None

### Expected Behavior

Terraform apply should create all the authorization rules for the event hub

### Actual Behavior

Terraform apply does not create all authorization rules and errors with a 404 that the authorization rules doesn't exists. e.g.

```
Error: eventhub.EventHubsClient#GetAuthorizationRule: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The requested resource rule4 does not exist. CorrelationId: 9d7b8524-4
7a5-eabe-bd57-fe3960951970"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

A similar issue has been reported for resource "azurerm_notification_hub_authorization_rule"
https://github.com/terraform-providers/terraform-provider-azurerm/pull/4087

* #0000

**Comment by RavulaChetan** [comment] 2020-01-10 03:20
Any Update on this? 
I am not sure if this issue is because of creating multiple auth rules. i am seeing this error even when having a depends_on creating one authrule at a time.
Auth rule seems to be created but still errors out with 404 error code.

I am using azurerm 1.35 version which should have the fix from #4087, but does seem like the issue is resolved.

**Comment by tombuildsstuff** [comment] 2020-01-10 10:32
@RavulaChetan #4087 fixed this in the Notification Hubs resource, not in the EventHub resources - which is what this issue is (open) tracking

**Comment by RavulaChetan** [comment] 2020-01-10 16:56
Thanks @tombuildsstuff for the clarification.
Is there any estimate on when this will be resolved for event hub?

**Comment by nickmhankins** [comment] 2020-04-09 20:57
We are also running into this issue.  It seems to happen intermittently.

```hcl
Error: eventhub.EventHubsClient#GetAuthorizationRule: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The requested resource ListenSendSharedAccessKey does not exist"

  on eventhubs.tf line 23, in resource "azurerm_eventhub_authorization_rule" "listener_accesskey":

  23: resource azurerm_eventhub_authorization_rule listener_accesskey {

Error: eventhub.EventHubsClient#GetAuthorizationRule: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The requested resource SendSharedAccessKey does not exist"


  on eventhubs.tf line 35, in resource "azurerm_eventhub_authorization_rule" "sender_accesskey":

  35: resource azurerm_eventhub_authorization_rule sender_accesskey {

```

**Comment by lukazeta** [comment] 2020-04-12 20:24
> Is there any current workaround for this?

since there is no retry mechanism, I've added ugly 5min sleep in between rules that appear to work(I did see this error with lower time on occasion). 

```
provisioner "local-exec" {
  command = "echo sleep 300s; sleep 300"
}
```

**Comment by lukazeta** [comment] 2020-04-14 07:18
I've eventually hit this error again with sleep. Thats when I noticed that all the rules are being deployed at once. I've chained them using dependencies instead and so far didnt hit this again.

**Comment by tombuildsstuff** [comment] 2020-04-14 09:26
Ultimately this'll be fixed via a lock when creating/updating/deleting EventHub (& Namespace) Auth Rules - as per #4087 - but in the interim it should be possible to use Terraform's parallelism feature to work around this (although clearly that's not ideal for speed reasons)

**Comment by nickmhankins** [comment] 2020-04-29 22:29
@tombuildsstuff I've submitted a pull request to fix the issue here:
https://github.com/terraform-providers/terraform-provider-azurerm/pull/6701

Thanks

**Comment by jacksinclairaudley** [comment] 2020-04-30 15:36
Would this also affect azurerm_servicebus_queue_authorization_rule? We are seeing the same error when creating multiple of these.

**Comment by nickmhankins** [comment] 2020-04-30 16:21
@jacksinclairaudley No, just event_hub.  I'd open a separate issue for servicebus auth rules.

**Closed** 2020-05-06 18:30 UTC
Labels: bug, good first issue, service/event-hubs

**Comment by AntonChernysh** [comment] 2020-05-27 11:18
this still doesn't work in 2.10.0
