### ISSUE TITLE
azurerm_app_service IP restrictions

### ISSUE THREAD

**Issue by dan-gibbons** [terraform-providers/terraform-provider-azurerm#4399] opened 2019-09-20 11:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Using Terraform v0.12.8

```
provider "azurerm" {
  version = "=1.34.0"
}
```

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```
resource "azurerm_app_service" "web_service" {
  name                = "${var.name}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  app_service_plan_id = "${var.app_service_plan_id}"
  https_only          = true
  enabled             = true

  site_config {
    dotnet_framework_version = "v4.0"
    min_tls_version          = "1.2"
    always_on                = true
    ftps_state = "Disabled"
    virtual_network_name = "${var.virtual_network_name}"
    
    ip_restriction = [
      for ip in var.whitelisted_ips : {
        ip_address = ip
        subnet_mask = "255.255.255.255"
      }
    ]
  }

  logs {
    http_logs {
      file_system {
        retention_in_days = 30
        retention_in_mb   = 100
      }
    }
  }

  tags = var.tags
}
```

### Expected Behavior

This should create access restrictions for the IPs in the list variable "var.whitelisted_ips"

According to https://www.terraform.io/docs/providers/azurerm/r/app_service.html either the 'ip_address' or the 'virtual_network_subnet_id' should be specified.

**NOTE: This does work with AzureRM provider v1.33.1**

### Actual Behavior

Terraform apply fails with following error message

>   on ..\..\modules\web-app\main.tf line 16, in resource "azurerm_app_service" "web_service":
>   16:     ip_restriction = [
> 
> Inappropriate value for attribute "ip_restriction": element 0: attribute
> "virtual_network_subnet_id" is required.
>
>ERROR: Terraform apply failed with exit code 1

### Steps to Reproduce

1. `terraform apply`

### References

* #4184

**Comment by tombuildsstuff** [comment] 2019-09-22 19:55
hi @dan-gibbons 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4383 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4383 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-22 19:55 UTC
Labels: bug, service/app-service

**Comment by dan-gibbons** [comment] 2019-09-23 08:54
Cheers Tom,

Sorry I didn't see #4383 - I'll follow that instead
