### ISSUE TITLE
AKS recreating after each plan&apply - change in azure api for windows profile username forces recreation

### ISSUE THREAD

**Issue by Cyanopus** [terraform-providers/terraform-provider-azurerm#6294] opened 2020-03-30 09:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

image: hashicorp/terraform:0.12.24

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Description

It seems that Azure has changed its API behavior for windows profile options in the AKS which is introducing breaking constant recreation of the AKS resource.

Previously you could specify only one of the two blocks:

```hcl
  linux_profile {
    admin_username = var.admin_username

    ssh_key {
      key_data = var.ssh_public_key
    }
  }
```
or
```hcl
  windows_profile {
    admin_username = var.win_admin_username
    admin_password = var.win_admin_password
  }
```
I would assume that this was to specify the OS of the default node pool as this option is no longer part of it as it was with the agent node pool where you had (os: Linux or Windows). So at a time in 0.42 we just skipped the windows_profile block as it's of no use and no essential for entirely Linux nodes.
For one week now, however, we get the following nice effect:
- Whenever a cluster is created and this block is missing ( left to the provider ) after the creation of the cluster the terraform diff ( plan & apply) detects that this parameter is now changed to azureuser by the cloud provider and naturally it detects that the null that is coming from the provider is not the same as the "behind the scenes" provider set of azureuser. This forces the cluster to be re-creatable in each run after provision.
Here is the output:
```hcl
...
      - windows_profile {
          - admin_username = "azureuser" -> null # forces replacement
        }
```
This azureuser is created by Azure after the cluster is provisioned with terraform which causes each next plan and runs to want to recreate the cluster as this change forces replacement.

### New or Affected Resource(s)
This is affecting only newly created resources. The old resources act as expected. When you don't have such a block it is not complaining of changes. I guess that the service is provisioned with templated at the backend and each resource has specific bindings to specific API version at the backend so this is not a hit in the old resources. 

### Expected Behavior

When Windows profile parameters are missing from the resource those should not be magically associated as changed after the next plan goes.

### Actual Behavior

When new AKS is provisioned with terraform after the provision windows profile admin username magically appears as azureuser without anywhere requested.

### Steps to Reproduce

1. Create new resource of kubernetes cluster and don't specify Windows Profile block. Apply twice and check.

* #0000

**Comment by tombuildsstuff** [comment] 2020-03-30 10:56
hi @Cyanopus 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6235 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6235 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-03-30 10:56 UTC
