### ISSUE TITLE
azurerm_logic_app_workflow parameters {} $connection for APIConnection

### ISSUE THREAD

**Issue by szferle** [terraform-providers/terraform-provider-azurerm#9222] opened 2020-11-09 17:29 UTC
### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
+ provider registry.terraform.io/hashicorp/azurerm v2.33.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Affected Resource(s)
* `azurerm_logic_app_workflow`

### Terraform Configuration Files

```
resource "azurerm_logic_app_workflow" "lapp-test" {
  name                = "lapp-test"
  location            = data.azurerm_resource_group.rgrp-test.location
  resource_group_name = data.azurerm_resource_group.rgrp-test.name
  parameters          = {
    "$connections" = <<EOF
      {
        "office365" = [
          {
            "connectionId"    = "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/rgrp-test/providers/Microsoft.Web/connections/office365"
            "connectionName"  = "office365"
            "id"              = "/subscriptions/11111111-1111-1111-1111-111111111111/providers/Microsoft.Web/locations/westus2/managedApis/office365"
          }
        ]
      }
    EOF
  }
}
```

### Debug Output
`Error: [ERROR] Error creating Logic App Workflow "lapp-test" (Resource Group "rgrp-twa1-it-malidor"): logic.WorkflowsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="The template validation failed: 'The workflow parameters '$connections' are not valid; they are not declared in the definition and therefore cannot be provided. The only declared parameters for this definition are ''.'."`

### Expected Behavior

`Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`

### Actual Behavior

We are not able to provision the logic workflow (logic app) resource with APIConnection.
$connection in parameters {} cant be filled properly. The APIConnection should refer to it as     
```
        "host": {
            "connection": {
                "name": "@parameters('$connections')['office365']['connectionId']"
            }
        }
```
And in an already logic app the parameters par looks like:
```
    "parameters": {
        "$connections": {
            "value": {
                "office365": {
                    "connectionId": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/rgrp-test/providers/Microsoft.Web/connections/office365",
                    "connectionName": "office365",
                    "id": /subscriptions/11111111-1111-1111-1111-111111111111/providers/Microsoft.Web/locations/westus2/managedApis/office365"
                }
            }
        }
    }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #4731
* #1691

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tombuildsstuff** [comment] 2020-11-09 17:51
hi @szferle 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1691 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1691 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-11-09 17:51 UTC
Labels: duplicate, service/logic
