### ISSUE TITLE
Azure virtual machine extension timeout and create empty extension

### ISSUE THREAD

**Issue by alk-rniveau** [terraform-providers/terraform-provider-azurerm#3449] opened 2019-05-15 14:52 UTC
### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.13
+ provider.azurerm v1.27.1
+ provider.dns v2.1.1
+ provider.null v2.1.2
```

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "vm-omsagent-extension" {
  name                       = "hostname"
  location                   = "${var.azure_location}"
  publisher                  = "Microsoft.EnterpriseCloud.Monitoring"
  resource_group_name        = "hostname.rg-name"
  type                       = "OmsAgentForLinux"
  type_handler_version       = "1.9"
  auto_upgrade_minor_version = "true"
  virtual_machine_name       = "hostname"
  settings                   = "{ \"workspaceId\": \"${logs-workspace.workspace_id}\"}"
  protected_settings         = "{\"vmResourceId\": \"hostname\", \"workspaceKey\": \"${logs-workspace.workspace_primary_key}\"}"
}

resource "azurerm_resource_group" "logs-rg" {
  name     = "logs-rg"
  location = "${var.azure_location}"
}

resource "azurerm_log_analytics_workspace" "log-workspace" {
  name                = "log-workspace"
  location            = "${var.azure_location}"
  resource_group_name = "${azurerm_resource_group.logs-rg.name}"
  sku                 = "PerGB2018"
  retention_in_days   = 30
}
```

### Debug Output

https://gist.github.com/alk-rniveau/acc0e89319d8860a95f8efcd50d601a6

### Expected Behavior

Have a extension setup and running on the virtual machine

### Actual Behavior

Terraform timeout and I have an empty extension on the azure portal (can see with picture)

### Steps to Reproduce

1. `terraform apply`
<img width="299" alt="Capture d’écran 2019-05-15 à 15 50 24" src="https://user-images.githubusercontent.com/50457177/57781625-dfe26a00-772a-11e9-898f-9f212ddcc4ee.png">

**Comment by tombuildsstuff** [comment] 2019-05-16 13:38
hi @alk-rniveau 

Thanks for opening this issue :)

Taking a look into this this appears to be a duplicate of https://github.com/hashicorp/go-azure-helpers/issues/22 - as such I'm going to close this in favour of that issue, please subscribe to that issue for updates.

Thanks!

**Closed by tombuildsstuff** 2019-05-16 13:38 UTC
