### ISSUE TITLE
azurerm_virtual_machine_extension timeout value is not honored

### ISSUE THREAD

**Issue by pessimism** [terraform-providers/terraform-provider-azurerm#8037] opened 2020-08-06 19:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.29 and 2.21.0

### Affected Resource(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

resource "azurerm_virtual_machine_extension" "sql1_extension" {
  name                 = "sql1_prepare"
  depends_on           = [module.sql1.domainJoinID]
  virtual_machine_id   = module.sql1.vm[0].id
  publisher               = "Microsoft.Powershell"
  type                    = "DSC"
  type_handler_version    = "2.80"
  **timeouts {
    create = "2h"**
    delete = "10m"
  }
  settings = <<SETTINGS
            {

### Debug Output

azurerm_virtual_machine_extension.sql1_extension: Still creating... [1h36m15s elapsed]
azurerm_virtual_machine_extension.sql1_extension: Still creating... [1h36m25s elapsed]
azurerm_virtual_machine_extension.sql1_extension: Still creating... [1h36m35s elapsed]
azurerm_virtual_machine_extension.sql1_extension: Still creating... [1h36m45s elapsed]
azurerm_virtual_machine_extension.sql1_extension: Still creating... [1h36m55s elapsed]
azurerm_virtual_machine_extension.sql1_extension: Still creating... [1h37m5s elapsed]
azurerm_virtual_machine_extension.sql1_extension: Still creating... [**1h37m15s** elapsed]
System.Management.Automation.RemoteException
Error: Code="VMExtensionProvisioningTimeout" Message="**Provisioning of VM extension sql1_prepare has timed out**. Extension provisioning has taken too long to complete. The extension did not report a message. More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot"

  on sql1.tf line 58, in resource "azurerm_virtual_machine_extension" "sql1_extension":

  58: resource "azurerm_virtual_machine_extension" "sql1_extension" {

### Expected Behavior

Operation waits two hours before timing out as specified in TIMEOUT block

### Actual Behavior

Operation timed out after 1 hour and 37 minutes

### Steps to Reproduce

Configure a long running VM extension (in my case a long DSC script for building a database server)
Configure a resource timeout on the extension resource

1. `terraform apply`

**Comment by ArcturusZhang** [comment] 2020-08-07 02:48
Hi @pessimism thanks for this issue!

Sorry for the trouble but this is not caused by the timeout settings in the provider, instead, this is an timeout error returned from the service. Usually, if the timeout in terraform is reached, the error message should be `context deadline exceeds` rather than in this pattern: `"Code" = "Something", Message = "Description"`, which matches the pattern of a service returned error.

Speaking of the service timeout, I am not aware of if there is a way that you could configure that timeout to extend the duration. But _sometimes_, even when the service returns an error and complains about timeout, the extension may still be installing in the backend - and you could check the process on the portal - which may result in that you have to import it into terraform before your next apply.

Hope this would help, thanks!

**Comment by tombuildsstuff** [comment] 2020-08-07 16:22
hi @pessimism 

As @ArcturusZhang has mentioned the `timeouts` block only controls the time that Terraform will poll for - the Azure API's have their own hard-coded timeouts on their end which can't be overridden (for example, 3 hours for a VM to boot, when it can take longer than that in the background in some cases). In the case of VM Extensions specifically unfortunately the API for these varies depending on the VM Extension in question being used - in this case it appears that's a ~90 minute timeout from the script starting to execute on the VM, so perhaps this is a configurable timeout within DSC or the VM Extension settings itself?

Since this error's coming from the VM Extension / Azure API here and isn't something we're able to override here - whilst I'd like to thank you for opening this issue I'm going to close this for the moment. As for next steps, I'd suggest filing an issue on the Azure VM Extensions repository where they (or potentially Azure Support) should be able to confirm the settings necessary to override the DSC timeouts here.

Thanks!

**Closed by tombuildsstuff** 2020-08-07 16:22 UTC
Labels: question, service/virtual-machine-extensions, waiting-response
