### ISSUE TITLE
Issue when Terraform destroys an Azure VPN Virtual Gateway

### ISSUE THREAD

**Issue by samberthol** [terraform-providers/terraform-provider-azurerm#1513] opened 2018-07-06 20:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

provider.azurerm v1.7.0

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway" "vpn0-vnetgw0" {
  name                = "${local.name-prefix-v0}-vnetgw0"
  location            = "${var.location0}"
  resource_group_name = "${azurerm_resource_group.rg.name}"

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false
  sku           = "VpnGw1"

  ip_configuration {
    name                          = "ipconfig1"
    public_ip_address_id          = "${azurerm_public_ip.vpn0-ippub0.id}"
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = "${azurerm_subnet.vnet0-sub0.id}"
  }
}
```

### Expected Behavior

When destroying a complete template that includes a full VPN IPsec configuration and the VPN virtual gateway is attached to subnets Terraform first destroys the subnets and then the gateway. Hence the deletion of the VPN gateway fails as it reports it misses its subnets. Deletion of the gateway from the Azure Portal also fails.

I opened a ticket through Azure support where they pointed me at trying to edit through the resources.azure.com to pass the resource from a status "Failed" to "Suceeded" but it didn't help. 

### Actual Behavior

Terraform should destroy the VPN virtual gateway first and the subnets.
If you recreate manually the subnets, then you are able to destroy the VPN virtual gateway either through Terraform or through the Azure Portal.

If you first go to the Azure Portal and delete the gateway manually, then you are able to destroy the rest of your terraform templates fine, down to the resource group.

### Steps to Reproduce

Using Terraform
1. Create VNETs
2. Create Create Subnets
3. Create a Virtual Network Gateway
4. Try to destroy it

* #0000

**Comment by erikpaasonen** [comment] 2019-04-26 19:26
I'm using:
```
Terraform v0.11.13
+ provider.azurerm v1.27.0
```
Terraform applies and destroys this entire stack idempotently:

``` hcl
resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "West US"
}

resource "azurerm_virtual_network" "test" {
  name                = "test"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "GatewaySubnet"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "test"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  allocation_method = "Dynamic"
}

resource "azurerm_virtual_network_gateway" "test" {
  name                = "test"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false
  sku           = "Basic"

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = "${azurerm_public_ip.test.id}"
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = "${azurerm_subnet.test.id}"
  }
}
```
Perhaps this bug got fixed already?

**Comment by tombuildsstuff** [comment] 2019-09-01 17:36
hey @samberthol 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this, based on @erikpaasonen's comment this sounds like a dependency issue within the Terraform Configuration being used. Since this issue's been open for quite a while (and I'm assuming that you've found a workaround by now) I'm going to close this issue for the moment, however if you're still having issues here would you be able to provide a reproducible Terraform Configuration so that we can try and diagnose this further?

Thanks!

**Closed by tombuildsstuff** 2019-09-01 17:36 UTC
Labels: bug, service/virtual-network-gateway
