### ISSUE TITLE
azurerm_eventhub_authorization_rule error provider 2.67.0

### ISSUE THREAD

**Issue by matt-garner-nw** [terraform-providers/terraform-provider-azurerm#12568] opened 2021-07-13 09:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_eventhub_authorization_rule `

### Terraform Configuration Files

```hcl

resource "azurerm_eventhub_authorization_rule" "example" {
  name                = "example"
  namespace_name      = azurerm_eventhub_namespace.eh_namespace[0].name
  eventhub_name       = azurerm_eventhub.eh_hub[0].name
  resource_group_name = azurerm_resource_group.example.name
  listen              = true
  send                = true
  manage              = true
}
```

### Expected Behaviour

Authorization Rule should have been created.

### Actual Behaviour

Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sebader** [comment] 2021-07-13 10:03
duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/12387

**Comment by jackofallops** [comment] 2021-07-13 13:21
> duplicate of #12387

Thanks for reporting, however, I'm going to close based on the earlier duplicate, please subscribe to the earlier issue for updates.

Thanks!

**Closed by jackofallops** 2021-07-13 13:21 UTC
