### ISSUE TITLE
Support for API management azure (error while adding adding virtual network )

### ISSUE THREAD

**Issue by manikantraj** [terraform-providers/terraform-provider-azurerm#6116] opened 2020-03-14 22:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "azurerm" {
 version = "=2.0.0"
 subscription_id = var.subscription_id
 features {}
}
resource "azurerm_api_management" "test" {
  name                = "example-apim"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  virtual_network_type = "${networkType}"

  virtual_network_configuration {
    subnet_id  = "${subnetId}"
    vnet_id    = "${vnetId}"
    subnetname = "${subnetName}"
  }  

  sku_name = "Developer_1"

}
```

### Expected Behavior
it should create a apim service with an private ip and connected to internal vnet 
https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-internal-vnet

### Actual Behavior

error : An argument named "virtual_network_type" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### References
https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-internal-vnet

**Comment by tombuildsstuff** [comment] 2020-03-16 07:53
hi @manikantraj 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3667 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3667 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-03-16 07:53 UTC
