### ISSUE TITLE
"azurerm_recovery_services_protected_vm" shows a change to be performed in the "backup_policy_id" even though there is no change made on the policy

### ISSUE THREAD

**Issue by AbhishekB15** [terraform-providers/terraform-provider-azurerm#4810] opened 2019-11-05 14:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

1.36.1

### Affected Resource(s)

azurerm_recovery_services_protected_vm

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

~ azurerm_recovery_services_protected_vm.VM
      backup_policy_id: "/subscriptions/XXXXXXXXXXXXXXX/resourcegroups/XXXX/providers/microsoft.recoveryservices/vaults/XXXXX/backupPolicies/VMPolicy" => "/subscriptions/XXXXXXXXXXXXXXX/resourceGroups/XXXX/providers/Microsoft.RecoveryServices/vaults/XXXXX/backupPolicies/VMPolicy"

### Expected Behavior

There should be no change as the backup policy isn't being changed

### Actual Behavior

Terraform plan is trying to update the backup policy to the existing backup policy

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2019-11-05 15:23
hi @AbhishekB15 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4774 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4774 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-11-05 15:23 UTC
Labels: duplicate, service/recovery-services, upstream-microsoft

**Comment by AbhishekB15** [comment] 2019-11-06 05:24
Thanks @tombuildsstuff
