### ISSUE TITLE
NAT Gateway and User Defined Route cannot coexist on a subnet

### ISSUE THREAD

**Issue by devblackops** [terraform-providers/terraform-provider-azurerm#6989] opened 2020-05-18 18:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azurerm v1.44.0

### Affected Resource(s)

* `azurerm_subnet`
* `azurerm_nat_gateway`
* `azurerm_subnet_nat_gateway_association`
* `azurerm_route_table`
* `azurerm_subnet_route_table_association`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.44.0"
}

resource "azurerm_resource_group" "rg" {
  name     = "test-nat"
  location = "eastus"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "test-vnet"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "test-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_public_ip" "nat_ip" {
  name                = "nat-ip"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  sku               = "Standard"
  allocation_method = "Static"
}

resource "azurerm_nat_gateway" "nat_gw" {
  name                = "nat-gw"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  public_ip_address_ids = [azurerm_public_ip.nat_ip.id]
  sku_name              = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "nat_gw_assoc" {
  subnet_id      = azurerm_subnet.subnet.id
  nat_gateway_id = azurerm_nat_gateway.nat_gw.id
}

resource "azurerm_route_table" "udr" {
  name                = "routetable"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  disable_bgp_route_propagation = true

  route {
    name                   = "custom-route"
    address_prefix         = "192.168.0.0/24"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = "10.0.1.0"
  }
}

resource "azurerm_subnet_route_table_association" "udr_assoc" {
  subnet_id      = azurerm_subnet.subnet.id
  route_table_id = azurerm_route_table.udr.id
}
```

### Panic Output

No Panic

### Expected Behavior

Both a NAT Gateway association and a route table association can be applied to a subnet at the same time.

### Actual Behavior

Both associations exist on the first `apply`, on subsequent `plans` and `applies`, Terraform wants to remote the route table associations from the subnet. Running the 2nd `apply` will remove the route_table_id, but also the NAT gateway subnet association, even though that is not in the plan.

This *appears* to be an issue with `azurerm_subnet` as when taking NAT Gateway out of the Terraform config, the route table associations alternates between being removed and added on subsequent applies.

When removing the route table from the Terraform config and adding back NAT Gateway, the gateway association is stable on subsequent plan/applies.

It looks like when `route_table_id` is removed from `azurerm_subnet`, this also impacts the NAT Gateway association.

### Steps to Reproduce

1. `terraform plan & apply`
2. `terraform plan & apply` again
3. Observe in plan that `azurerm_subnet` wants to remove the route table association via `route_table_id -> null`
4. Observe that after 2nd `apply` both route table and nat gateways subnet associations are removed, even though plan just lists `route_table_id`.
5. Run `terraform apply` again
6. Observe that both associations are added back
7. Rinse and repeat

### Important Factoids

None

### References

* #0000

**Comment by devblackops** [comment] 2020-05-18 19:29
Adding `ignore_changes` to `azurerm_subnet` appears to work but obviously isn't ideal.

```hcl
resource "azurerm_subnet" "subnet" {
  name                 = "test-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefix       = "10.0.1.0/24"

  lifecycle {
    ignore_changes = [
      route_table_id
    ]
  }
}
```

**Comment by njuCZ** [comment] 2020-05-27 08:20
@devblackops I tried using the latest version azurerm and could not reproduce this issue. Could you please upgrade the version and have a try?

**Comment by devblackops** [comment] 2020-05-27 17:55
Confirmed that this works with the AzureRM `2.11.0` provider. 

Unfortunately, we can't move to `2.x.x` just yet. I guess the workaround of ignoring changes to `route_table_id` will have to suffice for now.

Thanks for checking.

**Comment by mybayern1974** [comment] 2020-06-03 08:52
Hi @devblackops 

Glad to see you’ve got explanation from njuCZ and work arounds! Would you ok we close this issue for now? Feel free to reopen it if you think there is any follow up we can provide. Thank you.

**Closed by mybayern1974** 2020-06-03 08:52 UTC
Labels: question, service/nat-gateway
