### ISSUE TITLE
Feature to assign Managed Identity to Logic Apps

### ISSUE THREAD

**Issue by rizvan-ms** [terraform-providers/terraform-provider-azurerm#10741] opened 2021-02-25 16:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, there is not an "identity" block to define whether to use "system-assigned" or "user-assigned" managed Identity with logic apps. 

### New or Affected Resource(s)

* azurerm_logic_app_workflow

### Potential Terraform Configuration

```hcl
resource "azurerm_logic_app_workflow" "this" {
  for_each                                              = {for workflow in var.logic_app_workflow: workflow.name => workflow}
  name                                                  = each.value["name"]
  location                                              = each.value["location"]
  resource_group_name                       = each.value["resource_group_name"]
  integration_service_environment_id  = each.value["integration_service_environment_id"]
  logic_app_integration_account_id     = each.value["logic_app_integration_account_id"]

  identity {
    type = "SystemAssigned"
  }
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-02-25 16:29
hi @rizvan-ms 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2924 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2924 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-25 16:29 UTC
Labels: duplicate, enhancement, service/logic
