### ISSUE TITLE
Update FileUploadLimitInMb is failing with version 1.24.0

### ISSUE THREAD

**Issue by SirWayne** [terraform-providers/terraform-provider-azurerm#3177] opened 2019-04-04 12:37 UTC
Hello,

with the new version 1.24.0 i get always a 400 error code.

This is my configuration:
```
  waf_configuration {
    enabled          = true
    firewall_mode    = "Prevention"
    rule_set_type    = "OWASP"
    rule_set_version = "3.0"
    max_request_body_size_kb = 128
  }
```
And the error message:
```
* azurerm_application_gateway.AppGateway: 1 error(s) occurred:

* azurerm_application_gateway.AppGateway: Error Creating/Updating Application Gateway "***" (Resource Group "***"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayFirewallInvalidFileUploadLimitInMbForMediumGw" Message="FileUploadLimitInMb '0' is out of range for medium sku, it should be within '1' and '100' in context 'properties.webApplicationFirewallConfiguration'." Details=[]
<!---
Please note the following potential times when an issue might be in Terraform core:

* [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
* [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
* [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
* [Registry](https://registry.terraform.io/) issues
* Spans resources across multiple providers
```

EDIT: the issue is, when the file upload textfield  in the UI is empty as default

**Comment by SirWayne** [comment] 2019-04-04 13:00
A think it's duplicated sorry https://github.com/terraform-providers/terraform-provider-azurerm/issues/3011

**Comment by tombuildsstuff** [comment] 2019-04-04 13:21
hey @SirWayne 

Thanks for opening this issue :)

As you've mentioned I believe the root cause of this is being tracked in #3011 - rather than having multiple issues open tracking the same thing I'm going to close this in favour of #3011 - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2019-04-04 13:21 UTC
Labels: bug, duplicate, service/application-gateway
