### ISSUE TITLE
Atp settings are not supported on resources of type servers (PostgreSQL)

### ISSUE THREAD

**Issue by oscarmon7** [terraform-providers/terraform-provider-azurerm#6610] opened 2020-04-24 11:41 UTC
Hello,
using provider.azurem v2.2.0 I'm getting the below error when trying to activate ATP in a PostgreSQL server.

Error: Error checking for presence of existing Advanced Threat Protection for resource "/subscriptions/\*\*\*\/resourceGroups/\*\*\*\/providers/Microsoft.DBforPostgreSQL/servers/mypgserver": security.AdvancedThreatProtectionClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Not Supported" Message="Atp settings are not supported on resources of type servers"

  on resources\postgres.tf line 148, in resource "azurerm_advanced_threat_protection" "atp":
 148: resource "azurerm_advanced_threat_protection" "atp" {

There is an issue reporting this same topic #5238 which  was closed without a proper resolution. I would appreciate your feedback.

Thanks.

**Comment by pearcec** [comment] 2020-04-25 13:13
Seems similar to this issue #5629.

**Comment by katbyte** [comment] 2020-04-26 06:29
@oscarmon7 - this is a duplicate of #5629so as such i am going to close to keep discussion on one issue. thanks thou!

**Closed by katbyte** 2020-04-26 06:29 UTC
