### ISSUE TITLE
terraform import azurerm_role_assignment.<user> imports fine but terraform plan will then  destroy & create replacement

### ISSUE THREAD

**Issue by guri-s** [terraform-providers/terraform-provider-azurerm#1972] opened 2018-09-24 02:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform v0.11.8

### Affected Resource(s)

azurerm_role_assignment

### Terraform Configuration Files

I get the role assignment from azure cloud shell powershell by using below:
```
Get-AzureRmRoleAssignment
```

then use the out put for the user that already exists to import the role assignment for that user as:
```
terraform import azurerm_role_assignment.user /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/600ccdb8-e008-40e1-a498-fb8999b82071
```
iam_user.tf
```hcl
resource "azurerm_role_assignment" "user" {
  scope             = "${data.azurerm_subscription.current.id}"
  role_definition_name = "Owner"

  principal_id = "00000000-0000-0000-0000-000000000000"
}
```

### Expected Behavior

After the import, ```terraform plan ``` , there should be no changes to apply as the user's role assignment is successfully imported

### Actual Behavior

when doing ```terraform plan``` it tries to do below
```
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ azurerm_role_assignment.user (new resource required)
      id:                 "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/600ccdb8-e008-40e1-a498-fb8999b82071" => <computed> (forces new resource)
      name:               "600ccdb8-e008-40e1-a498-fb8999b82071" => <computed>
      principal_id:       "0c65668e-01e9-436a-a43d-bdb36da6933e" => "00000000-0000-0000-0000-000000000000"
      role_definition_id: "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635" => "/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635" (forces new resource)
      scope:              "/subscriptions/00000000-0000-0000-0000-000000000000" => "/subscriptions/00000000-0000-0000-0000-000000000000"
```

1. `terraform plan`

### References

https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html
* #0000

**Comment by metacpp** [comment] 2018-10-03 18:41
If you are importing a resource you should not assign any values to the resource in the tf file, so in your case the HCL in your tf file for the imported resource should look like the below.

```
resource "azurerm_role_assignment" "user" {
}
```

**Comment by tombuildsstuff** [comment] 2018-11-08 09:38
hi @guri-s 

Taking a look at this this appears to be a duplicate of #1454 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1454 - please subscribe to that issue for updates

Thanks!

**Closed by tombuildsstuff** 2018-11-08 09:38 UTC
Labels: question, service/authentication
