### ISSUE TITLE
azurerm_application_gateway - Ignore changes for ssl certificate does not work

### ISSUE THREAD

**Issue by yehia2221** [terraform-providers/terraform-provider-azurerm#7876] opened 2020-07-23 16:59 UTC
We have initial SSL certificates that were deployed via terraform, after the deployment, we have a process 'runbook' which renews the certificates automatically.  We have added the `ssl_certificate` block to the ignore_changes, and the `terraform plan` shows no actions and diff in the output, however, after the deployment, the certificates are destroyed and reset to the initial ones. This Behavior is not expected, the certificates should be ignored since they are added to the lifecycle block.  

```
  lifecycle {
    ignore_changes = [
      ssl_certificate
    ]
  }
```

**Terraform Version**
0.12.26

**azurerm provider version**
2.19

A similar issue is already reported in https://github.com/terraform-providers/terraform-provider-azurerm/issues/4084

**Comment by mybayern1974** [comment] 2020-07-24 08:27
hi  @yehia2221 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4084- rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4084 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-07-24 08:27 UTC
Labels: duplicate, service/application-gateway
