### ISSUE TITLE
metadata_url not optional for provider

### ISSUE THREAD

**Issue by elsesiy** [terraform-providers/terraform-provider-azurerm#7699] opened 2020-07-10 23:17 UTC
### Terraform (and AzureRM Provider) Version

2.18.0

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.18"
}
```

### Debug Output

```
missing required argument 'MetadataUrl'
```

### Expected Behavior

Environment should still be usable regardless of the new `metadata_url` property.

### Actual Behavior

Can't use provider in `2.18.0` without specifying `metadata_url`.
Also there's no documentation on how to obtain this property.

### References
https://github.com/terraform-providers/terraform-provider-azurerm/pull/7664/files
<img width="887" alt="Screen Shot 2020-07-10 at 4 12 55 PM" src="https://user-images.githubusercontent.com/7075075/87209985-ca35e980-c2c8-11ea-8e6f-cd227cfafd4c.png">

**Comment by elsesiy** [comment] 2020-07-11 02:06
In case anybody is experiencing the same issue, the metadata URL in my case was which I had to construct by going through the source as I couldn't find it anywhere in the portal.

`https://management.azure.com/metadata/endpoints?api-version=2019-05-01`

This should be a default if none is provided IMO

**Comment by tombuildsstuff** [comment] 2020-07-13 06:12
hey @elsesiy 

Thanks for opening this issue.

Taking a look into this I'm unable to reproduce this using either the Azure CLI, MSI (in Azure CloudShell) or a Service Principal to authenticate - so that we can take a look into this would you be able to confirm which authentication method you're using here?

Thanks!

**Comment by elsesiy** [comment] 2020-07-13 16:07
@tombuildsstuff I'm using Service Principal authentication but it could be an issue with SDK I'm using and not directly related to the tf provider. I'll try to create a repro using just terraform and will reach out to the vendor.

**Comment by tombuildsstuff** [comment] 2020-07-13 16:15
hi @elsesiy 

After digging into this, unfortunately I can't find a reference to `MetadataUrl` anywhere within this Provider - however it does [appear in the Pulumi codebase](https://github.com/pulumi/pulumi-azure/blob/73d547136edb349e10ce148bd518a01c65a76670/sdk/go/azure/provider.go#L25).

Whilst the Pulumi Azure Provider does vendor this Terraform Provider - where the plugin/translation layer that Pulumi doesn't correctly map the behaviours of this Terraform Provider in it's translation layer, unfortunately the behaviour of Resources and the Provider can differ - and as such unfortunately we're unable to offer support for this Terraform Provider inside of Pulumi.

As such whilst I'd like to thank you for opening this issue, since this isn't a bug that's reproducible in Terraform I'm going to close this issue for the moment.

Thanks!

**Comment by elsesiy** [comment] 2020-07-13 16:16
I filed a bug with them, thanks!

**Closed by tombuildsstuff** 2020-07-13 16:15 UTC
Labels: authentication, question

**Comment by stack72** [comment] 2020-07-13 16:31
Hi @tombuildsstuff 

So the issue is actually this PR - https://github.com/terraform-providers/terraform-provider-azurerm/pull/7664

This specifies the following in the AzureRM provider config block:

```
			"metadata_url": {
				Type:        schema.TypeString,
				Required:    true,
				DefaultFunc: schema.EnvDefaultFunc("ARM_METADATA_URL", ""),
				Description: "The Metadata URL which will be used to obtain the Cloud Environment.",
			},
```

As you can see, `metadata_url` is marked as `required` - is this not the case? 

//cc @elsesiy 

Paul

**Comment by tombuildsstuff** [comment] 2020-07-13 16:44
@stack72 there's a default value specified in the DefaultFunc, so this field is Optional by there being a default value - which is why Terraform picks this up as having a default value :)

**Comment by stack72** [comment] 2020-07-13 16:46
So the default being an env var of an empty value - wouldn't that suggest it's optional? Like the docs suggest

**Comment by stack72** [comment] 2020-07-13 16:49
FWIW, I don't mind either answer - i was just curious about the ambiguity :)
