### ISSUE TITLE
 Vnet diagnostic setting - Needs to be imported into the State

### ISSUE THREAD

**Issue by albertwo1978** [terraform-providers/terraform-provider-azurerm#8109] opened 2020-08-12 22:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Description

Running into a sporadic issue when enabling diagnostic settings on vnets and subnets. The issue seems to be happening since upgrading to Terraform v0.13.0. Periodically, the diagnostic setting does not save to state and I receive the following error. Future attempts to redeploy fail with the same error unless I manually delete the diagnostic setting in Azure before retrying:

**Error: A resource with the ID "/subscriptions/<sub_id>/resourcegroups/<rg_name>/providers/microsoft.network/networksecuritygroups/<nsg_name>/providers/microsoft.insights/diagnosticSettings/<setting_name>" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.**

I notice when it does succeed, I get the following two entries in my logs. I only see the first entry when it fails: 

**module.t2-network.azurerm_monitor_diagnostic_setting.vnet: Creating...
module.t2-network.azurerm_monitor_diagnostic_setting.vnet: Creation complete after 5s ...**

Here is a template sample of where it fails: 
![Screen Shot 2020-08-12 at 6 26 42 PM](https://user-images.githubusercontent.com/15147855/90074519-6fc5e980-dcc9-11ea-9e75-7557c6debbf6.png)

**Comment by magodo** [comment] 2020-08-14 09:17
Hi @albertwo1978 The error message tells that one of the diagnostic settings is already existed in Azure. Is there any chance it is created via other means by someone else?

**Comment by albertwo1978** [comment] 2020-08-14 20:59
It may be related to a diagnostic setting that was created, but deleted prior to the deployment. This Issue seems to be the same scenario. [https://github.com/terraform-providers/terraform-provider-azurerm/issues/6389](url)

**Comment by magodo** [comment] 2020-08-15 02:21
After you confirmed that the diag setting is deleted from portal, have you tried to provision via Terraform again?

**Comment by albertwo1978** [comment] 2020-08-18 16:17
I was confirming that the RG was deleted but not looking directly at the [diagnostics settings blade](https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/diagnosticsLogsl). I will try to repro and see if the setting still exists even after the RG has been deleted.

**Comment by tombuildsstuff** [comment] 2020-08-18 16:24
@albertwo1978 Diagnostics Settings are not deleted when Resource Groups are deleted - as such unfortunately this is going to stick around if this is not deleted via Terraform (and not deleted via the "Azure Monitor" section of the portal/through some other means). Just to double-check - how are these resources being deleted between Terraform applies?

**Comment by albertwo1978** [comment] 2020-08-19 00:56
@tombuildsstuff - We're going to try and repro and circle back. TF is erroring on deployment even if the resource is deleted from Azure Monitor. It seems to be related to maintaining state. Will chime back in in a few days.

**Comment by tombuildsstuff** [comment] 2020-08-20 16:14
Closing this issue out since the root-cause is this Diagnostic Setting still kicking around/not being deleted - as such Terraform is working as intended here by requiring this resource to be imported (rather than silently adopting it).

**Closed by tombuildsstuff** 2020-08-20 16:14 UTC
Labels: question, service/monitor, waiting-response
