### ISSUE TITLE
Account Kind BlobStorage not working with azurerm_storage_account

### ISSUE THREAD

**Issue by jbooth-idexx** [terraform-providers/terraform-provider-azurerm#3334] opened 2019-04-29 18:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.13
provider.azurerm v1.27.1

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
  resource "azurerm_storage_account" "storageaccount" {
    name                     = "teststorage"
    resource_group_name      = "test-rg"
    location                 = "westeurope"
    account_kind             = "BlobStorage"
    account_tier             = "Premium"
    account_replication_type = "LRS"
    access_tier              = "Hot"
  }
```

### Expected Behavior

I am trying to create a premium storage account using blobstorage.  I can create this account from the portal but it is failing in terraform.

Performance:
Premium
Replication:
Locally-redundant storage (LRS)
Account kind:
BlockBlobStorage

### Actual Behavior
I get the following error:

* azurerm_storage_account.storageaccount: Error creating Azure Storage Account "jpbstorage": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: kind."

### Steps to Reproduce

1. `terraform apply`

**Comment by saravanakkumar** [comment] 2019-05-23 14:10
Is there any workaround ?.

**Comment by jbooth-idexx** [comment] 2019-05-23 15:55
I was not able to find a workaround for this!  I created the storage account manually in the portal and created the storage containers in my terraform code.  This was not a good workaround because when I run a plan these storage containers that I created below are recreated every time!

resource "azurerm_storage_container" "datablob" {
  name                  = "${var.prefix}-data-blob"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  storage_account_name  = "${var.storage_account}"
  container_access_type = "private"
  }
}
resource "azurerm_storage_container" "imageblob" {
  name                  = "${var.prefix}-image-blob"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  storage_account_name  = "${var.storage_account}"
  container_access_type = "private"
}

**Comment by rk-tbrigley** [comment] 2019-06-06 21:03
Similar error here, maybe i'm missing something, i'm new to terraform.  I want to generate a new SAS for and existing storage account container, to use it in another section to populate the various storage accounts required for an aggregation job in hdinsight. I have the cluster and other bits coming up nicely, i just need to generate a temporary SAS token. P.S. any newb advise is welcome.

init and plan succeed. apply fails.

1 error occurred:
	* azurerm_storage_account.liverg: 1 error occurred:
	* azurerm_storage_account.liverg: Error creating Azure Storage Account "aswstagingsastorage": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: kind."

main.tf 
resource "azurerm_resource_group" "liverg" {
  name = "${var.rg_storage_account_1}"
  location = "Southeast Asia"
  lifecycle {
    ignore_changes = "all"
    prevent_destroy = true
  }
}
resource "azurerm_storage_account" "liverg" {
  name = "${var.storage_account_1}"
  resource_group_name      = "${azurerm_resource_group.liverg.name}"
  location                 = "${azurerm_resource_group.liverg.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}
  data "azurerm_storage_account_sas" "livesa" {
    connection_string = "${azurerm_storage_account.liverg.primary_connection_string}"
    https_only = true
    resource_types {
      service = true
      container = false
      object = false
    }
    services {
      blob = true
      queue = true
      table = true
      file = true
    }
    start = "${timestamp()}"
    expiry = "${timeadd(timestamp(),"10080m")}"
    permissions {
      read = true
      write = false
      delete = false
      list = true
      add = false
      create = false
      update = false
      process = false
    }
  }
  output "sas_url_sas_string" {
    value = "${replace("${data.azurerm_storage_account_sas.livesa.sas}", "?", "")}"
  }
  output "sas_url_sas_string_start" {
    value = "${data.azurerm_storage_account_sas.livesa.start}"
  }
  output "sas_url_sas_string_expire" {
    value = "${data.azurerm_storage_account_sas.livesa.expiry}"
  }

**Comment by alex-goncharov** [comment] 2019-06-18 09:32
This looks like a bad error message from Azure.  It looks like BlobStorage does not support `Premium_LRS` SKU. Try changing account_tier to Standard.

**Comment by jbooth-idexx** [comment] 2019-06-18 14:57
I was able to create the storage account via the portal.  So it does indeed look like a bad error message but I am not sure why...

Performance: Premium
Replication: Locally-redundant storage (LRS)
Account kind: BlockBlobStorage

**Comment by tombuildsstuff** [comment] 2019-08-21 14:08
👋 

Taking a look into this the root cause appears to be that Terraform currently doesn't support creating BlockBlobStorage accounts - which is being tracked in #4082 and will be added in #4131. As such I'm going to close this issue in favour of #4082 - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-21 14:08 UTC
Labels: bug, service/storage
