### ISSUE TITLE
Azure Cognitive Service - Creation Issue

### ISSUE THREAD

**Issue by roshanp85** [terraform-providers/terraform-provider-azurerm#7214] opened 2020-06-04 18:25 UTC
cognitiveservices.AccountsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ApiPropertiesInvalid" Message="The given 'apiProperties' '{\r\n  \"qnaRuntimeEndpoint\": \"\"\r\n}' is invalid. Validation errors: Property 'qnaRuntimeEndpoint' has not been defined and the schema does not allow additional properties. Path 'apiProperties.qnaRuntimeEndpoint'."

Terraform Code:

resource "azurerm_cognitive_account" "cognitive_account" {
  name                = var.cognitive_account_name
  location            = var.resource_group_location
  resource_group_name = var.resource_group_name
  kind                = "CognitiveServices"
  sku_name = "S0"
  tags = var.tags
}

While executing the above code, I get the error for attribute qnaRuntimeEndpoint, even though this is an optional component. and kind is "CognitiveServices". 

Has anyone seen this issue ? I am currently using provider: 2.9.0

provider "azurerm" {
  version = "= 2.9.0"
  features {    
  }
}

**Comment by tombuildsstuff** [comment] 2020-06-05 09:43
Duplicate of #6343

**Closed by tombuildsstuff** 2020-06-05 09:43 UTC
