### ISSUE TITLE
Add support for 'ExternalGit' scm_type to azurerm_app_service

### ISSUE THREAD

**Issue by ben-lings-tessella** [terraform-providers/terraform-provider-azurerm#1354] opened 2018-06-06 17:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to create an Azure Web App that's pointing to an external git repo. This is the configuration used, for example, by the Wordpress template in the Azure portal (https://portal.azure.com/#create/WordPress.WordPress). At the moment, I've reproduced this into Terraform script, with the exception of the SCM reference. If I try and import the existing resources, using `terraform apply` resets the `scm_type` to `None`.

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```hcl
  site_config {
    scm_type    = "ExternalGit"
  }

  source_control {
    repo_url = "https://github.com/azureappserviceoss/wordpress-azure"
    branch = "master"
  }
```

### References

* #0000

**Comment by katbyte** [comment] 2018-06-06 17:42
Hi @ben-lings-tessella,

Thank you for opening this issue, however as it appears to be a duplicate of #1104 I am going to close it in favour of the older issue.

**Closed by katbyte** 2018-06-06 17:42 UTC
