### ISSUE TITLE
Support for [azurebot]

### ISSUE THREAD

**Issue by wang415** [terraform-providers/terraform-provider-azurerm#12654] opened 2021-07-20 01:56 UTC
Creation of new Web App and Channel Registration bots will be deprecated on September 1, 2021. Learn more.

Please start creating with the updated Azure Bot resource.

For example:

* https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?WT.mc_id=Portal-Microsoft_Azure_BotService&view=azure-bot-service-4.0&tabs=csharp%2Ccshap#create-an-azure-bot-resource

**Comment by tombuildsstuff** [comment] 2021-07-20 09:10
Duplicate of #12522

**Closed by tombuildsstuff** 2021-07-20 09:10 UTC
