### ISSUE TITLE
DNS alias gets removed from public IP when VM is recreated

### ISSUE THREAD

**Issue by braunsonm** [terraform-providers/terraform-provider-azurerm#9044] opened 2020-10-27 22:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.24.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.5.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_public_ip`
* `azurerm_dns_a_record`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "acceptanceTestResourceGroup1"
  location = "West US"
}

resource "azurerm_dns_zone" "example" {
  name                = "mydomain.com"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_public_ip" "example" {
  name                = "mypublicip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Dynamic"
  ip_version          = "IPv4"
}

resource "azurerm_dns_a_record" "example" {
  name                = "test"
  zone_name           = azurerm_dns_zone.example.name
  resource_group_name = azurerm_resource_group.example.name
  ttl                 = 300
  target_resource_id  = azurerm_public_ip.example.id
}
```

Then have a VM with a NIC that uses this Public IP:

```
resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.example.id
  }
}
```

### Expected Behavior

When destroying and recreating the VM, the public IP should remain aliased to the DNS record.

### Actual Behavior

The public IP becomes disassociated from the DNS record and just becomes an empty DNS record in the Azure portal with no resources associated with it. I'm not sure why this happens, the NIC and public IP do not change, just their associations to a new VM do.

![image](https://user-images.githubusercontent.com/5280764/97366975-b36ad100-187e-11eb-9e65-4b1c536d6ead.png)
Note how the alias target became blank.

Now after you have ran the apply that destoryed and recreated the VM, if you run apply again TF picks up on the fact that it needs to update the DNS record and resolves the issue:

```
  # module.azurerm_dns_a_record.vault will be updated in-place
  ~ resource "azurerm_dns_a_record" "example" {
        fqdn                = "example.com."
        id                  = "/subscriptions"
        name                = "subdomain"
        records             = []
        resource_group_name = "example"
        tags                = {}
      + target_resource_id  = "/example"
        ttl                 = 300
        zone_name           = "example.com"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform taint <vmname>`
3. `terraform apply`

At this point the DNS record alias becomes blank.

4. `terraform apply`

At this point the DNS record is fixed.

**Comment by braunsonm** [comment] 2020-10-28 13:50
I'm thinking this might have to do with the fact that the IP is dynamic? But I figured since it is an alias it shouldn't matter.

**Comment by tombuildsstuff** [comment] 2020-10-28 15:10
@braunsonm agreed this is likely because the Public IP Address is Dynamic - unfortunately that's likely by design due to the way Dynamic IP's work in Azure.

Ultimately it should be possible to work around this using `depends_on` to force the ordering here - since presumably the DNS API is checking these resources and noting they have no IP assigned at this time, and so ignoring rather than raising an error here. It may also be possible to reference the ID of the Virtual Machine too - I'm not sure?

Since this should be fixed by adding a dependency on the Virtual Machine where this is set, I'm going to close this issue for the moment however if that doesn't work for you then please let us know and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-10-28 15:10 UTC

**Comment by braunsonm** [comment] 2020-10-28 15:16
@tombuildsstuff you can't use a `depends_on` here so that the IP depends on the VM since the IP is used to create the NIC for the VM, you'd have a circular depends.

Unless you mean the VM depends on the IP? That's already the case because the NIC for the VM depends on the IP...

**Comment by tombuildsstuff** [comment] 2020-10-28 15:24
@braunsonm I mean the dependency chain likely wants to be: PIP <- VM <- DNS A record - so that the Dynamic PIP has an IP Address (via the VM booting) when the DNS A record is created.

Hope that helps.

**Comment by braunsonm** [comment] 2020-11-03 23:12
@tombuildsstuff I really don't think this is normal. Even if it's a dynamic IP it shouldn't be changing the DNS record from alias to a static IP when just tainting the VM. Don't you think that's odd? The PIP resource isn't recreated so why would it remove the alias? I understand that the actual IP might not be allocated but it shouldn't remove the DNS Alias when the PIP resource still exists.

**Comment by braunsonm** [comment] 2020-11-12 16:56
@tombuildsstuff can this be reopened?

**Comment by tombuildsstuff** [comment] 2020-11-12 17:00
@braunsonm unfortunately this isn't a Terraform bug, but the way Dynamic IP's work by design within Azure - so unfortunately there's no issue to track on our side here.
