### ISSUE TITLE
Unexpect EOF log analytic

### ISSUE THREAD

**Issue by pratik141** [terraform-providers/terraform-provider-azurerm#3280] opened 2019-04-18 16:48 UTC
getting error in terraform plan of application gateway with log analytic  `refreshing state `

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform version: 0.11.11  

### Affected Resource(s)

* `azurerm_v1.25.0`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
2019/04/18 17:18:11 [ERROR] root.appgateway-piam: eval: *terraform.EvalRefresh, err: azurerm_monitor_diagnostic_setting.diagnostic_setting_la_for_singlecount: unexpected EOF
2019/04/18 17:18:11 [ERROR] root.appgateway-piam: eval: *terraform.EvalSequence, err: azurerm_monitor_diagnostic_setting.diagnostic_setting_la_for_singlecount: unexpected EOF
2019/04/18 17:18:11 [ERROR] root.appgateway-piam: eval: *terraform.EvalRefresh, err: azurerm_monitor_diagnostic_setting.diagnostic_setting_storage_for_singlecount: unexpected EOF
2019/04/18 17:18:11 [ERROR] root.appgateway-uiam: eval: *terraform.EvalRefresh, err: azurerm_monitor_diagnostic_setting.diagnostic_setting_la_for_singlecount: unexpected EOF
2019/04/18 17:18:11 [ERROR] root.appgateway-piam: eval: *terraform.EvalSequence, err: azurerm_monitor_diagnostic_setting.diagnostic_setting_storage_for_singlecount: unexpected EOF
2019/04/18 17:18:11 [ERROR] root.appgateway-uiam: eval: *terraform.EvalSequence, err: azurerm_monitor_diagnostic_setting.diagnostic_setting_la_for_singlecount: unexpected EOF

### Panic Output

2019-04-18T17:18:11.832+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: panic: runtime error: index out of range

### Actual Behavior

* module.appgateway-uiam.azurerm_monitor_diagnostic_setting.diagnostic_setting_storage_for_singlecount: azurerm_monitor_diagnostic_setting.diagnostic_setting_storage_for_singlecount: unexpected EOF
* module.appgateway-uiam.azurerm_monitor_diagnostic_setting.diagnostic_setting_la_for_singlecount: 1 error(s) occurred:

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2019-04-23 09:47
hi @pratik141 

Thanks for opening this issue :)

Unfortunately the stack trace provided above is incomplete such that it's hard to diagnose the root-cause here; would it be possible for you to provide the ID of the resource and the full stack trace os that we can investigate this further?

Thanks!

**Comment by pratik141** [comment] 2019-04-23 13:16
HI @tombuildsstuff 

A full stack trace is not possible as credentials and other secret are there.  [log link](https://gist.github.com/pratik141/d29eaf46ef7b296b66d9877f8bcce19b)
Please let me know if you need any thing else

**Comment by tombuildsstuff** [comment] 2019-04-23 13:37
@pratik141 thanks for providing that.

```

2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: panic: runtime error: index out of range
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: goroutine 311 [running]:
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenApplicationGatewayAuthenticationCertificates(0xc0005eeb20, 0xc000709a40, 0x5, 0x0, 0x0)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:1276 +0x562
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmApplicationGatewayRead(0xc000709a40, 0x2de1ce0, 0xc00000c000, 0xc000709a40, 0x0)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:1113 +0x623
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc000257d50, 0xc000b5df90, 0x2de1ce0, 0xc00000c000, 0xc0000980b0, 0x4d4701, 0x29a7e20)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x167
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc00058eaf0, 0xc000b5df40, 0xc000b5df90, 0xc0004b8000, 0x2, 0xa6b2120)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x99
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc000004280, 0xc0008eb560, 0xc0008eb6e0, 0x0, 0x0)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x55
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: reflect.Value.call(0xc000116960, 0xc0000b6330, 0x13, 0x2ea3294, 0x4, 0xc000c33f18, 0x3, 0x3, 0xc000aab240, 0xc000081020, ...)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x45b
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: reflect.Value.Call(0xc000116960, 0xc0000b6330, 0x13, 0xc000c33f18, 0x3, 0x3, 0x2000100000001, 0xc000159d00, 0x100010000)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xab
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: net/rpc.(*service).call(0xc0004f4080, 0xc0009421e0, 0xc0005f2050, 0xc0005f2060, 0xc00012a680, 0xc000b359a0, 0x29a7de0, 0xc0008eb560, 0x16, 0x29a7e20, ...)
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x155
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: created by net/rpc.(*Server).ServeCodec
2019-04-23T17:45:20.044+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.25.0_x4.exe: 	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x485
```

**Comment by tombuildsstuff** [comment] 2019-04-23 13:39
Taking a look into this, this appears to be a duplicate of #2817 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2817 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-04-23 13:39 UTC
Labels: bug, crash, service/monitor
