### ISSUE TITLE
azurerm_kusto_eventhub_data_connection requires too many arguments

### ISSUE THREAD

**Issue by oliverchristen** [terraform-providers/terraform-provider-azurerm#10409] opened 2021-02-01 15:27 UTC
### Terraform (and AzureRM Provider) Version
Terraform v0.14.4
provider registry.terraform.io/hashicorp/azurerm v2.45.1

### Affected Resource(s)

* `azurerm_kusto_eventhub_data_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_kusto_eventhub_data_connection" "eventhub_connection" {
  name                = "conn-eventhubtodataexplorer"
  resource_group_name = "rg-01"
  location            = "West Europe"
  cluster_name        = "my-azure-data-explorer-cluster"
  database_name       = "my-adx-database"

  eventhub_id    = "<id of the event hub>"
  consumer_group = "myConsumerGroup"

  # table_name        = "" this argument is not required
  mapping_rule_name = "Json_Mapping"
  data_format       = "MULTIJSON"
}
```

### Expected Behaviour

terraform apply should run successfully because only mapping_rule_name is a required argument. table_name and data_format are optional.

### Actual Behaviour

Error: if one of the target table properties `table_name`, `mapping_rule_name` or `data_format` are set, the other values must also be defined

### Steps to Reproduce

1. Configure kusto_eventhub_data_connection as on: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_eventhub_data_connection
but without table_name argument.
2. `terraform apply`

**Comment by tombuildsstuff** [comment] 2021-02-01 17:05
hey @oliverchristen 

Taking a look through here there's a value assigned for the field `table_name` in that it's defined as an empty string, rather than `null` (or being omitted) where this would be unset - which is why the validation is raising this issue. As such it should be possible to fix this error by either unsetting this field, or if coalescing this value, using `null` rather than an empty-string for this field to indicate no value.

Since this should be fixed by updating the Terraform Configuration here I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2021-02-01 17:05 UTC
Labels: question

**Comment by oliverchristen** [comment] 2021-02-01 20:00
I tried all of your suggestions, an empty string, null and omitting. In the first case another validation error occurs which says that table_name must not be empty. Omitting the argument or setting it to null leads to the described error. So please reopen the issue as it cannot be fixed by changing the Terraform config.

**Comment by oliverchristen** [comment] 2021-02-01 20:01
But thanks for the great response time!

**Comment by oliverchristen** [comment] 2021-02-02 06:58
Hi @tombuildsstuff 
To make it more clear. In the example above the line with `table_name` is commented out.
Setting `table_name` to null (or omitting `table_name`) leads to error: `Error: if one of the target table properties table_name, mapping_rule_name or data_format are set, the other values must also be defined`
Setting `table_name` to an empty string leads to error: `table_name must not consist of whitespaces only`

**Comment by oliverchristen** [comment] 2021-02-03 10:34
@tombuildsstuff do you agree with me to reopen this issue?

**Comment by oliverchristen** [comment] 2021-02-22 13:49
@tombuildsstuff could you please have a look again and consider to reopen this issue?

**Comment by oliverchristen** [comment] 2021-02-22 14:51
@tombuildsstuff when I manually set those settings and refresh Terraform state, the problem occurs too which then blocks completely any changes to the Terraform configuration.

**Comment by tombuildsstuff** [comment] 2021-02-22 16:00
@oliverchristen per the error message:

```
if one of the target table properties table_name, mapping_rule_name or data_format are set, the other values must also be defined
```

which appears that this is working as intended, since there's an omitted value (in the first example) and an empty value (in the last) for `table_name` in both of the examples above - meaning both of these conditions would be triggered? As such you can work around this by either setting all 3 of the fields to a non-empty, non-whitespace value - or omitting these 3 fields?

**Comment by oliverchristen** [comment] 2021-02-22 16:29
@tombuildsstuff What I want to achieve is to leave `table_name` empty. This field is not required (even if `data_format` is set. Only `mapping_rule_name` is required) as you can see in the screenshot below. This can be saved in the portal successfully and works as it should do. So it should be possible to configure the data connection like this in Terraform too, shouldn't it?
![DataConnection](https://user-images.githubusercontent.com/12251419/108737130-93000a00-7532-11eb-96d9-1001aefe93c3.PNG)

**Comment by oliverchristen** [comment] 2021-02-24 14:49
@tombuildsstuff do you agree with me or don't you?

**Comment by oliverchristen** [comment] 2021-03-03 09:32
@tombuildsstuff I did not hear anything from you within over a week. What do you think about my objections?
