### ISSUE TITLE
Batch subresources PUTs

### ISSUE THREAD

**Issue by colemickens** [terraform-providers/terraform-provider-azurerm#214] opened 2017-08-04 13:51 UTC
This is sort of a meta question to start with. Is it possible to batch the PUTs of sub-resources. There's a specific term for it that I can't recall, but route_table entries and nsg rules are examples. They can exist as their own top level resource, or as nested under the single nsg object.

Can Terraform try to merge these together, especially in the initial creation? I'm seeing some initial network stuff take a long time to setup with Terraform and Azure and I think it's due to a lot of NSG rules, each needing their own PUT, + Azure operation time, + polling overhead.

But I'm not sure if this is something that the module provider can even exercise control over, or if you just provide the implementations for resources and get called by Terraform itself.

**Comment by nbering** [comment] 2017-08-04 14:45
I think hashicorp/terraform#2275 kind of covers this idea. Currently, the Terraform provider API allows for a resource to create sub-resources, on the underlying cloud provider, but these resources are not treated as independent by Terraform

So you can either include rules as part of a security group, or separately as individual rule resources, but not both. If you do both it creates a sort of race condition where each time you apply your config it will update the security group to match either the nested rules or the individual rules in an endless cycle.

**Comment by tombuildsstuff** [comment] 2017-08-11 11:40
Hey @colemickens 

Thanks for opening this issue - sorry for the delay in responding to this!

> There's a specific term for it that I can't recall, but route_table entries and nsg rules are examples. They can exist as their own top level resource, or as nested under the single nsg object.

Related: I've been wondering if it'd be worth consolidating these into a single resource, by deprecating either the nested or separate subnet resources in favour of the other - to remove confusion caused by conflicts?

> I'm seeing some initial network stuff take a long time to setup with Terraform and Azure and I think it's due to a lot of NSG rules, each needing their own PUT, + Azure operation time, + polling overhead.

From memory the Azure Networking API's only allow modifying one item within the same network stack at a time (i.e. Virtual Networks -> Subnets -> NSG's -> NSG Rule's) which means we're currently locking on the Virtual Network name within Terraform (losing the benefits of parallelisation) - which is why I would assume this is taking so long.

I would assume (however, I've not tested it) that you may get a speed benefit from combining these separate resources into the nested objects - if that's an option in the interim?

> Can Terraform try to merge these together, especially in the initial creation.

Potentially - however that would require a change to Terraform Core to support this. There's [an issue open on Terraform Core tracking this request](https://github.com/hashicorp/terraform/issues/7388), which contains details of what's needed to make this happen (some major changes to the graph), however one of the Terraform Core devs would be better to comment here.

Thanks!

**Comment by colemickens** [comment] 2017-08-11 18:26
>Related: I've been wondering if it'd be worth consolidating these into a single resource, by deprecating either the nested or separate subnet resources in favour of the other - to remove confusion caused by conflicts?

Does this change the reconciliation logic? My concern is that if you collapse the NSG Rules into the NSG object and PUT it, that it will clobber any rules that anyone else has put into the NSG.

cc: @brendandburns for comment on ARM/RP behaviors and/or recommendations. It does seem that, for example, nearly half the time in `tectonic-installer` for Azure is spent creating the NSGs+Rules due to the behavior as-is.

**Comment by tombuildsstuff** [comment] 2017-10-12 14:38
👋 hey @colemickens 

Apologies for the delayed response here.

>> Related: I've been wondering if it'd be worth consolidating these into a single resource, by deprecating either the nested or separate subnet resources in favour of the other - to remove confusion caused by conflicts?

> Does this change the reconciliation logic?

Having Network Security Rules nested within a Network Security Group means any rules not defined in-line within the NSG will be removed, so that's not _always_ ideal, but it depends on your setup (hence why the separate resource is available). On the flip side, the separate resource is most likely to be used with the `count` parameter and isn't likely to be referenced directly - so there's limited use-cases for it (but it's still valid). Feels like something that needs some thought in the long-term more than anything we'll be changing in the near future.

> for example, nearly half the time in tectonic-installer for Azure is spent creating the NSGs+Rules due to the behavior as-is.

In that scenario I'd recommend folding the Network Security Rules inside the Network Security Group if possible - which means they'd be a single API call - which should reduce the provisioning time somewhat.

Regarding the Batching of API calls - I'm going to suggest we close this issue in [favour of this issue in Terraform Core](https://github.com/hashicorp/terraform/issues/7388) (since this is a core enhancement, and not something specific we'd be able to implement in the provider)

Thanks!

**Closed by tombuildsstuff** 2017-10-12 14:38 UTC
Labels: enhancement, nsg, question, upstream-terraform
