### ISSUE TITLE
'azurerm_backup_protected_vm' should re-link existing association on apply

### ISSUE THREAD

**Issue by schuettecarsten** [terraform-providers/terraform-provider-azurerm#6995] opened 2020-05-19 07:34 UTC
Azure has a 14 days retention policy on azurerm_backup_protected_vm resources. That means, if you delete a VM and then re-create the VM, you have to re-use the old, soft-deleted azurerm_backup_protected_vm association resource. It's not possible to delete the old association resource and create a new one.

That's why I expect that the AzureRM provider simply re-links the existing association with the same name on terraform apply. Due to a different problem with terraform import (https://github.com/hashicorp/terraform/issues/24985), it is currently not possible to import the existing association.

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.25
+ provider.azurerm v2.9.0
``` 

### Affected Resource(s)

* azurerm_backup_protected_vm

### Error message

```
Error: A resource with the ID "/Subscriptions/<REMOVED>/resourceGroups/abc-p1/providers/Microsoft.RecoveryServices/vaults/abc-p1-backup/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;abc-p1;abcp1vm01/protectedItems/VM;iaasvmcontainerv2;abc-p1;abcp1vm01" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_backup_protected_vm" for more information.

  on ..\sharedmodules\backup_vm_policy_association\main.tf line 1, in resource "azurerm_backup_protected_vm" "default":
   1: resource "azurerm_backup_protected_vm" "default" {
```

**Comment by tombuildsstuff** [comment] 2020-05-19 12:59
hi @schuettecarsten 

Thanks for opening this issue

In version 2.0 of the Azure Provider we fixed a bug where resources that already existed in Azure could be "adopted" by Terraform, since Azure has Upsert API's for a lot of API's (more details can be found in #2807). This is important because whilst some Azure API's have Upsert API's - certain fields can only be changed on existing resources by deleting/re-creating these resources. As such when attempting to "create" a resource in version 2.0 or later of the Azure Provider, we first check for the presence of an existing resource with the same Name and Resource Group in Azure - and if this exists we ask that users import this via the error you're seeing.

Whilst the root cause of being unable to import this looks to be an issue in Terraform Core - unfortunately the Azure Provider is working as intended here by raising that an existing resource exists, since we require that users import existing resources into the state file - and as such unfortunately this isn't a behaviour we have plans to change and as such I'm going to close this issue for the moment. Instead I'd suggest following up in [the Terraform Core issue](https://github.com/hashicorp/terraform/issues/24985) where (with a reproducible example) - the Terraform Core team should be able to take another look.

Thanks!

**Closed by tombuildsstuff** 2020-05-19 12:59 UTC
Labels: question, service/recovery-services
