### ISSUE TITLE
Support for Monitor Private Link Scope (AMPLS) 

### ISSUE THREAD

**Issue by arj119** [terraform-providers/terraform-provider-azurerm#12161] opened 2021-06-10 15:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To connect Azure Monitor to resources in a secure way (through a private network / VNET), you need to set up an Azure Monitor Private Link Scope (AMPLS). This allows you, with a private endpoint, to monitor resources over a private connection without exfiltrating data over the public internet. There is no support for this is in any sense yet in the provider, however this is quite important for enterprise applications.

### New or Affected Resource(s)

* azurerm_monitor_private_link_scope
* azurerm_monitor_private_link_scoped_resource

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_private_link_scope" "example" {
  name                = "example_private_link_scope"
  resource_group_name = "<resource-group-name>"
  location            = "global"
}

resource "azurerm_monitor_private_link_scoped_resource" "example" {
  name                = "example_private_link_scope"
  resource_group_name = "<resource-group-name>"
  linked_resource_id  = "<resource-id>"
}

# The external_id (potential attribute) can then be used with a private endpoint
```

### References

* [Azure Monitor Private Link Scope docs](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-security#:~:text=In%20your%20Azure%20Monitor%20Application%20Insights%20component%20resource%2C,Private%20Link%20Scope.%20Select%20Apply%20to%20connect%20it.)

**Comment by tj-corrigan** [comment] 2021-06-10 20:04
dupe of #10059

**Closed** 2021-06-10 23:55 UTC
