### ISSUE TITLE
Api management's vnet configuation is reset after applying policy update to Api management

### ISSUE THREAD

**Issue by Sasa33** [terraform-providers/terraform-provider-azurerm#4100] opened 2019-08-15 22:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "apimanagement-vnet" {
  name                = "${var.api_management_vnet["name"]}"
  address_space       = ["${var.api_management_vnet["address_space"]}"]
  location            = "${azurerm_resource_group.resource_group.location}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"

  tags = {
    environment = "${var.tag["environment"]}"
  }
}

resource "azurerm_subnet" "apimanagement-subnet" {
  name                 = "${var.api_management["subnet_name"]}"
  address_prefix       = "${var.api_management["subnet_address_prefix"]}"
  resource_group_name  = "${azurerm_resource_group.resource_group.name}"
  virtual_network_name = "${azurerm_virtual_network.apimanagement-vnet.name}"
}

resource "azurerm_api_management" "api_management" {
  sku {
    name     = "${var.api_management["sku_name"]}"
    capacity = "${var.api_management["capacity"]}"
  }

  name                = "${var.api_management["name"]}"
  location            = "${azurerm_resource_group.resource_group.location}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  publisher_name      = "xxx"
  publisher_email     = "xxx"

  tags = {
    environment = "${var.api_management["environment"]}"
  }

  **policy {
    xml_content = <<XML
<policies>
    <inbound>
        <set-header name="Trace-Id" exists-action="skip">
            <value>....</value>
        </set-header>
    </inbound>
    <backend>
        <forward-request />
    </backend>
    <outbound />
    <on-error />
</policies>
XML
  }**
}
```

### Expected Behavior

I only added the policy part as the updated change, and I expect to see that the policy is updated.

### Actual Behavior
What we found is that the policy is been updated correctly after **26** minutes, but the virtual networks configuration is changed to "off"
![image](https://user-images.githubusercontent.com/12396552/63130313-9d296b80-bf7f-11e9-9a9d-07724e00dc9b.png)
And at that time, azure cannot forward request to our backend service.

We tried to run "terraform plan", but we didn't get any changes, which is weird.

Finally we have to manually change the vnet configuration back to "external".

### Steps to Reproduce

1. create a api management with  vnet and subnet configuation (in the api management configuration, don't set policy), apply the changes.

2. Update the configuration with the policy part, then apply the change.

3. Check the virtual network configuration in azure.

**Comment by tombuildsstuff** [comment] 2019-08-16 07:59
hi @Sasa33 

So that it's possible to reproduce this, would it be possible for you to confirm which version of Terraform and the Azure Provider you're using?

Thanks.

**Comment by Sasa33** [comment] 2019-08-16 14:21
hi @tombuildsstuff Thanks for your response

Terraform v0.12.6
+ provider.azurerm v1.32.1

**Comment by tombuildsstuff** [comment] 2019-11-21 11:44
hi @Sasa33 

Apologies for the delayed response here!

Unfortunately at this time [due to a bug in the Azure API](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582#issuecomment-468184451) attaching API Management Instances to a Virtual Network isn't fully supported by Terraform - and as such it appears that the Azure API is removing this Virtual Network association behind the scenes if it's not configured in the Request/Response (which we can't do since the current API version is broken; and and we're unable to upgrade to the fixed API version since the updated API also contains a bug).

Support for attaching API Management Instances to Virtual Networks is being tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3667 - from what I can see this bug will be resolved when support for that is available - as such rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #3667 for the moment - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2019-11-21 11:44 UTC
Labels: bug, service/api-management
