### ISSUE TITLE
Support for SSL bindings & certificates for App Services

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3600] opened 2019-06-05 16:05 UTC
As above

**Comment by tombuildsstuff** [comment] 2019-06-06 08:10
hi @cdesewell 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1136 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1136 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-06-06 08:10 UTC
