### ISSUE TITLE
Casing issues for Azure Front Door resource IDs [upgrade, import]

### ISSUE THREAD

**Issue by nmiodice** [terraform-providers/terraform-provider-azurerm#8231] opened 2020-08-24 19:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
**+ provider.azurerm v2.24.0**
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
```

### Affected Resource(s)

* `azurerm_frontdoor_firewall_policy`
* `azurerm_frontdoor_custom_https_configuration`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor_custom_https_configuration" "afd_https" {
  frontend_endpoint_id              = azurerm_frontdoor.afd.frontend_endpoint[1].id
  resource_group_name               = data.azurerm_resource_group.rg.name
  custom_https_provisioning_enabled = true
  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

```
resource "azurerm_frontdoor_firewall_policy" "waf" {
  name                = replace(format("%s-waf", local.prefix), "-", "")
  resource_group_name = data.azurerm_resource_group.rg.name
  managed_rule {
    type    = "DefaultRuleSet"
    version = "1.0"
  }
}
```

### Actual Behavior

* Terraform plan should not fail
* Terraform import should not fail

### Steps to Reproduce

**Terraform Provider Upgrade**
We are upgrading from `2.20.0` to `2.24.0` and I'm noticing some issues related to the casing on Front Door resources. 

Deploy AFD WAF rule in `2.20.0`, then upgrade to `2.24.0` and run `terraform refresh`. 

you should see this error:

```
Error: flattening `frontend_endpoint`: ID was missing the `frontDoorWebApplicationFirewallPolicies` element
```

**Terraform Import**
For the HTTPS configuration, I tried to import the config and got this error:
```
Error: Error parsing Resource ID "/subscriptions/.../resourcegroups/.../providers/Microsoft.Network/frontdoors/.../frontendendpoints/...": ID was missing the `frontendEndpoints` element
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-08-25 06:35
hi @nmiodice 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8208 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8208 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-25 06:35 UTC
Labels: duplicate, service/frontdoor
