### ISSUE TITLE
Support for workspace-based Application Insights

### ISSUE THREAD

**Issue by lobstermania** [terraform-providers/terraform-provider-azurerm#8575] opened 2020-09-22 14:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure app insights now supports multiple modes, "workspace based" and "classic". The Terraform resource "azurerm_application_insights" should also support this. 

### New or Affected Resource(s)

azure provider (v2.28.0)
"azurerm_application_insights" resource

### References

Azure docs for workspace-based AA: https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource
Terraform resource: https://www.terraform.io/docs/providers/azurerm/r/application_insights.html

**Comment by mybayern1974** [comment] 2020-09-25 03:54
hi @lobstermania , 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7667 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7667 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-09-25 03:54 UTC
Labels: duplicate
