### ISSUE TITLE
Incorrect/missing conflict warning - azurerm_lb_rule.name

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#308] opened 2017-09-05 17:59 UTC
### Terraform Version
Terraform version: 0.10.3
Go runtime version: go1.9
terraform-provider-azurerm_v0.1.6_x4

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_lb_rule

### Terraform Configuration Files
*main.tf*
```hcl
variable "rg_name"                      { }
variable "location"                     { }
variable "location_c"                   { }
variable "tag_env"                      { }
variable "tag_role"                     { }
variable "tag_service"                  { }


variable "count_vm"                       { }
variable "create_vm_pip"                  { }

# Remote state data source, no interpolations allowed
terraform {
  backend "azurerm" {
    # TF state file to be stored remotely. terraform.tfstate should remain the suffix
    key = "bug-prod-eastus.terraform.tfstate"

    # Default backend storage account for Terraform - DO NOT CHANGE
    storage_account_name = "infdevopswestus"
    
    # Default backend storage account for Terraform - DO NOT CHANGE
    container_name       = "terraform-state"
  }
}

# Configure TF provider: Microsoft Azure
provider "azurerm" {
  version         = "~> 0.1"
  subscription_id = "***"
  client_id       = "***"
  client_secret   = "***"
  tenant_id       = "***"
}

resource "azurerm_resource_group" "bug_eastus" {
  name     = "${var.rg_name}"
  location = "${var.location}"
}

data "azurerm_resource_group" "test" {
  name = "${azurerm_resource_group.bug_eastus.name}"
}
```

*plb.tf*
```hcl
variable "dns_label0" { }

data "azurerm_public_ip" "pip" {
    name = "${var.dns_label0}-${var.tag_env}-Pip"
    resource_group_name = "${data.azurerm_resource_group.test.name}"
}

# Pub IP to associate, routing directly to Bug
resource "azurerm_public_ip" "bug_lb" {
  name                         = "${var.dns_label0}-${var.tag_env}-Pip"
  location                     = "${var.location}"
  resource_group_name          = "${data.azurerm_resource_group.test.name}"
  public_ip_address_allocation = "dynamic"
  domain_name_label = "inf1-lb-bug"
}

# Azure LB config
resource "azurerm_lb" "bug" {
  name                = "Bug-${var.tag_env}-${var.location_c}-PLb"
  location            = "${var.location}"
  resource_group_name = "${var.rg_name}"

  frontend_ip_configuration {
    name                 = "PublicIPBugDirect"
    public_ip_address_id = "${azurerm_public_ip.bug_lb.id}"
  }
}

resource "azurerm_lb_backend_address_pool" "bug" {
  resource_group_name = "${var.rg_name}"
  loadbalancer_id     = "${azurerm_lb.bug.id}"
  name                = "BackEndAddressPool"
}

resource "azurerm_lb_rule" "bug_ssh" {
  resource_group_name            = "${var.rg_name}"
  loadbalancer_id                = "${azurerm_lb.bug.id}"
  name                           = "SSH"
  protocol                       = "Tcp"
  frontend_port                  = 22
  backend_port                   = 22
  load_distribution              = "SourceIP"
  frontend_ip_configuration_name = "PublicIPBugDirect"
  backend_address_pool_id        = "${azurerm_lb_backend_address_pool.bug.id}"
  probe_id                       = "${azurerm_lb_probe.ssh.id}"
}

resource "azurerm_lb_rule" "bug_https" {
  resource_group_name            = "${var.rg_name}"
  loadbalancer_id                = "${azurerm_lb.bug.id}"
  name                           = "HTTPS"
  protocol                       = "Tcp"
  frontend_port                  = 443
  backend_port                   = 443
  load_distribution              = "SourceIP"
  frontend_ip_configuration_name = "PublicIPBugDirect"
  backend_address_pool_id        = "${azurerm_lb_backend_address_pool.bug.id}"
}

resource "azurerm_lb_probe" "ssh" {
  resource_group_name = "${var.rg_name}"
  loadbalancer_id     = "${azurerm_lb.bug.id}"
  name                = "ssh-running-probe"
  port                = 22
}
```
*terraform.tfvars*
```hcl
# Resource Group
location     = "East US"
rg_name      = "PoC-Bug-Prod-EastUS-Rg"

#Environment Details
location     = "East US"
location_c   = "EastUS"
tag_env      = "Prod"
tag_role     = "Bug"
tag_service  = "Bug"

dns_label0   = "Bug"

count_vm        = 1       # Num of VMs to create
create_vm_pip   = "true" # Create PIPs for VMs ?
```

### Debug Output
[Terraform plan output](https://gist.github.com/samirageb/eddf66348f87a48d14a71e120742ee74)

[Terraform apply output](https://gist.github.com/samirageb/ffa90582ad884d3a5c732672d244fa97)

### Panic Output
None

### Expected Behavior
Terraform should inform me that there is a name conflict, before proceeding with provisioning OR terraform should have the logic in the plan to tell me that it is going to destroy 1, change 1.

### Actual Behavior
Terraform attempts to provision the rule, and will actually *overwrite* the pre-existing rule details. Terraform plan output shows that it is destroying/adding the rule that was updated. In reality, it appears to be tearing down the rule with the same name, and adding the changed rule in its place.

### Steps to Reproduce
1. Have 2 distinctly (azure) named lb rules, with different port mappings 
2. `terraform apply`
3. Change the Azure name of one rule to match the other
4. `terraform plan` - Note the lack of conflict detection
5. `terraform apply`
6. Check Azure to see the broken state, and 1 rule is overridden.

### References
None

**Comment by tombuildsstuff** [comment] 2018-04-17 11:42
hi @samirageb 

Thanks for this issue - apologies for the delayed response here!

Unfortunately this behaviour is by design due to the way the Azure API's work - where all API calls are Upserts/PUTs/PATCHs calls rather than Inserts and Updates. Whilst Terraform could (and probably should) fail as there's an existing rule with the same name - that wouldn't alleviate the problem of two resources having a matching name and being provisioned in parallel. We plan to tackle the former in an upcoming version of the AzureRM Provider - but the latter we have no means of solving at this point in time (since it should be caught during Terraform's Plan phase); as such I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2018-04-17 11:42 UTC
Labels: M1, bug, service/load-balancers
