### ISSUE TITLE
Support for azurerm_kubernetes_cluster, block default_node_pool, attr. mode needed

### ISSUE THREAD

**Issue by omichels** [terraform-providers/terraform-provider-azurerm#8161] opened 2020-08-18 17:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
default_node_pool lacks the attribute "mode",
while this attribute is available in 
resource azurerm_kubernetes_cluster_node_pool

if you were running a cluster with 2 node pools, this would be handy, when trying to drop the second pool,
as the second pool can only be dropped, if the remaining pool is in mode=System

### New or Affected Resource(s)
azurerm_kubernetes_cluster

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-08-18 17:51
hey @omichels 

Thanks for opening this issue.

The AKS API requires when provisioning a Kubernetes Cluster that it has at least one System Node Pool - as such the `default_node_pool` block is required (and is provisioned as a 'System' node pool). Whilst historically it wasn't possible to remove the default node pool - over time this has become possible and as such the issue #7093 is now (indirectly) tracking cycling this system node pool, which I believe should cover this requirement.

From our side whilst we could look to expose a `mode` property for this default node pool - where this is required to be `system` at creation time, in practice it'd probably make more sense to make this node pool entirely removeable (so system node pools can be defined entirely outside of this resource) and have these configured using the separate resources. This could either happen through an update to the AKS API to allow provisioning without a default node pool - or potentially using a temporary 'terraform' system node pool until a custom one exists (if a user hasn't specified one) - either way the "default_node_pool" block is unfortunately more of a hack than anything else, due to this requirement within the Azure API.

Whilst I'd like to thank you for opening this feature request - since this isn't something we plan to support at this time I'm going to close this issue for the moment; however as mentioned above I believe that ultimately this'll be fixed by #7093 (which would make it possible to cycle, and potentially remove the default node pool entirely) - as such would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-18 17:51 UTC
Labels: question, service/kubernetes-cluster

**Comment by omichels** [comment] 2020-08-18 19:02
I'm pretty confident that the default node pool is in mode=User, making it impossible to drop an additional node pool.
I will check that and come back with a testcase.

**Comment by manoatsas** [comment] 2020-09-03 18:15
I just confirmed mode value is "User" with default_node_pool. However, default agent pool created through Azure portal, has `mode=System` correctly.

I think this should be addressed since default_node_pool is required for `azurerm_kubernetes_cluster`. I believe #6058 addresses only for `azurerm_kubernetes_cluster_node_pool` and #7093 refers to updates.
