### ISSUE TITLE
App Service - Plan shows site_credentials in cleartext

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#7183] opened 2020-06-03 08:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
azurerm v2.12.0

### Affected Resource(s)

* `azurerm_app_service`

### Expected Behavior

No credentials should ever be printed in the logs in cleartext

### Actual Behavior

When `terraform plan` detects a change to an existing app service, it prints the site_credentials (password and username) in cleartext:

![image](https://user-images.githubusercontent.com/11445087/83614894-1da86f80-a586-11ea-9c88-cde2810014e1.png)

### Steps to Reproduce

Make any changes that cause an existing app service to be updated by terraform and run `plan`.

1. `terraform plan`

**Comment by tombuildsstuff** [comment] 2020-06-03 11:12
hi @sebader 

Thanks for opening this issue.

Taking a look into this, the root cause of [this appears to be this bug in the Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk/issues/201) - since this would be fixed there (rather than here) I'm going to close this issue for the moment - would you mind subscribing to that issue for updates? When the fix becomes available we'll pull it in and that should fix this.

Thanks!

**Closed by tombuildsstuff** 2020-06-03 11:12 UTC
Labels: service/app-service, upstream-terraform

**Comment by hbuckle** [comment] 2020-06-16 13:04
@tombuildsstuff - there seems to be very little interest in fixing the issue on the SDK side (unless you know any different?). The response from @paultyng was 

> The definitive response is treat it all as sensitive.

Given that, can we look to mark the whole block as sensitive on the AzureRM provider side?
