### ISSUE TITLE
azurerm_app_service ip restrictions requiring IP and Subnet Id

### ISSUE THREAD

**Issue by mluker** [terraform-providers/terraform-provider-azurerm#4383] opened 2019-09-19 15:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.4
+ provider.azuread v0.6.0
+ provider.azurerm v1.34.0

### Affected Resource(s)
* `azurerm_app_service`

### Terraform Configuration Files

```hcl
When setting ip_restrictions it seems both "ip_address" and "virtual_network_subnet_id" are required.
```

### Debug Output
Inappropriate value for attribute "ip_restriction": element 0: attributes
"ip_address" and "virtual_network_subnet_id" are required.

### Expected Behavior

Allowed to set up restrictions by only specifying an ip address and not a virtual network subnet id.

### Actual Behavior

When setting ip_restrictions it seems both "ip_address" and "virtual_network_subnet_id" are required.

### Steps to Reproduce

```
resource "azurerm_app_service" "app-service" {
  app_service_plan_id = "FooPlan"
  location            = "FooLocation"
  name                = "FooName"
  resource_group_name = "FooRG"

    site_config {
    ip_restriction = [{
        ip_address  = "10.199.1.1"
        subnet_mask = "255.255.255.255"
      } ]   
  }
}
```

Run
1. `terraform init`
2. `terraform plan`

**Comment by vpetersen** [comment] 2019-09-19 16:33
This just started happening to me yesterday as well in our AZDO pipeline.

**Comment by mattbowes** [comment] 2019-09-19 18:17
We are receiving the error as well. Downgrading the provider back to 1.33.1 fixes it

**Comment by alex-3sr** [comment] 2019-09-23 14:42
Hi,

I can confirm, I recently have all CICD release having this settings who are now failed and as quick workaround I just comment this part (the Ip restriction remain as just previous, so it's not remove).

Regards
Alex

**Comment by kraihn** [comment] 2019-10-04 13:48
I was able to bypass the error by changing my ip_restriction block

from this
```
site_config {
    ip_restriction = [
      for address in var.allowed_ip_addresses : {
        ip_address  = address
        subnet_mask = "255.255.255.255"        
      }
    ]
  }
```

to this
```
site_config {
    dynamic "ip_restriction" {
      for_each = var.allowed_ip_addresses
      content {
        ip_address  = ip_restriction.value
        subnet_mask = "255.255.255.255"
      }
    }
  }
```

It makes me wonder if the issue isn't really the app_service resource, but with Terraform in how multiple blocks vs arrays are handled.

**Comment by antgonmir** [comment] 2020-03-26 08:20
Is there a workaround if you need to set restrictions based on both ip addresses and subnets? Terraform validate seems to fail because "both are required" and then Terraform plan fails because "only one needs to be supplied".

I'm using Terraform version: 0.12.24 and azurerm version: 2.2.0

The azurerm version provider 1.33.1 doesn't recognize fields like os_type for function apps, which makes deploying a linux function app challenging.

**Comment by sephross** [comment] 2020-04-01 04:27
Could someone please point me to an accurate example of ip_restriction being used? As per the previous example of the workaround posted above, it seems odd that I would need to use a dynamic block to add a single IP address.

When I try to add a single IP address without using a dynamic block I get the following error:

"Inappropriate value for attribute "ip_restriction": list of object required."

Also the documentation for this on https://www.terraform.io/docs/providers/azurerm/r/app_service.html is wrong.

Thanks,

**Comment by Heer-Boaz** [comment] 2020-07-23 16:09
For anyone encountering the same problem, this is a simple work-around to use:
For anyone facing this issue - there is a simple work-around that I verified to work in version 0.12.28.
Note the `ip_address = null` and populating both `virtual_network_subnet_id` and `subnet_id`.
```
    ip_restriction = [
      {
        ip_address                = null
        virtual_network_subnet_id = <reference_to_id>
        subnet_id                 = <reference_to_id>
        name                      = "<name>"
        description               = "<description>"
        priority                  = 10000
        action                    = "Allow"
      },
	  (...)
    ]
```

**Comment by ksooner** [comment] 2020-08-20 06:59
thanks @Heer-Boaz , your example did work for me and tf apply working but when i look at the azure resources, they are not right and all the priorities showing 65000, and empty names

![image](https://user-images.githubusercontent.com/27767208/90727228-47ac3b00-e306-11ea-89b6-4321edffcc77.png)

**Comment by tombuildsstuff** [comment] 2020-08-21 04:48
👋🏻

Taking a look through here it appears that this is possible [as is shown in @Heer-Boaz's comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4383#issuecomment-663095239) - and as such I'm going to close this issue for the moment - but if you're still having issues I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-08-21 04:48 UTC
Labels: question, service/app-service
