### ISSUE TITLE
Resource azurerm_private_link_endpoint has incorrect regex for subresource_names

### ISSUE THREAD

**Issue by rafa-pizzi** [terraform-providers/terraform-provider-azurerm#5128] opened 2019-12-11 05:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
`Terraform v0.12.16`
`provider.azurerm v1.38.0`

### Affected Resource(s)

* `azurerm_private_link_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_private_link_endpoint" "my_endpoint" {
  name                = "private-endpoint"
  location            = "australiaeast"
  resource_group_name = "my-rg-name"
  subnet_id           = "my-subnet-id"

  private_service_connection {
    name                           = "db-private-service"
    is_manual_connection           = false
    private_connection_resource_id = "sqlserverdbid"
    subresource_names              = ["sqlServer"]
  }
}
```

### Debug Output
When planning:
`Error: private_service_connection.0.subresource_names.0 must only contain upper or lowercase letters, numbers, underscores, and periods`

if no value is provided to subresource_names, then plan passes, but apply throws:
`Error: Error creating Private Link Endpoint "pg-private-endpoint" (Resource Group "RG-SYD-NPDI1-APIGW-CORE"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingParameterOnPrivateLinkServiceConnection" Message="Private link service connection /subscriptions/2dc11414-bef5-434e-824c-8c297e2c498e/resourceGroups/RG-SYD-NPDI1-APIGW-CORE/providers/Microsoft.Network/privateEndpoints/pg-private-endpoint/privateLinkServiceConnections/pg-private-service is missing required parameter 'group Id'." Details=[]`

### Panic Output
N/A

### Expected Behavior
The subresource_names under block private_service_connection expects a list of resources names. According to TF documentation, it asks you to refer to a [DNS](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#dns-configuration) configuration: (weird, but I agree the documentation on it is still not very good).
When planning, I'd expect that the subresource_names ["sqlServer"] would accept this value, and plan accordingly. It's not clear what kind of string is expected (I've tried a few), and my understanding this parameter is "mandatory" if the private_connection_resource_id is not a private link service but a PaaS service.

My expectation is that the Plan should have executed

### Actual Behavior
Errors as above

### Steps to Reproduce

`terraform plan`

**Comment by tombuildsstuff** [comment] 2019-12-11 12:00
hi @rafa-pizzi 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5110 - which has been fixed in #5118 which will make it into the next release. Since this has been fixed via #5118 I'm going to close this issue for the moment - but I'm going to assign this to the v1.39 milestone so that @hashibot will comment when this has been released.

Thanks!

**Closed by tombuildsstuff** 2019-12-11 12:00 UTC
Labels: bug, service/private-link
