### ISSUE TITLE
Can't run acceptance tests in this repo: no "permission to use the Resource Manager API"

### ISSUE THREAD

**Issue by gukoff** [terraform-providers/terraform-provider-azurerm#12391] opened 2021-06-28 11:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

N/A

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Debug Output

https://gist.github.com/gukoff/c11759511a2f49b8cd9516b561d6d9a8

### Panic Output

N/A

### Expected Behaviour

Acceptance tests can run.

### Actual Behaviour

Acceptance tests fail with allegedly missing permissions.

### Steps to Reproduce

1. Create an app registration following [these instructions](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#register-an-application-with-azure-ad-and-create-a-service-principal). This will be service principal.
2. Set all necessary env variables:
```
set -x ARM_CLIENT_ID "XXX"
set -x ARM_CLIENT_SECRET "YYY"
set -x ARM_TENANT_ID "ZZZ"
set -x ARM_SUBSCRIPTION_ID "XYZ"
```
3. Run one of the acceptance tests with `make acctests SERVICE=applicationinsights TESTARGS='-run=TestAccApplicationInsights_basicPhone'`

4. [It fails](https://gist.github.com/gukoff/c11759511a2f49b8cd9516b561d6d9a8).

### Important Factoids

I also gave both app registration (my service principal) and enterprise app (it was auto-created when I created app registration) full permissions to Azure Service Management API. It didn't help.

![image](https://user-images.githubusercontent.com/5655837/123631044-970ca300-d816-11eb-9433-101aa1f645d4.png)

I'm using Visual Studio Enterprise subscription, and it has `Microsoft.Resources` provider enabled:

![image](https://user-images.githubusercontent.com/5655837/123631424-07b3bf80-d817-11eb-90f6-d073d91cd23c.png)

If there's a way to auth with `az` instead of setting these env variables, it could help.

### References

N/A

**Comment by aristosvo** [comment] 2021-06-29 10:37
In bash:
```
#!/bin/bash

# This is the name of the service principal for TerraForm
AZURE_TF_SP_NAME=tst-tf-sp
# This is the id of your subscription
AZURE_SUBSCRIPTION=<>
# This is the name of the resource group that can be used to scope your permissions.., not enough for Acceptance Testing
AZURE_TF_RESOURCE_GROUP=tst-rg

# The service principal for TerraForm. Should have access on subscription level, resource group or resource level
TF_SP=$(az ad sp create-for-rbac -n $AZURE_TF_SP_NAME --role contributor --scope /subscriptions/$AZURE_SUBSCRIPTION)
# or on rg level:
# TF_SP=$(az ad sp create-for-rbac -n $AZURE_TF_SP_NAME --role contributor --scope /subscriptions/$AZURE_SUBSCRIPTION/resourceGroups/$AZURE_TF_RESOURCE_GROUP)
AZURE_TF_SP_APP_ID=$(echo $TF_SP | jq -r '.appId')
AZURE_TF_SP_PASSWORD=$(echo $TF_SP | jq -r '.password')
AZURE_TENANT=$(echo $TF_SP | jq -r '.tenant')
# Extra assigments:

# Check Permissions:
echo "Permissions TerraForm service principal"
az role assignment list --all --assignee $AZURE_TF_SP_APP_ID

# Get the variables:
echo "ARM_CLIENT_ID=$AZURE_TF_SP_APP_ID"
echo "ARM_CLIENT_SECRET=$AZURE_TF_SP_PASSWORD"
echo "ARM_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION"
echo "ARM_TENANT_ID=$AZURE_TENANT"
```

**Comment by manicminer** [comment] 2021-07-19 17:35
Hi @gukoff, thanks for opening this issue. Whilst the permissions you have applied are for the correct API, the provider does not use delegated auth and so these permissions will not have any effect (the `user_impersonation` scope would only apply if you were signing into Terraform using your own user credentials, e.g. via three legged oauth).

The error message does have some preamble but the root cause is there:
> The client '852b7e47-d83c-4129-a585-e440225ed787' with object id '852b7e47-d83c-4129-a585-e440225ed787' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/d44e9a58-e868-47b1-8b09-c8c1f4b9804a' or the scope is invalid.

The service principal must have access in its own capacity to the Azure resources you want to manage. You can do this by assigning a suitable IAM role to the service principal, for the resource (e.g. a subscription) that you want to manage. If you can run Terraform using service principal authentication supplied via environment variables, then you have the appropriate configuration to run the acceptance tests.

As this is more of a usage question, I'm going to close this one for now. If you have further issues, a good way to try out your credentials is with the Azure CLI using `az login --service-principal`.

**Closed by manicminer** 2021-07-19 17:35 UTC
Labels: authentication, question
