### ISSUE TITLE
Support for audit policy on azure sql server

### ISSUE THREAD

**Issue by RegePushkar** [terraform-providers/terraform-provider-azurerm#5008] opened 2019-11-27 20:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Enable audit policy for Azure sql server (see https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing)

### New or Affected Resource(s)
* azurerm_sql_server

### Potential Terraform Configuration

```hcl
audit_policy {
   state = "Enabled"
   storage_account = "storageAccount"
   actions = ["BATCH_COMPLETED_GROUP", "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP", "FAILED_DATABASE_AUTHENTICATION_GROUP"]
}
```

### References
 The Azure API documentation https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing

* #0000

**Comment by tombuildsstuff** [comment] 2019-11-28 06:14
hi @RegePushkar 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2217 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2217 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-11-28 06:14 UTC
Labels: duplicate, enhancement, service/mssql
