### ISSUE TITLE
Support for custom headers on azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by jmcshane** [terraform-providers/terraform-provider-azurerm#8223] opened 2020-08-24 13:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS is enabling many preview features via custom headers that are set on the resources. 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
 ...
  custom_header = {
    "EnableEphemeralOSDisk" = "true"
    "CustomizedUbuntu" = "aks-ubuntu-1804"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#os-configuration-preview
* https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os-preview

**Comment by jmcshane** [comment] 2020-08-24 13:42
See https://github.com/Azure/azure-sdk-for-go/issues/11692

**Comment by tombuildsstuff** [comment] 2020-08-24 13:47
hi @jmcshane 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6793 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-24 13:47 UTC

**Comment by jmcshane** [comment] 2020-08-24 13:58
Ah sorry about that @tombuildsstuff. I searched for this issue in the repo, but somehow missed the main one. Thanks
