### ISSUE TITLE
azurerm_recovery_services_protected_vm force new resource (recreate) instead of updating

### ISSUE THREAD

**Issue by horpek** [terraform-providers/terraform-provider-azurerm#3793] opened 2019-07-05 06:24 UTC
## Community Note
•	Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
•	Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
•	If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Terraform (and AzureRM Provider) Version
Terraform v0.11.10
AzureRM v1.31.0

## Affected Resource(s)
•	azurerm_recovery_services_protected_vm

## Terraform Configuration Files
resource "azurerm_recovery_services_protected_vm" "instance" {
  count               = "${var.vm_settings["backup_policy"] == "none" ? 0 : length(compact(local.vm_names))}"

  resource_group_name = "${element(split("/", var.recovery_vault_map[var.vm_settings["backup_policy"]]), 4)}"
  recovery_vault_name = "${element(split("/", var.recovery_vault_map[var.vm_settings["backup_policy"]]), 8)}"
  source_vm_id        = "${element(azurerm_virtual_machine.instance.*.id, count.index)}"
  backup_policy_id    = "${var.recovery_vault_map[var.vm_settings["backup_policy"]]}"

  depends_on = ["azurerm_virtual_machine.instance"]
}

## Expected Behavior
When we change the backup policy for the VM, terraform (or actually it is the azurerm provider) force a new resources instead of updating it.  This deletes all existing recovery points (i.e. backup images) taken with existing backup policy.  In Azure portal, it is an in place update called switching backup policy and it preserve all existing recovery points.
Actual Behavior
Terraform deletes all recovery points, delete the protected_vm item and creates it.  

And during this process, terraform issues the destroy and create instructions to Azure almost one after another and it causes a “locking issue”:
11:14:22 2 error(s) occurred:
11:14:22 
11:14:22 * module.3bp0sv.azurerm_recovery_services_protected_vm.instance: 1 error(s) occurred:
11:14:22 
11:14:22 * azurerm_recovery_services_protected_vm.instance: Error waiting for the Recovery Service Protected VM "VM;iaasvmcontainerv2;rsg-3bp0sv;rtpru322ououhsc" to be true (Resource Group "rsg-recoveryvault") to provision: timeout while waiting for state to become 'Found' (last state: 'NotFound', timeout: 30m0s)
11:14:22 * module.3bp0sv_1.azurerm_recovery_services_protected_vm.instance: 1 error(s) occurred:
11:14:22 
11:14:22 * azurerm_recovery_services_protected_vm.instance: Error waiting for the Recovery Service Protected VM "VM;iaasvmcontainerv2;rsg-3bp0sv;rtpru3li4yk1t89" to be true (Resource Group "rsg-recoveryvault") to provision: timeout while waiting for state to become 'Found' (last state: 'NotFound', timeout: 30m0s)

 

The error message from Azure activity log:
{ "Entity Name": "rtpru3li4yk1t89", "Job Id": "xxx77bf3-xxxx-xxxx-xxxx-2c6ff14b7xxx", "Start Time": "2019-07-05 02:44:20Z", "Failure Details": "Another operation is in progress on the selected item. If there is an in-progress operation, please retry after it has finished." }

"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[
{\"code\":\"BMSUserErrorObjectLocked\",\"message\":\"Another operation is in progress on the selected item.\"}
 
Rerunning the deployment after the first failure will trigger the creation (as the out-going protected_vm item is already destroyed) and ended successfully

## Steps to Reproduce
1.	deploy a VM with terraform and configure backup with azurerm_recovery_services_protected_vm.  Take a backup of the VM – this will create a recovery point.
2.	update the terraform configuration file with another backup_policy_id.
3.	Redeploy the terraform configuration and it will force new resource and will hit the error.  And the recovery point is deleted.

**Comment by horpek** [comment] 2019-07-05 06:37
I think it a feature request and an issue I brought up here:
  
**Feature request**: Can we make the "azurerm_recovery_services_protected_vm" provider updating the protected_vm item instead of recreating it?  So existing recovery points (backup images) can be preserved.  This can be done with Azure portal.

**Issue**: As current provider will recreate the resources, the creation did not wait for the deletion to complete and it fails as the resource is locked.

**Comment by ymash13** [comment] 2019-10-31 21:38
Any updates on this issue? Now the problem is bigger because Terraform apply fails with errors due to Azure soft deletes where you cannot remove the recovery vault item.

error: Error waiting for the Recovery Service Protected VM "VM;iaasvmcontainerv2;" to be true (Resource Group "") to provision: timeout while waiting for state to become 'Found' (last state: 'NotFound', timeout: 30m0s)

**Comment by wsmithCTP** [comment] 2019-11-06 21:46
@ymash13 I believe [#3822](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3822) fixes the original intent of this request and was released in provider [v1.32.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1320-july-24-2019).

I believe the soft delete problem is a separate (and frustrating) issue.

**Comment by tombuildsstuff** [comment] 2019-11-18 11:04
Fixed via #3822 - the Azure API not supporting soft delete is being discussed in #4774 - this is something that Microsoft are investigating supporting toggling on/off at some point, so we'll track that in #4774 for the moment

**Closed by tombuildsstuff** 2019-11-18 11:04 UTC
Labels: enhancement, service/recovery-services
