### ISSUE TITLE
Import AKS forces new resources when RBAC is enabled

### ISSUE THREAD

**Issue by janbrunrasmussen** [terraform-providers/terraform-provider-azurerm#2368] opened 2018-11-21 09:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Importing an existing AKS cluster, with RBAC with Active Directory enabled, forces a new resource.

### Terraform (and AzureRM Provider) Version
- Terraform v0.11.10
- provider.azurerm v1.19.0

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
...
  role_based_access_control {
    azure_active_directory {
      client_app_id = "<client_app_id>"
      server_app_id = "<server_app_id>"
      server_app_secret = "<server_app_secret>"
      tenant_id = "<tenant_id>"
    }
  }
...
}
```

### Debug Output
```
azurerm_kubernetes_cluster.aks (new resource required)
      id:                                                                     "/subscriptions/{subscription}/resourceGroups/{resourcegroup}/providers/Microsoft.ContainerService/managedClusters/test-import-aks" => <computed> (forces new resource)
      addon_profile.#:                                                        "1" => <computed>
      agent_pool_profile.#:                                                   "1" => "1"
      agent_pool_profile.0.count:                                             "2" => "2"
      agent_pool_profile.0.dns_prefix:                                        "" => <computed>
      agent_pool_profile.0.fqdn:                                              "{fqdn}" => <computed>
      agent_pool_profile.0.max_pods:                                          "110" => <computed>
      agent_pool_profile.0.name:                                              "nodepool1" => "nodepool1"
      agent_pool_profile.0.os_disk_size_gb:                                   "30" => <computed>
      agent_pool_profile.0.os_type:                                           "Linux" => "Linux"
      agent_pool_profile.0.vm_size:                                           "Standard_DS2_v2" => "Standard_DS2_v2"
      dns_prefix:                                                             "{dns-prefix}" => "test-import-aks"
      fqdn:                                                                   "{fqdn} => <computed>
      kube_config.#:                                                          "1" => <computed>
      kube_config_raw:                                                        <sensitive> => <computed> (attribute changed)
      kubernetes_version:                                                     "1.11.3" => "1.11.3"
      linux_profile.#:                                                        "1" => "1"
      linux_profile.0.admin_username:                                         "azureuser" => "azureuser"
      linux_profile.0.ssh_key.#:                                              "1" => "1"
      linux_profile.0.ssh_key.0.key_data:                                     "{public key}"
      location:                                                               "westeurope" => "westeurope"
      name:                                                                   "test-import-aks" => "test-import-aks"
      network_profile.#:                                                      "1" => <computed>
      node_resource_group:                                                    "{node resourcegroup}" => <computed>
      resource_group_name:                                                    "{resourcegroup}" => "{resourcegroup}"
      role_based_access_control.#:                                            "1" => "1"
      role_based_access_control.0.azure_active_directory.#:                   "1" => "1"
      role_based_access_control.0.azure_active_directory.0.client_app_id:     "{client_app_id}" => "{client_app_id}"
      role_based_access_control.0.azure_active_directory.0.server_app_id:     "{server_app_id}" => "{server_app_id}"
      role_based_access_control.0.azure_active_directory.0.server_app_secret: <sensitive> => <sensitive> (forces new resource)
      role_based_access_control.0.azure_active_directory.0.tenant_id:         "{tenant_id}" => "{tenant_id}"
      service_principal.#:                                                    "1" => "1"
      service_principal.2452071114.client_id:                                 "{client_id}" => "{client_id}"
      service_principal.2452071114.client_secret:                             <sensitive> => <sensitive> (attribute changed)
```

### Expected Behavior
AKS cluster should be imported under terraform management
### Actual Behavior
A new resource is forced based on `server_app_secret` (and `id`?) when running `terraform plan`

### Steps to Reproduce

1. Create cluster with cli `az aks create ...`
2. Add terraform config to match existing cluster
3. `terraform init`
4. `terraform import azurerm_kubernetes_cluster.aks <AKS resource id>`
1. `terraform plan`

### References

This issue is related, but for the ssh key data, which seems to be fixed.
*https://github.com/terraform-providers/terraform-provider-azurerm/issues/1806

**Comment by Starefossen** [comment] 2019-02-18 10:58
@janbrunrasmussen did you ever find a way to solve this, same issue here apparently...

**Comment by janbrunrasmussen** [comment] 2019-02-18 14:17
No, though I saw certain things around rbac changed in the provider, so I hoped that would fix it, but apparently not!? We decided to recreate clusters when the opportunity presents it-self.

**Comment by guitmz** [comment] 2019-03-04 14:14
this issue is still present with the current provider version :(

**Comment by eneault** [comment] 2019-03-28 18:35
same issue

azurerm 1.23.0
azuread 0.2.0

**Comment by gree-gorey** [comment] 2019-04-01 12:42
Same here.
As a workaround I used:
```hcl
lifecycle {
  ignore_changes = ["role_based_access_control"]
}
```
but it's obviously not the best solution.

**Comment by neil-yechenwei** [comment] 2020-05-09 12:36
Thanks for opening this issue. Seems there is no difference anymore for `tf plan` after tried with above repro steps. Maybe I missed something. If you need, you can try below tfconfig with above repro steps to check whether the problem still exists.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-aks-neil"
  location = "westus2"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestaksneil"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestaksneil"

  linux_profile {
    admin_username = "acctestuserneil"

    ssh_key {
      key_data = "xxxxxx"
    }
  }

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
  }
}
```

**Comment by ArcturusZhang** [comment] 2020-06-05 08:53
Hi @janbrunrasmussen 

Since this issue has been opened for quite a long time, and we cannot reproduce this issue on the latest version of the provider, I would close this issue hope you would not mind. 

If you find this issue persist, please feel free to reopen, comment, or open a new issue regarding the new version of the provider.

Thank you!

**Closed by ArcturusZhang** 2020-06-05 08:53 UTC
Labels: question, service/kubernetes-cluster
