### ISSUE TITLE
Azure private DNS zones v2

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#3738] opened 2019-06-27 01:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New preview of Azure private DNS zones with different API endpoint.

### New or Affected Resource(s)

* azurerm_dns_zone

### References

* https://azure.microsoft.com/en-us/updates/announcing-preview-refresh-for-azure-dns-private-zones-2/

**Comment by donestefan** [comment] 2019-06-27 07:59
Duplicate of #3714

**Comment by davidobrien1985** [comment] 2019-06-27 21:53
@donestefan not really... #3714 asks to split out private DNS zones into their own resources, instead of having a `Private` or `Public` property on the `azurerm_dns_zone` resource.

I'm here saying that there is a new API for private DNS zones, so really, #3738 and #3714 should be combined.

**Comment by timja** [comment] 2019-08-07 07:27
It is a duplicate?
The api is completely different under the hood, it's another resource.

**Comment by tombuildsstuff** [comment] 2019-10-02 05:44
hi @davidobrien1985 

Thanks for opening this issue :)

Taking a look through support for this new API has been added and [is now available as the `azurerm_private_dns_zone ` resource](https://www.terraform.io/docs/providers/azurerm/r/private_dns_zone.html) - would you be able to take a look and see if that works for you? The older preview fields are unsupported and will be removed in 2.0 - since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2019-10-02 05:44 UTC
Labels: new-resource, service/dns
