### ISSUE TITLE
azurerm_container_group: Error when diagnostics.log_analytics.log_type is set to ContainerInstanceLogs

### ISSUE THREAD

**Issue by kalekale** [terraform-providers/terraform-provider-azurerm#3216] opened 2019-04-09 14:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "1.24"
}

resource "azurerm_resource_group" "group" {
  name     = "myGroup"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "logs" {
  location            = "${azurerm_resource_group.group.location}"
  resource_group_name = "${azurerm_resource_group.group.name}"
  sku                 = "PerGB2018"
  retention_in_days   = 30
  name                = "myTestWorkspace"
}

resource "azurerm_container_group" "backend" {
  name = "backend"
  resource_group_name = "${azurerm_resource_group.group.name}"
  location = "${azurerm_resource_group.group.location}"
  os_type = "linux"
  diagnostics = {
    log_analytics = {
      log_type = "ContainerInsights"
      workspace_id = "7ccdaecd-2b50-4935-8744-f7789193c19e"
      workspace_key = "EpgI/EQmnv2yF42hgguMJAAEgGnxIfSgm14H9jhXoGg1Rp8ZovBkXwdR8Ghja0PSZsJDBltl3tASdqi1o3+LSA=="
    }
  }
  container = {
    name ="backend"
    image = "microsoft/aci-helloworld"
    cpu = "1"
    memory = "1.5"
    ports  = {
      port     = 80
      protocol = "TCP"
    }
  }
}
```

### Debug Output

https://gist.github.com/kalekale/6bdb26839a270961036fe1b8d657d9f5

### Expected Behavior

Create a container instance with logs sent to the log analytics workspace.

### Actual Behavior

Creation of container instance fails with:
```
2019-04-09T17:33:03.726+0300 [DEBUG] plugin.terraform-provider-azurerm_v1.24.0_x4: 2019/04/09 17:33:03 [ERR] plugin: plugin server: accept unix /var/folders/mb/wwjql4xx187_lkg4kzsjv02r0000gn/T/plugin399990517: use of closed network connection
* azurerm_container_group.backend: Error creating/updating container group "backend" (Resource Group "myGroup"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Error converting value \"ContainerInstanceLogs\" to type 'System.Nullable`1[Microsoft.Azure.CloudConsole.Providers.Common.Entities.LogAnalyticsLogType]'. Path 'properties.diagnostics.logAnalytics.logType', line 1, position 458.'."
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Works when `log_type` is set to `"ContainerInsights"`, but not `"ContainerInstanceLogs"`.

**Comment by miikka** [comment] 2019-07-10 13:27
This may be a bug in Azure – it seems to me that the AzureRM provider is doing a Create or Update API call that is valid according to the [API documentation](https://docs.microsoft.com/fi-fi/rest/api/container-instances/containergroups/createorupdate).

If that is the case, there's a potential workaround that could be implemented in the AzureRM provider: if you leave out the `logType` and `metadata` parameters entirely, the end result seems to be that you do get the Container Instance logs to your log analytics workspace.

**Comment by miikka** [comment] 2019-07-22 12:01
I contained Azure customer support about this a while ago and `"ContainerInstanceLogs"` seems to work correctly now.

**Comment by neil-yechenwei** [comment] 2020-06-08 08:12
Thanks for opening this issue. Seems it's a Service API issue. I raised an issue on Azure/azure-rest-api-specs#9768

**Comment by haaranenjarmo** [comment] 2020-07-29 11:48
Correct log_types are ContainerInsights and ContainerInstance

**Comment by miikka** [comment] 2020-07-29 13:31
> Correct log_types are ContainerInsights and ContainerInstance

How do you figure this out? The [docs](https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/list#loganalyticslogtype) still say it's `ContainerInsightsLogs`

**Comment by dankingobj** [comment] 2020-10-29 00:56
I've confirmed that removing the `"metadata":{}` section from the API call works - e.g.

`"diagnostics":{"logAnalytics":{"logType":"ContainerInstanceLogs","metadata":{},"workspaceId":"XXX","workspaceKey":"YYY=="}}

->

"diagnostics":{"logAnalytics":{"logType":"ContainerInstanceLogs","workspaceId":"XXX","workspaceKey":"YYY=="}}`

But as clook pointed out on the Azure issue, it feels weird to ignore the auto-generated documentation, but we're still looking at a broken option that people will want 5 months later.

**Comment by haaranenjarmo** [comment] 2020-10-29 14:31
> > Correct log_types are ContainerInsights and ContainerInstance
> 
> How do you figure this out? The [docs](https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/list#loganalyticslogtype) still say it's `ContainerInsightsLogs`

macolso comment on https://github.com/Azure/azure-rest-api-specs/issues/9768 and this is a bug in Azure rest api. Last stable rest api is still 2019-12-01. So they haven't fixed it.

**Comment by katbyte** [comment] 2023-07-19 16:40
I am going to close this as it was opened for `v1.x` of the provider (2 major versions ago) which is no longer actively maintained. 

If this is still an issue with `v3.x` of the provider please do let us know, thanks!

**Closed as completed by katbyte** 2023-07-19 16:40 UTC
Labels: bug, upstream/microsoft, service/log-analytics, v/1.x (legacy)

**Comment by trygvis** [comment] 2024-01-31 19:36
This is still an issue, see https://github.com/Azure/azure-rest-api-specs/issues/9768#issuecomment-1771041233

**Comment by esdccs1** [comment] 2024-03-11 17:09
I'm still getting this issue on the latest provider 3.95
