### ISSUE TITLE
azurerm_log_analytics_solution - Status=404 Code="Unknown" Message="Unknown service error" Details=[{"error":{"code":"NotFound"}}]

### ISSUE THREAD

**Issue by fluffy-cakes** [terraform-providers/terraform-provider-azurerm#2339] opened 2018-11-16 16:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
λ terraform -v
Terraform v0.11.10
+ provider.azurerm v1.18.0

### Affected Resource(s)

* azurerm_log_analytics_solution

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_solution" "loganalytics-solution-startstop" {
  solution_name         = "VmManagementSolution"
  location              = "${azurerm_resource_group.rg-loganalytics.location}"
  resource_group_name   = "${azurerm_resource_group.rg-loganalytics.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.loganalytics-workspace.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.loganalytics-workspace.name}"
  provider              = "azurerm.subPRD"

  plan {
    publisher           = "Microsoft"
    product             = "OMSGallery/VmManagementSolution"
  }
}
```

### Debug Output

```
azurerm_log_analytics_solution.loganalytics-solution-startstop: Creating...
  location:              "" => "westeurope"
  plan.#:                "" => "1"
  plan.0.name:           "" => "<computed>"
  plan.0.product:        "" => "OMSGallery/VmManagementSolution"
  plan.0.publisher:      "" => "Microsoft"
  resource_group_name:   "" => "rg-mgt-loganalytics"
  solution_name:         "" => "VmManagementSolution"
  workspace_name:        "" => "loganalytics-mgt"
  workspace_resource_id: "" => "/subscriptions/MY-SUBSCRIPTION/resourcegroups/rg-mgt-loganalytics/providers/microsoft.operationalinsights/workspaces/loganalytics-mgt"

Error: Error applying plan:

1 error(s) occurred:

* azurerm_log_analytics_solution.loganalytics-solution-startstop: 1 error(s) occurred:

* azurerm_log_analytics_solution.loganalytics-solution-startstop: Error creating/updating Log Analytics Solution "VmManagementSolution(loganalytics-mgt)" (Workspace "/subscriptions/MY-SUBSCRIPTION/resourcegroups/rg-mgt-loganalytics/providers/microsoft.operationalinsights/workspaces/loganalytics-mgt" / Resource Group "rg-mgt-loganalytics"): operationsmanagement.SolutionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"error":{"code":"NotFound"}}]

```

### Expected Behavior

Solution should be assigned to existing log-analytics account

### Actual Behavior

Solution deployment fails

### Steps to Reproduce

run provided configuration

### Important Factoids

Referencing a deployment I did manually in another subscription via resources.azure.com, I have found the correct terminology to use, but it still fails;

resources.azure.com:
```
{
  "plan": {
    "name": "Start-Stop-VM[WestSideLogs]",
    "publisher": "Microsoft",
    "promotionCode": "",
    "product": "VmManagementSolution"
  },
  "properties": {
    "workspaceResourceId": "/subscriptions/MY-SUBSCRIPTION/resourcegroups/westside/providers/Microsoft.OperationalInsights/workspaces/WestSideLogs",
    "provisioningState": "Succeeded",
    "creationTime": "Fri, 02 Nov 2018 15:27:45 GMT",
    "lastModifiedTime": "Fri, 02 Nov 2018 15:27:45 GMT",
    "containedResources": [
      "/subscriptions/MY-SUBSCRIPTION/resourceGroups/WestSide/providers/Microsoft.OperationalInsights/workspaces/WestSideLogs/views/StartStopVMView"
    ],
    "referencedResources": [
      ...
    ]
  },
  "id": "/subscriptions/MY-SUBSCRIPTION/resourcegroups/westside/providers/Microsoft.OperationsManagement/solutions/Start-Stop-VM[WestSideLogs]",
  "name": "Start-Stop-VM[WestSideLogs]",
  "type": "Microsoft.OperationsManagement/solutions",
  "location": "West Europe",
  "tags": {}
}
```

Adjusted code and failed output:
```
azurerm_log_analytics_solution.loganalytics-solution-startstop: Creating...
  location:              "" => "westeurope"
  plan.#:                "" => "1"
  plan.0.name:           "" => "<computed>"
  plan.0.product:        "" => "VmManagementSolution"
  plan.0.publisher:      "" => "Microsoft"
  resource_group_name:   "" => "rg-mgt-loganalytics"
  solution_name:         "" => "Start-Stop-VM[loganalytics-mgt]"
  workspace_name:        "" => "loganalytics-mgt"
  workspace_resource_id: "" => "/subscriptions/MY-SUBSCRIPTION/resourcegroups/rg-mgt-loganalytics/providers/microsoft.operationalinsights/workspaces/loganalytics-mgt"

Error: Error applying plan:

1 error(s) occurred:

* azurerm_log_analytics_solution.loganalytics-solution-startstop: 1 error(s) occurred:

* azurerm_log_analytics_solution.loganalytics-solution-startstop: Error creating/updating Log Analytics Solution "Start-Stop-VM[loganalytics-mgt](loganalytics-mgt)" (Workspace "/subscriptions/MY-SUBSCRIPTION/resourcegroups/rg-mgt-loganalytics/providers/microsoft.operationalinsights/workspaces/loganalytics-mgt" / Resource Group "rg-mgt-loganalytics"): operationsmanagement.SolutionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: "For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.  For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)" error: invalid character 'F' looking for beginning of value
```

I believe a Plan Name needs to be input, but this cannot be set;
```
resource "azurerm_log_analytics_solution" "loganalytics-solution-startstop" {
  solution_name         = "Start-Stop-VM[${azurerm_log_analytics_workspace.loganalytics-workspace.name}]"
  location              = "${azurerm_resource_group.rg-loganalytics.location}"
  resource_group_name   = "${azurerm_resource_group.rg-loganalytics.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.loganalytics-workspace.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.loganalytics-workspace.name}"
  provider              = "azurerm.subPRD"

  plan {
    name                = "Start-Stop-VM[${azurerm_log_analytics_workspace.loganalytics-workspace.name}]"
    publisher           = "Microsoft"
    product             = "VmManagementSolution"
  }
}
```

Error:
`Error: azurerm_log_analytics_solution.loganalytics-solution-startstop: "plan.0.name": this field cannot be set`

### References

* #0000

**Comment by metacpp** [comment] 2018-12-12 01:39
@fluffy-cakes thanks for opening this issue, I can reproduce it locally. I am working with service team to figure out the root cause, please stay tuned for the updates from me.

**Comment by ndoody** [comment] 2018-12-31 02:16
I'm getting this same problem, but I am trying to create a service map....my code is like below :-

resource "azurerm_log_analytics_solution" "oms01" {
  solution_name         = "ServiceMap(prd01-oms01)"
  location            = "${azurerm_resource_group.rg01.location}"
  resource_group_name = "${azurerm_resource_group.rg01.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.oms01.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.oms01.name}"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ServiceMap"
  }
}

Very similar, simple enough and I don't think it should error.

**Comment by metacpp** [comment] 2019-01-08 00:22
@fluffy-cakes we checked with service team, unfortunately, `VmManagementSolution` is not in the list of onboarded first party solutions. That's the reason for the failure.

**Comment by metacpp** [comment] 2019-01-08 18:49
@ndoody thanks for sharing your problem here. I tried to provision the serviceMap solution and it's successful. You solution name needs to be solutionType, which is "ServiceMap" in your case.

Below is the configuration used by me to provision the solution:
```tf
resource "azurerm_resource_group" "test" {
  name     = "k8s-log-analytics-test"
  location = "westeurope"
}

resource "random_id" "workspace" {
  keepers = {
    # Generate a new id each time we switch to a new resource group
    group_name = "${azurerm_resource_group.test.name}"
  }

  byte_length = 8
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "k8s-workspace-${random_id.workspace.hex}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "PerGB2018"
}

resource "azurerm_log_analytics_solution" "test" {
  solution_name         = "ServiceMap"
  location              = "${azurerm_resource_group.test.location}"
  resource_group_name   = "${azurerm_resource_group.test.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.test.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.test.name}"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ServiceMap"
  }
}
```

**Comment by metacpp** [comment] 2019-01-08 19:18
@fluffy-cakes since this issue is caused by `VmManagementSolution` missed in the first party list, I am going to close it. But, you can still leave comment here or reopen it.

**Closed by metacpp** 2019-01-08 19:18 UTC
Labels: question, service/oms, upstream-microsoft
