### ISSUE TITLE
Using for_each in updating azurerm_subnet service endpoints fails with AnotherOperationInProgress error.

### ISSUE THREAD

**Issue by bleemus** [terraform-providers/terraform-provider-azurerm#8135] opened 2020-08-14 18:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.23.0
```

### Affected Resource(s)

* `azurerm_virtual_network`
* `azurerm_subnet`

### Terraform Configuration Files

```hcl
# Trigger AnotherOperationInProgress bug

# Apply once as-is
# Flip local.endpoints and re-apply
# Fail

provider "azurerm" {
  features {}
}

locals {
  rg_name = "failtestrg"
}

resource azurerm_resource_group "testrg" {
  name     = local.rg_name
  location = "eastus"
}


resource "azurerm_virtual_network" "this" {
  name                = "failnet"
  location            = "eastus"
  address_space       = ["10.0.0.0/8"]
  resource_group_name = azurerm_resource_group.testrg.name
}


locals {
  with_cosmos    = ["Microsoft.Storage", "Microsoft.KeyVault", "Microsoft.AzureCosmosDB"]
  without_cosmos = ["Microsoft.Storage", "Microsoft.KeyVault"]

  # Flip this to local.with_cosmos after vnet has been initial created without.
  endpoints = local.with_cosmos

  subnets = {
    "snet-one" : {
      "cidr" : "10.0.1.0/24",
      "service_endpoints" : local.endpoints
    }
    "snet-two" : {
      "cidr" : "10.0.2.0/24",
      "service_endpoints" : local.endpoints
    }
    "snet-three" : {
      "cidr" : "10.0.3.0/24",
      "service_endpoints" : local.endpoints
    }
  }
}

resource "azurerm_subnet" "subnet" {
  for_each             = local.subnets
  name                 = each.key
  virtual_network_name = azurerm_virtual_network.this.name
  resource_group_name  = azurerm_resource_group.testrg.name
  address_prefixes     = [each.value.cidr]
  service_endpoints    = each.value.service_endpoints
}
```

### Debug Output
https://gist.github.com/bleemus/4a46c542ed24bab8f05d7094acb529e5

### Expected Behavior

* All subnets successfully remove the "Microsoft.AzureCosmosDB" service endpoint.

### Actual Behavior

* One subnet succeeds, other two fail with an "AnotherOperationInProgress" error.

### Steps to Reproduce

1. `terraform apply`
1. VNet successfully creates.
1. Change line 38: `local.with_cosmos` to `local.without_cosmos`
1. One succeeds, others fail.

### Important Factoids
N/A

### References

A couple others that look similar:
* #4285
* #3780

**Comment by mybayern1974** [comment] 2020-08-18 10:17
hi @bleemus ,   

Thanks for opening this issue :)

Given this appears to be a duplicate of #3780- rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3780 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-08-18 10:17 UTC
Labels: duplicate, service/subnets
