### ISSUE TITLE
azurerm role definition provider bug

### ISSUE THREAD

**Issue by Gvazzana** [terraform-providers/terraform-provider-azurerm#10629] opened 2021-02-18 07:59 UTC
**Issue:**
Unable to create Azure Role Definitions

**Scenarios:**
- No role definitions existing
- No existing state file
- Any azurerm provider version from 2.26-2.47
- Terraform 13 > and 14 >

This error showed up, with no change to the azurerm provider version, having been 2.36 for a long time.

**Error during Terraform Apply:**
```
Error: Provider produced inconsistent result after apply
When applying changes to module.rbac_prd_tenant.azurerm_role_definition.role3,
provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new
value: Root resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Unable to find any work arounds.
We are not using role assignments, only creating the role definition via terraform

**Provider code** (tried 2.36-2.47)
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.46.0"
    }
  }
}

provider "azurerm" {
  environment     = "public"
  subscription_id = var.cs_subscription_Id
  tenant_id       = var.tenant_id
  client_id       = var.mgmt_tf_sp_appid
  client_secret   = var.mgmt_tf_sp_secret
  version         = "=2.46.0"
  features {}
}
```

**Role definition tf code:**

```
resource "azurerm_role_definition" "role2" {
  name               = "${var.project_ident}-${var.cs_env_ident}-customer-admin"
  scope              = var.scope
  description        = "This is a custom role created via Terraform for customer Admin"
 
  permissions {
    actions = ["*"]
    not_actions = [
      "Microsoft.Network/virtualNetworks/*",
      "Microsoft.Network/networkWatchers/*",
      "Microsoft.Network/expressRouteCircuits/*",
      "Microsoft.Network/virtualWans/*",
      "Microsoft.Network/virtualRouters/*",
      "Microsoft.Network/expressRouteGateways/*",
      "Microsoft.Network/expressRouteGateways/*",
      "Microsoft.Network/expressRoutePorts/*",
      "Microsoft.Network/expressRoutePortsLocations/*",
      "Microsoft.Network/ddosProtectionPlans/*",
      "Microsoft.Network/routeTables/*",
      "Microsoft.Network/networkProfiles/*",
      "Microsoft.Network/ddosCustomPolicies/*",
      "Microsoft.Network/networkIntentPolicies/*",
      "Microsoft.Network/operations/*",
      "Microsoft.Network/expressRouteServiceProviders/*",
      "Microsoft.Network/bgpServiceCommunities/*",
      "Microsoft.Authorization/classicAdministrators/write",
      "Microsoft.Authorization/classicAdministrators/delete",
      "Microsoft.Authorization/elevateAccess/Action",
    ]
  }

  assignable_scopes = var.assignable_scopes
}

**Role Definition Creation Module call code:**
module "rbac_prd_tenant" {
  source        = "../modules/rbac"
  project_ident = var.project_ident
  cs_env_ident  = var.cs_env_ident
  scope         = data.azurerm_management_group.prd.id

  assignable_scopes = [
    data.azurerm_management_group.prd.id
  ]
}
```

**Impact:**
This has created a major blocker for our entire platform, as we can no longer create RBAC Roles on the parent management groups, where customer subscriptions reside.

Thank you

**Comment by tombuildsstuff** [comment] 2021-02-18 09:19
hi @Gvazzana 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #10442 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10442 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-18 09:19 UTC
Labels: bug, duplicate, service/roles

**Comment by Gvazzana** [comment] 2021-02-18 17:34
ty sir. I will track via https://github.com/terraform-providers/terraform-provider-azurerm/issues/10602, per #10442 thread

Any idea the target azurerm provider release for this fix?

**Comment by Gvazzana** [comment] 2021-02-18 22:10
> hi @Gvazzana
> 
> Thanks for opening this issue :)
> 
> Taking a look through this appears to be a duplicate of #10442 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10442 for updates?
> 
> Thanks!

ty sir. I will track via #10602, per #10442 thread

Any idea the target azurerm provider release for this fix?
