### ISSUE TITLE
Terraform cannot set an azurerm_key_vault_secret due to policy handling

### ISSUE THREAD

**Issue by tezzigator** [terraform-providers/terraform-provider-azurerm#4977] opened 2019-11-25 22:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.10
+ provider.azurerm v1.36.1

### Affected Resource(s)
azurerm_key_vault_secret and possibly something to do with azurerm_key_vault_access_policy
Just generic RG, VNet/subnet, and keyvault is all thats needed with this to duplicate.

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "rg" {
    name            = "TEST"
    location        = "eastus"
}
resource "azurerm_virtual_network" "vnet" {
    name                        = "${azurerm_resource_group.rg.name}"
    location                    = "eastus"
    resource_group_name         = "${azurerm_resource_group.rg.name}"
    address_space               = ["10.0.0.0/8"]
}
resource "azurerm_subnet" "netpublic" {
    name                        = "public"
    resource_group_name         = "${azurerm_resource_group.rg.name}"
    virtual_network_name        = "${azurerm_virtual_network.vnet.name}"
    address_prefix              = "10.0.0.0/24"
}
resource "azurerm_key_vault" "keyvault" {
    name                            = "blarghimdeadnow"
    location                        = "eastus"
    resource_group_name             = "${azurerm_resource_group.rg.name}"
    enabled_for_disk_encryption     = false
    tenant_id                       = "${var.tenant_id}"
    sku_name                        = "premium"
}
resource "azurerm_key_vault_access_policy" "TerraformSP" {
  key_vault_id        = "${azurerm_key_vault.keyvault.id}"
  tenant_id           = "${var.tenant_id}"
  object_id            = "${var.objectId}"
  key_permissions     = ["get", "list", "verify", "sign", "update", "create", "import", "delete", "recover", "backup", "restore"]
  secret_permissions  = ["get", "list", "set", "delete", "recover", "backup", "restore"]
}
resource "azurerm_key_vault_secret" "nosql-rw" {
  depends_on    = [azurerm_key_vault_access_policy.TerraformSP]
  name          = "nosql-rw"
  value         = "blargh"
  key_vault_id  = "${azurerm_key_vault.keyvault.id}"
}
```
### Debug Output
https://gist.github.com/tezzigator/be418f9e35d2bd2c4d978147e17e2e43#file-terraformazurekeyvault

### Panic Output
None

### Expected Behavior
secret put into keyvault

### Actual Behavior
Status=403 Code="Forbidden" Message="Access denied. Caller was not found on any access policy

### Steps to Reproduce
I have created a SP in AAD specifically for terraform, terraform is creating everything in my subscription_id here under that SP.  I have tried using the SP's appId and also tried the SP'd objectID as the 'object_id' in the policy, but both result in same 403 error when trying to set a secret.  The keyvault gets created no issue as does the policy, just cannot add a secret.

1. `terraform apply`

### Important Factoids
Nothing special

### References
None

**Comment by mrgeoffrich** [comment] 2019-11-26 03:29
I found I had to add a depends_on when setting the secret itself, where it depends on the access policy. Otherwise it tries to add the secret before it actually has access.

Something like
`depends_on = [ azurerm_key_vault_access_policy.TerraformSP ]`

**Comment by mrgeoffrich** [comment] 2019-11-26 03:32
I set the `object_id = data.azurerm_client_config.current.service_principal_object_id` on the policy, with the line `data "azurerm_client_config" "current" {}` declared before it.

**Comment by tezzigator** [comment] 2019-11-26 16:06
OK that worked - thanks.  but *why* does it work?  as best I can tell what I was doing was also putting the correct object ID in there; in fact, after doing that I went into the portal and checked access policy of the keyvault, and the AAD name of the SP Im trying to add was actually in there, but still couldnt set a secret.

But heres the weird thing, while trying to do it my way, for the portal's displayed access policy, the AAD name of the SP was there, but the category field was "unknown".  now, with it working your way, the category says "APPLICATION".  So that is obviously the difference here, I just dont see how why its different.  Especially since I have also set another entity (user managed MSI) to have access to the vault, using the same "azurerm_key_vault_access_policy" declaration, and it doesnt show as unknown

**Comment by mariojacobo** [comment] 2019-12-10 11:03
@tezzigator we ran into the same issue. It seems the issue is related to application (client) ID vs Object ID, something I have yet to wrap my head around and truly understand the difference. What we do, is first create the application, then create the SP with the same Application ID and finally insert the object ID into the access policy.  @mrgeoffrich solution also works

```
# create application in AD
resource "azuread_application" "aks_application" {
  name = "${azurerm_resource_group.aks.name}"
}

# create SP with the same application ID
resource "azuread_service_principal" "akssp" {
  application_id = "${azuread_application.aks_application.application_id}"
}
.........
# grab the object ID of the SP and add to policy
access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${azuread_service_principal.akssp.id}"

    secret_permissions = [
      "list",
      "get",
      "set",
    ]
  }
```

**Comment by tombuildsstuff** [comment] 2020-12-17 11:41
👋 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through here this appears to be a usage question regarding the Terraform Configuration which has been answered above (using the Object ID rather than the Application ID in the Access Policy).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). Since this question appears to be resolved, I'm going to close this issue for the moment, but should you have further questions I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2020-12-17 11:41 UTC
Labels: question, service/keyvault
