### ISSUE TITLE
Error: ID was missing the `mongodbDatabases` element with the provider 2.25

### ISSUE THREAD

**Issue by caronicolas** [terraform-providers/terraform-provider-azurerm#8331] opened 2020-09-02 19:50 UTC
I upgraded my provider to the 2.25.0, and I have a bug with my cosmosDB that I don't understand.
I didn't change anything and I have an error : "ID was missing the `mongodbDatabases` element"
I tried to upgrade step by step (from 2.14.0) and this error started at the version 2.20.0. I have been looking for some changes in the changelog but I can't find anything relevant...

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.25.0

Appears with the provider.azurerm v2.20.0

### Affected Resource(s)

I think the affected resource is the "azurerm_cosmosdb_mongo_collection"

### Terraform Configuration Files

```hcl
locals {
  collections = {
    "col1" : {
      "shard_key" : "shard_key",
      "throughput" : 2000
    },
    "col2" : {
      "shard_key" : "shard_key",
      "throughput" : 1000
    },
    "col3" : {
      "shard_key" : "shard_key",
      "throughput" : 1000
    },
  }
}

resource "azurerm_cosmosdb_mongo_database" "test" {
  name                = "test"
  resource_group_name = data.azurerm_resource_group.ci.name
  account_name        = azurerm_cosmosdb_account.ci.name
}

resource "azurerm_cosmosdb_mongo_collection" "marketplace" {
  for_each            = local.collections
  name                = each.key
  resource_group_name = azurerm_cosmosdb_account.ci.resource_group_name
  account_name        = azurerm_cosmosdb_account.ci.name
  database_name       = azurerm_cosmosdb_mongo_database.test.name

  shard_key  = each.value["shard_key"]
  throughput = each.value["throughput"]

  lifecycle {
    ignore_changes = [shard_key]
  }
}

```

### Expected Behavior

No change on my plan

### Actual Behavior

Display an error : "ID was missing the `mongodbDatabases`"

### Steps to Reproduce

1.   Set the azurerm provider version to 2.19.0
2.  `terraform plan`
3.  Check if everything is ok
4.  Change the azurerm provider version to 2.20.0
5.  `terraform plan`

**Comment by neil-yechenwei** [comment] 2020-09-04 08:40
@caronicolas, thanks for opening this issue. I assume the root cause is that the resource id format is changed from "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{accountName}/apis/mongodb/databases/{databaseName}/collections/{collectionanme}" to "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{accountName}/mongodbDatabases/{databaseName}/collections/{collectionanme}" but I assume this issue has been fixed in newer version such as 2.25.0. Could you have a try below tfconfig and repro steps to check whether the issue still exists? Thanks.

1. Create resource with 2.10.0:
```
provider "azurerm" {
  features {}
  version = "2.10.0"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-cosmos-test01"
  location = "eastus2"
}

resource "azurerm_cosmosdb_account" "test" {
  name                = "acctest-ca-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = azurerm_resource_group.test.location
    failover_priority = 0
  }
}

locals {
  collections = {
    "col1" : {
      "shard_key" : "shard_key",
      "throughput" : 2000
    },
    "col2" : {
      "shard_key" : "shard_key",
      "throughput" : 1000
    },
    "col3" : {
      "shard_key" : "shard_key",
      "throughput" : 1000
    },
  }
}

resource "azurerm_cosmosdb_mongo_database" "test" {
  name                = "cosmogodbtest01"
  resource_group_name = azurerm_resource_group.test.name
  account_name        = azurerm_cosmosdb_account.test.name
}

resource "azurerm_cosmosdb_mongo_collection" "test" {
  for_each            = local.collections
  name                = each.key
  resource_group_name = azurerm_cosmosdb_account.test.resource_group_name
  account_name        = azurerm_cosmosdb_account.test.name
  database_name       = azurerm_cosmosdb_mongo_database.test.name

  shard_key  = each.value["shard_key"]
  throughput = each.value["throughput"]

  lifecycle {
    ignore_changes = [shard_key]
  }
}
```
2. Run `tf plan`:
![image](https://user-images.githubusercontent.com/19754191/92217446-46fcd280-eeca-11ea-94d1-dfe9888b18c6.png)
3. Upgrade provider version from 2.10.0 to 2.25.0:
```
provider "azurerm" {
  features {}
  version = "2.25.0"
}
```
4. Run `tf plan`:
![image](https://user-images.githubusercontent.com/19754191/92217574-73185380-eeca-11ea-9e76-ff3f5c9499e5.png)

**Comment by caronicolas** [comment] 2020-09-10 09:27
@neil-yechenwei yes, you're right the problem is obviously from the ID, I can correct my problem with a lot of terraform state rm and terraform import (on all of my cosmos resources...).
I try your example, it works fine, I don't know exactly why it doesn’t work correctly on my real project...

**Comment by tombuildsstuff** [comment] 2020-10-26 10:37
👋 

Since we've not heard back from you here I'm going to close this issue for the moment, but please let us know if the solution proposed above doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2020-10-26 10:37 UTC
Labels: question, service/cosmosdb, waiting-response
