### ISSUE TITLE
Terraform does not return error message from azurerm_container_service

### ISSUE THREAD

**Issue by TobiG77** [terraform-providers/terraform-provider-azurerm#466] opened 2017-10-29 05:15 UTC
I initially built a module to deploy in Australia East, but had later moved to West US 2 . And I could not deploy anymore, because I kept getting an unspecific error message, without any indication what to do.

### Terraform Version

terraform 0.10.8
azurerm 0.3.1

### Affected Resource(s)

azurerm_container_service

### Terraform Configuration Files
```hcl

resource "azurerm_container_service" "example" {
  name                   = "example"
  location               = "${azurerm_resource_group.example.location}"
  resource_group_name    = "${azurerm_resource_group.example.name}"
  orchestration_platform = "Swarm"

  master_profile {
    count      = 1
    dns_prefix = "example-master"
  }

  linux_profile {
    admin_username = "example-linux"

    ssh_key {
      key_data = "foobar"
    }
  }

  agent_pool_profile {
    name       = "default"
    count      = 1
    dns_prefix = "example-agent"
    vm_size    = "Standard_A0"
  }

  diagnostics_profile {
    enabled = false
  }

  tags {
    Environment = "dev"
  }
}


```

### Debug Output

https://gist.githubusercontent.com/TobiG77/0403606dc2e8cc2fdc6fa4d05e09303c/raw/3640b83d5809c00afc009a7e2470643a369de519/debug-response.json

### Panic Output

None

### Expected Behavior
Seen the actual message content as provided by the API.

### Actual Behavior

Saw an unspecific message, with no explanation that I actually made an invalid request.

* azurerm_container_service.example: containerservice.ContainerServicesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This example will work with in Australia East, but fails in West US 2, because the available VMSizes are different.

### References

None

**Comment by tombuildsstuff** [comment] 2017-12-05 18:50
Hi @TobiG77 

Thanks for opening this issue - apologies for the delayed response here!

I've taken a quick look into this and from what I can see this is a bug in the Azure SDK for Go, where the correct error message isn't returned from the SDK. [I'd previously opened an issue about this here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/466) and have requested an update - unfortunately this affects multiple resources since it's related to the way that errors are parsed.

Thanks!

**Comment by katbyte** [comment] 2018-10-21 22:24
Hi @TobiG77,

I see the SDK issue has been closed so this should be fixed now and I can confirm errors are being returned from the service.

**Closed by katbyte** 2018-10-21 22:24 UTC
Labels: bug, service/container-service
