### ISSUE TITLE
azurerm_notification_hub -  Error retrieving Credentials for Notification Hub

### ISSUE THREAD

**Issue by JordanW94** [terraform-providers/terraform-provider-azurerm#12556] opened 2021-07-12 17:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.13.1
azurerm: 2.18.0

### Affected Resource(s)

* `azurerm_notification_hub`

### Terraform Configuration Files

```hcl

resource "azurerm_resource_group" "azure-rg" {
	name			= "${var.Azure_resourcegroup_name}"
	location		= "North Europe"
}


resource "azurerm_notification_hub_namespace" "azure-ns" {
        name                    = "${var.Azure_notification_hub_namespace_name}"
        location                = "${azurerm_resource_group.azure-rg.location}"
        resource_group_name     = "${azurerm_resource_group.azure-rg.name}"
        namespace_type          = "NotificationHub"
        sku_name                = "Free"
}

resource "azurerm_notification_hub" "azure-native-hub" {
        name                    = "${var.Azure_notification_hub_native_name}"
        namespace_name          = "${azurerm_notification_hub_namespace.azure-ns.name}"
        location                = "${azurerm_resource_group.azure-rg.location}"
        resource_group_name     = "${azurerm_resource_group.azure-rg.name}"
        gcm_credential  {
                api_key = "${local.xxx.gcm_api_key}"
        }
        apns_credential {
                application_mode        = "Production"
                bundle_id               = "${var.Azure_apns_bundle_id_native}"
                key_id                  = "${var.Azure_apns_key_id_native}"
                team_id                 = "${var.Azure_apns_team_id_native}"
                token                   = "${local.xxx.apns_token}"
        }
}

resource "azurerm_notification_hub_authorization_rule" "azure-native-rule" {
        name                    = "${var.Azure_notification_hub_authrule_name}"
        notification_hub_name   = "${azurerm_notification_hub.azure-native-hub.name}"
        namespace_name          = "${azurerm_notification_hub_namespace.azure-ns.name}"
        resource_group_name     = "${azurerm_resource_group.azure-rg.name}"
        manage                  = true
        send                    = true
        listen                  = true
}
```

### Debug Output

https://gist.github.com/JordanW94/9d2c1791a2931ecc86a5901c7d229332

### Expected Behaviour

This was working a week ago, it would just successfully create the notification hubs. I'm assuming something has changed on the Azure API side?

### Actual Behaviour

The error above is presented.

### Steps to Reproduce

2. Attempt to create the notification hubs on version 0.13.1

2. `terraform apply`

### Extra notes
I did upgrade my local terraform to the latest 1.0.2 release and 2.67.0 azurerm and tested out the same terraform code and was presented with a different error. (I believe this is down to azurerm as it would present the same on Terraform 0.13.1)

```
│ Error: ID was missing the `notificationHubs` element
│
│   with azurerm_notification_hub.azure-native-hub,
│   on notification.tf line 18, in resource "azurerm_notification_hub" "azure-native-hub":
│   18: resource "azurerm_notification_hub" "azure-native-hub" {
```

Thanks!

* #0000

**Comment by andysousa** [comment] 2021-07-13 00:17
I think you are having the same issue as https://github.com/terraform-providers/terraform-provider-azurerm/issues/11602

**Comment by tombuildsstuff** [comment] 2021-08-04 15:45
Duplicate of #11602

**Closed by tombuildsstuff** 2021-08-04 15:45 UTC
Labels: bug, service/notifications
