### ISSUE TITLE
Create azure subscription using azurerm provider in terraform

### ISSUE THREAD

**Issue by sangeethaguhan** [terraform-providers/terraform-provider-azurerm#5904] opened 2020-02-25 22:30 UTC
Hi,

Is it possible to create azure subscriptions using azurerm provider in terraform? I have an EA Azure account in place. I have done quite a bit of research on this, and found out that this feature is still in preview mode(Azure) - https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/programmatically-create-subscription?tabs=rest . Is there any alternate workaround for this? or subscriptions can only be created from portal for now? Please assist, would be of great help. Thank you!

**Comment by brunhil** [comment] 2020-02-28 21:25
This appears to be able to be done via a preview API version [2018-11-01](https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/billing/mgmt/2018-11-01-preview/billing). This seems like it could be created from this preview SDK.

**Comment by StefanSchoof** [comment] 2020-03-02 20:22
I think this is a duplicate of #1216

**Comment by tombuildsstuff** [comment] 2020-03-03 23:00
hi @sangeethaguhan 

Thanks for opening this issue :)

Taking a look through as @StefanSchoof has mentioned this appears to be a duplicate of #1216 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1216 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-03-03 23:00 UTC
Labels: duplicate
