### ISSUE TITLE
aks: agent_pool_profile should not take into account what value count has when autoscaler is enabled

### ISSUE THREAD

**Issue by aarroyoc** [terraform-providers/terraform-provider-azurerm#4429] opened 2019-09-25 09:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.9
+ provider.aws v2.19.0
+ provider.azuread v0.4.0
+ provider.azurerm v1.33.1
+ provider.helm v0.10.2
+ provider.kubernetes v1.8.1
+ provider.null v2.1.2
+ provider.random v2.2.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "internal-shared" {
  name                = "internal-shared-${random_string.kube-internal-shared-id.result}"
  location            = "${azurerm_resource_group.internal-shared.location}"
  resource_group_name = "${azurerm_resource_group.internal-shared.name}"
  dns_prefix          = "internal-shared-dns"
  kubernetes_version  = "1.13.10"

  agent_pool_profile {
    name                = "default"
    vm_size             = "Standard_D2s_v3"
    os_type             = "Linux"
    os_disk_size_gb     = 30
    enable_auto_scaling = true
    min_count           = 2
    max_count           = 100
    type                = "VirtualMachineScaleSets"
  }

  service_principal {
    client_id     = "${azuread_service_principal.kube-internal-shared.application_id}"
    client_secret = "${azuread_service_principal_password.kube-internal-shared.value}"
  }
}
```

### Debug Output

```
Error: Error creating/updating Managed Kubernetes Cluster "internal-shared-39gnBRXB" (Resource Group "internal-shared"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Cannot manually scale AgentPool 'default' of an AKS cluster with cluster autoscaler enabled. Please disable cluster autoscaler in the cluster to manually scale."
```

### Expected Behavior

As autoscaler is enabled, the value of count in agent_pool_profile shouldn't be taken into account.

### Actual Behavior

As my cluster grow to two machines (default value of count is 1), Terraform tries to reduce the number of nodes. But, as autoscaler is enabled, Azure doesn't let Terraform modify the number of nodes, causing an error and breaking all the Terraform workflow until the number of nodes in the managed cluster is equal to the one declared in configuration files (by default 1). 

### Steps to Reproduce

1.  Create a managed kubernetes cluster with autoscaler enabled
2. Grow it to have more than one node
3. `terraform apply`

**Comment by NickMetz** [comment] 2019-09-25 11:30
This looks like a duplicate of #4075

**Comment by tombuildsstuff** [comment] 2019-09-26 08:18
hi @aarroyoc 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4075 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4075 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-09-26 08:18 UTC
Labels: bug, duplicate, service/kubernetes-cluster
