### ISSUE TITLE
Cannot use azure_blob_storage_location in azurerm_data_factory_dataset_delimited_text

### ISSUE THREAD

**Issue by MrSimonEmms** [terraform-providers/terraform-provider-azurerm#7948] opened 2020-07-29 08:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_data_factory_dataset_delimited_text`

### Terraform Configuration Files

```hcl
// Resource group and data factory not defined as same as on doc page 
// @link https://www.terraform.io/docs/providers/azurerm/r/data_factory_dataset_delimited_text.html#azure_blob_storage_location

resource "azurerm_data_factory_linked_service_azure_blob_storage" "example" {
  name = example
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name = azurerm_data_factory.example.name
  connection_string = azurerm_storage_account.ingestion.primary_connection_string
}

resource "azurerm_data_factory_dataset_delimited_text" "example" {
  name = "example"
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name = azurerm_data_factory.example.name
  linked_service_name = azurerm_data_factory_linked_service_azure_blob_storage.example.id

  azure_blob_storage_location {
    container = "container"
    filename = "file.csv"
    path = "path"
  }

  column_delimiter = ","
  escape_character = "\\"
  quote_character = "\""
}
```

### Debug Output

[Output](https://gist.github.com/MrSimonEmms/f49077ac6a9d68e8fb4967a02042f68c)

### Expected Behavior

This should have applied an delimited text dataset

### Actual Behavior

Errors. I've tried using `blob_storage_location`, but that also errors.

```shell
Error: One of `http_server_location`, `blob_storage_location` must be specified to create a DataFactory Delimited Text Dataset

  on data-factory.tf line 35, in resource "azurerm_data_factory_dataset_delimited_text" "example":
  35: resource "azurerm_data_factory_dataset_delimited_text" "example" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- n/a

**Comment by mybayern1974** [comment] 2020-07-30 06:27
hi  @MrSimonEmms 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #7954. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one. Specially, in that issue is there a PR contributing to resolve it. Would you mind subscribing to #7954 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2020-07-30 06:27 UTC
Labels: service/data-factory
