### ISSUE TITLE
azurerm_kubernetes_cluster not working with Gen2 vm_size

### ISSUE THREAD

**Issue by shebang89** [terraform-providers/terraform-provider-azurerm#7947] opened 2020-07-29 08:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.0-beta3
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0

### Affected Resource(s)
* `azurerm_kubernetes_cluster`
* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.20.0"
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "aks-rg-01"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                    = "aks-test"
  location                = azurerm_resource_group.rg.location
  resource_group_name     = azurerm_resource_group.rg.name
  dns_prefix              = "myaks"
  kubernetes_version      = "1.18.4"
  private_cluster_enabled = false

  default_node_pool {
    name       = "default"
    vm_size    = "Standard_DC2s_v2"
    node_count = 1
  }

  identity {
    type = "SystemAssigned"
  }
}
```
### Expected Behavior
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

### Actual Behavior
Error: waiting for creation of Managed Kubernetes Cluster "aks-test" (Resource Group "aks-rg-01"): Code="CreateVMSSAgentPoolFailed" Message="VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\n  \"code\": \"BadRequest\",\n  \"message\": \"The selected VM Size 'Standard_DC2s_v2' cannot boot Hypervisor Generation '1'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size. If this was an Update operation please select a Hypervisor Generation '1' VM Size.\"\n } "

  on main.tf line 11, in resource "azurerm_kubernetes_cluster" "aks":
  11: resource "azurerm_kubernetes_cluster" "aks" {

### Steps to Reproduce
1. `terraform apply`

### Additional information
Since Terraform didn't work out I had to fall back to az cli, which gave me the exact same error as Terraform did. 
After some research in Azure documentation, I figured out I need to install the aks-preview extension in az cli to be able to provision AKS clusters with Gen2 VM sizes. 

Here are the steps for a successful deployment with az cli:
```shell
az extension add --name aks-preview
az feature register --name Gen2VMPreview --namespace Microsoft.ContainerService
az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/Gen2VMPreview')].{Name:name,State:properties.state}" (wait until status is "Registered" before proceeding to next step)
az provider register --namespace Microsoft.ContainerService
az group create --name aks-test-rg --location westeurope && \
az aks create \
--name aks-test \
--resource-group aks-test-rg \
--kubernetes-version 1.18.4 \
--node-count 3 \
--node-vm-size Standard_DC2s_v2 \
--aks-custom-headers usegen2vm=true
```

**Comment by tombuildsstuff** [comment] 2020-08-24 13:48
hi @shebang89 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6793 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-24 13:48 UTC
Labels: service/kubernetes-cluster
