### ISSUE TITLE
Modifying multiple subnet sizes causes network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'backend-w-subnet' is not valid in virtual network 'testvnet'

### ISSUE THREAD

**Issue by guywood13** [terraform-providers/terraform-provider-azurerm#11525] opened 2021-04-29 15:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_2.56.0` but test down to 2.51.0 then gave up!
* `terraform_0.14.8`

### Terraform Configuration Files

```hcl
# terraform.tf
resource "azurerm_resource_group" "example" {
  name     = "testrgvnet"
  location = "uksouth"
}

resource "azurerm_virtual_network" "main" {
  name                = "testvnet"
  address_space       = [var.address_spaces[var.location_short]]
  location            = "uksouth"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "subnets" {
  for_each             = local.subnet_list # Iterate over the list of subnets we need and create each
  name                 = "${each.key}-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.main.name

  # Size of the subnets is /27
  #address_prefixes  = [cidrsubnet(var.address_spaces[var.location_short], 4, each.value)]
  # Size of the subnets is /28
  address_prefixes  = [cidrsubnet(var.address_spaces[var.location_short], 5, each.value)]
}
```

```hcl
# variables.tf
variable "location_short" {  
}

variable "address_spaces" {
  type        = map(any)  
}

variable "subnet_list" {
  type        = map(any)  
  default =  {
    "zero"  = 0
    "one"   = 1
    "two"   = 2
    "three" = 3
    "four"  = 4 
    "five"  = 5
  }
}

locals {
  subnet_list = var.subnet_list
}
```

```hcl
terraform { 
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.56.0" 
    }
  }
  required_version = ">= 0.14.8"
}

provider "azurerm" {
  features {}
}
```

```hcl
location_short = "uks"

address_spaces = {
  uks = "10.0.0.0/23"
  ukw = "10.0.0.0/23"
}

subnet_list = {
  "frontend-l"     = 0
  "backend-w"      = 1
  "backend-l"      = 2
}

```

### Debug Output

```
Error: updating Subnet: (Name "backend-w-subnet" / Virtual Network Name "testvnet" / Resource Group "testrgvnet"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'backend-w-subnet' is not valid in virtual network 'testvnet'." Details=[]

  on terraform.tf line 13, in resource "azurerm_subnet" "subnets":
  13: resource "azurerm_subnet" "subnets" {



Error: updating Subnet: (Name "backend-l-subnet" / Virtual Network Name "testvnet" / Resource Group "testrgvnet"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'backend-w-subnet' is not valid in virtual network 'testvnet'." Details=[]

  on terraform.tf line 13, in resource "azurerm_subnet" "subnets":
  13: resource "azurerm_subnet" "subnets" {
```

### Expected Behaviour

Swapping out address_prefixes lines should change subnets from /27 to /28s and vice versa.

### Actual Behaviour

One or two subnets will successfully modify but at least 1 always fails.  Running apply a 2nd and/or 3rd time and this will successfully apply.

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by magodo** [comment] 2021-04-30 09:26
@guywood13 The issue is caused by address space overlapping between your subnets.

E.g. Given you have subnet addressPrefixes:

- subnet1: `cidrsubnet("10.0.0.0/23", 5, 1)` -> 10.0.0.16/28
- subnet2: `cidrsubnet("10.0.0.0/23", 5, 2)` -> 10.0.0.32/28

Then you change the `newbits` from 5 to 4:

- subnet1: `cidrsubnet("10.0.0.0/23", 4, 1)` -> 10.0.0.32/27
- subnet2: `cidrsubnet("10.0.0.0/23", 4, 2)` -> 10.0.0.64/27

The update of `subnet1` will fail due to the address space overlapps with the `subnet2` (before it is updated). While the update of `subnet2` will succeed. Then if you later try to update `subnet1`, it will now succeed as there is no overlap.

Since this is not an issue of the provider, I'm going to close this issue for now. If you have additional question, you can use one of the [Community Resources](https://www.terraform.io/community.html).

**Closed by magodo** 2021-04-30 09:26 UTC

**Comment by guywood13** [comment] 2021-04-30 11:38
Thanks @magodo and sorry for the time wasting.  I did consider this scenario but incorrectly ruled it out.  My apologies and appreciate the explanation!
