### ISSUE TITLE
azurerm_marketplace_agreement doesnt accept terms

### ISSUE THREAD

**Issue by drewmullen** [terraform-providers/terraform-provider-azurerm#12327] opened 2021-06-22 18:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
```

### Affected Resource(s)

* `azurerm_marketplace_agreement`

### Terraform Configuration Files

```
resource "azurerm_marketplace_agreement" "tomcat" {
  publisher = "bitnami"
  offer     = "tom-cat"
  plan      = "hourly"
}

resource "azurerm_linux_virtual_machine" "tc1" {
  admin_username                  = "azureuser"
  allow_extension_operations      = true
  computer_name                   = "tomcat-1"
  disable_password_authentication = true
  encryption_at_host_enabled      = false
  extensions_time_budget          = "PT1H30M"
  location                        = "eastus"
  max_bid_price                   = -1
  name                            = "tomcat-1"
  network_interface_ids = [
    azurerm_network_interface.tc1.id,
  ]
  priority            = "Regular"
  provision_vm_agent  = true
  resource_group_name = local.rsg
  size                = "Standard_D1_v2"
  tags = {
    "app"   = "tomcat"
  }
  zone = "1"

  admin_ssh_key {
    public_key = "<>"
    username   = "azureuser"
  }

  boot_diagnostics {}

  os_disk {
    caching                   = "ReadWrite"
    disk_size_gb              = 30
    name                      = "tomcat-1_OsDisk_1_081b04b909d643259dc8eeab0b14ee6b"
    storage_account_type      = "StandardSSD_LRS"
    write_accelerator_enabled = false
  }
 
 # NOTE: i have tried with and without this plan block
  plan {
    name      = "7-0"
    product   = "tom-cat"
    publisher = "bitnami"
  }

  source_image_reference {
    offer     = "tom-cat"
    publisher = "bitnami"
    sku       = "7-0"
    version   = "latest"
  }

  timeouts {}
}
```

### Actual Behaviour

```
│ Error: creating Linux Virtual Machine "tomcat-1" (Resource Group "acme-dev"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: <> for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='bitnami' offer = 'tom-cat', sku = '7-0', Correlation Id: 'a3e8cee9-2624-ff2f-7d05-f2437d539337'.'"
│
│   with azurerm_linux_virtual_machine.tc1,
│   on vm_test_tomcat.tf line 51, in resource "azurerm_linux_virtual_machine" "tc1":
│   51: resource "azurerm_linux_virtual_machine" "tc1" {
```

```
$ tf state show azurerm_marketplace_agreement.tomcat
# azurerm_marketplace_agreement.tomcat:
resource "azurerm_marketplace_agreement" "tomcat" {
    id                  = "/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly"
    license_text_link   = "https://mpcprodsa.blob.core.windows.net/legalterms/3E5ED_legalterms_BITNAMI%253a24TOM%253a2DCAT%253a24HOURLY%253a24TUHRPTBFUGCFZ7MYDV5YYPIWHN26Z4EG25KVSJP4ICXU6QHBC6MM2RIWDMKPZN7GE5Z43UNM3JLUYIGL6PPEHFCDIYYYPZFBXMWBNCA.txt"
    offer               = "tom-cat"
    plan                = "hourly"
    privacy_policy_link = "https://www.vmware.com/help/privacy.html"
    publisher           = "bitnami"
}
```

![image](https://user-images.githubusercontent.com/3812162/122980734-0261fb00-d367-11eb-88cf-57cf07b574db.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by drewmullen** [comment] 2021-06-22 19:34
this may also be part of the API backend:
```
 az vm image terms accept --offer tom-cat --publisher bitnami --plan hourly
{
  "accepted": true,
...
```

**Comment by tombuildsstuff** [comment] 2021-06-23 10:44
hi @drewmullen

Thanks for opening this issue.

Taking a look through here there's no dependency configured between these resources so they're provisioning in parallel - see [this guide on Terraform Dependencies](https://learn.hashicorp.com/tutorials/terraform/dependencies) for more information which should fix this.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader configuration questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe that adding the dependency should fix this, but if not I'd recommend opening an issue on [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2021-06-23 10:44 UTC
Labels: question, service/marketplace

**Comment by drewmullen** [comment] 2021-06-23 11:48
@tombuildsstuff I was using depends_on it just didn't make it into the issue code above (copy paste). As you can see above I showed that the state has the marketplace resource.

Respectfully, please reopen to ticket, this is a bug

**Comment by drewmullen** [comment] 2021-06-25 02:29
@katbyte can you please try to get @tombuildsstuff's take another look. this is not a race condition from configuration. i have provided more than enough evidence that this likely a bug

**Comment by tombuildsstuff** [comment] 2021-06-25 03:18
@drewmullen the log above shows that there's no dependency between those resources, since they're being deleted in parallel - which highlights that this a configuration issue, else the VM would be deleted first, then the Marketplace Agreement, then Marketplace Agreement would be re-provisioned before the VM - as such as mentioned above unfortunately this is not a bug in the Azure Provider but a configuration issue.

You can fix this configuration issue by adding an explicit `depends_on` to the Terraform Configuration as described in the document linked above - should you have any further configuration questions I'd point you towards [the Community Discuss Forum](https://discuss.hashicorp.com).

**Comment by drewmullen** [comment] 2021-06-25 11:45
@tombuildsstuff  all depends_on does is ensures the dependent resource is built in proper order. the marketplace agreement completed before the VM was created so - no, depends_on would not fix it. see below. in every example ive shown the marketplace resource was built first

the resource **do not work**

```
Terraform will perform the following actions:

  # azurerm_linux_virtual_machine.tc1 is tainted, so must be replaced
-/+ resource "azurerm_linux_virtual_machine" "tc1" {
      ~ id                              = "/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Compute/virtualMachines/tomcat" -> (known after apply)
        name                            = "tomcat"
      ~ private_ip_address              = "10.0.0.4" -> (known after apply)
      ~ private_ip_addresses            = [
          - "10.0.0.4",
        ] -> (known after apply)
      + public_ip_address               = (known after apply)
      ~ public_ip_addresses             = [] -> (known after apply)
        tags                            = {
            "acme-all" = "true"
            "admin"    = "yes"
            "app"      = "tomcat"
        }
      ~ virtual_machine_id              = "67914474-f480-410f-9e49-18ee6a40c9eb" -> (known after apply)
        # (15 unchanged attributes hidden)


      ~ boot_diagnostics {}

      ~ os_disk {
            name                      = "tomcat"
            # (4 unchanged attributes hidden)
        }



        # (4 unchanged blocks hidden)
    }

  # azurerm_marketplace_agreement.tomcat is tainted, so must be replaced
-/+ resource "azurerm_marketplace_agreement" "tomcat" {
      ~ id                  = "/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly" -> (known after apply)
      ~ license_text_link   = "https://mpcprodsa.blob.core.windows.net/legalterms/3E5ED_legalterms_BITNAMI%253a24TOM%253a2DCAT%253a24HOURLY%253a24TUHRPTBFUGCFZ7MYDV5YYPIWHN26Z4EG25KVSJP4ICXU6QHBC6MM2RIWDMKPZN7GE5Z43UNM3JLUYIGL6PPEHFCDIYYYPZFBXMWBNCA.txt" -> (known after apply)
      ~ privacy_policy_link = "https://www.vmware.com/help/privacy.html" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # azurerm_network_interface.tc1 will be updated in-place
  ~ resource "azurerm_network_interface" "tc1" {
        id                            = "/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Network/networkInterfaces/tomcat-1314"
        name                          = "tomcat-1314"
        tags                          = {
            "admin" = "yes"
            "app"   = "tomcat"
        }
        # (11 unchanged attributes hidden)

      ~ ip_configuration {
            name                          = "ipconfig1"
          ~ private_ip_address            = "10.0.0.4" -> "10.0.0.5"
            # (4 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 2 to add, 1 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_linux_virtual_machine.tc1: Destroying... [id=/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Compute/virtualMachines/tomcat]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 10s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 20s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 30s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 40s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 50s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m0s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m10s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m20s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m30s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m40s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m50s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m0s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m10s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m20s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m30s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m40s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m50s elapsed]
azurerm_linux_virtual_machine.tc1: Destruction complete after 2m53s
azurerm_marketplace_agreement.tomcat: Destroying... [id=/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly]
azurerm_network_interface.tc1: Modifying... [id=/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Network/networkInterfaces/tomcat-1314]
azurerm_network_interface.tc1: Modifications complete after 2s [id=/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Network/networkInterfaces/tomcat-1314]
azurerm_marketplace_agreement.tomcat: Destruction complete after 2s
azurerm_marketplace_agreement.tomcat: Creating...
azurerm_marketplace_agreement.tomcat: Creation complete after 5s [id=/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly]
azurerm_linux_virtual_machine.tc1: Creating...
╷
│ Error: creating Linux Virtual Machine "tomcat" (Resource Group "acme-dev"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: '<>' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='bitnami' offer = 'tom-cat', sku = '7-0', Correlation Id: '9b2358ad-74b1-778f-4b16-fae2a234fb33'.'"
│
│   with azurerm_linux_virtual_machine.tc1,
│   on vm_test_tomcat.tf line 65, in resource "azurerm_linux_virtual_machine" "tc1":
│   65: resource "azurerm_linux_virtual_machine" "tc1" {
```

**Comment by drewmullen** [comment] 2021-06-25 11:48
@tombuildsstuff  all depends_on does is ensures the dependent resource is built in proper order. the marketplace agreement completed before the VM was created so - no, depends_on would not fix it. see below. in every example ive shown the marketplace resource was built first

here is a run where i set `depends_on` explicitly, even though it doesnt matter at all in every circumstance above. the resource **does not work**

```
Terraform will perform the following actions:

  # azurerm_linux_virtual_machine.tc1 is tainted, so must be replaced
-/+ resource "azurerm_linux_virtual_machine" "tc1" {
      ~ id                              = "/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Compute/virtualMachines/tomcat" -> (known after apply)
        name                            = "tomcat"
      ~ private_ip_address              = "10.0.0.4" -> (known after apply)
      ~ private_ip_addresses            = [
          - "10.0.0.4",
        ] -> (known after apply)
      + public_ip_address               = (known after apply)
      ~ public_ip_addresses             = [] -> (known after apply)
        tags                            = {
            "acme-all" = "true"
            "admin"    = "yes"
            "app"      = "tomcat"
        }
      ~ virtual_machine_id              = "67914474-f480-410f-9e49-18ee6a40c9eb" -> (known after apply)
        # (15 unchanged attributes hidden)


      ~ boot_diagnostics {}

      ~ os_disk {
            name                      = "tomcat"
            # (4 unchanged attributes hidden)
        }



        # (4 unchanged blocks hidden)
    }

  # azurerm_marketplace_agreement.tomcat is tainted, so must be replaced
-/+ resource "azurerm_marketplace_agreement" "tomcat" {
      ~ id                  = "/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly" -> (known after apply)
      ~ license_text_link   = "https://mpcprodsa.blob.core.windows.net/legalterms/3E5ED_legalterms_BITNAMI%253a24TOM%253a2DCAT%253a24HOURLY%253a24TUHRPTBFUGCFZ7MYDV5YYPIWHN26Z4EG25KVSJP4ICXU6QHBC6MM2RIWDMKPZN7GE5Z43UNM3JLUYIGL6PPEHFCDIYYYPZFBXMWBNCA.txt" -> (known after apply)
      ~ privacy_policy_link = "https://www.vmware.com/help/privacy.html" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # azurerm_network_interface.tc1 will be updated in-place
  ~ resource "azurerm_network_interface" "tc1" {
        id                            = "/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Network/networkInterfaces/tomcat-1314"
        name                          = "tomcat-1314"
        tags                          = {
            "admin" = "yes"
            "app"   = "tomcat"
        }
        # (11 unchanged attributes hidden)

      ~ ip_configuration {
            name                          = "ipconfig1"
          ~ private_ip_address            = "10.0.0.4" -> "10.0.0.5"
            # (4 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 2 to add, 1 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_linux_virtual_machine.tc1: Destroying... [id=/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Compute/virtualMachines/tomcat]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 10s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 20s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 30s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 40s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 50s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m0s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m10s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m20s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m30s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m40s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 1m50s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m0s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m10s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m20s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m30s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m40s elapsed]
azurerm_linux_virtual_machine.tc1: Still destroying... [id=/subscriptions/8f6ea36f-48a4-4bc6-aaf1-...crosoft.Compute/virtualMachines/tomcat, 2m50s elapsed]
azurerm_linux_virtual_machine.tc1: Destruction complete after 2m53s
azurerm_marketplace_agreement.tomcat: Destroying... [id=/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly]
azurerm_network_interface.tc1: Modifying... [id=/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Network/networkInterfaces/tomcat-1314]
azurerm_network_interface.tc1: Modifications complete after 2s [id=/subscriptions/<>/resourceGroups/acme-dev/providers/Microsoft.Network/networkInterfaces/tomcat-1314]
azurerm_marketplace_agreement.tomcat: Destruction complete after 2s
azurerm_marketplace_agreement.tomcat: Creating...
azurerm_marketplace_agreement.tomcat: Creation complete after 5s [id=/subscriptions/<>/providers/Microsoft.MarketplaceOrdering/agreements/bitnami/offers/tom-cat/plans/hourly]
azurerm_linux_virtual_machine.tc1: Creating...
╷
│ Error: creating Linux Virtual Machine "tomcat" (Resource Group "acme-dev"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: '<>' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='bitnami' offer = 'tom-cat', sku = '7-0', Correlation Id: '9b2358ad-74b1-778f-4b16-fae2a234fb33'.'"
│
│   with azurerm_linux_virtual_machine.tc1,
│   on vm_test_tomcat.tf line 65, in resource "azurerm_linux_virtual_machine" "tc1":
│   65: resource "azurerm_linux_virtual_machine" "tc1" {
```

**Comment by drewmullen** [comment] 2021-06-25 11:59
https://github.com/Azure/azure-sdk-for-go/issues/14768

its a bug in the backend API, as i have suggested. please reopen this issue
