### ISSUE TITLE
Changes to azure_traffic_manager_profile removed all azure_traffic_manager_endpoint in it

### ISSUE THREAD

**Issue by nmlc** [terraform-providers/terraform-provider-azurerm#10468] opened 2021-02-04 07:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform: v0.13.2
provider: hashicorp/azurerm v2.6.0

### Affected Resource(s)

* `azure_traffic_manager_endpoint`
* `azure_traffic_manager_profile`
### Terraform Configuration Files

```hcl
resource "azurerm_traffic_manager_profile" "..." {
  name                   = "..."
  profile_status         = "Enabled"
  resource_group_name    = "..."
  tags                   = {}
  traffic_routing_method = "Weighted"

  dns_config {
    relative_name = "..."
    ttl           = var.ttl
  }

  monitor_config {
    expected_status_code_ranges  = []
    interval_in_seconds          = 10
    port                         = 443
    protocol                     = "TCP"
    timeout_in_seconds           = 5
    tolerated_number_of_failures = 2
  }
}

resource "azurerm_traffic_manager_endpoint" "..." {
  endpoint_status     = "Enabled"
  geo_mappings        = []
  min_child_endpoints = 0
  name                = ".."
  priority            = 2
  profile_name        = azurerm_traffic_manager_profile....name
  resource_group_name = azurerm_traffic_manager_profile....resource_group_name
  target              = "..."
  type                = "externalEndpoints"
  weight              = 50
}

```

### Expected Behaviour

Expected to change only what is in `terraform plan` output.

### Actual Behaviour

Resource that wasn't in `terraform plan` destroyed after `terraform apply`.

### More Info
Terraform plan:
```hcl
# module.atm_mindbox_cdp.azurerm_traffic_manager_profile.mindbox_cdp will be updated in-place
~ resource "azurerm_traffic_manager_profile" "..." {
    fqdn = "..."
    id = "..."
    name = "..."
    profile_status = "Enabled"
    resource_group_name = "..."
 ~ tags = {
    - "isForeign" = "false" - null
    - "product" = "infrastructure" - null
    }
    traffic_routing_method = "Weighted"
    dns_config {
      relative_name = "..."
      ttl = 60
    }
    monitor_config {
      expected_status_code_ranges = []
      interval_in_seconds = 10
      port = 443
      protocol = "TCP"
      timeout_in_seconds = 5
      tolerated_number_of_failures = 2
    }
    timeouts {}
}
```
As you can see, there is nothing criminal in the plan.

We wrote to azure support and get the actual request in json:
```json
{
    "id": "...",
    "name": "...",
    "type": "Microsoft.Network\/trafficManagerProfiles",
    "location": "global",
    "tags": {
        "product": "infrastructure"
    },
    "properties": {
        "profileStatus": "Enabled",
        "trafficRoutingMethod": "Weighted",
        "dnsConfig": {
            "relativeName": "...",
            "fqdn": "...",
            "ttl": 60
        },
        "monitorConfig": {
            "profileMonitorStatus": "Inactive",
            "protocol": "TCP",
            "port": 443,
            "path": "",
            "intervalInSeconds": 10,
            "toleratedNumberOfFailures": 2,
            "timeoutInSeconds": 5,
            "expectedStatusCodeRanges": []
        },
        "endpoints": [],
        "trafficViewEnrollmentStatus": "Disabled"
    }
}
```
Here we can see `"endpoints": []`,  which in my opinion deleted all endpoints because before this request it was looked like this:
```json
        "endpoints": [
            {
                "id": "...",
                "name": "...",
                "type": "Microsoft.Network\/trafficManagerProfiles\/externalEndpoints",
                "properties": {
                    "endpointStatus": "Enabled",
                    "endpointMonitorStatus": "Online",
                    "target": "...",
                    "weight": 50,
                    "priority": 2,
                    "endpointLocation": null,
                    "NestedProfile": null
                }
            },
            {
                "id": "...",
                "name": "...",
                "type": "Microsoft.Network\/trafficManagerProfiles\/externalEndpoints",
                "properties": {
                    "endpointStatus": "Enabled",
                    "endpointMonitorStatus": "Online",
                    "target": "...",
                    "weight": 50,
                    "priority": 3,
                    "endpointLocation": null,
                    "NestedProfile": null
                }
            }
        ]
```

---
Based on that, I assume that there is a bug in the provider that deletes all endpoints of a profile on any changes to it.

**Comment by tombuildsstuff** [comment] 2021-02-04 07:28
hi @nmlc 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #6041 which was fixed in v2.23.0 - as such you'd need to upgrade to that version to get this fix, however at the time of writing the latest release is v2.45.1, so you may wish to upgrade to that version to stay up to date. You can do this by updating the version in the `terraform` (in 0.13+) or `provider` block (0.12) and running `terraform init -upgrade`.

Since this should be fixed by updating the version of the Azure Provider being used here, I'm going to close this issue for the moment - but if this is still an issue on the latest version of the Azure Provider please let us know and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2021-02-04 07:28 UTC
