### ISSUE TITLE
Application Gateway to point to VMSS

### ISSUE THREAD

**Issue by az-cloud** [terraform-providers/terraform-provider-azurerm#7328] opened 2020-06-15 13:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.12.0

### Affected Resource(s)

Trying to deploy 3 tier arch (web, app & DB)

flow -> AppGW (own subnet) --> web tier (VMSS win & Linux) --> internal lb --> app tier (VMSS win & Linux) --> DB (each tier in own subnet)

works fine --> Azure Application Gateway allows to point at a VMSS (web tier) on the backend with upgrade mode MANUAL

facing error --> Azure Application Gateway allows to point at a VMSS (web tier) on the backend with upgrade mode ROLLING, requires health probe ID

is there a fix to it ?

azurerm_windows_virtual_machine_scale_set & azurerm_application_gateway

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_windows_virtual_machine_scale_set" "test" {
  name                      = "Wvmss1"
  resource_group_name       = azurerm_resource_group.test.name
  location                  = var.location
  instances                 = 2
  upgrade_mode              = "Rolling"
  health_probe_id           = " "  --> help on adding probe from app Gw
  

  network_interface {
    name    = "test_vmss1_nic"
    primary = true

    ip_configuration {
      name                                          = "test-vmss1-nic"
      primary                                       = true
      subnet_id                                     = azurerm_subnet.websubnet.id
	  application_gateway_backend_address_pool_ids  = ["${azurerm_application_gateway.testgw.id}/backendAddressPools/test-gw-beap"]
    }
	

### Expected Behavior

Success! The configuration is valid.

### Actual Behavior

Error: Incorrect attribute value type

  on main.tf line 309, in resource "azurerm_windows_virtual_machine_scale_set" "Web_Windows_VMSS":
 309:   health_probe_id           = ["${azurerm_application_gateway.v100_application_gateway.id}/probe/v100-gw-probe"]

Inappropriate value for attribute "health_probe_id": string required.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by az-cloud** [comment] 2020-06-15 14:59
tried removing [] in health_probe_id and received

azurerm_windows_virtual_machine_scale_set.Web_Windows_VMSS: Creating...

Error: Error creating Windows Virtual Machine Scale Set "WebWvmss1" (Resource Group "v100-rg"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJsonReferenceFormat","message":"Reference Id /subscriptions/1c37ebe3-2c26-4571-a01f-fd2ad4831225/resourceGroups/v100-rg/providers/Microsoft.Network/applicationGateways/v100appgw/probe/v100-gw-probe is not formatted correctly. The Id is expected to reference resources of type loadBalancers/probes. Path Properties.UpdateGroups[0].NetworkProfile.healthProbe."}]

  on main.tf line 297, in resource "azurerm_windows_virtual_machine_scale_set" "Web_Windows_VMSS":
 297: resource "azurerm_windows_virtual_machine_scale_set" "Web_Windows_VMSS" {

does this mean i cannot add a appgw/probe and it has to be loadBalancers/probes?

**Comment by ArcturusZhang** [comment] 2020-06-17 03:27
Hi @az-cloud thanks for this issue!

Regarding this 
> does this mean i cannot add a appgw/probe and it has to be loadBalancers/probes?
You are correct, by azure api's design, the `health_probe_id` attribute has to be a lb probe, an application gateway will be rejected. If you would like the VMSS to have `Rolling` upgrade mode, you will have to assign a `health_probe_id` or install an [Application Health Extension](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension) to this VMSS. Currently the `azurerm_linux|windows_virtual_machine_scale_set` does not support inline extensions, therefore the only way that can be done via purely terraform is to assign a `healh_probe_id`.

**Comment by az-cloud** [comment] 2020-06-17 03:35
Hi Arcturus,
Thanks much for the reply and this means at the top layer i have to replace application gateway with public load balancer to achieve this, correct me if iam wrong.
current --> App GW --> webtier --> internal lb --> app tier --> db tier
new --> public lb --> web tier --> internal lb --> app tier --> db tier

**Comment by az-cloud** [comment] 2020-06-17 03:35
Hi Arcturus,

Thanks much for the reply and this means at the top layer i have to replace
application gateway with public load balancer to achieve this, correct me
if iam wrong.

current --> App GW --> webtier --> internal lb --> app tier --> db tier

new --> public lb --> web tier --> internal lb --> app tier --> db tier

Thanks and Regards
Sriram Thanigaimani

**Comment by az-cloud** [comment] 2020-06-17 03:36
Hi Arcturus,
Thanks much for the reply and this means at the top layer i have to replace application gateway with public load balancer to achieve this, correct me if iam wrong.
current --> App GW --> webtier --> internal lb --> app tier --> db tier
new --> public lb --> web tier --> internal lb --> app tier --> db tier

**Comment by tombuildsstuff** [comment] 2020-06-23 09:50
Closing since per @ArcturusZhang's response this is by design in the Azure API - should this behaviour change, Terraform _should_ automatically support this however.

**Closed by tombuildsstuff** 2020-06-23 09:50 UTC
Labels: question, service/application-gateway
