### ISSUE TITLE
cannot update Logic App resource that uses Integration Service Environment

### ISSUE THREAD

**Issue by rpieterick** [terraform-providers/terraform-provider-azurerm#10412] opened 2021-02-01 16:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azurerm v2.43.0

### Affected Resource(s)

* `azurerm_logic_app_workflow`

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_workflow" "example" {
  name                               = "A3QARRRLAP01T"
  location                           = "centralus"
  resource_group_name                = "A3QARRRRSG01T"
  integration_service_environment_id = "/subscriptions/<subscription_id>/resourceGroups/A3DVENTISERSG01/providers/Microsoft.Logic/integrationServiceEnvironments/A3DVENTISE01"
  tags                               = {
    "application_id"       = "RRR"
  }
}
```

### Expected Behaviour

I should be able to update properties of the resource such as tags using the HCL above.

### Actual Behaviour

The apply fails.  The provider seems to be passing null for integration_service_environment_id when updating the resource.

```
azurerm_logic_app_workflow.example: Modifying... [id=/subscriptions/<subscription_id>/resourceGroups/A3QARRRRSG01T/providers/Microsoft.Logic/workflows/A3QARRRLAP01T]

Error: Error updating Logic App Workspace "A3QARRRLAP01T" (Resource Group "A3QARRRRSG01T"): logic.WorkflowsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="WorkflowIntegrationServiceEnvironmentMismatch" Message="The workflow '/subscriptions/<subscription_id>/resourceGroups/A3QARRRRSG01T/providers/Microsoft.Logic/workflows/A3QARRRLAP01T' is associated with integration service environment '/subscriptions/<subscription_id>/resourceGroups/A3DVENTISERSG01/providers/Microsoft.Logic/integrationServiceEnvironments/A3DVENTISE01' which does not match with integration service environment reference '<null>' present in the request definition. Changing the integration service environment of workflow is not supported."
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rizvan-ms** [comment] 2021-02-26 11:11
any updates on this?

**Comment by tombuildsstuff** [comment] 2021-02-26 17:36
Duplicate of #9542

**Closed by tombuildsstuff** 2021-02-26 17:36 UTC
