### ISSUE TITLE
azurerm_frontdoor with multiple front end endpoints and routing rule updates each plan/apply (list unsorted?)

### ISSUE THREAD

**Issue by Mobe1969** [terraform-providers/terraform-provider-azurerm#9930] opened 2020-12-18 02:18 UTC
This is occurring with current release, 2.41.0. I also tried with 2.35.0 and same result.

If you have multiple front end endpoints and routing rules for each, each time you plan or apply, is regenerates the routing rule in different order

`

      ~ routing_rule {
            accepted_protocols = [
                "Https",
            ]
            enabled            = true
          ~ frontend_endpoints = [
              - "wbr-Dev-xxxx",
              + "wbr-Dev-beta-xxxx",
            ]
            id                 = "/subscriptions/xxxx/resourceGroups/xx-Hosted-Dev/providers/Microsoft.Network/frontDoors/xx-Hosted-Dev/routingRules/xxdevwrau-blue-xxxx-rr"
          ~ name               = "xxdevwrau-blue-xxxx-rr" -> "xxdevwrau-gold-xxxx-rr"
            patterns_to_match  = [
                "/*",
            ]

          ~ forwarding_configuration {
              ~ backend_pool_name                     = "xxdevwrau-blue-xxxx-bp" -> "xxdevwrau-gold-xxxx-bp"
                cache_enabled                         = false
                cache_query_parameter_strip_directive = "StripAll"
                cache_use_dynamic_compression         = false
                forwarding_protocol                   = "MatchRequest"
            }
        }

`

**Comment by favoretti** [comment] 2020-12-18 03:02
I have an open PR #9357 that should supposedly fix it, unless you're using dynamics.

**Comment by Mobe1969** [comment] 2020-12-18 03:09
Thanks.

Hmm. I do have two dynamics - but they aren't being deployed in my current configuration, just the two static ones.

**Comment by tombuildsstuff** [comment] 2020-12-18 10:06
hey @Mobe1969 

Taking a look through this appears to be a duplicate of #9153 - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2020-12-18 10:06 UTC
