### ISSUE TITLE
Terraform import resource not releasing lease with Azure storage backend

### ISSUE THREAD

**Issue by janboll** [terraform-providers/terraform-provider-azurerm#997] opened 2018-03-19 09:33 UTC
Hi there,

I tried to import multiple resources using terraform and stumbled over this issue. It appears that terraform is not freeing leases on statefiles once the import ends. 

### Terraform Version
```
terraform -v
Terraform v0.11.4
+ provider.azurerm v1.3.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
Any of the resources

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
...
terraform {
  backend "azurerm" {
    storage_account_name = "xxx"
    container_name       = "xxx"
    key                  = "terraform.tfstate"
  }
}
...
```

### Error Output
```
Acquiring state lock. This may take a few moments...
Error locking state: Error acquiring the state lock: storage: service returned error: StatusCode=409, ErrorCode=LeaseAlreadyPresent, ErrorMessage=There is already a lease present.
RequestId:xxx
Time:2018-03-19T09:29:18.5939748Z, RequestInitiated=Mon, 19 Mar 2018 09:29:17 GMT, RequestId=xxx, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
Lock Info:
  ID:        xxx
  Path:      xxx/terraform.tfstate
  Operation: OperationTypeInvalid
  Who:       xxx@xxx-xxx
  Version:   0.11.4
  Created:   2018-03-19 09:23:46.236776318 +0000 UTC
  Info:


Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
```

### Expected Behavior
What should have happened?
Terraform should import the resource and release the lease afterwards.

### Actual Behavior
What actually happened?
Terraform imported the resources but did not release the lease afterwards

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import module.xxx.azurerm_network_interface.xxx /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkInterfaces/xxx`
2. `terraform import module.xxx.azurerm_network_interface.xxx2 /subscriptions/xxx/resourceGroups/xxx2/providers/Microsoft.Network/networkInterfaces/xxx2`

**Comment by bflad** [comment] 2018-03-20 14:29
Hi @janboll 👋 Sorry you're running into trouble here. We might have identified a potential regression in Terraform 0.11.4 with respect to this behavior: https://github.com/hashicorp/terraform/issues/17624

**Comment by wellingk** [comment] 2018-09-10 12:55
I am having the same issue as @janboll at the moment.  I ran an import now I am locked out, I know how to force an unlock in AWS when this happens, but wanted to store my azure backend in azure.  Is there a way to release?  I have a lot of importing of an existing infra!

**Comment by tombuildsstuff** [comment] 2018-09-12 11:10
👋 hi all

Since this is a bug in the AzureRM Backend (which is housed in [the Terraform Core repository](https://github.com/hashicorp/terraform)) - I'm going to close this issue in favour of the upstream issue https://github.com/hashicorp/terraform/issues/17046, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2018-09-12 11:10 UTC
Labels: bug, upstream-terraform
