### ISSUE TITLE
Wrong default value for HTTP response bode in App GW Health Probe

### ISSUE THREAD

**Issue by kinihun** [terraform-providers/terraform-provider-azurerm#4199] opened 2019-08-30 13:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_1.32.1`

### Terraform Configuration Files

```
resource "azurerm_application_gateway" "app-gateway" {
...
...
...
  probe{
    name = "${local.probe_name}"
    pick_host_name_from_backend_http_settings = true
    interval = 30
    path = "/"
    protocol = "http"
    timeout = 30
    unhealthy_threshold = 3
    match {
      body = ""
      status_code = ["200","201","202","203","204","205","206","207","208","226","300","301","302","303","304","305","306","307","308"]
    }
  }
}
```

### Expected Behavior

The default value should be null, not `*`, the string is not treated as a regex value.
See [(Azure doc)](https://docs.microsoft.com/en-gb/azure/application-gateway/application-gateway-probe-overview)

### Actual Behavior

The field has a value of `*` See [(Terraform doc)](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#body)

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2019-08-30 14:57
hi @kinihun 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1920 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1920 for updates?

Thanks!

**Closed by tombuildsstuff** 2019-08-30 14:57 UTC
Labels: bug, service/application-gateway
