### ISSUE TITLE
azurerm_kubernetes_cluster_node_pool always wants to recreate

### ISSUE THREAD

**Issue by patrickbsf** [terraform-providers/terraform-provider-azurerm#4995] opened 2019-11-26 21:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.11.14
* provider.azurerm v1.37.0

### Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Expected Behavior

Terraform apply, creating the new node pool, followed by subsequent apply with no changes to the resource definition should do nothing.

### Actual Behavior

Terraform wants to delete and recreate the node pool.
ie:

```
-/+ module.xxxpool.azurerm_kubernetes_cluster_node_pool.pool (new resource required)
      id:   "/subscriptions/xxxxx/resourcegroups/yyyygroup/providers/Microsoft.ContainerService/managedClusters/zzzcluster/agentPools/xxxpool" => <computed> (forces new resource)
```

### Steps to Reproduce

Just create an azurerm_kubernetes_cluster_node_pool resource on an existing AKS cluster, adding a pool of any size.   Apply it, letting it create.  Then apply again with no other changes.

**Comment by devblackops** [comment] 2019-11-26 22:45
Yep. I'm seeing this behavior as well.

**Comment by secustor** [comment] 2019-11-27 14:20
Probably the same issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4987

**Comment by patrickbsf** [comment] 2019-11-27 15:10
No, it's not the same issue as this is a completely different workspace, creating only the node pool.  It's standalone from the default/agent_pool_profile issue [which is also a big problem].
Perhaps under the covers the way the ids are handled is ultimately the same issue.  I could see that.

**Comment by tombuildsstuff** [comment] 2019-11-28 08:21
hi @patrickbsf 

Thanks for opening this issue.

Taking a look into this I'm unable to reproduce this using a Cluster with a couple of node pools:

```
------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

So that we can take another look at this, would you be able to provide a Terraform Configuration and the output of a Terraform Plan showing the changes you've mentioned above?

Thanks!

**Comment by patrickbsf** [comment] 2019-12-02 20:31
I tore everything down and tried again.  It appears as though the problem is me not specifying a vnet_subnet_id.  I would think it would just use (because it has to) the vnet_subnet_id of the default pool.  

It ends up doing just that, if not specified on creation, but on re-apply, the 'blank' subnet_id doesn't match the subnet_id that is now in the resource state and it forces recreation each time.

If I use a data resource to get the subnet id and specify it explicitly then it remains stable from run to run.

**Comment by tombuildsstuff** [comment] 2019-12-10 15:05
hey @patrickbsf 

At this time due to the behaviour of the AKS API the `vnet_subnet_id` has to be the same for all node pools within the Kubernetes Cluster - if one isn't specified within the Terraform Configuration for a secondary/additional Node Pool, but /is/ specified for the Default Node Pool then the additional node pool will automatically be placed in the same Subnet as the Default Node Pool.

From chatting with the AKS PM there's an intention to ship support for having multiple node pools on different networks (or some public/private) in the not-too-distant future - as this is a change happening within the API (which Terraform can automatically adopt) for the moment we've [opted to document this in the Kubernetes and Node Pool resources](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#vnet_subnet_id) as a disclaimer that all Node Pools need to be hosted within the same Subnet. When the change is rolled out within AKS in the near future, Terraform should automatically be able to adopt this functionality (and we can remove this disclaimer) - however for the moment all Node Pools will need to specify the same Subnet ID.

Given this is by design I'm going to close this issue for the moment - and it sounds like using the Data Source to retrieve this information solves this for you, but please let us know if it doesn't and we'll take another look :)

Thanks!

**Closed by tombuildsstuff** 2019-12-10 15:05 UTC
Labels: question, service/kubernetes-cluster

**Comment by patrickbsf** [comment] 2019-12-17 18:10
My recommendation then would be to make the subnet_id a required value instead of optional.  This would prevent the confusion (and odd recreation even when the subnet didn't change)

**Comment by tombuildsstuff** [comment] 2019-12-17 18:58
@patrickbsf unfortunately it's optional in the API - since it's possible to create AKS clusters/node pools which aren't on a virtual network
