### ISSUE TITLE
azurerm_storage_blob does not update file in storage account when source file is modified

### ISSUE THREAD

**Issue by eXXL** [terraform-providers/terraform-provider-azurerm#7503] opened 2020-06-25 20:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform 0.12.23
- AzureRM Provider 2.15.0

### Affected Resource(s)

* `azurerm_storage_blob`

### Terraform Configuration Files

I am using Terraform to upload a PowerShell script to an Azure Storage Account using the following snippet.
The script is located in the module folder and named in the variable script_name.

```hcl
resource "azurerm_storage_blob" "blob_dfir" {
  name = var.script_name
  type = "Block"
  size = 512

  storage_account_name   = data.azurerm_storage_account.scripts.name
  storage_container_name = azurerm_storage_container.vms.name

  source = "${path.module}/${var.script_name}"
}
```

### Expected Behavior

When I modify the script file, I expect Terraform to upload the modified script file to the storage account and overwrite the existing file.

### Actual Behavior

The file in the storage account is not overwritten. I have to delete it manually.

**Comment by eXXL** [comment] 2020-06-25 20:25
After manual deletion, the file is of course uploaded again during the next terraform apply run.

**Comment by tombuildsstuff** [comment] 2020-06-26 08:31
hi @eXXL 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1990 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1990 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-26 08:31 UTC
Labels: bug, duplicate, service/storage
