### ISSUE TITLE
azurerm_application_gateway tags update not working

### ISSUE THREAD

**Issue by ChristianGottinger** [terraform-providers/terraform-provider-azurerm#6106] opened 2020-03-13 15:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
azurerm v2.1.0

### Affected Resource(s)

* azurerm_application_gateway

### Terraform Configuration Files

Before updating the azure resource there is already a Tag (Key1) existing.

```hcl
...
tags = {
  Key1             = "value"
  Key2             = "value"
}
...
```
### Panic Output

No errors are logged

### Expected Behavior

Azure ApplicationGateway gets updated and resulting tags are Key1 and Key2

### Actual Behavior

Azure ApplicationGateway is reported as unchanged in plan and apply.

### Steps to Reproduce
1. `terraform apply`
2. Add additional Tag
3. `terraform apply`

### Additional observations
- Tags get applied correctly during creation of ApplicationGateway. Unexpected behavior only updating existing ApplicationGateway
-  Unexpected behavior is specific to azurerm_application_gateway resource
- There is no difference in behavior between azurerm v1 and v2

**Comment by neil-yechenwei** [comment] 2020-05-12 06:02
Thanks for opening this issue. Seems tags can be applied successfully with below tfconfig after manually added tag to the resource. Maybe I missed something. If you need, you can try below tfconfig to check whether the problem still exists.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-appgw-tester"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-vnet-tester"
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
}

resource "azurerm_subnet" "test" {
  name                 = "subnet-tester"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.0.0/24"
}

resource "azurerm_public_ip" "test2" {
  name                = "acctest-pubip2-tester"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
  domain_name_label   = "testdns-123"
}

resource "azurerm_application_gateway" "test" {
  name                = "acctestag-tester"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.test.id
  }

  frontend_port {
    name = "fptester"
    port = 80
  }

  frontend_ip_configuration {
    name                 = "ficntester"
    public_ip_address_id = azurerm_public_ip.test2.id
  }

  backend_address_pool {
    name = "bapntester"
  }

  backend_http_settings {
    name                  = "hsntester"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 1
	
	path                  = "/path1/"
    host_name             = "testdns-123"
  }

  http_listener {
    name                           = "lntester"
    frontend_ip_configuration_name = "ficntester"
    frontend_port_name             = "fptester"
    protocol                       = "Http"
    host_names                     = ["testdns-123"]
  }

  request_routing_rule {
    name                       = "rrrntester"
    rule_type                  = "Basic"
    http_listener_name         = "lntester"
    backend_address_pool_name  = "bapntester"
    backend_http_settings_name = "hsntester"
  }
  
  tags = {
    env = "test123"
	env2 = "test567"
  }
}
```

**Comment by ArcturusZhang** [comment] 2020-06-05 08:43
Hi @ChristianGottinger since we cannot reproduce this issue on the latest provider, could you please have a try to verify if this issue persist? And I will for now close this issue hope you do not mind. If you found this issue persist, please feel free to reopen, comment or open a new issue. Thank you!

**Closed by ArcturusZhang** 2020-06-05 08:43 UTC
Labels: bug, service/application-gateway
