### ISSUE TITLE
azurerm_policy_assignment creates the assigment, but is not granted specified permission (roleDefinitionIds) in policy

### ISSUE THREAD

**Issue by ThomasStubergh** [terraform-providers/terraform-provider-azurerm#11097] opened 2021-03-24 09:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
+ provider registry.terraform.io/hashicorp/local v2.1.0   
+ provider registry.terraform.io/hashicorp/vault v2.19.0  

### Affected Resource(s)

azurerm_policy_assignment 

### Terraform Configuration Files

```hcl
resource "azurerm_policy_definition" "policy" {
  for_each = local.policy_json

  name                  = join("", [var.name_prefix, ": ", each.value.name])
  display_name          = join("", [var.name_prefix, ": ", each.value.properties.displayName])
  policy_type           = each.value.properties.policyType
  mode                  = each.value.properties.mode
  metadata              = jsonencode(each.value.properties.metadata)
  policy_rule           = jsonencode(each.value.properties.policyRule)
  parameters            = jsonencode(each.value.properties.parameters)
  management_group_name = "xxx"

  lifecycle {
    ignore_changes = [
      metadata
    ]
  }
}

resource "azurerm_policy_set_definition" "policy_set" {
  name         = join("", [var.name_prefix, ": Diagnostic Policy Set"])
  display_name = join("", [var.name_prefix, ": Deploys Diagnostic Settings if resources have none"])
  policy_type  = "Custom"
  metadata = jsonencode({
    category : var.policy_set_category
  })
  management_group_name = "xxx"

  lifecycle {
    ignore_changes = [
      metadata
    ]
  }

  dynamic "policy_definition_reference" {

    for_each = azurerm_policy_definition.policy
    content {
      policy_definition_id = policy_definition_reference.value.id
    }
  }

  # Deprecated - Superseded by policy_definition_reference
  # policy_definitions = jsonencode([for p in local.policy_files_without_extension : { "policyDefinitionId" : azurerm_policy_definition.policy[p].id }])
}

resource "azurerm_policy_assignment" "policy_assignment" {
  name  = join("", [var.name_prefix, "-Diag-PA"])
  scope = var.policy_set_assignement_scope
  policy_definition_id = azurerm_policy_set_definition.policy_set.id
  description          = join("", [var.name_prefix, ": Diagnostic Policy Assignment"])
  display_name         = join("", [var.name_prefix, ": Diagnostic Policy Assignment (if resources have none)"])
  location             = var.policy_assignment_location
  enforcement_mode     = var.enforcement_mode

  identity {
    type = "SystemAssigned"
  }
}

locals {
  policy_folder = "${var.root_policy_folder}/${var.policy_type}/"
  policy_files  = fileset(local.policy_folder, "*.json")

  policy_files_without_extension = [for p in local.policy_files : split(".", p)[0]]

  policy_json = {
    for policy in local.policy_files_without_extension :
    policy => jsondecode(file(join("", [local.policy_folder, policy, ".json"])))
  }
}
```

### Debug Output

None

### Panic Output

None

### Expected Behaviour

Asignment is created and proper permissions are assigned in Azure Portal.

### Actual Behaviour

When you click on the assignment in Azure portal and want to create a remediation task, you get the following information warning:

The managed identity for this assignment does not have the appropriate permissions to remediate these resources. To add these permissions, go to the Edit Assignment page for this Policy and re-save it.

When you do as the information explains, the assignment is granted correct permissions.

### Steps to Reproduce

1. Replace variables with values.
2. Create a working policy.json file with roleDefinitionIds in the policy and place it in defined folder. I can supply one of my policies if needed.
3. Run terraform plan/apply.
4. Click on the assignment in the portal and try to create a remediation task.

**Comment by ThomasStubergh** [comment] 2021-03-25 09:22
Update:
I managed to find the problem and solve it by using azurerm_role_assignment on the systemassigned managed identity created in the azurerm_policy_assignment resource. Still I believe that this assignment should be handled by the azurerm_policy_assignment resource. The scope I used was a Management Group, and I need the role assignment to be inherited down to all resources in all subscriptions. I haven't tested if this works if the scope is a subscription or resource group. So for now the solution/workaround was to add this code to the deployment:

```hcl
resource "azurerm_role_assignment" "log_analytics_contrib" {
  name               = "00000000-0000-0000-0000-000000000000"
  scope              = var.policy_set_assignement_scope
  role_definition_id = "/providers/Microsoft.Authorization/roleDefinitions/92aaf0da-9dab-42b6-94a3-d43ce8d16293"
  principal_id       = azurerm_policy_assignment.policy_assignment.identity[0].principal_id
}
```

**Comment by anwojcie** [comment] 2021-07-29 11:54
Just to point that out for future ref:
https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources#how-remediation-security-works
describes you have to create the role assignment manually if the policy(set) assignment is done via SDK.
@katbyte : not a bug I think

**Comment by tombuildsstuff** [comment] 2021-07-29 12:11
Agreed, thanks @anwojcie 

The Azure Portal differs from the Azure API here insofar as it's calling other API's behind the scenes - since this is possible in Terraform using the Role Assignment resources (as described above), I'm going to close this out as working as intended 👍 

Thanks!

**Closed by tombuildsstuff** 2021-07-29 12:11 UTC
Labels: bug, question
