### ISSUE TITLE
azure_mssql_server resource fails to update when an audit policy exists on the server

### ISSUE THREAD

**Issue by OptuMatt** [terraform-providers/terraform-provider-azurerm#10100] opened 2021-01-08 13:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.13.4 Azure Provider 2.41 

### Affected Resource(s)

* `azure_mssql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "sqlserver" { 
  name                         = var.sql_server_name
  resource_group_name          = var.resource_group_name
  location                     = var.azure_location
  version                      = var.sql_server_version
  administrator_login          = var.sql_admin_name
  administrator_login_password = var.sql_admin_password

  azuread_administrator {
    login_username = var.sql_ad_admin_name
    object_id      = var.sql_ad_admin_id
    tenant_id      = var.arm_tenant_id
  }

  lifecycle {
    ignore_changes = [extended_auditing_policy] #Prevents conflicts with DevOps's "Launchpad" Event Hub auditing.
  }
}
```

### Expected Behaviour

Ideally, adding the lifecycle block to ignore changes to the SQL Server’s Extended Auditing Policy should completely ignore any Auditing Policy settings that exists.

### Actual Behaviour

Error: issuing create/update request for SQL Server "*****" Blob Auditing Policies(Resource Group "*****"): sql.ExtendedServerBlobAuditingPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DataSecurityInvalidUserSuppliedParameter" Message="Invalid parameter 'storageEndpoint'. Value should be a blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net)." 
on ..\..\..\modules\azure_sql_DBaaS_server_infrastructure\main.tf line 1, in resource "azurerm_mssql_server" "sqlserver": 
1: resource "azurerm_mssql_server" "sqlserver" { 

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/Azure/azure-rest-api-specs/issues/11271

**Comment by OptuMatt** [comment] 2021-01-08 13:50
There are only 2 ways I’ve been able to get this to run successfully after auditing is enabled.
1.	Remove auditing in the Azure Portal before each deployment.
a.	Removing auditing from the server in the Azure Portal isn’t a good solution, because we deploy several times a day and would need to contact another department to re-run their deployment each time we have a change in our terraform config.
2.	Add a second audit log destination using an extended auditing policy block added to the above resource in my terraform configuration.
a.	While adding a second audit log destination using an extended auditing policy block did prevent the error, this block will soon be deprecated AND this secondary logging is not needed.

Other things I’ve tried with no success.
1.	Add a lifecycle block to ignore changes to the server’s extended auditing policy.
lifecycle {ignore_changes = [extended_auditing_policy]}
a.	  Returns the same error.
2.	Edit the state file, since it has the following…  "extended_auditing_policy": [{"retention_in_days": 0, "storage_account_access_key": "", "storage_account_access_key_is_secondary": false, "storage_endpoint": ""}]
a.	Remove the details of the extended auditing policy from the state file. "extended_auditing_policy": []
i.	Simply adds the details back to the state file and returns the same error.
b.	Remove the extended auditing policy from the state file entirely.
i.	Simply adds the details back to the state file and returns the same error.

**Comment by xuzhang3** [comment] 2021-01-13 08:26
Hi @OptuMatt, I cannot reproduce your error. As I know ,this is a API bug and Terraform cannot manage this, also the azurerm provider provide a workaround in (v2.33.0)[https://github.com/Azure/azure-rest-api-specs/issues/11271#issuecomment-714591674].

**Comment by kaveaa** [comment] 2021-01-14 07:51
hi we have same/similar. Need to set auditing after terraform deployment. Once this is set redeployment fails (always).
for easy reproducing see https://github.com/terraform-providers/terraform-provider-azurerm/issues/8915#issuecomment-729660224

**Comment by OptuMatt** [comment] 2021-01-14 18:59
> Hi @OptuMatt, I cannot reproduce your error. As I know ,this is a API bug and Terraform cannot manage this, also the azurerm provider provide a workaround in (v2.33.0)[https://github.com/[Azure/azure-rest-api-specs/issues/11271](https://github.com/Azure/azure-rest-api-specs/issues/11271)#issuecomment-714591674].

The workaround mentioned here does not appear to work in my situation.  I'm using Terraform 0.13.4 and Azure Provider 2.41.  Does the workaround only work for v2.33?

**Comment by xuzhang3** [comment] 2021-01-15 06:37
@OptuMatt @kaveaa  I tested the script https://github.com/terraform-providers/terraform-provider-azurerm/issues/8915#issuecomment-729660224. The root reason is SQL audit is enabled and the audit log destination is not storage,  `extended_auditing_policy` only support [storage configuration ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server#extended_auditing_policy). 
Here is how this error happened:
1. Create the SQL server resource.
2. Enable the SQL audit out of current TF.
3. Before `apply` again, Terraform will read the resource meta data, because the audit is enabled but the destination is not storage, AzureRM will set `extended_auditing_policy` with empty values [Read and Set Extended Audit Policy](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/mssql/mssql_server_resource.go#L377). During the apply process, Terraform will find the  [extended_auditing_policy configurations](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/mssql/mssql_server_resource.go#L290) even you not configured in the TF files, when Terraform try update the audit configuration, the service will return the  parameter error as the request parameters are all empty values.

**Comment by tombuildsstuff** [comment] 2021-01-15 06:50
👋 

Based on what we can tell this appears to be an API issue - from our side we've been requesting that the Service Team reply to the upstream issue since mid-November, but frustratingly it's been closed instead.

As such to encourage the Service Team to look into this issue, would you mind commenting [on the upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/11271) where someone from the Service Team should be able to take a look - I'd also encourage you to open a Microsoft Support ticket referencing that Github issue.

Since this appears to be an issue in the Azure API rather than something specific to Terraform I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2021-01-15 06:50 UTC

**Comment by kaveaa** [comment] 2021-01-15 08:27
@xuzhang3 thanks for the explanation. Unfotunately we reaally need to do those settings and azurerm does not support them yet.
@tombuildsstuff  thank you for looking into this (again).  We had opened a ticket with microsoft for this beginning of November as well. Yesterday we had a call with product group. they are going to take a further look at it.
in the mean time does it make sense to create a feature request for azurerm to exclude setting properties that it can not cope with like the audit to log analytics settings?

**Comment by OptuMatt** [comment] 2021-01-15 14:11
@tombuildsstuff I have a support request, 121010724001695, in with Azure.  I had commented on https://github.com/Azure/azure-rest-api-specs/issues/11271, before and after it was closed.  There seems to be some finger pointing going on here, and based on several related github issues logged in both Azure and Terraform, there are quite a few impacted by this bug.

I don't want to point fingers and I appreciate that both Azure and Terraform have been looking into this.  But it is a little frustrating, since this has been a problem since mid-October.  How can everyone best work together to come up with a solution?
