### ISSUE TITLE
Possible regression on resource azurerm_lb with plugin 1.8

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#1470] opened 2018-06-30 17:15 UTC
I use this simple code in a module.
With plugin 1.7 it works fine, but with plugin 1.8 it generates this error if you set **private_ip_address_allocation** to dynamic and leave **private_ip_address** empty ("").

Error: module.ambari_MN.azurerm_lb.lb_private: "frontend_ip_configuration.0.private_ip_address" is not a valid IP4 address: ""

    locals {
      lb_private_ip_address_allocation = "dynamic"
      lb_private_ip_address            = ""
      ...
    }

    resource "azurerm_lb" "lb_private" {
      count               = "${local.instances}"
      resource_group_name = "${local.rg_name}"
      name                = "lb_${local.name}"
      location            = "${local.location}"
      sku                 = "${local.lb_sku}"

      frontend_ip_configuration {
        name                          = "${local.private_frontend_ip_conf_name}"
        private_ip_address_allocation = "${local.lb_private_ip_address_allocation}"
        private_ip_address            = "${local.lb_private_ip_address}"
        subnet_id                     = "${data.azurerm_subnet.lb_snet.id}"
      }
    }

My question is whether this situation is final with the plugin1.8 (and I need to duplicate the code once more) or if it is a regression.

Thanks

**Comment by tombuildsstuff** [comment] 2018-07-01 07:33
hey @jcmaasb

Thanks for opening this issue :)

That appears to be a regression in v1.8 of the AzureRM Provider, since it should be possible to set this value to an empty string. We’ll include a fix for this in the next release of the AzureRM provider - apologies for the inconvenience here!

Thanks!

**Comment by jcmaasb** [comment] 2018-07-01 07:57
Thank you very much for your quick reply!

**Closed** 2018-07-03 17:06 UTC
Labels: bug, regression, service/load-balancers

**Comment by alambike** [comment] 2018-07-17 11:18
I think we have similar problem with **subnet_id** not specified in **fronted_ip_configuration** using [Azurerm loadbalancer module](https://github.com/Azure/terraform-azurerm-loadbalancer):

```
$ terraform plan                                                                                                                          1 ↵

Error: module.loadbalancer.azurerm_lb.azlb: Can not parse "frontend_ip_configuration.0.subnet_id" as a resource id: Cannot parse Azure ID: parse 0: invalid URI for request

```

```
$ terraform version                                                                                                                       1 ↵
Terraform v0.11.7
+ provider.azurerm v1.9.0

```
