### ISSUE TITLE
data azurerm_shared_image_version returning 1.0.9 as latest whereas 1.0.12 was the actual latest

### ISSUE THREAD

**Issue by satyakrish** [terraform-providers/terraform-provider-azurerm#10516] opened 2021-02-10 04:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- data azurerm_shared_image_version

* `azurerm_2.45`
### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

data azurerm_shared_image_version should return the 1.0.12 when latest was specified as it was indeed the latest

### Actual Behaviour

data azurerm_shared_image_version returns 1.0.9 as the latest

### Steps to Reproduce

- publish a image with version 1.0.9 to a shared image gallery
- after some time or days publish another image with version 1.0.11 (note that the build for 1.0.10 failed and hence not published)
- then after some time publish version 1.0.12 
- now try to spin up a vm using the latest image, for this provide a data block as below to get the latest image expecting terraform to return 1.0.12 whereas it always returns 1.0.9

```
 variable "shared_image_version" {
  type    = string
  default = "latest"
}


data "azurerm_shared_image_version" "shared_image" {
  name                = var.shared_image_version
  image_name          = var.share_image_definition_name
  gallery_name        = var.shared_image_gallery_name
  resource_group_name = var.shared_image_gallery_resource_group
  # provider = azurerm.provider_integration_hub_np
}
module "virtual_machines" {
  source              = "../../../../xxxx/xxxx/xxxx"
  name                = "lin"
  namespace           = var.namespace
  resource_group_name = azurerm_resource_group.rg.name
  location            = var.location
  admin_login         = var.vm_admin.login
  admin_password      = var.vm_admin.password
  cloud_init_script   = ""
  tags                = var.tags
  vm_count            = var.vm_count
  vm_size             = "Standard_DS3_v2"
  signalfx_auth_token = var.signalfx_auth_token
  source_image_id     = data.azurerm_shared_image_version.shared_image.id
  vm_subnet_id            = data.azurerm_subnet.subnet.id

}
# module.virtual_machines.module.virtual_machines.azurerm_linux_virtual_machine.virtual_machines[0] will be created
  + resource "azurerm_linux_virtual_machine" "virtual_machines" {
      + admin_password                  = (sensitive value)
      + admin_username                  = "o360user"
      + allow_extension_operations      = true
      + computer_name                   = "lin-ansimgmt"
      + disable_password_authentication = false
      + extensions_time_budget          = "PT1H30M"
      + id                              = (known after apply)
      + location                        = "eastus"
      + max_bid_price                   = -1
      + name                            = "lin-ansimgmt"
      + network_interface_ids           = (known after apply)
      + priority                        = "Regular"
      + private_ip_address              = (known after apply)
      + private_ip_addresses            = (known after apply)
      + provision_vm_agent              = true
      + public_ip_address               = (known after apply)
      + public_ip_addresses             = (known after apply)
      + resource_group_name             = "xxxxx"
      + size                            = "Standard_DS3_v2"
      + source_image_id                 = "/subscriptions/xxxxxxx/resourceGroups/xxxx/providers/Microsoft.Compute/galleries/xxxxx/images/xxxxx/versions/1.0.9"
      + tags                          
```

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-02-10 10:33
hi @satyakrish 

Thanks for opening this issue.

Taking a look through here the root cause for this appears to be #10374 - as such rather than having multiple issues open tracking the same thing I'm going to close this in favour of #10374, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-10 10:33 UTC
