### ISSUE TITLE
azurerm_backup_policy_vm : Add support for custom ressource group for restore point collection

### ISSUE THREAD

**Issue by alex-3sr** [terraform-providers/terraform-provider-azurerm#7766] opened 2020-07-15 15:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

Microsoft has released recently (december 2019) the possibility to change ressource group where ares stored restore point collection : https://azure.microsoft.com/en-us/updates/azurebackuprg/
This is an option that we can see in GUI like this ->
![image](https://user-images.githubusercontent.com/38663389/87555430-bb2ead00-c6b5-11ea-8296-429c0768db3b.png)

It could be nice to have this feature in Terraform 

Thanks,
Alexandre

### New or Affected Resource(s)

It's just a new attribute to add in azurerm_backup_policy_vm
* azurerm_backup_policy_vm

### Potential Terraform Configuration

```hcl
resource "azurerm_backup_policy_vm" "ars_pol_01" {
  name                = "POL-BACKUP-01"
  resource_group_name = azurerm_resource_group.rg.name
  **resource_group_name_collection = azurerm_resource_group.rg_collection.name**
  recovery_vault_name = azurerm_recovery_services_vault.ars_vault[0].name
  timezone            = "UTC"

  backup {
    frequency = "Weekly"
    time      = "23:00"
    weekdays  = ["Sunday"]
  }

  retention_weekly {
    count    = 15
    weekdays = ["Sunday"]
  }
}
```

### References

Azure Documentation : https://docs.microsoft.com/en-us/azure/backup/backup-during-vm-creation#azure-backup-resource-group-for-virtual-machines

* #0000

**Comment by ArcturusZhang** [comment] 2020-07-21 05:37
Duplicate of #6622

**Closed by ArcturusZhang** 2020-07-21 05:37 UTC
Labels: enhancement, service/recovery-services
