### ISSUE TITLE
add export/out for azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by tezzigator** [terraform-providers/terraform-provider-azurerm#6359] opened 2020-04-03 22:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Description
would be great (extermely useful!) to have azurerm_kubernetes_cluster export a list of the VM hostnames of all the VM hosts that were created as part of the cluster creation.  This would be used for node affinity purposes.

### New or Affected Resource(s)
azurerm_kubernetes_cluster

### Potential Terraform Configuration
Where we'd be able to use this export/output:
```
output "vmhosts" {
    value = azurerm_kubernetes_cluster.vm_hosts
}
```

**Comment by tezzigator** [comment] 2020-04-11 00:25
Another one:  identityProfile.kubeletidentity.clientId is an attribute of the AKS cluster, but is currently not available to be exported as an output.  This is another item that would be extremely useful as a terraform output.

**Comment by syedhassaanahmed** [comment] 2020-04-11 01:22
+1 to exporting `identityProfile.kubeletidentity.clientId`, it is needed when [installing AAD Pod Identity](https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.msi.md#pre-requisites---role-assignments) on AKS Clusters with Managed Identity enabled.

**Comment by syedhassaanahmed** [comment] 2020-04-14 20:14
After working with `identityProfile.kubeletidentity` block, I'd propose that `identityProfile.kubeletidentity.objectId` should be exported instead of `.clientId` as it makes subsequent role assignment easier and avoids an additional Azure AD lookup.

Furthermore the export should also happen on the [AKS Data Source](https://www.terraform.io/docs/providers/azurerm/d/kubernetes_cluster.html).

**Comment by tombuildsstuff** [comment] 2020-04-16 09:08
hi @tezzigator 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6217 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6217 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-04-16 09:08 UTC
Labels: question, service/kubernetes-cluster
