### ISSUE TITLE
Can't scale AKS AvailabilitySet

### ISSUE THREAD

**Issue by muellermatthias** [terraform-providers/terraform-provider-azurerm#7522] opened 2020-06-29 17:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.25
+ provider.azurerm v2.16.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
    type       = "AvailabilitySet"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }
}

provider "azurerm" {
    features {}
}
```

### Expected Behavior

Changing the node_count from 1 to 2 should scale up the AvailabilitySet.

### Actual Behavior

While applying the change, this error gets thrown:

Error: updating Default Node Pool "example-aks1" (Resource Group "example-resources"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AgentPoolAPIsNotSupported" Message="AgentPool APIs supported only for clusters with VMSS agentpools. For more information, please check https://aka.ms/multiagentpoollimitations"

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2020-06-30 08:49
hi @muellermatthias 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5551 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5551 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-06-30 08:49 UTC
Labels: service/kubernetes-cluster
