### ISSUE TITLE
Key Vault access denied when first created. depends_on doesn't work

### ISSUE THREAD

**Issue by YunziZhangAzure** [terraform-providers/terraform-provider-azurerm#9114] opened 2020-10-31 23:46 UTC
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

Hi, 

Our team run into a similar issue as this one: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4569

I have tried the approach recommended by @tombuildsstuff , but the error still exists.

Could you please take a look at this issue? Please let me know how I can solve this problem. Thanks!

```
// Create user KV with access policy
resource "azurerm_key_vault" "kv_user" {
  count                      = local.enable_deployers ? 1 : 0
  name                       = format("%suser%s", local.kv_prefix, upper(substr(local.postfix, 0, 3)))
  location                   = azurerm_resource_group.deployer[0].location
  resource_group_name        = azurerm_resource_group.deployer[0].name
  tenant_id                  = data.azurerm_client_config.deployer.tenant_id
  soft_delete_enabled        = true
  soft_delete_retention_days = 7
  purge_protection_enabled   = true

  sku_name = "standard"
}

resource "azurerm_key_vault_access_policy" "kv_user_msi" {
  count        = local.enable_deployers ? 1 : 0
  key_vault_id = azurerm_key_vault.kv_user[0].id

  tenant_id = data.azurerm_client_config.deployer.tenant_id
  object_id = azurerm_user_assigned_identity.deployer.principal_id

  secret_permissions = [
    "delete",
    "get",
    "list",
    "set",
  ]
}

resource "azurerm_key_vault_access_policy" "kv_user_pre_deployer" {
  count        = local.enable_deployers ? 1 : 0
  key_vault_id = azurerm_key_vault.kv_user[0].id

  tenant_id = data.azurerm_client_config.deployer.tenant_id
  object_id = data.azurerm_client_config.deployer.object_id != "" ? data.azurerm_client_config.deployer.object_id : "00000000-0000-0000-0000-000000000000"

  secret_permissions = [
    "delete",
    "get",
    "list",
    "set",
  ]

  lifecycle {
    ignore_changes = [
      // Ignore changes to object_id
      object_id,
    ]
  }
}

// Using TF tls to generate SSH key pair and store in user KV
resource "tls_private_key" "deployer" {
  count = (
    local.enable_deployers
    && local.enable_key
    && (try(file(var.sshkey.path_to_public_key), "") == "" ? true : false)
  ) ? 1 : 0
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "azurerm_key_vault_secret" "ppk" {
  depends_on   = [azurerm_key_vault_access_policy.kv_user_pre_deployer[0]]
  count        = (local.enable_deployers && local.enable_key) ? 1 : 0
  name         = format("%s-sshkey", local.prefix)
  value        = local.private_key
  key_vault_id = azurerm_key_vault.kv_user[0].id
}

resource "azurerm_key_vault_secret" "pk" {
  depends_on   = [azurerm_key_vault_access_policy.kv_user_pre_deployer[0]]
  count        = (local.enable_deployers && local.enable_key) ? 1 : 0
  name         = format("%s-sshkey-pub", local.prefix)
  value        = local.public_key
  key_vault_id = azurerm_key_vault.kv_user[0].id
}

```
As you can see, I have used depends_on to force pk is provisoned after the access policy is configured, but this approach doesn't  work. We still got the following error message:

Error: Error checking for presence of existing Secret "U3829-EAUS-DEP00-sshkey" (Key Vault "https://***userfb0.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=***;oid=***;iss=https://sts.windows.net/***/' does not have secrets get permission on key vault '***userFB0;location=eastus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}

**Comment by bastiandg** [comment] 2020-11-02 08:56
This might be related to or even duplicate of #9107 .

You could do a `terraform apply` with `export TF_LOG=TRACE`  to verify.
If the following pops up, the errors probably have the same underlying issue:

```
2020-10-30T11:23:19.179+0100 [DEBUG] plugin.terraform-provider-azurerm_v2.34.0_x5: {"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}
```

**Comment by YunziZhangAzure** [comment] 2020-11-02 18:21
> Bearer or PoP token

Yes! You are right. There are such error messages. And I'm pretty sure this issue just started a few days ago. I haven't seen this issue before.

**Comment by tombuildsstuff** [comment] 2020-11-02 18:25
hey @YunziZhangAzure 

Thanks for confirming @bastiandg's hypothesis - I'd agree with both of you there that this appears to be a duplicate of #9107 - there's a PR open to fix that, however rather than having multiple issues open tracking the same thing I'm going to close this in favour of #9107, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2020-11-02 18:25 UTC
