### ISSUE TITLE
Add support for app_service of kind 'API'

### ISSUE THREAD

**Issue by JamesCarscadden** [terraform-providers/terraform-provider-azurerm#8247] opened 2020-08-25 15:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

An App Service of type API (as a complement to the basic web and function types) has been added to Azure. Provide support for creating this type of resource

### New or Affected Resource(s)

azurerm_api_app (to complement the azurerm_function_app which is azurerm_app_service with kind 'functionapp')

### Potential Terraform Configuration

configuration appears to be to that of the azurerm_app_service or azurerm_function_app

### References

[https://azure.microsoft.com/en-us/services/app-service/api/](https://azure.microsoft.com/en-us/services/app-service/api/)

* #0000

**Comment by tombuildsstuff** [comment] 2020-08-25 16:28
hi @JamesCarscadden 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #443 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #443 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-25 16:28 UTC
