### ISSUE TITLE
Error to increase mysql storage with replica

### ISSUE THREAD

**Issue by m2b-arariba** [terraform-providers/terraform-provider-azurerm#8196] opened 2020-08-21 14:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azurerm v2.23.0
```

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files

```hcl
# Mysql Master
resource "azurerm_mysql_server" "mysql_database" {
  name                              = "mydatabase"
  location                          = "East US 2"
  resource_group_name               = "my-resource-group"
  sku_name                          = "MO_Gen5_8"
  storage_mb                        = 1331200 # it was 102400 mb
  backup_retention_days             = 35
  geo_redundant_backup_enabled      = false
  auto_grow_enabled                 = false
  administrator_login               = "myadmin"
  administrator_login_password      = "mypassword"
  version                           = "5.7"
  ssl_enforcement_enabled           = true
  public_network_access_enabled     = true
}

# Mysql Replica
resource "azurerm_mysql_server" "mysql_database_replica" {
  name                              = "${azurerm_mysql_server.mysql_database.name}-replica"
  location                          = azurerm_mysql_server.mysql_database.location
  resource_group_name               = azurerm_mysql_server.mysql_database.resource_group_name
  sku_name                          = "MO_Gen5_8"
  storage_mb                        = 1331200 # it was 102400 mb
  backup_retention_days             = azurerm_mysql_server.mysql_database.backup_retention_days
  geo_redundant_backup_enabled      = azurerm_mysql_server.mysql_database.geo_redundant_backup_enabled
  auto_grow_enabled                 = true
  version                           = azurerm_mysql_server.mysql_database.version
  ssl_enforcement_enabled           = azurerm_mysql_server.mysql_database.ssl_enforcement_enabled
  public_network_access_enabled     = azurerm_mysql_server.mysql_database.public_network_access_enabled
  create_mode                       = "Replica"
  creation_source_server_id         = azurerm_mysql_server.mysql_database.id
}
```

### Debug Output

```
Error: updating MySQL Server "mydatabase" (Resource Group "my-resource-group"): mysql.ServersClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="ReplicationInvalidStorageSize" Message="The operation could not be completed. The requested storage update would cause the master server to have a larger storage size than its replica(s)."

  on database/mydatabase.tf line 2, in resource "azurerm_mysql_server" "mysql_database":
   2: resource "azurerm_mysql_server" "mysql_database" {
```

### Expected Behavior

It was expected that the replica storage auto grow with the master, or increase the replica storage before the master. 

### Actual Behavior

It tried to increase the replica storage before the master. 

To apply the terraform code, I had to do 2 steps:
1) Increase the replica storage and apply
2) Increase the master storage and apply

### Steps to Reproduce

1. `terraform apply`

**Comment by yupwei68** [comment] 2020-08-26 09:15
Hi @m2b-arariba , thanks for opening this issue. I have tried your steps to reproduce. First, apply two mysql servers. Second, increase the replica storage and apply. Third, increase the master storage and apply. But I could not reproduce your error. They all apply with success in azurerm v2.24.0. Would you mind trying to apply it again in azurerm v2.24.0?

**Comment by m2b-arariba** [comment] 2020-08-26 15:52
Hi @yupwei68 ! To reproduce the error you need to increase the storage in both servers at the same time and apply. This error happens because the Terraform tries to increase the master storage before the replica, and the Azure returns an error.

These steps that you did, was the same as I had done to by-pass the problem. If you still can't reproduce, I can try to apply it again in azurerm v2.24.0.

**Comment by yupwei68** [comment] 2020-08-27 01:58
Thanks @m2b-arariba for more details. I could reproduce your error now. I think this is a by-design service practice instead of a bug. It's not permitted to have the master server storage larger than its replicas, which is reasonable for the service need to replicate all the data into its replicas. Thus, the by-design practice is to enlarge the replicas storage before enlarging the master storage. In terraform, for the replica is dependent on the master server, the update of the master will be applied before the one of the replica, which is against the practice. 
Thus, the only solution will be enlarging the replica servers, and then enlarging the master servers, as what you have done.

**Comment by m2b-arariba** [comment] 2020-08-28 12:32
That's ok.
This error also occurs in the Portal Azure, so Microsoft could do something to fix that since the storage was auto grow.
Thank you @yupwei68 !

**Comment by tombuildsstuff** [comment] 2020-08-28 14:26
@m2b-arariba since this is by design in Azure/the service - it appears that this is working as intended and as such I'm going to close this issue for the moment - however should the API's behaviour change here we'll re-open this and take another look.

Thanks!

**Closed by tombuildsstuff** 2020-08-28 14:26 UTC
Labels: service/mysql
