### ISSUE TITLE
Support for Filesystem Application Logs (Azure App Service Linux)

### ISSUE THREAD

**Issue by grieshaber** [terraform-providers/terraform-provider-azurerm#10552] opened 2021-02-11 17:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

An Linux based Azure App Service does only support Application Logs to the Filesystem. Currently, the provider requires to add a azure_blob_storage configuration in the application_logs block. But, it should also provide a alternative file_system block, so that app logs could be enabled via terraform.

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service" "linux-app" {
  name                = "linux-app"
  ... 
  logs {
    application_logs {
      file_system {
        retention_in_days = 7
        retention_in_mb   = 35
      }
    }
  }
}
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service
* https://docs.microsoft.com/de-de/azure/app-service/troubleshoot-diagnostic-logs

**Comment by tombuildsstuff** [comment] 2021-02-12 12:31
hi @grieshaber 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #1082 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1082 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-02-12 12:31 UTC
Labels: duplicate, enhancement, service/app-service
