### ISSUE TITLE
New Resource: azurerm_app_configuration_key_value 

### ISSUE THREAD

**Issue by mvromer** [terraform-providers/terraform-provider-azurerm#8337] opened 2020-09-03 03:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new resource for setting a key-value in an Azure App Configuration with support for optionally setting its label and content type.

### New or Affected Resource(s)

* azurerm_app_configuration_key_value

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "East US"
}

resource "azurerm_app_configuration" "example" {
  name                = "example-conf"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}

resource "azurerm_app_configuration_key_value" "simple_kv" {
  app_configuration_name = azurerm_app_configuration.example.name

  key   = "sampleKey"
  value = "sampleValue"
}

resource "azurerm_app_configuration_key_value" "label_kv" {
  app_configuration_name = azurerm_app_configuration.example.name

  key   = "sampleKey"
  label = "myLabel"
  value = "anotherSampleValue"
}

resource "azurerm_app_configuration_key_value" "content_type_kv" {
  app_configuration_name = azurerm_app_configuration.example.name

  key          = "sampleKeyWithContentType"
  content_type = "application/json"
  value        = "[1, 2, 3, 4]"
}
```

### References

A couple of possibly interesting notes. Today, App Configuration doesn't really support doing anything with key-values through the Azure management APIs. Based on [this GitHub comment](https://github.com/Azure/azure-rest-api-specs/pull/10224#issuecomment-685435026), it also sounds like the App Config team's preferred approach is to manage key-values through the service's data plane APIs instead. Those APIs are documented [here](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/kv.md).

Also, apparently very recently, the App Config team released support for setting key-values via ARM templates ([ref](https://github.com/Azure/AppConfiguration/issues/268#issuecomment-683495265)). The above GitHub comment is part of a PR that is supposed to expose the relevant management APIs that ARM would use. However, it looks like what is scheduled for release won't support the complete lifecycle for a Terraform resource (namely, you can't delete a key-value through any of the soon-to-be-released management APIs). So even though some APIs will get exposed through ARM for setting key-values, it may be better for use the data plane APIs for the proposed resource.

**Comment by mvromer** [comment] 2020-09-03 03:54
I would have some interest in trying to help implement this. I would definitely welcome any advice/guidance/design review before really going after it. For one, based on some of my research, it seems like implementing this would need to use the data plane APIs of the target App Config instance instead of trying to go through anything exposed via ARM, hence the reason the proposed resource takes the App Config's name and not a resource ID.

Assuming that's the approach you would recommend, I wouldn't know what the best way of adding support for an App Config data plane client to the existing provider. Searching through the source code, I saw that something similar was done for supporting a storage account data plane client [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/a251f1f8ab2ab3d5f042450ea0919faedfbcb519/azurerm/internal/services/storage/client/client.go#L75) which calls out to a vendored library [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/tombuildsstuff/giovanni/storage/2018-11-09/blob/accounts/client.go#L20). Would/Should a similar approach be followed for implementing the proposed resource?

**Comment by tombuildsstuff** [comment] 2020-09-03 08:03
hey @mvromer 

Thanks for opening this issue.

This Provider interacts with Azure in a couple of ways:

- Resource Manager API calls are (generally) made using [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go).
- Data Plane API's are used when practical, depending on the underlying library being available.

Whilst the Resource Manager API's are generally fairly up to date in the Go SDK (presuming the Swagger for an API version is available, which the Go SDK is generated from) - Data Plane API's are unfortunately another story. Each Service Team decides which languages they're going to support with Data Plane SDK's and builds for those - so it's currently really hit and miss for if a Data Plane SDK is available.

In the instance of [Giovanni](https://github.com/tombuildsstuff/giovanni) - [Microsoft introduced a new Storage SDK](https://github.com/Azure/azure-storage-blob-go) which unfortunately didn't meet our needs (it panic'd instead of erroring, only had a single API version available etc) - after raising these bugs (and waiting ~6 months) in order to be able to ship this new functionality we ultimately ended up writing our own Storage SDK.

Whilst we could look to write another SDK for the App Configuration Data Plane API's - there's a larger question on the horizon in the form of the new "Track2" Azure SDK for Go that's being built. Based on what we've seen it appears that this'll also be unsuitable for our needs - and so my next couple of weeks is working out how we proceed with SDK's going forward of which this'll obviously form a part.

With regards to the Resource Manager API's that are available for this (based on the information in the ARM Template) - unfortunately it appears that this is available only in the latest preview version of the API, which is undocumented ([insofar as it doesn't exist in the Swagger repository, which the Azure Go SDK is generated from](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration) - so at this time I think we're blocked with this one in both approaches unfortunately.

Ultimately I think we'd need to implement the Data Plane API's here as you've suggested - but as mentioned above I think we need to first ascertain the general direction we're heading in SDK wise, before committing to building another. As such would you mind if we come back to this in a couple of weeks once we've had an opportunity to work that out?

Thanks!

**Comment by mvromer** [comment] 2020-09-03 13:15
That makes sense, @tombuildsstuff, and thanks for the detailed info! And yeah, I'm good with waiting for the outcomes of the broader SDK design work. Is there a another issue I could track to get updates on that effort as they become available?

**Comment by tombuildsstuff** [comment] 2020-09-03 13:20
@mvromer there's no specific issue right now, it's more something we need to prototype to give us a little more information to see if that's viable than something which'll directly affect users in the short-term, so there's no issue open tracking that right now.

That said - I'm hoping to get started on that early next week, so I'll set a reminder and post an update here in a couple of weeks time when we've got a little more detail :)

**Comment by tombuildsstuff** [comment] 2020-09-03 15:06
@mvromer actually taking a look through here this is a duplicate of #5840 - mind if we consolidate this issue into that one / subscribing to that one for updates?

**Closed by tombuildsstuff** 2020-09-03 15:06 UTC
Labels: question, sdk/not-yet-supported, service/app-configuration, thinking

**Comment by mvromer** [comment] 2020-09-03 15:21
Sounds good. I'll track that one. Thanks!

**Comment by arkiaconsulting** [comment] 2020-09-04 05:31
@mvromer If it can help, I wrote a provider some months ago (standard values and secrets as well)

https://github.com/arkiaconsulting/terraform-provider-akc

**Comment by mvromer** [comment] 2020-09-04 12:57
Awesome, @arkiaconsulting! I'll be sure to check it out. Thanks for the tip!
