### ISSUE TITLE
Azure Disk Encryption with VM Extensions vs. Using Managed Disks

### ISSUE THREAD

**Issue by stefan-rapp** [terraform-providers/terraform-provider-azurerm#5102] opened 2019-12-06 19:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.7
+ provider.azurerm v1.33.1
```

### Affected Resource(s)

* `azurerm_managed_disk`
* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

I created several VMs with managed (data) disks a few month ago according to the following resource :

```hcl
resource "azurerm_managed_disk" "md" {
    count                   = "${var.md_count}"
    name                    = "${var.md_name}-disk${count.index}"
    location                = "${var.md_location}"
    resource_group_name     = "${var.md_rg_name}"
    storage_account_type    = "${var.md_storage_account_type}"
    create_option           = "${var.md_create_option}"
    source_uri              = "${var.md_create_option == "Import" ? var.md_source_uri : null}"
    source_resource_id      = "${var.md_create_option == "Copy" || var.md_create_option == "Restore" ? var.md_source_resource_id : null}"
    image_reference_id      = "${var.md_create_option == "FromImage" ? var.md_image_reference_id : null}"
    os_type                 = "${var.md_create_option == "Copy" || var.md_create_option == "Import" ? var.md_os_type : null}"
    disk_size_gb            = "${var.md_disk_size_gb != "" ? var.md_disk_size_gb : null}"
    tags                    = "${merge(local.default_tags, var.md_tags)}"
}
```

I configured all VMs already (Software, Services, etc) and now the customer has the requirement to encrypt the disks using **BitLocker**. So I created the following resource to encrypt 'All' disk of a VM, and it worked fine so far:

```hcl
resource "azurerm_virtual_machine_extension" "vm_encry_win" {
  count                         = "${var.vm_encry_os_type == "Windows" ? 1 : 0}"
  name                          = "${var.vm_encry_name}"
  location                      = "${var.vm_encry_location}"
  resource_group_name           = "${var.vm_encry_rg_name}"
  virtual_machine_name          = "${var.vm_encry_vm_name}"
  publisher                     = "${var.vm_encry_publisher}"
  type                          = "${var.vm_encry_type}"
  type_handler_version          = "${var.vm_encry_type_handler_version == "" ? "2.2" : var.vm_encry_type_handler_version}"
  auto_upgrade_minor_version    = "${var.vm_encry_auto_upgrade_minor_version}"
  tags                          = "${var.vm_encry_tags}"

  settings = <<SETTINGS
                {
                    "EncryptionOperation":      "${var.vm_encry_operation}",
                    "KeyVaultURL":              "${var.vm_encry_kv_vault_uri}",
                    "KeyVaultResourceId":       "${var.vm_encry_kv_vault_id}",
                    "KeyEncryptionKeyURL":      "${var.vm_encry_kv_key_url}",
                    "KekVaultResourceId":       "${var.vm_encry_kv_vault_id}",
                    "KeyEncryptionAlgorithm":   "${var.vm_encry_key_algorithm}",
                    "VolumeType":               "${var.vm_encry_volume_type}"
                }
             SETTINGS
}
```

### Expected Behavior

The disks are encrypted and a re-run of `terraform plan` or `terraform apply` does **NOT** cause any changes.

### Actual Behavior

I have now a bigger issue regrading the encryption of managed Disks. When I re-run terraform using `terraform plan` or `terraform apply`, it wants to replace all my data disks I have already created, like the following screenshot illustrates. 

![2019-12-06 19_48_58-Window](https://user-images.githubusercontent.com/45358082/70348037-1962fa00-1862-11ea-9f3f-42ff26524b69.png)

I know that the problem is the `encryption_settings` section of the managed disk setting, but I do not know how to solve it. And my already created disks should not be replaces.

Does anyone has an idea? Appreciate it!

**Comment by stefan-rapp** [comment] 2019-12-07 11:57
@tombuildsstuff : Any idea why the `encryption_settings` of the managed disk force a replacement, if I use the `azurerm_virtual_machine_extension` with `Microsoft.Azure.Security`? Normally the `azurerm_managed_disk `should not do a replacement as I did not configure the `encryption_settings `for managed disk, as the code above shows. Is there a workaround? Thx.

**Comment by ArcturusZhang** [comment] 2019-12-23 05:47
By the definition of go sdk, the encryption setting enable of managed disks should be updatable ([code](https://github.com/Azure/azure-sdk-for-go/blob/781d9fb592a1818cb7fb8e0855ea9c00b095a9e9/services/compute/mgmt/2019-07-01/compute/disks.go#L693)). But I found a comment in the terraform code [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/6e006ff4e5d1fb200a6b37eb2743ff0ec8b11e0d/azurerm/encryption_settings.go#L20):
```
// Azure can change enabled from false to true, but not the other way around, so
//   to keep idempotency, we'll conservatively set this to ForceNew=true
```
Therefore I suppose that this `ForceNew` is only a temporary workaround to solve some other issues here.
Could the `ignore_changes` attribute work? You can find description of this [here](https://www.terraform.io/docs/configuration/resources.html). Maybe you can use this attribute to tell terraform to ignore the diff on `encryption_settings`, if this works, terraform will not try to replace the disk.

**Comment by stefan-rapp** [comment] 2019-12-23 08:43
Hi @ArcturusZhang,
thanks for your reply. 
The problem is solved. I found the following solution on #486 
The following code works fine:

```hcl
lifecycle {
        ignore_changes = [encryption_settings]
    }
```

Thx! 👍

**Comment by tombuildsstuff** [comment] 2020-06-25 07:57
hey @stefan-rapp 

Glad to hear this is now working for you - since this is working as intended (as Terraform should detect these changes not present in the config) - I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2020-06-25 07:57 UTC
Labels: question, service/virtual-machine-extensions
