### ISSUE TITLE
kubernetes node pool mode support

### ISSUE THREAD

**Issue by arodriguezdlc** [terraform-providers/terraform-provider-azurerm#6536] opened 2020-04-20 10:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure has released a new version of AKS service: https://github.com/Azure/AKS/releases/tag/2020-04-13. In this new version, they have introduced the *Mode* property for nodepools. This provider should also support this property.  

### New or Affected Resource(s)

* `azurerm_kubernetes_cluster`
* `azurerm_kubernetes_cluster_node_pool`

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  mode = System # Or User. System should be default value for retrocompatibility

  tags = {
    Environment = "Production"
  }
}
```

### References

 https://github.com/Azure/AKS/releases/tag/2020-04-13

**Comment by tombuildsstuff** [comment] 2020-04-20 10:25
Duplicate of #6058

**Closed by tombuildsstuff** 2020-04-20 10:25 UTC
