### ISSUE TITLE
azurerm_role_assignment doesn't work on first run

### ISSUE THREAD

**Issue by raycrawford** [terraform-providers/terraform-provider-azurerm#2113] opened 2018-10-18 18:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.azurerm v1.16.0

### Affected Resource(s)

* azurerm_role_assignment

### Terraform Configuration Files

```
provider "azurerm" {
  version = "= 1.16.0"
 }

data "azurerm_subscription" "primary" {}

resource "azurerm_azuread_application" "tfRunner" {
  name                       = "Terraform Runner"
  homepage                   = "https://tfRunner.io"
  identifier_uris            = ["https://tfRunner.io"]
  reply_urls                 = ["https://tfRunner.io"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
}

resource "azurerm_azuread_service_principal" "tfRunner" {
  application_id = "${azurerm_azuread_application.tfRunner.application_id}"
}

resource "azurerm_role_assignment" "tfRunner" {
  scope = "${data.azurerm_subscription.primary.id}"
  role_definition_name = "Owner"
  principal_id = "${azurerm_azuread_service_principal.tfRunner.id}"
}

resource "azurerm_azuread_service_principal_password" "tfRunner" {
  service_principal_id = "${azurerm_azuread_service_principal.tfRunner.id}"
  value                = "blahblahblahblah"
  end_date             = "2028-01-01T01:02:03Z"
}
```

### Debug Output

https://gist.github.com/raycrawford/19a9e8223ae071b7053d9f77d1b3d405

### Panic Output

NA

### Expected Behavior

Creation and assignment of Service Principal to the Subscription Owner RBAC role.

### Actual Behavior

Service Principal and associated App created, but the SP was not added to the Subscription RBAC on first run.  On subsequent runs, the SP was added.  This behavior works as expected in 1.15.0 and is broken in 1.16.0.

### Steps to Reproduce

1. az login (authZ must be at least Subscription Owner)
1. `terraform apply`

### Important Factoids

Works in 1.15.0.  Does not work in 1.16.0.

### References

NA

**Comment by straubt1** [comment] 2018-10-18 19:19
Can confirm, this occurs in `1.16.0` and not in `1.15.0`.

**Comment by dbilleci-lightstream** [comment] 2018-10-27 00:51
Hit this today too!

**Comment by tombuildsstuff** [comment] 2018-11-02 23:37
hi @raycrawford @straubt1 @dbilleci-lightstream 

Thanks for opening this issue :)

Taking a look into this this appears to be a duplicate of #1635 as such I'm going to close this issue in favour of that one - please subscribe to that issue for updates!

Thanks!

**Closed by tombuildsstuff** 2018-11-02 23:37 UTC
Labels: bug, service/authentication
