### ISSUE TITLE
Error: Provider produced inconsistent final plan in azurerm_monitor_diagnostic_setting

### ISSUE THREAD

**Issue by Anbukugan** [terraform-providers/terraform-provider-azurerm#7620] opened 2020-07-08 12:55 UTC
### Terraform (and AzureRM Provider) Version

* Terraform v0.12.28
* provider.azurerm v2.17.0

### Affected Resource(s)

* azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```
data "azurerm_monitor_diagnostic_categories" "main" {
  count       = length(var.diag_name)   
  resource_id = var.resource_id[count.index]
}

resource "azurerm_monitor_diagnostic_setting" "main" {
  count              = length(var.diag_name) 
  name               = var.diag_name[count.index]
  target_resource_id = var.resource_id[count.index]

  storage_account_id = "/subscriptions/${var.env_subscription_id}/resourceGroups/${var.diag_storage_resource_group}/providers/Microsoft.Storage/storageAccounts/${var.diag_storage_account_name}"
  

  dynamic "log" {
    for_each =  element(data.azurerm_monitor_diagnostic_categories.main.*.logs, count.index)

    content {
      category = log.key
    }
  }

  dynamic "metric" {
    for_each = element(data.azurerm_monitor_diagnostic_categories.main.*.metrics, count.index)

    content {
      category = metric.key
      
    }
  }
}
```

### Debug Output
Error: Provider produced inconsistent final plan

When expanding the plan for
module.Monitoring.module.diagnostic_setting.azurerm_monitor_diagnostic_setting.main[2]
to include new values learned so far during apply, provider
"registry.terraform.io/-/azurerm" produced an invalid new value for .log:
block set length changed from 1 to 3.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.Monitoring.module.diagnostic_setting.azurerm_monitor_diagnostic_setting.main[3]
to include new values learned so far during apply, provider
"registry.terraform.io/-/azurerm" produced an invalid new value for .log:
planned set element
cty.ObjectVal(map[string]cty.Value{"category":cty.UnknownVal(cty.String),
"enabled":cty.True,
"retention_policy":cty.ListValEmpty(cty.Object(map[string]cty.Type{"days":cty.Number,
"enabled":cty.Bool}))}) does not correlate with any element in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.Monitoring.module.diagnostic_setting.azurerm_monitor_diagnostic_setting.main[1]
to include new values learned so far during apply, provider
"registry.terraform.io/-/azurerm" produced an invalid new value for .log:
block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

**Comment by ausfestivus** [comment] 2020-07-09 02:17
Probably a dupe of https://github.com/terraform-providers/terraform-provider-azurerm/issues/6254

**Comment by magodo** [comment] 2020-07-17 01:56
@Anbukugan Thank you for submitting this!
This issue is duplicated with #6254, you can subscribe to that to track any progress. Hope you don't mind I close this issue for now.

**Closed by magodo** 2020-07-17 01:56 UTC
Labels: service/monitor
