### ISSUE TITLE
Error message should be more explicit

### ISSUE THREAD

**Issue by iriahk89** [terraform-providers/terraform-provider-azurerm#6348] opened 2020-04-03 07:31 UTC
Getting this error from terraform when destroy command failing:

![image](https://user-images.githubusercontent.com/19380966/78335992-3796f780-75c1-11ea-8a72-0cdeb05ab5e3.png)

Its not explicit at all compare to the error thrown that i get from activity log in portal as below:

![image](https://user-images.githubusercontent.com/19380966/78335800-de2ec880-75c0-11ea-96df-7a1c2cb64c51.png)

It will be nice if we could have same error message to ease the trouble shooting

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_app_service_plan

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2020-08-28 09:32
hi @iriahk89 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #6348 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6348 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-08-28 09:32 UTC
Labels: duplicate, enhancement, service/app-service
