### ISSUE TITLE
Diagnostic settings can't be added for Azure Storage (categories not accepted)

### ISSUE THREAD

**Issue by geekzter** [terraform-providers/terraform-provider-azurerm#8275] opened 2020-08-27 16:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Diagnostic settings can't be added for categories that are used for Azure Storage (currently in preview).

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azurerm v2.25.0
+ provider.random v2.3.0

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
locals {
  resource_group_name          = "storage-${lower(random_string.suffix.result)}"
  resource_group_name_short    = substr(lower(replace(local.resource_group_name,"-","")),0,20)

  tags                         = {
    application                = "Storage Diagnostic Setting Issue"
    provisioner                = "Terraform"
  }
}

resource random_string suffix {
  length                       = 4
  upper                        = false
  lower                        = true
  number                       = false
  special                      = false
}

resource azurerm_resource_group rg {
  name                         = local.resource_group_name
  location                     = var.location

  tags                         = local.tags
}

resource azurerm_storage_account diag_storage {
  name                         = "${lower(replace(local.resource_group_name,"-",""))}diag"
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  account_kind                 = "StorageV2"
  account_tier                 = "Standard"
  account_replication_type     = "LRS"

  tags                         = local.tags
}

resource azurerm_log_analytics_workspace workspace {
  name                         = "${azurerm_resource_group.rg.name}-loganalytics"
  location                     = azurerm_resource_group.rg.location
  resource_group_name          = azurerm_resource_group.rg.name
  sku                          = "Standalone"
  retention_in_days            = 90 

  tags                         = local.tags
}

resource azurerm_storage_account storage {
  name                         = "${local.resource_group_name_short}stor"
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  account_kind                 = "StorageV2"
  account_tier                 = "Standard"
  account_replication_type     = "LRS"

  provisioner "local-exec" {
    # Classic methof for storage logging
    command                    = "az storage logging update --account-name ${self.name} --log rwd --retention 90 --services b"
  }

  tags                         = local.tags
}

resource azurerm_monitor_diagnostic_setting storage {
  name                         = "${azurerm_storage_account.storage.name}-logs"
  target_resource_id           = azurerm_storage_account.storage.id
  storage_account_id           = azurerm_storage_account.diag_storage.id
  log_analytics_workspace_id   = azurerm_log_analytics_workspace.workspace.id

  log {
    # Fails, even when having access to private preview of diagnostic log settings
    # https://docs.microsoft.com/en-us/azure/storage/common/monitor-storage?tabs=azure-powershell#configuration
    # https://docs.microsoft.com/en-us/azure/azure-monitor/platform/resource-logs-categories#microsoftstoragestorageaccountsblobservices
    category                   = "StorageWrite"
    enabled                    = true

    retention_policy {
      enabled                  = false
    }
  }
}
```

### Expected Behavior

Diagnostic setting created, as it is when configured in the Azure Portal

### Actual Behavior

Error: Error creating Monitor Diagnostics Setting "storageodgxstor-logs" for Resource "/subscriptions/84c1a2c7-585a-4753-ad28-97f69618cf12/resourceGroups/storage-odgx/providers/Microsoft.Storage/storageAccounts/storageodgxstor": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Category 'StorageWrite' is not supported."
### Steps to Reproduce

1. `terraform init`
1. `terraform apply`

### Important Factoids

Azure Storage diagnostic settings are in private preview

### References
Description of Storage Account diagnostic setting categories (StorageRead, StorageWrite, StorageDelete):    
https://docs.microsoft.com/en-us/azure/storage/common/monitor-storage?tabs=azure-powershell#configuration
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/resource-logs-categories#microsoftstoragestorageaccountsblobservices

**Comment by neil-yechenwei** [comment] 2020-08-31 02:23
Thanks for opening. Seems it's an API limitation so that terraform cannot support it for now. So I filed an [issue](https://github.com/Azure/azure-rest-api-specs/issues/10646) on rest api side. Once the api is ready, terraform could be added support for it.

**Comment by lawrencegripper** [comment] 2021-01-06 10:37
Hey @neil-yechenwei I also hit this issue, looks like the APIs are available just not the same as the currently used one and it's possible to work around it. (Skip to the bottom if that's all you want to know)

If you call `/subscriptions/<SUBHERE>/resourceGroups/<RGHere>/providers/Microsoft.Storage/storageAccounts/<STORAGEACCOUNTHERE>/blobServices/default/providers/microsoft.insights/diagnosticSettingsCategories?api-version=2017-05-01-preview` then the full list of categories is provided.

The following request will allow creation of the settings, these are captured by looking at how the Azure Portal calls the API.

```
PUT /subscriptions/<SUBHERE>/resourceGroups/<RGHere>/providers/Microsoft.Storage/storageAccounts/<STORAGEACCOUNTHERE>/blobServices/default/providers/microsoft.insights/diagnosticSettings/readlogs?api-version=2017-05-01-preview HTTP/1.1
Host: management.azure.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: */*
Accept-Language: en
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
```

Looking at the current calls made by TF they are to `https://management.azure.com/subscriptions/<subhere>/resourceGroups/testenv21/providers/Microsoft.Storage/storageAccounts/<storagehere>/providers/microsoft.insights/diagnosticSettings/readwritenlqcd?api-version=2017-05-01-preview`

Given how the URL is composed you can add the additional `/blobServices/default/` to the `target_resource_id` and things behave as expected.

So the following TF will do the trick 

```terraform
resource "azurerm_monitor_diagnostic_setting" "core-diagnostic" {
  name                       = "readwrite${random_string.random.result}"
  target_resource_id         = "${azurerm_storage_account.core.id}/blobServices/default/"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.core.id

  log {
    category = "StorageRead"
    enabled  = true
  }

  log {
    category = "StorageWrite"
    enabled  = true
  }

  metric {
    category = "Transaction"
    enabled  = true
    retention_policy {
      days    = 5
      enabled = true
    }
  }
}

Running TF with debug logs we can now see the request correctly generated

```
2021-01-06T10:32:46.961Z [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/SUBHERE/resourceGroups/testenv21/providers/Microsoft.Storage/storageAccounts/ACCHERE/blobServices/default//providers/microsoft.insights/diagnosticSettings/readwritenlqcd?api-version=2017-05-01-preview: 
2021-01-06T10:32:46.961Z [DEBUG] plugin.terraform-provider-azurerm_v2.41.0_x5: HTTP/2.0 200 OK
```

@tombuildsstuff / @neil-yechenwei is this something I should add to the docs for the resource to help others out who hit this issue?

**Comment by zgalford** [comment] 2021-01-29 20:28
So we're seeing something similar where when we're attempting to apply monitor settings to a storage blob, except that we're getting that the path is not divisible by 2.  For kicks & giggles we also added the "/blobServices/default/" to the end of our target_resource_id to see if that would assist, but it still provides the same error:

```
Can not parse "target_resource_id" as a resource id: The number of path segments is not divisible by 2 in "terratest-dev-container/blobServices/default"

  on main.tf line 65, in resource "azurerm_monitor_diagnostic_setting" "iac-terratest":
  65: resource "azurerm_monitor_diagnostic_setting" "iac-terratest" {


azurerm_resource_group.iac-terratest: Refreshing state... [id=/subscriptions/<subscriptionID>/resourceGroups/terratest-dev-rg]
azurerm_storage_account.iac-terratest: Refreshing state... [id=/subscriptions/<subscriptionID>/resourceGroups/terratest-dev-rg/providers/Microsoft.Storage/storageAccounts/terratestdevsa]
azurerm_storage_container.iac-terratest: Refreshing state... [id=https://terratestdevsa.blob.core.windows.net/terratest-dev-container]
azurerm_storage_blob.iac-terratest: Refreshing state... [id=https://terratestdevsa.blob.core.windows.net/terratest-dev-container/terratest-dev-blob]
```

Here's our code:
```
resource "azurerm_resource_group" "iac-terratest" {
  name     = "${var.application}-${var.environment}-rg"
  location = var.location
  tags     = var.tags
}

resource "azurerm_storage_account" "iac-terratest" {
  name                     = "${var.application}${var.environment}sa"
  location                 = azurerm_resource_group.iac-terratest.location
  resource_group_name      = azurerm_resource_group.iac-terratest.name
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags                     = var.tags
}

resource "azurerm_storage_container" "iac-terratest" {
  name = "${var.application}-${var.environment}-container"
  storage_account_name = azurerm_storage_account.iac-terratest.name
}

resource "azurerm_storage_blob" "iac-terratest" {
  name = "${var.application}-${var.environment}-blob"
  storage_account_name = azurerm_storage_account.iac-terratest.name
  storage_container_name = azurerm_storage_container.iac-terratest.name
  type = "Block"
}

resource "azurerm_monitor_diagnostic_setting" "iac-terratest" {
  name = "${var.application}-${var.environment}-activity-ds"
  target_resource_id = "${azurerm_storage_container.iac-terratest.id}/blobServices/default/"
  storage_account_id = azurerm_storage_account.iac-terratest.id
  log {
    category = "StorageRead"
    enabled = true
    retention_policy {
      enabled = false
    }
  }
  log {
    category = "StorageWrite"
    enabled = true
    retention_policy {
      enabled = false
    }
  }
  log {
    category = "StorageDelete"
    enabled = true
    retention_policy {
      enabled = false
    }
  }
  metric {
    category = "AllMetrics"
    retention_policy {
      enabled = false
    }
  }
}
```

**Comment by lawrencegripper** [comment] 2021-01-30 07:14
@zgalford Hopefully an easy fix. In your shared snippet `target_resource_id` is set to to the ID of your `container` resource. It should be your `azure_storage_accounts` ID like below:

`target_resource_id         = "${azurerm_storage_account.core.id}/blobServices/default/" `

**Comment by rosych** [comment] 2021-02-24 20:54
@lawrencegripper, thanks for your [post](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8275#issuecomment-755222989), works like a charm!

**Comment by kemmemha** [comment] 2021-03-31 11:48
Maybe just as help the other `target_resource_id` are:

- id
- id/blobServices/default/
- id/queueServices/default/
- id/tableServices/default/

With the resource id's above you can reference all 5 resources of the Storage Account.

**Comment by abij** [comment] 2021-04-02 07:41
I can confirm it works, sending Azure Storage audit events (read/write/delete) to LogAnalytics using Terraform azurerm: `v2.53.0`.

I noticed that all details for `azurerm_monitor_diagnostic_setting` need to be specified, otherwise it's changing the resource each apply run.

```
resource azurerm_resource_group resource_group {
  name     = "tf_test_my_rg"
  location = "West Europe"
}

resource azurerm_storage_account datalake {
  name                     = "tftestunique123"
  resource_group_name      = azurerm_resource_group.resource_group.name
  location                 = azurerm_resource_group.resource_group.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
}

resource azurerm_log_analytics_workspace audit_logs {
  name                = "log-analytics-audit-collector-01"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  sku                 = "PerGB2018"
}

locals {
  # See: https://github.com/terraform-providers/terraform-provider-azurerm/issues/11099
  log_analytics_workspace_id = replace(replace(azurerm_log_analytics_workspace.audit_logs.id, "microsoft.operationalinsights", "Microsoft.OperationalInsights"), "resourcegroups", "resourceGroups")
}


resource azurerm_monitor_diagnostic_setting datalake_blob_audit {
  name                       = "audit-log-collector"
  target_resource_id          = "${azurerm_storage_account.datalake.id}/blobServices/default/"
  log_analytics_workspace_id = local.log_analytics_workspace_id

  log {
    category = "StorageRead"
    enabled  = true
    retention_policy {
      days    = 0
      enabled = false
    }
  }
  log {
    category = "StorageWrite"
    enabled  = true
    retention_policy {
      days    = 0
      enabled = false
    }
  }
  log {
    category = "StorageDelete"
    enabled  = true
    retention_policy {
      days    = 0
      enabled = false
    }
  }

  metric {
    category = "Transaction"
    enabled  = false
    retention_policy {
      days    = 0
      enabled = false
    }
  }
  metric {
    category = "Capacity"
    enabled  = false
    retention_policy {
      days    = 0
      enabled = false
    }
  }
}
```

**Comment by sebader** [comment] 2021-07-22 11:40
for completeness, based on @abij's post, here is my, fully dynamic solution for both storage-level as well as blob-level logging:

```
resource "azurerm_storage_account" "stamp" {
#...
}

# Use this data source to fetch all available log and metrics categories. We then enable all of them
data "azurerm_monitor_diagnostic_categories" "storage" {
  resource_id = azurerm_storage_account.stamp.id
}

resource "azurerm_monitor_diagnostic_setting" "storage" {
  name                       = "storageladiagnostics"
  target_resource_id         = azurerm_storage_account.stamp.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.stamp.id

  dynamic "log" {
    iterator = entry
    for_each = data.azurerm_monitor_diagnostic_categories.storage.logs

    content {
      category = entry.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 30
      }
    }
  }

  dynamic "metric" {
    iterator = entry
    for_each = data.azurerm_monitor_diagnostic_categories.storage.metrics

    content {
      category = entry.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 30
      }
    }
  }
}

data "azurerm_monitor_diagnostic_categories" "storage_blob" {
  resource_id = "${azurerm_storage_account.stamp.id}/blobServices/default/"
}

resource "azurerm_monitor_diagnostic_setting" "storage_blob" {
  name                       = "storageblobladiagnostics"
  target_resource_id         = "${azurerm_storage_account.stamp.id}/blobServices/default/"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.stamp.id

  dynamic "log" {
    iterator = entry
    for_each = data.azurerm_monitor_diagnostic_categories.storage_blob.logs

    content {
      category = entry.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 30
      }
    }
  }

  dynamic "metric" {
    iterator = entry
    for_each = data.azurerm_monitor_diagnostic_categories.storage_blob.metrics

    content {
      category = entry.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 30
      }
    }
  }
}
```

**Comment by tombuildsstuff** [comment] 2021-07-22 12:29
Closing this out since this question appears to be resolved / this is now possible using the example above

**Closed by tombuildsstuff** 2021-07-22 12:29 UTC
Labels: preview, question, service/monitor, service/storage
