### ISSUE TITLE
Bug creating 'azurerm_role_assignment' and adding it to state

### ISSUE THREAD

**Issue by OmerLaza** [terraform-providers/terraform-provider-azurerm#12195] opened 2021-06-13 15:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.62.0

### Affected Resource(s)

* `azurerm.azurerm_role_assignment`

### Terraform Configuration Files

Full TF here
https://gist.github.com/OmerLaza/6d68de4382e8f2b14e100595774a9b22

### Debug Output
https://gist.github.com/OmerLaza/6d68de4382e8f2b14e100595774a9b22

### Panic Output

When applying changes to azurerm_role_assignment.example, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root │ resource was present, but now absent.

### Expected Behaviour
TF creating the resources properly and adding then to the state file.

### Actual Behaviour

The ```apply``` ending in an error (yet creating the ```azurerm_role_assignment```, but not adding it to the state.

### Steps to Reproduce

1. `terraform apply` the TF file provided earlier.

**Comment by drjwelch** [comment] 2021-06-13 23:46
I have also seen this issue - I think it may be related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/1726.  I hacked around it by deleting the resource in the state and the portal; tf was then able to recreate the resource on the next apply.

**Comment by tombuildsstuff** [comment] 2021-06-14 06:34
hey @OmerLaza 

Unfortunately this was a regression in v2.62.0 which has since been fixed in v2.62.1 - as such you'd need to upgrade to that release (or the latest release v2.63.0) - but since this regressions been fixed I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2021-06-14 06:34 UTC

**Comment by aristosvo** [comment] 2021-06-14 06:35
Bumping your provider version to 2.62.1 or later will definitely help, although you've to manually remove the role assignment in the portal before running.

**Comment by OmerLaza** [comment] 2021-06-14 07:25
@tombuildsstuff Thanks 😄
I've upgraded the provider to v2.63.0 and the problem has been fixed.
