### ISSUE TITLE
[azurerm_app_service and azurerm_function_app] Support for siteextensions

### ISSUE THREAD

**Issue by nexxai** [terraform-providers/terraform-provider-azurerm#8717] opened 2020-10-01 23:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We're looking for a way to deploy and manage site extensions (like described [here](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/installsiteextension)) without having to resort to deploying ARM templates with our TF

### New or Affected Resource(s)

* azurerm_app_service
* azurerm_function_app

### Potential Terraform Configuration

```hcl
site_extension {
  name            = 'Datadog.AzureAppServices'
  version         = '0.3.10-prerelease'
  deployment_mode = 'Incremental'
}
```

### References

* Something like [this](https://www.phillipsj.net/posts/applying-azure-app-service-extensions-with-arm/) but using the most recent APIs and a native block-type within the resource

**Comment by tombuildsstuff** [comment] 2020-10-02 06:12
hi @nexxai 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #2328 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2328 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-10-02 06:12 UTC
Labels: duplicate, new-resource, service/app-service
