### ISSUE TITLE
azurerm_kubernetes_cluster default_node_pool works as a collection and shouldn't

### ISSUE THREAD

**Issue by giggio** [terraform-providers/terraform-provider-azurerm#5084] opened 2019-12-05 18:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

````
Terraform v0.12.17
+ provider.azuread v0.7.0
+ provider.azurerm v1.37.0
+ provider.null v2.1.2
````

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

Extra and unrelated information omitted for brevity.

```hcl
resource "azurerm_kubernetes_cluster" "saas" {
  default_node_pool {
    node_count = 1
  }
  lifecycle {
    ignore_changes = [
      default_node_pool.node_count,
    ]
  }
}
```

### Debug Output

Output of `terraform validate`, and also shows up on `terraform plan` and then fails the plan:

```
Error: Invalid operation

  on k8s.tf line 64, in resource "azurerm_kubernetes_cluster" "saas":
  64:       default_node_pool.node_count,

Block type "default_node_pool" is represented by a list of objects, so it must
be indexed using a numeric key, like .default_node_pool[0].
```

### Expected Behavior

Plan and validation succeed.

### Actual Behavior

Plan and validation fails.

### Steps to Reproduce

1. Create a file with the above contents for aks
1. Run `terraform validate` or `terraform plan`

### Important Factoids

There is only one `default_node_pool`, it should not be treated as a collection.

To get it to work, you have to change it to:

```hcl
  lifecycle {
    ignore_changes = [
      default_node_pool.0.node_count,
    ]
  }
```

**Comment by tombuildsstuff** [comment] 2020-01-21 09:41
hi @giggio 

Thanks for opening this issue.

The Terraform SDK supports exposing information in nested blocks using either a (ordered) List (accessible via `foo.0.bar`) or an (unordered) Set (accessible via `foo.23456789.bar`, where `23456789` is the hash code comprised of the values in the list) - unfortunately there's no "block" type which would allow us to expose this information in the manner you're describing. Of the two options available to us here a List allows this information to be referenced by users, thus we use it where we can - whereas a Set isn't designed for information to be referenced (since computing the hash code is non-trivial).

Since this isn't possible in the Terraform SDK at this time unfortunately this is by design and as such I'm going to close this issue for the moment. However should support for "blocks" (for want of a better term) become available in the Terraform SDK we'll circle around and take a look at switching these out where appropriate.

Thanks!

**Closed by tombuildsstuff** 2020-01-21 09:41 UTC
Labels: question, service/kubernetes-cluster

**Comment by giggio** [comment] 2020-01-22 02:39
Ok, I'll open an issue on the Terraform project. Thanks!
