### ISSUE TITLE
Updating to azurerm_windows_virtual_machine_scale_set forces replacement

### ISSUE THREAD

**Issue by hbuckle** [terraform-providers/terraform-provider-azurerm#11359] opened 2021-04-17 06:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.6
hashicorp/azurerm v2.56.0

### Affected Resource(s)

* `azurerm_windows_virtual_machine_scale_set`

### Actual Behaviour

I'm updating from the `azurerm_virtual_machine_scale_set` to `azurerm_windows_virtual_machine_scale_set`

After adding the new resource to the configuration and importing it the plan is showing a forced replacement due to `priority`

```
  # azurerm_windows_virtual_machine_scale_set.node_type["sharedz1"] must be replaced
-/+ resource "azurerm_windows_virtual_machine_scale_set" "node_type" {
      ~ admin_password                                    = (sensitive value)
        admin_username                                    = "azureuser"
        computer_name_prefix                              = "sharedz1"
        do_not_run_extensions_on_overprovisioned_machines = false
      + enable_automatic_updates                          = false
      - encryption_at_host_enabled                        = false -> null
        extensions_time_budget                            = "PT1H30M"
        location                                          = "uksouth"
        max_bid_price                                     = -1
        name                                              = "sharedz1"
        overprovision                                     = false
      ~ platform_fault_domain_count                       = 5 -> (known after apply)
      + priority                                          = "Regular" # forces replacement
```

We've never set priority on these scale sets (it was optional on the old resource), but they are not using spot instances.

Azure PowerShell shows the priority is set to null, and if I try and update it I get an error

```
Update-AzVmss: The specified priority value 'Regular' cannot be applied to the Virtual Machine Scale Set 'sharedz1' since no priority was specified while originally creating the Virtual Machine Scale Set.
```

### Expected Behaviour

Priority should default to null, not Regular

**Comment by hbuckle** [comment] 2021-04-17 08:49
I think I've worked round this by setting `lifecycle.ignore_changes priority` but I now have another issue with inline `extension` blocks because the new resource keeps trying to update the order on every plan. In the old resource `extension` was a set but now it is a list, any reason for that change?

**Comment by hbuckle** [comment] 2021-04-17 09:15
Changing the order of the extensions in the scale set model doesn't appear to change anything on the server side, so I think `extension` definitely needs to be a set not a list

**Comment by ArcturusZhang** [comment] 2021-04-19 05:11
Hi @hbuckle thanks for opening this issue!

I believe this issue is a duplicate of [this one](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8454), therefore I am going to close this one in favor of that. Thank you!

**Closed by ArcturusZhang** 2021-04-19 05:11 UTC
Labels: bug, duplicate, service/vmss
