### ISSUE TITLE
Support for numberOfWorkers  in azurerm_app_service

### ISSUE THREAD

**Issue by jigeay** [terraform-providers/terraform-provider-azurerm#8284] opened 2020-08-28 15:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I want to create an app_service_plan which would be able to scale up, but il will contain an app service which will be unable to scale.
To do that, I want to use the per_site_scaling option of azurerm_app-service-plan but i am unable to find an example or documentation from terraform. 
Microsoft says that to prevent an app service from scaling out, in such a case, we have to set numberOfWorkers to 1 inside the app service, but i can’t find how to do it using terraform.

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by njuCZ** [comment] 2020-09-16 09:55
duplicate as #7502

**Comment by tombuildsstuff** [comment] 2020-09-16 09:58
hi @jigeay 

Thanks for opening this issue :)

Taking a look through as @njuCZ has mentioned this appears to be a duplicate of #7502 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7502 for updates?

Thanks!

**Closed by tombuildsstuff** 2020-09-16 09:58 UTC
Labels: enhancement, service/app-service

**Comment by jigeay** [comment] 2020-09-16 10:27
Hello,
As I stated un #7502 , This issue is aimed to add numberOfWorkers option to *azurerm_app_service*, in order to use properly the per_site_scaling facility of the plan.
#7502 seems to be aimed to add a minimum number of workers for *the whole app_service_plan*, is azurerm_app_service_plan resource. It's not the same thing for me
