### ISSUE TITLE
Support for enabling accelerated writes on HDInsight HBase clusters

### ISSUE THREAD

**Issue by joeyea323** [terraform-providers/terraform-provider-azurerm#9441] opened 2020-11-24 15:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure HDInsight HBase clusters can be provisioned with accelerated writes, however the azurerm_hdinsight_hbase_cluster resource in the azurerm provider does not support setting that option.

### New or Affected Resource(s)

* azurerm_hdinsight_hbase_cluster

### Potential Terraform Configuration

Add `enable_accelerated_writes` as an optional boolean argument in the `azurerm_hdinsight_hbase_cluster` resource.

### References

* https://docs.microsoft.com/en-us/azure/hdinsight/hbase/apache-hbase-accelerated-writes

**Comment by ArcturusZhang** [comment] 2020-11-25 09:56
duplicate of #9142

**Closed by ArcturusZhang** 2020-11-25 09:56 UTC
Labels: duplicate, enhancement, service/hdinsight
