### ISSUE TITLE
KeyVault/Storage account failed to create, cannot find resource group 404 error

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#1423] opened 2018-06-21 09:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
AzureRM Provider 1.7.0

### Affected Resource(s)

azurerm_key_vault
azurerm_storage_account

### Terraform Configuration Files

```
resource "azurerm_storage_account" "storage" {
  name                     = "${var.environment}tnnt${var.number}store"
  resource_group_name      = "${azurerm_resource_group.resource_group.name}"
  location                 = "${var.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  enable_blob_encryption   = "true"
  enable_file_encryption   = "true"

  tags = "${var.tags}"
}

resource "azurerm_key_vault" "keyvault" {
  name                = "${local.name_prefix}-kv"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"

  sku {
    name = "standard"
  }

  tenant_id = "${data.azurerm_client_config.current.tenant_id}"

  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${var.group_id}"

    key_permissions = [
      "get",
      "list",
    ]

    secret_permissions = [
      "get",
      "list",
    ]

    certificate_permissions = [
      "get",
      "list",
    ]
}
```

### Debug Output

Removed original names from log below
I couldn't find anything interesting from the logs, i can forward whatever is needed as we kept them (we run all executions with TRACE)

azurerm_storage_account.storage: Error creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'rg_name' could not be found."
2018/06/17 17:57:22 [ERROR] root.TenantOnBoard: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

azurerm_storage_account.stoage: Error creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'rg_name' could not be found."

### Expected Behavior

Storage account and keyvault created successfully

### Actual Behavior

Keyvault and storage account fail to be created sporadically.

### Steps to Reproduce

1. Create HCL with resource group, keyvault, storage account
2. Try terraform apply until reproducing

### Important Factoids

We didn't get this issue at all for many months, out of the blue this has started for us.
We are on terraform 0.11.7 and we were on azurerm provider 1.4.0. after updating to 1.7.0 we receive it less, but it is still happening, we had 5 nightly executions from which 1 has failed due to this.

### References

#1147 
#49

**Comment by pixelicous** [comment] 2018-06-25 07:05
@tombuildsstuff hey, can you guys assign somebody to look over this? this fails our executions and seems to be related to more issues as well.

Thanks in advance 👍

**Comment by pixelicous** [comment] 2018-07-02 13:57
@tombuildsstuff @katbyte  Hey, this is super critical for us? we have many deployments which fail... can we get some attention on this? we will gladly help where needed..

**Comment by tombuildsstuff** [comment] 2018-07-02 14:43
@pixelicous is it possible to provide a reproducible Terraform configuration here? From what I can see that’s an error from the Azure API

**Comment by pixelicous** [comment] 2018-07-03 08:14
@tombuildsstuff yes.. ill take our configuration and strip out many items, i will try to reproduce this issue using this new configuration, if i see i receive the issue i will provide it here.
Anyways i will update.

Thanks a lot in advance, greatly appreciated, we really need to have a focus on this, it is crashing more on this issue since..

**Comment by tombuildsstuff** [comment] 2018-07-03 08:55
@pixelicous you can also just export a graph of the main configuration using `terraform graph | dot -Tpng > graph.png` (presuming you've got dot installed) which should highlight the same issue; if that's easier in the interim (since this appears to be a dependency issue within the configuration that the Azure API's returning an error for)

**Comment by pixelicous** [comment] 2018-07-03 13:15
@tombuildsstuff I will do that, and i have dot installed.. If it would have been a dependency problem it would have happened everytime, how come it works sometimes and sometimes it doesnt.. it's either API not responding correctly or the reading from the response is not done correctly..

**Comment by pixelicous** [comment] 2018-07-03 13:35
@tombuildsstuff Well im trying to get graph to work.. for some reason it complains that i cannot satisfy the plugin requirements, then i run init, everything is fine, and i run again the graph but again it complains about plugin requirements.. and init finishes green and fine..


> 
> Plugin reinitialization required. Please run "terraform init".
> Reason: Could not satisfy plugin requirements.
> 
> Plugins are external binaries that Terraform uses to access and manipulate
> resources. The configuration provided requires plugins which can't be located,
> don't satisfy the version constraints, or are otherwise incompatible.
> 
> 2 error(s) occurred:
> 
> * provider.azurerm: no suitable version installed
>   version requirements: "= 1.7.0"
>   versions installed: none
> * provider.null: no suitable version installed
>   version requirements: "(any version)"
>   versions installed: none
> 
> Terraform automatically discovers provider requirements from your
> configuration, including providers used in child modules. To see the
> requirements and constraints from each module, run "terraform providers".
> 
> error satisfying plugin requirements
> 
> C:\Terraform>terraform init -upgrade -plugin-dir=".\providerplugins"
> Upgrading modules...
> - module.naming
>   Updating source "git::https://some_server/collection/team_name/_git/terraform//modules/azure/data/naming"
> - module.TenantOnBoard
>   Updating source "./mymodulename"
> 
> Initializing provider plugins...
> 
> The following providers do not have any version constraints in configuration,
> so the latest version was installed.
> 
> To prevent automatic upgrades to new major versions that may contain breaking
> changes, it is recommended to add version = "..." constraints to the
> corresponding provider blocks in configuration, with the constraint strings
> suggested below.
> 
> * provider.null: version = "~> 1.0"
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
>

**Comment by pixelicous** [comment] 2018-07-04 07:59
@tombuildsstuff here you go - [Graph here](https://www.dropbox.com/s/fxwk15arqicpwns/graph.png?dl=0)
Dependency seems to be fine..

**Comment by pixelicous** [comment] 2018-07-09 13:13
@tombuildsstuff does it look ok? What are the next steps?

**Comment by tombuildsstuff** [comment] 2018-12-03 08:41
hi @pixelicous 

>  If it would have been a dependency problem it would have happened everytime, how come it works sometimes and sometimes it doesnt

Not necessarily, depending on the number of other items in the Terraform Configuration this would show up randomly, rather than consistently - as it depends which resources had been provisioned first.

#2270 outlines a similar issue which also contained issues with dependency ordering - as such I believe it should be possible to fix this using [the methods outlined in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2270#issuecomment-436965039) to apply either Implicit or Explicit Dependencies for the resources used in the Terraform Configuration. Would you be able to take a look and see if this works for you?

Since we've not got a full Terraform Configuration which reproduces this issue to be able to diagnose this issue further I'm going to close this issue for the moment - but I believe the underlying issue is that there's a missing dependency in the Terraform Configuration such that Terraform is unsure which order resources should be created in (which is the cause of this inconsistent failing).


Thanks!

**Closed by tombuildsstuff** 2018-12-03 08:41 UTC
Labels: question, service/keyvault
